
ALTER PROCEDURE [dbo].[FIRA_PR_CARGA_ALERT_301_RANKING_DAYTRADE_BVSP] @PREGAO SMALLDATETIME , @AUX INT
AS

/*************************************************************************************************
REGRA DO ALERTA:
Resultado mês > média + 3 desvios padrão
Índice acerto/erro > média + 3 desvios padrão
Quantidade de daytrade > 10
*************************************************************************************************/


 --passo 1
/**********************************
inicio da etapa de verificação
aqui temos o script da base padrao
***********************************/
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ST_ALERT_RANKING_DAYTRADE_BVSP_PADRAO]') AND type in (N'U'))
CREATE TABLE [dbo].[ST_ALERT_RANKING_DAYTRADE_BVSP_PADRAO](
[DATA] [date] NULL,
	[CD_CLIENTE] [int] NOT NULL,
	[ATV_NEG_DT] [varchar](max) NULL,
	[ATV_TOT] [varchar](max) NULL,
	[RSLT_FIN] [numeric](17, 2) NULL,
	[MED_RSLT_FIN] [numeric](17, 2) NULL,
	[DES_RSLT_FIN] [numeric](17, 2) NULL,
	[IND_ACERTO] [numeric](17, 2) NULL,
	[MED_IND_ACERTO] [numeric](17, 2) NULL,
	[DES_IND_ACERTO] [numeric](17, 2) NULL,
	[IND_ERRO] [numeric](17, 2) NULL,
	[MED_IND_ERRO] [numeric](17, 2) NULL,
	[DES_IND_ERRO] [numeric](17, 2) NULL,
	[QTD_DT] [int] NULL,
	[QTD_DIAS_DT] [int] NULL,
	[QTD_DIAS_OPE] [int] NULL,
	[DIAS_PROP] [numeric](17, 2) NULL,
	[VOLUME_DT] [numeric](17, 2) NULL,
	[RENT_PROP] [numeric](17, 5) NULL,
	[VOLUME_TOT] [numeric](17, 2) NULL,
	[DT_PROP] [numeric](17, 2) NULL,
	[CONTRA_IN] [numeric](8, 0) NULL,
	[CONTRA_OUT] [numeric](8, 0) NULL,
	[DAYTRADISTA] [varchar](1) NOT NULL,
	[ALT_FQ] [varchar](1) NOT NULL,
	[RSLT_FIN_ABS] [numeric](17, 2) NULL,
	[CD_PAPEL] [nvarchar](max) NULL,
	[DT_FIRA] DATETIME NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
 

/***************************************************
inicio da comparação entre a tabela
da base padrao fira origem x tabela cliente destino
*****************************************************/
EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo', @src_table='ST_ALERT_RANKING_DAYTRADE_BVSP_PADRAO',
  @schema_name='dbo', @base_table='ST_ALERT_RANKING_DAYTRADE_BVSP',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1;

/******** fim da etapa de verificação ************/


/*********inicio da carga do alerta*******/
--DECLARE @PREGAO SMALLDATETIME, @AUX INT
--SET @PREGAO = '20260105'
--SET @AUX = (SELECT DAY(@PREGAO))
 

DECLARE @INICIO SMALLDATETIME, @FIM SMALLDATETIME, @CD_CLIENTE VARCHAR(50), @DT_INICIO_6M SMALLDATETIME, @DT_FIM_6M SMALLDATETIME 
SET @INICIO = (SELECT MIN(DT_PERIODO) FROM ST_PERIODO WHERE CD_ANOMES = (SELECT MAX(CD_ANOMES) FROM ST_PERIODO WHERE DT_PERIODO = DATEADD(DAY,- @AUX,@PREGAO))) 
SET @FIM    = (SELECT MAX(DT_PERIODO) FROM ST_PERIODO WHERE CD_ANOMES = (SELECT MAX(CD_ANOMES) FROM ST_PERIODO WHERE DT_PERIODO = @INICIO)) 	

SET @DT_INICIO_6M = (SELECT MIN(DT_PERIODO) FROM ST_PERIODO WHERE CD_ANOMES = (SELECT MIN(CD_ANOMES) FROM ST_PERIODO WHERE DT_PERIODO >=DATEADD(MONTH,-6,@INICIO) AND  DT_PERIODO < @INICIO))
SET @DT_FIM_6M    = (SELECT MAX(DT_PERIODO) FROM ST_PERIODO WHERE CD_ANOMES = (SELECT MAX(CD_ANOMES) FROM ST_PERIODO WHERE DT_PERIODO >=DATEADD(MONTH,-6,@INICIO) AND  DT_PERIODO < @INICIO))

PRINT '[PARAMETROS - ALERTA RANKING DAYTRADE]'+'@DT_INICIO_6M:'+CONVERT(VARCHAR,@DT_INICIO_6M,23)+' @DT_FIM_6M:'+CONVERT(VARCHAR,@DT_FIM_6M,23)+' @INICIO:'+CONVERT(VARCHAR,@INICIO,23)+' @FIM:'+CONVERT(VARCHAR,@FIM,23)    
	
/*
	INICIO - DAYTRADE RESUMO
*/

DROP TABLE IF EXISTS #QDT_DAYTRADE_IN;
			SELECT
				CD_CLIENTE_COMPROU,
				CD_NEGOCIO_COMPROU,
				DT_PREGAO_COMPROU,
				SUM(CASE WHEN CD_NATOPE = 'C' THEN 1 ELSE 0 END) AS QTD_COMPRAS,
				SUM(CASE WHEN CD_NATOPE = 'V' THEN 1 ELSE 0 END) AS QTD_VENDAS
            INTO #QDT_DAYTRADE_IN
			FROM
				ST_DAYTRADE_DETALHE
			WHERE
			DT_PREGAO_COMPROU >=@INICIO
			AND DT_PREGAO_COMPROU <=@FIM
			and QT_DAYTRADE > 0 
			GROUP BY
				CD_CLIENTE_COMPROU,
				CD_NEGOCIO_COMPROU,
				DT_PREGAO_COMPROU
		


		DROP TABLE IF EXISTS #QDT_DAYTRADE_OUT;
		SELECT
			CD_CLIENTE_COMPROU,
			CD_NEGOCIO_COMPROU,
			DT_PREGAO_COMPROU,
			 CASE 
			WHEN QTD_COMPRAS > 0 AND QTD_VENDAS > 0 THEN 
            CASE 
                WHEN QTD_COMPRAS > QTD_VENDAS THEN QTD_VENDAS
                WHEN QTD_VENDAS > QTD_COMPRAS THEN QTD_COMPRAS
                ELSE QTD_COMPRAS 
            END
			ELSE 0
			END AS QTD
			INTO #QDT_DAYTRADE_OUT
		FROM
			#QDT_DAYTRADE_IN
		ORDER BY
			CD_CLIENTE_COMPROU,
			CD_NEGOCIO_COMPROU,
			DT_PREGAO_COMPROU;
----------------------------------------------------------------------

DROP TABLE IF EXISTS #T1;	
	SELECT CD_CLIENTE_COMPROU
		 ,b.CD_ANOMES
		 , SUM(VL_FINANC) FINAN
		 , (SELECT 		
				CAST(SUM(ACERTO) AS FLOAT) +		
				CAST(SUM(PERDA) AS FLOAT) +		
				CAST(SUM(EMPATE) AS FLOAT) QTD_DAYTRADES		
				FROM(		
					SELECT CD_CLIENTE, 		
					CASE WHEN VL_ACERTO > 0 THEN 1 ELSE 0 END ACERTO,		
					CASE WHEN VL_ACERTO < 0 THEN 1 ELSE 0 END PERDA,		
					CASE WHEN VL_ACERTO = 0 THEN 1 ELSE 0 END EMPATE		
					FROM(		
						SELECT DT_PREGAO_COMPROU DT_PREGAO, 		
						CD_CLIENTE_COMPROU CD_CLIENTE,CD_NEGOCIO_COMPROU CD_NEGOCIO, 		
						SUM((CASE WHEN CD_NATOPE = 'C' THEN -1 ELSE 1 END)*QT_DAYTRADE*VL_NEGOCIO_COMPROU) VL_ACERTO 		
						FROM ST_DAYTRADE_DETALHE XX		
						WHERE XX.DT_PREGAO_COMPROU >= @INICIO		
						AND XX.DT_PREGAO_COMPROU <= @FIM
						AND XX.CD_CLIENTE_COMPROU = A2.CD_CLIENTE_COMPROU
						AND XX.QT_DAYTRADE > 0		
						GROUP BY DT_PREGAO_COMPROU, CD_CLIENTE_COMPROU, CD_NEGOCIO_COMPROU	
						) X 		
					) X2		
				GROUP BY CD_CLIENTE) QTD_DAYTRADES
		 , (SELECT CAST(SUM(X.QTD_DIAS_DAYTRADE) AS FLOAT) 
			  FROM (SELECT A.CD_CLIENTE_COMPROU
						 , A.DT_PREGAO_COMPROU 
						 , COUNT(DISTINCT A.DT_PREGAO_COMPROU) AS QTD_DIAS_DAYTRADE
					  FROM ST_DAYTRADE_DETALHE A		
				     WHERE A.CD_CLIENTE_COMPROU = A2.CD_CLIENTE_COMPROU 		
					   AND A.DT_PREGAO_COMPROU >=@INICIO 
					   AND A.DT_PREGAO_COMPROU <=@FIM		
					   AND QT_DAYTRADE > 0		
				  GROUP BY A.CD_CLIENTE_COMPROU
					     , A.DT_PREGAO_COMPROU) 
				   X) QTD_DIAS_DAYTRADE	
				,SUM(ABS(VL_COMPRA) + ABS(VL_VENDA)) VOLUME_DAYTRADE
		INTO #T1
		FROM ST_DAYTRADE_RESUMO A2	
		left join ST_PERIODO b 
		on a2.DT_PREGAO_COMPROU = b.DT_PERIODO
	   WHERE DT_PREGAO_COMPROU >=@INICIO 
	     AND DT_PREGAO_COMPROU <=@FIM		
	   GROUP BY CD_CLIENTE_COMPROU,b.CD_ANOMES;	

----------------------------------------------------------------------		
--TODOS DAYTRADES POR PAPEL E DIA

 DROP TABLE IF EXISTS #T11;

		SELECT DT_PREGAO_COMPROU  AS DT_PREGAO
			 , CD_CLIENTE_COMPROU AS CD_CLIENTE
			 , CD_NEGOCIO_COMPROU AS CD_NEGOCIO
			 , SUM((CASE WHEN CD_NATOPE = 'C' THEN -1 ELSE 1 END) * QT_DAYTRADE * VL_NEGOCIO_COMPROU) AS VL_ACERTO 
			 , SUM((CASE WHEN CD_NATOPE = 'C' THEN  1 ELSE 1 END) * QT_DAYTRADE * VL_NEGOCIO_COMPROU) AS VL_DAYTRADE
		  INTO #T11
		  FROM ST_DAYTRADE_DETALHE
		 WHERE DT_PREGAO_COMPROU >= @INICIO
		   AND DT_PREGAO_COMPROU <= @FIM
	  GROUP BY DT_PREGAO_COMPROU
			 , CD_CLIENTE_COMPROU
			 , CD_NEGOCIO_COMPROU

----------------------------------------------------------------------
 
 DROP TABLE IF EXISTS #T22;

	    SELECT CD_CLIENTE
			 , SUM(VL_ACERTO)   AS VL_FINAN  
			 , SUM(VL_DAYTRADE) AS VOLUME_DAYTRADE
		  INTO #T22  
		  FROM #T11
	  GROUP BY CD_CLIENTE	

----------------------------------------------------------------------

DROP TABLE IF EXISTS #T2;

	   SELECT CD_CLIENTE
			, CAST(SUM(ACERTO) AS FLOAT) AS ACERTO
			, CAST(SUM(PERDA) AS FLOAT)  AS PERDA
			, CAST(SUM(EMPATE) AS FLOAT) AS EMPATE	
		INTO #T2
		FROM (		
				SELECT CD_CLIENTE
					 , CASE WHEN VL_ACERTO > 0 THEN 1 ELSE 0 END ACERTO
					 , CASE WHEN VL_ACERTO < 0 THEN 1 ELSE 0 END PERDA
					 , CASE WHEN VL_ACERTO = 0 THEN 1 ELSE 0 END EMPATE		
				  FROM (		
					    SELECT DT_PREGAO_COMPROU DT_PREGAO,     
						CD_CLIENTE_COMPROU CD_CLIENTE,CD_NEGOCIO_COMPROU CD_NEGOCIO,     
						SUM((CASE WHEN CD_NATOPE = 'C' THEN -1 ELSE 1 END) *QT_DAYTRADE*VL_NEGOCIO_COMPROU)  VL_ACERTO   
						FROM ST_DAYTRADE_DETALHE    
						WHERE DT_PREGAO_COMPROU >= @INICIO    
						AND DT_PREGAO_COMPROU <= @FIM    
						and QT_DAYTRADE > 0
						GROUP BY DT_PREGAO_COMPROU, CD_CLIENTE_COMPROU, CD_NEGOCIO_COMPROU  
						) X 		
			 ) X2		
	 GROUP BY CD_CLIENTE	
		
----------------------------------------------------------------------

  DROP TABLE IF EXISTS #RESULTADO_DAYTRADE;

		 SELECT T1.CD_ANOMES
			  , T1.CD_CLIENTE_COMPROU	
			  , T1.QTD_DAYTRADES
			  , T22.VL_FINAN AS RESULTADO_FINANCEIRO
			  , ABS(T22.VL_FINAN) AS RESULTADO_FINANCEIRO_ABS
			  , T22.VOLUME_DAYTRADE
			  , T2.ACERTO
			  , T2.PERDA		
			  , T2.EMPATE	
			  , T1.QTD_DIAS_DAYTRADE
			  , CAST(CAST(ACERTO AS NUMERIC(17,2)) / T1.QTD_DAYTRADES /*QTD_DIAS_DAYTRADE*/ AS NUMERIC(17,2))  INDICE_ACERTO
			  , CAST(CAST(PERDA  AS NUMERIC(17,2)) / T1.QTD_DAYTRADES /*QTD_DIAS_DAYTRADE*/ AS NUMERIC(17,2))  INDICE_ERRO
		   INTO #RESULTADO_DAYTRADE
		   FROM #T1 T1 
LEFT OUTER JOIN #T2 T2 
			 ON T1.CD_CLIENTE_COMPROU = T2.CD_CLIENTE
LEFT OUTER JOIN #T22 T22 
	         ON T1.CD_CLIENTE_COMPROU = T22.CD_CLIENTE		
	      WHERE T1.QTD_DAYTRADES IS NOT NULL
	   ORDER BY T1.CD_CLIENTE_COMPROU




/*
	FIM - DAYTRADE RESUMO
*/
	

/*
	INICIO - DAYTRADE RESUMO HISTORICO
*/

----------------------------------------------------------------------

DROP TABLE IF EXISTS #T1H2;

	   SELECT  A.CD_CLIENTE_COMPROU 
			 , B.CD_ANOMES 
			 , COUNT(DISTINCT A.CD_NEGOCIO_COMPROU) AS QTD_DAYTRADES 
			 , COUNT(DISTINCT A.DT_PREGAO_COMPROU)  AS QTD_DIAS_DAYTRADE 
		  INTO #T1H2
	      FROM ST_DAYTRADE_DETALHE A
	 LEFT JOIN ST_PERIODO B 
		    ON A.DT_PREGAO_COMPROU = B.DT_PERIODO
	     WHERE A.DT_PREGAO_COMPROU >= @DT_INICIO_6M 
		   AND A.DT_PREGAO_COMPROU <= @DT_FIM_6M		
		   AND QT_DAYTRADE > 0	
	  GROUP BY A.CD_CLIENTE_COMPROU
			 , B.CD_ANOMES
		
----------------------------------------------------------------------		
--TODOS DAYTRADES POR PAPEL E DIA

 DROP TABLE IF EXISTS #T11H2;

		SELECT DT_PREGAO_COMPROU  AS DT_PREGAO
			 , CD_CLIENTE_COMPROU AS CD_CLIENTE
			 , CD_NEGOCIO_COMPROU AS CD_NEGOCIO
			 , SUM((CASE WHEN CD_NATOPE = 'C' THEN -1 ELSE 1 END) * QT_DAYTRADE * VL_NEGOCIO_COMPROU) AS VL_ACERTO 
			 , SUM((CASE WHEN CD_NATOPE = 'C' THEN  1 ELSE 1 END) * QT_DAYTRADE * VL_NEGOCIO_COMPROU) AS VL_DAYTRADE
		  INTO #T11H2
		  FROM ST_DAYTRADE_DETALHE
		 WHERE DT_PREGAO_COMPROU >= @DT_INICIO_6M
		   AND DT_PREGAO_COMPROU <= @DT_FIM_6M
	  GROUP BY DT_PREGAO_COMPROU
			 , CD_CLIENTE_COMPROU
			 , CD_NEGOCIO_COMPROU

----------------------------------------------------------------------
 DROP TABLE IF EXISTS #T22H2;

	    SELECT CD_CLIENTE
			 , B.CD_ANOMES
			 , SUM(VL_ACERTO)   AS VL_FINAN  
			 , SUM(VL_DAYTRADE) AS VOLUME_DAYTRADE
		  INTO #T22H2  
		  FROM #T11H2 A 
	 LEFT JOIN ST_PERIODO B 
			ON A.DT_PREGAO = B.DT_PERIODO
	  GROUP BY CD_CLIENTE,B.CD_ANOMES	

----------------------------------------------------------------------

DROP TABLE IF EXISTS #T2H2;

	   SELECT CD_CLIENTE
			, CD_ANOMES
			, CAST(SUM(ACERTO) AS FLOAT) AS ACERTO
			, CAST(SUM(PERDA) AS FLOAT)  AS PERDA
			, CAST(SUM(EMPATE) AS FLOAT) AS EMPATE	
		INTO #T2H2
		FROM (		
				SELECT CD_CLIENTE
					 , CD_ANOMES
					 , CASE WHEN VL_ACERTO > 0 THEN 1 ELSE 0 END ACERTO
					 , CASE WHEN VL_ACERTO < 0 THEN 1 ELSE 0 END PERDA
					 , CASE WHEN VL_ACERTO = 0 THEN 1 ELSE 0 END EMPATE		
				  FROM (		
						 SELECT DT_PREGAO_COMPROU  AS DT_PREGAO
							  , CD_CLIENTE_COMPROU AS CD_CLIENTE
							  , SUM((CASE WHEN CD_NATOPE = 'C' THEN -1 ELSE 1 END) * QT_DAYTRADE * VL_NEGOCIO_COMPROU) AS VL_ACERTO 		
						   FROM ST_DAYTRADE_DETALHE 		
						  WHERE DT_PREGAO_COMPROU >= @DT_INICIO_6M		
						    AND DT_PREGAO_COMPROU <= @DT_FIM_6M		
						    AND QT_DAYTRADE > 0		
					   GROUP BY DT_PREGAO_COMPROU
						      , CD_CLIENTE_COMPROU
						) X 	LEFT JOIN ST_PERIODO B 
									   ON X.DT_PREGAO = B.DT_PERIODO	
			 ) X2		
	 GROUP BY CD_CLIENTE	,CD_ANOMES
	
----------------------------------------------------------------------

  DROP TABLE IF EXISTS #RESULTADO_DAYTRADEH2;

		 SELECT T1.CD_CLIENTE_COMPROU	--,T1.CD_ANOMES
			  , AVG(T22.VL_FINAN)   AS MEDIA_RESULTADO_FINANCEIRO
			  , ISNULL(STDEV(T22.VL_FINAN),0) AS DESVIO_RESULTADO_FINANCEIRO
			  , AVG(CAST(CAST(ACERTO AS NUMERIC(17,2)) / QTD_DIAS_DAYTRADE AS NUMERIC(17,2))) MEDIA_INDICE_ACERTO
			  , ISNULL(STDEV(CAST(CAST(ACERTO AS NUMERIC(17,2)) / QTD_DIAS_DAYTRADE AS NUMERIC(17,2))),0) DESVIO_INDICE_ACERTO
			  , AVG(CAST(CAST(PERDA  AS NUMERIC(17,2)) / QTD_DIAS_DAYTRADE AS NUMERIC(17,2)))  MEDIA_INDICE_ERRO
			  , ISNULL(STDEV(CAST(CAST(PERDA  AS NUMERIC(17,2)) / QTD_DIAS_DAYTRADE AS NUMERIC(17,2))),0)  DESVIO_INDICE_ERRO
		   INTO #RESULTADO_DAYTRADEH2 

		   FROM #T1H2 T1 
LEFT OUTER JOIN #T2H2 T2 
			 ON T1.CD_CLIENTE_COMPROU = T2.CD_CLIENTE
			 AND T1.CD_ANOMES = T2.CD_ANOMES
LEFT OUTER JOIN #T22H2 T22 
	         ON T1.CD_CLIENTE_COMPROU = T22.CD_CLIENTE	
			AND T1.CD_ANOMES = T22.CD_ANOMES
	       WHERE T1.QTD_DAYTRADES IS NOT NULL 		   
		
	   GROUP BY T1.CD_CLIENTE_COMPROU

/*
	FIM - DAYTRADE RESUMO HISTORICO ACERTO E PERDA
*/


/*
	INICIO - DAYTRADE PAPEL
*/

----------------------------------------------------------------------

 DROP TABLE IF EXISTS #T1_PAPEL;

		SELECT DT_PREGAO_COMPROU  AS DT_PREGAO
			 , CD_CLIENTE_COMPROU AS CD_CLIENTE
			 , CD_NEGOCIO_COMPROU AS CD_NEGOCIO
			 , SUM((CASE WHEN CD_NATOPE = 'C' THEN -1 ELSE 1 END) * QT_DAYTRADE * VL_NEGOCIO_COMPROU)  VL_ACERTO 
		  INTO #T1_PAPEL
		  FROM ST_DAYTRADE_DETALHE		
		 WHERE DT_PREGAO_COMPROU >= @INICIO		
		   AND DT_PREGAO_COMPROU <= @FIM		
	  GROUP BY DT_PREGAO_COMPROU
		     , CD_CLIENTE_COMPROU
			 , CD_NEGOCIO_COMPROU	
		
----------------------------------------------------------------------
--ACERTO POR PAPEL	
 DROP TABLE IF EXISTS #T3_PAPEL;

		SELECT CD_CLIENTE
			 , CD_NEGOCIO 
			 , SUM(CASE WHEN VL_ACERTO > 0 THEN 1 ELSE 0 END) VL_ACERTO
			 , SUM(CASE WHEN VL_ACERTO < 0 THEN 1 ELSE 0 END) VL_PERDA
			 , SUM(CASE WHEN VL_ACERTO = 0 THEN 1 ELSE 0 END) VL_EMPATE
			 , SUM(VL_ACERTO) VL_FINAN
		  INTO #T3_PAPEL
		  FROM #T1_PAPEL		
	  GROUP BY CD_CLIENTE
		     , CD_NEGOCIO	
		
----------------------------------------------------------------------
--FINANCEIRO TOTAL	
DROP TABLE IF EXISTS #T2_PAPEL;

	   SELECT CD_CLIENTE
			, SUM(VL_ACERTO) VL_FINAN  
		 INTO #T2_PAPEL 
		 FROM #T1_PAPEL		
	 GROUP BY CD_CLIENTE		

----------------------------------------------------------------------			
-- QUERY FINAL	
DROP TABLE IF EXISTS #RESULTADO_DAYTRADE_PAPEL;

		SELECT T3.CD_CLIENTE 
			 , T3.CD_NEGOCIO 
			 , T3.VL_FINAN [RESULTADO_FINANCEIRO]
			 , T2.VL_FINAN [RESULTADO_FINANCEIRO_TOTAL]
			 , T3.VL_ACERTO [ACERTO] 
			 , T3.VL_EMPATE [EMPATE]
			 , T3.VL_PERDA  [PERDA]	
		INTO #RESULTADO_DAYTRADE_PAPEL
		FROM #T2_PAPEL T2, #T3_PAPEL T3		
	   WHERE T2.CD_CLIENTE = T3.CD_CLIENTE;		
	
/*
	FIM - DAYTRADE PAPEL 
*/
	DROP TABLE IF EXISTS #TD_ATIVOS_NEG_A;

		  SELECT 
		DISTINCT CD_CLIENTE			   
			   , CD_PAPEL			   
			INTO #TD_ATIVOS_NEG_A
			FROM ST_MESA_BVSP 
		   WHERE DT_PERIODO >= @INICIO 
			 AND DT_PERIODO <= @FIM;

	DROP TABLE IF EXISTS #TD_ATIVOS_NEG_B;

		 SELECT CD_CLIENTE 
		      , STUFF((
			    SELECT ', ' + P.CD_PAPEL
			    FROM #TD_ATIVOS_NEG_A P
			    WHERE P.CD_CLIENTE = A.CD_CLIENTE
			    FOR XML PATH('')
			), 1, 2, '') AS ATIVOS_TOTAL 
		   INTO #TD_ATIVOS_NEG_B
		   FROM #TD_ATIVOS_NEG_A A 
	   GROUP BY CD_CLIENTE

/*
	INICIO - IN/OUT
*/
 DROP TABLE IF EXISTS #IN_OUT_A;	

		SELECT CD_CONTRAPARTE_COMPROU
			 , CD_CLIENTE_COMPROU					 
			 , CD_NATOPE
			 , CD_CONTRAPARTE_COMPROU_DE			 
			 , CD_CLIENTE_COMPROU_DE			 
			 , CD_NEGOCIO_COMPROU 
			 , QT_DAYTRADE
			 , VL_NEGOCIO_COMPROU
			 , CASE WHEN CD_CLIENTE_COMPROU_DE IS NULL THEN 'OUT' ELSE 'IN' END IND_CONTRAPARTE
		 INTO #IN_OUT_A
		 FROM ST_DAYTRADE_DETALHE 
		WHERE DT_PREGAO_COMPROU >= @INICIO 
		  AND DT_PREGAO_COMPROU <= @FIM;


  DROP TABLE IF EXISTS #IN_OUT_B;

		 SELECT CD_CONTRAPARTE_COMPROU_DE
			  , CD_CLIENTE_COMPROU 
			 , SUM((CASE WHEN CD_NATOPE = 'C' THEN -1 ELSE 1 END) * QT_DAYTRADE * VL_NEGOCIO_COMPROU) RESULTADO
			  ,'OUT' IND_CONTRAPARTE
		   INTO #IN_OUT_B
		   FROM #IN_OUT_A
		  WHERE IND_CONTRAPARTE = 'OUT'
		  GROUP BY CD_CONTRAPARTE_COMPROU_DE
		         , CD_CLIENTE_COMPROU
		 
		 UNION ALL

		 SELECT CD_CLIENTE_COMPROU_DE
			  , CD_CLIENTE_COMPROU
			  , SUM((CASE WHEN CD_NATOPE = 'C' THEN -1 ELSE 1 END) * QT_DAYTRADE * VL_NEGOCIO_COMPROU) RESULTADO
			  ,'IN' IND_CONTRAPARTE
		   FROM #IN_OUT_A
		  WHERE IND_CONTRAPARTE = 'IN'
		  GROUP BY CD_CLIENTE_COMPROU_DE
				 , CD_CLIENTE_COMPROU;
			
	DROP TABLE IF EXISTS  #IN_OUT_C;
		   SELECT * INTO #IN_OUT_C FROM #IN_OUT_B;
	
	DROP TABLE IF EXISTS #IN;
  
		  SELECT CD_CLIENTE_COMPROU 
			   , CD_CONTRAPARTE_COMPROU_DE
			   , RESULTADO
			   , IND_CONTRAPARTE
			   , ROW_NUMBER() OVER (PARTITION BY CD_CLIENTE_COMPROU ORDER BY RESULTADO DESC) RANKING
			INTO #IN
		    FROM #IN_OUT_C
		   WHERE IND_CONTRAPARTE = 'IN';
 
		

	DROP TABLE IF EXISTS #OUT;

		  SELECT CD_CLIENTE_COMPROU 
			   , CD_CONTRAPARTE_COMPROU_DE
			   , RESULTADO
			   , IND_CONTRAPARTE
			   , ROW_NUMBER() OVER (PARTITION BY CD_CLIENTE_COMPROU ORDER BY RESULTADO DESC) RANKING
			INTO #OUT
		    FROM #IN_OUT_C
		   WHERE IND_CONTRAPARTE = 'OUT';

    DROP TABLE IF EXISTS #TODOS;

		   SELECT CD_CLIENTE_COMPROU INTO #TODOS 
			 FROM #IN 

		    UNION

		   SELECT CD_CLIENTE_COMPROU 
		     FROM #OUT;

	DROP TABLE IF EXISTS #IN_OUT_VOLUME;

		   SELECT A.CD_CLIENTE_COMPROU
			    , B.CD_CONTRAPARTE_COMPROU_DE CONTRAPARTE_IN 
				, C.CD_CONTRAPARTE_COMPROU_DE CONTRAPARTE_OUT
			  INTO #IN_OUT_VOLUME
			 FROM #TODOS A 
		LEFT JOIN (SELECT * FROM #IN WHERE RANKING = 1) B 
			   ON A.CD_CLIENTE_COMPROU = B.CD_CLIENTE_COMPROU 
		LEFT JOIN (SELECT * FROM #OUT WHERE RANKING = 1) C 
			   ON A.CD_CLIENTE_COMPROU = C.CD_CLIENTE_COMPROU 


/*
	FIM - IN/OUT
*/

/*
	INICIO - DIAS OPERADOS
*/
   DROP TABLE IF EXISTS #DIAS_OPERADOS;
		  
		  SELECT 
		DISTINCT CD_CLIENTE 
			   , COUNT(DISTINCT DT_PERIODO) QT_DIAS_OPERADOS
			INTO #DIAS_OPERADOS
			FROM ST_MESA_BVSP 
		   WHERE DT_PERIODO >= @INICIO
			 AND DT_PERIODO <= @FIM
		GROUP BY CD_CLIENTE;
/*
	FIM - DIAS OPERADOS
*/


/*
	INICIO - VOLUME NEGOCIADO
*/

 DROP TABLE IF EXISTS #VOLUME_NEG;

		SELECT CD_CLIENTE
			 , SUM(ISNULL(VL_TOTNEG,0))		   AS VOL_MES_ATUAL
			 , SUM(ISNULL(QT_MULTIPLICADOR,0)) AS QTD_MES
		 INTO #VOLUME_NEG
		 FROM ST_CORRETAGEM_ORDEM A
		 
		WHERE DT_NEGOCIO >= @INICIO
		  AND DT_NEGOCIO <= @FIM
	 GROUP BY CD_CLIENTE;

/*
	FIM - VOLUME NEGOCIADO
*/



DELETE FROM ST_ALERT_RANKING_DAYTRADE_BVSP WHERE DATA =  DATEADD(DAY,- @AUX,@PREGAO);

INSERT INTO ST_ALERT_RANKING_DAYTRADE_BVSP(DATA,CD_CLIENTE,ATV_NEG_DT,ATV_TOT,RSLT_FIN,MED_RSLT_FIN,DES_RSLT_FIN,IND_ACERTO
										  ,MED_IND_ACERTO,DES_IND_ACERTO,IND_ERRO,MED_IND_ERRO,DES_IND_ERRO,QTD_DT,QTD_DIAS_DT,QTD_DIAS_OPE,DIAS_PROP,VOLUME_DT,RENT_PROP
										  ,VOLUME_TOT,DT_PROP,CONTRA_IN,CONTRA_OUT,DAYTRADISTA,ALT_FQ,RSLT_FIN_ABS,CD_PAPEL)   
	  SELECT 
	DISTINCT  DATEADD(DAY,- @AUX,@PREGAO)																				  AS DATA
			, A.CD_CLIENTE_COMPROU																						  AS CD_CLIENTE
			,STUFF(
			(SELECT ', ' + P.CD_NEGOCIO
			 FROM #RESULTADO_DAYTRADE_PAPEL P
			 WHERE P.CD_CLIENTE = A.CD_CLIENTE_COMPROU
			 FOR XML PATH('')), 1, 2, '')																				  AS ATV_NEG_DT --ativos_daytrade
		   , C.ATIVOS_TOTAL																								  AS ATV_TOT	--ativos_total 
		   , CAST(A.RESULTADO_FINANCEIRO AS NUMERIC(17,2))																  AS RSLT_FIN --resultado financeiro
		   , ABS(CAST(G.MEDIA_RESULTADO_FINANCEIRO AS NUMERIC(17,2)))													  AS MED_RSLT_FIN -- MEDIA_RESULTADO_FINANCEIRO
		   , ABS(CAST(G.DESVIO_RESULTADO_FINANCEIRO AS NUMERIC(17,2)))													  AS DES_RSLT_FIN --DESVIO_RESULTADO_FINANCEIRO
		   , CAST(A.INDICE_ACERTO AS NUMERIC(17,2))																		  AS IND_ACERTO --INDICE_ACERTO
		   , CAST(G.MEDIA_INDICE_ACERTO AS NUMERIC(17,2))																  AS MED_IND_ACERTO --MEDIA_INDICE_ACERTO
		   , CAST(G.DESVIO_INDICE_ACERTO AS NUMERIC(17,2))																  AS DES_IND_ACERTO --DESVIO_INDICE_ACERTO
		   , CAST(A.INDICE_ERRO AS NUMERIC(17,2))																		  AS IND_ERRO --INDICE_ERRO
		   , CAST(G.MEDIA_INDICE_ERRO AS NUMERIC(17,2))																	  AS MED_IND_ERRO --MEDIA_INDICE_ERRO
		   , CAST(G.DESVIO_INDICE_ERRO  AS NUMERIC(17,2))																  AS DES_IND_ERRO--DESVIO_INDICE_ERRO
		   , A.QTD_DAYTRADES																							  AS QTD_DT
		   , A.QTD_DIAS_DAYTRADE 																						  AS QTD_DIAS_DT	   
		   , E.QT_DIAS_OPERADOS																							  AS QTD_DIAS_OPE
		   , cast(cast(a.QTD_DIAS_DAYTRADE as numeric(17,2))/cast(e.QT_DIAS_OPERADOS as numeric(17,2))as numeric(17,2))   AS DIAS_PROP
		   , VOLUME_DAYTRADE																							  AS VOLUME_DT
		   , CAST((A.RESULTADO_FINANCEIRO / VOLUME_DAYTRADE)	AS NUMERIC(17,5))										  AS RENT_PROP
		   , F.VOL_MES_ATUAL 																							  AS VOLUME_TOT	  
		   , CAST((VOLUME_DAYTRADE / VOL_MES_ATUAL ) AS NUMERIC(17,2))													  AS DT_PROP --DAYTRADE_PROP
		   , D.CONTRAPARTE_IN																							  AS CONTRA_IN --CONTRAPARTE_IN
		   , D.CONTRAPARTE_OUT																							  AS CONTRA_OUT --CONTRAPARTE_OUT
		   , CASE WHEN (QTD_DIAS_DAYTRADE / QT_DIAS_OPERADOS) >= 0.7 THEN 'S' ELSE 'N' END								  AS DAYTRADISTA
		   , CASE WHEN QTD_DIAS_DAYTRADE > 12 THEN 'S' ELSE 'N' END														  AS ALT_FQ --ALTA_FREQUENCIA
		   , CAST(RESULTADO_FINANCEIRO_ABS  AS NUMERIC(17,2))														      AS RSLT_FIN_ABS --resultado financeiro ABSOLUTO
		   , C.ATIVOS_TOTAL																								  AS CD_PAPEL --papel concatenados, para alerta oscilação
		

		FROM #RESULTADO_DAYTRADE A 
   LEFT JOIN #RESULTADO_DAYTRADE_PAPEL B 
		  ON A.CD_CLIENTE_COMPROU = B.CD_CLIENTE
   LEFT JOIN #TD_ATIVOS_NEG_B C
		  ON A.CD_CLIENTE_COMPROU = C.CD_CLIENTE
   LEFT JOIN #IN_OUT_VOLUME D
		  ON A.CD_CLIENTE_COMPROU = D.CD_CLIENTE_COMPROU
   LEFT JOIN #DIAS_OPERADOS E
		  ON A.CD_CLIENTE_COMPROU = E.CD_CLIENTE
   LEFT JOIN #VOLUME_NEG F 
		  ON A.CD_CLIENTE_COMPROU = F.CD_CLIENTE
   LEFT JOIN #RESULTADO_DAYTRADEH2 G
		  ON A.CD_CLIENTE_COMPROU = G.CD_CLIENTE_COMPROU
   
   WHERE
	QTD_DAYTRADES > 10
and (
      (isnull(A.RESULTADO_FINANCEIRO,0) > 0
       and isnull(A.RESULTADO_FINANCEIRO,0) > (isnull(G.MEDIA_RESULTADO_FINANCEIRO,0) + 3* isnull(G.DESVIO_RESULTADO_FINANCEIRO,0))
       and isnull(A.INDICE_ACERTO,0) >= (isnull(G.MEDIA_INDICE_ACERTO,0) + 3* isnull(G.DESVIO_INDICE_ACERTO,0)))
   or (isnull(A.RESULTADO_FINANCEIRO,0) < 0
       and isnull(A.RESULTADO_FINANCEIRO,0) < (isnull(G.MEDIA_RESULTADO_FINANCEIRO,0) - 3* isnull(G.DESVIO_RESULTADO_FINANCEIRO,0))
       and isnull(A.INDICE_ERRO,0) >= (isnull(G.MEDIA_INDICE_ERRO,0) + 3* isnull(G.DESVIO_INDICE_ERRO,0)))
    )

/******* fim do processo de carga do alerta **********/
-- ================================================
-- Marca DT_FIRA para registros carregados (fallback)
-- ================================================
DECLARE @__dt_fira_now DATETIME = GETDATE();
IF COL_LENGTH(N'dbo.ST_ALERT_RANKING_DAYTRADE_BVSP', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE [dbo].ST_ALERT_RANKING_DAYTRADE_BVSP
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL;
END

--passo 3
/***** limpa a tabela do banco para nao ficar sujeira ******/
DROP TABLE IF EXISTS ST_ALERT_RANKING_DAYTRADE_BVSP_PADRAO 

