CREATE PROCEDURE [dbo].[PR_NEGOCIO_VS_CORRETORA] @INICIO SMALLDATETIME, @FIM SMALLDATETIME, @CD_CLIENTE VARCHAR(10)	,@QTDPORPAGINA INT	, @PAGINA INT
WITH RECOMPILE
AS		


--DECLARE @PAGINA        INT =1
--DECLARE @QTDPORPAGINA INT = 100000
--DECLARE @INICIO SMALLDATETIME, @FIM SMALLDATETIME, @CD_CLIENTE VARCHAR(10)
--SET @INICIO='20230101'		
--SET @FIM='20230131'		
--SET @CD_CLIENTE=''	
 
SET ARITHABORT OFF 		
SET ANSI_WARNINGS OFF		
		
;WITH #T1	 AS (
SELECT ST.CD_CLIENTE, SUM(QT_MULTIPLICADOR) QTD_NEGOCIOS 	
FROM ST_CORRETAGEM_ORDEM ST  (nolock)		
WHERE	ST.DT_NEGOCIO>=@INICIO AND ST.DT_NEGOCIO <=@FIM	
AND CD_CLIENTE LIKE (CASE WHEN ISNULL(@CD_CLIENTE,'')='' THEN ST.CD_CLIENTE ELSE CONVERT(INT,@CD_CLIENTE) END)
GROUP BY ST.CD_CLIENTE		
)	
 		
		
--QUERY FINAL		
SELECT 
ST.CD_CLIENTE,
C.NM_CLIENTE, 
D.NM_CORRET, 
FORMAT(ISNULL(SUM(ST.QT_MULTIPLICADOR),0),'#,0','PT-BR') QTD_NEGOCIOS,		
FORMAT(ISNULL(#T1.QTD_NEGOCIOS,0),'#,0','PT-BR') QTD_TOT, 		
ISNULL(FORMAT(SUM(CAST(ST.QT_MULTIPLICADOR AS FLOAT)) / CAST(#T1.QTD_NEGOCIOS AS FLOAT),'P2','PT-BR'),0) PERC		
FROM 
ST_CORRETAGEM_ORDEM ST (nolock) 
LEFT JOIN #T1 ON ST.CD_CLIENTE = #T1.CD_CLIENTE
LEFT JOIN ST_CORRETORA D (nolock) ON ST.CD_CONTRAPARTE = D.CD_CORRET
LEFT JOIN (SELECT DISTINCT CD_CLIENTE,NM_CLIENTE FROM V_CLIENTE_TODOS (nolock)) C ON ST.CD_CLIENTE = C.CD_CLIENTE
    
WHERE	ST.DT_NEGOCIO>=@INICIO AND ST.DT_NEGOCIO <=@FIM		
    AND ST.CD_CLIENTE LIKE (CASE WHEN ISNULL(@CD_CLIENTE,'')='' THEN ST.CD_CLIENTE ELSE CONVERT(INT,@CD_CLIENTE) END)		
		
GROUP BY ST.CD_CLIENTE
, C.NM_CLIENTE
, d.NM_CORRET
, #T1.QTD_NEGOCIOS		
		
		
ORDER BY 1
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;