CREATE PROCEDURE [dbo].[PR_DAY_TRADE_RESUMO] @INICIO SMALLDATETIME, @FIM SMALLDATETIME, @INICIO2 SMALLDATETIME , @FIM2 SMALLDATETIME, @CD_CLIENTE VARCHAR(50), @QTDPORPAGINA INT, @PAGINA INT	
WITH RECOMPILE
AS		
		
--DECLARE @QTDPORPAGINA INT = 5000,@PAGINA INT = 1;
--DECLARE @INICIO SMALLDATETIME,@FIM SMALLDATETIME,@INICIO2 SMALLDATETIME,@FIM2 SMALLDATETIME,@CD_CLIENTE VARCHAR(50)

--SET @INICIO = '20250201'
--SET @FIM = '20250228'
--SET @INICIO2 = '20250101'
--SET @FIM2 = '20250131'
--SET @CD_CLIENTE = '278978'
		
--RESULTADO	
;WITH  #T1 AS (
SELECT CD_CLIENTE_COMPROU,		
@INICIO INICIO, 		
@FIM FIM,
--(CASE WHEN SUM(VL_FINANC)= 0 THEN 0 ELSE SUM(VL_FINANC) END)FINAN,		
 (SELECT CAST(SUM(X.QTD_DIAS_DAYTRADE) AS FLOAT) 
			  FROM (SELECT A.CD_CLIENTE_COMPROU
						 , A.DT_PREGAO_COMPROU 
						 , COUNT(DISTINCT A.DT_PREGAO_COMPROU) AS QTD_DIAS_DAYTRADE
					  FROM ST_DAYTRADE_DETALHE A		
				     WHERE A.CD_CLIENTE_COMPROU = A2.CD_CLIENTE_COMPROU 		
					   AND A.DT_PREGAO_COMPROU >=@INICIO 
					   AND A.DT_PREGAO_COMPROU <=@FIM		
					   AND QT_DAYTRADE > 0		
				  GROUP BY A.CD_CLIENTE_COMPROU
					     , A.DT_PREGAO_COMPROU) 
				   X) QTD_DIAS_DAYTRADE	
FROM ST_DAYTRADE_RESUMO A2		
WHERE DT_PREGAO_COMPROU >=@INICIO AND DT_PREGAO_COMPROU <=@FIM		
GROUP BY CD_CLIENTE_COMPROU	
),


--TODOS DAYTRADES POR PAPEL E DIA
 #T11 AS (
SELECT DT_PREGAO_COMPROU DT_PREGAO, 
CD_CLIENTE_COMPROU CD_CLIENTE,--CD_NEGOCIO_COMPROU CD_NEGOCIO, 
SUM((CASE WHEN CD_NATOPE = 'C' THEN -1 ELSE 1 END)*QT_DAYTRADE*VL_NEGOCIO_COMPROU) VL_ACERTO 
FROM ST_DAYTRADE_DETALHE
WHERE DT_PREGAO_COMPROU >= @INICIO
AND DT_PREGAO_COMPROU <= @FIM
and QT_DAYTRADE > 0
GROUP BY DT_PREGAO_COMPROU, CD_CLIENTE_COMPROU--, CD_NEGOCIO_COMPROU
),

--FINANCEIRO TOTAL
#T22 AS (
SELECT CD_CLIENTE, 
SUM(VL_ACERTO) VL_FINAN  FROM #T11
GROUP BY CD_CLIENTE),		
		
--ACERTOS PERIODO
#T2 AS (
SELECT CD_CLIENTE, 		
CAST(SUM(ACERTO) AS FLOAT) ACERTO,		
CAST(SUM(PERDA) AS FLOAT) PERDA,		
CAST(SUM(EMPATE) AS FLOAT) EMPATE		
FROM(		
	SELECT CD_CLIENTE, 		
	CASE WHEN VL_ACERTO > 0 THEN 1 ELSE 0 END ACERTO,		
	CASE WHEN VL_ACERTO < 0 THEN 1 ELSE 0 END PERDA,		
	CASE WHEN VL_ACERTO = 0 THEN 1 ELSE 0 END EMPATE		
	FROM(		
		SELECT DT_PREGAO_COMPROU DT_PREGAO, 		
		CD_CLIENTE_COMPROU CD_CLIENTE,CD_NEGOCIO_COMPROU CD_NEGOCIO, 		
		SUM((CASE WHEN CD_NATOPE = 'C' THEN -1 ELSE 1 END)*QT_DAYTRADE*VL_NEGOCIO_COMPROU) VL_ACERTO 		
		FROM ST_DAYTRADE_DETALHE 		
		WHERE DT_PREGAO_COMPROU >= @INICIO		
		AND DT_PREGAO_COMPROU <= @FIM		
		AND QT_DAYTRADE > 0		
		GROUP BY DT_PREGAO_COMPROU, CD_CLIENTE_COMPROU, CD_NEGOCIO_COMPROU	
		) X 		
	) X2		
GROUP BY CD_CLIENTE),	
		
		
--RESULTADO ANT		
#T4 AS (
SELECT CD_CLIENTE_COMPROU,		
@INICIO INICIO, 		
@FIM FIM,		
 (SELECT CAST(SUM(X.QTD_DIAS_DAYTRADE) AS FLOAT) 
			  FROM (SELECT A.CD_CLIENTE_COMPROU
						 , A.DT_PREGAO_COMPROU 
						 , COUNT(DISTINCT A.DT_PREGAO_COMPROU) AS QTD_DIAS_DAYTRADE
					  FROM ST_DAYTRADE_DETALHE A		
				     WHERE A.CD_CLIENTE_COMPROU = A2.CD_CLIENTE_COMPROU 		
					   AND A.DT_PREGAO_COMPROU >=@INICIO 
					   AND A.DT_PREGAO_COMPROU <=@FIM		
					   AND QT_DAYTRADE > 0		
				  GROUP BY A.CD_CLIENTE_COMPROU
					     , A.DT_PREGAO_COMPROU) 
				   X) QTD_DIAS_DAYTRADE			
FROM ST_DAYTRADE_RESUMO A2		
WHERE DT_PREGAO_COMPROU >=@INICIO2 AND DT_PREGAO_COMPROU <=@FIM2		
GROUP BY CD_CLIENTE_COMPROU	),

		
		
--ACERTOS PERIODO ANT
#T3 AS (
SELECT CD_CLIENTE,
CAST(SUM(ACERTO) AS FLOAT) ACERTO,		
CAST(SUM(PERDA) AS FLOAT) PERDA,		
CAST(SUM(EMPATE) AS FLOAT) EMPATE
FROM(
	SELECT CD_CLIENTE, 
	CASE WHEN VL_ACERTO > 0 THEN 1 ELSE 0 END ACERTO,		
	CASE WHEN VL_ACERTO < 0 THEN 1 ELSE 0 END PERDA,		
	CASE WHEN VL_ACERTO = 0 THEN 1 ELSE 0 END EMPATE	
	FROM(
		SELECT DT_PREGAO_COMPROU DT_PREGAO, 
		CD_CLIENTE_COMPROU CD_CLIENTE,--CD_NEGOCIO_COMPROU CD_NEGOCIO,
		SUM((CASE WHEN CD_NATOPE = 'C' THEN -1 ELSE 1 END)*QT_DAYTRADE*VL_NEGOCIO_COMPROU) VL_ACERTO 
		FROM ST_DAYTRADE_DETALHE
		WHERE DT_PREGAO_COMPROU >= @INICIO2
		AND DT_PREGAO_COMPROU <= @FIM2
		AND QT_DAYTRADE >0
		GROUP BY DT_PREGAO_COMPROU, CD_CLIENTE_COMPROU--, CD_NEGOCIO_COMPROU
		) X
	) X2
GROUP BY CD_CLIENTE)		



		
---QUERY FINAL		
SELECT 		
FORMAT(T1.INICIO,'d','pt-br')[DATA INÍCIO], 		
FORMAT(T1.FIM,'d','pt-br') [DATA FIM], 	
T1.CD_CLIENTE_COMPROU AS [CÓD. CLIENTE], 		 		
(SELECT MAX(NM_CLIENTE) FROM V_CLIENTE_TODOS TT		
	WHERE TT.CD_CLIENTE = T1.CD_CLIENTE_COMPROU) [NOME DO CLIENTE], 		
FORMAT(T1.QTD_DIAS_DAYTRADE,'#,0','PT-BR') [QTD. DIAS DAYTRADES],	
FORMAT(T22.VL_FINAN,'f','pt-br') AS [RESULTADO FINANCEIRO],
FORMAT(T2.ACERTO,'#,0','PT-BR')ACERTO, 		
FORMAT(T2.PERDA,'#,0','PT-BR')PERDA,		
FORMAT(T2.EMPATE,'#,0','PT-BR')EMPATE,		

FORMAT(T2.ACERTO / (T2.ACERTO + T2.PERDA + T2.EMPATE ),'P','PT-BR') [PERC. ACERTO], 	

FORMAT(ISNULL(CAST(T3.ACERTO AS FLOAT),0) / NULLIF((T3.ACERTO + T3.PERDA + T3.EMPATE),0),'P','PT-BR') [PERC. ACERTO ANTERIOR] 				
FROM #T1 T1 
LEFT OUTER JOIN #T2 T2 ON T1.CD_CLIENTE_COMPROU = T2.CD_CLIENTE
LEFT OUTER JOIN #T3 T3 ON T1.CD_CLIENTE_COMPROU = T3.CD_CLIENTE
LEFT OUTER JOIN #T4 ON T3.CD_CLIENTE = #T4.CD_CLIENTE_COMPROU
LEFT OUTER JOIN #T22 T22 ON T1.CD_CLIENTE_COMPROU = T22.CD_CLIENTE
WHERE T1.QTD_DIAS_DAYTRADE IS NOT NULL
AND T1.CD_CLIENTE_COMPROU = CASE WHEN ISNULL(@CD_CLIENTE,'')='' THEN T1.CD_CLIENTE_COMPROU ELSE ISNULL(@CD_CLIENTE,'') END
ORDER BY T1.CD_CLIENTE_COMPROU

OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;