CREATE PROC [dbo].[PR_DISPERCAO_PRECOS_BOVESPA] @INICIO SMALLDATETIME, @CD_CLIENTE VARCHAR(160), @PAGINA INT, @QTDPORPAGINA INT 
--WITH RECOMPILE
AS


--DECLARE @PAGINA        INT = 1;
--DECLARE @QTDPORPAGINA INT = ''
--DECLARE @INICIO SMALLDATETIME
--DECLARE @CD_CLIENTE INT
--SET @INICIO = '20251201'


drop table if exists #v_cliente_todos
select distinct cd_cliente, nm_cliente 
into #v_cliente_todos
from ST_DADOS_BASICOS_PF
union all
select distinct cd_cliente, nm_cliente from ST_DADOS_BASICOS_PJ


--;WITH #OPER_BROKER AS (
drop table if exists #OPER_BROKER
SELECT DT_NEGOCIO AS DT_PERIODO, F.CD_CLIENTE
--, C.NM_CLIENTE
, CD_CLIENTE_BRO AS [BROKER]
--, D.NM_CLIENTE AS NM_BROKER
, CD_PAPEL,SUM(F.VL_NEGOCIO) PRECO, F.NR_NEGOCIO, CD_NATOPE AS CD_TIPO_OFERTA 
into #OPER_BROKER
FROM 
ST_CORRETAGEM_ORDEM F 
--LEFT JOIN (SELECT DISTINCT CD_CLIENTE,NM_CLIENTE FROM V_CLIENTE_TODOS (NOLOCK)) C ON F.CD_CLIENTE = C.CD_CLIENTE
--LEFT JOIN (SELECT DISTINCT CD_CLIENTE,NM_CLIENTE FROM V_CLIENTE_TODOS (NOLOCK)) D ON F.CD_CLIENTE_BRO = D.CD_CLIENTE 
WHERE 
DT_NEGOCIO = @INICIO
AND f.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN f.CD_CLIENTE ELSE @CD_CLIENTE END
GROUP BY 
DT_NEGOCIO, F.CD_CLIENTE
--, C.NM_CLIENTE
, CD_CLIENTE_BRO
--, D.NM_CLIENTE
, CD_PAPEL, 
F.NR_NEGOCIO, CD_NATOPE 
--)
CREATE NONCLUSTERED INDEX t_oper_broker
ON [dbo].[#OPER_BROKER] ([BROKER],[CD_PAPEL],[PRECO])
INCLUDE ([DT_PERIODO],[CD_CLIENTE],[NR_NEGOCIO],[CD_TIPO_OFERTA])

--,#OPER_MEDIA AS (
drop table if exists #OPER_MEDIA
SELECT BROKER,CD_PAPEL, AVG(CAST(PRECO AS NUMERIC(19,2))) MEDIA_PRECO
into #OPER_MEDIA
FROM #OPER_BROKER
GROUP BY BROKER, CD_PAPEL
--)



SELECT DT_PERIODO as [DATA]
,Y.BROKER as [CÓD. BROKER]
, z.nm_Cliente as [NOME DO BROKER]
, y.CD_CLIENTE as [CÓD. DO CLIENTE]
, w.nm_Cliente as [Nome do Cliente]
,Y.CD_PAPEL as ATIVO
, NR_NEGOCIO as [NR. NEGÓCIO]
,CD_TIPO_OFERTA as [C / V]
,CAST(PRECO AS MONEY) as [PREÇO]
,CAST(X.MEDIA_PRECO AS MONEY) AS [PREÇO MÉDIO]
,CASE WHEN CD_TIPO_OFERTA= 'C' AND PRECO > MEDIA_PRECO THEN 'NEGATIVO: COMPRA MAIOR QUE A MEDIA'
     WHEN CD_TIPO_OFERTA= 'C' AND CAST(PRECO AS NUMERIC(19,2)) < CAST(MEDIA_PRECO AS NUMERIC(19,2)) THEN 'POSITIVO: COMPRA MENOR QUE A MEDIA'
     WHEN CD_TIPO_OFERTA= 'V' AND CAST(PRECO AS NUMERIC(19,2)) > CAST(MEDIA_PRECO AS NUMERIC(19,2))  THEN 'POSITIVO: VENDA MAIOR QUE A MEDIA'
     WHEN CD_TIPO_OFERTA= 'V' AND CAST(PRECO AS NUMERIC(19,2)) < CAST(MEDIA_PRECO AS NUMERIC(19,2))  THEN 'NEGATIVO: VENDA MENOR QUE A MEDIA'
     ELSE 'EMPATE' END RESULTADO
FROM #OPER_BROKER Y 
INNER JOIN #OPER_MEDIA X ON Y.CD_PAPEL = X.CD_PAPEL AND Y.BROKER = X.BROKER
left outer join #v_Cliente_todos z on Y.CD_CLIENTE = z.cd_cliente
left outer join #v_Cliente_todos w on Y.CD_CLIENTE = w.cd_cliente
WHERE Y.BROKER <> Y.CD_CLIENTE
AND ( CAST(PRECO AS NUMERIC(19,2)) > CAST(MEDIA_PRECO AS NUMERIC(19,2))
OR CAST(PRECO AS NUMERIC(19,2)) < CAST(MEDIA_PRECO AS NUMERIC(19,2)) )

ORDER BY 
Y.BROKER,  ATIVO, CD_TIPO_OFERTA, y.CD_CLIENTE

OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;