CREATE PROCEDURE [dbo].[FIRA_PR_CARGA_ST_PERIODO]
AS


SET LANGUAGE PORTUGUESE  

DECLARE @P_DATA AS SMALLDATETIME
DECLARE @CD_ANO INT
DECLARE @CD_MES  INT
DECLARE @DS_MES VARCHAR(20)
DECLARE @CD_ANOMES INT
DECLARE @DS_ANOMES VARCHAR(20)
DECLARE @CD_ANOTRIM INT
DECLARE @DS_ANOTRIM VARCHAR(20)
DECLARE @SG_MES VARCHAR(20)
DECLARE @DT_TEMPO SMALLDATETIME
DECLARE @CD_DIA INT
DECLARE @CD_DIASEMANAORI VARCHAR(20)
DECLARE @CD_DIASEMANAABV VARCHAR(20)


-- APAGA A TABELA DE PERIODO
TRUNCATE TABLE DBO.ST_PERIODO

-- AJUSTA O IDENTITY DA TABELA  PARA COMEÇAR COM 1
DBCC CHECKIDENT (ST_PERIODO, RESEED, 1)


-- DATA INICIAL
SET @DT_TEMPO =  CAST ('01-JAN-2025' AS SMALLDATETIME)
SET @P_DATA = CAST(GETDATE() AS DATE)


-- INICIO DO LOOP DE DATA INICIAL ATÉ DATA FINAL
WHILE (@DT_TEMPO <= @P_DATA )
BEGIN
           
    -- NÚMERO DO ANO
    SET @CD_ANO = DATEPART(YEAR, @DT_TEMPO)

    -- NÚMERO DO MÊS
    SET @CD_MES = DATEPART(MONTH, @DT_TEMPO) 

    -- DESCRIÇÃO DO MÊS
    SET @DS_MES = UPPER(CAST(DATENAME(MONTH, @DT_TEMPO) AS CHAR(1))) + SUBSTRING(DATENAME(MONTH, @DT_TEMPO), 2, 20)

    -- NÚMERO DO ANO MÊS
    SET @CD_ANOMES = @CD_ANO * 100 + @CD_MES

    -- SG MÊS
    SET @SG_MES = SUBSTRING(DATENAME(MONTH, @DT_TEMPO), 1, 3)
    
    -- DESCRIÇÃO ANO MÊS
    SET @DS_ANOMES = SUBSTRING(CAST(@CD_ANO AS CHAR(4)), 1, 4) + '/' + @SG_MES 

    -- NÚMERO DO TRIMESTRE
    SET @CD_ANOTRIM = DATEPART(QUARTER, @DT_TEMPO) 

    -- DESCRIÇÃO DO TRIMESTRE
    SET @DS_ANOTRIM = 'TRIM' + CAST(@CD_ANOTRIM AS CHAR(1)) + '/' + CAST(@CD_ANO AS CHAR(4))

    -- NÚMERO DO DIA DA SEMANA
    SET @CD_DIA = (DATEPART(DW, @DT_TEMPO))
    
    -- DIA DA SEMANA
    IF @CD_DIA = 1      SET @CD_DIASEMANAORI = 'DOMINGO'
    IF @CD_DIA = 2      SET @CD_DIASEMANAORI = 'SEGUNDA-FEIRA'
    IF @CD_DIA = 3      SET @CD_DIASEMANAORI = 'TERÇA-FEIRA'
    IF @CD_DIA = 4      SET @CD_DIASEMANAORI = 'QUARTA-FEIRA'
    IF @CD_DIA = 5      SET @CD_DIASEMANAORI = 'QUINTA-FEIRA'
    IF @CD_DIA = 6      SET @CD_DIASEMANAORI = 'SEXTA-FEIRA'
    IF @CD_DIA = 7      SET @CD_DIASEMANAORI = 'SABADO'

    -- DIA DA SEMANA ABREVIADO
    IF @CD_DIA = 1      SET @CD_DIASEMANAABV = 'DOMINGO'
    IF @CD_DIA = 2      SET @CD_DIASEMANAABV = 'SEGUNDA'
    IF @CD_DIA = 3      SET @CD_DIASEMANAABV = 'TERÇA'
    IF @CD_DIA = 4      SET @CD_DIASEMANAABV = 'QUARTA'
    IF @CD_DIA = 5      SET @CD_DIASEMANAABV = 'QUINTA'
    IF @CD_DIA = 6      SET @CD_DIASEMANAABV = 'SEXTA'
    IF @CD_DIA = 7      SET @CD_DIASEMANAABV = 'SABADO'

    
    -- INSERE LINHA NA TABELA DE PERIODO
    INSERT INTO [DBO].[ST_PERIODO]
          (DT_PERIODO, CD_ANO, CD_MES, DS_MES, CD_ANOMES, DS_ANOMES, CD_ANOTRIM, DS_ANOTRIM, CD_DIA, CD_DIASEMANA, DS_DIASEMANA_ABREV, DS_DIASEMANA)
          
    -- EXIBE DADOS
    SELECT @DT_TEMPO, @CD_ANO, @CD_MES, UPPER(@DS_MES), @CD_ANOMES, UPPER(@DS_ANOMES), @CD_ANOTRIM, @DS_ANOTRIM, @CD_DIA, @CD_DIA, @CD_DIASEMANAABV, @CD_DIASEMANAORI

    -- DATA DO PERIOODO
    SET @DT_TEMPO = DATEADD(DAY, 1, @DT_TEMPO)           

END  
-- FIM DO LOOP  


/*#### UPDATES ####*/

	UPDATE ST_PERIODO	
	SET DT_PERIODO_ANT = (SELECT DT_PERIODO -1 FROM ST_PERIODO B WHERE B.ID_PERIODO = ST_PERIODO.ID_PERIODO)
						--AND DATEPART(WEEKDAY,B.DT_PERIODO) NOT IN (7,1))--TIRO SABDO E DOMINGO

	UPDATE ST_PERIODO 
	SET CD_DIA = (SELECT DAY(DT_PERIODO) FROM ST_PERIODO B WHERE B.ID_PERIODO = ST_PERIODO.ID_PERIODO)


-- IDENTIFICA FERIADOS: DIAS ÚTEIS SEM MOVIMENTAÇÃO NA CORRETAGEM
DROP TABLE IF EXISTS #FERIADO  

SELECT DISTINCT  DT_PERIODO, 'SIM' DT_FERIADO  
INTO #FERIADO
FROM ST_PERIODO A  
WHERE NOT EXISTS (SELECT DISTINCT DT_NEGOCIO   
          FROM ST_CORRETAGEM_ORDEM B  
          WHERE A.DT_PERIODO = B.DT_NEGOCIO  
          )
AND DATEPART(DW, DT_PERIODO) NOT IN (1, 7)
AND DT_PERIODO < CAST(GETDATE() AS DATE)

-- MARCA OS FERIADOS ENCONTRADOS
UPDATE ST_PERIODO
SET DT_FERIADO = (SELECT MAX(DT_FERIADO) FROM #FERIADO X
					WHERE X.DT_PERIODO = ST_PERIODO.DT_PERIODO)

-- MARCA TODOS OS DEMAIS DIAS COMO NÃO FERIADO (INCLUSIVE FINS DE SEMANA)
UPDATE ST_PERIODO
SET DT_FERIADO = 'NAO'
WHERE DT_FERIADO IS NULL 

-- MARCA O DIA ATUAL COMO NÃO FERIADO (AINDA SEM MOVIMENTAÇÃO POIS O DIA NÃO ENCERROU)
UPDATE ST_PERIODO
SET DT_FERIADO = 'NAO'
WHERE DT_PERIODO = CAST(GETDATE() AS DATE)
AND DATEPART(DW, DT_PERIODO) NOT IN (1, 7)


/*********************************************
insere de acordo que os dias 
vão avançando. tabela do modulo ocorrencias.
***********************************************/
INSERT INTO REFERENCIA (REF_ANO, REF_PERIODO, VISIVEL)
SELECT DISTINCT CD_ANO, DS_MES, 1 FROM ST_PERIODO X
WHERE NOT EXISTS (SELECT * FROM REFERENCIA Y
                        WHERE Y.REF_ANO = X.CD_ANO
                        AND Y.REF_PERIODO = X.DS_MES
                        )
AND DT_PERIODO >= ISNULL((SELECT EOMONTH(MIN(DATE_START), -1) FROM INCIDENT), '20250101')
ORDER BY CD_ANO