CREATE PROCEDURE [dbo].[PR_ATIVOS_LIQUIDOS]
    @DS_MES VARCHAR(20),
    @CD_ANO INT,
	@QTDPORPAGINA INT,
	@PAGINA INT
AS
BEGIN
    SET NOCOUNT ON;
    
    DECLARE @DT_INICIO DATE = (SELECT MIN(DT_PERIODO) FROM ST_PERIODO WHERE CD_ANO = @CD_ANO AND DS_MES = @DS_MES);
    DECLARE @DT_FIM DATE = (SELECT MAX(DT_PERIODO) FROM ST_PERIODO WHERE CD_ANO = @CD_ANO AND DS_MES = @DS_MES);
    
    SELECT 
        Codigo,
        Acao,
        Tipo,
        QtdTeorica,
        Parte
    FROM 
        [dbo].[CarteiraIndiceBovespa]
    WHERE 
        Data >= @DT_INICIO AND
        Data <= @DT_FIM
    ORDER BY
        Codigo        
	OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
	FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;
END