CREATE PROCEDURE [dbo].[PR_NEGOCIO_VS_CORRETORA_BMF] @INICIO SMALLDATETIME, @FIM SMALLDATETIME, @CD_CLIENTE VARCHAR(10)	,@QTDPORPAGINA INT, @PAGINA INT
--WITH ENCRYPTION
AS		
	
--DECLARE @PAGINA INT = 1;
--DECLARE @QTDPORPAGINA INT = 500000
--DECLARE @INICIO SMALLDATETIME, @FIM SMALLDATETIME, @CD_CLIENTE VARCHAR(10)				
--SET @INICIO='20240101'		
--SET @FIM='20240131'		
--SET @CD_CLIENTE='421759'	
	
				
SET ARITHABORT OFF 		
SET ANSI_WARNINGS OFF		
;WITH #T1 AS  (		
SELECT 		
ST.CD_CLIENTE, 		
SUM(ST.QT_QTDDET) QTD_NEGOCIOS 		
FROM ST_BMF_NEGOCIOS_NC ST		
WHERE		
ST.DT_NEGOCIO >= @INICIO AND ST.DT_NEGOCIO <= @FIM	
and TP_NEGOCIO IN ('NORMAL','DAY TRADE')
GROUP BY ST.CD_CLIENTE)		
 		
 --QUERY FINAL		
SELECT 		
ST.CD_CLIENTE AS [Cod Cliente], 		
C.NM_CLIENTE as [Nome do Cliente], 
ST.CD_CONTRAPARTE as [Cod Contraparte],
COR.NM_CORRET as [Nome da Contraparte],		
FORMAT(ISNULL(SUM(ST.QT_QTDDET),0),'#,0','PT-BR') as [Qtd de Negocios],		
FORMAT(ISNULL(#T1.QTD_NEGOCIOS,0),'#,0','PT-BR') as [Qtd Total], 		
FORMAT(SUM(CAST(ST.QT_QTDDET AS FLOAT)) / NULLIF(#T1.QTD_NEGOCIOS,0),'P2','PT-BR') as [Percentual]		
		
FROM 		
ST_BMF_NEGOCIOS_NC ST 		
LEFT OUTER JOIN st_Corretora COR ON ST.CD_CONTRAPARTE = COR.CD_CORRET
LEFT OUTER JOIN V_CLIENTE_TODOS C ON ST.CD_CLIENTE = C.CD_CLIENTE 	
LEFT OUTER JOIN #T1	ON ST.CD_CLIENTE = #T1.CD_CLIENTE 		
		
WHERE 		
	ST.TP_NEGOCIO IN ('NORMAL','DAY TRADE')
AND ST.DT_NEGOCIO >= @INICIO AND ST.DT_NEGOCIO <=@FIM		
AND	ST.CD_CLIENTE LIKE (CASE WHEN ISNULL(@CD_CLIENTE,'')='' THEN ST.CD_CLIENTE ELSE CONVERT(INT,@CD_CLIENTE) END)		
		
GROUP BY ST.CD_CLIENTE, C.NM_CLIENTE, #T1.QTD_NEGOCIOS,COR.NM_CORRET,ST.CD_CONTRAPARTE			


ORDER BY 1

OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;