CREATE   PROCEDURE [dbo].[FIRA_PR_CARGA_ST_DIRETAS_BMF] @PREGAO DATETIME, @PREGAOFIM DATETIME
--WITH ENCRYPTION
AS
 
DROP TABLE IF EXISTS [dbo].[ST_DIRETAS_BMF_PADRAO]
    CREATE TABLE [dbo].[ST_DIRETAS_BMF_PADRAO] (
    [CD_CLIENTE_COMPRA] [int] NULL,
	[NM_CLIENTE_COMPRA] [varchar](400) NULL,
	[VINC_COMPRA] [char](1) NULL,
	[CD_CLIENTE_VENDA] [int] NULL,
	[NM_CLIENTE_VENDA] [varchar](400) NULL,
	[VINC_VENDA] [char](1) NULL,
	[DT_NEGOCIO] [datetime] NULL,
	[NR_NEGOCIO] [numeric](12, 0) NULL,
	[QT_NEGOCIO_COMPRA] [float] NOT NULL,
	[QT_NEGOCIO_VENDA] [float] NOT NULL,
	[CD_NEGOCIO] [varchar](20) NULL,
	[CD_COMMOD] [char](3) NULL,
	[CD_SERIE] [char](4) NULL,
	[HH_COMPRA] [varchar](8) NULL,
	[HH_VENDA] [varchar](8) NULL,
	[VL_TOTNEG_COMPRA] [float] NOT NULL,
	[VL_TOTNEG_VENDA] [float] NOT NULL,
	[VL_NEGOCIO_COMPRA] [float] NOT NULL,
	[VL_NEGOCIO_VENDA] [float] NOT NULL,
	[CD_ASSESSOR_COMPRA] [int] NULL,
	[DS_ASSESSOR_COMPRA] [varchar](60) NULL,
	[CD_ASSESSOR_VENDA] [int] NULL,
	[DS_ASSESSOR_VENDA] [varchar](60) NULL,
	[SISTEMA_COMPRA] [varchar](10) NULL,
	[USUARIO_COMPRA] [varchar](100) NULL,
	[SISTEMA_VENDA] [varchar](10) NULL,
	[USUARIO_VENDA] [varchar](100) NULL,
	[tp_cliente_compra] [int] NULL,
	[tp_cliente_venda] [int] NULL,
	[DS_MERCAD] [varchar](100) NULL,
	[in_after] [char](1) NULL,
	[DT_FIRA] DATETIME NULL
) ON [PRIMARY];

/***************************************************
inicio da comparação entre a tabela
da base padrao fira origem x tabela cliente destino
*****************************************************/
EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo',, @src_table='ST_DIRETAS_BMF_PADRAO',
  @schema_name='dbo', @base_table='ST_DIRETAS_BMF',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1;


/*******************************	
	CARGA ST_BMF_NEGOCIOS		
********************************/  

--DECLARE @PREGAO DATETIME, @PREGAOFIM DATETIME
--SET @PREGAO ='20250101'
--SET @PREGAOFIM ='20260201'


/*******************************	
	CARGA ST_DIRETAS_BMF		
********************************/  
   
WHILE @PREGAO < @PREGAOFIM 	
BEGIN	

	----
	--DELETA		
	DELETE ST_DIRETAS_BMF WHERE DT_NEGOCIO = @PREGAO	
 	
	
	----
	--INSERT FINAL	
	INSERT INTO ST_DIRETAS_BMF	
	(
	CD_CLIENTE_COMPRA,NM_CLIENTE_COMPRA,VINC_COMPRA,CD_CLIENTE_VENDA,NM_CLIENTE_VENDA,VINC_VENDA
	,DT_NEGOCIO,NR_NEGOCIO,QT_NEGOCIO_COMPRA,QT_NEGOCIO_VENDA,CD_NEGOCIO,CD_COMMOD,CD_SERIE
	,HH_COMPRA,HH_VENDA,VL_TOTNEG_COMPRA,VL_TOTNEG_VENDA,VL_NEGOCIO_COMPRA,VL_NEGOCIO_VENDA
	,CD_ASSESSOR_COMPRA,DS_ASSESSOR_COMPRA,CD_ASSESSOR_VENDA,DS_ASSESSOR_VENDA,SISTEMA_COMPRA
	,USUARIO_COMPRA,SISTEMA_VENDA,USUARIO_VENDA,tp_cliente_compra,tp_cliente_venda,DS_MERCAD,in_after
	)
		SELECT DISTINCT 	
			F1.CD_CLIENTE AS CD_CLIENTE_COMPRA,	
			V1.NM_CLIENTE AS NM_CLIENTE_COMPRA,	
			V1.IN_PESS_VINC AS VINC_COMPRA,	
			F2.CD_CLIENTE AS CD_CLIENTE_VENDA,	
			V2.NM_CLIENTE AS NM_CLIENTE_VENDA,	
			V2.IN_PESS_VINC AS VINC_VENDA,	
			F1.DT_NEGOCIO,	
			F1.NR_NEGOCIO,	
			CASE WHEN F1.QT_QTDDET <= F2.QT_QTDDET THEN F1.QT_QTDDET ELSE F2.QT_QTDDET END AS QT_NEGOCIO_COMPRA,	
			CASE WHEN F1.QT_QTDDET <= F2.QT_QTDDET THEN F1.QT_QTDDET ELSE F2.QT_QTDDET END AS QT_NEGOCIO_VENDA,	
			F1.CD_COMMOD + ISNULL(F1.CD_SERIE,'') AS CD_NEGOCIO,	
			F1.CD_COMMOD,	
			ISNULL(F1.CD_SERIE,'') AS CD_SERIE,	
		
			--(SELECT MAX(X.HR_NEGOCIO) FROM ST_BMF_NEGOCIOS X	
			-- WHERE X.CD_CLIENTE = F1.CD_CLIENTE AND X.CD_COMMOD = F1.CD_COMMOD AND X.CD_SERIE = ISNULL(F1.CD_SERIE,'')	
			-- AND X.NR_NEGOCIO = F1.NR_NEGOCIO AND X.DT_NEGOCIO = F1.DT_NEGOCIO AND X.CD_NATOPE = F1.CD_NATOPE) AS HH_COMPRA,
			NULL AS HH_COMPRA,
		
			--(SELECT MAX(X.HR_NEGOCIO) FROM ST_BMF_NEGOCIOS X	
			-- WHERE X.CD_CLIENTE = F2.CD_CLIENTE AND X.CD_COMMOD = F2.CD_COMMOD AND X.CD_SERIE = ISNULL(F2.CD_SERIE,'')	
			-- AND X.NR_NEGOCIO = F2.NR_NEGOCIO AND X.DT_NEGOCIO = F2.DT_NEGOCIO AND X.CD_NATOPE = F2.CD_NATOPE) AS HH_VENDA,
			NULL AS HH_VENDA,
		
			(F1.VL_VALOPE/F1.QT_QTDDET) * CASE WHEN F1.QT_QTDDET <= F2.QT_QTDDET THEN F1.QT_QTDDET ELSE F2.QT_QTDDET END AS VL_TOTNEG_COMPRA,	
			(F2.VL_VALOPE/F2.QT_QTDDET) * CASE WHEN F1.QT_QTDDET <= F2.QT_QTDDET THEN F1.QT_QTDDET ELSE F2.QT_QTDDET END AS VL_TOTNEG_VENDA,
		
			F1.PR_NEGOCIO AS VL_NEGOCIO_COMPRA,	
			F2.PR_NEGOCIO AS VL_NEGOCIO_VENDA,	
			V1.CD_ASSESSOR AS CD_ASSESSOR_COMPRA,	
			V1.NM_ASSESSOR AS DS_ASSESSOR_COMPRA,	
			V2.CD_ASSESSOR AS CD_ASSESSOR_VENDA,	
			V2.NM_ASSESSOR AS DS_ASSESSOR_VENDA,	
		
			--(SELECT MAX(X.CD_OPERADOR) FROM ST_BMF_NEGOCIOS X	
			-- WHERE X.CD_CLIENTE = F1.CD_CLIENTE AND X.CD_COMMOD = F1.CD_COMMOD AND ISNULL(X.CD_SERIE,'') = ISNULL(F1.CD_SERIE,'')	
			-- AND X.NR_NEGOCIO = F1.NR_NEGOCIO AND X.DT_NEGOCIO = F1.DT_NEGOCIO AND X.CD_NATOPE = F1.CD_NATOPE) AS SISTEMA_COMPRA,
			 NULL AS SISTEMA_COMPRA,
		
			--(SELECT MAX(X.NM_USUARIO) FROM ST_BMF_NEGOCIOS X	
			-- WHERE X.CD_CLIENTE = F1.CD_CLIENTE AND X.CD_COMMOD = F1.CD_COMMOD AND ISNULL(X.CD_SERIE,'') = ISNULL(F1.CD_SERIE,'')	
			-- AND X.NR_NEGOCIO = F1.NR_NEGOCIO AND X.DT_NEGOCIO = F1.DT_NEGOCIO AND X.CD_NATOPE = F1.CD_NATOPE) AS USUARIO_COMPRA,
			 NULL AS USUARIO_COMPRA,
		
			--(SELECT MAX(X.CD_OPERADOR) FROM ST_BMF_NEGOCIOS X	
			-- WHERE X.CD_CLIENTE = F2.CD_CLIENTE AND X.CD_COMMOD = F2.CD_COMMOD AND ISNULL(X.CD_SERIE,'') = ISNULL(F2.CD_SERIE,'')	
			-- AND X.NR_NEGOCIO = F2.NR_NEGOCIO AND X.DT_NEGOCIO = F2.DT_NEGOCIO AND X.CD_NATOPE = F2.CD_NATOPE) AS SISTEMA_VENDA,
			 NULL AS SISTEMA_VENDA,
		
			--(SELECT MAX(X.NM_USUARIO) FROM ST_BMF_NEGOCIOS X	
			-- WHERE X.CD_CLIENTE = F2.CD_CLIENTE AND X.CD_COMMOD = F2.CD_COMMOD AND ISNULL(X.CD_SERIE,'') = ISNULL(F2.CD_SERIE,'')	
			-- AND X.NR_NEGOCIO = F2.NR_NEGOCIO AND X.DT_NEGOCIO = F2.DT_NEGOCIO AND X.CD_NATOPE = F2.CD_NATOPE) AS USUARIO_VENDA ,
			 NULL AS USUARIO_VENDA,
		
			NULL AS TP_CLIENTE_COMPRA,	
			NULL AS TP_CLIENTE_VENDA,	
			F1.CD_MERCAD AS DS_MERCAD,	
			NULL AS IN_AFTER	
		
		FROM 	
			ST_BMF_NEGOCIOS_NC (NOLOCK) F1,	
			ST_BMF_NEGOCIOS_NC (NOLOCK) F2,	
			V_CLIENTE_TODOS (NOLOCK) V1,	
			V_CLIENTE_TODOS (NOLOCK) V2	
		
		WHERE 	
			F1.CD_NATOPE = 'C' 	
		AND F2.CD_NATOPE = 'V' 	
		AND F1.DT_NEGOCIO = F2.DT_NEGOCIO 	
		AND F1.CD_COMMOD = F2.CD_COMMOD 	
		AND F1.NR_NEGOCIO = F2.NR_NEGOCIO 	
		AND F1.CD_CLIENTE = V1.CD_CLIENTE 	
		AND ISNULL(F1.CD_SERIE,'') =  ISNULL(F2.CD_SERIE,'') 	
		AND F2.CD_CLIENTE = V2.CD_CLIENTE
		AND F1.TP_NEGOCIO IN ('NORMAL', 'DAY TRADE','DAYTRADE') 	
		AND F2.TP_NEGOCIO IN ('NORMAL','DAY TRADE','DAYTRADE') 	
		AND F1.DT_NEGOCIO = @PREGAO 


	------------------------------------------
	------ UPDATES NA ST_DIRETAS_BMF  --------
	------ COLUNAS:	HH_COMPRA, 		  --------
	------			HH_VENDA, 		  --------
	------			SISTEMA_COMPRA,	  --------
	------			USUARIO_COMPRA,	  --------
	------			SISTEMA_VENDA, 	  --------
	------			USUARIO_VENDA	  --------
	------------------------------------------
		SELECT 
			 DT_NEGOCIO
			,CD_CLIENTE
			,CD_COMMOD
			,CD_SERIE
			,CD_NATOPE
			,NR_NEGOCIO
			,NM_USUARIO
			,HR_NEGOCIO
			,CD_OPERADOR

		INTO #BMF_NEGOCIOS
		FROM ST_BMF_NEGOCIOS (NOLOCK)
		WHERE DT_NEGOCIO = @PREGAO 


		--HH_COMPRA
		UPDATE TB1
		SET TB1.HH_COMPRA = TB2.HR_NEGOCIO 
		FROM ST_DIRETAS_BMF (NOLOCK) AS TB1
		INNER JOIN #BMF_NEGOCIOS TB2	
			ON  TB2.CD_CLIENTE	= TB1.CD_CLIENTE_COMPRA 
			AND TB2.CD_COMMOD	= TB1.CD_COMMOD 
			AND TB2.CD_SERIE	= ISNULL(TB1.CD_SERIE,'')
			AND TB2.NR_NEGOCIO	= TB1.NR_NEGOCIO 
			AND TB2.DT_NEGOCIO	= TB1.DT_NEGOCIO 
			AND TB2.CD_NATOPE	= 'C'	
		WHERE TB1.DT_NEGOCIO = @PREGAO 
	

		--SISTEMA_COMPRA
		UPDATE TB1
		SET TB1.SISTEMA_COMPRA = TB2.CD_OPERADOR
		FROM ST_DIRETAS_BMF (NOLOCK) AS TB1
		INNER JOIN #BMF_NEGOCIOS TB2	
			ON  TB2.CD_CLIENTE	= TB1.CD_CLIENTE_COMPRA 
			AND TB2.CD_COMMOD	= TB1.CD_COMMOD 
			AND TB2.CD_SERIE	= ISNULL(TB1.CD_SERIE,'')
			AND TB2.NR_NEGOCIO	= TB1.NR_NEGOCIO 
			AND TB2.DT_NEGOCIO	= TB1.DT_NEGOCIO 
			AND TB2.CD_NATOPE	= 'C'	
		WHERE TB1.DT_NEGOCIO = @PREGAO 


		--USUARIO_COMPRA
		UPDATE TB1
		SET TB1.USUARIO_COMPRA = TB2.NM_USUARIO
		FROM ST_DIRETAS_BMF (NOLOCK) AS TB1
		INNER JOIN #BMF_NEGOCIOS TB2	
			ON  TB2.CD_CLIENTE	= TB1.CD_CLIENTE_COMPRA 
			AND TB2.CD_COMMOD	= TB1.CD_COMMOD 
			AND TB2.CD_SERIE	= ISNULL(TB1.CD_SERIE,'')
			AND TB2.NR_NEGOCIO	= TB1.NR_NEGOCIO 
			AND TB2.DT_NEGOCIO	= TB1.DT_NEGOCIO 
			AND TB2.CD_NATOPE	= 'C'
		WHERE TB1.DT_NEGOCIO = @PREGAO 


		--HH_VENDA
		UPDATE TB1
		SET TB1.HH_VENDA = TB2.HR_NEGOCIO
		FROM ST_DIRETAS_BMF (NOLOCK) AS TB1
		INNER JOIN #BMF_NEGOCIOS TB2	
			ON  TB2.CD_CLIENTE	= TB1.CD_CLIENTE_VENDA 
			AND TB2.CD_COMMOD	= TB1.CD_COMMOD 
			AND TB2.CD_SERIE	= ISNULL(TB1.CD_SERIE,'')
			AND TB2.NR_NEGOCIO	= TB1.NR_NEGOCIO 
			AND TB2.DT_NEGOCIO	= TB1.DT_NEGOCIO 
			AND TB2.CD_NATOPE	= 'V'	
		WHERE TB1.DT_NEGOCIO = @PREGAO 


		--SISTEMA_VENDA
		UPDATE TB1
		SET TB1.SISTEMA_VENDA = TB2.CD_OPERADOR
		FROM ST_DIRETAS_BMF (NOLOCK) AS TB1
		INNER JOIN #BMF_NEGOCIOS TB2	
			ON  TB2.CD_CLIENTE	= TB1.CD_CLIENTE_VENDA 
			AND TB2.CD_COMMOD	= TB1.CD_COMMOD 
			AND TB2.CD_SERIE	= ISNULL(TB1.CD_SERIE,'')
			AND TB2.NR_NEGOCIO	= TB1.NR_NEGOCIO 
			AND TB2.DT_NEGOCIO	= TB1.DT_NEGOCIO 
			AND TB2.CD_NATOPE	= 'V'	
		WHERE TB1.DT_NEGOCIO = @PREGAO 


		--USUARIO_VENDA
		UPDATE TB1
		SET TB1.USUARIO_VENDA = TB2.NM_USUARIO
		FROM ST_DIRETAS_BMF (NOLOCK) AS TB1
		INNER JOIN #BMF_NEGOCIOS TB2	
			ON  TB2.CD_CLIENTE	= TB1.CD_CLIENTE_VENDA 
			AND TB2.CD_COMMOD	= TB1.CD_COMMOD 
			AND TB2.CD_SERIE	= ISNULL(TB1.CD_SERIE,'')
			AND TB2.NR_NEGOCIO	= TB1.NR_NEGOCIO 
			AND TB2.DT_NEGOCIO	= TB1.DT_NEGOCIO 
			AND TB2.CD_NATOPE	= 'V'	
		WHERE TB1.DT_NEGOCIO = @PREGAO 


	

	/*** DROP TEMP ***/
	DROP TABLE #BMF_NEGOCIOS

		
SET @PREGAO = @PREGAO +1	

END	

-- ================================================
-- Marca DT_FIRA para registros carregados (fallback)
-- ================================================
DECLARE @__dt_fira_now DATETIME = GETDATE();
IF COL_LENGTH(N'dbo.ST_DIRETAS_BMF', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE [dbo].[ST_DIRETAS_BMF]
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL;
END
/******* fim do processo de carga **********/

--passo 3
/***** limpa a tabela do banco para nao ficar sujeira ******/
DROP TABLE IF EXISTS ST_DIRETAS_BMF_PADRAO