CREATE PROCEDURE [dbo].[FIRA_PR_CARGA_ST_DAYTRADE_RESUMO_ATIVO_BMF]  @PREGAO DATETIME , @PREGAOFIM DATETIME
AS

DROP TABLE IF EXISTS [dbo].[ST_DAYTRADE_RESUMO_ATIVO_BMF_PADRAO]
    CREATE TABLE [dbo].[ST_DAYTRADE_RESUMO_ATIVO_BMF_PADRAO] (
    [CD_CLIENTE] int NOT NULL,
    [CD_COMMOD] varchar(10) NULL,
    [CD_SERIE] varchar(10) NULL,
    [VL_COMPRA] float NULL,
    [VL_VENDA] float NULL,
    [VL_FINANC] float NULL,
    [DT_PREGAO_COMPROU] datetime NULL,
    [QT_CONTRAPARTES] int NULL,
    [DT_PRIMEIRA_OPER] smalldatetime NULL,
	[DT_FIRA] DATETIME NULL
);

/***************************************************
inicio da comparação entre a tabela
da base padrao fira origem x tabela cliente destino
*****************************************************/
EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo',, @src_table='ST_DAYTRADE_RESUMO_ATIVO_BMF_PADRAO',
  @schema_name='dbo', @base_table='ST_DAYTRADE_RESUMO_ATIVO_BMF',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1;


--DECLARE @PREGAO DATETIME,@PREGAOFIM DATETIME
--SET @PREGAO ='20260201'
--SET @PREGAOFIM ='20260213'


/****************************	
	CARGA ST_DAYTRADE_RESUMO_ATIVO_BMF		
****************************/     

WHILE @PREGAO < @PREGAOFIM 	
BEGIN	
	
	--DELETA		
	DELETE ST_DAYTRADE_RESUMO_ATIVO_BMF	WHERE DT_PREGAO_COMPROU = @PREGAO	
	
	----
	--INSERT FINAL	
	INSERT INTO ST_DAYTRADE_RESUMO_ATIVO_BMF
	(
	CD_CLIENTE,CD_COMMOD,CD_SERIE,VL_COMPRA,VL_VENDA,VL_FINANC
	,DT_PREGAO_COMPROU,QT_CONTRAPARTES,DT_PRIMEIRA_OPER
	)
		SELECT 
				CD_CLIENTE
				,CD_COMMOD
				,CD_SERIE
				,CAST(SUM(VL_COMPRA) AS DECIMAL(15,2)) VL_COMPRA
				,CAST(SUM(VL_VENDA) AS DECIMAL(15,2))VL_VENDA
				,CAST(SUM(VL_FINANC) AS DECIMAL(15,2))VL_FINANC
				,DT_PREGAO_COMPROU
				,NULL AS QT_CONTRAPARTES
				,NULL AS DT_PRIMEIRA_OPER	
			FROM(		
				SELECT 
					A.CD_CLIENTE
					,A.DT_DATMOV AS DT_PREGAO_COMPROU
					,CASE WHEN CD_NATOPE = 'C' THEN SUM(VL_VALOPE) ELSE 0 END VL_COMPRA
					,CASE WHEN CD_NATOPE = 'V' THEN SUM(VL_VALOPE) ELSE 0 END VL_VENDA
					,SUM(VL_VALOPE) AS VL_FINANC
					,CD_COMMOD
					,CD_SERIE		
				FROM 
					ST_BMF_NEGOCIOS_NC (NOLOCK)	A	
				WHERE 
					A.TP_NEGOCIO IN ('DAY TRADE','DAYTRADE')		
				AND A.DT_DATMOV = @PREGAO					
			GROUP BY CD_CLIENTE,  DT_DATMOV, CD_COMMOD,CD_SERIE	,CD_NATOPE
			HAVING 
				SUM(VL_VALOPE) <> 0
			)X
		GROUP BY 
		CD_CLIENTE,CD_COMMOD,CD_SERIE,DT_PREGAO_COMPROU

	
	---
	--UPDATES

		UPDATE ST_DAYTRADE_RESUMO_ATIVO_BMF 		
		SET QT_CONTRAPARTES = (	SELECT COUNT(DISTINCT A.CD_CLIENTE_COMPROU_DE) 		
								FROM ST_DAYTRADE_DETALHE_BMF (NOLOCK) A		
								WHERE 
									A.CD_CLIENTE = ST_DAYTRADE_RESUMO_ATIVO_BMF.CD_CLIENTE 		
								AND A.DT_DATMOV = ST_DAYTRADE_RESUMO_ATIVO_BMF.DT_PREGAO_COMPROU )		
		WHERE DT_PREGAO_COMPROU = @PREGAO		
			
		UPDATE ST_DAYTRADE_RESUMO_ATIVO_BMF 		
		SET DT_PRIMEIRA_OPER = (SELECT MIN(A.DT_PREGAO_COMPROU) 
								FROM ST_DAYTRADE_RESUMO_BMF (NOLOCK)A		
								WHERE A.CD_CLIENTE_COMPROU = ST_DAYTRADE_RESUMO_ATIVO_BMF.CD_CLIENTE )		
		WHERE DT_PREGAO_COMPROU = @PREGAO

	
	
SET @PREGAO = @PREGAO +1
END	

-- ================================================
-- Marca DT_FIRA para registros carregados (fallback)
-- ================================================
DECLARE @__dt_fira_now DATETIME = GETDATE();
IF COL_LENGTH(N'dbo.ST_DAYTRADE_RESUMO_ATIVO_BMF', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE [dbo].[ST_DAYTRADE_RESUMO_ATIVO_BMF]
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL;
END

/******* fim do processo de carga **********/

--passo 3
/***** limpa a tabela do banco para nao ficar sujeira ******/
DROP TABLE IF EXISTS ST_DAYTRADE_RESUMO_ATIVO_BMF_PADRAO