CREATE   PROCEDURE [dbo].[PR_RELATORIO_ALERT_301_HISTORICO] @CD_ANO INT, @DS_MES  VARCHAR(20) , @CD_CLIENTE VARCHAR(160) ,@QTDPORPAGINA INT, @PAGINA INT
--WITH RECOMPILE
AS


/*************************************
RELATORIO TRAZ O HISTORICO DOS ULTIMOS
6 MESES DOS CLIENTES.
****************************************/

--DECLARE @CD_ANO INT, @DS_MES  VARCHAR(20) , @CD_CLIENTE VARCHAR(160),@QTDPORPAGINA INT = '100000', @PAGINA INT = 1;
--SET @CD_ANO = 2024 
--SET @DS_MES = 'SETEMBRO'
--SET @CD_CLIENTE ='100396'

DECLARE @DT_PERIODO SMALLDATETIME
SET @DT_PERIODO = (SELECT MAX(DT_PERIODO) FROM St_PERIODO WHERE CD_ANO = @CD_ANO AND DS_MES = @DS_MES)


DECLARE @WV_RISCO_FINAL TABLE ([Data] VARCHAR(20), [Cód. do Cliente] int,[Nome do Cliente] nvarchar(160),[RISCO_FINAL] varchar(5))
INSERT INTO @WV_RISCO_FINAL SELECT [Data],[Cód. do Cliente],[Nome do Cliente],[RISCO_FINAL] FROM WV_RISCO_FINAL
--DROP TABLE IF EXISTS #WV_RISCO_FINAL
--SELECT * INTO #WV_RISCO_FINAL FROM WV_RISCO_FINAL

---FRONTEIRA
DECLARE @FRONTEIRA TABLE ([Cidade] varchar(50),[UF] varchar(4))
INSERT INTO @FRONTEIRA
SELECT DISTINCT DBO.FN_FORMATAR_TEXTO(NOME)[Cidade],
SUBSTRING(
        Detalhes, 
        CHARINDEX('SIGLA_UF:', Detalhes) + LEN('SIGLA_UF:'), 
        2
    ) AS [UF] FROM ListaAtencao 
WHERE IdSublista = 47
AND  CHARINDEX('SIGLA_UF:', Detalhes) > 0


SELECT 
    CASE 
    WHEN ( SUM(BOVESPA_AML)       >0 
        OR SUM(BMF_AML)           >0 
        OR SUM(SPOOFING_01)       >0 
        OR SUM(LAYERING_01)       >0 
        OR SUM(MONEYPASS_BOVESPA) >0
        OR SUM(MONEYPASS_BMF)     >0
		OR SUM(OSCILACAO)     >0) 
    THEN 'VERMELHO'
    WHEN (  SUM(BOVESPA_AML)=0 
        AND SUM(BMF_AML)    =0 
        AND SUM(SPOOFING_01)=0 
        AND SUM(LAYERING_01)=0) 
        AND (      SUM(DAYTRADE_BOVESPA_01)         >0 
                OR SUM(DAYTRADE_BMF_01)             >0 
                OR SUM(DAYTRADE_ATIVO_BOVESPA)      >0 
                OR SUM(DAYTRADE_ATIVO_BMF)          >0 
                OR SUM(AML_CORRETORA)               >0 
                OR SUM(AML_CORRETORA_BMF)           >0 
                OR SUM(SWING_BOVESPA)               >0 
                OR SUM(SWING_BMF)                   >0 
                OR SUM(SWING_ATIVO_BMF)             >0
                OR SUM(SWING_ATIVO_BVSP)            >0 
                --OR SUM(CHURNING_01)                   >0
                OR SUM(CHURNING_02)                 >0
                OR SUM(ATULIZACAO_CADASTRAL_01)     >0 
                --OR SUM(INSIDER_TRADING_BOVESPA)       >0 
                OR SUM(INSIDER_TRADING_BOVESPA_02)  >0 
                OR SUM(TRANSFERENCIA_FINANCEIRA_01) >0 
                OR SUM(TRANSFERENCIA_FINANCEIRA_02) >0
				OR SUM(OSCILACAO) >0	)  
        THEN 'AMARELO'  
        WHEN  ( SUM(BOVESPA_AML)                =0 
            AND SUM(BMF_AML)                    =0 
            AND SUM(SPOOFING_01)                =0 
            AND SUM(LAYERING_01)                =0 
            AND SUM(DAYTRADE_BOVESPA_01)        =0 
            OR SUM(DAYTRADE_BMF_01)             =0 
            OR  SUM(DAYTRADE_ATIVO_BOVESPA)     =0 
            OR SUM(DAYTRADE_ATIVO_BMF)          =0 
            OR SUM(AML_CORRETORA)               =0 
            OR SUM(AML_CORRETORA_BMF)           =0 
            OR SUM(SWING_BOVESPA)               =0 
            OR SUM(SWING_ATIVO_BMF)             =0 
            OR SUM(SWING_ATIVO_BVSP)            =0 
            OR SUM(SWING_BMF)                   =0 
            --OR SUM(CHURNING_01)                   =0 
            OR SUM(CHURNING_02)                 =0 
            OR SUM(ATULIZACAO_CADASTRAL_01)     =0 
            --OR SUM(INSIDER_TRADING_BOVESPA)       =0 
            OR SUM(INSIDER_TRADING_BOVESPA_02)      =0
            OR SUM(TRANSFERENCIA_FINANCEIRA_01) =0 
            OR SUM(TRANSFERENCIA_FINANCEIRA_02) =0)  
           AND (   SUM(PATRIMONIO_CUSTODIA)     >0 
                OR SUM(PATRIMONIO_NETTING)      >0 
                OR SUM(PATRIMONIO_MOVCC)        >0
                OR SUM(PATRIMONIO_TRANSF_CUST)  >0 
                OR SUM(OMC_BMF_01)              >0 
                OR SUM(OMC_01)                  >0 
                OR SUM(PROCURADOR_01)           >0 
                OR SUM(PATRIMONIO_01)           >0
				OR SUM(OSCILACAO)           >0)
        THEN 'LARANJA' 
        ELSE 'VERDE' 
        END  AS "ANALISE",
        CONCAT(CASE WHEN MONTH(EOMONTH(@DT_PERIODO,-6)) = 1 THEN 'JANEIRO' 
                    WHEN MONTH(EOMONTH(@DT_PERIODO,-6)) = 2 THEN 'FEVEREIRO'
                    WHEN MONTH(EOMONTH(@DT_PERIODO,-6)) = 3 THEN 'MARÇO'
                    WHEN MONTH(EOMONTH(@DT_PERIODO,-6)) = 4 THEN 'ABRIL'
                    WHEN MONTH(EOMONTH(@DT_PERIODO,-6)) = 5 THEN 'MAIO'
                    WHEN MONTH(EOMONTH(@DT_PERIODO,-6)) = 6 THEN 'JUNHO'
                    WHEN MONTH(EOMONTH(@DT_PERIODO,-6)) = 7 THEN 'JULHO'
                    WHEN MONTH(EOMONTH(@DT_PERIODO,-6)) = 8 THEN 'AGOSTO'
                    WHEN MONTH(EOMONTH(@DT_PERIODO,-6)) = 9 THEN 'SETEMBRO'
                    WHEN MONTH(EOMONTH(@DT_PERIODO,-6)) = 10 THEN 'OUTUBRO'
                    WHEN MONTH(EOMONTH(@DT_PERIODO,-6)) = 11 THEN 'NOVEMBRO'
                    WHEN MONTH(EOMONTH(@DT_PERIODO,-6)) = 12 THEN 'DEZEMBRO' END,' - ',
				CASE WHEN MONTH(EOMONTH(@DT_PERIODO,-6)) = 1 THEN 'JANEIRO' 
                            WHEN MONTH(EOMONTH(@DT_PERIODO,-1)) = 2 THEN 'FEVEREIRO'
                            WHEN MONTH(EOMONTH(@DT_PERIODO,-1)) = 3 THEN 'MARÇO'
                            WHEN MONTH(EOMONTH(@DT_PERIODO,-1)) = 4 THEN 'ABRIL'
                            WHEN MONTH(EOMONTH(@DT_PERIODO,-1)) = 5 THEN 'MAIO'
                            WHEN MONTH(EOMONTH(@DT_PERIODO,-1)) = 6 THEN 'JUNHO'
                            WHEN MONTH(EOMONTH(@DT_PERIODO,-1)) = 7 THEN 'JULHO'
                            WHEN MONTH(EOMONTH(@DT_PERIODO,-1)) = 8 THEN 'AGOSTO'
                            WHEN MONTH(EOMONTH(@DT_PERIODO,-1)) = 9 THEN 'SETEMBRO'
                            WHEN MONTH(EOMONTH(@DT_PERIODO,-1)) = 10 THEN 'OUTUBRO'
                            WHEN MONTH(EOMONTH(@DT_PERIODO,-1)) = 11 THEN 'NOVEMBRO'
                            WHEN MONTH(EOMONTH(@DT_PERIODO,-1)) = 12 THEN 'DEZEMBRO' END +' / '+ CAST(YEAR(EOMONTH(@DT_PERIODO,-1)) AS VARCHAR))AS Referencia,

                Y.CD_CLIENTE AS "Cód. Cliente",
                T1.NM_CLIENTE AS "NOME DO CLIENTE",
                MAX(T1.DS_NACION) AS "NACIONALIDADE",
                CASE WHEN LEN(T1.CD_CPFCGC) > 11 THEN dbo.formatar_cnpj(t1.cd_cpfcgc) ELSE dbo.formatar_cpf(t1.cd_cpfcgc)  END AS "CPF/CNPJ", 
                CASE WHEN LEN(T1.CD_CPFCGC) > 11 THEN 'PJ' ELSE 'PF ' END AS "PF / PJ",             
                MAX(T1.IDADE) AS "IDADE",
                MAX(T1.DS_TIPO_CLIENTE) AS "INVESTIDOR",                
                FORMAT(T1.DT_CRIACAO,'d','PT-BR') AS "DATA DE CRIAÇÃO",
				CASE WHEN F.CIDADE IS NOT NULL THEN 'SIM'
				ELSE 'NÃO'
				END AS "FRONTEIRA",
                CASE WHEN T1.IN_POLITICO_EXP = 'S' THEN 'SIM'
                WHEN T1.IN_POLITICO_EXP = 'N' THEN 'NÃO'
                ELSE  '' END AS "PEP SINACOR",
                CASE WHEN T1.IN_PESS_VINC = 'S' THEN 'SIM'
                WHEN T1.IN_PESS_VINC = 'N' THEN 'NÃO'
                ELSE  '' END AS "PESSOA VINCULADA",
                MAX(T1.INR) AS "INR",
                MAX(T1.NM_ASSESSOR) AS "ASSESSOR",
                MAX(T1.DS_ATIV) AS "PROFISSÃO",
                ISNULL(MAX(T1.RISCO),'OUTROS') AS "PROFISSÃO DE RISCO",
                ISNULL(MAX(TT.RISCO_FINAL),'') AS "SCORE RISCO",    
FORMAT(SUM(LISTA_ATENCAO),'0.#','PT-BR')   AS "LISTA ATENÇÃO",               
FORMAT(SUM(BOVESPA_AML),'0.#','PT-BR')  AS "AML BVSP",
FORMAT(SUM(BMF_AML),'0.#','PT-BR')   AS "AML BMF",
FORMAT(SUM(AML_CORRETORA),'0.#','PT-BR')   AS "AML CORRETORA BVSP", 
FORMAT(SUM(AML_CORRETORA_BMF),'0.#','PT-BR')    AS "AML CORRETORA BMF",
FORMAT(SUM(MEDIA_BMF_01),'0.#','PT-BR')  AS "MÉDIA BMF", 
FORMAT(SUM(MEDIA_BOVESPA_01),'0.#','PT-BR')  AS "MÉDIA BVSP",
FORMAT(SUM(TRANSFERENCIA_FINANCEIRA_01),'0.#','PT-BR')  AS "TRANSF. FINANCEIRA 01",
FORMAT(SUM(TRANSFERENCIA_FINANCEIRA_02),'0.#','PT-BR')  AS "TRANSF. FINANCEIRA 02",
FORMAT(SUM(PATRIMONIO_CUSTODIA),'0.#','PT-BR') AS "PATRIMÔNIO X CUSTÓDIA",
FORMAT(SUM(PATRIMONIO_NETTING),'0.#','PT-BR')   AS "PATRIMÔNIO X NETTING",
FORMAT(SUM(PATRIMONIO_MOVCC),'0.#','PT-BR')  AS "PATRIMÔNIO X MOV CC", 
FORMAT(SUM(PATRIMONIO_TRANSF_CUST),'0.#','PT-BR')   AS "PATRIMÔNIO X TRANSF. CUST.",
FORMAT(SUM(ATULIZACAO_CADASTRAL_01),'0.#','PT-BR') AS "ATUALIZAÇÃO CADASTRAL",
FORMAT(SUM(PROCURADOR_01),'0.#','PT-BR')  AS "PROCURADOR", 
FORMAT(SUM(MUDANCA_REPENTINA_01),'0.#','PT-BR')  AS "MUDANÇA REPENTINA",
FORMAT(SUM(INSIDER_TRADING_BOVESPA_02),'0.#','PT-BR') AS "INSIDER TRADING", 
FORMAT(SUM(CHURNING_02),'0.#','PT-BR') AS "CHURNING",
FORMAT(SUM(OMC_01),'0.#','PT-BR')  AS "OMC BVSP",
FORMAT(SUM(OMC_BMF_01),'0.#','PT-BR')  AS "OMC BMF", 
FORMAT(SUM(LAYERING_01),'0.#','PT-BR')  AS "LAYERING", 
FORMAT(SUM(SPOOFING_01),'0.#','PT-BR')  AS "SPOOFING",
FORMAT(SUM(MONEYPASS_BOVESPA),'0.#','PT-BR')   AS "MONEY PASS BVSP",
FORMAT(SUM(MONEYPASS_BMF),'0.#','PT-BR')   AS "MONEY PASS BMF",
FORMAT(SUM(RANKING_DAYTRADE_BVSP),'0.#','PT-BR')   AS "RANKING DAYTRADE BVSP",
FORMAT(SUM(RANKING_DAYTRADE_BMF),'0.#','PT-BR')   AS "RANKING DAYTRADE BMF",
FORMAT(SUM(OSCILACAO),'0.#','PT-BR')   AS "OSCILACAO",

SUM(CHURNING_02) +
SUM(OMC_01)  +
SUM(OMC_BMF_01)  + 
SUM(LAYERING_01) + 
SUM(SPOOFING_01) +
SUM(INSIDER_TRADING_BOVESPA_02) +
SUM(ATULIZACAO_CADASTRAL_01) +
SUM(PROCURADOR_01) + 
SUM(MUDANCA_REPENTINA_01) +
SUM(MEDIA_BMF_01) +
SUM(MEDIA_BOVESPA_01) +
SUM(TRANSFERENCIA_FINANCEIRA_01) +
SUM(TRANSFERENCIA_FINANCEIRA_02) +
SUM(BOVESPA_AML) +
SUM(BMF_AML) +
SUM(AML_CORRETORA)  +
SUM(AML_CORRETORA_BMF) +
SUM(PATRIMONIO_CUSTODIA) +
SUM(PATRIMONIO_NETTING) +
SUM(PATRIMONIO_MOVCC) + 
SUM(PATRIMONIO_TRANSF_CUST) +
SUM(MONEYPASS_BOVESPA) +
SUM(MONEYPASS_BMF)+
SUM(RANKING_DAYTRADE_BVSP)+
SUM(RANKING_DAYTRADE_BMF)+
SUM(LISTA_ATENCAO)+
SUM(OSCILACAO)
AS "TOTAL"


FROM(

        SELECT DISTINCT DATA,CD_CLIENTE, COUNT(DISTINCT 1)  AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0  BMF_AML, 0  BOVESPA_AML, 0  DAYTRADE_ATIVO_BMF, 0  
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA, 0  TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01,
        0 CHURNING_01, 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02, 0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA, 
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF
        
        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_AML_CORRETORA_BMF INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO) X
        GROUP BY DATA,CD_CLIENTE


        UNION ALL -- AML_CORRETORA
        SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, COUNT(DISTINCT 1)  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0  BMF_AML, 0  BOVESPA_AML, 0  DAYTRADE_ATIVO_BMF, 0  
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA, 0  TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01,
        0 CHURNING_01, 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02, 0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA, 
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF

        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_AML_CORRETORA INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO) X
        GROUP BY DATA,CD_CLIENTE
        UNION ALL

        ---ATUALIZACAO_CADASTRAL_01
        SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, COUNT(DISTINCT 1)  ATULIZACAO_CADASTRAL_01, 0  BMF_AML, 0  BOVESPA_AML, 0  DAYTRADE_ATIVO_BMF, 0  
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA, 0  TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01, 0 CHURNING_01
        , 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02, 0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA, 
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF
        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_ATULIZACAO_CADASTRAL_01 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE


        UNION ALL ---BMF_AML
        SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, COUNT(DISTINCT CD_CLIENTE)  BMF_AML, 0  BOVESPA_AML, 0  DAYTRADE_ATIVO_BMF, 0  
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA, 0  TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01, 0 CHURNING_01
        , 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02, 0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA, 
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF
        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_BMF_AML INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE


        UNION ALL --BOVESPA_AML
        SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, COUNT(DISTINCT 1)  BOVESPA_AML, 0  DAYTRADE_ATIVO_BMF, 0  
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA, 0  TRANSFERENCIA_FINANCEIRA_01,0 PATRIMONIO_01,  0 CHURNING_01
        , 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02, 0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA,
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF

        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_BOVESPA_AML INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE


        --UNION ALL --DAYTRADE_BMF_01
        --SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        --DAYTRADE_ATIVO_BOVESPA, COUNT(DISTINCT 1)  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        --0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA, 0  TRANSFERENCIA_FINANCEIRA_01,0 PATRIMONIO_01,  0 CHURNING_01
        --, 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02, 0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA, 
        --0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF

        --,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF
        --FROM(
        --SELECT DISTINCT DATA,CD_CLIENTE
        --FROM ST_ALERT_DAYTRADE_BMF_01 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        --WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        --) X
        --GROUP BY DATA,CD_CLIENTE

        --UNION ALL --DAYTRADE_BOVESPA_01
        --SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        --DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, COUNT(DISTINCT 1)  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        --0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA, 0  TRANSFERENCIA_FINANCEIRA_01,0 PATRIMONIO_01,  0 CHURNING_01
        --, 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02, 0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA, 
        --0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF

        --,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF
        --FROM(
        --SELECT DISTINCT DATA,CD_CLIENTE
        --FROM ST_ALERT_DAYTRADE_BOVESPA_01 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        --WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        --) X
        --GROUP BY DATA,CD_CLIENTE


        UNION ALL --MEDIA_BMF_01
        SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, COUNT(DISTINCT 1)  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA, 0  TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01, 0 CHURNING_01
        , 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02, 0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA, 
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF

        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_MEDIA_BMF_01 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL --MEDIA_BOVESPA_01
        SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, COUNT(DISTINCT 1)  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA, 0  TRANSFERENCIA_FINANCEIRA_01,0 PATRIMONIO_01,  0 CHURNING_01
        , 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02, 0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA, 
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF

        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_MEDIA_BOVESPA_01 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL --MUDANCA_REPENTINA_01
        SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        COUNT(DISTINCT 1)  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA, 0  TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01,  0 CHURNING_01
        , 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02, 0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA,
         0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF

        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_MUDANCA_REPENTINA_01 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL --PROCURADOR
        SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, COUNT(DISTINCT 1)  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA, 0  TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01, 0
        CHURNING_01, 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02, 0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA, 
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF

        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_PROCURADOR_02 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE


        ----UNION ALL --SWING_BMF
        ----SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        ----DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        ----0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, COUNT(DISTINCT 1)  SWING_BMF, 0  SWING_BOVESPA, 0  TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01,
        ----0 CHURNING_01, 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02, 0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA, 
        ----0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF

        ----,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        ----FROM(
        ----SELECT DISTINCT DATA,CD_CLIENTE
        ----FROM ST_ALERT_SWING_BMF INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        ----WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ----) X
        ----GROUP BY DATA,CD_CLIENTE

        --UNION ALL --SWING_BOVESPA
        --SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        --DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        --0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, COUNT(DISTINCT 1)  SWING_BOVESPA, 0  TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01,
        --0 CHURNING_01, 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02, 0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA, 
        --0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF

        --,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        --FROM(
        --SELECT DISTINCT DATA,CD_CLIENTE
        --FROM ST_ALERT_SWING_BOVESPA INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        --WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        --) X
        --GROUP BY DATA,CD_CLIENTE

        UNION ALL --TRANSFERENCIA_FINANCEIRA_01
        SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA, COUNT(DISTINCT 1)  TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01,  0 CHURNING_01
        , 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02, 0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA, 
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF

        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_TRANSFERENCIA_FINANCEIRA_01 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE

        /*UNION ALL --CHURNING_01
        SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA, 0  TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01,
        COUNT(DISTINCT 1) CHURNING_01, 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02, 0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA, 
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF
        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_CHURNING_BOVESPA_01 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE*/


        UNION ALL --OMC_01
        SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA, 0  TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01,
        0 CHURNING_01, COUNT(DISTINCT 1) OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02, 0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA,
         0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF
        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_OMC_01 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE


        UNION ALL --OMC_BMF_01
        SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA, 0  TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01,
        0 CHURNING_01, 0 OMC_01, COUNT(DISTINCT 1) OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02, 0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA, 
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF
        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_OMC_BMF_01 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE



        UNION ALL --LAYERING_01 
        SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA, 0  TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01,
        0 CHURNING_01, 0 OMC_01, 0 OMC_BMF_01, COUNT(DISTINCT 1) LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02, 0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA, 
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF
        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_LAYRERING_02 INNER JOIN ST_PERIODO ON DATA = ST_PERIODO.DT_PERIODO
        WHERE ST_PERIODO.DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND ST_PERIODO.DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE


        UNION ALL -- SPOOFING_BOVESPA_01 
        SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA, 0  TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01,
        0 CHURNING_01, 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, COUNT(DISTINCT 1) SPOOFING_01 ,0 TRANSFERENCIA_FINANCEIRA_02, 0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA, 
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF
        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_SPOOFING_BOVESPA_02 INNER JOIN ST_PERIODO ON DATA = ST_PERIODO.DT_PERIODO
        WHERE ST_PERIODO.DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND ST_PERIODO.DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL --TRANSFERENCIA_FINANCEIRA_02
        SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA,0 TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01, 0 CHURNING_01
        , 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01, COUNT(DISTINCT 1)TRANSFERENCIA_FINANCEIRA_02, 0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA, 
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF
        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_TRANSFERENCIA_FINANCEIRA_02 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE

        /*UNION ALL  --ST_ALERT_INSIDER_TRADING_BOVESPA
        SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA,0 TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01, 0 CHURNING_01
        , 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02,  0 TRANSFERENCIA_01,  COUNT(DISTINCT 1) INSIDER_TRADING_BOVESPA,
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF
        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_INSIDER_TRADING_BOVESPA INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE*/

        UNION ALL  --ST_ALERT_PATRIMONIO_CUSTODIA
        SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA,0 TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01, 0 CHURNING_01
        , 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02,  0 TRANSFERENCIA_01,  0 INSIDER_TRADING_BOVESPA,
        COUNT(DISTINCT 1) PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF
        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_PATRIMONIO_CUSTODIA INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL  --ST_ALERT_PATRIMONIO_NETTING
        SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA,0 TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01, 0 CHURNING_01
        , 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02,  0 TRANSFERENCIA_01,  0 INSIDER_TRADING_BOVESPA,
        0 PATRIMONIO_CUSTODIA,  COUNT(DISTINCT 1) PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF
        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_PATRIMONIO_NETTING INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL  --ST_ALERT_PATRIMONIO_MOVCC
        SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA,0 TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01, 0 CHURNING_01
        , 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02,  0 TRANSFERENCIA_01,  0 INSIDER_TRADING_BOVESPA,
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING,  COUNT(DISTINCT 1) PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF
        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_PATRIMONIO_MOVIMENTO INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL  --ST_ALERT_PATRIMONIO_TRANSF_CUST
        SELECT DISTINCT DATA,CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA,0 TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01, 0 CHURNING_01
        , 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02,  0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA,
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC,  COUNT(DISTINCT 1) PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,0 MONEYPASS_BOVESPA, 0 MONEYPASS_BMF
        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_PATRIMONIO_TRANF_CUST INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE


        
        UNION ALL  --MONEYPASS_BOVESPA
        SELECT DISTINCT DATA, CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA,0 TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01, 0 CHURNING_01
        , 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02,  0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA,
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,  COUNT(DISTINCT 1) MONEYPASS_BOVESPA, 0 MONEYPASS_BMF
        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_MONEYPASS_BOVESPA INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE


        UNION ALL  --MONEYPASS_BMF
        SELECT DISTINCT DATA, CD_CLIENTE_X CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA,0 TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01, 0 CHURNING_01
        , 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02,  0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA,
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,  0 MONEYPASS_BOVESPA, COUNT(DISTINCT 1)  MONEYPASS_BMF
        ,0 CHURNING_02,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE_X
        FROM ST_ALERT_MONEYPASS_BMF INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE_x

        UNION ALL  --CHURNING_02

        SELECT DISTINCT DATA, CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA,0 TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01, 0 CHURNING_01
        , 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02,  0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA,
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,  0 MONEYPASS_BOVESPA, 0  MONEYPASS_BMF
        ,COUNT(DISTINCT 1) CHURNING_02 ,0 INSIDER_TRADING_BOVESPA_02, 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_CHURNING_BOVESPA_02 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL

        SELECT DISTINCT DATA, CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA,0 TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01, 0 CHURNING_01
        , 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02,  0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA,
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,  0 MONEYPASS_BOVESPA, 0  MONEYPASS_BMF
        ,0 CHURNING_02 , COUNT(DISTINCT 1) INSIDER_TRADING_BOVESPA_02 , 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_INSIDER_TRADING_02 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE
        UNION ALL

        SELECT DISTINCT DATA, CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA,0 TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01, 0 CHURNING_01
        , 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02,  0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA,
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,  0 MONEYPASS_BOVESPA, 0  MONEYPASS_BMF
        ,0 CHURNING_02 , 0 INSIDER_TRADING_BOVESPA_02 , COUNT(DISTINCT 1) LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_LISTA_ATENCAO INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE
        UNION ALL

        SELECT DISTINCT DATA, CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA,0 TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01, 0 CHURNING_01
        , 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02,  0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA,
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,  0 MONEYPASS_BOVESPA, 0  MONEYPASS_BMF
        ,0 CHURNING_02 , 0 INSIDER_TRADING_BOVESPA_02 , 0 LISTA_ATENCAO, COUNT(DISTINCT 1) RANKING_DAYTRADE_BVSP, 0 RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_RANKING_DAYTRADE_BVSP INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE
        UNION ALL

        SELECT DISTINCT DATA, CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA,0 TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01, 0 CHURNING_01
        , 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02,  0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA,
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,  0 MONEYPASS_BOVESPA, 0  MONEYPASS_BMF
        ,0 CHURNING_02 , 0 INSIDER_TRADING_BOVESPA_02 , 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP , COUNT(DISTINCT 1) RANKING_DAYTRADE_BMF, 0 OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_RANKING_DAYTRADE_BMF INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE
		UNION ALL

        SELECT DISTINCT DATA, CD_CLIENTE, 0 AML_CORRETORA_BMF, 0  AML_CORRETORA, 0  ATULIZACAO_CADASTRAL_01, 0 BMF_AML, 0  BOVESPA_AML, 0 DAYTRADE_ATIVO_BMF, 0   
        DAYTRADE_ATIVO_BOVESPA, 0  DAYTRADE_BMF_01, 0  DAYTRADE_BOVESPA_01, 0  MEDIA_BMF_01, 0  MEDIA_BOVESPA_01, 
        0  MUDANCA_REPENTINA_01, 0  PROCURADOR_01, 0  SWING_BMF, 0  SWING_BOVESPA,0 TRANSFERENCIA_FINANCEIRA_01, 0 PATRIMONIO_01, 0 CHURNING_01
        , 0 OMC_01, 0 OMC_BMF_01, 0 LAYERING_01, 0 SPOOFING_01,0 TRANSFERENCIA_FINANCEIRA_02,  0 TRANSFERENCIA_01, 0 INSIDER_TRADING_BOVESPA,
        0 PATRIMONIO_CUSTODIA, 0 PATRIMONIO_NETTING, 0 PATRIMONIO_MOVCC, 0 PATRIMONIO_TRANSF_CUST,0 SWING_ATIVO_BMF,0 SWING_ATIVO_BVSP,  0 MONEYPASS_BOVESPA, 0  MONEYPASS_BMF
        ,0 CHURNING_02 , 0 INSIDER_TRADING_BOVESPA_02 , 0 LISTA_ATENCAO, 0 RANKING_DAYTRADE_BVSP , 0 RANKING_DAYTRADE_BMF, COUNT(DISTINCT 1) OSCILACAO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_OSCILACAO INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE DT_PERIODO >= EOMONTH(@DT_PERIODO,-6) AND DT_PERIODO < @DT_PERIODO
        ) X
        GROUP BY DATA,CD_CLIENTE
) Y 
LEFT OUTER JOIN V_CLIENTE_TODOS T1 ON Y.CD_CLIENTE = T1.CD_CLIENTE
INNER JOIN ST_PERIODO DD ON DD.DT_PERIODO = Y.DATA
--LEFT OUTER JOIN LISTAATENCAO E ON T1.NM_CLIENTE = E.NOME
LEFT JOIN @WV_RISCO_FINAL TT ON Y.CD_CLIENTE = TT.[CÓD. DO CLIENTE] AND CONVERT(VARCHAR,DD.DT_PERIODO,103) = TT.DATA
LEFT JOIN @FRONTEIRA F ON F.[Cidade] = T1.NM_CIDADE and f.[UF] = T1.SG_ESTADO
WHERE Y.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN Y.CD_CLIENTE ELSE CONVERT(INT,@CD_CLIENTE) END
 
GROUP BY  
Y.CD_CLIENTE,CD_CPFCGC,T1.NM_CLIENTE,T1.DT_CRIACAO,T1.IN_POLITICO_EXP,
T1.IN_PESS_VINC,T1.TP_SITUAC, T1.IN_SITUAC,F.CIDADE

ORDER BY 1      
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
 FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;