CREATE PROCEDURE [dbo].[PR_CONTROLE_MANIPULACAO_BVSP] @INICIO SMALLDATETIME , @FIM SMALLDATETIME ,  
@CLIENTE INT , @CD_PAPEL VARCHAR(10),@QTDPORPAGINA INT,@PAGINA INT
------ HML: quando tiver linha sem preço abertura etc, conferir no robo do breno, geralemnte está vazio lá por conta dos dados fakes.
AS

--DECLARE @INICIO SMALLDATETIME , @FIM SMALLDATETIME, @CLIENTE INT, @CD_PAPEL VARCHAR(10) , @PAGINA       INT = 1    ,@QTDPORPAGINA INT  =50   
--    SET @INICIO='2024-01-29'
--    SET @FIM='2024-01-29'
--    SET @CD_PAPEL=''--'GOLL4T'--'BBSE3F'
--    SET @CLIENTE=''--'505787'

	SELECT FORMAT(A.DT_PERIODO,'d','PT-BR')						  AS [DATA]
		 , A.CD_CLIENTE											  AS [COD CLIENTE]
		 , B.NM_CLIENTE											  AS [NOME CLIENTE]
		 , A.CD_PAPEL											  AS [ATIVO]
		 , A.PRAZOT												  AS [PRAZO A TERMO]
		 , A.CD_CLIENTE_BRO										  AS [COD BROKER]
		 , C.NM_CLIENTE											  AS [NOME BROKER]
		 , A.INDICE_BVSP										  AS [INDICE BVSP]
		 , FORMAT(A.PREABE,'F','PT-BR')							  AS [PRECO ABERTURA MERC]
		 , FORMAT(A.PRECO_MAX_MERCADO,'F','PT-BR')				  AS [PREÇO MAX MERC]
		 , FORMAT(A.PRECO_MIN_MERCADO,'F','PT-BR')				  AS [PREÇO MIN MERC]
		 , FORMAT(A.PREMED,'F','PT-BR')							  AS [PRECO MED MERC]		 
		 , FORMAT(A.PREULT,'F','PT-BR')							  AS [PRECO FECHAMENTO MERC]	
		 , FORMAT(A.VOLUME_MERCADO,'F','PT-BR')					  AS [VOLUME MERCADO]
		 , FORMAT(A.VOLUME_MERCADO_ANT,'F','PT-BR')				  AS [VOLUME MERCADO ANT]
		 , A.VARIACAO_MERCADO_STRING							  AS [VARIACAO MERCADO]
		 , A.QTD_NEGOCIOS_MERCADO								  AS [QTD NEG MERC]
		 , FORMAT(A.VOLUME,'F','PT-BR')							  AS [VOLUME CLIENTE]
		 , FORMAT(A.VOLUME_CLIENTE_ANT,'F','PT-BR')				  AS [VOLUME CLIENTE ANT]
		 , FORMAT(A.VOL_MED_ATUAL,'F','PT-BR')					  AS [VOLUME MED]
		 , A.VARIACAO_CLIENTE_STRING							  AS [VARIACAO CLIENTE]		 
		 , A.PERC_CLIENTE_MERCADO_STRING						  AS [VARIACAO CLIENTE X MERC]
		 , CASE WHEN A.IND_LEILAO = 'S' THEN 'SIM' ELSE 'NÃO' END AS [LEILÃO]
		 , FORMAT(A.VL_NEGOCIO_ABERTURA,'F','PT-BR')			  AS [PRECO DE ABERTURA CLIENTE]
		 , FORMAT(A.VL_NEGOCIO_FECHAMENTO,'F','PT-BR')			  AS [PRECO DE FECHAMENTO CLIENTE]
		 , FORMAT(A.VL_NEGOCIO_MIN,'F','PT-BR')					  AS [PREÇO MIN CLIENTE]
		 , FORMAT(A.VL_NEGOCIO_MAX,'F','PT-BR')					  AS [PREÇO MAX CLIENTE]
		 , FORMAT(A.VL_NEGOCIO_AVG,'F','PT-BR')					  AS [PREÇO MED CLIENTE]
		 , A.QTD_NEGOCIO										  AS [QTD NEGOCIO CLIENTE]		 
		 , A.INTRADAY_CLIENTE_STRING							  AS [INTRADAY CLIENTE]
		 , A.INTERDAY_CLIENTE_STRING							  AS [INTERDAY CLIENTE]
		 , A.INTRADAY_MERCADO_STRING							  AS [INTRADAY MERCADO]
		 , A.INTERDAY_MERCADO_STRING							  AS [INTERDAY MERCADO]
	  FROM ST_MANIPULACAO_BVSP A
 LEFT JOIN V_CLIENTE_TODOS B 
	    ON A.CD_CLIENTE = B.CD_CLIENTE
 LEFT JOIN V_CLIENTE_TODOS C 
	    ON A.CD_CLIENTE_BRO = C.CD_CLIENTE

	 WHERE A.DT_PERIODO >= @INICIO
	   AND A.DT_PERIODO <= @FIM
	   AND A.CD_CLIENTE = CASE WHEN ISNULL(@CLIENTE,'') ='' THEN A.CD_CLIENTE ELSE @CLIENTE END
	   AND CD_PAPEL = CASE WHEN ISNULL(@CD_PAPEL,'') ='' THEN CD_PAPEL ELSE @CD_PAPEL END

  ORDER BY A.CD_CLIENTE
		 , A.CD_PAPEL
		 , A.DT_PERIODO

	OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
	FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;