CREATE PROCEDURE [dbo].[FIRA_PR_CARGA_ST_CONTROLE_VINCULADOS] @PREGAO DATETIME , @PREGAOFIM DATETIME
 
AS


DROP TABLE IF EXISTS [dbo].[ST_CONTROLE_VINCULADOS_PADRAO]
    CREATE TABLE [dbo].[ST_CONTROLE_VINCULADOS_PADRAO] (
    [CD_CLIENTE_COMPRA] [int] NOT NULL,
	[NM_CLIENTE_COMPRA] [varchar](400) NULL,
	[VINC_COMPRA] [char](1) NULL,
	[CD_CLIENTE_BRO_COMPRA] [int] NOT NULL,
	[CD_CLIENTE_VENDA] [int] NULL,
	[NM_CLIENTE_VENDA] [varchar](400) NULL,
	[VINC_VENDA] [char](1) NULL,
	[CD_CLIENTE_BRO_VENDA] [int] NULL,
	[DT_PERIODO] [smalldatetime] NOT NULL,
	[SISTEMA_COMPRA] [varchar](40) NULL,
	[SISTEMA_VENDA] [varchar](40) NULL,
	[NR_NEGOCIO] [int] NOT NULL,
	[QT_NEGOCIO_COMPRA] [float] NOT NULL,
	[QT_NEGOCIO_VENDA] [float] NULL,
	[CD_PAPEL] [varchar](50) NOT NULL,
	[HH_COMPRA] [varchar](5) NULL,
	[HH_VENDA] [varchar](5) NULL,
	[VL_TOTNEG_COMPRA] [float] NULL,
	[VL_TOTNEG_VENDA] [float] NULL,
	[VL_NEGOCIO_COMPRA] [float] NULL,
	[VL_NEGOCIO_VENDA] [float] NULL,
	[CD_ASSESSOR_COMPRA] [int] NULL,
	[DS_ASSESSOR_COMPRA] [varchar](60) NULL,
	[CD_ASSESSOR_VENDA] [int] NULL,
	[DS_ASSESSOR_VENDA] [varchar](60) NULL,
	[DS_TIPO_OFERTA] [varchar](6) NOT NULL,
	[SALDO_CC] [numeric](15, 2) NULL,
	[POSI_PAPEL_LIVRE] [float] NULL,
	[POSI_GARANTIAS] [float] NULL,
	[DT_FIRA] DATETIME NULL
) ON [PRIMARY];

/***************************************************
inicio da comparação entre a tabela
da base padrao fira origem x tabela cliente destino
*****************************************************/
EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo',, @src_table='ST_CONTROLE_VINCULADOS_PADRAO',
  @schema_name='dbo', @base_table='ST_CONTROLE_VINCULADOS',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1;



--DECLARE  @PREGAO DATETIME , @PREGAOFIM DATETIME 
--SET @PREGAO ='20250701'
--SET @PREGAOFIM ='20260101'


/****************************	
	CARGA ST_CONTROLE_VINCULADOS		
****************************/     

drop table if exists #v_cliente_todos
select cd_cliente,NM_CLIENTE,IN_PESS_VINC,CD_ASSESSOR, NM_ASSESSOR 
into #v_cliente_todos
from ST_DADOS_BASICOS_PF
group by cd_cliente,NM_CLIENTE,IN_PESS_VINC,CD_ASSESSOR, NM_ASSESSOR

insert into #v_cliente_todos
select cd_cliente,NM_CLIENTE,IN_PESS_VINC,CD_ASSESSOR, NM_ASSESSOR 
from ST_DADOS_BASICOS_PF
group by cd_cliente,NM_CLIENTE,IN_PESS_VINC,CD_ASSESSOR, NM_ASSESSOR




WHILE @PREGAO < @PREGAOFIM 	
BEGIN	

	DELETE FROM ST_CONTROLE_VINCULADOS	WHERE DT_PERIODO = @PREGAO	
	
	
	/*******************************
	  #### PRIMEIRO PROCESSO  ####
	*******************************/ 
			
		INSERT INTO ST_CONTROLE_VINCULADOS	
		(
		 CD_CLIENTE_COMPRA,NM_CLIENTE_COMPRA,VINC_COMPRA,CD_CLIENTE_BRO_COMPRA,CD_CLIENTE_VENDA,NM_CLIENTE_VENDA
		,VINC_VENDA,CD_CLIENTE_BRO_VENDA,DT_PERIODO,SISTEMA_COMPRA,SISTEMA_VENDA,NR_NEGOCIO,QT_NEGOCIO_COMPRA,QT_NEGOCIO_VENDA
		,CD_PAPEL,HH_COMPRA,HH_VENDA,VL_TOTNEG_COMPRA,VL_TOTNEG_VENDA,VL_NEGOCIO_COMPRA,VL_NEGOCIO_VENDA,CD_ASSESSOR_COMPRA
		,DS_ASSESSOR_COMPRA,CD_ASSESSOR_VENDA,DS_ASSESSOR_VENDA,DS_TIPO_OFERTA,SALDO_CC,POSI_PAPEL_LIVRE,POSI_GARANTIAS
		)
		SELECT 
			[CD_CLIENTE_COMPRA],
			[NM_CLIENTE_COMPRA],
			[VINC_COMPRA],
			CD_CLIENTE_BRO_COMPRA,
			[CD_CLIENTE_VENDA],
			[NM_CLIENTE_VENDA],
			[VINC_VENDA],
			CD_CLIENTE_BRO_VENDA,
			[DT_PERIODO],
			NULL SISTEMA_COMPRA,
			NULL SISTEMA_VENDA,
			[NR_NEGOCIO],
			[QT_NEGOCIO_COMPRA],
			[QT_NEGOCIO_VENDA],
			[CD_PAPEL],
			[HH_COMPRA],
			[HH_VENDA],
			[VL_TOTNEG_COMPRA],
			[VL_TOTNEG_VENDA],
			[VL_NEGOCIO_COMPRA],
			[VL_NEGOCIO_VENDA],
			[CD_ASSESSOR_COMPRA],
			[DS_ASSESSOR_COMPRA],
			[CD_ASSESSOR_VENDA],
			[DS_ASSESSOR_VENDA], 
			'COMPRA' DS_TIPO_OFERTA, 	
			
			--(SELECT TOP 1 VL_DISPONIVEL FROM ST_SALDO WHERE ST_DIRETAS_BVSP.DT_PERIODO = ST_SALDO.DATA AND ST_DIRETAS_BVSP.CD_CLIENTE_COMPRA=ST_SALDO.CD_CLIENTE) 
			NULL AS SALDO_CC,	
			
			--(SELECT TOP 1 QTDE_DISP FROM ST_CUSTODIA	
			-- WHERE 
			--	 ST_DIRETAS_BVSP.DT_PERIODO = ST_CUSTODIA.DT_CUSTODIA 	
			-- AND ST_DIRETAS_BVSP.CD_CLIENTE_COMPRA = ST_CUSTODIA.CD_CLIENTE 	
			-- AND ST_DIRETAS_BVSP.CD_PAPEL = ST_CUSTODIA.COD_NEG 	
			-- AND ST_CUSTODIA.DESC_CARTEIRA = 'CARTEIRA LIVRE') 
			 NULL AS POSI_PAPEL_LIVRE, 
			 
			--(SELECT TOP 1 QTDE_DISP FROM ST_CUSTODIA	
			-- WHERE 
			--	 ST_DIRETAS_BVSP.DT_PERIODO = ST_CUSTODIA.DT_CUSTODIA
			-- AND ST_DIRETAS_BVSP.CD_CLIENTE_COMPRA = ST_CUSTODIA.CD_CLIENTE
			-- AND ST_DIRETAS_BVSP.CD_PAPEL = ST_CUSTODIA.COD_NEG	
			-- AND ST_CUSTODIA.DESC_CARTEIRA = 'GARANTIAS DE DERIVATIVOS/BTC') 
			 NULL AS POSI_GARANTIAS
			
			 
		FROM [ST_DIRETAS_BVSP]	
		WHERE 
			VINC_COMPRA = 'S'
		AND DT_PERIODO = @PREGAO	

 
	
	
	/*****************************
	  #### SEGUNDO PROCESSO  ####
	*****************************/
 
		
		INSERT INTO ST_CONTROLE_VINCULADOS	
		(
		 CD_CLIENTE_COMPRA,NM_CLIENTE_COMPRA,VINC_COMPRA,CD_CLIENTE_BRO_COMPRA,CD_CLIENTE_VENDA,NM_CLIENTE_VENDA
		,VINC_VENDA,CD_CLIENTE_BRO_VENDA,DT_PERIODO,SISTEMA_COMPRA,SISTEMA_VENDA,NR_NEGOCIO,QT_NEGOCIO_COMPRA,QT_NEGOCIO_VENDA
		,CD_PAPEL,HH_COMPRA,HH_VENDA,VL_TOTNEG_COMPRA,VL_TOTNEG_VENDA,VL_NEGOCIO_COMPRA,VL_NEGOCIO_VENDA,CD_ASSESSOR_COMPRA
		,DS_ASSESSOR_COMPRA,CD_ASSESSOR_VENDA,DS_ASSESSOR_VENDA,DS_TIPO_OFERTA,SALDO_CC,POSI_PAPEL_LIVRE,POSI_GARANTIAS
		)
		SELECT 
			CD_CLIENTE, 
			NM_CLIENTE, 
			IN_PESS_VINC, 
			CD_CLIENTE_BRO, 
			A, 
			AA, 
			AAA, 
			AAAAAAAAAAAAAAAAA,	
			DT_PERIODO, 
			DS_SISTEMA_ORIGEM, 
			AAAA, 
			NR_NEGOCIO, 
			QT_MULTIPLICADOR, 
			AAAAA, 
			CD_PAPEL, 
			HH_NEGOCIO, 
			AAAAAA,	
			VL_TOTNEG, 
			AAAAAAA, 
			VL_NEGOCIO, 
			AAAAAAAA, 
			CD_ASSESSOR, 
			NM_ASSESSOR, 
			AAAAAAAAA, 
			AAAAAAAAAA, 
			NATOPE,	
			SALDO_CC,		
			POSI_PAPEL_LIVRE,
			POSI_GARANTIAS 
		
		FROM(
			SELECT 
				CO.CD_CLIENTE, 
				VCT.NM_CLIENTE, 
				VCT.IN_PESS_VINC, 
				CO.CD_CLIENTE_BRO, 
				NULL AS A, 
				NULL AS AA, 
				NULL AS AAA, 
				NULL AS AAAAAAAAAAAAAAAAA,	
				CO.DT_NEGOCIO AS DT_PERIODO, 
				NULL AS DS_SISTEMA_ORIGEM, 
				NULL AS AAAA, 
				CO.NR_NEGOCIO, 
				CO.QT_MULTIPLICADOR, 
				NULL AS AAAAA, 
				CO.CD_PAPEL, 
				CO.HH_NEGOCIO, 
				NULL AS AAAAAA,	
				CO.VL_TOTNEG, 
				NULL AS AAAAAAA, 
				CO.VL_NEGOCIO, 
				NULL AS AAAAAAAA, 
				VCT.CD_ASSESSOR, 
				VCT.NM_ASSESSOR, 
				NULL AS AAAAAAAAA, 
				NULL AS AAAAAAAAAA, 
				'COMPRA' NATOPE,	

				--(SELECT TOP 1 VL_DISPONIVEL 
				--  FROM ST_SALDO	
				--  WHERE 
				--	  CO.DT_NEGOCIO = ST_SALDO.DATA	
				--  AND VCT.CD_CLIENTE = ST_SALDO.CD_CLIENTE) 
				  NULL AS SALDO_CC,	
					
				--(SELECT TOP 1 QTDE_DISP 
				--  FROM ST_CUSTODIA	
				--  WHERE 
				--	  CO.DT_NEGOCIO = ST_CUSTODIA.DT_CUSTODIA 	
				--  AND CO.CD_PAPEL = ST_CUSTODIA.COD_NEG 	
				--  AND VCT.CD_CLIENTE = ST_CUSTODIA.CD_CLIENTE 	
				--  AND ST_CUSTODIA.DESC_CARTEIRA = 'CARTEIRA LIVRE') 
				  NULL AS POSI_PAPEL_LIVRE,
							
				--(SELECT TOP 1 QTDE_DISP 
				--  FROM ST_CUSTODIA	
				--  WHERE 
				--	  CO.DT_NEGOCIO = ST_CUSTODIA.DT_CUSTODIA 	
				--  AND CO.CD_PAPEL = ST_CUSTODIA.COD_NEG 	
				--  AND ST_CUSTODIA.DESC_CARTEIRA = 'GARANTIAS DE DERIVATIVOS/BTC') 
				  NULL AS POSI_GARANTIAS
				  
					
			FROM #V_CLIENTE_TODOS VCT
			INNER JOIN ST_CORRETAGEM_ORDEM CO
				ON VCT.CD_CLIENTE = CO.CD_CLIENTE
			WHERE	
				VCT.IN_PESS_VINC = 'S'
			AND CO.CD_NATOPE ='C' 
		) XX	
		WHERE
			XX.DT_PERIODO = @PREGAO		
		AND NOT EXISTS (SELECT NR_NEGOCIO, QT_MULTIPLICADOR 
						FROM ST_DIRETAS_BVSP A	
						WHERE 
							A.CD_CLIENTE_COMPRA = XX.CD_CLIENTE 	
						AND A.NR_NEGOCIO = XX.NR_NEGOCIO 	
						AND A.DT_PERIODO = XX.DT_PERIODO 	
						AND A.CD_PAPEL =XX.CD_PAPEL 	
						)	
	 
	 
		 
		 
	/******************************
	  #### TERCEIRO PROCESSO  ####
	******************************/
	
	 	
		
		INSERT INTO ST_CONTROLE_VINCULADOS	
		(
		 CD_CLIENTE_COMPRA,NM_CLIENTE_COMPRA,VINC_COMPRA,CD_CLIENTE_BRO_COMPRA,CD_CLIENTE_VENDA,NM_CLIENTE_VENDA
		,VINC_VENDA,CD_CLIENTE_BRO_VENDA,DT_PERIODO,SISTEMA_COMPRA,SISTEMA_VENDA,NR_NEGOCIO,QT_NEGOCIO_COMPRA,QT_NEGOCIO_VENDA
		,CD_PAPEL,HH_COMPRA,HH_VENDA,VL_TOTNEG_COMPRA,VL_TOTNEG_VENDA,VL_NEGOCIO_COMPRA,VL_NEGOCIO_VENDA,CD_ASSESSOR_COMPRA
		,DS_ASSESSOR_COMPRA,CD_ASSESSOR_VENDA,DS_ASSESSOR_VENDA,DS_TIPO_OFERTA,SALDO_CC,POSI_PAPEL_LIVRE,POSI_GARANTIAS
		)
		SELECT 
			CD_CLIENTE, 
			NM_CLIENTE, 
			IN_PESS_VINC, 
			CD_CLIENTE_BRO, 
			A, 
			AA, 
			AAA, 
			AAAAAAAAAAAAAAAAA,	
			DT_PERIODO, 
			DS_SISTEMA_ORIGEM, 
			AAAA, 
			NR_NEGOCIO, 
			QT_MULTIPLICADOR, 
			AAAAA, 
			CD_PAPEL, 
			HH_NEGOCIO, 
			AAAAAA,	
			VL_TOTNEG, 
			AAAAAAA, 
			VL_NEGOCIO, 
			AAAAAAAA, 
			CD_ASSESSOR, 
			NM_ASSESSOR, 
			AAAAAAAAA, 
			AAAAAAAAAA, 
			NATOPE,	
			SALDO_CC,
			POSI_PAPEL_LIVRE,
			POSI_GARANTIAS
		
		FROM(
			SELECT 
				CO.CD_CLIENTE, 
				VCT.NM_CLIENTE, 
				VCT.IN_PESS_VINC, 
				CO.CD_CLIENTE_BRO, 
				NULL AS A, 
				NULL AS AA, 
				NULL AS AAA, 
				NULL AS AAAAAAAAAAAAAAAAA,	
				CO.DT_NEGOCIO AS DT_PERIODO, 
				NULL AS DS_SISTEMA_ORIGEM, 
				NULL AS AAAA, 
				CO.NR_NEGOCIO, 
				CO.QT_MULTIPLICADOR, 
				NULL AS AAAAA, 
				CO.CD_PAPEL, 
				CO.HH_NEGOCIO, 
				NULL AS AAAAAA,	
				CO.VL_TOTNEG, 
				NULL AS AAAAAAA, 
				CO.VL_NEGOCIO, 
				NULL AS AAAAAAAA, 
				VCT.CD_ASSESSOR, 
				VCT.NM_ASSESSOR, 
				NULL AS AAAAAAAAA, 
				NULL AS AAAAAAAAAA, 
				'VENDA' NATOPE,	

				--(SELECT TOP 1 VL_DISPONIVEL 
				--  FROM ST_SALDO	
				--  WHERE 
				--	  CO.DT_NEGOCIO = ST_SALDO.DATA	
				--  AND VCT.CD_CLIENTE = ST_SALDO.CD_CLIENTE) 
				  NULL AS SALDO_CC	,
					
				--(SELECT TOP 1 QTDE_DISP 
				--  FROM ST_CUSTODIA	
				--  WHERE 
				--	  CO.DT_NEGOCIO = ST_CUSTODIA.DT_CUSTODIA 	
				--  AND CO.CD_PAPEL = ST_CUSTODIA.COD_NEG 	
				--  AND VCT.CD_CLIENTE = ST_CUSTODIA.CD_CLIENTE 	
				--  AND ST_CUSTODIA.DESC_CARTEIRA = 'CARTEIRA LIVRE') 
				  NULL AS POSI_PAPEL_LIVRE,
							
				--(SELECT TOP 1 QTDE_DISP 
				--  FROM ST_CUSTODIA	
				--  WHERE 
				--	  CO.DT_NEGOCIO = ST_CUSTODIA.DT_CUSTODIA 	
				--  AND CO.CD_PAPEL = ST_CUSTODIA.COD_NEG 	
				--  AND ST_CUSTODIA.DESC_CARTEIRA = 'GARANTIAS DE DERIVATIVOS/BTC') 
				  NULL AS POSI_GARANTIAS
				 
					
			FROM #V_CLIENTE_TODOS VCT
			INNER JOIN ST_CORRETAGEM_ORDEM CO
				ON VCT.CD_CLIENTE = CO.CD_CLIENTE
			WHERE	
				VCT.IN_PESS_VINC = 'S'
			AND CO.CD_NATOPE ='V' 
		) XX	
		WHERE
			XX.DT_PERIODO = @PREGAO		
		AND NOT EXISTS (SELECT NR_NEGOCIO, QT_MULTIPLICADOR 
						FROM ST_DIRETAS_BVSP A	
						WHERE 
							A.CD_CLIENTE_COMPRA = XX.CD_CLIENTE 	
						AND A.NR_NEGOCIO = XX.NR_NEGOCIO 	
						AND A.DT_PERIODO = XX.DT_PERIODO 	
						AND A.CD_PAPEL =XX.CD_PAPEL 	
						)	

	 

	/*****************************
	  ####  QUARTO PROCESSO   ####
	*****************************/ 
	
	 
		
		INSERT INTO ST_CONTROLE_VINCULADOS
		(
		 CD_CLIENTE_COMPRA,NM_CLIENTE_COMPRA,VINC_COMPRA,CD_CLIENTE_BRO_COMPRA,CD_CLIENTE_VENDA,NM_CLIENTE_VENDA
		,VINC_VENDA,CD_CLIENTE_BRO_VENDA,DT_PERIODO,SISTEMA_COMPRA,SISTEMA_VENDA,NR_NEGOCIO,QT_NEGOCIO_COMPRA,QT_NEGOCIO_VENDA
		,CD_PAPEL,HH_COMPRA,HH_VENDA,VL_TOTNEG_COMPRA,VL_TOTNEG_VENDA,VL_NEGOCIO_COMPRA,VL_NEGOCIO_VENDA,CD_ASSESSOR_COMPRA
		,DS_ASSESSOR_COMPRA,CD_ASSESSOR_VENDA,DS_ASSESSOR_VENDA,DS_TIPO_OFERTA,SALDO_CC,POSI_PAPEL_LIVRE,POSI_GARANTIAS
		)
		SELECT 
			[CD_CLIENTE_VENDA],
			[NM_CLIENTE_VENDA],
			[VINC_VENDA], 
			CD_CLIENTE_BRO_VENDA,
			[CD_CLIENTE_COMPRA],
			[NM_CLIENTE_COMPRA],
			[VINC_COMPRA], 
			CD_CLIENTE_BRO_COMPRA,
			[DT_PERIODO],
			NULL SISTEMA_VENDA,
			NULL SISTEMA_COMPRA,
			[NR_NEGOCIO],
			[QT_NEGOCIO_VENDA],
			[QT_NEGOCIO_COMPRA],
			[CD_PAPEL],
			[HH_VENDA],
			[HH_COMPRA],
			[VL_TOTNEG_VENDA]	
			,[VL_TOTNEG_COMPRA],
			[VL_NEGOCIO_VENDA],
			[VL_NEGOCIO_COMPRA],
			[CD_ASSESSOR_VENDA],
			[DS_ASSESSOR_VENDA],
			[CD_ASSESSOR_COMPRA],
			[DS_ASSESSOR_COMPRA], 
			'VENDA' NATOPE,	
			
			--(SELECT TOP 1 VL_DISPONIVEL 
			-- FROM ST_SALDO	
			-- WHERE 
			--	 ST_DIRETAS_BVSP.DT_PERIODO = ST_SALDO.DATA 	
			-- AND ST_DIRETAS_BVSP.CD_CLIENTE_VENDA = ST_SALDO.CD_CLIENTE  ) 
			 NULL AS SALDO_CC,
			   
			--(SELECT TOP 1 QTDE_DISP 
			-- FROM ST_CUSTODIA	
			-- WHERE 
			--	 ST_DIRETAS_BVSP.DT_PERIODO = ST_CUSTODIA.DT_CUSTODIA 	
			-- AND ST_DIRETAS_BVSP.CD_CLIENTE_VENDA = ST_CUSTODIA.CD_CLIENTE 	
			-- AND ST_DIRETAS_BVSP.CD_PAPEL = ST_CUSTODIA.COD_NEG 	
			-- AND ST_CUSTODIA.DESC_CARTEIRA = 'CARTEIRA LIVRE') 
			 NULL AS POSI_PAPEL_LIVRE,
			 
			--(SELECT TOP 1 QTDE_DISP 
			-- FROM ST_CUSTODIA	
			-- WHERE 
			--	 ST_DIRETAS_BVSP.DT_PERIODO = ST_CUSTODIA.DT_CUSTODIA 	
			-- AND ST_DIRETAS_BVSP.CD_CLIENTE_VENDA = ST_CUSTODIA.CD_CLIENTE 	
			-- AND ST_DIRETAS_BVSP.CD_PAPEL = ST_CUSTODIA.COD_NEG 	
			-- AND ST_CUSTODIA.DESC_CARTEIRA = 'GARANTIAS DE DERIVATIVOS/BTC') 
			 NULL AS POSI_GARANTIAS

		
		FROM [ST_DIRETAS_BVSP]	
		WHERE 
			VINC_VENDA= 'S'	
		AND DT_PERIODO = @PREGAO		

	

SET @PREGAO = @PREGAO +1

END	


-- ================================================
-- Marca DT_FIRA para registros carregados (fallback)
-- ================================================
DECLARE @__dt_fira_now DATETIME = GETDATE();
IF COL_LENGTH(N'dbo.ST_BMF_NEGOCIOS', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE [dbo].[ST_BMF_NEGOCIOS]
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL;
END


/******* fim do processo de carga **********/

--passo 3
/***** limpa a tabela do banco para nao ficar sujeira ******/
DROP TABLE IF EXISTS ST_CONTROLE_VINCULADOS_PADRAO