CREATE PROCEDURE [dbo].[FIRA_PR_CARGA_OCORRENCIA]
AS
DECLARE @ERROR_NUMBER INT
	   ,@ERROR_MESSAGE NVARCHAR(200)
	   ,@ERROR_LINE INT
	   ,@ERRO VARCHAR(200)
	   ,@SUCESSO BIT = 1
	   ,@TIPO INT 
	   ,@IDPROCESSO INT
	   ,@PROCESSO VARCHAR(20)
		
	   ---VARIAVEIS DO PROCESSO DE EXECUCÃO DA CARGA
	   ,@PROCESSO_INI  INT
	   ,@PROCESSO_FIM INT
		
	   ---VARIAVEIS PARA CARGA
	   ,@PREGAO SMALLDATETIME
	   ,@AUX INT
	   ,@DIA_UTIL INT

DECLARE @TIPO_OCORRENCIA VARCHAR(50)
SET @PREGAO = GETDATE()

/** PEGA O QUARTO DIA UTIL DO MES **/
SET @DIA_UTIL = DBO.DIA_UTIL(@PREGAO)--(SELECT count(1) FROM ST_PERIODO WHERE CD_ANO  = YEAR(@PREGAO) AND CD_MES  = MONTH(@PREGAO) AND CD_DIA <= DAY(@PREGAO) AND and DATEPART(WEEKDAY, DT_PERIODO) NOT IN (7,1));

IF @DIA_UTIL = (SELECT MAX(CD_PARAMETRO) FROM ST_CLIENTE_PARAMETROS WHERE DS_PARAMETRO  = 'DIA_UTIL')
BEGIN

SET @TIPO_OCORRENCIA = (SELECT MAX(CD_PARAMETRO) FROM ST_CLIENTE_PARAMETROS WHERE DS_PARAMETRO = 'OCORRENCIA')

EXEC FIRA_PR_LOG @ERROR_NUMBER,@ERROR_MESSAGE,@ERROR_LINE, 1,'CARGA_OCORRENCIAS', 9997	
BEGIN  TRY

		PRINT 'TIPO OCORRENCIA: ' + @TIPO_OCORRENCIA 

		IF @TIPO_OCORRENCIA = 'POR_CLIENTE'
		BEGIN

			PRINT 'GEREÇÃO DE OCORRÊNCIAS POR CLIENTE EM EXECUÇÃO';

				EXEC FIRA_PR_CARGA_OCORRENCIA_POR_CLIENTE;

		END

		IF @TIPO_OCORRENCIA = 'POR_ALERTA'
		BEGIN

			PRINT 'GEREÇÃO DE OCORRÊNCIAS POR ALERTA EM EXECUÇÃO';

			EXEC FIRA_PR_CARGA_OCORRENCIA_POR_ALERTA;

		END
END TRY

	BEGIN CATCH
		SET @SUCESSO		= 0 
		SET @TIPO 			= 3
		SET @ERROR_MESSAGE  = ERROR_MESSAGE()		
		SET @PROCESSO 		= 'CARGA_OCORRENCIAS'
		SET @IDPROCESSO 	= 9997

		EXEC FIRA_PR_LOG @ERROR_NUMBER, @ERROR_MESSAGE, @ERROR_LINE,  @TIPO, @PROCESSO, @IDPROCESSO  RAISERROR(@ERROR_MESSAGE,16,1)
			
	END CATCH

	IF(@SUCESSO = 1)
	BEGIN

		EXEC FIRA_PR_LOG @ERROR_NUMBER,@ERROR_MESSAGE,@ERROR_LINE, 2,'CARGA_OCORRENCIAS',9997
	END
	PRINT 'FIM DA CARGA CARGA_OCORRENCIAS'
END