CREATE PROCEDURE [dbo].[FIRA_PR_CARGA_ALERT_08_OMG_BMF] @PREGAO SMALLDATETIME, @AUX INT
AS
/*************************************************************************************************
REGRA DO ALERTA:
Identifica clientes com algum tipo de vínculo entre si, quando as operações realizadas
dentro desse grupo representam mais de 10% das operações totais do cliente no mês.
 
 schema alinhado ao Relatório OMG-BMF:
  * Colunas da tabela do alerta com os nomes do relatório:
       DATA            (MANTIDA — populada com DATEADD(DAY,-@AUX,@PREGAO))
       CD_CLIENTE_ENC  -> CD_CONTRAPARTE
       VOLUME          -> QTD_CONTRATO_MES_GRUPO
       (adicionada)    -> QTD_CONTRATO_CLIENTE
       (adicionada)    -> NR_NEGOCIO    (texto "CD_PAPEL:NR_NEGOCIO; ...")
       QTD_NEGOCIO_TOTAL_MES (REMOVIDA — não existe no relatório)
       QTD_NEGOCIO_MES_GRUPO (mantida)
       CONCENTRACAO          (mantida)
       CD_CPFCGC             (mantida)
       DT_FIRA               (mantida — operacional)
  * Lógica de cálculo idêntica ao relatório:
       - QTD_CONTRATO via SUM(ISNULL(QT_QTDDET,0)) de ST_BMF_NEGOCIOS_NC
       - CONCENTRACAO = QTD_CONTRATO_MES_GRUPO / QTD_CONTRATO_CLIENTE * 100
       - Atribuição do negócio ao COMPRADOR (#VINCULO simétrica cobre o vendedor)
       - GRUPO restrito a (CD_CLIENTE, DT_NEGOCIO, NR_NEGOCIO) presentes em ST_DIRETAS_BMF
       - NR_NEGOCIO no formato "CD_PAPEL:NR_NEGOCIO; ..." (ex.: DI1F31:40)
  * Regra do alerta preservada: CONCENTRACAO > 10
 
  v4: STRING_AGG substituído por STUFF + FOR XML PATH (compat com SQL Server < 2017).
*************************************************************************************************/


-- ============== RENAMES ==============
-- A ideia é que, independente do nome em que a coluna está hoje, ela termine
-- com o nome novo. Cada bloco só faz o sp_rename se o nome antigo existir
-- e o nome novo ainda não existir.

-- ----- VOLUME / RESULTADO_OMG / QTD_CONTRATO_GRUPO -> QTD_CONTRATO_MES_GRUPO -----
--IF COL_LENGTH('dbo.ST_ALERT_OMG_BMF_PADRAO','VOLUME') IS NOT NULL
--   AND COL_LENGTH('dbo.ST_ALERT_OMG_BMF_PADRAO','QTD_CONTRATO_MES_GRUPO') IS NULL
--    EXEC sp_rename 'dbo.ST_ALERT_OMG_BMF_PADRAO.VOLUME', 'QTD_CONTRATO_MES_GRUPO', 'COLUMN';

--IF COL_LENGTH('dbo.ST_ALERT_OMG_BMF_PADRAO','RESULTADO_OMG') IS NOT NULL
--   AND COL_LENGTH('dbo.ST_ALERT_OMG_BMF_PADRAO','QTD_CONTRATO_MES_GRUPO') IS NULL
--    EXEC sp_rename 'dbo.ST_ALERT_OMG_BMF_PADRAO.RESULTADO_OMG', 'QTD_CONTRATO_MES_GRUPO', 'COLUMN';

--IF COL_LENGTH('dbo.ST_ALERT_OMG_BMF_PADRAO','QTD_CONTRATO_GRUPO') IS NOT NULL
--   AND COL_LENGTH('dbo.ST_ALERT_OMG_BMF_PADRAO','QTD_CONTRATO_MES_GRUPO') IS NULL
--    EXEC sp_rename 'dbo.ST_ALERT_OMG_BMF_PADRAO.QTD_CONTRATO_GRUPO', 'QTD_CONTRATO_MES_GRUPO', 'COLUMN';

---- ----- CD_CLIENTE_ENC -> CD_CONTRAPARTE -----
--IF COL_LENGTH('dbo.ST_ALERT_OMG_BMF_PADRAO','CD_CLIENTE_ENC') IS NOT NULL
--   AND COL_LENGTH('dbo.ST_ALERT_OMG_BMF_PADRAO','CD_CONTRAPARTE') IS NULL
--    EXEC sp_rename 'dbo.ST_ALERT_OMG_BMF_PADRAO.CD_CLIENTE_ENC', 'CD_CONTRAPARTE', 'COLUMN';



---- Mesmo conjunto de renames na tabela LIVE:
--IF OBJECT_ID('dbo.ST_ALERT_OMG_BMF','U') IS NOT NULL
--BEGIN
--    IF COL_LENGTH('dbo.ST_ALERT_OMG_BMF','VOLUME') IS NOT NULL
--       AND COL_LENGTH('dbo.ST_ALERT_OMG_BMF','QTD_CONTRATO_MES_GRUPO') IS NULL
--        EXEC sp_rename 'dbo.ST_ALERT_OMG_BMF.VOLUME', 'QTD_CONTRATO_MES_GRUPO', 'COLUMN';

--    IF COL_LENGTH('dbo.ST_ALERT_OMG_BMF','RESULTADO_OMG') IS NOT NULL
--       AND COL_LENGTH('dbo.ST_ALERT_OMG_BMF','QTD_CONTRATO_MES_GRUPO') IS NULL
--        EXEC sp_rename 'dbo.ST_ALERT_OMG_BMF.RESULTADO_OMG', 'QTD_CONTRATO_MES_GRUPO', 'COLUMN';

--    IF COL_LENGTH('dbo.ST_ALERT_OMG_BMF','QTD_CONTRATO_GRUPO') IS NOT NULL
--       AND COL_LENGTH('dbo.ST_ALERT_OMG_BMF','QTD_CONTRATO_MES_GRUPO') IS NULL
--        EXEC sp_rename 'dbo.ST_ALERT_OMG_BMF.QTD_CONTRATO_GRUPO', 'QTD_CONTRATO_MES_GRUPO', 'COLUMN';

--    IF COL_LENGTH('dbo.ST_ALERT_OMG_BMF','CD_CLIENTE_ENC') IS NOT NULL
--       AND COL_LENGTH('dbo.ST_ALERT_OMG_BMF','CD_CONTRAPARTE') IS NULL
--        EXEC sp_rename 'dbo.ST_ALERT_OMG_BMF.CD_CLIENTE_ENC', 'CD_CONTRAPARTE', 'COLUMN';

--END
 
-- ============== CREATE TABLE PADRAO (schema alinhado ao relatório, mantendo DATA) ==============
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ST_ALERT_OMG_BMF_PADRAO]') AND type in (N'U'))
CREATE TABLE [dbo].[ST_ALERT_OMG_BMF_PADRAO](
    [DATA] [date] NULL,
    [CD_CLIENTE] [int] NULL,
    [CD_CPFCGC] [varchar](20) NULL,
    [CD_CONTRAPARTE] [varchar](2000) NULL,
    [VINCULOS] [varchar](500) NULL,
    [NR_NEGOCIO] [varchar](MAX) NULL,
    [QTD_CONTRATO_MES_GRUPO] [decimal](17, 2) NULL,
    [QTD_CONTRATO_CLIENTE] [decimal](17, 2) NULL,
    [CONCENTRACAO] [decimal](17, 2) NULL,
    [QTD_NEGOCIO_MES_GRUPO] [int] NULL,
    [DT_FIRA] DATETIME NULL
) ON [PRIMARY]
 
-- Aplica o sync (vai adicionar NR_NEGOCIO, QTD_CONTRATO_CLIENTE,
-- e remover QTD_NEGOCIO_TOTAL_MES — desde que @allow_drop=1).
EXEC dbo.usp_sync_table_schema_add_alter_2012
  @schema_name='dbo', @base_table='ST_ALERT_OMG_BMF',
  @execute=1, @allow_drop=1, @apply_rename_map=1;



 
--DECLARE @PREGAO SMALLDATETIME, @AUX INT
--SET @PREGAO = '20260105'
--SET @AUX = (SELECT DAY(@PREGAO))
 
DECLARE @INICIO SMALLDATETIME, @FIM SMALLDATETIME;
SET @INICIO = (SELECT MIN(DT_PERIODO) FROM ST_PERIODO WHERE CD_ANOMES = (SELECT MAX(CD_ANOMES) FROM ST_PERIODO WHERE DT_PERIODO = DATEADD(DAY,-@AUX,@PREGAO)));
SET @FIM    = (SELECT MAX(DT_PERIODO) FROM ST_PERIODO WHERE CD_ANOMES = (SELECT MAX(CD_ANOMES) FROM ST_PERIODO WHERE DT_PERIODO = @INICIO));
 
-- Limpa carga anterior da mesma data de referência.
DELETE FROM ST_ALERT_OMG_BMF WHERE DATA = CAST(@PREGAO-@AUX AS DATE);
 
DROP TABLE IF EXISTS #DADOS_BASICOS;
SELECT DISTINCT ST_DADOS_BASICOS_PF.CD_CPFCGC
       ,CD_CLIENTE
       ,NM_CLIENTE
       ,CASE WHEN(SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('|AVENIDA','AC','AH.','AV','AV.','AV:','AVENIDA','AVENIDA:','AVN')) OR
                 (SUBSTRING(NM_LOGRADOURO,1,CHARINDEX('.',NM_LOGRADOURO,1)) in ('|AVENIDA','AC','AH.','AV','AV.','AV:','AVENIDA','AVENIDA:','AVN')) THEN 'AV ' +SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             WHEN SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('AL','AL.','ALAMEDA','ALM','ALMEDA') THEN 'AL' +SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             WHEN SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('DODOVIA','ROD','ROD.','ROD.BR','ROD.MT','RODOVIA') THEN 'ROD'+SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             WHEN SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('ROD''EST','ESTM','ESTR','ESTR.','ESTRADA','ETRADA') THEN 'EST'+SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             WHEN SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('RUA','RUA:') THEN 'R' +SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             WHEN SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('TRAVESSA') THEN 'T' +SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             ELSE SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1))+''+SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
       END NM_LOGRADOURO
       ,NR_PREDIO,NM_COMP_ENDE,NM_BAIRRO,NM_CIDADE,SG_ESTADO,SG_PAIS,CD_CEP
       ,CD_DDD_TEL,REPLACE(NR_TELEFONE,' ','') NR_TELEFONE
       ,NM_E_MAIL,NM_PAI,NM_MAE,NM_CONJUGE,DT_NASC_FUND,DT_CRIACAO
       ,1 TIPO
  INTO #DADOS_BASICOS
  FROM ST_DADOS_BASICOS_PF
 WHERE IN_SITUAC ='A'
   AND EXISTS (SELECT DISTINCT CD_CLIENTE_COMPRA FROM ST_DIRETAS_BMF A
                WHERE A.CD_CLIENTE_COMPRA = ST_DADOS_BASICOS_PF.CD_CLIENTE
                  AND DT_NEGOCIO >= @INICIO AND DT_NEGOCIO <= @FIM)
 
UNION ALL
SELECT DISTINCT ST_DADOS_BASICOS_PJ.CD_CPFCGC
       ,CD_CLIENTE
       ,NM_CLIENTE
       ,CASE WHEN(SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('|AVENIDA','AC','AH.','AV','AV.','AV:','AVENIDA','AVENIDA:','AVN')) OR
                 (SUBSTRING(NM_LOGRADOURO,1,CHARINDEX('.',NM_LOGRADOURO,1)) in ('|AVENIDA','AC','AH.','AV','AV.','AV:','AVENIDA','AVENIDA:','AVN')) THEN 'AV ' +SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             WHEN SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('AL','AL.','ALAMEDA','ALM','ALMEDA') THEN 'AL' +SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             WHEN SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('DODOVIA','ROD','ROD.','ROD.BR','ROD.MT','RODOVIA') THEN 'ROD'+SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             WHEN SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('ROD''EST','ESTM','ESTR','ESTR.','ESTRADA','ETRADA') THEN 'EST'+SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             WHEN SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('RUA','RUA:') THEN 'R' +SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             WHEN SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('TRAVESSA') THEN 'T' +SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             ELSE SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1))+''+SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
       END NM_LOGRADOURO
       ,NR_PREDIO,NM_COMP_ENDE,NM_BAIRRO,NM_CIDADE,SG_ESTADO,SG_PAIS,CD_CEP
       ,CD_DDD_TEL,REPLACE(NR_TELEFONE,' ','') NR_TELEFONE
       ,NM_E_MAIL,NULL,NULL,NULL,DT_NASC_FUND,DT_CRIACAO
       ,0 TIPO
  FROM ST_DADOS_BASICOS_PJ
 WHERE IN_SITUAC ='A'
   AND EXISTS (SELECT DISTINCT CD_CLIENTE_COMPRA FROM ST_DIRETAS_BMF A
                WHERE A.CD_CLIENTE_COMPRA = ST_DADOS_BASICOS_PJ.CD_CLIENTE
                  AND DT_NEGOCIO >= @INICIO AND DT_NEGOCIO <= @FIM);
 
DROP TABLE IF EXISTS #PF;
SELECT DISTINCT A.CD_CLIENTE, A.NM_CLIENTE, A.NM_EMPRESA, A.CPF AS CD_CPFCGC
       , UPPER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(A.NM_EMPRESA, ' ', ''),
                CHAR(9), ''),CHAR(10), ''),CHAR(13), ''),'.', ''),',', ''),';', ''),':', ''),'!', ''),'?', ''),'"', '')
                ,'''', ''),'(', ''),')', ''),'[', ''),']', ''),'{', ''),'}', ''),'/', ''),'\', ''),'|', ''),'@', ''),'#', ''),
                '$', ''),'%', ''),'&', ''),'*', ''),'-', ''),'_', ''),'=', ''),'+', ''),'á','a'),'à','a'),'ã','a'),'â','a'),
                'ä','a'),'é','e'),'è','e'),'ê','e'),'ë','e'),'í','i'),'ì','i'),'î','i'),'ï','i'),'ó','o'),'ò','o'),'õ','o'),
                'ô','o'),'ö','o'),'ú','u'),'ù','u'),'û','u'),'ü','u'),'ç','c'))  AS NM_EMPRESA_LIMPO,
         'PF' TIPO_CLIENTE
  INTO #PF
  FROM ST_DADOS_FINANCEIROS_PF a
 WHERE NM_EMPRESA <> '-'
   AND EXISTS (SELECT DISTINCT CD_CLIENTE_COMPRA FROM ST_DIRETAS_BMF AA
                WHERE AA.CD_CLIENTE_COMPRA = A.CD_CLIENTE
                  AND DT_NEGOCIO >= @INICIO AND DT_NEGOCIO <= @FIM);
 
DROP TABLE IF EXISTS #PJ;
SELECT DISTINCT A.CD_CLIENTE AS CD_CLIENTE, A.NM_CLIENTE AS NM_CLIENTE, A.NM_EMPRESA, A.CPF AS CD_CPFCGC
       , UPPER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(A.NM_CLIENTE, ' ', ''),
                CHAR(9), ''),CHAR(10), ''),CHAR(13), ''),'.', ''),',', ''),';', ''),':', ''),'!', ''),'?', ''),'"', '')
                ,'''', ''),'(', ''),')', ''),'[', ''),']', ''),'{', ''),'}', ''),'/', ''),'\', ''),'|', ''),'@', ''),'#', ''),
                '$', ''),'%', ''),'&', ''),'*', ''),'-', ''),'_', ''),'=', ''),'+', ''),'á','a'),'à','a'),'ã','a'),'â','a'),
                'ä','a'),'é','e'),'è','e'),'ê','e'),'ë','e'),'í','i'),'ì','i'),'î','i'),'ï','i'),'ó','o'),'ò','o'),'õ','o'),
                'ô','o'),'ö','o'),'ú','u'),'ù','u'),'û','u'),'ü','u'),'ç','c'))  AS NM_EMPRESA_LIMPO,
         'PJ' TIPO_CLIENTE
  INTO #PJ
  FROM ST_DADOS_FINANCEIROS_PJ a
 WHERE EXISTS (SELECT DISTINCT CD_CLIENTE_COMPRA FROM ST_DIRETAS_BMF AA
                WHERE AA.CD_CLIENTE_COMPRA = A.CD_CLIENTE
                  AND DT_NEGOCIO >= @INICIO AND DT_NEGOCIO <= @FIM);
 
DROP TABLE IF EXISTS #VINCULO;
-- ENDERECO
SELECT DISTINCT D1.CD_CLIENTE AS CD_CLIENTE_BUSC, D1.CD_CPFCGC AS CD_CPFCGC_BUSC,
       D2.CD_CLIENTE AS CD_CLIENTE_ENC, D2.CD_CPFCGC AS CD_CPFCGC_ENC, 'ENDERECO' AS TIPO_VINCULO
  INTO #VINCULO
  FROM #DADOS_BASICOS D1
  JOIN #DADOS_BASICOS D2
    ON D1.NM_LOGRADOURO = D2.NM_LOGRADOURO AND D1.NR_PREDIO = D2.NR_PREDIO
   AND D1.NM_BAIRRO = D2.NM_BAIRRO AND D1.NM_CIDADE = D2.NM_CIDADE
   AND D1.SG_ESTADO = D2.SG_ESTADO AND D1.SG_PAIS = D2.SG_PAIS AND D1.CD_CEP = D2.CD_CEP
 WHERE D1.CD_CPFCGC <> D2.CD_CPFCGC
   AND D1.NM_LOGRADOURO IS NOT NULL AND D1.NR_PREDIO IS NOT NULL AND D1.NM_BAIRRO IS NOT NULL
   AND D1.NM_CIDADE IS NOT NULL AND D1.SG_ESTADO IS NOT NULL AND D1.SG_PAIS IS NOT NULL
   AND D1.CD_CEP <> ' ' AND D1.NM_LOGRADOURO <> ' ' AND D1.NR_PREDIO <> ' '
   AND D1.NM_BAIRRO <> ' ' AND D1.NM_CIDADE <> ' ' AND D1.SG_ESTADO <> ' '
   AND D1.SG_PAIS <> ' ' AND D1.CD_CEP <> ' '
UNION ALL
-- TELEFONE
SELECT DISTINCT D1.CD_CLIENTE AS CD_CLIENTE_BUSC, D1.CD_CPFCGC AS CD_CPFCGC_BUSC,
       D2.CD_CLIENTE AS CD_CLIENTE_ENC, D2.CD_CPFCGC AS CD_CPFCGC_ENC, 'TELEFONE' AS TIPO_VINCULO
  FROM #DADOS_BASICOS D1
  JOIN #DADOS_BASICOS D2 ON D1.CD_DDD_TEL = D2.CD_DDD_TEL AND D1.NR_TELEFONE = D2.NR_TELEFONE
 WHERE D1.CD_CPFCGC <> D2.CD_CPFCGC
   AND D1.CD_DDD_TEL IS NOT NULL AND D1.NR_TELEFONE IS NOT NULL
   AND D2.CD_DDD_TEL IS NOT NULL AND D2.NR_TELEFONE IS NOT NULL
   AND D1.NR_TELEFONE <> '0' AND D2.NR_TELEFONE <> '0'
UNION ALL
-- E-MAIL
SELECT DISTINCT D1.CD_CLIENTE AS CD_CLIENTE_BUSC, D1.CD_CPFCGC AS CD_CPFCGC_BUSC,
       D2.CD_CLIENTE AS CD_CLIENTE_ENC, D2.CD_CPFCGC AS CD_CPFCGC_ENC, 'E-MAIL' AS TIPO_VINCULO
  FROM #DADOS_BASICOS D1
  JOIN #DADOS_BASICOS D2 ON D1.NM_E_MAIL = D2.NM_E_MAIL
 WHERE D1.CD_CPFCGC <> D2.CD_CPFCGC
   AND D1.NM_E_MAIL IS NOT NULL AND D2.NM_E_MAIL IS NOT NULL
   AND D1.NM_E_MAIL <> ' ' AND D2.NM_E_MAIL <> ' '
UNION ALL
-- PAI E MAE
SELECT DISTINCT D1.CD_CLIENTE AS CD_CLIENTE_BUSC, D1.CD_CPFCGC AS CD_CPFCGC_BUSC,
       D2.CD_CLIENTE AS CD_CLIENTE_ENC, D2.CD_CPFCGC AS CD_CPFCGC_ENC, 'PAI OU MAE' AS TIPO_VINCULO
  FROM #DADOS_BASICOS D1
  JOIN #DADOS_BASICOS D2 ON D1.NM_PAI = D2.NM_PAI AND D1.NM_MAE = D2.NM_MAE
 WHERE D1.CD_CPFCGC <> D2.CD_CPFCGC
   AND (D1.NM_PAI IS NOT NULL OR D1.NM_MAE IS NOT NULL)
   AND (D1.NM_PAI <> ' ' OR D1.NM_MAE <> ' ')
UNION ALL
-- CONJUGE
SELECT DISTINCT D1.CD_CLIENTE AS CD_CLIENTE_BUSC, D1.CD_CPFCGC AS CD_CPFCGC_BUSC,
       D2.CD_CLIENTE AS CD_CLIENTE_ENC, D2.CD_CPFCGC AS CD_CPFCGC_ENC, 'CONJUGE' AS TIPO_VINCULO
  FROM #DADOS_BASICOS D1
  JOIN #DADOS_BASICOS D2 ON D1.NM_CONJUGE = D2.NM_CLIENTE
 WHERE D1.CD_CPFCGC <> D2.CD_CPFCGC
   AND D1.NM_CONJUGE IS NOT NULL AND D1.NM_CONJUGE <> ' '
UNION ALL
-- EMPRESA PF<->PJ
SELECT DISTINCT A.CD_CLIENTE, A.CD_CPFCGC,
       B.CD_CLIENTE AS CD_CLIENTE_ENC, B.CD_CPFCGC AS CD_CPFCGC_ENC, 'EMPRESA' TIPO_VINCULO
  FROM #PF A
  JOIN #PJ B
    ON A.NM_EMPRESA_LIMPO = B.NM_EMPRESA_LIMPO
   AND A.CD_CLIENTE <> B.CD_CLIENTE
 WHERE A.NM_EMPRESA_LIMPO NOT IN ('N','NA','NAO','NAOINFORMAR',
                                   'AUTONOMO','AUTONOMA',
                                   'NENHUMA','ESCRITORIOPROPRIO')
   AND A.NM_EMPRESA_LIMPO NOT LIKE '%NAO%'
   AND A.NM_EMPRESA_LIMPO IS NOT NULL
   AND A.NM_EMPRESA_LIMPO <> ''
UNION ALL
-- EMPRESA PF<->PF
SELECT DISTINCT B.CD_CLIENTE, B.CD_CPFCGC,
       A.CD_CLIENTE AS CD_CLIENTE_ENC, A.CD_CPFCGC AS CD_CPFCGC_ENC, 'EMPRESA' TIPO_VINCULO
  FROM #PF A
  JOIN #PF B
    ON A.NM_EMPRESA_LIMPO = B.NM_EMPRESA_LIMPO
   AND A.CD_CLIENTE <> B.CD_CLIENTE
 WHERE A.NM_EMPRESA_LIMPO NOT IN ('N','NA','NAO','NAOINFORMAR',
                                   'AUTONOMO','AUTONOMA',
                                   'NENHUMA','ESCRITORIOPROPRIO')
   AND A.NM_EMPRESA_LIMPO NOT LIKE '%NAO%'
   AND A.NM_EMPRESA_LIMPO IS NOT NULL
   AND A.NM_EMPRESA_LIMPO <> '';
 
DROP TABLE IF EXISTS #CLIENTES;
SELECT CD_CLIENTE_BUSC AS CD_CLIENTE INTO #CLIENTES FROM #VINCULO
UNION
SELECT CD_CLIENTE_ENC FROM #VINCULO;
 
-- ============== #NEGOCIO  (estrutural — sem colunas de quantidade) ==============
DROP TABLE IF EXISTS #NEGOCIO;
SELECT A.DT_NEGOCIO,
       A.NR_NEGOCIO,
       A.CD_NEGOCIO AS CD_PAPEL,
       A.CD_CLIENTE_COMPRA,
       A.CD_CLIENTE_VENDA
  INTO #NEGOCIO
  FROM ST_DIRETAS_BMF A
 WHERE DT_NEGOCIO >= @INICIO AND DT_NEGOCIO <= @FIM;
 
CREATE INDEX IDX_NEGOCIO_CLIENTES   ON #NEGOCIO (CD_CLIENTE_COMPRA, CD_CLIENTE_VENDA);
CREATE INDEX IDX_NEGOCIO_NR_NEGOCIO ON #NEGOCIO (NR_NEGOCIO);
CREATE NONCLUSTERED INDEX IX_NEGOCIO_COMPRA_VENDA ON #NEGOCIO (CD_CLIENTE_COMPRA, CD_CLIENTE_VENDA);
CREATE NONCLUSTERED INDEX IX_NEGOCIO_VENDA_COMPRA ON #NEGOCIO (CD_CLIENTE_VENDA, CD_CLIENTE_COMPRA);
CREATE INDEX IDX_VINCULO_CLIENTE_BUSC ON #VINCULO (CD_CLIENTE_BUSC, CD_CLIENTE_ENC, CD_CPFCGC_ENC);
CREATE INDEX IDX_VINCULO_CLIENTE_ENC  ON #VINCULO (CD_CLIENTE_ENC) INCLUDE (TIPO_VINCULO);
CREATE INDEX IDX_PF ON #PF (NM_EMPRESA_LIMPO);
CREATE INDEX IDX_PJ ON #PJ (NM_EMPRESA_LIMPO);
 
-- Cada negócio é atribuído ao CLIENTE COMPRADOR. A #VINCULO é simétrica, então
-- o lado vendedor é capturado pela entrada reversa do par. Igual ao relatório v4.
DROP TABLE IF EXISTS #RESULTADO;
SELECT CD_CLIENTE_BUSC AS CD_CLIENTE, CD_CPFCGC_BUSC AS CD_CPFCGC,
       CD_CLIENTE_ENC, CD_CPFCGC_ENC, TIPO_VINCULO
  INTO #RESULTADO
  FROM #VINCULO A
 WHERE EXISTS (SELECT 1 FROM #NEGOCIO B
                WHERE A.CD_CLIENTE_BUSC = B.CD_CLIENTE_COMPRA
                  AND A.CD_CLIENTE_ENC  = B.CD_CLIENTE_VENDA);
 
-- ============== #NEGOCIO_VINCULO  (estrutura dos negócios do grupo) ==============
DROP TABLE IF EXISTS #NEGOCIO_VINCULO;
SELECT CD_CLIENTE_BUSC AS CD_CLIENTE, CD_CPFCGC_BUSC AS CD_CPFCGC,
       CD_CLIENTE_ENC, CD_CPFCGC_ENC, TIPO_VINCULO,
       B.DT_NEGOCIO,
       B.NR_NEGOCIO,
       B.CD_PAPEL,
       B.CD_CLIENTE_COMPRA, B.CD_CLIENTE_VENDA
  INTO #NEGOCIO_VINCULO
  FROM #VINCULO A
  JOIN #NEGOCIO B
    ON A.CD_CLIENTE_BUSC = B.CD_CLIENTE_COMPRA
   AND A.CD_CLIENTE_ENC  = B.CD_CLIENTE_VENDA;
 
DROP TABLE IF EXISTS #NEGOCIO_VINCULO_DISTINCT;
SELECT DISTINCT CD_CLIENTE, DT_NEGOCIO, NR_NEGOCIO, CD_PAPEL
  INTO #NEGOCIO_VINCULO_DISTINCT
  FROM #NEGOCIO_VINCULO;
 
-- ============== QTD_CONTRATO via ST_BMF_NEGOCIOS_NC ==============
DROP TABLE IF EXISTS #QTD_CONTRATO_CLIENTE;
SELECT CD_CLIENTE,
       SUM(ISNULL(QT_QTDDET, 0)) AS QTD_CONTRATO_CLIENTE
  INTO #QTD_CONTRATO_CLIENTE
  FROM ST_BMF_NEGOCIOS_NC
 WHERE DT_NEGOCIO >= @INICIO AND DT_NEGOCIO <= @FIM
 GROUP BY CD_CLIENTE;
 
DROP TABLE IF EXISTS #QTD_CONTRATO_MES_GRUPO;
SELECT N.CD_CLIENTE,
       SUM(ISNULL(N.QT_QTDDET, 0)) AS QTD_CONTRATO_MES_GRUPO
  INTO #QTD_CONTRATO_MES_GRUPO
  FROM ST_BMF_NEGOCIOS_NC N
  JOIN #NEGOCIO_VINCULO_DISTINCT V
    ON N.CD_CLIENTE  = V.CD_CLIENTE
   AND N.DT_NEGOCIO  = V.DT_NEGOCIO
   AND N.NR_NEGOCIO  = V.NR_NEGOCIO
 WHERE N.DT_NEGOCIO >= @INICIO AND N.DT_NEGOCIO <= @FIM
 GROUP BY N.CD_CLIENTE;
 
DROP TABLE IF EXISTS #QTD_NEGOCIO_VINCULO;
SELECT CD_CLIENTE,
       COUNT(*) AS QTD_NEGOCIO_MES_GRUPO
  INTO #QTD_NEGOCIO_VINCULO
  FROM #NEGOCIO_VINCULO_DISTINCT
 GROUP BY CD_CLIENTE;
 
-- ============== #CONCENTRACAO ==============
DROP TABLE IF EXISTS #CONCENTRACAO;
SELECT A.CD_CLIENTE,
       A.QTD_CONTRATO_CLIENTE,
       B.QTD_CONTRATO_MES_GRUPO,
       C.QTD_NEGOCIO_MES_GRUPO,
       CAST(B.QTD_CONTRATO_MES_GRUPO AS FLOAT)
         / NULLIF(CAST(A.QTD_CONTRATO_CLIENTE AS FLOAT), 0) * 100 AS CONCENTRACAO
  INTO #CONCENTRACAO
  FROM #QTD_CONTRATO_CLIENTE  A
  JOIN #QTD_CONTRATO_MES_GRUPO B ON A.CD_CLIENTE = B.CD_CLIENTE
  JOIN #QTD_NEGOCIO_VINCULO    C ON A.CD_CLIENTE = C.CD_CLIENTE;
 
-- ============== #RESULTADO_FINAL  (aplica regra do alerta) ==============
DROP TABLE IF EXISTS #RESULTADO_FINAL;
SELECT A.CD_CLIENTE, A.CD_CPFCGC, A.CD_CLIENTE_ENC, A.CD_CPFCGC_ENC,
       A.TIPO_VINCULO,
       B.QTD_NEGOCIO_MES_GRUPO,
       B.QTD_CONTRATO_CLIENTE,
       B.QTD_CONTRATO_MES_GRUPO,
       CAST(B.CONCENTRACAO AS NUMERIC(7,2)) AS CONCENTRACAO
  INTO #RESULTADO_FINAL
  FROM #RESULTADO A
  JOIN #CONCENTRACAO B ON A.CD_CLIENTE = B.CD_CLIENTE
 WHERE B.CONCENTRACAO > 10;   -- regra do alerta
 
DROP TABLE IF EXISTS #VINCULO_RESULTADO;
SELECT DISTINCT CD_CLIENTE, TIPO_VINCULO
  INTO #VINCULO_RESULTADO FROM #RESULTADO_FINAL;
 
DROP TABLE IF EXISTS #CD_CLIENTE_RESULTADO;
SELECT DISTINCT CD_CLIENTE, CD_CLIENTE_ENC
  INTO #CD_CLIENTE_RESULTADO FROM #RESULTADO_FINAL;
 
-- Sem STRING_AGG -> STUFF + FOR XML PATH (compat com SQL Server < 2017)
DROP TABLE IF EXISTS #CD_CLI_RESULT;
SELECT X.CD_CLIENTE,
       STUFF((SELECT ';' + CAST(Y.CD_CLIENTE_ENC AS VARCHAR(50))
                FROM #CD_CLIENTE_RESULTADO Y
               WHERE Y.CD_CLIENTE = X.CD_CLIENTE
               FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 1, '') AS CD_CONTRAPARTE
  INTO #CD_CLI_RESULT
  FROM (SELECT DISTINCT CD_CLIENTE FROM #CD_CLIENTE_RESULTADO) X;
 
DROP TABLE IF EXISTS #VINC_RESULT;
SELECT X.CD_CLIENTE,
       STUFF((SELECT ';' + Y.TIPO_VINCULO
                FROM #VINCULO_RESULTADO Y
               WHERE Y.CD_CLIENTE = X.CD_CLIENTE
               FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 1, '') AS VINCULO
  INTO #VINC_RESULT
  FROM (SELECT DISTINCT CD_CLIENTE FROM #VINCULO_RESULTADO) X;
 
CREATE NONCLUSTERED INDEX IX_VINC_RESULT_CLIENTE   ON #VINC_RESULT (CD_CLIENTE);
CREATE NONCLUSTERED INDEX IX_CD_CLI_RESULT_CLIENTE ON #CD_CLI_RESULT (CD_CLIENTE);
 
-- ============== NR_NEGOCIO agregado: "CD_PAPEL:NR_NEGOCIO; ..." ==============
DROP TABLE IF EXISTS #NR_NEG_DISTINCT;
SELECT DISTINCT CD_CLIENTE, NR_NEGOCIO, CD_PAPEL
  INTO #NR_NEG_DISTINCT
  FROM #NEGOCIO_VINCULO;
 
DROP TABLE IF EXISTS #NR_NEG_RESULT;
SELECT X.CD_CLIENTE,
       STUFF((SELECT '; ' + RTRIM(LTRIM(ISNULL(Y.CD_PAPEL,''))) + ':' + CAST(Y.NR_NEGOCIO AS VARCHAR(50))
                FROM #NR_NEG_DISTINCT Y
               WHERE Y.CD_CLIENTE = X.CD_CLIENTE
               ORDER BY Y.CD_PAPEL, Y.NR_NEGOCIO
               FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 2, '') AS NR_NEGOCIO
  INTO #NR_NEG_RESULT
  FROM (SELECT DISTINCT CD_CLIENTE FROM #NR_NEG_DISTINCT) X;
 
-- ============== INSERT no alerta (colunas alinhadas com o relatório v4) ==============
INSERT INTO ST_ALERT_OMG_BMF
    (DATA, CD_CLIENTE, CD_CPFCGC, CD_CONTRAPARTE, VINCULOS, NR_NEGOCIO,
     QTD_CONTRATO_MES_GRUPO, QTD_CONTRATO_CLIENTE, CONCENTRACAO, QTD_NEGOCIO_MES_GRUPO)
SELECT DISTINCT
       DATEADD(DAY,-@AUX,@PREGAO)                  AS DATA,
       a.CD_CLIENTE                                AS CD_CLIENTE,
       a.CD_CPFCGC                                 AS CD_CPFCGC,
       MAX(c.CD_CONTRAPARTE)                       AS CD_CONTRAPARTE,
       MAX(b.VINCULO)                              AS VINCULOS,
       MAX(d.NR_NEGOCIO)                           AS NR_NEGOCIO,
       MAX(QTD_CONTRATO_MES_GRUPO)                 AS QTD_CONTRATO_MES_GRUPO,
       MAX(QTD_CONTRATO_CLIENTE)                   AS QTD_CONTRATO_CLIENTE,
       MAX(CONCENTRACAO)                           AS CONCENTRACAO,
       MAX(QTD_NEGOCIO_MES_GRUPO)                  AS QTD_NEGOCIO_MES_GRUPO
  FROM #RESULTADO_FINAL a
  JOIN #VINC_RESULT     b ON a.CD_CLIENTE = b.CD_CLIENTE
  JOIN #CD_CLI_RESULT   c ON a.CD_CLIENTE = c.CD_CLIENTE
  LEFT JOIN #NR_NEG_RESULT d ON a.CD_CLIENTE = d.CD_CLIENTE
 GROUP BY a.CD_CLIENTE, a.CD_CPFCGC;
 
/******* fim do processo de carga do alerta **********/
 
-- ================================================
-- Marca DT_FIRA para registros carregados (fallback)
-- ================================================
DECLARE @__dt_fira_now DATETIME = GETDATE();
IF COL_LENGTH(N'dbo.ST_ALERT_OMG_BMF', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE [dbo].ST_ALERT_OMG_BMF
       SET DT_FIRA = @__dt_fira_now
     WHERE DT_FIRA IS NULL;
END
 
DROP TABLE IF EXISTS ST_ALERT_OMG_BMF_PADRAO;