CREATE   PROCEDURE [dbo].[FIRA_PR_CARGA_ST_CONTROLE_VINCULADOS_BMF] @PREGAO DATETIME, @PREGAOFIM DATETIME
--WITH ENCRYPTION
AS


DROP TABLE IF EXISTS [dbo].[ST_CONTROLE_VINCULADOS_BMF_PADRAO]
    CREATE TABLE [dbo].[ST_CONTROLE_VINCULADOS_BMF_PADRAO] (
    [DT_NEGOCIO] datetime NOT NULL,
    [CD_CLIENTE_COMPRA] int NULL,
    [NM_CLIENTE_COMPRA] varchar(400) NULL,
    [VINC_COMPRA] char(1) NULL,
    [CD_CLIENTE_VENDA] int NULL,
    [NM_CLIENTE_VENDA] varchar(400) NULL,
    [VINC_VENDA] char(1) NULL,
    [NR_NEGOCIO] numeric(12,0) NULL,
    [QT_NEGOCIO_COMPRA] float NOT NULL,
    [CD_COMMOD] varchar(10) NULL,
    [CD_SERIE] varchar(10) NULL,
    [HH_COMPRA] varchar(8) NULL,
    [VL_TOTNEG_COMPRA] float NOT NULL,
    [VL_NEGOCIO_COMPRA] float NOT NULL,
    [CD_ASSESSOR_COMPRA] int NULL,
    [DS_ASSESSOR_COMPRA] varchar(60) NULL,
    [CD_ASSESSOR_VENDA] int NULL,
    [DS_ASSESSOR_VENDA] varchar(60) NULL,
    [SISTEMA_COMPRA] varchar(10) NULL,
    [USUARIO_COMPRA] varchar(100) NULL,
    [SISTEMA_VENDA] varchar(10) NULL,
    [USUARIO_VENDA] varchar(100) NULL,
    [IN_DAYTRADE_COMPRA] char(1) NULL,
    [IN_DAYTRADE_VENDA] char(1) NULL,
    [CD_NATOPE] char(1) NULL,
	[DT_FIRA] DATETIME NULL
);

/***************************************************
inicio da comparação entre a tabela
da base padrao fira origem x tabela cliente destino
*****************************************************/
EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo',, @src_table='ST_CONTROLE_VINCULADOS_BMF_PADRAO',
  @schema_name='dbo', @base_table='ST_CONTROLE_VINCULADOS_BMF',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1;


--DECLARE  @PREGAO DATETIME , @PREGAOFIM DATETIME
--SET @PREGAO ='20250611'
--SET @PREGAOFIM ='20260101'


/****************************	
	CARGA ST_CONTROLE_VINCULADOS		
****************************/     

drop table if exists #v_cliente_todos
select cd_cliente,NM_CLIENTE,IN_PESS_VINC,CD_ASSESSOR, NM_ASSESSOR 
into #v_cliente_todos
from ST_DADOS_BASICOS_PF
group by cd_cliente,NM_CLIENTE,IN_PESS_VINC,CD_ASSESSOR, NM_ASSESSOR

insert into #v_cliente_todos
select cd_cliente,NM_CLIENTE,IN_PESS_VINC,CD_ASSESSOR, NM_ASSESSOR 
from ST_DADOS_BASICOS_PF
group by cd_cliente,NM_CLIENTE,IN_PESS_VINC,CD_ASSESSOR, NM_ASSESSOR


/*******************************	
	CARGA ST_CONTROLE_VINCULADOS_BMF		
********************************/  
   
WHILE @PREGAO < @PREGAOFIM 	
BEGIN	

	----
	--DELETA		
	DELETE ST_CONTROLE_VINCULADOS_BMF WHERE DT_NEGOCIO = @PREGAO	
 	
	
	----
	--INSERT FINAL
	----------
	--COMPRA--
	---------
	
		INSERT INTO ST_CONTROLE_VINCULADOS_BMF	
		(
		 DT_NEGOCIO,CD_CLIENTE_COMPRA,NM_CLIENTE_COMPRA,VINC_COMPRA,CD_CLIENTE_VENDA,NM_CLIENTE_VENDA,VINC_VENDA
		,NR_NEGOCIO,QT_NEGOCIO_COMPRA,CD_COMMOD,CD_SERIE,HH_COMPRA,VL_TOTNEG_COMPRA,VL_NEGOCIO_COMPRA
		,CD_ASSESSOR_COMPRA,DS_ASSESSOR_COMPRA,CD_ASSESSOR_VENDA,DS_ASSESSOR_VENDA,SISTEMA_COMPRA
		,USUARIO_COMPRA,SISTEMA_VENDA,USUARIO_VENDA,IN_DAYTRADE_COMPRA,IN_DAYTRADE_VENDA,CD_NATOPE
		)
		SELECT 
			DT_NEGOCIO,
			CD_CLIENTE_COMPRA, 
			NM_CLIENTE_COMPRA, 
			VINC_COMPRA, 
			CD_CLIENTE_VENDA, 
			NM_CLIENTE_VENDA, 
			VINC_VENDA, 	
			NR_NEGOCIO, 
			QT_NEGOCIO_COMPRA, 
			CD_COMMOD, 
			CD_SERIE, 
			HH_COMPRA,
			VL_TOTNEG_COMPRA,
			VL_NEGOCIO_COMPRA, 
			CD_ASSESSOR_COMPRA,	
			DS_ASSESSOR_COMPRA,
			CD_ASSESSOR_VENDA, 
			DS_ASSESSOR_VENDA, 
			SISTEMA_COMPRA, 
			USUARIO_COMPRA, 
			SISTEMA_VENDA, 
			USUARIO_VENDA,	
			NULL AS IN_DAYTRADE_COMPRA, 
			NULL AS IN_DAYTRADE_VENDA, 
			'C'	
		FROM [ST_DIRETAS_BMF](NOLOCK)	
		WHERE 
			VINC_COMPRA = 'S' 	
		AND DT_NEGOCIO = @PREGAO
	

	---------	
	--VENDA--
	---------

		INSERT INTO ST_CONTROLE_VINCULADOS_BMF
				(
		 DT_NEGOCIO,CD_CLIENTE_COMPRA,NM_CLIENTE_COMPRA,VINC_COMPRA,CD_CLIENTE_VENDA,NM_CLIENTE_VENDA,VINC_VENDA
		,NR_NEGOCIO,QT_NEGOCIO_COMPRA,CD_COMMOD,CD_SERIE,HH_COMPRA,VL_TOTNEG_COMPRA,VL_NEGOCIO_COMPRA
		,CD_ASSESSOR_COMPRA,DS_ASSESSOR_COMPRA,CD_ASSESSOR_VENDA,DS_ASSESSOR_VENDA,SISTEMA_COMPRA
		,USUARIO_COMPRA,SISTEMA_VENDA,USUARIO_VENDA,IN_DAYTRADE_COMPRA,IN_DAYTRADE_VENDA,CD_NATOPE
		)
		SELECT 
			DT_NEGOCIO,
			CD_CLIENTE_VENDA, 
			NM_CLIENTE_VENDA, 
			VINC_VENDA, 
			CD_CLIENTE_COMPRA, 
			NM_CLIENTE_COMPRA, 
			VINC_COMPRA, 	
			NR_NEGOCIO, 
			QT_NEGOCIO_VENDA, 
			CD_COMMOD, 
			CD_SERIE, 
			HH_COMPRA,
			VL_TOTNEG_VENDA,
			VL_NEGOCIO_VENDA, 
			CD_ASSESSOR_VENDA,	
			DS_ASSESSOR_VENDA,
			CD_ASSESSOR_COMPRA, 
			DS_ASSESSOR_COMPRA, 
			SISTEMA_VENDA, 
			USUARIO_VENDA, 
			SISTEMA_COMPRA, 
			USUARIO_COMPRA,	
			NULL AS IN_DAYTRADE_COMPRA, 
			NULL AS IN_DAYTRADE_VENDA, 
			'V'	
		FROM [ST_DIRETAS_BMF](NOLOCK)	
		WHERE 
			VINC_VENDA= 'S'	
		AND DT_NEGOCIO = @PREGAO	
	


	------------------------
	---	NATOPE -> COMPRA ---
	------------------------


		INSERT INTO ST_CONTROLE_VINCULADOS_BMF
				(
		 DT_NEGOCIO,CD_CLIENTE_COMPRA,NM_CLIENTE_COMPRA,VINC_COMPRA,CD_CLIENTE_VENDA,NM_CLIENTE_VENDA,VINC_VENDA
		,NR_NEGOCIO,QT_NEGOCIO_COMPRA,CD_COMMOD,CD_SERIE,HH_COMPRA,VL_TOTNEG_COMPRA,VL_NEGOCIO_COMPRA
		,CD_ASSESSOR_COMPRA,DS_ASSESSOR_COMPRA,CD_ASSESSOR_VENDA,DS_ASSESSOR_VENDA,SISTEMA_COMPRA
		,USUARIO_COMPRA,SISTEMA_VENDA,USUARIO_VENDA,IN_DAYTRADE_COMPRA,IN_DAYTRADE_VENDA,CD_NATOPE
		)
		SELECT 
			A.DT_NEGOCIO, 
			A.CD_CLIENTE, 
			B.NM_CLIENTE,
			'S',
			NULL,
			NULL,
			'N', 
			A.NR_NEGOCIO, 
			A.QT_QTDDET, 
			A.CD_COMMOD, 
			A.CD_SERIE,	
			
			(SELECT MAX(X.HR_NEGOCIO) 
			 FROM ST_BMF_NEGOCIOS X	(NOLOCK)
			 WHERE X.DT_NEGOCIO = @PREGAO AND X.CD_CLIENTE = A.CD_CLIENTE AND X.CD_COMMOD = A.CD_COMMOD AND X.CD_SERIE = A.CD_SERIE	
			 AND X.NR_NEGOCIO = A.NR_NEGOCIO AND X.DT_NEGOCIO = A.DT_NEGOCIO AND X.CD_NATOPE = A.CD_NATOPE) AS HR_NEGOCIO,		 	
			
			A.VL_VALOPE, 
			A.PR_NEGOCIO,
			B.CD_ASSESSOR, 
			B.NM_ASSESSOR, 
			NULL,
			NULL,	
			
			(SELECT MAX(X.CD_OPERADOR) 
			 FROM ST_BMF_NEGOCIOS X	(NOLOCK)
			 WHERE X.DT_NEGOCIO = @PREGAO AND X.CD_CLIENTE = A.CD_CLIENTE AND X.CD_COMMOD = A.CD_COMMOD AND X.CD_SERIE = A.CD_SERIE	
			 AND X.NR_NEGOCIO = A.NR_NEGOCIO AND X.DT_NEGOCIO = A.DT_NEGOCIO AND X.CD_NATOPE = A.CD_NATOPE) AS CD_OPERADOR,	
			
			(SELECT MAX(X.NM_USUARIO) 
			 FROM ST_BMF_NEGOCIOS X	(NOLOCK)
			 WHERE X.DT_NEGOCIO = @PREGAO AND X.CD_CLIENTE = A.CD_CLIENTE AND X.CD_COMMOD = A.CD_COMMOD AND X.CD_SERIE = A.CD_SERIE	
			 AND X.NR_NEGOCIO = A.NR_NEGOCIO AND X.DT_NEGOCIO = A.DT_NEGOCIO AND X.CD_NATOPE = A.CD_NATOPE) AS NM_USUARIO,
		 
			NULL,
			NULL,		
			NULL AS IN_DAYTRADE_COMPRA, 
			NULL AS IN_DAYTRADE_VENDA, 
			'C'
	
		FROM ST_BMF_NEGOCIOS_NC (NOLOCK)A, 
			 #V_CLIENTE_TODOS (NOLOCK)B	
		WHERE 
			A.CD_CLIENTE = B.CD_CLIENTE	
		AND B.IN_PESS_VINC = 'S' 
		AND A.CD_NATOPE = 'C'	
		AND NOT EXISTS(SELECT 
							B.NR_NEGOCIO, 
							B.DT_NEGOCIO 
					   FROM ST_DIRETAS_BMF B	(NOLOCK)
					   WHERE 	
						   A.NR_NEGOCIO = B.NR_NEGOCIO 	
					   AND A.CD_SERIE 	= B.CD_SERIE 	
					   AND A.CD_COMMOD 	= B.CD_COMMOD  	
					   AND A.CD_CLIENTE = B.CD_CLIENTE_COMPRA 	
					   AND A.DT_NEGOCIO = B.DT_NEGOCIO 
					   AND B.DT_NEGOCIO = @PREGAO
					   )	
		AND A.DT_NEGOCIO = @PREGAO	


		
	-----------------------
	--- NATOPE -> VENDA ---
	-----------------------

		INSERT INTO ST_CONTROLE_VINCULADOS_BMF
				(
		 DT_NEGOCIO,CD_CLIENTE_COMPRA,NM_CLIENTE_COMPRA,VINC_COMPRA,CD_CLIENTE_VENDA,NM_CLIENTE_VENDA,VINC_VENDA
		,NR_NEGOCIO,QT_NEGOCIO_COMPRA,CD_COMMOD,CD_SERIE,HH_COMPRA,VL_TOTNEG_COMPRA,VL_NEGOCIO_COMPRA
		,CD_ASSESSOR_COMPRA,DS_ASSESSOR_COMPRA,CD_ASSESSOR_VENDA,DS_ASSESSOR_VENDA,SISTEMA_COMPRA
		,USUARIO_COMPRA,SISTEMA_VENDA,USUARIO_VENDA,IN_DAYTRADE_COMPRA,IN_DAYTRADE_VENDA,CD_NATOPE
		)
		SELECT 
			A.DT_NEGOCIO, 
			A.CD_CLIENTE, 
			B.NM_CLIENTE,
			'S',
			NULL,
			NULL,
			'N', 
			A.NR_NEGOCIO, 
			A.QT_QTDDET, 
			A.CD_COMMOD, 
			A.CD_SERIE,	
			
			(SELECT MAX(X.HR_NEGOCIO) 
			 FROM ST_BMF_NEGOCIOS X	(NOLOCK)
			 WHERE X.DT_NEGOCIO = @PREGAO AND X.CD_CLIENTE = A.CD_CLIENTE AND X.CD_COMMOD = A.CD_COMMOD AND X.CD_SERIE = A.CD_SERIE	
			 AND X.NR_NEGOCIO = A.NR_NEGOCIO AND X.DT_NEGOCIO = A.DT_NEGOCIO AND X.CD_NATOPE = A.CD_NATOPE) AS HR_NEGOCIO,	
			
			A.VL_VALOPE, 
			A.PR_NEGOCIO, 
			B.CD_ASSESSOR,
			B.NM_ASSESSOR,
			NULL, 
			NULL, 	
			
			(SELECT MAX(X.CD_OPERADOR) 
			 FROM ST_BMF_NEGOCIOS X	(NOLOCK)
			 WHERE X.DT_NEGOCIO = @PREGAO AND X.CD_CLIENTE = A.CD_CLIENTE AND X.CD_COMMOD = A.CD_COMMOD AND X.CD_SERIE = A.CD_SERIE	
			 AND X.NR_NEGOCIO = A.NR_NEGOCIO AND X.DT_NEGOCIO = A.DT_NEGOCIO AND X.CD_NATOPE = A.CD_NATOPE) AS CD_OPERADOR,	
			
			(SELECT MAX(X.NM_USUARIO) 
			 FROM ST_BMF_NEGOCIOS X	(NOLOCK)
			 WHERE X.DT_NEGOCIO = @PREGAO AND X.CD_CLIENTE = A.CD_CLIENTE AND X.CD_COMMOD = A.CD_COMMOD AND X.CD_SERIE = A.CD_SERIE	
			 AND X.NR_NEGOCIO = A.NR_NEGOCIO AND X.DT_NEGOCIO = A.DT_NEGOCIO AND X.CD_NATOPE = A.CD_NATOPE) AS NM_USUARIO, 
		
			NULL,
			NULL,		
			NULL AS IN_DAYTRADE_COMPRA, 
			NULL AS IN_DAYTRADE_VENDA, 
			'V'
		
		FROM ST_BMF_NEGOCIOS_NC (NOLOCK) A, 
			 #V_CLIENTE_TODOS (NOLOCK) B	
		WHERE 
			A.CD_CLIENTE = B.CD_CLIENTE	
		AND B.IN_PESS_VINC = 'S'
		AND A.CD_NATOPE = 'V'	
		AND NOT EXISTS(SELECT 
							B.NR_NEGOCIO, 
							B.DT_NEGOCIO 
					   FROM ST_DIRETAS_BMF B (NOLOCK)	
					   WHERE 	
						   A.NR_NEGOCIO = B.NR_NEGOCIO 	
					   AND A.CD_SERIE 	= B.CD_SERIE 	
					   AND A.CD_COMMOD 	= B.CD_COMMOD  	
					   AND A.CD_CLIENTE = B.CD_CLIENTE_VENDA 	
					   AND A.DT_NEGOCIO = B.DT_NEGOCIO 
					   AND B.DT_NEGOCIO = @PREGAO
					   )	
		AND A.DT_NEGOCIO = @PREGAO	

	----
	--UPDATE

		UPDATE ST_CONTROLE_VINCULADOS_BMF 
		SET IN_DAYTRADE_COMPRA = 'S'	
		WHERE EXISTS (SELECT CD_CLIENTE
					  FROM ST_DAYTRADE_DETALHE_BMF (NOLOCK) B	
					  WHERE 
						  ST_CONTROLE_VINCULADOS_BMF.DT_NEGOCIO = B.DT_DATMOV	
					  AND ST_CONTROLE_VINCULADOS_BMF.CD_CLIENTE_COMPRA = B.CD_CLIENTE	
					  AND ST_CONTROLE_VINCULADOS_BMF.CD_COMMOD = B.CD_COMMOD	
					  AND ST_CONTROLE_VINCULADOS_BMF.CD_SERIE = B.CD_SERIE	
					  AND ST_CONTROLE_VINCULADOS_BMF.NR_NEGOCIO = B.NR_NEGOCIO	
					  AND B.CD_NATOPE = 'C'
					  AND B.DT_DATMOV = @PREGAO
					  )	
		AND DT_NEGOCIO = @PREGAO	
		

		UPDATE ST_CONTROLE_VINCULADOS_BMF 
		SET IN_DAYTRADE_VENDA = 'S'	
		WHERE EXISTS (SELECT CD_CLIENTE 
					  FROM ST_DAYTRADE_DETALHE_BMF (NOLOCK) B	
					  WHERE ST_CONTROLE_VINCULADOS_BMF.DT_NEGOCIO = B.DT_DATMOV	
					  AND ST_CONTROLE_VINCULADOS_BMF.CD_CLIENTE_VENDA = B.CD_CLIENTE	
					  AND ST_CONTROLE_VINCULADOS_BMF.CD_COMMOD = B.CD_COMMOD	
					  AND ST_CONTROLE_VINCULADOS_BMF.CD_SERIE = B.CD_SERIE	
					  AND ST_CONTROLE_VINCULADOS_BMF.NR_NEGOCIO = B.NR_NEGOCIO	
					  AND B.CD_NATOPE = 'V'
					  AND B.DT_DATMOV = @PREGAO
					  )	
		AND DT_NEGOCIO = @PREGAO
		

	
		


SET @PREGAO = @PREGAO + 1	

END	

-- ================================================
-- Marca DT_FIRA para registros carregados (fallback)
-- ================================================
DECLARE @__dt_fira_now DATETIME = GETDATE();
IF COL_LENGTH(N'dbo.ST_CONTROLE_VINCULADOS_BMF', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE [dbo].[ST_CONTROLE_VINCULADOS_BMF]
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL;
END
/******* fim do processo de carga **********/

--passo 3
/***** limpa a tabela do banco para nao ficar sujeira ******/
DROP TABLE IF EXISTS ST_CONTROLE_VINCULADOS_BMF_PADRAO