CREATE PROCEDURE [dbo].[PR_ALERTADETALHADOTRANSFERENCIAFINANCEIRA02]
(
   @CD_ANO INT, @DS_MES VARCHAR(50), @CD_CLIENTE INT
)

--11/02/2025 - COLUNA PATRIMONIO ADICIONADA - FLÁVIO


AS
BEGIN

IF @DS_MES = '01' BEGIN SET @DS_MES = 'JANEIRO' END
ELSE IF @DS_MES = '02' BEGIN SET @DS_MES = 'FEVEREIRO' END
ELSE IF @DS_MES = '03' BEGIN SET @DS_MES = 'MARÇO' END
ELSE IF @DS_MES = '04' BEGIN SET @DS_MES = 'ABRIL' END
ELSE IF @DS_MES = '05' BEGIN SET @DS_MES = 'MAIO' END
ELSE IF @DS_MES = '06' BEGIN SET @DS_MES = 'JUNHO' END
ELSE IF @DS_MES = '07' BEGIN SET @DS_MES = 'JULHO' END
ELSE IF @DS_MES = '08' BEGIN SET @DS_MES = 'AGOSTO' END
ELSE IF @DS_MES = '09' BEGIN SET @DS_MES = 'SETEMBRO' END
ELSE IF @DS_MES = '10' BEGIN SET @DS_MES = 'OUTUBRO' END
ELSE IF @DS_MES = '11' BEGIN SET @DS_MES = 'NOVEMBRO' END
ELSE IF @DS_MES = '12' BEGIN SET @DS_MES = 'DEZEMBRO' END

SET @CD_ANO = CAST(@CD_ANO AS INT)
SET @CD_CLIENTE = CAST(@CD_CLIENTE AS INT)

SELECT DISTINCT 
FORMAT(DATA,'d','pt-br')DATA
,CD_CLIENTE AS [CÓD. CLIENTE]
,TP_CLIENTE AS [TIPO CLIENTE]
,NM_CLIENTE AS [NOME DO CLIETE]
,CD_CPFCGC AS [CPF/CNPJ]
,FORMAT(DT_CRIACAO,'d','pt-br')AS [DATA DE CRIAÇÃO]
,FORMAT(DT_DEPOSITO,'d','pt-br')AS [DATA DO DEPOSITO]
,FORMAT(DT_RETIRADA,'d','pt-br') AS [DATA DE RETIRADA]
,FORMAT(TOTAL,'f','pt-br')AS [VALOR DE RETIRADA]
,FORMAT(PATRIMONIO,'f','pt-br')AS [PATRIMONIO]

FROM ST_ALERT_TRANSFERENCIA_FINANCEIRA_02 A
INNER JOIN ST_PERIODO C  ON DATA = DT_PERIODO  
--LEFT OUTER JOIN V_CLIENTE_TODOS D ON A.CD_CLIENTE = D.CD_CLIENTE  
WHERE CD_ANO = @CD_ANO AND DS_MES = @DS_MES  AND A.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN A.CD_CLIENTE ELSE @CD_CLIENTE END

END