CREATE PROCEDURE [dbo].[FIRA_PR_CARGA_ST_DAYTRADE_RESUMO_BMF]  @PREGAO DATETIME , @PREGAOFIM DATETIME
--WITH ENCRYPTION
AS


DROP TABLE IF EXISTS [dbo].[ST_DAYTRADE_RESUMO_BMF_PADRAO]
    CREATE TABLE [dbo].[ST_DAYTRADE_RESUMO_BMF_PADRAO] (
    [CD_CLIENTE_COMPROU] int NULL,
    [VL_COMPRA] float NULL,
    [VL_VENDA] float NULL,
    [VL_FINANC] float NULL,
    [DT_PREGAO_COMPROU] datetime NOT NULL,
    [QT_CONTRAPARTES] int NULL,
    [DT_PRIMEIRA_OPER] smalldatetime NULL,
	[DT_FIRA] DATETIME NULL
);

/***************************************************
inicio da comparação entre a tabela
da base padrao fira origem x tabela cliente destino
*****************************************************/
EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo',, @src_table='ST_DAYTRADE_RESUMO_BMF_PADRAO',
  @schema_name='dbo', @base_table='ST_DAYTRADE_RESUMO_BMF',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1;



--DECLARE  @PREGAO DATETIME	,@PREGAOFIM DATETIME 
--SET @PREGAO ='20260201'
--SET @PREGAOFIM ='20260213'

/*********************	
	CARGA ST_DAYTRADE_RESUMO_BMF		
**********************/     

WHILE @PREGAO < @PREGAOFIM 	
BEGIN	
	
	----
	--DELETA		
	DELETE ST_DAYTRADE_RESUMO_BMF WHERE DT_PREGAO_COMPROU = @PREGAO 
	
	----
	--INSERT FINAL	
	INSERT INTO ST_DAYTRADE_RESUMO_BMF
	(
	CD_CLIENTE_COMPROU,VL_COMPRA,VL_VENDA,VL_FINANC,DT_PREGAO_COMPROU
	,QT_CONTRAPARTES,DT_PRIMEIRA_OPER
	)
	    	
			SELECT  
			 CD_CLIENTE_COMPROU
			,CAST(SUM(VL_COMPRA) AS decimal(15,2))  VL_COMPRA
			,CAST(SUM(VL_VENDA) AS decimal(15,2)) VL_VENDA
			,CAST(SUM(VL_FINANC) AS decimal(15,2)) VL_FINANC
			,DT_PREGAO_COMPROU
			,QT_CONTRAPARTES
			,DT_PRIMEIRA_OPER
			FROM (
			SELECT 
			 CD_CLIENTE AS CD_CLIENTE_COMPROU
			,CASE WHEN CD_NATOPE = 'C' THEN SUM(VL_VALOPE) ELSE 0 END VL_COMPRA
			,CASE WHEN CD_NATOPE = 'V' THEN SUM(VL_VALOPE) ELSE 0 END VL_VENDA
			,SUM(VL_VALOPE)VL_FINANC
			,DT_DATMOV AS DT_PREGAO_COMPROU
			,NULL AS QT_CONTRAPARTES
			,NULL AS DT_PRIMEIRA_OPER
			FROM 
				ST_BMF_NEGOCIOS_NC (NOLOCK) A		
			WHERE 	
			    A.TP_NEGOCIO IN ('DAY TRADE','DAYTRADE')
				AND A.DT_DATMOV = @PREGAO
			GROUP BY 
				CD_CLIENTE,CD_NATOPE,DT_DATMOV
			HAVING 
				SUM(VL_VALOPE) <> 0
		 )XX
		 GROUP BY 
		  CD_CLIENTE_COMPROU,DT_PREGAO_COMPROU,QT_CONTRAPARTES,DT_PRIMEIRA_OPER
	

	--UPDATE
UPDATE ST_DAYTRADE_RESUMO_BMF 
		SET QT_CONTRAPARTES = ( SELECT COUNT(DISTINCT A.CD_CLIENTE_COMPROU_DE) 
								FROM ST_DAYTRADE_DETALHE_BMF (NOLOCK) A		
								WHERE 
									A.CD_CLIENTE = ST_DAYTRADE_RESUMO_BMF.CD_CLIENTE_COMPROU 		
								AND A.DT_DATMOV = ST_DAYTRADE_RESUMO_BMF.DT_PREGAO_COMPROU
								AND A.DT_DATMOV = @PREGAO
								)		
		WHERE DT_PREGAO_COMPROU = @PREGAO	
		
		UPDATE ST_DAYTRADE_RESUMO_BMF 
		SET DT_PRIMEIRA_OPER =( SELECT MIN(A.DT_PREGAO_COMPROU) 
								FROM ST_DAYTRADE_RESUMO_BMF (NOLOCK) A		
								WHERE A.CD_CLIENTE_COMPROU = ST_DAYTRADE_RESUMO_BMF.CD_CLIENTE_COMPROU)		
		WHERE DT_PREGAO_COMPROU = @PREGAO

	
SET @PREGAO = @PREGAO +1

END	

-- ================================================
-- Marca DT_FIRA para registros carregados (fallback)
-- ================================================
DECLARE @__dt_fira_now DATETIME = GETDATE();
IF COL_LENGTH(N'dbo.ST_DAYTRADE_RESUMO_ATIVO_BMF', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE [dbo].[ST_DAYTRADE_RESUMO_ATIVO_BMF]
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL;
END

/******* fim do processo de carga **********/

--passo 3
/***** limpa a tabela do banco para nao ficar sujeira ******/
DROP TABLE IF EXISTS ST_DAYTRADE_RESUMO_BMF_PADRAO