CREATE PROCEDURE [dbo].[OBTERSCORELISTAATENCAO]
(
	@USUARIO INT
)
--WITH ENCRYPTION
AS
BEGIN

	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO)
	BEGIN
		SELECT 5 AS PESOANM1, 5 AS PESOB31, 5 AS PESOBCB1, 5 AS PESOBCB2, 5 AS PESOBIS1, 5 AS PESOCGU1, 5 AS PESOCGU2, 5 AS PESOCGU3, 5 AS PESOCGU4, 5 AS PESOCGU5, 5 AS PESOCGU6, 5 AS PESOCGU7, 5 AS PESOCGU8,
							5 AS PESOCGU9, 5 AS PESODFAT1, 5 AS PESODFIFSA1, 5 AS PESOEBC1, 5 AS PESOEBC2, 5 AS PESOEEAS1, 5 AS PESOFINCEN1, 5 AS PESOGAFI1, 5 AS PESOIBAMA1, 5 AS PESOICIJ1, 5 AS PESOINTERPOL1,
							5 AS PESOIPEA1, 5 AS PESOITA1, 5 AS PESOMYSOCIETY1, 5 AS PESOOFAC1, 5 AS PESOOFSIHMT1, 5 AS PESOOSFI1, 5 AS PESOOSFI2, 5 AS PESOPACE1, 5 AS PESOPGFN1,
							5 AS PESORF1, 5 AS PESOSECO1, 5 AS PESOSISCOAF1, 5 AS PESOTCU1, 5 AS PESOTCU2, 5 AS PESOTCU3, 5 AS PESOTI1, 5 AS PESOTSE1, 5 AS PESOTSE2, 5 AS PESOTSE3, 5 AS PESOUNSC1
	END
	ELSE
	BEGIN
		SELECT 
			CASE WHEN ANM1 IS NULL THEN 5 ELSE ANM1 END AS PESOANM1,
			CASE WHEN B31 IS NULL THEN 5 ELSE B31 END AS PESOB31,
			CASE WHEN BCB1 IS NULL THEN 5 ELSE BCB1 END AS PESOBCB1,
			CASE WHEN BCB2 IS NULL THEN 5 ELSE BCB2 END AS PESOBCB2,
			CASE WHEN BIS1 IS NULL THEN 5 ELSE BIS1 END AS PESOBIS1,
			CASE WHEN CGU1 IS NULL THEN 5 ELSE CGU1 END AS PESOCGU1,
			CASE WHEN CGU2 IS NULL THEN 5 ELSE CGU2 END AS PESOCGU2,
			CASE WHEN CGU3 IS NULL THEN 5 ELSE CGU3 END AS PESOCGU3,
			CASE WHEN CGU4 IS NULL THEN 5 ELSE CGU4 END AS PESOCGU4,
			CASE WHEN CGU5 IS NULL THEN 5 ELSE CGU5 END AS PESOCGU5,
			CASE WHEN CGU6 IS NULL THEN 5 ELSE CGU6 END AS PESOCGU6,
			CASE WHEN CGU7 IS NULL THEN 5 ELSE CGU7 END AS PESOCGU7,
			CASE WHEN CGU8 IS NULL THEN 5 ELSE CGU8 END AS PESOCGU8,
			CASE WHEN CGU9 IS NULL THEN 5 ELSE CGU9 END AS PESOCGU9,
			CASE WHEN DFAT1 IS NULL THEN 5 ELSE DFAT1 END AS PESODFAT1,
			CASE WHEN DFIFSA1 IS NULL THEN 5 ELSE DFIFSA1 END AS PESODFIFSA1,
			CASE WHEN EBC1 IS NULL THEN 5 ELSE EBC1 END AS PESOEBC1,
			CASE WHEN EBC2 IS NULL THEN 5 ELSE EBC2 END AS PESOEBC2,
			CASE WHEN EEAS1 IS NULL THEN 5 ELSE EEAS1 END AS PESOEEAS1,
			CASE WHEN FINCEN1 IS NULL THEN 5 ELSE FINCEN1 END AS PESOFINCEN1,
			CASE WHEN GAFI1 IS NULL THEN 5 ELSE GAFI1 END AS PESOGAFI1,
			CASE WHEN IBAMA1 IS NULL THEN 5 ELSE IBAMA1 END AS PESOIBAMA1,
			CASE WHEN ICIJ1 IS NULL THEN 5 ELSE ICIJ1 END AS PESOICIJ1,
			CASE WHEN INTERPOL1 IS NULL THEN 5 ELSE INTERPOL1 END AS PESOINTERPOL1,
			CASE WHEN IPEA1 IS NULL THEN 5 ELSE IPEA1 END AS PESOIPEA1,
			CASE WHEN ITA1 IS NULL THEN 5 ELSE ITA1 END AS PESOITA1,
			CASE WHEN MYSOCIETY1 IS NULL THEN 5 ELSE MYSOCIETY1 END AS PESOMYSOCIETY1,
			CASE WHEN OFAC1 IS NULL THEN 5 ELSE OFAC1 END AS PESOOFAC1,
			CASE WHEN OFSIHMT1 IS NULL THEN 5 ELSE OFSIHMT1 END AS PESOOFSIHMT1,
			CASE WHEN OSFI1 IS NULL THEN 5 ELSE OSFI1 END AS PESOOSFI1,
			CASE WHEN OSFI2 IS NULL THEN 5 ELSE OSFI2 END AS PESOOSFI2,
			CASE WHEN PACE1 IS NULL THEN 5 ELSE PACE1 END AS PESOPACE1,
			CASE WHEN PGFN1 IS NULL THEN 5 ELSE PGFN1 END AS PESOPGFN1,
			CASE WHEN RF1 IS NULL THEN 5 ELSE RF1 END AS PESORF1,
			CASE WHEN SECO1 IS NULL THEN 5 ELSE SECO1 END AS PESOSECO1,
			CASE WHEN SISCOAF1 IS NULL THEN 5 ELSE SISCOAF1 END AS PESOSISCOAF1,
			CASE WHEN TCU1 IS NULL THEN 5 ELSE TCU1 END AS PESOTCU1,
			CASE WHEN TCU2 IS NULL THEN 5 ELSE TCU2 END AS PESOTCU2,
			CASE WHEN TCU3 IS NULL THEN 5 ELSE TCU3 END AS PESOTCU3,
			CASE WHEN TI1 IS NULL THEN 5 ELSE TI1 END AS PESOTI1,
			CASE WHEN TSE1 IS NULL THEN 5 ELSE TSE1 END AS PESOTSE1,
			CASE WHEN TSE2 IS NULL THEN 5 ELSE TSE2 END AS PESOTSE2,
			CASE WHEN TSE3 IS NULL THEN 5 ELSE TSE3 END AS PESOTSE3,
			CASE WHEN UNSC1 IS NULL THEN 5 ELSE UNSC1 END AS PESOUNSC1
		FROM
		(
			SELECT PESO, ITEM
			FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO
		) D
		PIVOT
		(
			MAX(PESO)
			FOR ITEM IN ( ANM1, B31, BCB1, BCB2, BIS1, CGU1, CGU2, CGU3, CGU4, CGU5, CGU6, CGU7, CGU8,
							CGU9, DFAT1, DFIFSA1, EBC1, EBC2, EEAS1, FINCEN1, GAFI1, IBAMA1, ICIJ1, INTERPOL1,
							IPEA1, ITA1, MYSOCIETY1, OFAC1, OFSIHMT1, OSFI1, OSFI2, PACE1, PGFN1,
							RF1, SECO1, SISCOAF1, TCU1, TCU2, TCU3, TI1, TSE1, TSE2, TSE3, UNSC1)
		) PIV;
	END

END