CREATE PROCEDURE [dbo].[OBTERSCORETRANSACIONAL]
(
	@USUARIO INT
)
--WITH ENCRYPTION
AS

DECLARE @DEFAULT INT = 5
--DECLARE @USUARIO INT = 1
BEGIN
 
	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO)
		BEGIN
        SELECT @DEFAULT AS PATRIMONIO_CUSTODIA,@DEFAULT AS PATRIMONIO_MOVCC,@DEFAULT AS PATRIMONIO_NETTING,@DEFAULT AS PATRIMONIO_TRANSF_CUST, @DEFAULT AS SWING_BOVESPA,
							@DEFAULT AS SWING_BMF, @DEFAULT AS DAYTRADE_BOVESPA_01, @DEFAULT AS DAYTRADE_BMF_01, @DEFAULT AS MUDANCA_REPENTINA,@DEFAULT AS ATUALIZACAO_CADASTRAL,
							@DEFAULT AS MEDIA_BOVESPA_01, @DEFAULT AS MEDIA_BMF_01, @DEFAULT AS AML_BOVESPA, @DEFAULT AS AML_BMF, @DEFAULT AS AML_CORRETORA_BOVESPA, 
							@DEFAULT AS AML_CORRETORA_BMF, @DEFAULT AS OMC_BOVESPA, @DEFAULT AS OMC_BMF, @DEFAULT AS INSIDER_TRADING_BOVESPA, @DEFAULT AS PROCURADOR,
							@DEFAULT AS LAYERING_01, @DEFAULT AS SPOOFING_01, @DEFAULT AS TRANSFERENCIA_FINANCEIRA_01, @DEFAULT AS TRANSFERENCIA_FINANCEIRA_02,
							@DEFAULT AS CHURNING_01
		END
		ELSE
		BEGIN

		SELECT 
			CASE WHEN PATRIMONIO_CUSTODIA IS NULL THEN @DEFAULT ELSE PATRIMONIO_CUSTODIA END AS PATRIMONIO_CUSTODIA,
			CASE WHEN PATRIMONIO_MOVCC IS NULL THEN @DEFAULT ELSE PATRIMONIO_MOVCC END AS PATRIMONIO_MOVCC,
			CASE WHEN PATRIMONIO_NETTING IS NULL THEN @DEFAULT ELSE PATRIMONIO_NETTING END AS PATRIMONIO_NETTING,
			CASE WHEN PATRIMONIO_TRANSF_CUST IS NULL THEN @DEFAULT ELSE PATRIMONIO_TRANSF_CUST END AS PATRIMONIO_TRANSF_CUST,
			CASE WHEN SWING_BOVESPA IS NULL THEN @DEFAULT ELSE SWING_BOVESPA END AS SWING_BOVESPA,
			CASE WHEN SWING_BMF IS NULL THEN @DEFAULT ELSE SWING_BMF END AS SWING_BMF,
			CASE WHEN DAYTRADE_BOVESPA_01 IS NULL THEN @DEFAULT ELSE DAYTRADE_BOVESPA_01 END AS DAYTRADE_BOVESPA_01,
			CASE WHEN DAYTRADE_BMF_01 IS NULL THEN @DEFAULT ELSE DAYTRADE_BMF_01 END AS DAYTRADE_BMF_01,
			CASE WHEN MUDANCA_REPENTINA IS NULL THEN @DEFAULT ELSE MUDANCA_REPENTINA END AS MUDANCA_REPENTINA,
			CASE WHEN MEDIA_BOVESPA_01 IS NULL THEN @DEFAULT ELSE MEDIA_BOVESPA_01 END AS MEDIA_BOVESPA_01,
			CASE WHEN MEDIA_BMF_01 IS NULL THEN @DEFAULT ELSE MEDIA_BMF_01 END AS MEDIA_BMF_01,
			CASE WHEN AML_BOVESPA IS NULL THEN @DEFAULT ELSE AML_BOVESPA END AS AML_BOVESPA,
			CASE WHEN AML_BMF IS NULL THEN @DEFAULT ELSE AML_BMF END AS AML_BMF,
			CASE WHEN AML_CORRETORA_BOVESPA IS NULL THEN @DEFAULT ELSE AML_CORRETORA_BOVESPA END AS AML_CORRETORA_BOVESPA,
			CASE WHEN AML_CORRETORA_BMF IS NULL THEN @DEFAULT ELSE AML_CORRETORA_BMF END AS AML_CORRETORA_BMF,
			CASE WHEN OMC_BOVESPA IS NULL THEN @DEFAULT ELSE OMC_BOVESPA END AS OMC_BOVESPA,
			CASE WHEN INSIDER_TRADING_BOVESPA IS NULL THEN @DEFAULT ELSE INSIDER_TRADING_BOVESPA END AS INSIDER_TRADING_BOVESPA,
			CASE WHEN OMC_BMF IS NULL THEN @DEFAULT ELSE OMC_BMF END AS OMC_BMF,
			CASE WHEN LAYERING_01 IS NULL THEN @DEFAULT ELSE LAYERING_01 END AS LAYERING_01,
			CASE WHEN SPOOFING_01 IS NULL THEN @DEFAULT ELSE SPOOFING_01 END AS SPOOFING_01,
			CASE WHEN CHURNING_01 IS NULL THEN @DEFAULT ELSE CHURNING_01 END AS CHURNING_01,
			CASE WHEN TRANSFERENCIA_FINANCEIRA_01 IS NULL THEN @DEFAULT ELSE TRANSFERENCIA_FINANCEIRA_01 END AS TRANSFERENCIA_FINANCEIRA_01,
			CASE WHEN TRANSFERENCIA_FINANCEIRA_02 IS NULL THEN @DEFAULT ELSE TRANSFERENCIA_FINANCEIRA_02 END AS TRANSFERENCIA_FINANCEIRA_02,
			CASE WHEN PROCURADOR IS NULL THEN @DEFAULT ELSE PROCURADOR END AS PROCURADOR,
			CASE WHEN ATUALIZACAO_CADASTRAL IS NULL THEN @DEFAULT ELSE ATUALIZACAO_CADASTRAL END AS ATUALIZACAO_CADASTRAL
		FROM
		(
			SELECT PESO, ITEM
			FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO
		) D
		PIVOT
		(
			MAX(PESO)
			FOR ITEM IN ( PATRIMONIO_CUSTODIA,PATRIMONIO_MOVCC,PATRIMONIO_NETTING,PATRIMONIO_TRANSF_CUST,CHURNING_01,
							SWING_BOVESPA, SWING_BMF, DAYTRADE_BOVESPA_01, DAYTRADE_BMF_01, MUDANCA_REPENTINA,PROCURADOR,ATUALIZACAO_CADASTRAL,
							MEDIA_BOVESPA_01, MEDIA_BMF_01, AML_BOVESPA, AML_BMF, AML_CORRETORA_BOVESPA, AML_CORRETORA_BMF, OMC_BOVESPA,OMC_BMF,
							INSIDER_TRADING_BOVESPA, LAYERING_01, SPOOFING_01, TRANSFERENCIA_FINANCEIRA_01, TRANSFERENCIA_FINANCEIRA_02)
		) PIV;
	END

	 

	--TOTAL
	SELECT TIPO, SUM(PESO)PESO_TOTAL
	INTO #TOTAL
	FROM PORTALCONFIGSCORE
	WHERE TIPO ='TRANSACIONAL'
	GROUP BY TIPO

	--TRUNCATE TABLE ST_SCORE

	--INSERT INTO ST_SCORE
	--SELECT A.TIPO,
	--CASE WHEN A.ITEM = 'TRANSFERENCIA_FINANCEIRA_01'		THEN 'TRANSFERENCIA_FINANCEIRA_01'  
 --        WHEN A.ITEM = 'TRANSFERENCIA_FINANCEIRA_02'		THEN 'TRANSFERENCIA_FINANCEIRA_02'  
 --        WHEN A.ITEM = 'ATUALIZACAO_CADASTRAL'	THEN 'ATUALIZACAO_CADASTRAL'  
 --        WHEN A.ITEM = 'PROCURADOR'		    THEN 'PROCURADOR'  
 --        WHEN A.ITEM = 'PATRIMONIO_CUSTODIA'  THEN 'PATRIMONIO_CUSTODIA'  
 --        WHEN A.ITEM = 'PATRIMONIO_MOVIMENTO'	THEN 'PATRIMONIO_MOVCC'  
 --        WHEN A.ITEM = 'PATRIMONIO_NETTING'	THEN 'PATRIMONIO_NETTING'  
 --        WHEN A.ITEM = 'PATRIMONIO_TRANF_CUST'THEN 'PATRIMONIO_TRANSF_CUST'   
 --        WHEN A.ITEM = 'SWING_BOVESPA'	THEN 'SWING_BOVESPA'   
 --        WHEN A.ITEM = 'SWING_BMF'		THEN 'SWING_BMF'  
 --        WHEN A.ITEM = 'DAYTRADE_BOVESPA_01'		THEN 'DAYTRADE_BOVESPA_01'   
 --        WHEN A.ITEM = 'DAYTRADE_BMF_01'			THEN 'DAYTRADE_BMF_01'    
 --        WHEN A.ITEM = 'MUDANCA_REPENTINA'		THEN 'MUDANCA_REPENTINA'  
 --        WHEN A.ITEM = 'MEDIA_BOVESPA_01'			THEN 'MEDIA_BOVESPA_01'   
 --        WHEN A.ITEM = 'MEDIA_BMF_01'				THEN 'MEDIA_BMF_01' 
 --        WHEN A.ITEM = 'AML_BOVESPA'			THEN 'AML_BOVESPA'  
 --        WHEN A.ITEM = 'AML_BMF'				THEN 'AML_BMF' 
	--	 WHEN A.ITEM = 'AML_CORRETORA_BOVESPA'			THEN 'AML_CORRETORA_BOVESPA'  
 --        WHEN A.ITEM = 'AML_CORRETORA_BMF'				THEN 'AML_CORRETORA_BMF' 
 --        WHEN A.ITEM = 'OMC_BOVESPA'				    THEN 'OMC_BOVESPA'  
 --        WHEN A.ITEM = 'OMC_BMF'				    THEN 'OMC_BMF'  
 --        WHEN A.ITEM = 'INSIDER_TRADING_BOVESPA'			THEN 'INSIDER_TRADING_BOVESPA'  
 --        WHEN A.ITEM = 'CHURNING_01'			    THEN 'CHURNING_01'  
	--	 WHEN A.ITEM = 'LAYERING_01'			    THEN 'LAYERING_01' 
	--	 WHEN A.ITEM = 'SPOOFING_01'			    THEN 'SPOOFING_01' 
	--     ELSE A.ITEM END ITEM,

	--PESO,B.PESO_TOTAL,
	--(CAST(PESO AS FLOAT) / CAST(B.PESO_TOTAL AS FLOAT)) * 100 AS AJUSTE

	--FROM PORTALCONFIGSCORE A
	--LEFT OUTER JOIN #TOTAL B 
	--ON A.TIPO = B.TIPO
	
	--WHERE A.TIPO  = 'TRANSACIONAL'
 
	DROP TABLE #TOTAL

END