CREATE PROCEDURE [dbo].[FIRA_PR_CARGA_ST_MESA_BVSP]
AS

-- 1) cria tabela PADRAO baseada na estrutura atual da destino
DROP TABLE IF EXISTS [dbo].[ST_MESA_BVSP_PADRAO]
    CREATE TABLE [dbo].[ST_MESA_BVSP_PADRAO] (
    [CD_CLIENTE] int NOT NULL,
    [DT_PERIODO] smalldatetime NOT NULL,
    [NR_NEGOCIO] int NOT NULL,
    [CD_NATOPE] char(1) NOT NULL,
    [CD_PAPEL] varchar(12) NOT NULL,
    [NR_SEQORD] int NOT NULL,
    [CD_CONTRAPARTE] numeric(5,0) NULL,
    [CD_ASSESSOR] int NULL,
    [HH_NEGOCIO] varchar(5) NULL,
    [QT_NEGOCIO] bigint NULL,
    [VL_NEGOCIO] float NULL,
    [VL_TOTNEG] float NULL,
    [VL_CORTOT_ORI] float NULL,
    [CD_OPERADOR] int NULL,
    [DS_OPERADOR] varchar(160) NULL,
    [NM_CORRET] varchar(400) NULL,
    [TP_PESSOA] char(2) NULL,
    [CD_CPFCGC] varchar(20) NULL,
    [NM_CLIENTE] varchar(400) NULL,
	[DT_FIRA] DATETIME NULL
);

-- 2) sincroniza schema (PADRAO -> DESTINO)
EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo',, @src_table='ST_MESA_BVSP_PADRAO',
  @schema_name='dbo', @base_table='ST_MESA_BVSP',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1;

-- 3) corpo original


	DECLARE @DT_PREGAO	   SMALLDATETIME 
		  , @DT_PREGAO_FIM SMALLDATETIME
			
			-- CASO A TABELA ESTIVER VAZIA CARREGARÁ O MES EM QUE ESTIVER RODANDO.
			SET @DT_PREGAO	   = ISNULL((SELECT MAX(DT_PERIODO) FROM ST_MESA_BVSP),DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1)) 
			SET @DT_PREGAO_FIM = GETDATE()
		
	WHILE @DT_PREGAO < @DT_PREGAO_FIM
	BEGIN
		PRINT CONVERT(VARCHAR,@DT_PREGAO,23)
		DELETE FROM ST_MESA_BVSP WHERE DT_PERIODO = @DT_PREGAO;

		INSERT INTO ST_MESA_BVSP 
		(
		CD_CLIENTE,DT_PERIODO,NR_NEGOCIO,CD_NATOPE,CD_PAPEL,CD_CONTRAPARTE,NR_SEQORD,
		CD_ASSESSOR,HH_NEGOCIO,QT_NEGOCIO,VL_NEGOCIO,VL_TOTNEG,VL_CORTOT_ORI,CD_OPERADOR,
		DS_OPERADOR,NM_CORRET,TP_PESSOA,CD_CPFCGC,NM_CLIENTE
		)
	     
			 SELECT 
		   DISTINCT F.CD_CLIENTE
				  , DT_NEGOCIO 
				  , F.NR_NEGOCIO
				  , F.CD_NATOPE
				  , CD_PAPEL
				  , F.CD_CONTRAPARTE		
				  , F.NR_SEQORD
				  , F.CD_ASSESSOR
				  , F.HH_NEGOCIO		
				  ,SUM(F.QT_MULTIPLICADOR)
				  ,AVG(F.VL_NEGOCIO)						
				  ,CASE WHEN CD_NATOPE ='V' THEN CAST(SUM (VL_TOTNEG) AS FLOAT) *-1 ELSE CAST(SUM (VL_TOTNEG) AS FLOAT) END --SUM(F.VL_TOTNEG)							
				  ,SUM(F.VL_CORTOT_ORI)
				  ,F.CD_OPERADOR
				  ,CASE WHEN PP.CD_OPERADOR =99999 THEN 'OPERADOR NÃO CADASTRADO' ELSE PP.DS_OPERADOR END DS_OPERADOR
				  ,COR.NM_CORRET
				  ,CASE WHEN TIPO = 'F' THEN 'PF' ELSE 'PJ' END TP_PESSOA
				  ,CD_CPFCGC
				  ,NM_CLIENTE
			  FROM ST_CORRETAGEM_ORDEM F (NOLOCK)	
		 LEFT JOIN ST_CORRETORA COR 
				ON F.CD_CONTRAPARTE = COR.CD_CORRET 		
		 LEFT JOIN (SELECT DISTINCT CD_OPERADOR,DS_OPERADOR FROM ST_OPERADOR) PP 
				ON  F.CD_OPERADOR = PP.CD_OPERADOR
		LEFT JOIN  (SELECT DISTINCT CD_CLIENTE,NM_CLIENTE,CD_CPFCGC,TIPO FROM V_CLIENTE_TODOS) V
			  ON F.CD_CLIENTE = V.CD_CLIENTE
			 WHERE DT_NEGOCIO = @DT_PREGAO
			 
		  GROUP BY F.CD_CLIENTE
				 , DT_NEGOCIO 
				 , F.NR_NEGOCIO
				 , F.CD_NATOPE
				 , CD_PAPEL
				 , f.CD_CONTRAPARTE		
				 , F.NR_SEQORD
				 , F.CD_ASSESSOR
				 , F.HH_NEGOCIO
				 , F.CD_OPERADOR
				 , PP.CD_OPERADOR
				 , PP.DS_OPERADOR
				 , COR.NM_CORRET
				 , TIPO
				 , CD_CPFCGC
				 , NM_CLIENTE;
				 --, ASS.NM_ASSESSOR;
				
	    SET @DT_PREGAO = DATEADD(DAY,1,@DT_PREGAO)

		END;

-- ================================================
-- Marca DT_FIRA para registros carregados (fallback)
-- ================================================
	DECLARE @__dt_fira_now DATETIME = GETDATE();
IF COL_LENGTH(N'dbo.ST_MESA_BVSP', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE [dbo].[ST_MESA_BVSP]
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL;
END
-- 4) limpa PADRAO
DROP TABLE IF EXISTS [dbo].[ST_MESA_BVSP_PADRAO];