CREATE   PROCEDURE [dbo].[PR_PATRIMONIOXCUSTODIA_PERIODO] @INICIO SMALLDATETIME, @FIM SMALLDATETIME,@CD_CLIENTE VARCHAR(50),@QTDPORPAGINA INT, @PAGINA INT
WITH RECOMPILE
AS

--DECLARE @PAGINA        INT 
--DECLARE @QTDPORPAGINA INT 
--DECLARE @INICIO SMALLDATETIME, @FIM SMALLDATETIME ,@CD_CLIENTE VARCHAR(50),@IND VARCHAR(10),@IN_SITUAC VARCHAR(10)
--SET @CD_CLIENTE='852' 
--SET @INICIO ='20251201'
--SET @FIM ='20251231'

 	DECLARE @CD_ANOMES_INICIO_180 INT,@CD_ANOMES_FIM_180 INT	
	SET @CD_ANOMES_INICIO_180 = (SELECT TOP 1 YEAR(EOMONTH(DT_PERIODO,-7))*100 + MONTH(EOMONTH(DT_PERIODO,-7)) FROM ST_PERIODO WHERE DT_PERIODO = @INICIO)
	SET @CD_ANOMES_FIM_180 = (SELECT TOP 1 YEAR(EOMONTH(DT_PERIODO,-1))*100 + MONTH(EOMONTH(DT_PERIODO,-1)) FROM ST_PERIODO WHERE DT_PERIODO = @INICIO)



---PATRIMONIO  
---busco o patrimonio do ultimo dia util do mes do alerta
--;with #patrimonio as (
drop table if exists #PATRIMONIO
SELECT XX.CD_CLIENTE, isnull(CAST(SUM(VAL_BENS) AS NUMERIC(38,2)),0) PATRIMONIO
INTO #PATRIMONIO
FROM ST_PATRIMONIO_LIQ  XX
WHERE DATA = (SELECT MAX(DATA) FROM ST_PATRIMONIO_LIQ YY 
				WHERE  (DATA) >= @INICIO
				AND  (DATA) <= @FIM
				and DATEPART(WEEKDAY, DATA) NOT IN (7,1)
				)
GROUP BY  XX.CD_CLIENTE
 --)

CREATE NONCLUSTERED INDEX T1 oN [DBO].[#PATRIMONIO] ([CD_CLIENTE]) INCLUDE ([PATRIMONIO])  


;WITH MEDIA_180 AS (
		  SELECT a.CD_CLIENTE
			   , AVG(cast(MED_CARTEIRA as decimal(15,2)))  AS MED_CARTEIRA
		    FROM ST_CARTEIRA_MEDIA_MENSAL A			 
		   WHERE CD_ANOMES >= @CD_ANOMES_INICIO_180
		     AND CD_ANOMES <= @CD_ANOMES_FIM_180
			 and a.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'')='' THEN A.CD_CLIENTE ELSE ISNULL(@CD_CLIENTE,'') END
		GROUP BY a.CD_CLIENTE
		)
			   		 	  	  	   	
									
									 
SELECT DISTINCT
convert(varchar,DT_CUSTODIA,103) AS [PERÍODO]
,A.CD_CLIENTE AS [CÓD. CLIENTE]
,A.CD_CPFCGC  AS [CPF/CNPJ]
,A.NM_CLIENTE [NOME DO CLIENTE]
,DS_ATIV AS [PROFISSÃO]
,FORMAT(POSICAO_CC,'f','pt-br') as [saldo cc]
,FORMAT(POSICAO_BOVESPA,'f','pt-br') as [acoes bvsp]
,FORMAT(POSICAO_BMF,'f','pt-br') as  [acoes bmf]
,FORMAT(TESOURO,'f','pt-br') as [tesouro]
,FORMAT(RENDA_FIXA,'f','pt-br') as [renda fixa]
,FORMAT(FUNDOS,'f','pt-br') as [fundos]
,FORMAT(CARTEIRA,'f','pt-br') as [carteira total]
,FORMAT(c.PATRIMONIO,'f','pt-br') [PATRIMONIO]
,FORMAT(MED_CARTEIRA,'f','pt-br') as [MED CARTEIRA 6M]
FROM ST_PATRIMONIO_CUSTODIA A
left outer join MEDIA_180 b on a.CD_CLIENTE = b.CD_CLIENTE
inner join ( SELECT distinct DT_PERIODO FROM ST_PERIODO WHERE DT_FERIADO = 'NAO' AND DS_DIASEMANA NOT IN ('SABADO','DOMINGO'))  bb on a.dt_custodia = bb.DT_PERIODO
left outer join #PATRIMONIO c on a.CD_CLIENTE = c.CD_CLIENTE


WHERE DT_CUSTODIA >= @INICIO AND DT_CUSTODIA <= @FIM 
AND A.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'')='' THEN A.CD_CLIENTE ELSE ISNULL(@CD_CLIENTE,'') END
and  CARTEIRA > 0


ORDER BY 1,2
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;