CREATE PROCEDURE [dbo].[PR_ZE_COM_ZE_BMF] 
(
	@INICIO DATETIME,
	@FIM DATETIME,
    @CD_CLIENTE_COMPRA VARCHAR(10),
	@CD_COMMOD VARCHAR(50),
	@CD_SERIE VARCHAR(50),
	@QTDPORPAGINA INT, @PAGINA INT
)
--WITH ENCRYPTION
AS


--DECLARE @PAGINA  INT = 1;
--DECLARE @QTDPORPAGINA INT = 5,
--@INICIO DATETIME,
--	@FIM DATETIME,
--    @CD_CLIENTE_COMPRA VARCHAR(10) ,
--	@CD_COMMOD VARCHAR(50),
--	@CD_SERIE VARCHAR(5)

--SET @INICIO  ='20230101'
--SET @FIM  = '20231231'
--SET @CD_CLIENTE_COMPRA =''
--SET @CD_COMMOD =''
--SET @CD_SERIE =''
	

SELECT
CONVERT(VARCHAR(20),[DT_NEGOCIO],103) [PERÍODO]
,[CD_CLIENTE_COMPRA] as [CÓD. CLIENTE COMPRA]
,[NM_CLIENTE_COMPRA] AS [NOME DO CLIENTE COMPRA]
,CASE WHEN [VINC_COMPRA] ='S' THEN 'SIM' WHEN [VINC_COMPRA] = 'N' THEN 'NÃO' END AS [VINC. COMPRA]
,[CD_CLIENTE_VENDA] AS [CÓD. CLIENTE VENDA]
,[NM_CLIENTE_VENDA] AS [NOME DO CLIENTE VENDA]
,CASE WHEN [VINC_VENDA] ='S' THEN 'SIM' WHEN [VINC_VENDA] ='N' THEN 'NÃO' END [VINC. VENDA]
--,[SISTEMA_COMPRA] [SISTEMA COMPRA]
--,[SISTEMA_VENDA] [SISTEMA VENDA]
,[NR_NEGOCIO] [NR. NEGÓCIO]
,FORMAT(SUM([QT_NEGOCIO_COMPRA]),'#.#','PT-BR') [QTD. NEGÓCIO COMPRA]
,FORMAT(SUM([QT_NEGOCIO_VENDA]),'#.#','PT-BR') [QTD. NEGÓCIO VENDA]
,[CD_SERIE][SÉRIE]
,CD_COMMOD [COMMOD]
,[HH_COMPRA] [HORA COMPRA]
,[HH_VENDA] [HORA VENDA]
,FORMAT(SUM([VL_TOTNEG_COMPRA]),'f','pt-br') [VL. TOTNEG. COMPRA]
,FORMAT(SUM([VL_TOTNEG_VENDA]),'f','pt-br') [VL. TOTNEG. VENDA]
,FORMAT(SUM([VL_NEGOCIO_COMPRA]),'f','pt-br') [VL. NEGÓCIO COMPRA]
,FORMAT(SUM([VL_NEGOCIO_VENDA]),'f','pt-br') [VL. NEGÓCIO VENDA]
,[CD_ASSESSOR_COMPRA] [CÓD. ASSESSOR COMPRA]
,[DS_ASSESSOR_COMPRA] [DS. ASSESSOR COMPRA]
--,[CD_ASSESSOR_VENDA] [CÓD. ASSESSOR VENDA]
--,[DS_ASSESSOR_VENDA] [DS. ASSESSOR VENDA]
--,USUARIO_COMPRA [CÓD. CLIENTE BRO. COMPRA]
--,USUARIO_VENDA [CÓD. CLIENTE BRO. VENDA]
,IN_AFTER [IN. AFTERM]
  
FROM [ST_DIRETAS_BMF]
WHERE 
CD_CLIENTE_COMPRA = CD_CLIENTE_VENDA 
AND DT_NEGOCIO >=@INICIO AND DT_NEGOCIO<=@FIM 
AND CD_CLIENTE_COMPRA = (CASE WHEN ISNULL(@CD_CLIENTE_COMPRA,'') = '' THEN CD_CLIENTE_COMPRA ELSE CONVERT(INT,@CD_CLIENTE_COMPRA) END)
AND CD_SERIE = (CASE WHEN ISNULL(@CD_SERIE,'') ='' THEN CD_SERIE ELSE @CD_SERIE END)
AND CD_COMMOD = (CASE WHEN ISNULL(@CD_COMMOD,'')=''  THEN CD_COMMOD ELSE @CD_COMMOD END)
  
GROUP BY 
 [CD_CLIENTE_COMPRA],[NM_CLIENTE_COMPRA],[VINC_COMPRA],[CD_CLIENTE_VENDA],[NM_CLIENTE_VENDA],[VINC_VENDA]
,CONVERT(VARCHAR(20),[DT_NEGOCIO],103),[SISTEMA_COMPRA],[SISTEMA_VENDA],[NR_NEGOCIO],[CD_SERIE],[HH_COMPRA]
,[HH_VENDA],[CD_ASSESSOR_COMPRA],[DS_ASSESSOR_COMPRA],[CD_ASSESSOR_VENDA],[DS_ASSESSOR_VENDA],   USUARIO_COMPRA,
USUARIO_VENDA,CD_COMMOD, IN_AFTER
 


ORDER BY 1
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;