CREATE PROCEDURE [dbo].[PR_RELATORIO_CARGAS] @DATA SMALLDATETIME,@QTDPORPAGINA INT, @PAGINA INT 
AS

SELECT 
IDLOG AS [ID] 
,IDPROCESSO AS [ID PROCESSO] 
,PROCESSO AS [NOME DO PROCESSO] 
,FORMAT(DTCARGA,'d','PT-BR') AS [DATA CARGA] 
,FORMAT(DTINICIO, 'dd/MM/yyyy HH:mm:ss', 'pt-BR')AS [INICIO]
,FORMAT(DTFIM, 'dd/MM/yyyy HH:mm:ss', 'pt-BR')AS [FIM]
,FORMAT(TEMPO_EXECUCAO, 'HH:mm:ss') AS [TEMPO DE EXECUCAO] 
,STATUS AS [STATUS] 
,ERRO 

FROM 
ST_LOG_CARGA

WHERE 
CAST(DTCARGA AS DATE) >= @DATA 

ORDER BY 1 DESC 

OFFSET (ISNULL(@PAGINA,1) - 1)* CASE WHEN ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS 
FETCH NEXT CASE WHEN ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;