CREATE PROCEDURE [dbo].[FIRA_PR_CARGA_ALERT_RELATORIO] @pregao smalldatetime, @aux int
--WITH RECOMPILE
AS

DECLARE @CD_ANO VARCHAR(4), 
		@DS_MES  VARCHAR(20),
		@dt_alerta smalldatetime, 
		@dia_util int


/*****************************************
REPROCESAMENTO DESCOMENTAR AQUI
******************************************/
--DECLARE @PREGAO SMALLDATETIME, @AUX INT
--SET @PREGAO = '20260105'
--SET @AUX = (SELECT DAY(@PREGAO))


set @dt_alerta = (select cast(@pregao - @aux as date))
SET @CD_ANO = (select max(cd_Ano) from st_periodo where dt_periodo = @dt_alerta) 
SET @DS_MES = (select max(ds_mes) from st_periodo where dt_periodo = @dt_alerta)


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ST_RELATORIO_PAINEL_ALERTAS_CVM_PADRAO]') AND type in (N'U'))
CREATE TABLE [dbo].[ST_RELATORIO_PAINEL_ALERTAS_CVM_PADRAO](
	[ANALISE] [varchar](8)  NULL,
	[Referencia] [varchar](42) NULL,
	[Cód. Cliente] [int] NULL,
	[NOME DO CLIENTE] [nvarchar](160) NULL,
	[NACIONALIDADE] [varchar](160) NULL,
	[CPF/CNPJ] [varchar](20) NULL,
	[PF / PJ] [varchar](3)  NULL,
	[IDADE] [int] NULL,
	[INVESTIDOR] [nvarchar](160) NULL,
	[DATA DE CRIAÇÃO] [nvarchar](4000) NULL,
	[FRONTEIRA] [varchar](3) NULL,
	[PEP SINACOR] [varchar](3)  NULL,
	[PESSOA VINCULADA] [varchar](3) NULL,
	[INR] [varchar](13) NULL,
	[ASSESSOR] [varchar](160) NULL,
	[PROFISSÃO / SEGMENTO DE ATUAÇÃO] [varchar](160) NULL,
	[PROFISSÃO DE RISCO] [varchar](160) NULL,
	[SCORE RISCO] [varchar](5) NULL,
	[RISCO ABR] [varchar](10) NULL,
	[Money Pass Corretora Bvsp] [nvarchar](4000) NULL,
	[Money Pass Corretora Bmf] [nvarchar](4000) NULL,
	[Money Pass Bvsp] [nvarchar](4000) NULL,
	[Money Pass Bmf] [nvarchar](4000) NULL,
	[Média Oper. Bmf] [nvarchar](4000) NULL,
	[Média Oper. Bvsp] [nvarchar](4000) NULL,
	[Transf. Financeira 01] [nvarchar](4000) NULL,
	[Transf. Financeira 02] [nvarchar](4000) NULL,
	[Patrimônio X Custódia] [nvarchar](4000) NULL,
	[Patrimônio X Netting] [nvarchar](4000) NULL,
	[Patrimônio X Mov Cc] [nvarchar](4000) NULL,
	[Patrimônio X Transf. Custodia] [nvarchar](4000) NULL,
	[Atualização Cadastral] [nvarchar](4000) NULL,
	[Procurador] [nvarchar](4000) NULL,
	[Mudança Repentina] [nvarchar](4000) NULL,
	[Ranking Daytrade Bvsp] [nvarchar](4000) NULL,
	[Ranking Daytrade Bmf] [nvarchar](4000) NULL,
	[Ativo Restrito] [nvarchar](4000) NULL,
	[Insider Trading] [nvarchar](4000) NULL,
	[Churning] [nvarchar](4000) NULL,
	[Omc Bvsp] [nvarchar](4000) NULL,
	[Omc Bmf] [nvarchar](4000) NULL,
	[Oscilação] [nvarchar](4000) NULL,
	[Omg Bvsp] [nvarchar](4000) NULL,
	[Omg Bmf] [nvarchar](4000) NULL,
	[Vinculado ao Emissor] [nvarchar](4000) NULL,
	[TOTAL] [int] NULL,
	[DT_FIRA] DATETIME NULL
) ON [PRIMARY]
 
--/***************************************************
--inicio da comparação entre a tabela
--da base padrao fira origem x tabela cliente destino
--*****************************************************/
---- 1) Faz o sync (pode ficar estático)
EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo', @src_table='ST_RELATORIO_PAINEL_ALERTAS_CVM_PADRAO',
  @schema_name='dbo', @base_table='ST_RELATORIO_PAINEL_ALERTAS_CVM',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1;

delete from ST_RELATORIO_PAINEL_ALERTAS_CVM
WHERE ltrim(rTRIM(LEFT(REFERENCIA, CHARINDEX('/', REFERENCIA) - 1))) = @DS_MES
AND ltrim(rTRIM(SUBSTRING(REFERENCIA, CHARINDEX('/', REFERENCIA) + 1, LEN(REFERENCIA)))) = @CD_ANO
 
 /**********************************************************************
3) INSERT em SQL dinâmico (compila após o ALTER) INSERT com lista 
explícita de colunas Isso evita dor de cabeça caso a tabela destino 
tenha colunas a mais, ordem diferente, identity, etc.
**********************************************************************/
DECLARE @sql nvarchar(max) = N'
DROP TABLE IF EXISTS STG_WV_RISCO_FINAL
CREATE TABLE STG_WV_RISCO_FINAL ([Data] VARCHAR(20), [Cód. do Cliente] int,[Nome do Cliente] nvarchar(160),[RISCO_FINAL] varchar(5))
INSERT INTO STG_WV_RISCO_FINAL
(
    [Data], [Cód. do Cliente],[Nome do Cliente],[RISCO_FINAL]
)
SELECT [Data],[Cód. do Cliente],[Nome do Cliente],[RISCO_FINAL] 
FROM WV_RISCO_FINAL
where year(data) = '''+@cd_Ano+'''
and CASE WHEN month(data) = 1 THEN ''JANEIRO'' 
         WHEN month(data) = 2 THEN ''FEVEREIRO''
         WHEN month(data) = 3 THEN ''MARÇO''
         WHEN month(data) = 4 THEN ''ABRIL''
         WHEN month(data) = 5 THEN ''MAIO''
         WHEN month(data) = 6 THEN ''JUNHO''
         WHEN month(data) = 7 THEN ''JULHO''
         WHEN month(data) = 8 THEN ''AGOSTO''
		 WHEN month(data) = 9 THEN ''SETEMBRO''
         WHEN month(data) = 10 THEN ''OUTUBRO''
         WHEN month(data) = 11 THEN ''NOVEMBRO''
         WHEN month(data) = 12 THEN ''DEZEMBRO'' END = '''+@DS_MES+'''


---FRONTEIRA
DROP TABLE IF EXISTS STG_FRONTEIRA
CREATE TABLE STG_FRONTEIRA ([Cidade] varchar(50),[UF] varchar(4))
INSERT INTO STG_FRONTEIRA
(
    [CIDADE], [UF]
)
SELECT DISTINCT DBO.FN_FORMATAR_TEXTO(NOME)[Cidade],
SUBSTRING(
        Detalhes, 
        CHARINDEX(''SIGLA_UF:'', Detalhes) + LEN(''SIGLA_UF:''), 
        2
    ) AS [UF] FROM ListaAtencao 
WHERE IdSublista = 47
AND  CHARINDEX(''SIGLA_UF:'', Detalhes) > 0



insert into ST_RELATORIO_PAINEL_ALERTAS_CVM 
(
	 [ANALISE],[Referencia],[Cód. Cliente],[NOME DO CLIENTE],[NACIONALIDADE],[CPF/CNPJ],[PF / PJ],[IDADE]
	,[INVESTIDOR],[DATA DE CRIAÇÃO],[FRONTEIRA],[PEP SINACOR],[PESSOA VINCULADA],[INR],[ASSESSOR],[PROFISSÃO / SEGMENTO DE ATUAÇÃO]
	,[PROFISSÃO DE RISCO],[SCORE RISCO],[RISCO ABR],[Money Pass Corretora Bvsp],[Money Pass Corretora Bmf],[Money Pass Bvsp]
	,[Money Pass Bmf],[Média Oper. BMF],[Média Oper. Bvsp],[Transf. Financeira 01],[Transf. Financeira 02],[Patrimônio X Custódia]
	,[Patrimônio X Netting],[Patrimônio X Mov Cc],[Patrimônio X Transf. Custodia],[Atualização Cadastral],[Procurador],[Mudança Repentina]
	,[Ranking Daytrade Bvsp],[Ranking Daytrade Bmf],[Ativo Restrito],[Insider Trading],[Churning],[Omc Bvsp],[Omc Bmf]
	,[Oscilação],[Omg Bvsp],[Omg Bmf],[Vinculado ao Emissor],[TOTAL]
)

SELECT 
CASE
    WHEN UPPER(ISNULL(MAX(rsel.RISCO_FINAL), '''')) = ''ALTO''				 THEN ''VERMELHO''
    WHEN UPPER(ISNULL(MAX(rsel.RISCO_FINAL), '''')) IN (''MÉDIO'',''MEDIO'') THEN ''AMARELO''
    WHEN UPPER(ISNULL(MAX(rsel.RISCO_FINAL), '''')) = ''BAIXO''				 THEN ''VERDE''
    ELSE '''' END AS [ANALISE],
                       CASE WHEN CD_MES = 1 THEN ''JANEIRO''
                            WHEN CD_MES = 2 THEN ''FEVEREIRO''
                            WHEN CD_MES = 3 THEN  ''MARÇO''
                            WHEN CD_MES = 4 THEN  ''ABRIL''
                            WHEN CD_MES = 5 THEN  ''MAIO''
                            WHEN CD_MES = 6 THEN  ''JUNHO''
                            WHEN CD_MES = 7 THEN  ''JULHO''
                            WHEN CD_MES = 8 THEN  ''AGOSTO''
                            WHEN CD_MES = 9 THEN  ''SETEMBRO''
                            WHEN CD_MES = 10 THEN ''OUTUBRO''
                            WHEN CD_MES = 11 THEN ''NOVEMBRO''
                            WHEN CD_MES = 12 THEN ''DEZEMBRO'' END +'' / ''+ CAST(DD.CD_ANO AS VARCHAR) AS Referencia,

                Y.CD_CLIENTE AS [Cód. Cliente],
                T1.NM_CLIENTE AS [NOME DO CLIENTE],
                MAX(T1.DS_NACION) AS [NACIONALIDADE],
                CASE WHEN LEN(T1.CD_CPFCGC) > 11 THEN dbo.formatar_cnpj(t1.cd_cpfcgc) ELSE dbo.formatar_cpf(t1.cd_cpfcgc)  END AS [CPF/CNPJ], 
                CASE WHEN LEN(T1.CD_CPFCGC) > 11 THEN ''PJ'' ELSE ''PF '' END AS [PF / PJ],             
                MAX(T1.IDADE) AS [IDADE],
                MAX(T1.DS_TIPO_CLIENTE) AS [INVESTIDOR],                
                FORMAT(T1.DT_CRIACAO,''d'',''PT-BR'') AS [DATA DE CRIAÇÃO],
				CASE WHEN F.CIDADE IS NOT NULL THEN ''SIM''
				ELSE ''NÃO''
				END AS [FRONTEIRA],
                CASE WHEN T1.IN_POLITICO_EXP = ''S'' THEN ''SIM''
                WHEN T1.IN_POLITICO_EXP = ''N'' THEN ''NÃO''
                ELSE  '''' END AS [PEP SINACOR],
                CASE WHEN T1.IN_PESS_VINC = ''S'' THEN ''SIM''
                WHEN T1.IN_PESS_VINC = ''N'' THEN ''NÃO''
                ELSE  '''' END AS [PESSOA VINCULADA],
                MAX(T1.INR) AS [INR],
                MAX(T1.NM_ASSESSOR) AS [ASSESSOR],
                MAX(T1.DS_ATIV) AS [PROFISSÃO / SEGMENTO DE ATUAÇÃO],
                ISNULL(MAX(T1.RISCO),''NÃO INFORMADO'') AS [PROFISSÃO DE RISCO],
                ISNULL(MAX(rsel.RISCO_FINAL), '''') AS [SCORE RISCO],
				MAX(T1.PERFIL) AS [RISCO ABR], --essa informação virá de cada cliente.
				
             
FORMAT(CASE WHEN SUM(MONEYPASS_CORRETORA) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'')   AS [Money Pass Corretora Bvsp], 
FORMAT(CASE WHEN SUM(MONEYPASS_CORRETORA_BMF) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'')    AS [Money Pass Corretora Bmf],
FORMAT(CASE WHEN SUM(MONEYPASS_BVSP_02) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'')   AS [Money Pass Bvsp],
FORMAT(CASE WHEN SUM(MONEYPASS_BMF_02) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'')   AS [Money Pass Bmf],
FORMAT(CASE WHEN SUM(MEDIA_BMF_01) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'')  AS [Média Oper. BMF], 
FORMAT(CASE WHEN SUM(MEDIA_BOVESPA_01) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'')  AS [Média Oper. Bvsp],
FORMAT(CASE WHEN SUM(TRANSFERENCIA_FINANCEIRA_01) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'')  AS [Transf. Financeira 01],
FORMAT(CASE WHEN SUM(TRANSFERENCIA_FINANCEIRA_02) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'')  AS [Transf. Financeira 02],
FORMAT(CASE WHEN SUM(PATRIMONIO_CUSTODIA) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'') AS [Patrimônio X Custódia],
FORMAT(CASE WHEN SUM(PATRIMONIO_NETTING) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'')   AS [Patrimônio X Netting],
FORMAT(CASE WHEN SUM(PATRIMONIO_MOVCC) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'')  AS [Patrimônio X Mov Cc], 
FORMAT(CASE WHEN SUM(PATRIMONIO_TRANSF_CUST) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'')   AS [Patrimônio X Transf. Custodia],
FORMAT(CASE WHEN SUM(ATULIZACAO_CADASTRAL_01) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'') AS [Atualização Cadastral],
FORMAT(CASE WHEN SUM(PROCURADOR_01) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'')  AS Procurador, 
FORMAT(CASE WHEN SUM(MUDANCA_REPENTINA_01) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'')  AS [Mudança Repentina],
FORMAT(CASE WHEN SUM(RANKING_DAYTRADE_BVSP) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'')   AS [Ranking Daytrade Bvsp],
FORMAT(CASE WHEN SUM(RANKING_DAYTRADE_BMF) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'')   AS [Ranking Daytrade Bmf],
FORMAT(CASE WHEN SUM(ATIVO_RESTRITO) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'')   AS [Ativo Restrito],
--CVM 62/08
FORMAT (CASE WHEN SUM(INSIDER_TRADING_BOVESPA_02) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'') AS [Insider Trading], 
FORMAT (CASE WHEN SUM(CHURNING_02) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'') AS [Churning],
FORMAT (CASE WHEN SUM(OMC_01) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'')  AS [Omc Bvsp],
FORMAT (CASE WHEN SUM(OMC_BMF_01) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'')  AS [Omc Bmf], 
FORMAT(CASE WHEN SUM(OSCILACAO) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'')   AS [Oscilação],
FORMAT(CASE WHEN SUM(OMG_BOVESPA) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'')   AS [Omg Bvsp],
FORMAT(CASE WHEN SUM(OMG_BMF) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'')   AS [Omg Bmf],
FORMAT(CASE WHEN SUM(VINCULADO_EMISSOR) > 0 THEN 1 ELSE 0 END,''0.#'',''PT-BR'')   AS [Vinculado ao Emissor],

CASE WHEN SUM(CHURNING_02) > 0 THEN 1 ELSE 0 END +
CASE WHEN SUM(OMC_01) > 0 THEN 1 ELSE 0 END  +
CASE WHEN SUM(OMC_BMF_01) > 0 THEN 1 ELSE 0 END  + 
CASE WHEN SUM(INSIDER_TRADING_BOVESPA_02) > 0 THEN 1 ELSE 0 END +
CASE WHEN SUM(ATULIZACAO_CADASTRAL_01) > 0 THEN 1 ELSE 0 END +
CASE WHEN SUM(PROCURADOR_01) > 0 THEN 1 ELSE 0 END + 
CASE WHEN SUM(MUDANCA_REPENTINA_01) > 0 THEN 1 ELSE 0 END +
CASE WHEN SUM(MEDIA_BMF_01) > 0 THEN 1 ELSE 0 END +
CASE WHEN SUM(MEDIA_BOVESPA_01) > 0 THEN 1 ELSE 0 END +
CASE WHEN SUM(TRANSFERENCIA_FINANCEIRA_01) > 0 THEN 1 ELSE 0 END +
CASE WHEN SUM(TRANSFERENCIA_FINANCEIRA_02) > 0 THEN 1 ELSE 0 END +
CASE WHEN SUM(MONEYPASS_CORRETORA) > 0 THEN 1 ELSE 0 END  +
CASE WHEN SUM(MONEYPASS_CORRETORA_BMF) > 0 THEN 1 ELSE 0 END +
CASE WHEN SUM(PATRIMONIO_CUSTODIA) > 0 THEN 1 ELSE 0 END +
CASE WHEN SUM(PATRIMONIO_NETTING) > 0 THEN 1 ELSE 0 END +
CASE WHEN SUM(PATRIMONIO_MOVCC) > 0 THEN 1 ELSE 0 END + 
CASE WHEN SUM(PATRIMONIO_TRANSF_CUST) > 0 THEN 1 ELSE 0 END +
CASE WHEN SUM(MONEYPASS_BVSP_02) > 0 THEN 1 ELSE 0 END +
CASE WHEN SUM(MONEYPASS_BMF_02) > 0 THEN 1 ELSE 0 END+
CASE WHEN SUM(RANKING_DAYTRADE_BVSP) > 0 THEN 1 ELSE 0 END+
CASE WHEN SUM(RANKING_DAYTRADE_BMF) > 0 THEN 1 ELSE 0 END+
CASE WHEN SUM(OSCILACAO) > 0 THEN 1 ELSE 0 END+
CASE WHEN SUM(OMG_BOVESPA) > 0 THEN 1 ELSE 0 END+
CASE WHEN SUM(OMG_BMF) > 0 THEN 1 ELSE 0 END+
CASE WHEN SUM(ATIVO_RESTRITO) > 0 THEN 1 ELSE 0 END+
CASE WHEN SUM(VINCULADO_EMISSOR) > 0 THEN 1 ELSE 0 END
AS [TOTAL]

FROM(
		--ST_ALERT_MONEYPASS_CORRETORA
         SELECT DISTINCT DATA,CD_CLIENTE,
		 COUNT(distinct 1)  MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_MONEYPASS_CORRETORA INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+''') X
        GROUP BY DATA,CD_CLIENTE

		 
        UNION ALL -- MONEYPASS_CORRETORA
        SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,COUNT(distinct 1)  MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_MONEYPASS_CORRETORA_BMF INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+''') X
        GROUP BY DATA,CD_CLIENTE
        UNION ALL

        ---ST_ALERT_MONEYPASS_02
        SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,COUNT(distinct 1)  MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_MONEYPASS_02 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE
			   
        UNION ALL --ST_ALERT_MONEYPASS_BMF_02
        SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,COUNT(distinct 1)  MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE AS CD_CLIENTE
        FROM ST_ALERT_MONEYPASS_BMF_02 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL --ST_ALERT_MEDIA_BMF_01
        SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,COUNT(distinct 1)  MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_MEDIA_BMF_01 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL --ST_ALERT_MEDIA_BOVESPA_01
        SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,COUNT(distinct 1)  MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_MEDIA_BOVESPA_01 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL --ST_ALERT_TRANSFERENCIA_FINANCEIRA_01
        SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,COUNT(distinct 1)  TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_TRANSFERENCIA_FINANCEIRA_01 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL --ST_ALERT_TRANSFERENCIA_FINANCEIRA_02
        SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,COUNT(distinct 1)  TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_TRANSFERENCIA_FINANCEIRA_02 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL --ST_ALERT_PATRIMONIO_CUSTODIA
        SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,COUNT(distinct 1)  PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSORO
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_PATRIMONIO_CUSTODIA INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE


        UNION ALL --ST_ALERT_PATRIMONIO_NETTING
        SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,COUNT(distinct 1)  PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_PATRIMONIO_NETTING INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE



        UNION ALL --ST_ALERT_PATRIMONIO_MOVIMENTO 
        SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,COUNT(distinct 1)  PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_PATRIMONIO_MOVIMENTO INNER JOIN ST_PERIODO ON DATA = ST_PERIODO.DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE


        UNION ALL -- ST_ALERT_PATRIMONIO_TRANF_CUST 
        SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,COUNT(distinct 1)  PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_PATRIMONIO_TRANF_CUST 
		INNER JOIN ST_PERIODO ON DATA = ST_PERIODO.DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL --ST_ALERT_ATULIZACAO_CADASTRAL_01
        SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,COUNT(distinct 1)  ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_ATULIZACAO_CADASTRAL_01 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL  --ST_ALERT_PROCURADOR_02
        SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,COUNT(distinct 1)  PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_PROCURADOR_02 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL  --ST_ALERT_MUDANCA_REPENTINA_01
        SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,COUNT(distinct 1)  MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_MUDANCA_REPENTINA_01 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL  --ST_ALERT_RANKING_DAYTRADE_BVSP
        SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,COUNT(distinct 1)  RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_RANKING_DAYTRADE_BVSP INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL  --ST_ALERT_RANKING_DAYTRADE_BMF
        SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,COUNT(distinct 1)  RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_RANKING_DAYTRADE_BMF INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL  --ST_ALERT_ATIVO_RESTRITO
        SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,COUNT(distinct 1)  ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_ATIVO_RESTRITO INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL  --ST_ALERT_INSIDER_TRADING_02
		SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,COUNT(distinct 1)  INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_INSIDER_TRADING_02 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL ---ST_ALERT_CHURNING_BOVESPA_02
		SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,COUNT(distinct 1)  CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_CHURNING_BOVESPA_02 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL --ST_ALERT_OMC_01
		SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,COUNT(distinct 1)  OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_OMC_01 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL --ST_ALERT_OMC_BMF_01
		SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,COUNT(distinct 1)  OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_OMC_BMF_01 INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE

        UNION ALL --ST_ALERT_OSCILACAO
		SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,COUNT(distinct 1)  OSCILACAO,0 OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_OSCILACAO INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE

		UNION ALL --ST_ALERT_OMG
		SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,COUNT(distinct 1)  OMG_BOVESPA,0 OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_OMG INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE

		UNION ALL --ST_ALERT_OMG_BMF
		SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,COUNT(distinct 1)  OMG_BMF, 0 VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_OMG_BMF INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE
		
		UNION ALL --ST_ALERT_EMISSOR_VINCULADO
		SELECT DISTINCT DATA,CD_CLIENTE,
		 0 MONEYPASS_CORRETORA,0 MONEYPASS_CORRETORA_BMF,0 MONEYPASS_BVSP_02,0 MONEYPASS_BMF_02,0 MEDIA_BMF_01,0 MEDIA_BOVESPA_01,0 TRANSFERENCIA_FINANCEIRA_01
		,0 TRANSFERENCIA_FINANCEIRA_02,0 PATRIMONIO_CUSTODIA,0 PATRIMONIO_NETTING,0 PATRIMONIO_MOVCC,0 PATRIMONIO_TRANSF_CUST,0 ATULIZACAO_CADASTRAL_01
		,0 PROCURADOR_01,0 MUDANCA_REPENTINA_01,0 RANKING_DAYTRADE_BVSP,0 RANKING_DAYTRADE_BMF,0 ATIVO_RESTRITO,0 INSIDER_TRADING_BOVESPA_02
		,0 CHURNING_02,0 OMC_01,0 OMC_BMF_01,0 OSCILACAO,0 OMG_BOVESPA,0  OMG_BMF, COUNT(distinct 1) VINCULADO_EMISSOR
        FROM(
        SELECT DISTINCT DATA,CD_CLIENTE
        FROM ST_ALERT_EMISSOR_VINCULADO INNER JOIN ST_PERIODO ON DATA = DT_PERIODO
        WHERE CD_ANO = '''+@CD_ANO+''' AND DS_MES = '''+@DS_MES+'''
        ) X
        GROUP BY DATA,CD_CLIENTE
) Y 
LEFT OUTER JOIN 
V_CLIENTE_TODOS T1 ON Y.CD_CLIENTE = T1.CD_CLIENTE
INNER JOIN ST_PERIODO DD ON DD.DT_PERIODO = Y.DATA
LEFT OUTER JOIN LISTAATENCAO E ON T1.NM_CLIENTE = E.NOME
OUTER APPLY (
  SELECT TOP (1) w.RISCO_FINAL
  FROM STG_WV_RISCO_FINAL w
  WHERE w.[Cód. do Cliente] = Y.CD_CLIENTE
    AND w.[Data] <= EOMONTH(DD.DT_PERIODO)
  ORDER BY TRY_CONVERT(date, w.[Data], 103) DESC
) rsel

LEFT JOIN STG_FRONTEIRA F ON F.[Cidade] = T1.NM_CIDADE AND F.[UF] = T1.SG_ESTADO
 
 
GROUP BY DD.CD_MES,DD.CD_ANO,
Y.CD_CLIENTE,CD_CPFCGC,T1.NM_CLIENTE,T1.DT_CRIACAO,T1.IN_POLITICO_EXP,
T1.IN_PESS_VINC,T1.TP_SITUAC, T1.IN_SITUAC,F.CIDADE
';
EXEC sys.sp_executesql @sql;
 
-- ================================================
-- Marca DT_FIRA para registros carregados (fallback)
-- ================================================
DECLARE @__dt_fira_now DATETIME = GETDATE();
IF COL_LENGTH(N'dbo.ST_RELATORIO_PAINEL_ALERTAS_CVM', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE [dbo].ST_RELATORIO_PAINEL_ALERTAS_CVM
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL;
END
--passo 3
--/***** limpa a tabela do banco para nao ficar sujeira ******/
DROP TABLE IF EXISTS ST_RELATORIO_PAINEL_ALERTAS_CVM_PADRAO