CREATE PROCEDURE [dbo].[PR_SWINGTRADE_BMF]  @INICIO SMALLDATETIME,@FIM SMALLDATETIME, @CD_CLIENTE VARCHAR(160),@QTDPORPAGINA INT,@PAGINA INT
--WITH ENCRYPTION
AS


--DECLARE @PAGINA        INT = 1;
--DECLARE @QTDPORPAGINA INT = 5
--DECLARE @INICIO SMALLDATETIME,@FIM SMALLDATETIME, @CD_CLIENTE  VARCHAR(160)
--SET @INICIO ='20171001'
--SET @FIM ='20171031'
--SET @CD_CLIENTE =''



SELECT  format(@INICIO,'d','pt-br') [DATA INÍCIO],
format(@fim,'d','pt-br') [DATA FIM],
ST_SWINGTRADE_BMF.CD_CLIENTE as [CÓD. CLIENTE], 
V.NM_CLIENTE [NOME DO CLIENTE],
SUM(QTD_SWINGTRADE) [QTD. SWINGTRADE] , 
SUM(CASE WHEN RESULTADO > 0 THEN 1 ELSE 0 END) ACERTO,
SUM(CASE WHEN RESULTADO < 0 THEN 1 ELSE 0 END) PERDA, 
SUM(CASE WHEN RESULTADO = 0 THEN 1 ELSE 0 END) EMPATE, 
FORMAT(ABS(SUM(RESULTADO)),'f','pt-br') [RESULTADO FINANCEIRO],
FORMAT(SUM(FINANCEIRO),'f','pt-br') [RESULTADO FINANCEIRO TOTAL]
FROM ST_SWINGTRADE_BMF 
left outer JOIN  V_CLIENTE_TODOS V
ON ST_SWINGTRADE_BMF.CD_CLIENTE =V.CD_CLIENTE
WHERE PREGAO >=@INICIO AND PREGAO <=@FIM
AND ST_SWINGTRADE_BMF.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN ST_SWINGTRADE_BMF.CD_CLIENTE ELSE @CD_CLIENTE END
GROUP BY ST_SWINGTRADE_BMF.CD_CLIENTE, V.NM_CLIENTE

ORDER BY 1
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;