CREATE PROCEDURE [dbo].[PR_CONTROLE_EMITENTE] @NOME_EMIT VARCHAR(160) ,@QTDPORPAGINA INT, @PAGINA INT
--WITH ENCRYPTION
AS

/******************************************************
CONTROLE DE EMITENTES, VERIFICA QTS CLIENTES TEM CADA 
EMITENTE E SE É O PRINCIPAL OU NAO
*******************************************************/

--DECLARE @NOME_EMIT VARCHAR(160) ,@QTDPORPAGINA INT, @PAGINA INT
--SET @NOME_EMIT=''
--SET @PAGINA = 1
--SET @QTDPORPAGINA = 10000000


SELECT DISTINCT dbo.formatar_cpf(X.CD_CPFCGC_EMIT) CD_CPFCGC_EMIT,  MAX(X.NM_EMIT_ORDEM) NM_EMIT_ORDEM,NM_CLIENTE,IN_PRINCIPAL
FROM (
	SELECT CD_CPFCGC_EMIT, LTRIM(RTRIM(MAX(NM_EMIT_ORDEM))) NM_EMIT_ORDEM,NM_CLIENTE,IN_PRINCIPAL
	FROM ST_DADOS_BASICOS_PF
	WHERE CD_CPFCGC_EMIT IS NOT NULL
	AND NM_EMIT_ORDEM  LIKE  (CASE WHEN ISNULL(@NOME_EMIT,'') = 'TODOS' THEN NM_EMIT_ORDEM ELSE '%'+@NOME_EMIT+'%' END)
	GROUP BY CD_CPFCGC_EMIT ,NM_CLIENTE,IN_PRINCIPAL
 
		UNION ALL

	SELECT CD_CPFCGC_EMIT,LTRIM(RTRIM(MAX(NM_EMIT_ORDEM)))  NM_EMIT_ORDEM,NM_CLIENTE,IN_PRINCIPAL
	FROM ST_DADOS_BASICOS_PJ
	WHERE CD_CPFCGC_EMIT IS NOT NULL
	AND NM_EMIT_ORDEM LIKE (CASE WHEN ISNULL(@NOME_EMIT,'') = 'TODOS' THEN NM_EMIT_ORDEM ELSE  '%'+@NOME_EMIT+'%' END)
	GROUP BY CD_CPFCGC_EMIT,NM_CLIENTE,IN_PRINCIPAL

		UNION ALL

	SELECT ISNULL(CD_CPFCGC_EMIT,0) as CD_CPFCGC_EMIT, LTRIM(RTRIM(MAX(NM_EMIT_ORDEM)))  NM_EMIT_ORDEM,NM_CLIENTE,IN_PRINCIPAL
	FROM ST_DADOS_BASICOS_PF
	WHERE CD_CPFCGC_EMIT IS NULL AND NM_EMIT_ORDEM IS NOT NULL
	AND NM_EMIT_ORDEM LIKE (CASE WHEN ISNULL(@NOME_EMIT,'') = 'TODOS' THEN NM_EMIT_ORDEM ELSE  '%'+@NOME_EMIT+'%' END)
	GROUP BY CD_CPFCGC_EMIT,NM_CLIENTE,IN_PRINCIPAL

		UNION ALL

	SELECT ISNULL(CD_CPFCGC_EMIT,0) as CD_CPFCGC_EMIT, LTRIM(RTRIM(MAX(NM_EMIT_ORDEM)))  NM_EMIT_ORDEM,NM_CLIENTE,IN_PRINCIPAL
	FROM ST_DADOS_BASICOS_PJ
	WHERE CD_CPFCGC_EMIT IS NULL AND NM_EMIT_ORDEM IS NOT NULL
	AND NM_EMIT_ORDEM LIKE (CASE WHEN ISNULL(@NOME_EMIT,'') = 'TODOS' THEN NM_EMIT_ORDEM ELSE  '%'+@NOME_EMIT+'%' END)
	GROUP BY CD_CPFCGC_EMIT,NM_CLIENTE,IN_PRINCIPAL

	 
	) X
WHERE CD_CPFCGC_EMIT > '0'
GROUP BY X.CD_CPFCGC_EMIT, X.NM_EMIT_ORDEM,NM_CLIENTE,IN_PRINCIPAL
 
ORDER BY 1		
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE  ISNULL(@QTDPORPAGINA,'') END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;