CREATE PROCEDURE [dbo].[PR_RESUMO_DIRETAS_BMF] @INICIO SMALLDATETIME, @FIM SMALLDATETIME, @CLIENTE INT,    
@INICIO2 SMALLDATETIME, @FIM2 SMALLDATETIME , @QTDPORPAGINA INT, @PAGINA INT   
WITH RECOMPILE  
AS    
    
--DECLARE @PAGINA        INT   
  
  
--DECLARE @QTDPORPAGINA INT    
--DECLARE @INICIO SMALLDATETIME, @FIM SMALLDATETIME, @CLIENTE INT,@INICIO2 SMALLDATETIME, @FIM2 SMALLDATETIME    
--SET @INICIO = '20240201'    
--SET @FIM = '20240228'    
--SET @CLIENTE = ''    
--SET @INICIO2 = '20240201'    
--SET @FIM2 = '20240228'    
    
    
DECLARE @CORRET FLOAT    
  
SET @CORRET = (SELECT SUM(QTD_DIRETAS_PONTA) QTD_DIRETAS     
    FROM ST_RESUMO_DIRETAS_BMF ST    
    WHERE DT_NEGOCIO>=@INICIO AND DT_NEGOCIO<=@FIM)    
    
  
;WITH #T1 AS (    
SELECT ST.CD_CLIENTE, SUM(QTD_DIRETAS_PONTA) QTD_DIRETAS    
 FROM ST_RESUMO_DIRETAS_BMF ST    
 WHERE DT_NEGOCIO >=@INICIO AND DT_NEGOCIO <= @FIM    
 AND ST.CD_CLIENTE = CASE WHEN ISNULL(@CLIENTE,'') ='' THEN ST.CD_CLIENTE ELSE CAST(@CLIENTE AS INT) END    
GROUP BY CD_CLIENTE    
),    
  
#TNEG AS (    
SELECT CD_CLIENTE,SUM(QT_NEGOCIO) QTD_NEGOCIOS   
FROM ST_BMF_NEGOCIOS    
WHERE DT_NEGOCIO >=@INICIO AND DT_NEGOCIO <=@FIM    
AND CD_CLIENTE = CASE WHEN ISNULL(@CLIENTE,'') ='' THEN CD_CLIENTE ELSE CAST(@CLIENTE AS INT) END    
GROUP BY CD_CLIENTE    
),  
  
#TNEGANT AS (    
SELECT CD_CLIENTE,SUM(QT_NEGOCIO) QTD_NEGOCIOS    
FROM ST_BMF_NEGOCIOS    
WHERE DT_NEGOCIO >=@INICIO2 AND DT_NEGOCIO <=@FIM2    
AND CD_CLIENTE = CASE WHEN ISNULL(@CLIENTE,'') ='' THEN CD_CLIENTE ELSE CAST(@CLIENTE AS INT) END    
GROUP BY CD_CLIENTE    
),    
  
  
#TDIRANT AS (    
SELECT ST.CD_CLIENTE, SUM(QTD_DIRETAS_PONTA) QTD_DIRETAS    
FROM ST_RESUMO_DIRETAS_BMF ST    
WHERE DT_NEGOCIO>=@INICIO2 AND DT_NEGOCIO<=@FIM2    
AND ST.CD_CLIENTE = CASE WHEN ISNULL(@CLIENTE,'') ='' THEN ST.CD_CLIENTE ELSE CAST(@CLIENTE AS INT) END    
GROUP BY ST.CD_CLIENTE    
),    
  
  
#TPONTA AS (    
SELECT CD_CLIENTE, SUM(QTD_DIRETAS_PONTA) QTD, CD_CLIENTE_PONTA    
FROM ST_RESUMO_DIRETAS_BMF    
WHERE DT_NEGOCIO>=@INICIO    
AND DT_NEGOCIO<=@FIM    
AND CD_CLIENTE = CASE WHEN ISNULL(@CLIENTE,'') ='' THEN CD_CLIENTE ELSE CAST(@CLIENTE AS INT) END    
GROUP BY CD_CLIENTE, CD_CLIENTE_PONTA    
),    
  
  
CTE AS   
(    
   SELECT *,    
         ROW_NUMBER() OVER (PARTITION BY CD_CLIENTE ORDER BY QTD DESC) AS RN    
   FROM #TPONTA    
),  
  
#T4 AS (  
SELECT CD_CLIENTE,    
QTD, CD_CLIENTE_PONTA    
FROM CTE     
WHERE RN = 1    
)  
  
--QUERY FINAL  
 SELECT  format(@INICIO,'d','pt-br') [DATA INÍCIO],  
format(@fim,'d','pt-br') [DATA FIM],    
#T1.CD_CLIENTE AS "COD. CLIENTE",  
SA.NM_CLIENTE AS "NOME DO CLIENTE",  
#T4.CD_CLIENTE_PONTA AS "COD. CLIENTE PONTA",     
SA2.NM_CLIENTE AS "NOME DO CLIENTE PONTA",  
  
FORMAT(SUM(ISNULL(#TNEG.QTD_NEGOCIOS,0)),'#,0','PT-BR') AS "QTD. NEGOCIOS",   
FORMAT(SUM(ISNULL(#T1.QTD_DIRETAS,0)),'#,0','PT-BR') AS "QTD. DIRETAS",    
FORMAT(CAST(SUM(#T1.QTD_DIRETAS)AS FLOAT)/CAST(SUM(#TNEG.QTD_NEGOCIOS) AS FLOAT),'P2') AS "PROPORÇÃO QTD. NÉGOCIOS",   
  
ISNULL(FORMAT(CAST(SUM(#T1.QTD_DIRETAS)AS FLOAT)/CAST(SUM(#TDIRANT.QTD_DIRETAS) AS FLOAT)-1,'P2'),0) AS "QTD DIRETAS / ANTERIOR",    
FORMAT(CAST(SUM(ISNULL(#T4.QTD,0)) AS FLOAT)/CAST(SUM(#T1.QTD_DIRETAS) AS FLOAT),'P2') "QTD. PONTA / QTD. DIRETAS",    
FORMAT(CAST(SUM(ISNULL(#T1.QTD_DIRETAS,0)) AS FLOAT) / @CORRET,'P2') AS "QTD. DIRETAS / CORRETORA",     
CASE WHEN SA.CD_CPFCGC = SA2.CD_CPFCGC THEN 'SIM' ELSE 'NÃO' END AS "MESMO CPF/CNPJ",    
'NÃO' AS "BROKER"  
  
FROM #T1   
INNER JOIN #TNEG    
ON #T1.CD_CLIENTE = #TNEG.CD_CLIENTE    
INNER JOIN #T4    
ON #T1.CD_CLIENTE = #T4.CD_CLIENTE    
INNER JOIN V_CLIENTE_TODOS SA    
ON #T1.CD_CLIENTE = SA.CD_CLIENTE    
INNER JOIN V_CLIENTE_TODOS SA2    
ON #T4.CD_CLIENTE_PONTA = SA2.CD_CLIENTE    
LEFT OUTER JOIN #TNEGANT    
ON #T1.CD_CLIENTE = #TNEGANT.CD_CLIENTE    
LEFT OUTER JOIN #TDIRANT    
ON #T1.CD_CLIENTE = #TDIRANT.CD_CLIENTE    
    
  
GROUP BY #T1.CD_CLIENTE, SA.NM_CLIENTE, SA2.NM_CLIENTE,    
#T4.CD_CLIENTE_PONTA, SA.CD_CPFCGC, SA2.CD_CPFCGC  
  
  
ORDER BY #T1.CD_CLIENTE  
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS  
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;