CREATE PROCEDURE [dbo].[PR_ALERTADETALHADOPATRIMONIOTRANSFCUSTODIA]
(
   @CD_ANO INT, @DS_MES VARCHAR(50), @CD_CLIENTE INT
)
--WITH ENCRYPTION
AS

--declare @CD_ANO INT, @DS_MES VARCHAR(50), @CD_CLIENTE INT
--set @cd_ano = '2025'
--set @DS_MES ='DEZEMBRO'

BEGIN

IF @DS_MES = '01' BEGIN SET @DS_MES = 'JANEIRO' END
ELSE IF @DS_MES = '02' BEGIN SET @DS_MES = 'FEVEREIRO' END
ELSE IF @DS_MES = '03' BEGIN SET @DS_MES = 'MARÇO' END
ELSE IF @DS_MES = '04' BEGIN SET @DS_MES = 'ABRIL' END
ELSE IF @DS_MES = '05' BEGIN SET @DS_MES = 'MAIO' END
ELSE IF @DS_MES = '06' BEGIN SET @DS_MES = 'JUNHO' END
ELSE IF @DS_MES = '07' BEGIN SET @DS_MES = 'JULHO' END
ELSE IF @DS_MES = '08' BEGIN SET @DS_MES = 'AGOSTO' END
ELSE IF @DS_MES = '09' BEGIN SET @DS_MES = 'SETEMBRO' END
ELSE IF @DS_MES = '10' BEGIN SET @DS_MES = 'OUTUBRO' END
ELSE IF @DS_MES = '11' BEGIN SET @DS_MES = 'NOVEMBRO' END
ELSE IF @DS_MES = '12' BEGIN SET @DS_MES = 'DEZEMBRO' END

SET @CD_ANO = CAST(@CD_ANO AS INT)
SET @CD_CLIENTE = CAST(@CD_CLIENTE AS INT)

IF OBJECT_ID('tempdb..#v_Cliente_todos') IS NOT NULL
    DROP TABLE #v_Cliente_todos;
select distinct CD_CLIENTE,NM_CLIENTE,TIPO,CD_CPFCGC
into #v_Cliente_todos
from v_cliente_Todos;

SELECT DISTINCT 
FORMAT(DATA,'d','pt-br')DATA
,A.CD_CLIENTE AS [CÓD. CLIENTE]
,NM_CLIENTE AS [NOME DO CLIENTE]
,TIPO AS [PF / PJ]
,CD_CPFCGC AS [CPF / CNPJ]
,FORMAT(TOTAL_MES,'f','pt-br') [TOTAL TRANSF.]
,FORMAT(PATRIMONIO,'f','pt-br') PATRIMONIO

FROM ST_ALERT_PATRIMONIO_TRANF_CUST A
INNER JOIN ST_PERIODO C  ON DATA = DT_PERIODO  
LEFT OUTER JOIN #V_CLIENTE_TODOS D ON A.CD_CLIENTE = D.CD_CLIENTE  
WHERE CD_ANO = @CD_ANO AND DS_MES = @DS_MES  AND A.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN A.CD_CLIENTE ELSE @CD_CLIENTE END

END