CREATE PROCEDURE [dbo].[ATUALIZARSCOREPROFISSAO] @SCORE INT, @RISCONEW VARCHAR(MAX),@TIPO VARCHAR(2),@PROFISSAO VARCHAR(MAX)
AS 

 
--DECLARE @SCORE INT, @RISCONEW VARCHAR(MAX),@TIPO VARCHAR(2),@PROFISSAO VARCHAR(MAX)
--SET @SCORE = 500
--SET @PROFISSAO = 'DEMAIS ATIVIDADES'
--SET @RISCONEW = 'BAIXO'
--SET @TIPO = 'PJ'



UPDATE ST_PROFISSAO_RISCO
SET PONTUACAO = @SCORE, RISCO = @RISCONEW
WHERE PROFISSAO = @PROFISSAO
AND TIPO = @TIPO