CREATE PROCEDURE [dbo].[PR_DAYTRADE_PAPEL_BMF] @INICIO SMALLDATETIME, @FIM SMALLDATETIME, @CD_CLIENTE VARCHAR(160),@CD_COMMOD VARCHAR(20),@CD_SERIE VARCHAR(20),@QTDPORPAGINA INT ,@PAGINA INT   
WITH RECOMPILE  
AS    
    
--DECLARE @PAGINA   INT 
--DECLARE @QTDPORPAGINA INT      
--DECLARE  @INICIO SMALLDATETIME, @FIM SMALLDATETIME, @CD_CLIENTE VARCHAR(160), @CD_COMMOD VARCHAR(20), @CD_SERIE VARCHAR(20)   
  
--SET @INICIO = '20240401'    
--SET @FIM = '20240429'    
--SET @CD_CLIENTE = ''    
--SET @CD_COMMOD =''   
--SET @CD_SERIE =''    
     
;WITH  #T1  AS (    
SELECT DT_PREGAO_COMPROU DT_PREGAO,     
CD_CLIENTE,CD_COMMOD, CD_SERIE, 
SUM(CAST(VL_FINANC AS FLOAT)) VL_FINAN    
   
FROM ST_DAYTRADE_RESUMO_ATIVO_BMF    
WHERE DT_PREGAO_COMPROU >= @INICIO AND DT_PREGAO_COMPROU <= @FIM    
AND CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'')='' THEN CD_CLIENTE ELSE ISNULL(@CD_CLIENTE,'') END    
GROUP BY DT_PREGAO_COMPROU, CD_CLIENTE, CD_COMMOD,CD_SERIE  
 ),   
    
    
    
  #T3  AS (    
SELECT CD_CLIENTE, CD_COMMOD,CD_SERIE,
SUM(CASE WHEN VL_FINAN >0 THEN 1 ELSE 0 END) VL_ACERTO,    
SUM(CASE WHEN VL_FINAN =0 THEN 1 ELSE 0 END) VL_EMPATE,    
SUM(CASE WHEN VL_FINAN <0 THEN 1 ELSE 0 END) VL_PERDAS,    
SUM(VL_FINAN) VL_FINAN   
FROM #T1    
GROUP BY CD_CLIENTE, CD_COMMOD,CD_SERIE ),   
    
    
    
    
#T2 AS (    
SELECT CD_CLIENTE, SUM(#T1.VL_FINAN ) ACERTO  FROM #T1    
GROUP BY CD_CLIENTE )   
    
    
SELECT    format(@INICIO,'d','pt-br') [DATA INÍCIO],  
format(@fim,'d','pt-br') [DATA FIM],  
T3.CD_CLIENTE as [CÓD. CLIENTE],     
V.NM_CLIENTE [NOME DO CLIENTE],    
T3.CD_COMMOD [COMMOD],    
ISNULL(T3.CD_SERIE,'')[SÉRIE],   
FORMAT(ISNULL(T3.VL_FINAN,0),'f','pt-br') [RESULTADO FINANCEIRO],    
FORMAT(ISNULL(T2.ACERTO,0),'f','pt-br') [RESULTADO FINANCEIRO TOTAL],  
T3.VL_ACERTO [ACERTO] ,      
T3.VL_EMPATE [EMPATE] ,      
T3.VL_PERDAS [PERDA] ,      
FORMAT((CAST(T3.VL_ACERTO AS FLOAT) / (CAST(T3.VL_ACERTO AS FLOAT) + CAST(T3.VL_EMPATE AS FLOAT) + CAST(T3.VL_PERDAS AS FLOAT))), 'P2') [PERC. ACERTO],    
FORMAT((CAST(T3.VL_PERDAS AS FLOAT) / NULLIF((CAST(T3.VL_ACERTO AS FLOAT) + CAST(T3.VL_EMPATE AS FLOAT) + CAST(T3.VL_PERDAs AS FLOAT)), 0)), 'P2') [PERC. PERDA]
   
    
--ISNULL(CAST(T3.VL_FINAN AS FLOAT)/CAST(T2.ACERTO AS FLOAT),0) PERC_ACERTO    
    
    
FROM #T2 T2
INNER JOIN #T3 T3 ON T2.CD_CLIENTE = T3.CD_CLIENTE 
INNER JOIN V_CLIENTE_TODOS V ON T2.CD_CLIENTE = V.CD_CLIENTE
WHERE       
T3.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') ='' THEN T3.CD_CLIENTE ELSE @CD_CLIENTE END    
AND  T3.CD_COMMOD = CASE WHEN ISNULL(@CD_COMMOD,'') ='' THEN T3.CD_COMMOD ELSE @CD_COMMOD END   
AND  T3.CD_SERIE = CASE WHEN ISNULL(@CD_SERIE,'') ='' THEN T3.CD_SERIE ELSE @CD_SERIE END   
ORDER BY 1   
  
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS  
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;