--USE [FIRA_DEV]
--GO

CREATE PROCEDURE [dbo].[PR_ALERTADETALHADORANKINGDAYTRADEBVSP]
(
   @CD_ANO INT, @DS_MES VARCHAR(50), @CD_CLIENTE INT
)
--WITH ENCRYPTION
AS
BEGIN

--DECLARE @CD_ANO INT = 2023, @DS_MES VARCHAR(50)= 'DEZEMBRO', @CD_CLIENTE INT

IF @DS_MES = '01' BEGIN SET @DS_MES = 'JANEIRO' END
ELSE IF @DS_MES = '02' BEGIN SET @DS_MES = 'FEVEREIRO' END
ELSE IF @DS_MES = '03' BEGIN SET @DS_MES = 'MARÇO' END
ELSE IF @DS_MES = '04' BEGIN SET @DS_MES = 'ABRIL' END
ELSE IF @DS_MES = '05' BEGIN SET @DS_MES = 'MAIO' END
ELSE IF @DS_MES = '06' BEGIN SET @DS_MES = 'JUNHO' END
ELSE IF @DS_MES = '07' BEGIN SET @DS_MES = 'JULHO' END
ELSE IF @DS_MES = '08' BEGIN SET @DS_MES = 'AGOSTO' END
ELSE IF @DS_MES = '09' BEGIN SET @DS_MES = 'SETEMBRO' END
ELSE IF @DS_MES = '10' BEGIN SET @DS_MES = 'OUTUBRO' END
ELSE IF @DS_MES = '11' BEGIN SET @DS_MES = 'NOVEMBRO' END
ELSE IF @DS_MES = '12' BEGIN SET @DS_MES = 'DEZEMBRO' END

SET @CD_ANO = CAST(@CD_ANO AS INT)
SET @CD_CLIENTE = CAST(@CD_CLIENTE AS INT)

    SELECT 
  DISTINCT 
		  FORMAT(DATA,'d','pt-br')														AS "DATA"				
		, CD_CLIENTE																	AS "CÓD. CLIENTE"
		, ATV_NEG_DT																	AS "ATIVOS NEGOCIADOS DAYTRADE"
		, ATV_TOT																		AS "TOTAL DE ATIVOS"
		, FORMAT(RSLT_FIN,'f','pt-br') 													AS "RESULTADO FINANCEIRO"
		, FORMAT(RSLT_FIN_ABS,'f','pt-br') 										        AS "RESULTADO ABSOLUTO"
		, FORMAT(MED_RSLT_FIN,'f','pt-br') 												AS "MÉDIA RESULTADO FINANCEIRO"
		, FORMAT(DES_RSLT_FIN,'f','pt-br') 												AS "DESVIO RESULTADO FINANCEIRO"
		, CONCAT(CONVERT(VARCHAR,CAST(IND_ACERTO * 100 AS NUMERIC(17,0))), '%')		    AS "ÍNDICE ACERTO"
		, CONCAT(CONVERT(VARCHAR,CAST(MED_IND_ACERTO * 100 AS NUMERIC(17,0))), '%')		AS "MÉDIA ÍNDICE ACERTO"
		, CONCAT(CONVERT(VARCHAR,CAST(DES_IND_ACERTO * 100 AS NUMERIC(17,0))), '%') 	AS "DESVIO ÍNDICE ACERTO"
		, CONCAT(CONVERT(VARCHAR,CAST(IND_ERRO * 100 AS NUMERIC(17,0))), '%')			AS "ÍNDICE ERRO"
		, CONCAT(CONVERT(VARCHAR,CAST(MED_IND_ERRO * 100 AS NUMERIC(17,0))), '%') 		AS "MÉDIA ÍNDICE ERRO"
		, CONCAT(CONVERT(VARCHAR,CAST(DES_IND_ERRO * 100 AS NUMERIC(17,0))), '%')  		AS "DESVIO ÍNDICE ERRO"
		, QTD_DT																	    AS "QTD. DAYTRADE"
		, QTD_DIAS_DT																    AS "QTD. DE DIAS DAYTRADE"
		, QTD_DIAS_OPE																    AS "QTD. DE DIAS OPERADOS"
		, CONCAT(CONVERT(VARCHAR,CAST(DIAS_PROP * 100 AS NUMERIC(17,2))), '%')			AS "PROPORÇÃO DE DIAS"
		, FORMAT(VOLUME_DT,'f','pt-br')													AS "VOLUME DAYTRADE"
		, CONCAT(CONVERT(VARCHAR,CAST(RENT_PROP * 100 AS NUMERIC(17,2))), '%')			AS "PROPORÇÃO DE RENTABILIDADE"
		, VOLUME_TOT																	AS "VOLUME TOTAL"
		,  CONCAT(CONVERT(VARCHAR,CAST(DT_PROP * 100 AS NUMERIC(17,2))), '%')			AS "PROPORÇÃO DAYTRADE"
		, CONTRA_IN																		AS "CONTRAPARTE INTERNA"
		, CONTRA_OUT																	AS "CONTRAPARTE EXTERNA"
		, DAYTRADISTA																	AS "DAYTRADISTA"
		, ALT_FQ																		AS "ALTA FREQUENCIA"

	  FROM ST_ALERT_RANKING_DAYTRADE_BVSP A
INNER JOIN ST_PERIODO C  ON DATA = DT_PERIODO  
	 WHERE CD_ANO = @CD_ANO AND DS_MES = @DS_MES  AND A.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN A.CD_CLIENTE ELSE @CD_CLIENTE END

END



--SELECT * 
--  FROM SP_HELP ST_ALERT_RANKING_DAYTRADE_BVSP

--SELECT * FROM ST_ALERT_RANKING_DAYTRADE_BMF