CREATE PROCEDURE [dbo].[PR_TRANFERENCIA] @INICIO SMALLDATETIME, @FIM SMALLDATETIME, @COD_CLI VARCHAR(160),@QTDPORPAGINA INT,@PAGINA INT  
AS  
  
  
--DECLARE @PAGINA        INT   
--DECLARE @QTDPORPAGINA INT   
--DECLARE @INICIO SMALLDATETIME, @FIM SMALLDATETIME,  @COD_CLI VARCHAR(160)   
--SET @INICIO = '20251201'  
--SET @FIM = '20251231'  
--SET @COD_CLI = ''   
  
  
   
---PATRIMONIO  
---busco o patrimonio do ultimo dia util do mes do alerta
drop table if exists #PATRIMONIO
SELECT XX.CD_CLIENTE, isnull(CAST(SUM(VAL_BENS) AS NUMERIC(38,2)),0) PATRIMONIO
INTO #PATRIMONIO
FROM ST_PATRIMONIO_LIQ  XX
WHERE DATA = (SELECT MAX(DATA) FROM ST_PATRIMONIO_LIQ YY 
				WHERE  (DATA) >= @INICIO
				AND  (DATA) <= @FIM
				and DATEPART(WEEKDAY, DATA) NOT IN (7,1)
				)
GROUP BY  XX.CD_CLIENTE
 
CREATE NONCLUSTERED INDEX T1         
ON [DBO].[#PATRIMONIO] ([CD_CLIENTE]) 
INCLUDE ([PATRIMONIO])    
  
;with #TPAPEL AS(  
SELECT DT_NEGOCIO,CD_PAPEL,CAST(MAX(A.VL_NEGOCIO)AS FLOAT)VL_NEGOCIO  
  
FROM ST_CORRETAGEM_ORDEM A (NOLOCK)  
WHERE DT_NEGOCIO >= @INICIO AND   DT_NEGOCIO <= @FIM  
GROUP BY DT_NEGOCIO,CD_PAPEL),  
  
#DIA AS (  
SELECT COD_CLI,DATA_MVTO,SUM(TOTAL_DIA)TOTAL_DIA  
FROM (   
 SELECT DISTINCT A.COD_CLI,DATA_MVTO, (SUM(A.QTDE_MVTO) * ISNULL(B.VL_NEGOCIO,0))  TOTAL_DIA  
 FROM ST_TRANSFERENCIA_CUST A (NOLOCK)  
 INNER JOIN #TPAPEL B ON A.COD_NEG = B.CD_PAPEL AND A.DATA_MVTO = B.DT_NEGOCIO  
 WHERE DATA_MVTO >=@INICIO  AND  DATA_MVTO <=  @FIM  
 AND A.COD_CLI = CASE WHEN ISNULL(@COD_CLI,'')='' THEN A.COD_CLI ELSE @COD_CLI END  
  
 AND NAT_OPE = 'C'   
    AND TIPO_MVTO = 'LC03'  
 AND COD_MVTO =  6   
 AND COD_USUA_CONP NOT IN (select MAX(cd_parametro) from ST_CLIENTE_PARAMETROS where DS_PARAMETRO = 'CD_CONTRAPARTE')  
 GROUP BY A.COD_CLI,DATA_MVTO,(B.VL_NEGOCIO)  
 ) X  
 GROUP BY COD_CLI,DATA_MVTO),  
   
    
  
#TOTAL AS (  
SELECT COD_CLI,ISNULL(SUM(TOTAL_MES),0) TOTAL_MES  
FROM(  
 SELECT DISTINCT A.COD_CLI,DATA_MVTO, SUM(A.QTDE_MVTO) * ISNULL(B.VL_NEGOCIO,0)  TOTAL_MES  
 FROM ST_TRANSFERENCIA_CUST A (NOLOCK)  
 INNER JOIN #TPAPEL B ON A.COD_NEG = B.CD_PAPEL AND A.DATA_MVTO = B.DT_NEGOCIO  
 WHERE DATA_MVTO >=@INICIO  AND  DATA_MVTO <=  @FIM  
 AND NAT_OPE = 'C'   
    AND TIPO_MVTO = 'LC03'  
 AND COD_MVTO =  6   
 AND COD_USUA_CONP NOT IN (select MAX(cd_parametro) from ST_CLIENTE_PARAMETROS where DS_PARAMETRO = 'CD_CONTRAPARTE')  
 GROUP BY A.COD_CLI,DATA_MVTO,(B.VL_NEGOCIO)  
)X  
GROUP BY COD_CLI)  
  
  
SELECT   
S.COD_CLI AS [COD. CLIENTE]  
,D.TP_SITUAC [SITUAÇÃO CAD. GERAL]  
,D.IN_SITUAC [SITUAÇÃO MOD. BOLSA],  
CONVERT(VARCHAR,S.DATA_MVTO,103)[DATA MOVIMENTO],  
COD_NEG AS [ATIVO],  
  
FORMAT(SUM(CAST(QTDE_MVTO AS FLOAT)),'#.#','PT-BR')[QTD.],  
  
DESC_HIST_MVTO [DESCRIÇÃO MOVIMENTO]  
,COD_USUA_CONP  
,COD_MVTO [COD. MOVIMENTO]  
,NAT_OPE [OPERAÇÃO]  
,TIPO_MVTO [TIPO MOVIMENTO]  
,COD_ISIN [COD. ISIN]  
,TIPO_MERC [MERCADO]  
,CC.NM_CORRET [NOME CONTRAPARTE],  
  
FORMAT(CAST(SS.VL_NEGOCIO AS FLOAT),'f','pt-br') [PREÇO MAXIMO] ,  
FORMAT(CAST((SUM(CAST(QTDE_MVTO AS FLOAT))*SS.VL_NEGOCIO)AS FLOAT ),'f','pt-br') [VALOR TRANSF.],  
  
D.NM_CLIENTE [NOME CLIENTE]  
,CD_ASSESSOR [COD. ASSESSOR]  
,NM_ASSESSOR [NOME ASSESSOR],  
  
FORMAT(ISNULL(PAT.PATRIMONIO,0),'f','pt-br') AS PATRIMONIO,  
  
COD_LOC AS [COD. CORRETORA],  
  
CASE WHEN COD_USUA_CONP IN (select MAX(cd_parametro) from ST_CLIENTE_PARAMETROS where DS_PARAMETRO = 'CD_CONTRAPARTE') THEN 'INTERNA' ELSE 'EXTERNA' END TRANSFERENCIA,  
CASE WHEN COD_USUA_CONP IN (select MAX(cd_parametro) from ST_CLIENTE_PARAMETROS where DS_PARAMETRO = 'CD_CONTRAPARTE') THEN ''   
     WHEN CAST((SUM(CAST(QTDE_MVTO AS FLOAT))*SS.VL_NEGOCIO)AS FLOAT ) > ISNULL(PAT.PATRIMONIO,0) THEN 'SIM' ELSE 'NÃO' END ALERTA_DIARIO,  
  
FORMAT(ISNULL(CASE WHEN COD_USUA_CONP IN (select MAX(cd_parametro) from ST_CLIENTE_PARAMETROS where DS_PARAMETRO = 'CD_CONTRAPARTE') THEN NULL ELSE ISNULL(DIA.TOTAL_DIA,0) END,0),'f','pt-br') [TOTAL DIA],  
  
FORMAT(ISNULL(CASE WHEN COD_USUA_CONP IN (select MAX(cd_parametro) from ST_CLIENTE_PARAMETROS where DS_PARAMETRO = 'CD_CONTRAPARTE') THEN NULL ELSE ISNULL(TOT.TOTAL_MES,0) END,0),'f','pt-br') [TOTAL MES],  
  
CASE WHEN COD_USUA_CONP IN (select MAX(cd_parametro) from ST_CLIENTE_PARAMETROS where DS_PARAMETRO = 'CD_CONTRAPARTE') THEN ''  
     WHEN ISNULL(TOT.TOTAL_MES,0) > ISNULL(PAT.PATRIMONIO,0) THEN 'SIM' ELSE 'NÃO' END [ALERTA MENSAL]  
   
FROM ST_TRANSFERENCIA_CUST S (NOLOCK)  
LEFT OUTER JOIN #TPAPEL SS ON S.COD_NEG = SS.CD_PAPEL AND S.DATA_MVTO = SS.DT_NEGOCIO  
LEFT OUTER JOIN V_CLIENTE_TODOS (NOLOCK) D ON S.COD_CLI = D.CD_CLIENTE  
LEFT OUTER JOIN ST_CORRETORA (NOLOCK) CC ON S.COD_USUA_CONP = CC.CD_CORRET   
LEFT OUTER JOIN #patrimonio PAT ON S.COD_CLI = PAT.CD_CLIENTE  
LEFT OUTER JOIN #TOTAL TOT ON S.COD_CLI = TOT.COD_CLI  
LEFT OUTER JOIN #DIA DIA ON S.COD_CLI = DIA.COD_CLI AND S.DATA_MVTO = DIA.DATA_MVTO  
WHERE  
-- NAT_OPE = 'C'  
--AND TIPO_MVTO = 'LC03'  
--AND COD_MVTO =  6   
    S.DATA_MVTO >= @INICIO   
AND S.DATA_MVTO <= @FIM  
AND S.COD_CLI = CASE WHEN ISNULL(@COD_CLI,'')='' THEN S.COD_CLI ELSE @COD_CLI END  
     
GROUP BY S.COD_CLI,D.TP_SITUAC,D.IN_SITUAC,  
CONVERT(VARCHAR,S.DATA_MVTO,103),COD_NEG,ISNULL(PAT.PATRIMONIO,0),ISNULL(DIA.TOTAL_DIA,0),  
DESC_HIST_MVTO,COD_USUA_CONP,COD_MVTO,NAT_OPE,TIPO_MVTO,COD_ISIN,TIPO_MERC,CC.NM_CORRET,  
CAST(SS.VL_NEGOCIO AS FLOAT),D.NM_CLIENTE,CD_ASSESSOR,NM_ASSESSOR, COD_LOC,TOT.TOTAL_MES  
  
ORDER BY S.COD_CLI, CONVERT(VARCHAR,S.DATA_MVTO,103)  
  
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS  
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;