CREATE PROCEDURE [dbo].[PR_ALERTADETALHADOCHURNINGBOVESPA02]
(
   @CD_ANO INT, @DS_MES VARCHAR(50), @CD_CLIENTE INT
)
--WITH ENCRYPTION
AS
BEGIN

--DECLARE @CD_ANO INT, @DS_MES VARCHAR(50), @CD_CLIENTE INT
--SET @CD_ANO = 2024
--SET @DS_MES = 'ABRIL'
--SET @CD_CLIENTE = ''

--SELECT 'A' AS DATA, 'B' AS CD_CLIENTE, 'C' AS QTD, 'D' AS QTD_MED, 'E' AS QTD_DES, 'F' AS CORRETAGEM

IF @DS_MES = '01' BEGIN SET @DS_MES = 'JANEIRO' END
ELSE IF @DS_MES = '02' BEGIN SET @DS_MES = 'FEVEREIRO' END
ELSE IF @DS_MES = '03' BEGIN SET @DS_MES = 'MARÇO' END
ELSE IF @DS_MES = '04' BEGIN SET @DS_MES = 'ABRIL' END
ELSE IF @DS_MES = '05' BEGIN SET @DS_MES = 'MAIO' END
ELSE IF @DS_MES = '06' BEGIN SET @DS_MES = 'JUNHO' END
ELSE IF @DS_MES = '07' BEGIN SET @DS_MES = 'JULHO' END
ELSE IF @DS_MES = '08' BEGIN SET @DS_MES = 'AGOSTO' END
ELSE IF @DS_MES = '09' BEGIN SET @DS_MES = 'SETEMBRO' END
ELSE IF @DS_MES = '10' BEGIN SET @DS_MES = 'OUTUBRO' END
ELSE IF @DS_MES = '11' BEGIN SET @DS_MES = 'NOVEMBRO' END
ELSE IF @DS_MES = '12' BEGIN SET @DS_MES = 'DEZEMBRO' END

SET @CD_ANO = CAST(@CD_ANO AS INT)
SET @CD_CLIENTE = CAST(@CD_CLIENTE AS INT)

  SELECT 
DISTINCT 
           FORMAT(DATA,'d','pt-br')DATA
         , A.CD_CLIENTE AS [CÓD. CLIENTE]
		 , B.CD_CPFCGC AS [CPF / CNPJ]
		 , NM_cLIENTE AS [NOME DO CLIENTE]
         , FORMAT(QTD,'#,0','PT-BR') AS QUANTIDADE
         , FORMAT(CORRETAGEM,'f','pt-br') AS CORRETAGEM
         , (TURNOVER_RATIO) AS [TURNOVER RATIO]
         , (COST_EQUITY_RATIO) AS [COST EQUITY RATIO]
         , ALERTADO_TR AS [ALERTADO TR]
         , ALERTADO_CE AS [ALERTADO CE]
		 , FORMAT(VOLUME_COMPRA,'f','pt-br') AS [VOLUME DE COMPRA]
		 , QTD_DIA_UTEIS_MES AS [QUANTIDADE DE DIAS ÚTEIS NO MÊS]
         , QTD_DIA_UTEIS_SEMESTRE  AS [QUANTIDADE DE DIAS ÚTEIS NO SEMESTRE]
         , FORMAT(MED_CARTEIRA,'f','pt-br') AS [MÉDIA DA CARTEIRA]
		 , ATIVO AS [ATIVOS]
		 , FORMAT(RESULTADO,'f','pt-br') as [RESULTADO]
	  FROM ST_ALERT_CHURNING_BOVESPA_02 A
INNER JOIN ST_PERIODO C  ON DATA = DT_PERIODO
LEFT OUTER JOIN  (SELECT DISTINCT CD_cLIENTE,CD_CPFCGC FROM V_CLIENTE_TODOS) B ON A.CD_CLIENTE = B.CD_CLIENTE
	 WHERE CD_ANO = @CD_ANO 
	   AND DS_MES = @DS_MES  
	   AND A.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN A.CD_CLIENTE ELSE @CD_CLIENTE END

END

/*
SELECT DISTINCT 
FORMAT(DATA,'d','pt-br')DATA
,CD_CLIENTE AS [CÓD. CLIENTE]
,FORMAT(QTD,'#,0','PT-BR') AS QUANTIDADE
,FORMAT(CORRETAGEM,'f','pt-br') AS CORRETAGEM
,FORMAT(TURNOVER_RATIO,'f','pt-br') AS [TURNOVER RATIO]
,FORMAT(COST_EQUITY_RATIO,'f','pt-br') AS [COST EQUITY RATIO]
,FORMAT(ALERTADO_TR,'P2') AS [ALERTADO TR]
,FORMAT(ALERTADO_CE,'P2') AS [ALERTADO CE]


FROM ST_ALERT_CHURNING_BOVESPA_02 A
INNER JOIN ST_PERIODO C  ON DATA = DT_PERIODO */