CREATE PROCEDURE [dbo].[PR_DISPERCAO_PRECOS_BMF] @INICIO SMALLDATETIME, @CD_CLIENTE VARCHAR(10),@QTDPORPAGINA INT	, @PAGINA INT
WITH RECOMPILE
AS		
		
-- DECLARE    @PAGINA       INT = 1;	 	
		
--DECLARE @INICIO SMALLDATETIME,@QTDPORPAGINA INT	=''		
--DECLARE @CD_CLIENTE INT		
--SET @INICIO = '20251201'		
--SET @CD_CLIENTE =''		
	

drop table if exists #v_cliente_todos
select distinct cd_cliente, nm_cliente 
into #v_cliente_todos
from ST_DADOS_BASICOS_PF
union all
select distinct cd_cliente, nm_cliente from ST_DADOS_BASICOS_PJ

--;WITH #OPER_BROKER_BMF AS  (
drop table if exists #OPER_BROKER_BMF
SELECT DT_NEGOCIO, F.CD_CLIENTE, CD_COMMOD, CD_SERIE, CAST(SUM(F.PR_NEGOCIO) AS NUMERIC(19,2)) PRECO, F.NR_NEGOCIO, CD_NATOPE
into #OPER_BROKER_BMF
FROM ST_BMF_NEGOCIOS_NC F (NOLOCK)
WHERE F.DT_NEGOCIO = @INICIO		
AND TP_NEGOCIO IN ('NORMAL','DAY TRADE','DAYTRADE')
AND F.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN F.CD_CLIENTE ELSE @CD_CLIENTE END		
GROUP BY DT_NEGOCIO, F.CD_CLIENTE, CD_COMMOD, CD_SERIE, F.NR_NEGOCIO,CD_NATOPE		
--),		


--#OPER_MEDIA_BMF AS (		
drop table if exists #OPER_MEDIA_BMF
SELECT CD_COMMOD, CD_SERIE, 
CAST(AVG(PRECO) AS NUMERIC(19,2)) MEDIA_PRECO
into #OPER_MEDIA_BMF
FROM #OPER_BROKER_BMF		
GROUP BY CD_COMMOD, CD_SERIE	
--)


--QUERY FINAL			
SELECT 
FORMAT(DT_NEGOCIO,'d','pt-br') AS "DATA",
Y.CD_CLIENTE AS "CÓD. CLIENTE", 
NM_CLIENTE AS "NOME DO CLIENTE",
Y.CD_COMMOD AS "COMMODITIES", 
Y.CD_SERIE AS "SÉRIE",
NR_NEGOCIO AS "NR NEGOCIO",
CD_NATOPE AS "NATUREZA", 
FORMAT(ISNULL(PRECO,0),'f','pt-br')AS "PREÇO",
FORMAT(ISNULL(X.MEDIA_PRECO,0),'f','pt-br') AS "PREÇO MÉDIO",

CASE WHEN CD_NATOPE= 'C' AND PRECO > MEDIA_PRECO THEN 'NEGATIVO: COMPRA MAIOR QUE A MEDIA'		
	WHEN CD_NATOPE= 'C' AND PRECO < MEDIA_PRECO THEN 'POSITIVO: COMPRA MENOR QUE A MEDIA'		
	WHEN CD_NATOPE= 'V' AND PRECO > MEDIA_PRECO THEN 'POSITIVO: VENDA MAIOR QUE A MEDIA'		
	WHEN CD_NATOPE= 'V' AND PRECO < MEDIA_PRECO THEN 'NEGATIVO: VENDA MENOR QUE A MEDIA' ELSE 'EMPATE' END "RESULTADO" 		

FROM #OPER_BROKER_BMF Y 
INNER JOIN #OPER_MEDIA_BMF X ON Y.CD_COMMOD = X.CD_COMMOD AND Y.CD_SERIE = X.CD_SERIE
LEFT OUTER JOIN #V_CLIENTE_TODOS (NOLOCK) Z ON Y.CD_CLIENTE = Z.CD_CLIENTE

WHERE (PRECO > MEDIA_PRECO OR PRECO < MEDIA_PRECO)		

ORDER BY Y.CD_COMMOD, Y.CD_SERIE, CD_NATOPE, Y.CD_CLIENTE		
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;