CREATE PROCEDURE [dbo].[FIRA_PR_CARGA_ST_DADOS_BASICOS_PJ] 
--WITH ENCRYPTION
AS

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ST_DADOS_BASICOS_PJ_PADRAO]') AND type in (N'U'))
CREATE TABLE [dbo].[ST_DADOS_BASICOS_PJ_PADRAO](
	[NM_CLIENTE] [varchar](160) NOT NULL,
	[CD_CLIENTE] [int] NOT NULL,
	[CD_CPFCGC] [varchar](20) NOT NULL,
	[DT_CRIACAO] [datetime2](7) NOT NULL,
	[DT_ATUALIZ] [datetime2](7) NULL,
	[NM_LOGRADOURO] [nvarchar](max) NULL,
	[NR_PREDIO] [varchar](5) NULL,
	[NM_COMP_ENDE] [varchar](110) NULL,
	[NM_BAIRRO] [varchar](118) NULL,
	[NM_CIDADE] [varchar](128) NULL,
	[SG_ESTADO] [varchar](4) NULL,
	[SG_PAIS] [varchar](10) NULL,
	[NM_E_MAIL] [varchar](255) NULL,
	[IN_PESS_VINC] [char](1) NULL,
	[DT_NASC_FUND] [datetime2](7) NULL,
	[DS_TIPO_CLIENTE] [varchar](40) NULL,
	[NR_TELEFONE] [nvarchar](400) NULL,
	[EMAIL_SEQ] [nvarchar](384) NULL,
	[ENDE_SEQ] [nvarchar](384) NULL,
	[NM_EMIT_ORDEM] [varchar](130) NULL,
	[CD_CPFCGC_EMIT] [varchar](20) NULL,
	[CD_DOC_IDENT_EMIT] [varchar](16) NULL,
	[EMISSOR_PRINCIPAL] [char](1) NULL,
	[CD_SISTEMA] [varchar](4) NULL,
	[CD_ASSESSOR] [numeric](15, 0) NULL,
	[CD_CON_DEP] [int] NULL,
	[DS_CON_DEP] [varchar](50) NULL,
	[IN_CONTA_INV] [char](1) NULL,
	[IN_SITUAC] [char](1) NULL,
	[cd_Cep] [varchar](15) NULL,
	[CD_DDD_TEL] [int] NULL,
	[TP_SITUAC] [varchar](15) NULL,
	[nm_grupo] [varchar](30) NULL,
	[CD_DDD_FAX] [int] NULL,
	[NR_DDD_FAX] [int] NULL,
	[NM_ASSESSOR] [varchar](100) NULL,
	[VL_OPERACIONAL1] [float] NULL,
	[VL_OPERACIONAL2] [float] NULL,
	[VL_OPERACIONAL3] [float] NULL,
	[VL_CAPACIDADE_FIN] [float] NULL,
	[DT_ATUALIZ_SALARIO] [smalldatetime] NULL,
	[TP_CLIENTE] [int] NULL,
	[NM_RESU_ASSES] [varchar](100) NULL,
	[in_politico_exp] [char](1) NULL,
	[IN_PROCUR] [varchar](2) NULL,
	[IN_PRINCIPAL] [varchar](2) NULL,
	[IND_CAD_SIMP] [varchar](2) NULL,
	[DT_ULT_OPER] [smalldatetime] NULL,
	[DT_VALIDADE] [datetime] NULL,
	[NM_COMPL_NOME] [nvarchar](24) NULL,
	[CPFCNPJ] [varchar](20) NULL,
	[CD_CNPJ_EMPRESA] [varchar](20) NULL,
	[IN_QUALIFICADO] VARCHAR(4) NULL,
	[DT_FIRA] DATETIME NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
 
/***************************************************
inicio da comparação entre a tabela
da base padrao fira origem x tabela cliente destino
*****************************************************/
EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo',, @src_table='ST_DADOS_BASICOS_PJ_PADRAO',
  @schema_name='dbo', @base_table='ST_DADOS_BASICOS_PJ',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1;


-- 2) TRUNCATE pode ficar estático
TRUNCATE TABLE ST_DADOS_BASICOS_PJ
	
/**********************************************************************
3) INSERT em SQL dinâmico (compila após o ALTER) INSERT com lista 
explícita de colunas Isso evita dor de cabeça caso a tabela destino 
tenha colunas a mais, ordem diferente, identity, etc.
**********************************************************************/
DECLARE @sql nvarchar(max) = N'
INSERT INTO ST_DADOS_BASICOS_PJ
(
	 NM_CLIENTE,CD_CLIENTE,CD_CPFCGC,DT_CRIACAO,DT_ATUALIZ,NM_LOGRADOURO,NR_PREDIO
	,NM_COMP_ENDE,NM_BAIRRO,NM_CIDADE,SG_ESTADO,SG_PAIS,NM_E_MAIL,IN_PESS_VINC
	,DT_NASC_FUND,DS_TIPO_CLIENTE,NR_TELEFONE,EMAIL_SEQ,ENDE_SEQ,NM_EMIT_ORDEM
	,CD_CPFCGC_EMIT,CD_DOC_IDENT_EMIT,EMISSOR_PRINCIPAL,CD_SISTEMA,CD_ASSESSOR
	,CD_CON_DEP,DS_CON_DEP,IN_CONTA_INV,IN_SITUAC,cd_Cep,CD_DDD_TEL,TP_SITUAC
	,nm_grupo,CD_DDD_FAX,NR_DDD_FAX,NM_ASSESSOR,VL_OPERACIONAL1,VL_OPERACIONAL2
	,VL_OPERACIONAL3,VL_CAPACIDADE_FIN,DT_ATUALIZ_SALARIO,TP_CLIENTE,NM_RESU_ASSES
	,in_politico_exp,IN_PROCUR,IN_PRINCIPAL,IND_CAD_SIMP,DT_ULT_OPER,DT_VALIDADE
	,NM_COMPL_NOME,CPFCNPJ,IN_QUALIFICADO,CD_CNPJ_EMPRESA
)
SELECT  
	B.NM_CLIENTE,
	A.CD_CLIENTE,
	A.CD_CPFCGC,
	A.DT_CRIACAO,
	B.DT_ATUALIZ,
	C.NM_LOGRADOURO,
	C.NR_PREDIO,
	C.NM_COMP_ENDE,
	C.NM_BAIRRO,
	C.NM_CIDADE,
	C.SG_ESTADO, 
	C.SG_PAIS,
	ISNULL(M.NM_E_MAIL, C.NM_E_MAIL) NM_E_MAIL,
	B.IN_PESS_VINC,
	A.DT_NASC_FUND,
	E.DS_TIPO_CLIENTE,
	C.NR_TELEFONE,0,
	NULL ENDE_SEQ,
	H.NM_EMIT_ORDEM,
	H.CD_CPFCGC_EMIT,
	H.CD_DOC_IDENT_EMIT,
	H.IN_PRINCIPAL AS EMISSOR_PRINCIPAL,
	H.CD_SISTEMA,
	A.CD_ASSESSOR,
	I.CD_CON_DEP,
	I.DS_CON_DEP, 
	A.IN_CONTA_INV, 
	A.IN_SITUAC,
	CAST(C.CD_CEP AS VARCHAR)+''-''+CAST(C.CD_CEP_EXT AS VARCHAR) AS CD_CEP,
	C.CD_DDD_TEL,
	CASE 
		WHEN B.TP_SITUAC = ''AT'' THEN ''ATIVO''
		WHEN B.TP_SITUAC = ''IN'' THEN ''INATIVO''
		WHEN B.TP_SITUAC = ''BL'' THEN ''BLOQUEADO''
		WHEN B.TP_SITUAC = ''EN'' THEN ''ENCERRADO''
		ELSE ''OUTROS'' END,
	J.NM_GRUPO,
	NULL CD_DDD_FAX, 
	NULL NR_FAX, 
	K.NM_ASSESSOR, 
	B.VL_OPERACIONAL1, 
	B.VL_OPERACIONAL2, 
	B.VL_OPERACIONAL3,
	B.VL_CAPACIDADE_FIN,
	B.DT_VL_OPERACIONAL, 
	E.TP_CLIENTE,
	K.NM_RESU_ASSES,
	B.IN_POLITICO_EXP,
	A.IND_CAD_SIMP,
	H.IN_PRINCIPAL,
	IN_PROCUR,
	DT_ULT_OPER,
	CASE 
		WHEN D.DT_VALIDADE < CONVERT(VARCHAR,''17530101'',103) THEN CONVERT(VARCHAR,''99991231'',103)
		ELSE D.DT_VALIDADE 
	END AS DT_VALIDADE,
	 NM_COMPL_NOME,
	null,
	IN_QUALIFICADO,
	NULL AS CD_CNPJ_EMPRESA


FROM TSCCLIBOL A
INNER JOIN TSCCLIGER B
	ON A.CD_CPFCGC = B.CD_CPFCGC
	AND A.DT_NASC_FUND = B.DT_NASC_FUND
	AND A.CD_CON_DEP = B.CD_CON_DEP
	
LEFT OUTER JOIN TSCENDE C
	ON  A.CD_CPFCGC =C.CD_CPFCGC
	AND A.DT_NASC_FUND = C.DT_NASC_FUND
	AND A.CD_CON_DEP = C.CD_CON_DEP
	
LEFT OUTER JOIN TSCDOCS D  	
	ON A.CD_CPFCGC = D.CD_CPFCGC  	
	AND A.DT_NASC_FUND = D.DT_NASC_FUND  	
	AND A.CD_CON_DEP = D.CD_CON_DEP 
	
LEFT OUTER JOIN TSCTIPCLI E
	ON B.TP_CLIENTE = E.TP_CLIENTE
	
LEFT OUTER JOIN TSCEMITORDEM H
	ON  B.CD_CPFCGC = H.CD_CPFCGC
	AND B.DT_NASC_FUND = H.DT_NASC_FUND
	AND B.CD_CON_DEP = H.CD_CON_DEP
	
LEFT OUTER JOIN TSCCONDEP I
	ON  A.CD_CON_DEP = I.CD_CON_DEP
	
LEFT OUTER JOIN TSCCLIGRUPO J
	ON B.CD_GRUPO = J.CD_GRUPO
	
LEFT OUTER JOIN TSCASSES K
	ON A.CD_ASSESSOR = K.CD_ASSESSOR

LEFT OUTER JOIN TSCEMAIL M
	ON A.CD_CPFCGC = M.CD_CPFCGC
	AND A.DT_NASC_FUND = M.DT_NASC_FUND

 

WHERE 
	B.TP_PESSOA = ''J''




INSERT INTO ST_DADOS_BASICOS_PJ
(
	 NM_CLIENTE,CD_CLIENTE,CD_CPFCGC,DT_CRIACAO,DT_ATUALIZ,NM_LOGRADOURO,NR_PREDIO
	,NM_COMP_ENDE,NM_BAIRRO,NM_CIDADE,SG_ESTADO,SG_PAIS,NM_E_MAIL,IN_PESS_VINC
	,DT_NASC_FUND,DS_TIPO_CLIENTE,NR_TELEFONE,EMAIL_SEQ,ENDE_SEQ,NM_EMIT_ORDEM
	,CD_CPFCGC_EMIT,CD_DOC_IDENT_EMIT,EMISSOR_PRINCIPAL,CD_SISTEMA,CD_ASSESSOR
	,CD_CON_DEP,DS_CON_DEP,IN_CONTA_INV,IN_SITUAC,cd_Cep,CD_DDD_TEL,TP_SITUAC
	,nm_grupo,CD_DDD_FAX,NR_DDD_FAX,NM_ASSESSOR,VL_OPERACIONAL1,VL_OPERACIONAL2
	,VL_OPERACIONAL3,VL_CAPACIDADE_FIN,DT_ATUALIZ_SALARIO,TP_CLIENTE,NM_RESU_ASSES
	,in_politico_exp,IN_PROCUR,IN_PRINCIPAL,IND_CAD_SIMP,DT_ULT_OPER,DT_VALIDADE
	,NM_COMPL_NOME,CPFCNPJ,IN_QUALIFICADO,CD_CNPJ_EMPRESA
)
SELECT DISTINCT 
	B.NM_CLIENTE,
	A.CD_CLIENTE,
	A.CD_CPFCGC,
	A.DT_CRIACAO,
	B.DT_ATUALIZ,
	C.NM_LOGRADOURO,
	C.NR_PREDIO,
	C.NM_COMP_ENDE,
	C.NM_BAIRRO,
	C.NM_CIDADE,
	C.SG_ESTADO, 
	C.SG_PAIS,
	ISNULL(M.NM_E_MAIL, C.NM_E_MAIL) NM_E_MAIL,
	B.IN_PESS_VINC,
	A.DT_NASC_FUND,
	E.DS_TIPO_CLIENTE,
	C.NR_TELEFONE,0,
	NULL ENDE_SEQ,
	H.NM_EMIT_ORDEM,
	H.CD_CPFCGC_EMIT,
	H.CD_DOC_IDENT_EMIT,
	H.IN_PRINCIPAL AS EMISSOR_PRINCIPAL,
	H.CD_SISTEMA,
	B.CD_ASSESSOR,
	I.CD_CON_DEP,
	I.DS_CON_DEP, 
	NULL AS IN_CONTA_INV, 
	NULL AS IN_SITUAC,
	CAST(C.CD_CEP AS VARCHAR)+''-''+CAST(C.CD_CEP_EXT AS VARCHAR) AS CD_CEP,
	C.CD_DDD_TEL,
	CASE 
		WHEN B.TP_SITUAC = ''AT'' THEN ''ATIVO''
		WHEN B.TP_SITUAC = ''IN'' THEN ''INATIVO''
		WHEN B.TP_SITUAC = ''BL'' THEN ''BLOQUEADO''
		WHEN B.TP_SITUAC = ''EN'' THEN ''ENCERRADO''
		ELSE ''OUTROS'' END,
	J.NM_GRUPO,
	NULL CD_DDD_FAX, 
	NULL NR_FAX, 
	K.NM_ASSESSOR, 
	B.VL_OPERACIONAL1, 
	B.VL_OPERACIONAL2, 
	B.VL_OPERACIONAL3,
	B.VL_CAPACIDADE_FIN,
	B.DT_VL_OPERACIONAL, 
	E.TP_CLIENTE,
	K.NM_RESU_ASSES,
	B.IN_POLITICO_EXP,
	NULL AS IND_CAD_SIMP,
	H.IN_PRINCIPAL,
	IN_PROCUR,
	NULL AS DT_ULT_OPER,
	CASE 
		WHEN D.DT_VALIDADE < CONVERT(VARCHAR,''17530101'',103) THEN CONVERT(VARCHAR,''99991231'',103)
		ELSE D.DT_VALIDADE 
	END AS DT_VALIDADE,
	null NM_COMPL_NOME,
	 null,
	 NULL,
	 NULL

FROM TSCCLICC A
INNER JOIN TSCCLIGER B
	ON A.CD_CPFCGC = B.CD_CPFCGC
	AND A.DT_NASC_FUND = B.DT_NASC_FUND
	AND A.CD_CON_DEP = B.CD_CON_DEP
	
LEFT OUTER JOIN TSCENDE C
	ON  A.CD_CPFCGC =C.CD_CPFCGC
	AND A.DT_NASC_FUND = C.DT_NASC_FUND
	AND A.CD_CON_DEP = C.CD_CON_DEP
	
LEFT OUTER JOIN TSCDOCS D  	
	ON A.CD_CPFCGC = D.CD_CPFCGC  	
	AND A.DT_NASC_FUND = D.DT_NASC_FUND  	
	AND A.CD_CON_DEP = D.CD_CON_DEP 
	
LEFT OUTER JOIN TSCTIPCLI E
	ON B.TP_CLIENTE = E.TP_CLIENTE
	
LEFT OUTER JOIN TSCEMITORDEM H
	ON  B.CD_CPFCGC = H.CD_CPFCGC
	AND B.DT_NASC_FUND = H.DT_NASC_FUND
	AND B.CD_CON_DEP = H.CD_CON_DEP
	
LEFT OUTER JOIN TSCCONDEP I
	ON  A.CD_CON_DEP = I.CD_CON_DEP
	
LEFT OUTER JOIN TSCCLIGRUPO J
	ON B.CD_GRUPO = J.CD_GRUPO
	
LEFT OUTER JOIN TSCASSES K
	ON B.CD_ASSESSOR = K.CD_ASSESSOR

LEFT OUTER JOIN TSCEMAIL M
	ON A.CD_CPFCGC = M.CD_CPFCGC
	AND A.DT_NASC_FUND = M.DT_NASC_FUND

 
WHERE 
	B.TP_PESSOA = ''J''
AND A.CD_CLIENTE NOT IN (SELECT DISTINCT CD_CLIENTE FROM ST_DADOS_BASICOS_PJ)
	
	
	update st_dados_basicos_pj
	set cpfcnpj =  DBO.FORMATAR_CNPJ(CD_CPFCGC)

	 DROP TABLE IF EXISTS #Q
	 SELECT CD_CLIENTE INTO #Q  FROM ST_DADOS_BASICOS_PJ
	 WHERE IN_QUALIFICADO IS NULL

	 DROP TABLE IF EXISTS #V
	 SELECT A.CD_CLIENTE,IN_QUALIFICADO INTO #V FROM ST_V_TBOMOVCL A
	 JOIN #Q B ON A.CD_CLIENTE=B.CD_CLIENTE
	 
	 UPDATE A
	 SET A.IN_QUALIFICADO = B.IN_QUALIFICADO
	 FROM ST_DADOS_BASICOS_PJ A JOIN #V B ON A.CD_CLIENTE=B.CD_CLIENTE

';
EXEC sys.sp_executesql @sql;
/******* fim do processo de carga **********/

-- ================================================
-- Marca DT_FIRA para registros carregados (fallback)
-- ================================================
DECLARE @__dt_fira_now DATETIME = GETDATE();
IF COL_LENGTH(N'dbo.ST_DADOS_BASICOS_PJ', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE [dbo].[ST_DADOS_BASICOS_PJ]
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL;
END

--passo 3
/***** limpa a tabela do banco para nao ficar sujeira ******/
DROP TABLE IF EXISTS ST_DADOS_BASICOS_PJ_PADRAO