CREATE PROCEDURE [dbo].[PR_INSIDER_TRADING_02]  @CD_ANOMES INT,@CD_CLIENTE int,@CD_PAPEL VARCHAR(20),  @QTDPORPAGINA  INT ,@PAGINA INT 

AS  
 
   --DECLARE @CD_PAPEL VARCHAR(20) ,
   --@CD_CLIENTE int ,
   --@CD_ANOMES INT,
   --@ALERTA CHAR(1) ,
   --@QTDPORPAGINA  INT ,
   --@PAGINA INT   

   --set @CD_ANOMES = '202310' 

  
    SELECT B.DS_ANOMES             AS [ANO/MÊS]  
   , CD_CLIENTE             AS [CÓD. CLIENTE]  
   , CD_PAPEL                    AS [ATIVO]  
   , convert(varchar,DT_FATO,103)            AS [DATA FATO RELEVANTE]  
   , FATO_RELEVANTE            AS [FATO RELEVANTE]  
   , FORMAT(ISNULL(PRECO_MEDIO_COMPRA_PRE,0),'f','pt-br')    AS [PRECO MÉD COMPRA PRÉ]  
   , FORMAT(ISNULL(PRECO_MEDIO_VENDA_PRE,0),'f','pt-br')     AS [PRECO MÉD VENDA PRÉ]  
   , FORMAT(ISNULL(PRECO_MEDIO_COMPRA_POS,0),'f','pt-br')    AS [PRECO MÉD COMPRA POS]  
   , FORMAT(ISNULL(PRECO_MEDIO_VENDA_POS,0),'f','pt-br')     AS [PRECO MÉD VENDA POS]  
   , FORMAT(ISNULL(QTDE_VALORIZOU,0),'f','pt-br')        AS [QTDE. VALORIZOU]  
   , FORMAT(ISNULL(QTDE_DESVALORIZOU,0),'f','pt-br')       AS [QTDE. DESVALORIZOU]  
   , FORMAT(ISNULL(RESULTADO,0),'f','pt-br')         AS [RESULTADO]  
   , FORMAT(ISNULL(AVG_INTERDAY_POS,0),'f','pt-br')    AS [MÉD INTERDAY POS]  
   , FORMAT(ISNULL(AVG_INTRADAY_POS,0),'f','pt-br')    AS [MÉD INTRADAY POS]  
            , CASE WHEN ALERTA ='S' THEN 'SIM' ELSE  'NÃO' END    AS ALERTADO  
  
   FROM ST_INSIDER_TRADING A  
    LEFT JOIN ST_PERIODO B ON A.DATA = B.DT_PERIODO  
        WHERE B.CD_ANOMES  = @CD_ANOMES   
         AND A.CD_PAPEL   = CASE WHEN ISNULL(@CD_PAPEL,'') = '' THEN A.CD_PAPEL ELSE @CD_PAPEL END   
         AND A.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,0) = 0 THEN A.CD_CLIENTE ELSE @CD_CLIENTE END        
  
ORDER BY 2 , 3   
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;