CREATE PROCEDURE [dbo].[PR_ALERTADETALHADOMONEYPASSBOVESPA02]
(
   @CD_ANO INT, @DS_MES VARCHAR(50), @CD_CLIENTE INT
)
--WITH ENCRYPTION
AS
BEGIN

IF @DS_MES = '01' BEGIN SET @DS_MES = 'JANEIRO' END
ELSE IF @DS_MES = '02' BEGIN SET @DS_MES = 'FEVEREIRO' END
ELSE IF @DS_MES = '03' BEGIN SET @DS_MES = 'MARÇO' END
ELSE IF @DS_MES = '04' BEGIN SET @DS_MES = 'ABRIL' END
ELSE IF @DS_MES = '05' BEGIN SET @DS_MES = 'MAIO' END
ELSE IF @DS_MES = '06' BEGIN SET @DS_MES = 'JUNHO' END
ELSE IF @DS_MES = '07' BEGIN SET @DS_MES = 'JULHO' END
ELSE IF @DS_MES = '08' BEGIN SET @DS_MES = 'AGOSTO' END
ELSE IF @DS_MES = '09' BEGIN SET @DS_MES = 'SETEMBRO' END
ELSE IF @DS_MES = '10' BEGIN SET @DS_MES = 'OUTUBRO' END
ELSE IF @DS_MES = '11' BEGIN SET @DS_MES = 'NOVEMBRO' END
ELSE IF @DS_MES = '12' BEGIN SET @DS_MES = 'DEZEMBRO' END

SET @CD_ANO = CAST(@CD_ANO AS INT)
SET @CD_CLIENTE = CAST(@CD_CLIENTE AS INT)

SELECT DISTINCT 

FORMAT(DATA,'d','pt-br')DATA
,CD_CLIENTE AS [CÓD. CLIENTE]
,CD_CONTRAPARTE AS [CÓD. CONTRAPARTE]
,NR_NEGOCIOS AS [NR. NEGÓCIOS]
,PAPEIS AS [PAPEIS]
,QTD_TOTAL AS [QTD. TOTAL]
,FORMAT(RESULTADO,'f','pt-br') RESULTADO
,FORMAT(RESULTADO_MEDIA_6M,'f','pt-br') [MÉDIA RESULTADO 6M]
,FORMAT(RESULTADO_DESVIO_6M,'f','pt-br') [DESVIO RESULTADO 6M]

,FORMAT(INTENCIONALIDADE,'f','pt-br') INTENCIONALIDADE
,FORMAT(INTENCIONALIDADE_MEDIA_6M,'f','pt-br') [MÉDIA INTENCIONALIDADE 6M]
,FORMAT(INTENCIONALIDADE_DESVIO_6M,'f','pt-br') [DESVIO INTENCIONALIDADE 6M]

,FORMAT(CONCENTRACAO,'f','pt-br') CONCENTRACAO
,FORMAT(CONCENTRACAO_MEDIA_6M,'f','pt-br') [MÉDIA CONCENTRAÇÃO 6M]
,FORMAT(CONCENTRACAO_DESVIO_6M,'f','pt-br') [DESVIO CONCENTRAÇÃO 6M]

--,FORMAT(ASSERTIVIDADE,'f','pt-br') ASSERTIVIDADE
--,FORMAT(MEDIA_ASSERTIVIDADE,'f','pt-br') [MEDIA ASSERTIVIDADE]
--,FORMAT(DESVIO_ASSERTIVIDADE,'f','pt-br') [DESVIO ASSERTIVIDADE]

,FORMAT(IND_ACERTO,'f','pt-br') [IND. DE ACERTO]
,FORMAT(IND_ACERTO_MEDIO_6M,'f','pt-br') [MÉDIA IND. ACERTO 6M]
,FORMAT(IND_ERRO,'f','pt-br') [IND. ERRO]
,FORMAT(IND_ERRO_6M,'f','pt-br') [MÉDIA IND. ERRO 6M]

FROM ST_ALERT_MONEYPASS_02 A
INNER JOIN ST_PERIODO C  ON DATA = DT_PERIODO  
--LEFT OUTER JOIN V_CLIENTE_TODOS D ON A.CD_CLIENTE = D.CD_CLIENTE  
WHERE CD_ANO = @CD_ANO AND DS_MES = @DS_MES  AND A.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN A.CD_CLIENTE ELSE @CD_CLIENTE END
 
END