CREATE PROCEDURE [dbo].[PR_MEDIA_OPERACOES_ATIVO] @ANOMES INT, @CD_CLIENTE INT,@CD_PAPEL VARCHAR(150), @QTDPORPAGINA INT,@PAGINA       INT	
WITH RECOMPILE 
AS

		
--DECLARE @PAGINA        INT;
--DECLARE @QTDPORPAGINA INT 
--DECLARE @ANOMES INT
--DECLARE @CD_CLIENTE INT	

--SET @ANOMES =202302
--SET @CD_CLIENTE=''	

DECLARE @ANOMES_INI SMALLDATETIME
DECLARE @ANOMES_FIM SMALLDATETIME

SET @ANOMES_INI = (SELECT TOP 1 EOMONTH(DT_PERIODO,-7) FROM ST_PERIODO WHERE CD_ANOMES = @ANOMES)
SET @ANOMES_FIM = (SELECT TOP 1 EOMONTH(DT_PERIODO,-1) FROM ST_PERIODO WHERE CD_ANOMES = @ANOMES)

       				
		
--------VOL MES ATUAL------------	
;WITH #T1  AS(
SELECT 		
CD_ANOMES,		
CD_CLIENTE,
CD_PAPEL,
SUM(ISNULL(VL_TOTNEG,0)) VOL_MES_ATUAL,
SUM(ISNULL(QT_MULTIPLICADOR,0))QTD_MES
FROM 		
ST_CORRETAGEM_ORDEM F,		
ST_PERIODO X 		
WHERE 		 	
F.DT_NEGOCIO = X.DT_PERIODO AND		
X.CD_ANOMES = @ANOMES AND		
CD_CLIENTE= CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN CD_CLIENTE ELSE CAST(@CD_CLIENTE AS INT) END		
 GROUP BY X.CD_ANOMES,CD_CLIENTE,CD_PAPEL 
),		
		
			
--------------MEDIA E DESVIO 6 MESES-----------------
#T4 AS (
SELECT 
CD_CLIENTE,
CD_PAPEL,
AVG(VOL_MES_ATUAL)VOL_MED_6_MESES,
STDEV(VOL_MES_ATUAL)VOL_DESV_6_MESES,
AVG(TOTAL) QTD_MED_6MESES,
STDEV(TOTAL)QTD_DESV_6MESES
FROM (
	SELECT 		
	X.CD_ANOMES,	
	CD_CLIENTE,
	CD_PAPEL,
	SUM(ISNULL(VL_TOTNEG,0)) VOL_MES_ATUAL,
	SUM(ISNULL(QT_MULTIPLICADOR,0)) TOTAL
	FROM 		
	ST_CORRETAGEM_ORDEM F,		
	ST_PERIODO X 		
	WHERE 		 	
	F.DT_NEGOCIO = X.DT_PERIODO AND		
	X.DT_PERIODO > @ANOMES_INI AND
	X.DT_PERIODO <= @ANOMES_FIM AND
	CD_CLIENTE= CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN CD_CLIENTE ELSE CAST(@CD_CLIENTE AS INT) END		
	GROUP BY X.CD_ANOMES,CD_CLIENTE,CD_PAPEL
	)X	
GROUP BY CD_CLIENTE,CD_PAPEL) 
		
 
 	

--------------SOMA TUDO--------------		
SELECT 		
A.CD_ANOMES AS [ANO MÊS],		
A.CD_CLIENTE AS [CÓD. CLIENTE],		
NM.NM_CLIENTE AS [NOME DO CLIENTE],
A.CD_PAPEL AS [ATIVO],
FORMAT(ISNULL(A.QTD_MES,0),'#.#','PT-BR') [QTD. NEG. MÊS],
FORMAT(ISNULL(A.VOL_MES_ATUAL,0),'f','pt-br') [VOLUME DO MÊS],	
FORMAT(ISNULL(D. VOL_MED_6_MESES,0),'f','pt-br') AS [MÉD. VOLUME 6M]  ,
FORMAT(ISNULL(D.VOL_DESV_6_MESES,0),'f','pt-br') AS [DESV. VOLUME 6M],
FORMAT(ISNULL(ISNULL(A.VOL_MES_ATUAL,0) / NULLIF(D.VOL_MED_6_MESES,0),0),'P2') [PERC. VOLUME DO MÊS],
FORMAT(ISNULL(D.QTD_MED_6MESES,0),'f','pt-br') [MÉD. NEG. 6M],	
FORMAT(ISNULL(D.QTD_DESV_6MESES,0),'f','pt-br') [DESVIO NEG. 6M],	
FORMAT(ISNULL(ISNULL(CAST(A.QTD_MES AS FLOAT),0)/NULLIF(CAST(D.QTD_MED_6MESES AS FLOAT),0),0),'P2') [PERC. QTD. NEG. MÊS],
		
CASE WHEN 	ISNULL(A.VOL_MES_ATUAL,0) >  D.VOL_MED_6_MESES + (ISNULL(D.VOL_DESV_6_MESES,0)*3) THEN 'SIM' ELSE 'NÃO' END [CAI ALERTA]
FROM #T1 A 		
LEFT OUTER JOIN #T4 D ON A.CD_CLIENTE = D.CD_CLIENTE AND A.CD_PAPEL = D.CD_PAPEL		
LEFT OUTER JOIN (SELECT DISTINCT CD_CLIENTE,NM_CLIENTE FROM V_CLIENTE_TODOS) NM	ON A.CD_CLIENTE = NM.CD_CLIENTE
		
		
WHERE 		
    A.CD_ANOMES =  (CASE WHEN ISNULL(@ANOMES,'') = '' THEN A.CD_ANOMES ELSE CONVERT(INT,@ANOMES) END)		
AND A.CD_CLIENTE = (CASE WHEN ISNULL(@CD_CLIENTE,'')='' THEN A.CD_CLIENTE ELSE CONVERT(INT,@CD_CLIENTE) END)		

ORDER BY 1

OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;