CREATE PROCEDURE [dbo].[PR_CONTROLE_VINCULADOS] @INICIO SMALLDATETIME , @FIM SMALLDATETIME ,@CD_CLIENTE VARCHAR(160)  , @QTDPORPAGINA INT, @PAGINA INT 
--WITH ENCRYPTION
AS 



--DECLARE @QTDPORPAGINA INT ,        @PAGINA       INT;
--DECLARE @INICIO SMALLDATETIME , @FIM SMALLDATETIME   ,@CD_CLIENTE VARCHAR(160) 
--SET @INICIO ='20230202'
--SET @FIM='20230228'
--SET @CD_CLIENTE =''


 
 
 SELECT DISTINCT  
	   A.CD_CLIENTE_COMPRA
      ,ISNULL(CAST(A.NM_CLIENTE_COMPRA AS VARCHAR),'-')NM_CLIENTE_COMPRA
      ,CASE WHEN A.VINC_COMPRA = 'S' THEN 'SIM' ELSE 'NÃO' END VINC_COMPRA
      , CD_CLIENTE_BRO_COMPRA
      ,ISNULL(CAST(A.CD_CLIENTE_VENDA AS VARCHAR),'-')CD_CLIENTE_VENDA
      ,ISNULL(CAST(A.NM_CLIENTE_VENDA AS VARCHAR),'-')NM_CLIENTE_VENDA
      , CD_CLIENTE_BRO_VENDA
      ,CASE WHEN A.VINC_VENDA ='S' THEN 'SIM' ELSE 'NÃO' END VINC_VENDA
      ,CONVERT(VARCHAR(10),A.DT_PERIODO,103) DT_PERIODO
      ,A.SISTEMA_COMPRA
      ,A.SISTEMA_VENDA
      ,A.NR_NEGOCIO
      ,FORMAT(CASE WHEN A.QT_NEGOCIO_COMPRA > A.QT_NEGOCIO_VENDA THEN A.QT_NEGOCIO_VENDA ELSE A.QT_NEGOCIO_COMPRA END,'#,0','PT-BR') QT_NEGOCIO --QT_NEGOCIO_COMPRA
 --   ,FORMAT(A.QT_NEGOCIO_VENDA,'#,0','PT-BR')QT_NEGOCIO_VENDA
      ,A.CD_PAPEL
      ,A.HH_COMPRA HORARIO
--    ,A.HH_VENDA
      ,FORMAT(CAST(A.VL_TOTNEG_COMPRA AS FLOAT),'f','pt-br') VL_TOTNEG --VL_TOTNEG_COMPRA
--    ,FORMAT(CAST(A.VL_TOTNEG_VENDA  AS FLOAT),'f','pt-br')VL_TOTNEG_VENDA
      ,FORMAT(CAST(A.VL_NEGOCIO_COMPRA  AS FLOAT),'f','pt-br') PRECO --VL_NEGOCIO_COMPRA
  --  ,FORMAT(CAST(A.VL_NEGOCIO_VENDA  AS FLOAT),'f','pt-br')VL_NEGOCIO_VENDA
      ,ISNULL(CAST(A.CD_ASSESSOR_COMPRA AS VARCHAR),'-') CD_ASSESSOR_COMPRA
      ,ISNULL(A.DS_ASSESSOR_COMPRA,'-') DS_ASSESSOR_COMPRA
      ,ISNULL(CAST(A.CD_ASSESSOR_VENDA AS VARCHAR),'-')CD_ASSESSOR_VENDA
      ,ISNULL(A.DS_ASSESSOR_VENDA,'-') DS_ASSESSOR_VENDA
             
      FROM ST_CONTROLE_VINCULADOS A 
	  LEFT OUTER JOIN V_CLIENTE_TODOS B  ON A.CD_CLIENTE_VENDA = B.CD_CLIENTE 
	  LEFT OUTER JOIN V_CLIENTE_TODOS C  ON A.CD_CLIENTE_COMPRA = C.CD_CLIENTE
     
	 WHERE 
	 A.DT_PERIODO >=@INICIO 
     AND A.DT_PERIODO <=@FIM
	 AND A.CD_CLIENTE_COMPRA = CASE WHEN ISNULL(@CD_CLIENTE,'')='' THEN A.CD_CLIENTE_COMPRA ELSE @CD_CLIENTE END 
	   

ORDER BY 1	
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;