CREATE PROCEDURE [dbo].[PR_CONTROLE_VINCULADOS_BMF]		
		
(		
  @INICIO SMALLDATETIME, @FIM SMALLDATETIME,		
  @CD_CLIENTE VARCHAR(10),
  @QTDPORPAGINA INT,@PAGINA INT
)		--WITH ENCRYPTION
AS		

--DECLARE @QTDPORPAGINA INT ,        @PAGINA       INT ;
	
--DECLARE @INICIO SMALLDATETIME, @FIM SMALLDATETIME,  @CD_CLIENTE VARCHAR(10)		
--SET @INICIO ='20230202'		
--SET @FIM ='20230228'		
--SET @CD_CLIENTE=''		
		
		
		
SELECT DISTINCT		
CONVERT(VARCHAR(20),A.DT_NEGOCIO,103) DATA,		
A.CD_CLIENTE_COMPRA "COD DO CLIENTE DA COMPRA", 		
A.NM_CLIENTE_COMPRA "NOME DO CLIENTE DA COMPRA",		
A.CD_CLIENTE_VENDA "COD DO CLIENTE DA VENDA", 		
A.NM_CLIENTE_VENDA "NOME DO CLIENTE DA VENDA",		
A.NR_NEGOCIO "NÃºMERO DO NEGOCIO", 		
FORMAT(QT_NEGOCIO_COMPRA,'#,0','PT-BR') "QUANTIDADE DO NEGOCIO",		
CD_COMMOD COMMOD, 		
CD_SERIE SERIE,		
HH_COMPRA HORA, 		
FORMAT(VL_TOTNEG_COMPRA,'f','pt-br') VALOR, 		
FORMAT(VL_NEGOCIO_COMPRA,'f','pt-br') "PRECO",		
CD_ASSESSOR_COMPRA "COD DO ASSESSOR DA COMPRA", 		
DS_ASSESSOR_COMPRA "NOME DO ASSESSOR DA COMPRA",		
CD_ASSESSOR_VENDA "COD DO ASSESSOR DA VENDA", 		
DS_ASSESSOR_VENDA "NOME DO ASSESSOR DA VENDA",		
SISTEMA_COMPRA "SISTEMA DA COMPRA", 		
USUARIO_COMPRA "USUARIO DA COMPRA", 		
SISTEMA_VENDA "SISTEMA DA VENDA",		
USUARIO_VENDA "USUARIO DA VENDA", 		
ISNULL(IN_DAYTRADE_COMPRA,'N') "COMPRA FOI DAYTRADE",		
ISNULL(IN_DAYTRADE_VENDA,'N') "VENDA FOI DAYTRADE",		
FORMAT(ISNULL(CAST(B.VL_DISPONIVEL AS NUMERIC(15,2)),0),'f','pt-br') "SALDO_CC CLIENTE COMPRA",		
FORMAT(ISNULL(CAST(C.VL_DISPONIVEL AS NUMERIC(15,2)),0),'f','pt-br') "SALDO_CC CLIENTE VENDA",  		
--CASE WHEN ISNULL(B.SALDO_CC,0) < 0 THEN 'SIM' ELSE 'NÃO' END "CLIENTE COMPRA DORMIU NEGATIVO",		
--CASE WHEN ISNULL(C.SALDO_CC,0) < 0 THEN 'SIM' ELSE 'NÃO' END "CLIENTE VENDA DORMIU NEGATIVO", 		
CD_NATOPE, 		
VINC_VENDA		
		
FROM 		
ST_CONTROLE_VINCULADOS_BMF A 		
LEFT OUTER JOIN ST_SALDO B		
ON A.CD_CLIENTE_COMPRA = B.CD_CLIENTE 		
AND A.DT_NEGOCIO = B.[DATA]		
LEFT OUTER JOIN ST_SALDO C		
ON A.CD_CLIENTE_VENDA = C.CD_CLIENTE 		
AND A.DT_NEGOCIO = C.[DATA]		
		
WHERE DT_NEGOCIO >= @INICIO		
AND DT_NEGOCIO <= @FIM		
AND A.CD_CLIENTE_COMPRA = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN A.CD_CLIENTE_COMPRA ELSE CAST(@CD_CLIENTE AS INT) END		
		
		
ORDER BY 1


OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;