CREATE PROCEDURE [dbo].[PR_OMG_BMF] (
    @INICIO       SMALLDATETIME,
    @FIM          SMALLDATETIME,
    @CD_CLIENTE   VARCHAR(160),
    @QTDPORPAGINA INT,
    @PAGINA       INT
)
--WITH ENCRYPTION
AS

--DECLARE @INICIO SMALLDATETIME , @FIM SMALLDATETIME, @CD_CLIENTE INT , @PAGINA       INT     ,@QTDPORPAGINA INT
--set @inicio='20251201'
--set @fim='20251231'
--SET @CD_CLIENTE = ''
 
DROP TABLE IF EXISTS #DADOS_BASICOS;
SELECT DISTINCT ST_DADOS_BASICOS_PF.CD_CPFCGC
       ,CD_CLIENTE
       ,NM_CLIENTE
       ,CASE WHEN(SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('|AVENIDA','AC','AH.','AV','AV.','AV:','AVENIDA','AVENIDA:','AVN')) OR
                 (SUBSTRING(NM_LOGRADOURO,1,CHARINDEX('.',NM_LOGRADOURO,1)) in ('|AVENIDA','AC','AH.','AV','AV.','AV:','AVENIDA','AVENIDA:','AVN')) THEN 'AV ' +SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             WHEN SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('AL','AL.','ALAMEDA','ALM','ALMEDA') THEN 'AL' +SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             WHEN SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('DODOVIA','ROD','ROD.','ROD.BR','ROD.MT','RODOVIA') THEN 'ROD'+SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             WHEN SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('ROD''EST','ESTM','ESTR','ESTR.','ESTRADA','ETRADA') THEN 'EST'+SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             WHEN SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('RUA','RUA:') THEN 'R' +SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             WHEN SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('TRAVESSA') THEN 'T' +SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             ELSE SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1))+''+SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
       END NM_LOGRADOURO
       ,NR_PREDIO,NM_COMP_ENDE,NM_BAIRRO,NM_CIDADE,SG_ESTADO,SG_PAIS,CD_CEP
       ,CD_DDD_TEL,REPLACE(NR_TELEFONE,' ','') NR_TELEFONE
       ,NM_E_MAIL,NM_PAI,NM_MAE,NM_CONJUGE,DT_NASC_FUND,DT_CRIACAO
       ,1 TIPO
  INTO #DADOS_BASICOS
  FROM ST_DADOS_BASICOS_PF
 WHERE IN_SITUAC ='A'
 
UNION ALL
SELECT DISTINCT ST_DADOS_BASICOS_PJ.CD_CPFCGC
       ,CD_CLIENTE
       ,NM_CLIENTE
       ,CASE WHEN(SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('|AVENIDA','AC','AH.','AV','AV.','AV:','AVENIDA','AVENIDA:','AVN')) OR
                 (SUBSTRING(NM_LOGRADOURO,1,CHARINDEX('.',NM_LOGRADOURO,1)) in ('|AVENIDA','AC','AH.','AV','AV.','AV:','AVENIDA','AVENIDA:','AVN')) THEN 'AV ' +SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             WHEN SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('AL','AL.','ALAMEDA','ALM','ALMEDA') THEN 'AL' +SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             WHEN SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('DODOVIA','ROD','ROD.','ROD.BR','ROD.MT','RODOVIA') THEN 'ROD'+SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             WHEN SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('ROD''EST','ESTM','ESTR','ESTR.','ESTRADA','ETRADA') THEN 'EST'+SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             WHEN SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('RUA','RUA:') THEN 'R' +SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             WHEN SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1)) in ('TRAVESSA') THEN 'T' +SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
             ELSE SUBSTRING(NM_LOGRADOURO,1,CHARINDEX(' ',NM_LOGRADOURO,1))+''+SUBSTRING(NM_LOGRADOURO,CHARINDEX(' ',NM_LOGRADOURO,1),LEN(NM_LOGRADOURO))
       END NM_LOGRADOURO
       ,NR_PREDIO,NM_COMP_ENDE,NM_BAIRRO,NM_CIDADE,SG_ESTADO,SG_PAIS,CD_CEP
       ,CD_DDD_TEL,REPLACE(NR_TELEFONE,' ','') NR_TELEFONE
       ,NM_E_MAIL,NULL,NULL,NULL,DT_NASC_FUND,DT_CRIACAO
       ,0 TIPO
  FROM ST_DADOS_BASICOS_PJ
 WHERE IN_SITUAC ='A';
 
DROP TABLE IF EXISTS #PF;
SELECT DISTINCT A.CD_CLIENTE, A.NM_CLIENTE, A.NM_EMPRESA, B.CD_CPFCGC
       , UPPER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(A.NM_EMPRESA, ' ', ''),
                CHAR(9), ''),CHAR(10), ''),CHAR(13), ''),'.', ''),',', ''),';', ''),':', ''),'!', ''),'?', ''),'"', '')
                ,'''', ''),'(', ''),')', ''),'[', ''),']', ''),'{', ''),'}', ''),'/', ''),'\', ''),'|', ''),'@', ''),'#', ''),
                '$', ''),'%', ''),'&', ''),'*', ''),'-', ''),'_', ''),'=', ''),'+', ''),'á','a'),'à','a'),'ã','a'),'â','a'),
                'ä','a'),'é','e'),'è','e'),'ê','e'),'ë','e'),'í','i'),'ì','i'),'î','i'),'ï','i'),'ó','o'),'ò','o'),'õ','o'),
                'ô','o'),'ö','o'),'ú','u'),'ù','u'),'û','u'),'ü','u'),'ç','c'))  AS NM_EMPRESA_LIMPO,
         'PF' TIPO_CLIENTE
  INTO #PF
  FROM ST_DADOS_FINANCEIROS_PF a JOIN ST_DADOS_BASICOS_PF B ON A.CD_CLIENTE = B.CD_CLIENTE
 WHERE NM_EMPRESA <> '-';
 
DROP TABLE IF EXISTS #PJ;
SELECT DISTINCT A.CD_CLIENTE, A.NM_CLIENTE, A.NM_EMPRESA, B.CD_CPFCGC
       , UPPER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(A.NM_CLIENTE, ' ', ''),
                CHAR(9), ''),CHAR(10), ''),CHAR(13), ''),'.', ''),',', ''),';', ''),':', ''),'!', ''),'?', ''),'"', '')
                ,'''', ''),'(', ''),')', ''),'[', ''),']', ''),'{', ''),'}', ''),'/', ''),'\', ''),'|', ''),'@', ''),'#', ''),
                '$', ''),'%', ''),'&', ''),'*', ''),'-', ''),'_', ''),'=', ''),'+', ''),'á','a'),'à','a'),'ã','a'),'â','a'),
                'ä','a'),'é','e'),'è','e'),'ê','e'),'ë','e'),'í','i'),'ì','i'),'î','i'),'ï','i'),'ó','o'),'ò','o'),'õ','o'),
                'ô','o'),'ö','o'),'ú','u'),'ù','u'),'û','u'),'ü','u'),'ç','c'))  AS NM_EMPRESA_LIMPO,
         'PJ' TIPO_CLIENTE
  INTO #PJ
  FROM ST_DADOS_FINANCEIROS_PJ a JOIN ST_DADOS_BASICOS_PJ B ON A.CD_CLIENTE = B.CD_CLIENTE;
 
DROP TABLE IF EXISTS #VINCULO;
-- ENDEREÇO
SELECT DISTINCT D1.CD_CLIENTE AS CD_CLIENTE_BUSC, D1.CD_CPFCGC AS CD_CPFCGC_BUSC,
       D2.CD_CLIENTE AS CD_CLIENTE_ENC, D2.CD_CPFCGC AS CD_CPFCGC_ENC, 'ENDEREÇO' AS TIPO_VINCULO
  INTO #VINCULO
  FROM #DADOS_BASICOS D1
  JOIN #DADOS_BASICOS D2
    ON D1.NM_LOGRADOURO = D2.NM_LOGRADOURO AND D1.NR_PREDIO = D2.NR_PREDIO
   AND D1.NM_BAIRRO = D2.NM_BAIRRO AND D1.NM_CIDADE = D2.NM_CIDADE
   AND D1.SG_ESTADO = D2.SG_ESTADO AND D1.SG_PAIS = D2.SG_PAIS AND D1.CD_CEP = D2.CD_CEP
 WHERE D1.CD_CPFCGC <> D2.CD_CPFCGC
   AND D1.NM_LOGRADOURO IS NOT NULL AND D1.NR_PREDIO IS NOT NULL AND D1.NM_BAIRRO IS NOT NULL
   AND D1.NM_CIDADE IS NOT NULL AND D1.SG_ESTADO IS NOT NULL AND D1.SG_PAIS IS NOT NULL
   AND D1.CD_CEP <> ' ' AND D1.NM_LOGRADOURO <> ' ' AND D1.NR_PREDIO <> ' '
   AND D1.NM_BAIRRO <> ' ' AND D1.NM_CIDADE <> ' ' AND D1.SG_ESTADO <> ' '
   AND D1.SG_PAIS <> ' ' AND D1.CD_CEP <> ' '
UNION ALL
-- TELEFONE
SELECT DISTINCT D1.CD_CLIENTE AS CD_CLIENTE_BUSC, D1.CD_CPFCGC AS CD_CPFCGC_BUSC,
       D2.CD_CLIENTE AS CD_CLIENTE_ENC, D2.CD_CPFCGC AS CD_CPFCGC_ENC, 'TELEFONE' AS TIPO_VINCULO
  FROM #DADOS_BASICOS D1
  JOIN #DADOS_BASICOS D2 ON D1.CD_DDD_TEL = D2.CD_DDD_TEL AND D1.NR_TELEFONE = D2.NR_TELEFONE
 WHERE D1.CD_CPFCGC <> D2.CD_CPFCGC
   AND D1.CD_DDD_TEL IS NOT NULL AND D1.NR_TELEFONE IS NOT NULL
   AND D2.CD_DDD_TEL IS NOT NULL AND D2.NR_TELEFONE IS NOT NULL
   AND D1.NR_TELEFONE <> '0' AND D2.NR_TELEFONE <> '0'
UNION ALL
-- E-MAIL
SELECT DISTINCT D1.CD_CLIENTE AS CD_CLIENTE_BUSC, D1.CD_CPFCGC AS CD_CPFCGC_BUSC,
       D2.CD_CLIENTE AS CD_CLIENTE_ENC, D2.CD_CPFCGC AS CD_CPFCGC_ENC, 'E-MAIL' AS TIPO_VINCULO
  FROM #DADOS_BASICOS D1
  JOIN #DADOS_BASICOS D2 ON D1.NM_E_MAIL = D2.NM_E_MAIL
 WHERE D1.CD_CPFCGC <> D2.CD_CPFCGC
   AND D1.NM_E_MAIL IS NOT NULL AND D2.NM_E_MAIL IS NOT NULL
   AND D1.NM_E_MAIL <> ' ' AND D2.NM_E_MAIL <> ' '
UNION ALL
-- PAI E MÃE
SELECT DISTINCT D1.CD_CLIENTE AS CD_CLIENTE_BUSC, D1.CD_CPFCGC AS CD_CPFCGC_BUSC,
       D2.CD_CLIENTE AS CD_CLIENTE_ENC, D2.CD_CPFCGC AS CD_CPFCGC_ENC, 'PAI OU MÃE' AS TIPO_VINCULO
  FROM #DADOS_BASICOS D1
  JOIN #DADOS_BASICOS D2 ON D1.NM_PAI = D2.NM_PAI AND D1.NM_MAE = D2.NM_MAE
 WHERE D1.CD_CPFCGC <> D2.CD_CPFCGC
   AND (D1.NM_PAI IS NOT NULL OR D1.NM_MAE IS NOT NULL)
   AND (D1.NM_PAI <> ' ' OR D1.NM_MAE <> ' ')
UNION ALL
-- CÔNJUGE
SELECT DISTINCT D1.CD_CLIENTE AS CD_CLIENTE_BUSC, D1.CD_CPFCGC AS CD_CPFCGC_BUSC,
       D2.CD_CLIENTE AS CD_CLIENTE_ENC, D2.CD_CPFCGC AS CD_CPFCGC_ENC, 'CÔNJUGE' AS TIPO_VINCULO
  FROM #DADOS_BASICOS D1
  JOIN #DADOS_BASICOS D2 ON D1.NM_CONJUGE = D2.NM_CLIENTE
 WHERE D1.CD_CPFCGC <> D2.CD_CPFCGC
   AND D1.NM_CONJUGE IS NOT NULL AND D1.NM_CONJUGE <> ' '
UNION ALL
-- EMPRESA PF↔PJ
SELECT DISTINCT A.CD_CLIENTE, A.CD_CPFCGC,
       B.CD_CLIENTE AS CD_CLIENTE_ENC, B.CD_CPFCGC AS CD_CPFCGC_ENC, 'EMPRESA' TIPO_VINCULO
  FROM #PF A
  JOIN #PJ B
    ON A.NM_EMPRESA_LIMPO = B.NM_EMPRESA_LIMPO
   AND A.CD_CLIENTE <> B.CD_CLIENTE
 WHERE A.NM_EMPRESA_LIMPO NOT IN ('N','NA','NAO','NAOINFORMAR',
                                   'AUTONOMO','AUTONOMA',
                                   'NENHUMA','ESCRITORIOPROPRIO')
   AND A.NM_EMPRESA_LIMPO NOT LIKE '%NAO%'
   AND A.NM_EMPRESA_LIMPO IS NOT NULL
   AND A.NM_EMPRESA_LIMPO <> ''
UNION ALL
-- EMPRESA PF↔PF
SELECT DISTINCT B.CD_CLIENTE, B.CD_CPFCGC,
       A.CD_CLIENTE AS CD_CLIENTE_ENC, A.CD_CPFCGC AS CD_CPFCGC_ENC, 'EMPRESA' TIPO_VINCULO
  FROM #PF A
  JOIN #PF B
    ON A.NM_EMPRESA_LIMPO = B.NM_EMPRESA_LIMPO
   AND A.CD_CLIENTE <> B.CD_CLIENTE
 WHERE A.NM_EMPRESA_LIMPO NOT IN ('N','NA','NAO','NAOINFORMAR',
                                   'AUTONOMO','AUTONOMA',
                                   'NENHUMA','ESCRITORIOPROPRIO')
   AND A.NM_EMPRESA_LIMPO NOT LIKE '%NAO%'
   AND A.NM_EMPRESA_LIMPO IS NOT NULL
   AND A.NM_EMPRESA_LIMPO <> '';
 
DROP TABLE IF EXISTS #CLIENTES;
SELECT CD_CLIENTE_BUSC AS CD_CLIENTE INTO #CLIENTES FROM #VINCULO
UNION
SELECT CD_CLIENTE_ENC FROM #VINCULO;
 
-- ============== #NEGOCIO  (estrutural — sem colunas de quantidade) ==============
-- Usado apenas para identificar comprador/vendedor por NR_NEGOCIO e para
-- montar a lista NR_NEGOCIO:CD_PAPEL no output. As quantidades de contrato
-- agora vêm de ST_BMF_NEGOCIOS_NC (ver mais abaixo).
DROP TABLE IF EXISTS #NEGOCIO;
SELECT A.DT_NEGOCIO,
       A.NR_NEGOCIO,
       A.CD_NEGOCIO AS CD_PAPEL,
       A.CD_CLIENTE_COMPRA,
       A.CD_CLIENTE_VENDA
  INTO #NEGOCIO
  FROM ST_DIRETAS_BMF A
 WHERE DT_NEGOCIO >= @INICIO AND DT_NEGOCIO <= @FIM;
 
CREATE INDEX IDX_NEGOCIO_CLIENTES   ON #NEGOCIO (CD_CLIENTE_COMPRA, CD_CLIENTE_VENDA);
CREATE INDEX IDX_NEGOCIO_NR_NEGOCIO ON #NEGOCIO (NR_NEGOCIO);
CREATE INDEX IDX_VINCULO_CLIENTE_BUSC ON #VINCULO (CD_CLIENTE_BUSC) INCLUDE (TIPO_VINCULO);
CREATE INDEX IDX_VINCULO_CLIENTE_ENC  ON #VINCULO (CD_CLIENTE_ENC)  INCLUDE (TIPO_VINCULO);
CREATE INDEX IDX_PF ON #PF (NM_EMPRESA_LIMPO);
CREATE INDEX IDX_PJ ON #PJ (NM_EMPRESA_LIMPO);
 
-- Cada negócio é atribuído ao CLIENTE COMPRADOR (1 atribuição por negócio).
DROP TABLE IF EXISTS #RESULTADO;
SELECT CD_CLIENTE_BUSC AS CD_CLIENTE, CD_CPFCGC_BUSC AS CD_CPFCGC,
       CD_CLIENTE_ENC, CD_CPFCGC_ENC, TIPO_VINCULO
  INTO #RESULTADO
  FROM #VINCULO A
 WHERE EXISTS (SELECT 1 FROM #NEGOCIO B
                WHERE A.CD_CLIENTE_BUSC = B.CD_CLIENTE_COMPRA
                  AND A.CD_CLIENTE_ENC  = B.CD_CLIENTE_VENDA);
 
-- ============== #NEGOCIO_VINCULO  (lista de negócios dentro do grupo) ==============
-- Sem coluna QTD_CONTRATO aqui — esse cálculo agora vem de ST_BMF_NEGOCIOS_NC.
-- (v4.1) Inclui DT_NEGOCIO para servir de chave de junção com ST_BMF_NEGOCIOS_NC.
DROP TABLE IF EXISTS #NEGOCIO_VINCULO;
SELECT CD_CLIENTE_BUSC AS CD_CLIENTE, CD_CPFCGC_BUSC AS CD_CPFCGC,
       CD_CLIENTE_ENC, CD_CPFCGC_ENC, TIPO_VINCULO,
       B.DT_NEGOCIO,
       B.NR_NEGOCIO,
       B.CD_PAPEL,
       B.CD_CLIENTE_COMPRA, B.CD_CLIENTE_VENDA
  INTO #NEGOCIO_VINCULO
  FROM #VINCULO A
  JOIN #NEGOCIO B
    ON A.CD_CLIENTE_BUSC = B.CD_CLIENTE_COMPRA
   AND A.CD_CLIENTE_ENC  = B.CD_CLIENTE_VENDA;
 
-- DISTINCT (CD_CLIENTE, DT_NEGOCIO, NR_NEGOCIO, CD_PAPEL) p/ não inflar
-- contagem quando o mesmo negócio aparece em mais de um TIPO_VINCULO.
DROP TABLE IF EXISTS #NEGOCIO_VINCULO_DISTINCT;
SELECT DISTINCT CD_CLIENTE, DT_NEGOCIO, NR_NEGOCIO, CD_PAPEL
  INTO #NEGOCIO_VINCULO_DISTINCT
  FROM #NEGOCIO_VINCULO;
 
-- ============== Métricas auxiliares (mantidas — não dependem de QTD_CONTRATO) ==============
DROP TABLE IF EXISTS #contraparte;
SELECT a.CD_CLIENTE, a.CD_CLIENTE_ENC INTO #contraparte FROM #NEGOCIO_VINCULO AS a;
 
DROP TABLE IF EXISTS #qtd_total_por_contraparte;
SELECT CD_CLIENTE, CD_CLIENTE_ENC, COUNT(*) AS qtd_cd_cliente
  INTO #qtd_total_por_contraparte
  FROM #contraparte GROUP BY CD_CLIENTE, CD_CLIENTE_ENC;
 
DROP TABLE IF EXISTS #contraparte_distinto;
SELECT CD_CLIENTE, COUNT(DISTINCT CD_CLIENTE_ENC) AS qt_distinct
  INTO #contraparte_distinto
  FROM #qtd_total_por_contraparte GROUP BY CD_CLIENTE;
 
DROP TABLE IF EXISTS #concentracao_por_cliente;
SELECT a.CD_CLIENTE, a.CD_CLIENTE_ENC,
       CAST(100.0 * a.qtd_cd_cliente
            / NULLIF(SUM(a.qtd_cd_cliente) OVER (PARTITION BY a.CD_CLIENTE), 0)
            AS DECIMAL(9,4)) AS CONCENTRACAO_PCT
  INTO #concentracao_por_cliente
  FROM #qtd_total_por_contraparte AS a;
 
DROP TABLE IF EXISTS #concentracao_geral;
SELECT AVG(CONCENTRACAO_PCT) AS avg_concentracao,
       STDEV(CONCENTRACAO_PCT) AS stdev_concentracao
  INTO #concentracao_geral FROM #concentracao_por_cliente;
 
DECLARE @avg_concentracao_geral DECIMAL(17,5) = (SELECT MAX(avg_concentracao)   FROM #concentracao_geral)
      , @stdev_concentracao_geral DECIMAL(17,5) = (SELECT MAX(stdev_concentracao) FROM #concentracao_geral);
 
-- ============== >>> NOVO: QTD_CONTRATO via ST_BMF_NEGOCIOS_NC <<< ==============
-- QTD_CONTRATO_CLIENTE = soma de QT_QTDDET de TODOS os negócios do cliente no mês.
-- Na ST_BMF_NEGOCIOS_NC cada linha já representa o lado de UM cliente em UM negócio,
-- então basta agrupar por CD_CLIENTE.
DROP TABLE IF EXISTS #QTD_CONTRATO_CLIENTE;
SELECT CD_CLIENTE,
       SUM(ISNULL(QT_QTDDET, 0)) AS QTD_CONTRATO_CLIENTE
  INTO #QTD_CONTRATO_CLIENTE
  FROM ST_BMF_NEGOCIOS_NC
 WHERE DT_NEGOCIO >= @INICIO AND DT_NEGOCIO <= @FIM
 GROUP BY CD_CLIENTE;
 
-- QTD_CONTRATO_GRUPO = mesma soma, MAS restrita aos negócios específicos que
-- foram identificados como "grupo" na ST_DIRETAS_BMF (i.e., aqueles em que o
-- cliente é COMPRADOR e a contraparte VENDEDORA é um vínculo do cliente).
-- A junção é feita por (CD_CLIENTE, DT_NEGOCIO, NR_NEGOCIO) — o número do
-- negócio + o dia identificam unicamente a operação direta com a contraparte.
DROP TABLE IF EXISTS #QTD_CONTRATO_GRUPO;
SELECT N.CD_CLIENTE,
       SUM(ISNULL(N.QT_QTDDET, 0)) AS QTD_CONTRATO_GRUPO
  INTO #QTD_CONTRATO_GRUPO
  FROM ST_BMF_NEGOCIOS_NC N
  JOIN #NEGOCIO_VINCULO_DISTINCT V
    ON N.CD_CLIENTE  = V.CD_CLIENTE
   AND N.DT_NEGOCIO  = V.DT_NEGOCIO
   AND N.NR_NEGOCIO  = V.NR_NEGOCIO
 WHERE N.DT_NEGOCIO >= @INICIO AND N.DT_NEGOCIO <= @FIM
 GROUP BY N.CD_CLIENTE;
 
-- Contagem de negócios DISTINTOS dentro do grupo (para a coluna QTD. NEGÓCIO MÊS GRUPO).
DROP TABLE IF EXISTS #QTD_NEGOCIO_VINCULO;
SELECT CD_CLIENTE,
       COUNT(*) AS QTD_NEGOCIO_MES_GRUPO
  INTO #QTD_NEGOCIO_VINCULO
  FROM #NEGOCIO_VINCULO_DISTINCT
 GROUP BY CD_CLIENTE;
 
-- ============== #CONCENTRACAO  (NOVA FÓRMULA) ==============
-- CONCENTRACAO = QTD_CONTRATO_GRUPO / QTD_CONTRATO_CLIENTE * 100
DROP TABLE IF EXISTS #CONCENTRACAO;
SELECT A.CD_CLIENTE,
       A.QTD_CONTRATO_CLIENTE,
       B.QTD_CONTRATO_GRUPO,
       C.QTD_NEGOCIO_MES_GRUPO,
       CAST(B.QTD_CONTRATO_GRUPO AS FLOAT)
         / NULLIF(CAST(A.QTD_CONTRATO_CLIENTE AS FLOAT), 0) * 100 AS CONCENTRACAO
  INTO #CONCENTRACAO
  FROM #QTD_CONTRATO_CLIENTE A
  JOIN #QTD_CONTRATO_GRUPO   B ON A.CD_CLIENTE = B.CD_CLIENTE
  JOIN #QTD_NEGOCIO_VINCULO  C ON A.CD_CLIENTE = C.CD_CLIENTE;
 
DROP TABLE IF EXISTS #RESULTADO_FINAL;
SELECT A.CD_CLIENTE, A.CD_CPFCGC, A.CD_CLIENTE_ENC, A.CD_CPFCGC_ENC,
       A.TIPO_VINCULO,
       B.QTD_NEGOCIO_MES_GRUPO,
       B.QTD_CONTRATO_CLIENTE,
       B.QTD_CONTRATO_GRUPO,
       CAST(B.CONCENTRACAO AS NUMERIC(7,2)) AS CONCENTRACAO
  INTO #RESULTADO_FINAL
  FROM #RESULTADO A
  JOIN #CONCENTRACAO B ON A.CD_CLIENTE = B.CD_CLIENTE;
-- WHERE B.CONCENTRACAO > 10;  -- relatório NÃO filtra (regra existe só no alerta)
 
DROP TABLE IF EXISTS #VINCULO_RESULTADO;
SELECT DISTINCT CD_CLIENTE, TIPO_VINCULO
  INTO #VINCULO_RESULTADO FROM #RESULTADO_FINAL;
 
DROP TABLE IF EXISTS #CD_CLIENTE_RESULTADO;
SELECT DISTINCT CD_CLIENTE, CD_CLIENTE_ENC
  INTO #CD_CLIENTE_RESULTADO FROM #RESULTADO_FINAL;
 
-- Sem STRING_AGG -> STUFF + FOR XML PATH
DROP TABLE IF EXISTS #CD_CLI_RESULT;
SELECT X.CD_CLIENTE,
       STUFF((SELECT ';' + CAST(Y.CD_CLIENTE_ENC AS VARCHAR(50))
                FROM #CD_CLIENTE_RESULTADO Y
               WHERE Y.CD_CLIENTE = X.CD_CLIENTE
               FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 1, '') AS CD_CLIENTE_ENC
  INTO #CD_CLI_RESULT
  FROM (SELECT DISTINCT CD_CLIENTE FROM #CD_CLIENTE_RESULTADO) X;
 
DROP TABLE IF EXISTS #VINC_RESULT;
SELECT X.CD_CLIENTE,
       STUFF((SELECT ';' + Y.TIPO_VINCULO
                FROM #VINCULO_RESULTADO Y
               WHERE Y.CD_CLIENTE = X.CD_CLIENTE
               FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 1, '') AS VINCULO
  INTO #VINC_RESULT
  FROM (SELECT DISTINCT CD_CLIENTE FROM #VINCULO_RESULTADO) X;
 
-- ============== CD_PAPEL + NR_NEGOCIO agregado por cliente ==============
-- Formato: "CD_PAPEL:NR_NEGOCIO; CD_PAPEL:NR_NEGOCIO; ..."  (ex.: ABC:123; DEF:456)
DROP TABLE IF EXISTS #NR_NEG_DISTINCT;
SELECT DISTINCT CD_CLIENTE, NR_NEGOCIO, CD_PAPEL
  INTO #NR_NEG_DISTINCT
  FROM #NEGOCIO_VINCULO;
 
DROP TABLE IF EXISTS #NR_NEG_RESULT;
SELECT X.CD_CLIENTE,
       STUFF((SELECT '; ' + RTRIM(LTRIM(ISNULL(Y.CD_PAPEL,''))) + ':' + CAST(Y.NR_NEGOCIO AS VARCHAR(50))
                FROM #NR_NEG_DISTINCT Y
               WHERE Y.CD_CLIENTE = X.CD_CLIENTE
               ORDER BY Y.CD_PAPEL, Y.NR_NEGOCIO
               FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 2, '') AS NR_NEGOCIOS
  INTO #NR_NEG_RESULT
  FROM (SELECT DISTINCT CD_CLIENTE FROM #NR_NEG_DISTINCT) X;
 
-- ============== SELECT FINAL ==============
-- [QTD CONTRATO MÊS GRUPO]  = SUM(QT_QTDDET) do grupo (ST_BMF_NEGOCIOS_NC + vínculo)
-- [QTD CONTRATO CLIENTE]    = SUM(QT_QTDDET) do cliente (ST_BMF_NEGOCIOS_NC)
-- [CONCENTRAÇÃO]            = GRUPO / CLIENTE * 100
-- [QTD. NEGÓCIO MÊS GRUPO]  = COUNT distinto de (NR_NEGOCIO, CD_PAPEL) no grupo
-- [NR. NEGÓCIO]             = lista "NR_NEGOCIO:CD_PAPEL; ..."
SELECT DISTINCT
       FORMAT(@INICIO,'d','pt-br')                AS [DATA INÍCIO],
       FORMAT(@FIM,'d','pt-br')                   AS [DATA FIM],
       a.CD_CLIENTE                               AS [CÓD. CLIENTE],
       CD_CPFCGC                                  AS [CPF/CNPJ],
       MAX(c.CD_CLIENTE_ENC)                      AS [CÓD. CONTRAPARTE],
       MAX(b.VINCULO)                             AS [VÍNCULOS],
       MAX(d.NR_NEGOCIOS)                         AS [NEGÓCIOS],
	    FORMAT(MAX(CONCENTRACAO),'f','pt-br')      AS [CONCENTRAÇÃO],
       MAX(QTD_CONTRATO_GRUPO)                    AS [QTD. CONTRATO MÊS GRUPO],
       MAX(QTD_CONTRATO_CLIENTE)                  AS [QTD. CONTRATO MÊS CLIENTE],
      MAX(QTD_NEGOCIO_MES_GRUPO)                 AS [QTD. NEGÓCIO MÊS GRUPO]
  FROM #RESULTADO_FINAL a
  JOIN #VINC_RESULT    b ON a.CD_CLIENTE = b.CD_CLIENTE
  JOIN #CD_CLI_RESULT  c ON a.CD_CLIENTE = c.CD_CLIENTE
  LEFT JOIN #NR_NEG_RESULT d ON a.CD_CLIENTE = d.CD_CLIENTE
 WHERE a.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN a.CD_CLIENTE ELSE @CD_CLIENTE END
 GROUP BY a.CD_CLIENTE, a.CD_CPFCGC
 ORDER BY 1
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;