CREATE PROCEDURE [dbo].[FIRA_PR_CARGA_ST_DIRETAS_BVSP] @PREGAO DATETIME , @PREGAOFIM DATETIME
--WITH ENCRYPTION
AS


DROP TABLE IF EXISTS [dbo].[ST_DIRETAS_BVSP_PADRAO]
    CREATE TABLE [dbo].[ST_DIRETAS_BVSP_PADRAO] (
    [CD_CLIENTE_COMPRA] [int] NOT NULL,
	[NM_CLIENTE_COMPRA] [varchar](400) NULL,
	[VINC_COMPRA] [char](1) NULL,
	[CD_CLIENTE_BRO_COMPRA] [int] NOT NULL,
	[CD_CLIENTE_VENDA] [int] NOT NULL,
	[NM_CLIENTE_VENDA] [varchar](400) NULL,
	[VINC_VENDA] [char](1) NULL,
	[CD_CLIENTE_BRO_VENDA] [int] NOT NULL,
	[DT_PERIODO] [smalldatetime] NULL,
	[SISTEMA_COMPRA] [varchar](40) NULL,
	[SISTEMA_VENDA] [varchar](40) NULL,
	[NR_NEGOCIO] [int] NOT NULL,
	[QT_NEGOCIO_COMPRA] [float] NOT NULL,
	[QT_NEGOCIO_VENDA] [float] NOT NULL,
	[CD_PAPEL] [varchar](50) NULL,
	[HH_COMPRA] [varchar](5) NULL,
	[HH_VENDA] [varchar](5) NULL,
	[VL_TOTNEG_COMPRA] [float] NULL,
	[VL_TOTNEG_VENDA] [float] NULL,
	[VL_NEGOCIO_COMPRA] [float] NULL,
	[VL_NEGOCIO_VENDA] [float] NULL,
	[CD_ASSESSOR_COMPRA] [int] NULL,
	[DS_ASSESSOR_COMPRA] [varchar](60) NULL,
	[CD_ASSESSOR_VENDA] [int] NULL,
	[DS_ASSESSOR_VENDA] [varchar](60) NULL,
	[CD_OPERADOR_COMPRA] [int] NULL,
	[CD_OPERADOR_VENDA] [int] NULL,
	[DS_OPERADOR_COMPRA] [varchar](40) NULL,
	[DS_OPERADOR_VENDA] [varchar](40) NULL,
	[TP_CLIENTE_COMPRA] [int] NULL,
	[DS_TP_CLIENTE_COMPRA] [varchar](40) NULL,
	[TP_CLIENTE_VENDA] [int] NULL,
	[DS_TP_CLIENTE_VENDA] [varchar](40) NULL,
	[ds_tp_mercado_compra] [varchar](100) NULL,
	[cd_tp_mercado_compra] [varchar](3) NULL,
	[ds_tp_mercado_venda] [varchar](100) NULL,
	[cd_tp_mercado_venda] [varchar](3) NULL,
	[in_Afterm] [varchar](100) NULL,
	[DT_FIRA] DATETIME NULL
) ON [PRIMARY];

/***************************************************
inicio da comparação entre a tabela
da base padrao fira origem x tabela cliente destino
*****************************************************/
EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo',, @src_table='ST_DIRETAS_BVSP_PADRAO',
  @schema_name='dbo', @base_table='ST_DIRETAS_BVSP',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1;


/*******************************	
	CARGA ST_BMF_NEGOCIOS		
********************************/  

--DECLARE @PREGAO DATETIME, @PREGAOFIM DATETIME
--SET @PREGAO ='20250101'
--SET @PREGAOFIM ='20260201'


/****************************	
	CARGA ST_DIRETAS_BVSP		
****************************/     

WHILE @PREGAO < @PREGAOFIM 	
BEGIN	

	DELETE FROM ST_DIRETAS_BVSP	WHERE DT_PERIODO = @PREGAO	
	
		------
		---COMPRA
		SELECT 
			CD_CLIENTE, 
			F.DT_NEGOCIO, 
			F.CD_PAPEL, 
			F.CD_OPERADOR , 
			O.DS_OPERADOR,
			null AS DS_SISTEMA_ORIGEM,
			F.CD_NATOPE, 	
			F.CD_ASSESSOR, 
			F.TP_MERCADO, 
			F.NR_NEGOCIO, 
			SUM(QT_MULTIPLICADOR) QT_MULTIPLICADOR,	
			HH_NEGOCIO,
			SUM(VL_TOTNEG) VL_TOTNEG, 
			SUM(VL_NEGOCIO) VL_NEGOCIO,
			F.IN_AFTERM, 
			CD_CLIENTE_BRO

		INTO #COMPRA
		FROM ST_CORRETAGEM_ORDEM F 
		left JOIN ST_OPERADOR O
			ON F.CD_OPERADOR = O.CD_OPERADOR
		WHERE 
			CD_NATOPE= 'C' 
		AND DT_NEGOCIO = @PREGAO
		GROUP BY 
			CD_CLIENTE, 
			F.DT_NEGOCIO, 
			F.CD_PAPEL, 
			F.CD_OPERADOR, 
			O.DS_OPERADOR,
			F.CD_NATOPE, 	
			F.CD_ASSESSOR, 
			F.TP_MERCADO, 
			F.NR_NEGOCIO, 
			HH_NEGOCIO,
			F.IN_AFTERM, 
			CD_CLIENTE_BRO

		CREATE NONCLUSTERED INDEX IX_TEMP_COMPRA ON #COMPRA (CD_CLIENTE ) INCLUDE (DT_NEGOCIO,	CD_PAPEL,NR_NEGOCIO)


		------
		---VENDA
		SELECT 
			CD_CLIENTE, 
			F.DT_NEGOCIO, 
			F.CD_PAPEL, 
			F.CD_OPERADOR,
			O.DS_OPERADOR, 
			null AS DS_SISTEMA_ORIGEM,
			F.CD_NATOPE, 	
			F.CD_ASSESSOR, 
			F.TP_MERCADO, 
			F.NR_NEGOCIO, 
			SUM(QT_MULTIPLICADOR) AS QT_MULTIPLICADOR,	
			HH_NEGOCIO,
			SUM(VL_TOTNEG) VL_TOTNEG, 
			SUM(VL_NEGOCIO) VL_NEGOCIO,
			F.IN_AFTERM, 
			CD_CLIENTE_BRO
		into #VENDA
		FROM ST_CORRETAGEM_ORDEM F 
		left JOIN ST_OPERADOR O
			ON F.CD_OPERADOR = O.CD_OPERADOR
		WHERE 
			CD_NATOPE= 'V' 
		AND DT_NEGOCIO = @PREGAO
		GROUP BY 
			CD_CLIENTE, 
			F.DT_NEGOCIO, 
			F.CD_PAPEL, 
			F.CD_OPERADOR,
			O.DS_OPERADOR,
			F.CD_NATOPE, 	
			F.CD_ASSESSOR, 
			F.TP_MERCADO, 
			F.NR_NEGOCIO, 
			HH_NEGOCIO,
			F.IN_AFTERM, 
			CD_CLIENTE_BRO

		
		
		CREATE NONCLUSTERED INDEX IX_TEMP_VENDA ON #VENDA (CD_CLIENTE)INCLUDE (DT_NEGOCIO,	CD_PAPEL,NR_NEGOCIO)			

		-------
		------FINAL
		INSERT INTO ST_DIRETAS_BVSP	
		(
		 CD_CLIENTE_COMPRA,NM_CLIENTE_COMPRA,VINC_COMPRA,CD_CLIENTE_BRO_COMPRA,CD_CLIENTE_VENDA,NM_CLIENTE_VENDA,VINC_VENDA
		,CD_CLIENTE_BRO_VENDA,DT_PERIODO,SISTEMA_COMPRA,SISTEMA_VENDA,NR_NEGOCIO,QT_NEGOCIO_COMPRA,QT_NEGOCIO_VENDA,CD_PAPEL,HH_COMPRA
		,HH_VENDA,VL_TOTNEG_COMPRA,VL_TOTNEG_VENDA,VL_NEGOCIO_COMPRA,VL_NEGOCIO_VENDA,CD_ASSESSOR_COMPRA,DS_ASSESSOR_COMPRA,CD_ASSESSOR_VENDA
		,DS_ASSESSOR_VENDA,CD_OPERADOR_COMPRA,CD_OPERADOR_VENDA,DS_OPERADOR_COMPRA,DS_OPERADOR_VENDA,TP_CLIENTE_COMPRA,DS_TP_CLIENTE_COMPRA
		,TP_CLIENTE_VENDA,DS_TP_CLIENTE_VENDA,DS_TP_MERCADO_COMPRA,CD_TP_MERCADO_COMPRA,DS_TP_MERCADO_VENDA,CD_TP_MERCADO_VENDA,IN_AFTERM
		)
		SELECT  
			C.CD_CLIENTE AS CD_CLIENTE_COMPRA,
			VCTC.NM_CLIENTE AS NM_CLIENTE_COMPRA,
			VCTC.IN_PESS_VINC AS VINC_COMPRA,	
			C.CD_CLIENTE_BRO AS CD_CLIENTE_BRO_COMPRA,	
			V.CD_CLIENTE AS CD_CLIENTE_VENDA,
			VCTV.NM_CLIENTE AS NM_CLIENTE_VENDA,
			VCTV.IN_PESS_VINC AS VINC_VENDA,	
			V.CD_CLIENTE_BRO AS CD_CLIENTE_BRO_VENDA,
			C.DT_NEGOCIO AS DT_PERIODO,
			C.DS_SISTEMA_ORIGEM AS SISTEMA_COMPRA,
			V.DS_SISTEMA_ORIGEM AS SISTEMA_VENDA, 
			C.NR_NEGOCIO,
			CASE WHEN C.QT_MULTIPLICADOR <= V.QT_MULTIPLICADOR THEN C.QT_MULTIPLICADOR ELSE V.QT_MULTIPLICADOR END AS QT_NEGOCIO_COMPRA,
			CASE WHEN C.QT_MULTIPLICADOR <= V.QT_MULTIPLICADOR THEN C.QT_MULTIPLICADOR ELSE V.QT_MULTIPLICADOR END AS QT_NEGOCIO_VENDA,	
			C.CD_PAPEL,
			C.HH_NEGOCIO AS HH_COMPRA,
			V.HH_NEGOCIO AS HH_VENDA,
			C.VL_TOTNEG  AS VL_TOTNEG_COMPRA,	
			V.VL_TOTNEG  AS VL_TOTNEG_VENDA,
			C.VL_NEGOCIO AS VL_NEGOCIO_COMPRA,	
			V.VL_NEGOCIO AS VL_NEGOCIO_VENDA,	
			VCTC.CD_ASSESSOR AS CD_ASSESSOR_COMPRA,	
			VCTC.NM_ASSESSOR AS DS_ASSESSOR_COMPRA,	
			VCTV.CD_ASSESSOR AS CD_ASSESSOR_VENDA,	
			VCTV.NM_ASSESSOR AS DS_ASSESSOR_VENDA,
			C.CD_OPERADOR AS CD_OPERADOR_COMPRA,
			V.CD_OPERADOR AS CD_OPERADOR_VENDA,
			C.DS_OPERADOR AS DS_OPERADOR_COMPRA,
			V.DS_OPERADOR AS DS_OPERADOR_VENDA,
			VCTC.TP_CLIENTE AS TP_CLIENTE_COMPRA,
			VCTC.DS_TIPO_CLIENTE AS DS_TP_CLIENTE_COMPRA,	
			VCTV.TP_CLIENTE AS TP_CLIENTE_COMPRA,
			VCTV.DS_TIPO_CLIENTE AS DS_TP_CLIENTE_COMPRA,

			CASE 
				WHEN C.TP_MERCADO = 'IER' THEN 'INTEGRALIZAÇÃO E RESG.DE COTAS'
				WHEN C.TP_MERCADO = 'VIS' THEN 'VISTA'
				WHEN C.TP_MERCADO = 'VIS' THEN 'VISTA'
				WHEN C.TP_MERCADO = 'EOC' THEN 'EXERC OPC COMPRA'
				WHEN C.TP_MERCADO = 'EOV' THEN 'EXERC OPC  VENDA'
				WHEN C.TP_MERCADO = 'LEI' THEN 'LEILAO'
				WHEN C.TP_MERCADO = 'LNC' THEN 'LEILAO DE  NAO COTADOS'
				WHEN C.TP_MERCADO = 'FRA' THEN 'FRACIONARIO'
				WHEN C.TP_MERCADO = 'TER' THEN 'TERMO'
				WHEN C.TP_MERCADO = 'OPC' THEN 'OPCAO DE COMPRA'
				WHEN C.TP_MERCADO = 'OPV' THEN 'OPCAO DE VENDA'
				WHEN C.TP_MERCADO = 'FUT' THEN 'FUTURO C/ MOV. CONTINUA'
				WHEN C.TP_MERCADO = 'VFU' THEN 'VENCIMENTO FUTURO'
				WHEN C.TP_MERCADO = 'EST' THEN 'ESTRUTURADO'
				WHEN C.TP_MERCADO = 'CET' THEN 'COTAS DE ETF'
			ELSE 'MERCADO NÃO CADASTRADO' END AS DS_TP_MERCADO_COMPRA,
		
			C.TP_MERCADO AS CD_TP_MERCADO_COMPRA,	

			CASE 
				WHEN C.TP_MERCADO = 'IER' THEN 'INTEGRALIZAÇÃO E RESG.DE COTAS'
				WHEN C.TP_MERCADO = 'VIS' THEN 'VISTA'
				WHEN C.TP_MERCADO = 'VIS' THEN 'VISTA'
				WHEN C.TP_MERCADO = 'EOC' THEN 'EXERC OPC COMPRA'
				WHEN C.TP_MERCADO = 'EOV' THEN 'EXERC OPC  VENDA'
				WHEN C.TP_MERCADO = 'LEI' THEN 'LEILAO'
				WHEN C.TP_MERCADO = 'LNC' THEN 'LEILAO DE  NAO COTADOS'
				WHEN C.TP_MERCADO = 'FRA' THEN 'FRACIONARIO'
				WHEN C.TP_MERCADO = 'TER' THEN 'TERMO'
				WHEN C.TP_MERCADO = 'OPC' THEN 'OPCAO DE COMPRA'
				WHEN C.TP_MERCADO = 'OPV' THEN 'OPCAO DE VENDA'
				WHEN C.TP_MERCADO = 'FUT' THEN 'FUTURO C/ MOV. CONTINUA'
				WHEN C.TP_MERCADO = 'VFU' THEN 'VENCIMENTO FUTURO'
				WHEN C.TP_MERCADO = 'EST' THEN 'ESTRUTURADO'
				WHEN C.TP_MERCADO = 'CET' THEN 'COTAS DE ETF'
			ELSE 'MERCADO NÃO CADASTRADO' END AS DS_TP_MERCADO_VENDA,
		
			V.TP_MERCADO AS CD_TP_MERCADO_VENDA,	
			C.IN_AFTERM

		FROM #COMPRA C
		INNER JOIN #VENDA V
			ON  C.DT_NEGOCIO = V.DT_NEGOCIO 	
			AND C.CD_PAPEL	 = V.CD_PAPEL 	
			AND C.NR_NEGOCIO = V.NR_NEGOCIO 	 
		left JOIN (SELECT DISTINCT CD_CLIENTE,NM_CLIENTE,IN_PESS_VINC,CD_ASSESSOR,NM_ASSESSOR,TP_CLIENTE,DS_TIPO_CLIENTE FROM V_CLIENTE_TODOS) VCTC ON C.CD_CLIENTE = VCTC.CD_CLIENTE
		left JOIN (SELECT DISTINCT CD_CLIENTE,NM_CLIENTE,IN_PESS_VINC,CD_ASSESSOR,NM_ASSESSOR,TP_CLIENTE,DS_TIPO_CLIENTE FROM V_CLIENTE_TODOS) VCTV ON V.CD_CLIENTE = VCTV.CD_CLIENTE


	---### DROP TEMP ###---
	DROP TABLE #COMPRA
	DROP TABLE #VENDA



SET @PREGAO = @PREGAO +1

END	

-- ================================================
-- Marca DT_FIRA para registros carregados (fallback)
-- ================================================
DECLARE @__dt_fira_now DATETIME = GETDATE();
IF COL_LENGTH(N'dbo.ST_DIRETAS_BVSP', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE [dbo].[ST_DIRETAS_BVSP]
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL;
END
/******* fim do processo de carga **********/

--passo 3
/***** limpa a tabela do banco para nao ficar sujeira ******/
DROP TABLE IF EXISTS ST_DIRETAS_BVSP_PADRAO