CREATE PROCEDURE [dbo].[PR_MEDIA_OPERACOES_BMF] @ANOMES INT, @CD_CLIENTE INT	, @QTDPORPAGINA INT, @PAGINA INT	
WITH RECOMPILE
AS

--DECLARE @PAGINA        INT = 1;
--DECLARE @QTDPORPAGINA INT = 5 	
--DECLARE @ANOMES INT
--DECLARE @CD_CLIENTE INT	
--SET @ANOMES =202512	
--SET @CD_CLIENTE = '10'	

DECLARE @ANOMES_INI SMALLDATETIME
DECLARE @ANOMES_FIM SMALLDATETIME
DECLARE @ANOMES_MES_INI SMALLDATETIME
DECLARE @ANOMES_MES_FIM SMALLDATETIME

SET @ANOMES_INI = (SELECT TOP 1 EOMONTH(DT_PERIODO,-1) FROM ST_PERIODO WHERE CD_ANOMES = @ANOMES)
SET @ANOMES_FIM = (SELECT TOP 1 EOMONTH(DT_PERIODO) FROM ST_PERIODO WHERE CD_ANOMES = @ANOMES)

SET @ANOMES_MES_INI = (SELECT TOP 1 EOMONTH(DT_PERIODO,-7) FROM ST_PERIODO WHERE CD_ANOMES = @ANOMES)
SET @ANOMES_MES_FIM = (SELECT TOP 1 EOMONTH(DT_PERIODO,-1) FROM ST_PERIODO WHERE CD_ANOMES = @ANOMES)
 

-------VOL MES ATUAL------------
;WITH #T1  AS(
SELECT 		
YEAR(DT_NEGOCIO)*100 + MONTH(DT_NEGOCIO) AS CD_ANOMES,		
F.CD_CLIENTE, 
SUM(ISNULL((pr_negocio * QT_QTDDET),0)) VOL_MES_ATUAL,
SUM(ISNULL(QT_QTDDET,0)) QTD_MES
FROM 		
ST_BMF_NEGOCIOS_NC F 
inner join ST_PERIODO p on F.DT_NEGOCIO = p.DT_PERIODO
WHERE 		
p.CD_ANOMES = @ANOMES and		
TP_NEGOCIO IN ('NORMAL','DAY TRADE','DAYTRADE') AND
F.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN F.CD_CLIENTE ELSE CAST(@CD_CLIENTE AS INT) END		
GROUP BY YEAR(DT_NEGOCIO)*100 + MONTH(DT_NEGOCIO) ,F.CD_CLIENTE
),



--------------MEDIA E DESVIO 6 MESES-----------------	

#T4 AS (
SELECT 
CD_CLIENTE,	 
AVG(VOL_MES_ATUAL)VOL_MED_6_MESES,
STDEV(VOL_MES_ATUAL)VOL_DESV_6_MESES,
AVG(QTD_CONTRATOS)QTD_MED_6MESES,
STDEV(QTD_CONTRATOS)QTD_DESV_6MESES
FROM (
	SELECT 		
	YEAR(DT_NEGOCIO)*100 + MONTH(DT_NEGOCIO) CD_ANOMES,	
	F.CD_CLIENTE, 		
	SUM(ISNULL(pr_negocio * QT_QTDDET,0)) VOL_MES_ATUAL,
	SUM(ISNULL(QT_QTDDET,0)) QTD_CONTRATOS
	FROM 		
	ST_BMF_NEGOCIOS_NC F 		
	WHERE 			
	F.DT_NEGOCIO > @ANOMES_MES_INI AND
	F.DT_NEGOCIO <= @ANOMES_MES_FIM AND
	F.TP_NEGOCIO IN ('NORMAL', 'DAY TRADE','DAYTRADE') AND
F.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN F.CD_CLIENTE ELSE CAST(@CD_CLIENTE AS INT) END		
	GROUP BY YEAR(DT_NEGOCIO)*100 + MONTH(DT_NEGOCIO),F.CD_CLIENTE 
	)X	
GROUP BY CD_CLIENTE )		
 

 
SELECT 
A.CD_ANOMES AS [ANO MÊS],		
A.CD_CLIENTE AS [CÓD. CLIENTE],		
VV.NM_CLIENTE AS [NOME DO CLIENTE],		
ISNULL(A.QTD_MES,0) AS [QTD. CONTRATO MÊS],	
FORMAT(ISNULL(A.VOL_MES_ATUAL,0),'f','pt-br') AS [VALOR AJUSTE MÊS],	
FORMAT(ISNULL(D.VOL_MED_6_MESES,0),'f','pt-br') AS [MÉDIA AJUSTE 6M],
FORMAT(ISNULL(D.VOL_DESV_6_MESES,0) ,'f','pt-br') AS [DESVIO AJUSTE 6M],
FORMAT(ISNULL(ISNULL(A.VOL_MES_ATUAL,0) / NULLIF(D.VOL_MED_6_MESES,0),0),'P2') AS [PERC. AJUSTE MÊS],
FORMAT(ISNULL(D.QTD_MED_6MESES,0),'f','pt-br') AS [MÉDIA QTD. CONTRATO 6M],	
FORMAT(ISNULL(D.QTD_DESV_6MESES,0),'f','pt-br') AS [DESVIO QTD. CONTRATO 6M],	
FORMAT(ISNULL(ISNULL(CAST(A.QTD_MES AS FLOAT),0)/NULLIF(CAST(D.QTD_MED_6MESES AS FLOAT),0),0),'P2') AS [PERC. QTD. CONTRATO MÊS],
		
CASE WHEN 	ISNULL(A.QTD_MES,0) > D.QTD_MED_6MESES + (ISNULL(D.QTD_DESV_6MESES,0)*3) THEN 'SIM' ELSE 'NÃO' END [CAI ALERTA]

FROM #T1 A 		
LEFT OUTER JOIN #T4 D ON A.CD_CLIENTE = D.CD_CLIENTE	
LEFT OUTER JOIN (SELECT DISTINCT CD_CLIENTE,NM_CLIENTE FROM V_CLIENTE_TODOS) VV ON VV.CD_CLIENTE = A.CD_CLIENTE


ORDER BY 1

OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;