CREATE PROCEDURE [dbo].[PR_CADASTRO_COMITENTE]  @CD_CLIENTE VARCHAR(160),@NOME_EMIT VARCHAR(MAX), @QTDPORPAGINA INT, @PAGINA INT
--WITH ENCRYPTION
AS		

--DECLARE @PAGINA INT = 1, @QTDPORPAGINA INT = 80000, @CD_CLIENTE INT,@NOME_EMIT VARCHAR(160)
--SET @CD_CLIENTE=''
--SET @NOME_EMIT =''


	SELECT DISTINCT		
	'CPF' TIPO_EMIT_DOC,		
	dbo.formatar_cpf(A.CD_CPFCGC_EMIT) as CD_CPFCGC_EMIT,		
	RTRIM(LTRIM(NM_EMIT_ORDEM))   NM_EMIT_ORDEM,		
	A.CD_SISTEMA,		
	'BRA' SG_PAIS_EMIT,		
	FORMAT((SELECT MAX(DT_CRIACAO) FROM TSCCLIGER X		
	WHERE X.CD_CPFCGC = A.CD_CPFCGC),'d','pt-br') DT_INICIO,		
	'INDETERMINADO' DT_FIM,		
	'CPF' TIPO_COMIT_CLI, SG_PAIS SG_PAIS_COMITENTE,		
	CD_CLIENTE,		
	dbo.formatar_cpf(CD_CPFCGC) as CD_CPFCGC,		
	NM_CLIENTE		
	FROM ST_DADOS_BASICOS_PF A		
	WHERE 
	A.IN_CONTA_INV = 'N' AND	
	A.CD_CPFCGC_EMIT IS NOT NULL	AND 
	A.IN_SITUAC = 'A'	
	AND CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN CD_CLIENTE ELSE CAST(@CD_CLIENTE AS INT) END	
	AND RTRIM(LTRIM(NM_EMIT_ORDEM)) LIKE CASE WHEN ISNULL(@NOME_EMIT,'T') = 'TODOS' THEN RTRIM(LTRIM(NM_EMIT_ORDEM)) ELSE  '%'+@NOME_EMIT+'%' END	

 
		UNION ALL		
		
	SELECT DISTINCT		
	'CPF' TIPO_EMIT_DOC,		
	dbo.formatar_cpf(A.CD_CPFCGC_EMIT)CD_CPFCGC_EMIT,		
	RTRIM(LTRIM(NM_EMIT_ORDEM))   NM_EMIT_ORDEM,		
	A.CD_SISTEMA,		
	'BRA' SG_PAIS_EMIT,		
	FORMAT((SELECT MAX(DT_CRIACAO) FROM TSCCLIGER X		
	WHERE X.CD_CPFCGC = A.CD_CPFCGC),'d','pt-br') DT_INICIO,		
	'INDETERMINADO' DT_FIM,		
	'CNPJ' TIPO_COMIT_CLI, SG_PAIS SG_PAIS_COMITENTE,		
	CD_CLIENTE,		
	dbo.formatar_cnpj(CD_CPFCGC) as CD_CPFCGC ,		
	NM_CLIENTE		
	FROM ST_DADOS_BASICOS_PJ A		
	WHERE 
	A.IN_CONTA_INV = 'N' AND
	A.CD_CPFCGC_EMIT IS NOT NULL AND 
	A.IN_SITUAC = 'A'	
	AND CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN CD_CLIENTE ELSE CAST(@CD_CLIENTE AS INT) END	
	AND RTRIM(LTRIM(NM_EMIT_ORDEM)) LIKE CASE WHEN ISNULL(@NOME_EMIT,'T') = 'TODOS' THEN RTRIM(LTRIM(NM_EMIT_ORDEM)) ELSE  '%'+@NOME_EMIT+'%' END	

	ORDER BY 1
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE ISNULL(@QTDPORPAGINA,'') END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE ISNULL(@QTDPORPAGINA,'') END ROWS ONLY;