CREATE PROCEDURE [dbo].[FIRA_PR_CARGA_ALERT_301_RANKING_DAYTRADE_BMF] @PREGAO SMALLDATETIME , @AUX INT
AS

/*************************************************************************************************
REGRA DO ALERTA:
Resultado mês > média + 3 desvios padrão
Índice acerto/erro > média + 3 desvios padrão
Quantidade de daytrade > 10
*************************************************************************************************/


 --passo 1
/**********************************
inicio da etapa de verificação
aqui temos o script da base padrao
***********************************/
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ST_ALERT_RANKING_DAYTRADE_BMF_PADRAO]') AND type in (N'U'))
CREATE TABLE [dbo].[ST_ALERT_RANKING_DAYTRADE_BMF_PADRAO](
	[DATA] [date] NULL,
	[CD_CLIENTE] [int] NOT NULL,
	[ATV_NEG_DT] [varchar](max) NULL,
	[ATV_TOT] [varchar](max) NULL,
	[RSLT_FIN] [numeric](17, 2) NULL,
	[MED_RSLT_FIN] [numeric](17, 2) NULL,
	[DES_RSLT_FIN] [numeric](17, 2) NULL,
	[IND_ACERTO] [numeric](17, 2) NULL,
	[MED_IND_ACERTO] [numeric](17, 2) NULL,
	[DES_IND_ACERTO] [numeric](17, 2) NULL,
	[IND_ERRO] [numeric](17, 2) NULL,
	[MED_IND_ERRO] [numeric](17, 2) NULL,
	[DES_IND_ERRO] [numeric](17, 2) NULL,
	[QTD_DT] [int] NULL,
	[QTD_DIAS_DT] [int] NULL,
	[QTD_DIAS_OPE] [int] NULL,
	[DIAS_PROP] [numeric](17, 2) NULL,
	[QTD_CRT_DT] [numeric](17, 2) NULL,
	[RENT_PROP] [numeric](17, 5) NULL,
	[QTD_CRT_TOT] [numeric](17, 2) NULL,
	[DT_PROP] [numeric](17, 2) NULL,
	[CONTRA_IN] [numeric](10, 0) NULL,
	[CONTRA_OUT] [numeric](10, 0) NULL,
	[DAYTRADISTA] [varchar](1) NOT NULL,
	[ALT_FQ] [varchar](1) NOT NULL,
	[RSLT_FIN_ABS] [numeric](17, 2) NULL,
	[DT_FIRA] DATETIME NULL
) ON [PRIMARY]
 

/***************************************************
inicio da comparação entre a tabela
da base padrao fira origem x tabela cliente destino
*****************************************************/
EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo', @src_table='ST_ALERT_RANKING_DAYTRADE_BMF_PADRAO',
  @schema_name='dbo', @base_table='ST_ALERT_RANKING_DAYTRADE_BMF',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1;

/******** fim da etapa de verificação ************/


/*********inicio da carga do alerta*******/
--DECLARE @PREGAO SMALLDATETIME, @AUX INT
--SET @PREGAO = '20250805'
--SET @AUX = (SELECT DAY(@PREGAO))

DECLARE @INICIO SMALLDATETIME, @FIM SMALLDATETIME, @CD_CLIENTE VARCHAR(50), @DT_INICIO_6M SMALLDATETIME, @DT_FIM_6M SMALLDATETIME 
SET @INICIO = (SELECT MIN(DT_PERIODO) FROM ST_PERIODO WHERE CD_ANOMES = (SELECT MAX(CD_ANOMES) FROM ST_PERIODO WHERE DT_PERIODO = DATEADD(DAY,- @AUX,@PREGAO))) 
SET @FIM    = (SELECT MAX(DT_PERIODO) FROM ST_PERIODO WHERE CD_ANOMES = (SELECT MAX(CD_ANOMES) FROM ST_PERIODO WHERE DT_PERIODO = @INICIO)) 	

SET @DT_INICIO_6M = (SELECT MIN(DT_PERIODO) FROM ST_PERIODO WHERE CD_ANOMES = (SELECT MIN(CD_ANOMES) FROM ST_PERIODO WHERE DT_PERIODO >=DATEADD(MONTH,-6,@INICIO) AND  DT_PERIODO < @INICIO))
SET @DT_FIM_6M    = (SELECT MAX(DT_PERIODO) FROM ST_PERIODO WHERE CD_ANOMES = (SELECT MAX(CD_ANOMES) FROM ST_PERIODO WHERE DT_PERIODO >=DATEADD(MONTH,-6,@INICIO) AND  DT_PERIODO < @INICIO))

PRINT '[PARAMETROS - ALERTA RANKING DAYTRADE BMF]'+'@DT_INICIO_6M:'+CONVERT(VARCHAR,@DT_INICIO_6M,23)+' @DT_FIM_6M:'+CONVERT(VARCHAR,@DT_FIM_6M,23)+' @INICIO:'+CONVERT(VARCHAR,@INICIO,23)+' @FIM:'+CONVERT(VARCHAR,@FIM,23)    	
		
/*
	INICIO - DAYTRADE RESUMO BMF
*/

----------------------------------------------------------------------

DROP TABLE IF EXISTS #T1;	
	SELECT CD_CLIENTE_COMPROU
		 , @INICIO INICIO
		 , @FIM FIM
		 , SUM(VL_FINANC) FINAN
		 , (SELECT CAST(SUM(X.QTD) AS FLOAT) 
			  FROM (SELECT A.CD_CLIENTE
						 , A.DT_DATMOV
						 , COUNT(DISTINCT  A.CD_COMMOD + ISNULL(A.CD_SERIE,'')) QTD
					  FROM ST_DAYTRADE_DETALHE_BMF A		
				     WHERE A.CD_CLIENTE = A2.CD_CLIENTE_COMPROU 		
					   AND A.DT_DATMOV >=@INICIO 
					   AND A.DT_DATMOV <=@FIM		
					   AND QT_QTDDET > 0		
				  GROUP BY A.CD_CLIENTE
					     , A.DT_DATMOV) 
				   X) QTD_DAYTRADES
		, (SELECT CAST(SUM(X.QTD_DIAS_DAYTRADE) AS FLOAT) 
			  FROM (SELECT A.CD_CLIENTE
						 , A.DT_DATMOV 
						 , COUNT(DISTINCT A.DT_DATMOV) AS QTD_DIAS_DAYTRADE
					  FROM ST_DAYTRADE_DETALHE_BMF A		
				     WHERE A.CD_CLIENTE = A2.CD_CLIENTE_COMPROU 		
					   AND A.DT_DATMOV >=@INICIO 
					   AND A.DT_DATMOV <=@FIM		
					   AND QT_QTDDET > 0		
				  GROUP BY A.CD_CLIENTE
					     , A.DT_DATMOV) 
				   X) QTD_DIAS_DAYTRADE	
				,SUM(ABS(VL_COMPRA) + ABS(VL_VENDA)) VOLUME_DAYTRADE
		INTO #T1
		FROM ST_DAYTRADE_RESUMO_BMF A2		
	   WHERE DT_PREGAO_COMPROU >=@INICIO 
	     AND DT_PREGAO_COMPROU <=@FIM		
	GROUP BY CD_CLIENTE_COMPROU;	

----------------------------------------------------------------------

	DROP TABLE IF EXISTS #BMF01 ;

	SELECT DT_NEGOCIO
		 , F.CD_CLIENTE
		 , ISNULL(QT_QTDDET,0) AS QT_QTDDET
		 , PR_NEGOCIO
		 , TP_NEGOCIO
	  INTO #BMF01
	  FROM ST_BMF_NEGOCIOS_NC F 
	 WHERE F.DT_NEGOCIO >= @INICIO 
	   AND F.DT_NEGOCIO <= @FIM  
	   AND TP_NEGOCIO IN ('NORMAL','DAYTRADE','DAY TRADE')

	DROP TABLE IF EXISTS #BMF02;

	SELECT YEAR(DT_NEGOCIO)*100 + MONTH(DT_NEGOCIO) AS CD_ANOMES
		 , F.CD_CLIENTE
		 , SUM(ISNULL(QT_QTDDET,0)) AS QT_CONTRATO_DAYTRADE 
	  INTO #BMF02
	  FROM #BMF01 F 
	 WHERE F.DT_NEGOCIO >= @INICIO 
	   AND F.DT_NEGOCIO <= @FIM  
	   AND TP_NEGOCIO IN ('DAYTRADE','DAYTRADE','DAY TRADE')
  GROUP BY  YEAR(DT_NEGOCIO)*100 + MONTH(DT_NEGOCIO) 
		 , CD_CLIENTE

	DROP TABLE IF EXISTS #BMF03;

	SELECT YEAR(DT_NEGOCIO)*100 + MONTH(DT_NEGOCIO) AS CD_ANOMES
		 , F.CD_CLIENTE
		 , SUM(ISNULL(QT_QTDDET,0)) AS QT_CONTRATO_TOTAL 

	  INTO #BMF03
	  FROM #BMF01 F 
	 WHERE F.DT_NEGOCIO >= @INICIO 
	   AND F.DT_NEGOCIO <= @FIM  
	   AND TP_NEGOCIO IN ('NORMAL','DAYTRADE','DAY TRADE')
  GROUP BY  YEAR(DT_NEGOCIO)*100 + MONTH(DT_NEGOCIO) 
		 , CD_CLIENTE
		  

	DROP TABLE IF EXISTS  #VOLUME_CONTRATO;

		 SELECT A.CD_CLIENTE
			  , A.QT_CONTRATO_DAYTRADE
			  , B.QT_CONTRATO_TOTAL
		   INTO #VOLUME_CONTRATO
		   FROM #BMF02 A 
	  LEFT JOIN #BMF03 B 
			 ON A.CD_CLIENTE = B.CD_CLIENTE

----------------------------------------------------------------------
DROP TABLE IF EXISTS #T2;

	   SELECT CD_CLIENTE
			, CAST(SUM(ACERTO) AS FLOAT) ACERTO
			, CAST(SUM(PERDA) AS FLOAT)  PERDA
			, CAST(SUM(EMPATE) AS FLOAT) EMPATE
		INTO #T2
		FROM(SELECT CD_CLIENTE
				 , CASE WHEN VL_ACERTO > 0 THEN 1 ELSE 0 END ACERTO
				 , CASE WHEN VL_ACERTO < 0 THEN 1 ELSE 0 END PERDA
				 , CASE WHEN VL_ACERTO = 0 THEN 1 ELSE 0 END EMPATE		
			  FROM ( SELECT DT_DATMOV DT_PREGAO
						  , A.CD_CLIENTE
						  --, CD_COMMOD
						  --, CD_SERIE
						  , CAST(SUM(CAST(VL_VALOPE AS NUMERIC(15,2)))AS FLOAT) VL_ACERTO 		
					   FROM ST_DAYTRADE_DETALHE_BMF A		
					  WHERE DT_DATMOV >= @INICIO 
					    AND DT_DATMOV <= @FIM		
					    AND QT_QTDDET > 0		
				   GROUP BY DT_DATMOV
						  , CD_CLIENTE
						  --, CD_COMMOD
						  --, CD_SERIE		
					) X		
			) X2		
	GROUP BY CD_CLIENTE;	
----------------------------------------------------------------------		
  DROP TABLE IF EXISTS #RESULTADO_DAYTRADE;	

		 SELECT 
	   DISTINCT T1.CD_CLIENTE_COMPROU
			  , T1.QTD_DAYTRADES
			  , T1.FINAN AS RESULTADO_FINANCEIRO
			  ,	B.QT_CONTRATO_DAYTRADE
			  , B.QT_CONTRATO_TOTAL
			  , T2.ACERTO 
			  , T2.PERDA  
			  , T2.EMPATE 
			  , T1.QTD_DIAS_DAYTRADE
			  , CAST(CAST(ACERTO AS NUMERIC(17,2)) / QTD_DIAS_DAYTRADE AS NUMERIC(17,2))  INDICE_ACERTO
			  , CAST(CAST(PERDA  AS NUMERIC(17,2)) / QTD_DIAS_DAYTRADE AS NUMERIC(17,2))  INDICE_ERRO
		   INTO #RESULTADO_DAYTRADE
		   FROM #T1 T1 		
LEFT OUTER JOIN #T2 T2 
			 ON T1.CD_CLIENTE_COMPROU = T2.CD_CLIENTE 
LEFT OUTER JOIN #VOLUME_CONTRATO B
			 ON T1.CD_CLIENTE_COMPROU = B.CD_CLIENTE


/*
	FIM - DAYTRADE RESUMO BMF
*/

/*
	INICIO - DAYTRADE RESUMO BMF - HISTORICO
*/

----------------------------------------------------------------------
		
DROP TABLE IF EXISTS #T1H;	
	SELECT CD_CLIENTE_COMPROU
		 , B.CD_ANOMES
		 , SUM(VL_FINANC) FINAN
		 , (SELECT CAST(SUM(X.QTD) AS FLOAT) 
			  FROM (SELECT A.CD_CLIENTE
						 , A.DT_DATMOV
						 , COUNT(DISTINCT  A.CD_COMMOD + ISNULL(A.CD_SERIE,'')) QTD
					  FROM ST_DAYTRADE_DETALHE_BMF A		
				     WHERE A.CD_CLIENTE = A2.CD_CLIENTE_COMPROU 		
					   AND A.DT_DATMOV >= @DT_INICIO_6M 
					   AND A.DT_DATMOV <= @DT_FIM_6M		
					   AND QT_QTDDET > 0		
				  GROUP BY A.CD_CLIENTE
					     , A.DT_DATMOV) 
				   X) QTD_DAYTRADES
		, (SELECT CAST(SUM(X.QTD_DIAS_DAYTRADE) AS FLOAT) 
			  FROM (SELECT A.CD_CLIENTE
						 , A.DT_DATMOV 
						 , COUNT(DISTINCT A.DT_DATMOV) AS QTD_DIAS_DAYTRADE
					  FROM ST_DAYTRADE_DETALHE_BMF A		
				     WHERE A.CD_CLIENTE = A2.CD_CLIENTE_COMPROU 		
					   AND A.DT_DATMOV >=@DT_INICIO_6M 
					   AND A.DT_DATMOV <=@DT_FIM_6M		
					   AND QT_QTDDET > 0		
				  GROUP BY A.CD_CLIENTE
					     , A.DT_DATMOV) 
				   X) QTD_DIAS_DAYTRADE	
				,SUM(ABS(VL_COMPRA) + ABS(VL_VENDA)) VOLUME_DAYTRADE
		INTO #T1H
		FROM ST_DAYTRADE_RESUMO_BMF A2 
   LEFT JOIN ST_PERIODO B
		  ON A2.DT_PREGAO_COMPROU = B.DT_PERIODO

	   WHERE DT_PREGAO_COMPROU >=@DT_INICIO_6M 
	     AND DT_PREGAO_COMPROU <=@DT_FIM_6M		
	GROUP BY CD_CLIENTE_COMPROU,CD_ANOMES;	
----------------------------------------------------------------------


----------------------------------------------------------------------
DROP TABLE IF EXISTS #T2H;

	   SELECT CD_CLIENTE
			, CD_ANOMES
			, CAST(SUM(ACERTO) AS FLOAT) ACERTO
			, CAST(SUM(PERDA)  AS FLOAT)  PERDA
			, CAST(SUM(EMPATE) AS FLOAT) EMPATE
		INTO #T2H
		FROM(SELECT CD_CLIENTE
				 , CASE WHEN VL_ACERTO > 0 THEN 1 ELSE 0 END ACERTO
				 , CASE WHEN VL_ACERTO < 0 THEN 1 ELSE 0 END PERDA
				 , CASE WHEN VL_ACERTO = 0 THEN 1 ELSE 0 END EMPATE	
				 ,YEAR(DT_PREGAO)*100 + MONTH(DT_PREGAO) CD_ANOMES
			  FROM ( SELECT DT_DATMOV DT_PREGAO
						  , A.CD_CLIENTE
						 -- , CD_COMMOD
						 -- , CD_SERIE
						  , CAST(SUM(CAST(VL_VALOPE AS NUMERIC(15,2)))AS FLOAT) VL_ACERTO 		
					   FROM ST_DAYTRADE_DETALHE_BMF A		
					  WHERE DT_DATMOV >= @DT_INICIO_6M 
					    AND DT_DATMOV <= @DT_FIM_6M		
					    AND QT_QTDDET > 0		
				   GROUP BY DT_DATMOV
						  , CD_CLIENTE
						 -- , CD_COMMOD
						  --, CD_SERIE		
					) X		
			) X2		
	GROUP BY CD_CLIENTE,CD_ANOMES;	

----------------------------------------------------------------------		
  DROP TABLE IF EXISTS #RESULTADO_DAYTRADEH;	

		 SELECT 
	   DISTINCT T1.CD_CLIENTE_COMPROU
			  ,   AVG(T1.FINAN)																	   AS MEDIA_RESULTADO_FINANCEIRO
			  ,ISNULL(STDEV(T1.FINAN),0)														   AS DESVIO_RESULTADO_FINANCEIRO
			  ,   AVG(CAST(CAST(T2.ACERTO AS NUMERIC(17,2)) / QTD_DIAS_DAYTRADE AS NUMERIC(17,2))) AS MEDIA_INDICE_ACERTO
			  ,ISNULL(STDEV(CAST(CAST(T2.ACERTO AS NUMERIC(17,2)) / QTD_DIAS_DAYTRADE AS NUMERIC(17,2))),0) AS DESVIO_INDICE_ACERTO
			  ,   AVG(CAST(CAST(T2.PERDA AS NUMERIC(17,2))  / QTD_DIAS_DAYTRADE AS NUMERIC(17,2))) AS MEDIA_INDICE_ERRO
			  ,ISNULL(STDEV(CAST(CAST(T2.PERDA AS NUMERIC(17,2))  / QTD_DIAS_DAYTRADE AS NUMERIC(17,2))),0) AS DESVIO_INDICE_ERRO
 
		   INTO #RESULTADO_DAYTRADEH
		   FROM #T1H T1 		
			LEFT OUTER JOIN #T2H T2 
			 ON T1.CD_CLIENTE_COMPROU = T2.CD_CLIENTE 
			AND T1.CD_ANOMES = T2.CD_ANOMES
	   GROUP BY T1.CD_CLIENTE_COMPROU

/*
	FIM - DAYTRADE RESUMO BMF - HISTORICO
*/
/*
	INICIO - DAYTRADE PAPEL BMF
*/

----------------------------------------------------------------------

 DROP TABLE IF EXISTS #T1_PAPEL;

		SELECT DT_DATMOV  AS DT_PREGAO
			 , CD_CLIENTE AS CD_CLIENTE
			 , CD_COMMOD+ISNULL(CD_SERIE,'') AS CD_NEGOCIO
			 , SUM((CASE WHEN CD_NATOPE = 'C' THEN -1 ELSE 1 END) * QT_QTDDET * PR_NEGOCIO)  VL_ACERTO 
		  INTO #T1_PAPEL
		  FROM ST_DAYTRADE_DETALHE_BMF	
		 WHERE DT_DATMOV >= @INICIO		
		   AND DT_DATMOV <= @FIM		
	  GROUP BY DT_DATMOV
		     , CD_CLIENTE
			 , CD_COMMOD+ISNULL(CD_SERIE,'')	
----------------------------------------------------------------------
--ACERTO POR PAPEL	
 DROP TABLE IF EXISTS #T3_PAPEL;

		SELECT CD_CLIENTE
			 , CD_NEGOCIO 
			 , SUM(CASE WHEN VL_ACERTO > 0 THEN 1 ELSE 0 END) VL_ACERTO
			 , SUM(CASE WHEN VL_ACERTO < 0 THEN 1 ELSE 0 END) VL_PERDA
			 , SUM(CASE WHEN VL_ACERTO = 0 THEN 1 ELSE 0 END) VL_EMPATE
			 , SUM(VL_ACERTO) VL_FINAN
		  INTO #T3_PAPEL
		  FROM #T1_PAPEL		
	  GROUP BY CD_CLIENTE
		     , CD_NEGOCIO	
----------------------------------------------------------------------
--FINANCEIRO TOTAL	
DROP TABLE IF EXISTS #T2_PAPEL;

	   SELECT CD_CLIENTE
			, SUM(VL_ACERTO) VL_FINAN  
		 INTO #T2_PAPEL 
		 FROM #T1_PAPEL		
	 GROUP BY CD_CLIENTE	
----------------------------------------------------------------------			
-- QUERY FINAL	
DROP TABLE IF EXISTS #RESULTADO_DAYTRADE_PAPEL;

		SELECT T3.CD_CLIENTE 
			 , T3.CD_NEGOCIO 
			 , T3.VL_FINAN [RESULTADO_FINANCEIRO]
			 , T2.VL_FINAN [RESULTADO_FINANCEIRO_TOTAL]
			 , T3.VL_ACERTO [ACERTO] 
			 , T3.VL_EMPATE [EMPATE]
			 , T3.VL_PERDA  [PERDA]	
		INTO #RESULTADO_DAYTRADE_PAPEL
		FROM #T2_PAPEL T2, #T3_PAPEL T3		
	   WHERE T2.CD_CLIENTE = T3.CD_CLIENTE;		
	
/*
	FIM - DAYTRADE PAPEL 
*/


	DROP TABLE IF EXISTS #TD_ATIVOS_NEG_A;

		  SELECT 
		DISTINCT CD_CLIENTE			   
			   , CD_COMMOD+ISNULL(CD_SERIE,'') AS CD_PAPEL			   
			INTO #TD_ATIVOS_NEG_A
			FROM ST_BMF_NEGOCIOS_NC 
		   WHERE DT_DATMOV >= @INICIO 
			 AND DT_DATMOV <= @FIM
			 AND TP_NEGOCIO IN ('NORMAL','DAYTRADE','DAY TRADE');
		
	DROP TABLE IF EXISTS #TD_ATIVOS_NEG_B;

		 SELECT CD_CLIENTE 
		      , STUFF((
			    SELECT ', ' + P.CD_PAPEL
			    FROM #TD_ATIVOS_NEG_A P
			    WHERE P.CD_CLIENTE = A.CD_CLIENTE
			    FOR XML PATH('')
			), 1, 2, '') AS ATIVOS_TOTAL 
		   INTO #TD_ATIVOS_NEG_B
		   FROM #TD_ATIVOS_NEG_A A 
	   GROUP BY CD_CLIENTE


/*
	INICIO - IN/OUT
*/

 DROP TABLE IF EXISTS #IN_OUT_A;	

		SELECT CD_CONTRAPARTE_COMPROU
			 , CD_CLIENTE CD_CLIENTE_COMPROU					 
			 , CD_NATOPE
			 , CD_CONTRAPARTE_COMPROU CD_CONTRAPARTE_COMPROU_DE			 
			 , CD_CLIENTE_COMPROU_DE			 
			 , CD_COMMOD+ISNULL(CD_SERIE,'') CD_NEGOCIO_COMPROU 
			 , QT_QTDDET QT_DAYTRADE
			 , PR_NEGOCIO VL_NEGOCIO_COMPROU
			 , CASE WHEN CD_CLIENTE_COMPROU_DE IS NULL THEN 'OUT' ELSE 'IN' END IND_CONTRAPARTE
		 INTO #IN_OUT_A
		 FROM ST_DAYTRADE_DETALHE_BMF
		WHERE DT_DATMOV >= @INICIO 
		  AND DT_DATMOV <= @FIM;



  DROP TABLE IF EXISTS #IN_OUT_B;

		 SELECT CD_CONTRAPARTE_COMPROU_DE
			  , CD_CLIENTE_COMPROU 
			  , SUM((CASE WHEN CD_NATOPE = 'C' THEN -1 ELSE 1 END) * QT_DAYTRADE * VL_NEGOCIO_COMPROU) RESULTADO
			  ,'OUT' IND_CONTRAPARTE
		   INTO #IN_OUT_B
		   FROM #IN_OUT_A
		  WHERE IND_CONTRAPARTE = 'OUT'
		  GROUP BY CD_CONTRAPARTE_COMPROU_DE
		         , CD_CLIENTE_COMPROU
		 
		 UNION ALL

		 SELECT CD_CLIENTE_COMPROU_DE
			  , CD_CLIENTE_COMPROU
			  , SUM((CASE WHEN CD_NATOPE = 'C' THEN -1 ELSE 1 END) * QT_DAYTRADE * VL_NEGOCIO_COMPROU) RESULTADO
			  ,'IN' IND_CONTRAPARTE
		   FROM #IN_OUT_A
		  WHERE IND_CONTRAPARTE = 'IN'
		  GROUP BY CD_CLIENTE_COMPROU_DE
				 , CD_CLIENTE_COMPROU;
			
	DROP TABLE IF EXISTS  #IN_OUT_C;
		   SELECT * INTO #IN_OUT_C FROM #IN_OUT_B;
	
	DROP TABLE IF EXISTS #IN;
  
		  SELECT CD_CLIENTE_COMPROU 
			   , CD_CONTRAPARTE_COMPROU_DE
			   , RESULTADO
			   , IND_CONTRAPARTE
			   , ROW_NUMBER() OVER (PARTITION BY CD_CLIENTE_COMPROU ORDER BY RESULTADO DESC) RANKING
			INTO #IN
		    FROM #IN_OUT_C
		   WHERE IND_CONTRAPARTE = 'IN';
 
		

	DROP TABLE IF EXISTS #OUT;

		  SELECT CD_CLIENTE_COMPROU 
			   , CD_CONTRAPARTE_COMPROU_DE
			   , RESULTADO
			   , IND_CONTRAPARTE
			   , ROW_NUMBER() OVER (PARTITION BY CD_CLIENTE_COMPROU ORDER BY RESULTADO DESC) RANKING
			INTO #OUT
		    FROM #IN_OUT_C
		   WHERE IND_CONTRAPARTE = 'OUT';

    DROP TABLE IF EXISTS #TODOS;

		   SELECT CD_CLIENTE_COMPROU INTO #TODOS 
			 FROM #IN 

		    UNION

		   SELECT CD_CLIENTE_COMPROU 
		     FROM #OUT;

	DROP TABLE IF EXISTS #IN_OUT_VOLUME;

		   SELECT A.CD_CLIENTE_COMPROU
			    , B.CD_CONTRAPARTE_COMPROU_DE CONTRAPARTE_IN 
				, C.CD_CONTRAPARTE_COMPROU_DE CONTRAPARTE_OUT
			  INTO #IN_OUT_VOLUME
			 FROM #TODOS A 
		LEFT JOIN (SELECT * FROM #IN WHERE RANKING = 1) B 
			   ON A.CD_CLIENTE_COMPROU = B.CD_CLIENTE_COMPROU 
		LEFT JOIN (SELECT * FROM #OUT WHERE RANKING = 1) C 
			   ON A.CD_CLIENTE_COMPROU = C.CD_CLIENTE_COMPROU 


/*
	FIM - IN/OUT
*/
/*
	INICIO - DIAS OPERADOS
*/
   DROP TABLE IF EXISTS #DIAS_OPERADOS;
		  
		  SELECT 
		DISTINCT CD_CLIENTE 
			   , COUNT(DISTINCT DT_DATMOV) QT_DIAS_OPERADOS
			INTO #DIAS_OPERADOS
			FROM ST_BMF_NEGOCIOS_NC 
		   WHERE DT_DATMOV >= @INICIO
			 AND DT_DATMOV <= @FIM
			 AND TP_NEGOCIO IN ('NORMAL','DAYTRADE','DAY TRADE')
		GROUP BY CD_CLIENTE;
/*
	FIM - DIAS OPERADOS
*/

/*
	INICIO - VOLUME NEGOCIADO
*/

 DROP TABLE IF EXISTS #VOLUME_NEG;

		SELECT CD_CLIENTE
			 , SUM(ISNULL(QT_QTDDET * PR_NEGOCIO,0)) AS VOL_MES_ATUAL
			 , SUM(ISNULL(QT_QTDDET,0)) AS QTD_MES
		 INTO #VOLUME_NEG
		 FROM ST_BMF_NEGOCIOS_NC A
		 
		WHERE DT_DATMOV >= @INICIO
		  AND DT_DATMOV <= @FIM
		  AND TP_NEGOCIO IN ('NORMAL','DAYTRADE','DAY TRADE')
	 GROUP BY CD_CLIENTE;

/*
	FIM - VOLUME NEGOCIADO
*/

 --DELETE FROM ST_ALERT_RANKING_DAYTRADE_BMF WHERE  DATA = DATEADD(DAY,- @AUX,@PREGAO);

 --INSERT INTO ST_ALERT_RANKING_DAYTRADE_BMF (DATA,CD_CLIENTE,ATV_NEG_DT,ATV_TOT,RSLT_FIN,MED_RSLT_FIN,DES_RSLT_FIN,IND_ACERTO,MED_IND_ACERTO,DES_IND_ACERTO,IND_ERRO,MED_IND_ERRO,DES_IND_ERRO,QTD_DT,QTD_DIAS_DT,QTD_DIAS_OPE,DIAS_PROP,QTD_CRT_DT,RENT_PROP,QTD_CRT_TOT,DT_PROP,CONTRA_IN,CONTRA_OUT,DAYTRADISTA,ALT_FQ,RSLT_FIN_ABS)

	  SELECT 
	DISTINCT  DATEADD(DAY,- @AUX,@PREGAO)																				  AS DATA
			, 
			A.CD_CLIENTE_COMPROU																						  AS CD_CLIENTE
			,replace(STUFF(
			(SELECT ', ' + P.CD_NEGOCIO
			 FROM #RESULTADO_DAYTRADE_PAPEL P
			 WHERE P.CD_CLIENTE = A.CD_CLIENTE_COMPROU
			 FOR XML PATH('')), 1, 2, ''),' ','')																				  AS ATV_NEG_DT --ativos_daytrade
		   , C.ATIVOS_TOTAL																								  AS ATV_TOT	--ativos_total 
		   , CAST(A.RESULTADO_FINANCEIRO AS NUMERIC(17,2))																  AS RSLT_FIN --resultado financeiro
		   , ABS(CAST(G.MEDIA_RESULTADO_FINANCEIRO AS NUMERIC(17,2)))													  AS MED_RSLT_FIN -- MEDIA_RESULTADO_FINANCEIRO
		   , ABS(CAST(G.DESVIO_RESULTADO_FINANCEIRO AS NUMERIC(17,2)))													  AS DES_RSLT_FIN --DESVIO_RESULTADO_FINANCEIRO
		   , CAST(A.INDICE_ACERTO AS NUMERIC(17,2))																		  AS IND_ACERTO --INDICE_ACERTO
		   , CAST(G.MEDIA_INDICE_ACERTO AS NUMERIC(17,2))																  AS MED_IND_ACERTO --MEDIA_INDICE_ACERTO
		   , CAST(G.DESVIO_INDICE_ACERTO AS NUMERIC(17,2))																  AS DES_IND_ACERTO --DESVIO_INDICE_ACERTO
		   , CAST(A.INDICE_ERRO AS NUMERIC(17,2))																		  AS IND_ERRO --INDICE_ERRO
		   , CAST(G.MEDIA_INDICE_ERRO AS NUMERIC(17,2))																	  AS MED_IND_ERRO --MEDIA_INDICE_ERRO
		   , CAST(G.DESVIO_INDICE_ERRO  AS NUMERIC(17,2))																  AS DES_IND_ERRO--DESVIO_INDICE_ERRO
		   , A.QTD_DAYTRADES																							  AS QTD_DT
		   , A.QTD_DIAS_DAYTRADE 																						  AS QTD_DIAS_DT	   
		   , E.QT_DIAS_OPERADOS																							  AS QTD_DIAS_OPE
		   , CAST((QTD_DIAS_DAYTRADE / QT_DIAS_OPERADOS) AS NUMERIC(17,2))											      AS DIAS_PROP
		   , QT_CONTRATO_DAYTRADE																						  AS QTD_CRT_DT
		   , CAST((A.RESULTADO_FINANCEIRO / QT_CONTRATO_DAYTRADE)	AS NUMERIC(17,5))									  AS RENT_PROP
		   , QT_CONTRATO_TOTAL																							  AS QTD_CRT_TOT	  
		   , CAST((QT_CONTRATO_DAYTRADE / QT_CONTRATO_TOTAL) AS NUMERIC(17,2))											  AS DT_PROP --DAYTRADE_PROP
		   , D.CONTRAPARTE_IN																							  AS CONTRA_IN --CONTRAPARTE_IN
		   , D.CONTRAPARTE_OUT																							  AS CONTRA_OUT --CONTRAPARTE_OUT
		   , CASE WHEN (QTD_DIAS_DAYTRADE / QT_DIAS_OPERADOS) >= 0.7 THEN 'S' ELSE 'N' END								  AS DAYTRADISTA
		   , CASE WHEN QTD_DIAS_DAYTRADE > 12 THEN 'S' ELSE 'N' END														  AS ALT_FQ --ALTA_FREQUENCIA
		   , ABS(CAST(A.RESULTADO_FINANCEIRO AS NUMERIC(17,2)))															  AS RSLT_FIN_ABS
		FROM #RESULTADO_DAYTRADE A  
   LEFT JOIN #RESULTADO_DAYTRADE_PAPEL B 
		  ON A.CD_CLIENTE_COMPROU = B.CD_CLIENTE
   LEFT JOIN #TD_ATIVOS_NEG_B C
		  ON A.CD_CLIENTE_COMPROU = C.CD_CLIENTE
   LEFT JOIN #IN_OUT_VOLUME D
		  ON A.CD_CLIENTE_COMPROU = D.CD_CLIENTE_COMPROU
   LEFT JOIN #DIAS_OPERADOS E
		  ON A.CD_CLIENTE_COMPROU = E.CD_CLIENTE
   LEFT JOIN #VOLUME_NEG F 
		  ON A.CD_CLIENTE_COMPROU = F.CD_CLIENTE
   LEFT JOIN #RESULTADO_DAYTRADEH G
		  ON A.CD_CLIENTE_COMPROU = G.CD_CLIENTE_COMPROU

	    WHERE

	QTD_DAYTRADES > 10
and (
      (isnull(A.RESULTADO_FINANCEIRO,0) > 0
       and isnull(A.RESULTADO_FINANCEIRO,0) > (isnull(G.MEDIA_RESULTADO_FINANCEIRO,0) + 3* isnull(G.DESVIO_RESULTADO_FINANCEIRO,0))
       and isnull(A.INDICE_ACERTO,0) >= (isnull(G.MEDIA_INDICE_ACERTO,0) + 3* isnull(G.DESVIO_INDICE_ACERTO,0)))
   or (isnull(A.RESULTADO_FINANCEIRO,0) < 0
       and isnull(A.RESULTADO_FINANCEIRO,0) < (isnull(G.MEDIA_RESULTADO_FINANCEIRO,0) - 3* isnull(G.DESVIO_RESULTADO_FINANCEIRO,0))
       and isnull(A.INDICE_ERRO,0) >= (isnull(G.MEDIA_INDICE_ERRO,0) + 3* isnull(G.DESVIO_INDICE_ERRO,0)))
    )
 
 

/******* fim do processo de carga do alerta **********/
 --================================================
 --Marca DT_FIRA para registros carregados (fallback)
 --================================================
DECLARE @__dt_fira_now DATETIME = GETDATE();
IF COL_LENGTH(N'dbo.ST_ALERT_RANKING_DAYTRADE_BMF', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE [dbo].ST_ALERT_RANKING_DAYTRADE_BMF
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL;
END

--passo 3
/***** limpa a tabela do banco para nao ficar sujeira ******/
DROP TABLE IF EXISTS ST_ALERT_RANKING_DAYTRADE_BMF_PADRAO