CREATE PROCEDURE [dbo].[OBTERSCORECADASTRO]
(
	@USUARIO INT
)
--WITH ENCRYPTION
AS

BEGIN

DECLARE @DEFAULT INT  =3

	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO)
	BEGIN
		SELECT @DEFAULT AS PESOMENORIDADE, @DEFAULT AS PESOSEPTUAGENARIO, @DEFAULT AS PESOPROFISSAORISCO, @DEFAULT AS PESOVINCULADO
	END
	ELSE
	BEGIN
		SELECT 
			CASE WHEN MENORIDADE IS NULL THEN @DEFAULT ELSE MENORIDADE END AS PESOMENORIDADE,
			CASE WHEN SEPTUAGENARIO IS NULL THEN @DEFAULT ELSE SEPTUAGENARIO END AS PESOSEPTUAGENARIO,
			CASE WHEN PROFISSAORISCO IS NULL THEN @DEFAULT ELSE PROFISSAORISCO END AS PESOPROFISSAORISCO,
			CASE WHEN VINCULADO IS NULL THEN @DEFAULT ELSE VINCULADO END AS PESOVINCULADO
		FROM
		(
			SELECT PESO, ITEM
			FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO
		) D
		PIVOT
		(
			MAX(PESO)
			FOR ITEM IN ( MENORIDADE, SEPTUAGENARIO, PROFISSAORISCO, VINCULADO)
		) PIV;
	END
END