CREATE PROCEDURE [dbo].[FIRA_PR_CARGA_ST_DAYTRADE_RESUMO] @PREGAO DATETIME , @PREGAOFIM DATETIME
AS

DROP TABLE IF EXISTS [dbo].[ST_DAYTRADE_RESUMO_PADRAO]
    CREATE TABLE [dbo].[ST_DAYTRADE_RESUMO_PADRAO] (
    [CD_CLIENTE_COMPROU] int NULL, 
    [VL_COMPRA] float NULL,
    [VL_VENDA] float NULL,
    [VL_FINANC] float NULL,
    [DT_PREGAO_COMPROU] datetime NOT NULL,
    [QT_CONTRAPARTES] int NULL,
    [DT_PRIMEIRA_OPER] smalldatetime NULL,
	[DT_FIRA] DATETIME NULL
);

/***************************************************
inicio da comparação entre a tabela
da base padrao fira origem x tabela cliente destino
*****************************************************/
EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo',, @src_table='ST_DAYTRADE_RESUMO_PADRAO',
  @schema_name='dbo', @base_table='ST_DAYTRADE_RESUMO',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1;


--DECLARE @PREGAO DATETIME , @PREGAOFIM DATETIME
--SET @PREGAO ='20260201'
--SET @PREGAOFIM ='20260213'

/*********************************
VARIAVEIS DO CURSOR
*************************************/
DECLARE @DT_PREGAO_COMPROU SMALLDATETIME
DECLARE @CD_CLIENTE_COMPROU NUMERIC
DECLARE @CD_NEGOCIO_COMPROU VARCHAR(12)
DECLARE @COMPRA BIGINT
DECLARE @VENDA BIGINT
DECLARE @DT_PREGAO_COMPROU2 SMALLDATETIME
DECLARE @CD_CLIENTE_COMPROU2 NUMERIC
DECLARE @CD_NEGOCIO_COMPROU2 VARCHAR(12)
DECLARE @COMPRA2 BIGINT
DECLARE @VENDA2 BIGINT
DECLARE @QT_NEGOCIO_COMPROU2 BIGINT
DECLARE @QT_AUX BIGINT
DECLARE @NR_NEGOCIO_COMPROU2 NUMERIC(18,2)
DECLARE @IN CHAR(01)


/****************************	
	CARGA ST_DAYTRADE_RESUMO		
****************************/     

WHILE @PREGAO < @PREGAOFIM 	
BEGIN	
	/***************************
	##### DEFINE DAYTRADE #####
	***************************/
 

		UPDATE ST_DAYTRADE_DETALHE
		SET QT_DAYTRADE = NULL
		WHERE DT_PREGAO_COMPROU = @PREGAO


		DECLARE CUR_TOT CURSOR FOR
	
			SELECT DT_PREGAO_COMPROU, CD_CLIENTE_COMPROU, CD_NEGOCIO_COMPROU, SUM(COMPRA) C, SUM(VENDA) V 
			FROM(
				SELECT DT_PREGAO_COMPROU, CD_CLIENTE_COMPROU, CD_NEGOCIO_COMPROU, 
				CASE WHEN CD_NATOPE = 'C' THEN SUM(QT_NEGOCIO_COMPROU) ELSE SUM(0) END COMPRA,
				CASE WHEN CD_NATOPE = 'V' THEN SUM(QT_NEGOCIO_COMPROU) ELSE SUM(0) END VENDA
			
				FROM ST_DAYTRADE_DETALHE A
				WHERE DT_PREGAO_COMPROU = @PREGAO
				GROUP BY DT_PREGAO_COMPROU, CD_CLIENTE_COMPROU, CD_NEGOCIO_COMPROU, CD_NATOPE
			) X
			GROUP BY DT_PREGAO_COMPROU, CD_CLIENTE_COMPROU, CD_NEGOCIO_COMPROU 
			ORDER BY 1,2,3
		

		OPEN CUR_TOT
		FETCH NEXT FROM CUR_TOT INTO @DT_PREGAO_COMPROU, @CD_CLIENTE_COMPROU, @CD_NEGOCIO_COMPROU, @COMPRA, @VENDA
		--------ABRE CURSOR TOT
		WHILE @@FETCH_STATUS = 0
		BEGIN
		SET @QT_AUX =0
		SET @IN = 'N'

		IF @COMPRA >= @VENDA -----COMPRA MAIOR QUE VENDA
		BEGIN
			UPDATE ST_DAYTRADE_DETALHE
			SET QT_DAYTRADE = QT_NEGOCIO_COMPROU
			WHERE DT_PREGAO_COMPROU = @DT_PREGAO_COMPROU
			AND CD_CLIENTE_COMPROU = @CD_CLIENTE_COMPROU 
			AND CD_NEGOCIO_COMPROU = @CD_NEGOCIO_COMPROU
			AND CD_NATOPE = 'V'


		DECLARE CUR_COMPRA CURSOR FOR
			SELECT DT_PREGAO_COMPROU, CD_CLIENTE_COMPROU ,CD_NEGOCIO_COMPROU, QT_NEGOCIO_COMPROU, NR_NEGOCIO_COMPROU
			FROM ST_DAYTRADE_DETALHE
			WHERE DT_PREGAO_COMPROU = @DT_PREGAO_COMPROU
			AND CD_CLIENTE_COMPROU = @CD_CLIENTE_COMPROU
			AND CD_NEGOCIO_COMPROU =@CD_NEGOCIO_COMPROU
			AND CD_NATOPE = 'C'
			ORDER BY NR_NEGOCIO_COMPROU

		OPEN CUR_COMPRA

		FETCH NEXT FROM CUR_COMPRA INTO @DT_PREGAO_COMPROU2, @CD_CLIENTE_COMPROU2, @CD_NEGOCIO_COMPROU2, @QT_NEGOCIO_COMPROU2,@NR_NEGOCIO_COMPROU2

		WHILE @@FETCH_STATUS = 0 ----ABRE CURSOR DETALHE
		BEGIN
		SET @QT_AUX = @QT_NEGOCIO_COMPROU2 + @QT_AUX
		IF @QT_AUX <= @VENDA
		BEGIN
			UPDATE ST_DAYTRADE_DETALHE SET QT_DAYTRADE = QT_NEGOCIO_COMPROU
			WHERE DT_PREGAO_COMPROU = @DT_PREGAO_COMPROU2
			AND CD_CLIENTE_COMPROU = @CD_CLIENTE_COMPROU2
			AND CD_NEGOCIO_COMPROU = @CD_NEGOCIO_COMPROU2
			AND NR_NEGOCIO_COMPROU = @NR_NEGOCIO_COMPROU2
			AND CD_NATOPE = 'C'

		IF @QT_AUX = @VENDA
		SET @IN= 'S'

		END
		ELSE 
		BEGIN
			IF @IN = 'N'
			BEGIN
			SET @IN = 'S'
			SET @QT_AUX = ABS(@QT_AUX-@VENDA-@QT_NEGOCIO_COMPROU2)
			UPDATE ST_DAYTRADE_DETALHE SET QT_DAYTRADE = @QT_AUX
			WHERE DT_PREGAO_COMPROU = @DT_PREGAO_COMPROU2
			AND CD_CLIENTE_COMPROU = @CD_CLIENTE_COMPROU2
			AND CD_NEGOCIO_COMPROU = @CD_NEGOCIO_COMPROU2
			AND NR_NEGOCIO_COMPROU = @NR_NEGOCIO_COMPROU2
			AND CD_NATOPE = 'C'

			SET @QT_AUX = @VENDA +1
			END

		END
		FETCH NEXT FROM CUR_COMPRA INTO @DT_PREGAO_COMPROU2, @CD_CLIENTE_COMPROU2, @CD_NEGOCIO_COMPROU2, @QT_NEGOCIO_COMPROU2,@NR_NEGOCIO_COMPROU2

		END

		CLOSE CUR_COMPRA
		DEALLOCATE CUR_COMPRA

		END
		ELSE
		BEGIN-----------------TRECHO 2
			UPDATE ST_DAYTRADE_DETALHE
			SET QT_DAYTRADE = QT_NEGOCIO_COMPROU
			WHERE DT_PREGAO_COMPROU = @DT_PREGAO_COMPROU
			AND CD_CLIENTE_COMPROU = @CD_CLIENTE_COMPROU 
			AND CD_NEGOCIO_COMPROU = @CD_NEGOCIO_COMPROU
			AND CD_NATOPE = 'C'

		DECLARE CUR_VENDA CURSOR FOR
			SELECT DT_PREGAO_COMPROU, CD_CLIENTE_COMPROU ,CD_NEGOCIO_COMPROU, QT_NEGOCIO_COMPROU, NR_NEGOCIO_COMPROU
			FROM ST_DAYTRADE_DETALHE A
			WHERE DT_PREGAO_COMPROU = @DT_PREGAO_COMPROU
			AND CD_CLIENTE_COMPROU = @CD_CLIENTE_COMPROU
			AND CD_NEGOCIO_COMPROU =@CD_NEGOCIO_COMPROU
			AND CD_NATOPE = 'V'
			ORDER BY NR_NEGOCIO_COMPROU;

		OPEN CUR_VENDA

		SET @QT_AUX= 0

		FETCH NEXT FROM CUR_VENDA INTO @DT_PREGAO_COMPROU2, @CD_CLIENTE_COMPROU2, @CD_NEGOCIO_COMPROU2, @QT_NEGOCIO_COMPROU2,@NR_NEGOCIO_COMPROU2

		WHILE @@FETCH_STATUS = 0 ----ABRE CURSOR DETALHE
		BEGIN
		SET @QT_AUX = @QT_NEGOCIO_COMPROU2 + @QT_AUX
		IF @QT_AUX <= @COMPRA
		BEGIN
			UPDATE ST_DAYTRADE_DETALHE SET QT_DAYTRADE = QT_NEGOCIO_COMPROU
			WHERE DT_PREGAO_COMPROU = @DT_PREGAO_COMPROU2
			AND CD_CLIENTE_COMPROU = @CD_CLIENTE_COMPROU2
			AND CD_NEGOCIO_COMPROU = @CD_NEGOCIO_COMPROU2
			AND NR_NEGOCIO_COMPROU = @NR_NEGOCIO_COMPROU2
			AND CD_NATOPE = 'V'

		IF @QT_AUX = @COMPRA
		   SET @IN= 'S'

		END
		ELSE 
		BEGIN
		IF @IN = 'N'
		BEGIN
			SET @QT_AUX = ABS(@QT_AUX-@COMPRA-@QT_NEGOCIO_COMPROU2)
			SET @IN= 'S'
		
			UPDATE ST_DAYTRADE_DETALHE SET QT_DAYTRADE = @QT_AUX
			WHERE DT_PREGAO_COMPROU = @DT_PREGAO_COMPROU2
			AND CD_CLIENTE_COMPROU = @CD_CLIENTE_COMPROU2
			AND CD_NEGOCIO_COMPROU = @CD_NEGOCIO_COMPROU2
			AND NR_NEGOCIO_COMPROU = @NR_NEGOCIO_COMPROU2
			AND CD_NATOPE = 'V'

		SET @QT_AUX = @COMPRA +1
		END
		END
		FETCH NEXT FROM CUR_VENDA INTO @DT_PREGAO_COMPROU2, @CD_CLIENTE_COMPROU2, @CD_NEGOCIO_COMPROU2, @QT_NEGOCIO_COMPROU2,@NR_NEGOCIO_COMPROU2

		END
		CLOSE CUR_VENDA
		DEALLOCATE CUR_VENDA

		END
		FETCH NEXT FROM CUR_TOT INTO @DT_PREGAO_COMPROU, @CD_CLIENTE_COMPROU, @CD_NEGOCIO_COMPROU, @COMPRA, @VENDA

		END
		CLOSE CUR_TOT
		DEALLOCATE CUR_TOT



	 



	/************************************
	##### INSERT ST_DAYTRADE_RESUMO #####
	*************************************/
	 

		DELETE ST_DAYTRADE_RESUMO WHERE DT_PREGAO_COMPROU = @PREGAO
	
		INSERT INTO ST_DAYTRADE_RESUMO
		(
		CD_CLIENTE_COMPROU,VL_COMPRA,VL_VENDA,VL_FINANC,DT_PREGAO_COMPROU
		,QT_CONTRAPARTES,DT_PRIMEIRA_OPER
		)
		SELECT 
			CD_CLIENTE_COMPROU, 
			SUM(COMP) AS VL_COMPRA, 
			SUM(VEND) AS VL_VENDA,
			SUM(VEND)-SUM(COMP) AS VL_FINANC,
			DT_PREGAO_COMPROU, 
			NULL AS QT_CONTRAPARTES,
			NULL AS DT_PRIMEIRA_OPER

		FROM ( 
			SELECT 
				DT_PREGAO_COMPROU, 
				CD_CLIENTE_COMPROU,
				(CASE WHEN CD_NATOPE = 'C' THEN QT_DAYTRADE ELSE 0 END * VL_NEGOCIO_COMPROU) COMP,
				(CASE WHEN CD_NATOPE = 'V' THEN QT_DAYTRADE ELSE 0 END * VL_NEGOCIO_COMPROU) VEND
			FROM ST_DAYTRADE_DETALHE
			WHERE QT_DAYTRADE > 0  
		) X
		WHERE DT_PREGAO_COMPROU = @PREGAO
		GROUP BY DT_PREGAO_COMPROU, CD_CLIENTE_COMPROU

	 

	/*******************
	##### UPDATES #####
	*******************/
	 

		UPDATE ST_DAYTRADE_RESUMO 
		SET QT_CONTRAPARTES = (SELECT SUM(QTD) 
								FROM(
									SELECT 
										CD_NEGOCIO_COMPROU,
										COUNT(DISTINCT A.CD_CLIENTE_COMPROU_DE) QTD 
									FROM ST_DAYTRADE_DETALHE A
									WHERE 
										A.CD_CLIENTE_COMPROU = ST_DAYTRADE_RESUMO.CD_CLIENTE_COMPROU 
									AND A.DT_PREGAO_COMPROU = ST_DAYTRADE_RESUMO.DT_PREGAO_COMPROU 
									AND QT_DAYTRADE IS NOT NULL
									AND A.CD_CLIENTE_COMPROU_DE IS NOT NULL
									GROUP BY CD_NEGOCIO_COMPROU
									) X
								)
		WHERE DT_PREGAO_COMPROU = @PREGAO
		--
		--
		UPDATE ST_DAYTRADE_RESUMO 
		SET DT_PRIMEIRA_OPER = (SELECT MIN(A.DT_PREGAO_COMPROU) 
								FROM ST_DAYTRADE_RESUMO A
								WHERE A.CD_CLIENTE_COMPROU = ST_DAYTRADE_RESUMO.CD_CLIENTE_COMPROU)
		WHERE DT_PREGAO_COMPROU = @PREGAO



SET @PREGAO = @PREGAO +1

END	

-- ================================================
-- Marca DT_FIRA para registros carregados (fallback)
-- ================================================
DECLARE @__dt_fira_now DATETIME = GETDATE();
IF COL_LENGTH(N'dbo.ST_DAYTRADE_RESUMO', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE [dbo].[ST_DAYTRADE_RESUMO]
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL;
END


/******* fim do processo de carga **********/

--passo 3
/***** limpa a tabela do banco para nao ficar sujeira ******/
DROP TABLE IF EXISTS ST_DAYTRADE_RESUMO_PADRAO