CREATE PROCEDURE [dbo].[ATUALIZARSCORETRANSACIONAL]
(
	@USUARIO INT, 
	@PATRIMONIO_MOVCC TINYINT,@PATRIMONIO_NETTING TINYINT,@PATRIMONIO_TRANSF_CUST TINYINT,
    @SWING_BOVESPA TINYINT, @SWING_BMF TINYINT, @DAYTRADE_BOVESPA_01 TINYINT, @DAYTRADE_BMF_01 TINYINT, @MUDANCA_REPENTINA TINYINT,
    @MEDIA_BOVESPA_01 TINYINT, @MEDIA_BMF_01 TINYINT, @AML_BOVESPA TINYINT, @AML_BMF TINYINT,@AMLCORRETORABOVESPA TINYINT, @AMLCORRETORABMF TINYINT,
	@OMC_BOVESPA TINYINT,@OMC_BMF TINYINT,@ATUALIZACAO_CADASTRAL TINYINT,@PROCURADOR TINYINT,@SPOOFING_01 TINYINT , @LAYERING_01 TINYINT,
    @INSIDER_TRADING_BOVESPA TINYINT, @TRANSFERENCIA_FINANCEIRA_01 TINYINT, @TRANSFERENCIA_FINANCEIRA_02 TINYINT,@CHURNING_01 TINYINT
)
--WITH ENCRYPTION
AS

--DECLARE
--@USUARIO INT , 
--	@PATRIMONIO_MOVCC TINYINT,@PATRIMONIO_NETTING TINYINT,@PATRIMONIO_TRANSF_CUST TINYINT,
--    @SWING_BOVESPA TINYINT, @SWING_BMF TINYINT, @DAYTRADE_BOVESPA_01 TINYINT, @DAYTRADE_BMF_01 TINYINT, @MUDANCA_REPENTINA TINYINT,
--    @MEDIA_BOVESPA_01 TINYINT, @MEDIA_BMF_01 TINYINT, @AML_BOVESPA TINYINT, @AML_BMF TINYINT,@AMLCORRETORABOVESPA TINYINT, @AMLCORRETORABMF TINYINT,
--	@OMC_BOVESPA TINYINT,@OMC_BMF TINYINT,@ATUALIZACAO_CADASTRAL TINYINT,@PROCURADOR TINYINT,@SPOOFING_01 TINYINT , @LAYERING_01 TINYINT,
--    @INSIDER_TRADING_BOVESPA TINYINT, @TRANSFERENCIA_FINANCEIRA_01 TINYINT, @TRANSFERENCIA_FINANCEIRA_02 TINYINT,@CHURNING_01 TINYINT

--set @usuario = 1
--set @PATRIMONIO_MOVCC = 5 set @PATRIMONIO_NETTING = 5 set @PATRIMONIO_TRANSF_CUST = 5
--set @SWING_BOVESPA = 5 set  @SWING_BMF = 5 set  @DAYTRADE_BOVESPA_01 = 5  set @DAYTRADE_BMF_01 = 5 set  @MUDANCA_REPENTINA = 5
--set @MEDIA_BOVESPA_01 = 5 set  @MEDIA_BMF_01 = 5 set  @AML_BOVESPA = 5  set @AML_BMF = 5 set @AMLCORRETORABOVESPA = 5 set @AMLCORRETORABMF = 5
--set @OMC_BOVESPA = 5 set @OMC_BMF = 5 set @ATUALIZACAO_CADASTRAL = 5 set @PROCURADOR = 5 set @SPOOFING_01 = 5   set @LAYERING_01 = 5
--set @INSIDER_TRADING_BOVESPA = 5 set  @TRANSFERENCIA_FINANCEIRA_01 = 15 set  @TRANSFERENCIA_FINANCEIRA_02 = 5 set @CHURNING_01 = 5

BEGIN
 

	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'PATRIMONIO_MOVCC')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('PATRIMONIO_MOVCC', 'TRANSACIONAL', @PATRIMONIO_MOVCC, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @PATRIMONIO_MOVCC
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'PATRIMONIO_MOVCC'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'PATRIMONIO_NETTING')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('PATRIMONIO_NETTING', 'TRANSACIONAL', @PATRIMONIO_NETTING, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @PATRIMONIO_NETTING
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'PATRIMONIO_NETTING'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'PATRIMONIO_TRANSF_CUST')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('PATRIMONIO_TRANSF_CUST', 'TRANSACIONAL', @PATRIMONIO_TRANSF_CUST, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @PATRIMONIO_TRANSF_CUST
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'PATRIMONIO_TRANSF_CUST'
	END



	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'ATUALIZACAO_CADASTRAL')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('ATUALIZACAO_CADASTRAL', 'TRANSACIONAL', @ATUALIZACAO_CADASTRAL, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @ATUALIZACAO_CADASTRAL 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'ATUALIZACAO_CADASTRAL'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'SWING_BOVESPA')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('SWING_BOVESPA', 'TRANSACIONAL', @SWING_BOVESPA, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @SWING_BOVESPA 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'SWING_BOVESPA'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'SWING_BMF')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('SWING_BMF', 'TRANSACIONAL', @SWING_BMF, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @SWING_BMF 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'SWING_BMF'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'DAYTRADE_BOVESPA_01')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('DAYTRADE_BOVESPA_01', 'TRANSACIONAL', @DAYTRADE_BOVESPA_01, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @DAYTRADE_BOVESPA_01 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'DAYTRADE_BOVESPA_01'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'DAYTRADE_BMF_01')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('DAYTRADE_BMF_01', 'TRANSACIONAL', @DAYTRADE_BMF_01, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @DAYTRADE_BMF_01 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'DAYTRADE_BMF_01'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'MUDANCA_REPENTINA')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('MUDANCA_REPENTINA', 'TRANSACIONAL', @MUDANCA_REPENTINA, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @MUDANCA_REPENTINA 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'MUDANCA_REPENTINA'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'MEDIA_BOVESPA_01')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('MEDIA_BOVESPA_01', 'TRANSACIONAL', @MEDIA_BOVESPA_01, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @MEDIA_BOVESPA_01 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'MEDIA_BOVESPA_01'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'MEDIA_BMF_01')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('MEDIA_BMF_01', 'TRANSACIONAL', @MEDIA_BMF_01, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @MEDIA_BMF_01 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'MEDIA_BMF_01'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'AML_BOVESPA')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('AML_BOVESPA', 'TRANSACIONAL', @AML_BOVESPA, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @AML_BOVESPA 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'AML_BOVESPA'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'AML_BMF')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('AML_BMF', 'TRANSACIONAL', @AML_BMF, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @AML_BMF 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'AML_BMF'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'AMLCORRETORABOVESPA')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('AMLCORRETORABOVESPA', 'TRANSACIONAL', @AMLCORRETORABOVESPA, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @AMLCORRETORABOVESPA 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'AMLCORRETORABOVESPA'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'AMLCORRETORABMF')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('AMLCORRETORABMF', 'TRANSACIONAL', @AMLCORRETORABMF, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @AMLCORRETORABMF 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'AMLCORRETORABMF'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'OMC_BOVESPA')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('OMC_BOVESPA', 'TRANSACIONAL', @OMC_BOVESPA, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @OMC_BOVESPA 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'OMC_BOVESPA'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'OMC_BMF')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('OMC_BMF', 'TRANSACIONAL', @OMC_BMF, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @OMC_BMF
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'OMC_BMF'
	END

	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'INSIDER_TRADING_BOVESPA')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('INSIDER_TRADING_BOVESPA', 'TRANSACIONAL', @INSIDER_TRADING_BOVESPA, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @INSIDER_TRADING_BOVESPA 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'INSIDER_TRADING_BOVESPA'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'LAYERING_01')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('LAYERING_01', 'TRANSACIONAL', @LAYERING_01, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @LAYERING_01 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'LAYERING_01'
	END

	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'SPOOFING_01')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('SPOOFING_01', 'TRANSACIONAL', @SPOOFING_01, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @SPOOFING_01 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'SPOOFING_01'
	END

	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'CHURNING_01')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('CHURNING_01', 'TRANSACIONAL', @CHURNING_01, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @CHURNING_01 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'CHURNING_01'
	END

	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'PROCURADOR')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('PROCURADOR', 'TRANSACIONAL', @PROCURADOR, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @PROCURADOR
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'PROCURADOR'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'TRANSFERENCIA_FINANCEIRA_01')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('TRANSFERENCIA_FINANCEIRA_01', 'TRANSACIONAL', @TRANSFERENCIA_FINANCEIRA_01, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @TRANSFERENCIA_FINANCEIRA_01 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'TRANSFERENCIA_FINANCEIRA_01'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'TRANSFERENCIA_FINANCEIRA_02')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('TRANSFERENCIA_FINANCEIRA_02', 'TRANSACIONAL', @TRANSFERENCIA_FINANCEIRA_02, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @TRANSFERENCIA_FINANCEIRA_02 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'TRANSFERENCIA_FINANCEIRA_02'
	END

	--
	 

	--TOTAL
	SELECT TIPO, SUM(PESO)PESO_TOTAL
	INTO #TOTAL
	FROM PORTALCONFIGSCORE
	WHERE TIPO ='TRANSACIONAL'
	GROUP BY TIPO

	--TRUNCATE TABLE ST_SCORE

	--INSERT INTO ST_SCORE
	--SELECT A.TIPO,
	--CASE WHEN A.ITEM = 'TRANSFERENCIA_FINANCEIRA_01'		THEN 'TRANSFERENCIA_FINANCEIRA_01'  
 --        WHEN A.ITEM = 'TRANSFERENCIA_FINANCEIRA_02'		THEN 'TRANSFERENCIA_FINANCEIRA_02'  
 --        WHEN A.ITEM = 'ATUALIZACAO_CADASTRAL'	THEN 'ATUALIZACAO_CADASTRAL'  
 --        WHEN A.ITEM = 'PROCURADOR'		    THEN 'PROCURADOR'  
 --        WHEN A.ITEM = 'PATRIMONIO_MOVIMENTO'	THEN 'PATRIMONIO_MOVCC'  
 --        WHEN A.ITEM = 'PATRIMONIO_NETTING'	THEN 'PATRIMONIO_NETTING'  
 --        WHEN A.ITEM = 'PATRIMONIO_TRANF_CUST'THEN 'PATRIMONIO_TRANSF_CUST'   
 --        WHEN A.ITEM = 'SWING_BOVESPA'	THEN 'SWING_BOVESPA'   
 --        WHEN A.ITEM = 'SWING_BMF'		THEN 'SWING_BMF'  
 --        WHEN A.ITEM = 'DAYTRADE_BOVESPA_01'		THEN 'DAYTRADE_BOVESPA_01'   
 --        WHEN A.ITEM = 'DAYTRADE_BMF_01'			THEN 'DAYTRADE_BMF_01'    
 --        WHEN A.ITEM = 'MUDANCA_REPENTINA'		THEN 'MUDANCA_REPENTINA'  
 --        WHEN A.ITEM = 'MEDIA_BOVESPA_01'			THEN 'MEDIA_BOVESPA_01'   
 --        WHEN A.ITEM = 'MEDIA_BMF_01'				THEN 'MEDIA_BMF_01' 
 --        WHEN A.ITEM = 'AML_BOVESPA'			THEN 'AML_BOVESPA'  
 --        WHEN A.ITEM = 'AML_BMF'				THEN 'AML_BMF'
	--	 WHEN A.ITEM = 'AMLCORRETORABOVESPA'			THEN 'AMLCORRETORABOVESPA'  
 --        WHEN A.ITEM = 'AMLCORRETORABMF'				THEN 'AMLCORRETORABMF'  
 --        WHEN A.ITEM = 'OMC_BOVESPA'				    THEN 'OMC_BOVESPA'  
 --        WHEN A.ITEM = 'OMC_BMF'				    THEN 'OMC_BMF'  
 --        WHEN A.ITEM = 'INSIDER_TRADING_BOVESPA'			THEN 'INSIDER_TRADING_BOVESPA'  
 --        WHEN A.ITEM = 'CHURNING_01'			    THEN 'CHURNING_01'   
	--	 WHEN A.ITEM = 'LAYERING_01'			    THEN 'LAYERING_01' 
	--	 WHEN A.ITEM = 'SPOOFING_01'			    THEN 'SPOOFING_01' 
	--     ELSE A.ITEM END ITEM,

	--PESO,B.PESO_TOTAL,
	--(CAST(PESO AS FLOAT) / CAST(B.PESO_TOTAL AS FLOAT)) * 100 AS AJUSTE

	--FROM PORTALCONFIGSCORE A
	--LEFT OUTER JOIN #TOTAL B 
	--ON A.TIPO = B.TIPO
	
	--WHERE A.TIPO  = 'TRANSACIONAL'
 
	DROP TABLE #TOTAL
END