CREATE PROCEDURE [dbo].[PR_OBTERFILTROS]
(
	@PROCEDURE NVARCHAR(MAX)
)
--WITH ENCRYPTION
AS
BEGIN
    SELECT  
   'PARAMETER_NAME' = NAME,  
   'TYPE'   = TYPE_NAME(USER_TYPE_ID),  
   'LENGTH'   = MAX_LENGTH,  
   'PREC'   = CASE WHEN TYPE_NAME(SYSTEM_TYPE_ID) = 'UNIQUEIDENTIFIER' 
              THEN PRECISION  
              ELSE ODBCPREC(SYSTEM_TYPE_ID, MAX_LENGTH, PRECISION) END,  
   'SCALE'   = ODBCSCALE(SYSTEM_TYPE_ID, SCALE),  
   'PARAM_ORDER'  = PARAMETER_ID,  
   'COLLATION'   = CONVERT(SYSNAME, 
                   CASE WHEN SYSTEM_TYPE_ID IN (35, 99, 167, 175, 231, 239)  
                   THEN SERVERPROPERTY('COLLATION') END)  

  FROM SYS.PARAMETERS WHERE OBJECT_ID = OBJECT_ID(@PROCEDURE)
END