CREATE PROCEDURE [dbo].[PR_SWINGTRADE_PAPEL]  @INICIO SMALLDATETIME,@FIM SMALLDATETIME, @CD_CLIENTE VARCHAR(160),@CD_PAPEL VARCHAR(50),@QTDPORPAGINA INT,@PAGINA INT
--WITH ENCRYPTION
AS

--DECLARE @PAGINA        INT 
--DECLARE @QTDPORPAGINA INT 
--DECLARE @INICIO SMALLDATETIME,@FIM SMALLDATETIME, @CD_CLIENTE VARCHAR(160),@CD_PAPEL VARCHAR(50)
--SET @INICIO ='20230101'
--SET @FIM ='20230331'
--SET @CD_CLIENTE =''



--SELECT V.CD_CLIENTE,CD_PAPEL,
SELECT 
FORMAT(STB.PREGAO_ANT,'d','pt-br')[DATA PREGÃO ANT.],
FORMAT(STB.PREGAO,'d','pt-br')[DATA PREGÃO],
STB.CD_CLIENTE [CÓD. CLIENTE],
V.NM_CLIENTE [NOME DO CLIENTE],
PAPEL [ATIVO],
FORMAT(SUM(QTD_SWINGTRADE),'#,0','PT-BR') AS [QTD. SWINGTRADE],
SUM(CASE WHEN RESULTADO >0 THEN 1 ELSE 0 END ) [ACERTO],
SUM(CASE WHEN RESULTADO <0 THEN 1 ELSE 0 END ) [PERDA],
SUM(CASE WHEN RESULTADO =0 THEN 1 ELSE 0 END ) [EMPATE],
FORMAT(SUM(RESULTADO),'f','pt-br') RESULTADO
--, FORMAT(SUM(),'f','pt-br') FINANCEIRO
FROM ST_SWINGTRADE_BOVESPA STB 
LEFT OUTER JOIN V_CLIENTE_TODOS V
ON STB.CD_CLIENTE = V.CD_CLIENTE

WHERE PREGAO >= @INICIO AND PREGAO <= @FIM
AND  STB.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN STB.CD_CLIENTE ELSE @CD_CLIENTE END
AND  STB.PAPEL = CASE WHEN ISNULL(@CD_PAPEL,'') = '' THEN STB.PAPEL ELSE @CD_PAPEL END

GROUP BY STB.PREGAO,STB.PREGAO_ANT,STB.CD_CLIENTE,  V.NM_CLIENTE, PAPEL

ORDER BY 3
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;