CREATE PROCEDURE [dbo].[PR_SWINGTRADE_PAPEL_BMF]  @INICIO SMALLDATETIME,@FIM SMALLDATETIME, @CD_CLIENTE VARCHAR(160),@CD_COMMOD VARCHAR(10), @CD_SERIE VARCHAR(10),@QTDPORPAGINA INT,@PAGINA INT  
--WITH ENCRYPTION  
AS  
  
--DECLARE @PAGINA        INT 
--DECLARE @QTDPORPAGINA INT 
--DECLARE @INICIO SMALLDATETIME,@FIM SMALLDATETIME, @CD_CLIENTE VARCHAR(160),@CD_COMMOD VARCHAR(10), @CD_SERIE VARCHAR(10)  
--SET @INICIO ='20240201'  
--SET @FIM ='20240229'  
--SET @CD_CLIENTE =''  
--SET @CD_COMMOD =''  
--SET @CD_SERIE =''  
  
  SELECT  
format(ST_SWINGTRADE_BMF.PREGAO_ANT,'d','pt-br') AS[PREGÃO ANT.],  
format(ST_SWINGTRADE_BMF.PREGAO,'d','pt-br') AS [PREGÃO],  
ST_SWINGTRADE_BMF.CD_CLIENTE [CÓD. CLIENTE],   
V.NM_CLIENTE [NOME DO CLIENTE],  
CD_COMMOD [COMMOD],  
CD_SERIE [SÉRIE],  
SUM(QTD_SWINGTRADE) [QTD. SWINGTRADE] ,   
SUM(CASE WHEN RESULTADO > 0 THEN 1 ELSE 0 END) [ACERTO],  
SUM(CASE WHEN RESULTADO < 0 THEN 1 ELSE 0 END) [PERDA],   
SUM(CASE WHEN RESULTADO = 0 THEN 1 ELSE 0 END) [EMPATE],   
FORMAT(SUM(RESULTADO),'f','pt-br') AS [RESULTADO FINANCEIRO],  
FORMAT(SUM(FINANCEIRO),'f','pt-br') [RESULTADO FINANCEIRO TOTAL]  
  
FROM ST_SWINGTRADE_BMF   
LEFT OUTER JOIN  V_CLIENTE_TODOS V ON ST_SWINGTRADE_BMF.CD_CLIENTE =V.CD_CLIENTE  
  
WHERE PREGAO >=@INICIO AND PREGAO <=@FIM  
AND ST_SWINGTRADE_BMF.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN ST_SWINGTRADE_BMF.CD_CLIENTE ELSE @CD_CLIENTE END  
AND ST_SWINGTRADE_BMF.CD_COMMOD = CASE WHEN ISNULL(@CD_COMMOD,'') = '' THEN ST_SWINGTRADE_BMF.CD_COMMOD ELSE @CD_COMMOD END  
AND ST_SWINGTRADE_BMF.CD_SERIE = CASE WHEN ISNULL(@CD_SERIE,'') = '' THEN ST_SWINGTRADE_BMF.CD_SERIE ELSE @CD_SERIE END  
GROUP BY   
ST_SWINGTRADE_BMF.PREGAO_ANT,ST_SWINGTRADE_BMF.PREGAO,  
ST_SWINGTRADE_BMF.CD_CLIENTE, V.NM_CLIENTE,CD_COMMOD, CD_SERIE  
  
ORDER BY 1  
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS  
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;