CREATE PROCEDURE [dbo].[PR_DEPOSITOS_E_RETIRADAS] @INICIO SMALLDATETIME, @FIM SMALLDATETIME, @CD_CLIENTE VARCHAR(160),@QTDPORPAGINA INT,@PAGINA INT		
--WITH ENCRYPTION
AS		
		
--DECLARE @INICIO SMALLDATETIME, @FIM SMALLDATETIME, @CD_CLIENTE VARCHAR(10),@QTDPORPAGINA INT = 100, @PAGINA       INT = 1		
--SET @INICIO = '20251201'		
--SET @FIM = '20251231'		
--SET @CD_CLIENTE =''	
		
SELECT 
FORMAT(DT_REFERENCIA,'d','pt-br')DT_REFERENCIA, 
A.CD_CLIENTE,NM_CLIENTE, 
FORMAT(SUM(A.DEPOSITO),'f','pt-br') DEPOSITO, 
FORMAT(SUM(A.RETIRADA),'f','pt-br') RETIRADA
FROM(		
	SELECT DT_REFERENCIA,CD_CLIENTE,NM_CLIENTE, SUM(CAST(VL_LANCAMENTO AS FLOAT)) DEPOSITO, 0 RETIRADA		
	FROM ST_EXTRATO_CC		
	WHERE DT_REFERENCIA >= @INICIO AND DT_REFERENCIA <= @FIM		
	AND CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'')='' THEN CD_CLIENTE ELSE CAST(@CD_CLIENTE AS INT) END		
	AND CD_HISTORICO IN (SELECT CD_PARAMETRO FROM ST_CLIENTE_PARAMETROS WHERE DS_PARAMETRO = 'DEPOSITO') --DEPÓSITO		
	GROUP BY DT_REFERENCIA,CD_CLIENTE,NM_CLIENTE		
		
	UNION  		
		
	SELECT DT_REFERENCIA,CD_CLIENTE,NM_CLIENTE, 0 DEPOSITO, SUM(CAST(VL_LANCAMENTO AS FLOAT)) RETIRADA		
	FROM ST_EXTRATO_CC		
	WHERE DT_REFERENCIA >= @INICIO AND DT_REFERENCIA <= @FIM		
	AND CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'')='' THEN CD_CLIENTE ELSE CAST(@CD_CLIENTE AS INT) END		
	AND CD_HISTORICO  IN (SELECT CD_PARAMETRO FROM ST_CLIENTE_PARAMETROS WHERE DS_PARAMETRO = 'RETIRADA') --RETIRADA	
	GROUP BY DT_REFERENCIA,CD_CLIENTE,NM_CLIENTE		
)A
		
GROUP BY DT_REFERENCIA,A.CD_CLIENTE,NM_CLIENTE		
 		
ORDER BY 1		
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
 FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;