CREATE PROCEDURE [dbo].[PR_DIRETAS_BVSP] --'2009-01-01','2010-01-12','JOAQUIM CARNEIRO BARBOSA',''		
(		
	@INICIO DATETIME,		
	@FIM DATETIME,		
    @CD_CLIENTE_COMPRA VARCHAR(160),		
    @CD_CLIENTE_VENDA VARCHAR(160),
	@QTDPORPAGINA INT, @PAGINA INT
		
		
    --@CD_ASSESSOR_COMPRA VARCHAR(10),		
    --@CD_ASSESSOR_VENDA VARCHAR(10),		
    --@VINCULADO_COMPRA CHAR(01),		
    --@VINCULADO_VENDA CHAR(01),		
    --@CD_PAPEL VARCHAR(10),		
    --@TP_CLIENTE_COMPRA INT,		
    --@TP_CLIENTE_VENDA INT		
)		--WITH ENCRYPTION
		
AS		
/*
Atualizações
04/09/2024 - 16h24 - Author: Guimo
Ajuste na coluna Volume Venda, estava multiplicando por compra ao inves de venda.
*/	

--DECLARE @PAGINA        INT = 1;


--DECLARE @QTDPORPAGINA INT = 5
		
--DECLARE @INICIO DATETIME,		
--	@FIM DATETIME,		
--    @CD_CLIENTE_COMPRA VARCHAR(160),		
--    @CD_CLIENTE_VENDA VARCHAR(160)		
		
--SET @INICIO ='2024-07-01'		
--SET	@FIM='2024-07-31'		
--SET @CD_CLIENTE_COMPRA= '831508'		
--SET @CD_CLIENTE_VENDA='529685'			
		
SELECT [CD_CLIENTE_COMPRA]	[COD. CLIENTE]	
      ,[NM_CLIENTE_COMPRA]	[NOME CLIENTE]
      ,[VINC_COMPRA]		[VINCULADO COMPRA]	
      ,[CD_CLIENTE_VENDA]	[COD. CLIENTE PONTA]		
      ,[NM_CLIENTE_VENDA]	[NOME CLIENTE PONTA]
      ,[VINC_VENDA]			[VINCULADO VENDA]
      ,FORMAT([DT_PERIODO],'d','pt-br') [DATA]		
      --,[SISTEMA_COMPRA]		[SISTEMA COMPRA]
      --,[SISTEMA_VENDA]		[SISTEMA VENDA]
      ,[NR_NEGOCIO]			[NR NEGOCIO]
      ,FORMAT(CASE WHEN ([QT_NEGOCIO_COMPRA])> ([QT_NEGOCIO_VENDA]) THEN ([QT_NEGOCIO_VENDA]) ELSE  [QT_NEGOCIO_COMPRA] END,'#,0','PT-BR') [QTD. NEGOCIO COMPRA]		
      ,FORMAT(CASE WHEN ([QT_NEGOCIO_COMPRA])> ([QT_NEGOCIO_VENDA]) THEN ([QT_NEGOCIO_VENDA]) ELSE  [QT_NEGOCIO_COMPRA] END,'#,0','PT-BR') [QTD. NEGOCIO VENDA]		
      ,[CD_PAPEL]	[ATIVO]																									   
      ,[HH_COMPRA]		[HH COMPRA]
      ,[HH_VENDA]		[HH VENDA]
      ,FORMAT(CASE WHEN ([QT_NEGOCIO_COMPRA])> ([QT_NEGOCIO_VENDA]) THEN ([QT_NEGOCIO_VENDA]) ELSE  [QT_NEGOCIO_COMPRA] END * ([VL_NEGOCIO_COMPRA]),'f','pt-br') [VOLUME COMPRA]		
      ,FORMAT(CASE WHEN ([QT_NEGOCIO_COMPRA])> ([QT_NEGOCIO_VENDA]) THEN ([QT_NEGOCIO_VENDA]) ELSE  [QT_NEGOCIO_COMPRA] END * ([VL_NEGOCIO_VENDA]),'f','pt-br') [VOLUME VENDA]		
      ,FORMAT([VL_NEGOCIO_COMPRA],'f','pt-br') [PREÇO COMPRA]		
      ,FORMAT([VL_NEGOCIO_VENDA],'f','pt-br') [PREÇO VENDA]		
      ,[CD_ASSESSOR_COMPRA]		[COD. ASSESSOR COMPRA]
      ,[DS_ASSESSOR_COMPRA]		[ASSESSOR COMPRA]
      ,[CD_ASSESSOR_VENDA]		[COD. ASSESSOR VENDA]
      ,[DS_ASSESSOR_VENDA]		[ASSESSOR VENDA],		
         CD_OPERADOR_COMPRA [COD. OPERADOR COMPRA],		
         DS_OPERADOR_COMPRA [OPERADOR COMPRA],		
         CD_OPERADOR_VENDA  [COD. OPERADOR VENDA],		
         DS_OPERADOR_VENDA  [OPERADOR VENDA], 
		 CD_CLIENTE_BRO_VENDA [COD. BROKER COMPRA], 
		 CD_CLIENTE_BRO_COMPRA [COD. BROKER VENDA],
		 
CASE WHEN CD_CLIENTE_BRO_VENDA = CD_CLIENTE_BRO_COMPRA THEN 'SIM' ELSE 'NÃO' END [BROKER],		
          DS_TP_CLIENTE_COMPRA [TIPO CLIENTE COMPRA], DS_TP_CLIENTE_VENDA		 [TIPO CLIENTE VENDA]
  FROM [ST_DIRETAS_BVSP]		
  WHERE 		
   CD_CLIENTE_COMPRA <> CD_CLIENTE_VENDA --ADICIONADO ZE COM ZE 26-MAY-2011		
  AND DT_PERIODO >=@INICIO AND DT_PERIODO<=@FIM 		
  AND CD_CLIENTE_COMPRA = (CASE WHEN ISNULL(@CD_CLIENTE_COMPRA,'') = '' THEN CD_CLIENTE_COMPRA ELSE @CD_CLIENTE_COMPRA END)		
  AND CD_CLIENTE_VENDA = (CASE WHEN ISNULL(@CD_CLIENTE_VENDA,'') = '' THEN CD_CLIENTE_VENDA ELSE @CD_CLIENTE_VENDA END)		
		
--AND CD_ASSESSOR_COMPRA = (CASE WHEN @CD_ASSESSOR_COMPRA = '' THEN CD_ASSESSOR_COMPRA ELSE CONVERT(INT,@CD_ASSESSOR_COMPRA) END)		
--AND CD_ASSESSOR_VENDA = (CASE WHEN @CD_ASSESSOR_VENDA = '' THEN CD_ASSESSOR_VENDA ELSE CONVERT(INT,@CD_ASSESSOR_VENDA) END)		
--AND CD_PAPEL = (CASE WHEN @CD_PAPEL = '' THEN CD_PAPEL ELSE @CD_PAPEL END)		
--AND VINC_COMPRA = (CASE WHEN ISNULL(@VINCULADO_COMPRA,'') = '' THEN VINC_COMPRA ELSE @VINCULADO_COMPRA END)		
--AND VINC_VENDA = (CASE WHEN ISNULL(@VINCULADO_VENDA,'')='' THEN VINC_VENDA ELSE @VINCULADO_VENDA END)		
--AND TP_CLIENTE_COMPRA = CASE WHEN ISNULL(@TP_CLIENTE_COMPRA,'')='' THEN TP_CLIENTE_COMPRA ELSE @VINCULADO_COMPRA END		
--AND TP_CLIENTE_VENDA = CASE WHEN ISNULL(@TP_CLIENTE_VENDA,'')='' THEN TP_CLIENTE_VENDA ELSE @TP_CLIENTE_VENDA END	--0M5	
 
 
  ORDER BY 1		
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;