CREATE PROCEDURE [dbo].[PR_DAYTRADE_PAPEL] @INICIO SMALLDATETIME, @FIM SMALLDATETIME, @CD_CLIENTE VARCHAR(160), @CD_PAPEL VARCHAR(100), @QTDPORPAGINA INT, @PAGINA INT  
WITH RECOMPILE  
AS    
  
--DECLARE @QTDPORPAGINA INT ,        @PAGINA       INT ;  
--DECLARE  @INICIO SMALLDATETIME, @FIM SMALLDATETIME, @CD_CLIENTE INT , @CD_PAPEL VARCHAR (100)   
--SET @INICIO = '20250201'
--SET @FIM = '20250228'
--SET @CD_CLIENTE = '4587867'
--SET @CD_PAPEL = ''  
    

--TODOS DAYTRADES POR PAPEL E DIA  
drop table if exists #T1 ;
SELECT DT_PREGAO_COMPROU DT_PREGAO,     
CD_CLIENTE_COMPROU CD_CLIENTE,CD_NEGOCIO_COMPROU CD_NEGOCIO,     
SUM((CASE WHEN CD_NATOPE = 'C' THEN -1 ELSE 1 END) *QT_DAYTRADE*VL_NEGOCIO_COMPROU)  VL_ACERTO   
  into   #T1 
FROM ST_DAYTRADE_DETALHE    
WHERE DT_PREGAO_COMPROU >= @INICIO    
AND DT_PREGAO_COMPROU <= @FIM    
and QT_DAYTRADE > 0
GROUP BY DT_PREGAO_COMPROU, CD_CLIENTE_COMPROU, CD_NEGOCIO_COMPROU   
    

--ACERTO POR PAPEL   
drop table if exists #T3 ;
SELECT CD_CLIENTE, CD_NEGOCIO ,    
SUM(CASE WHEN VL_ACERTO > 0 THEN 1 ELSE 0 END) VL_ACERTO,    
SUM(CASE WHEN VL_ACERTO < 0 THEN 1 ELSE 0 END) VL_PERDA,    
SUM(CASE WHEN VL_ACERTO = 0 THEN 1 ELSE 0 END) VL_EMPATE,    
SUM(VL_ACERTO) VL_FINAN   
into #T3 
FROM #T1    
GROUP BY CD_CLIENTE, CD_NEGOCIO 

--FINANCEIRO TOTAL   
drop table if exists #T2 ;
SELECT CD_CLIENTE,     
SUM(VL_ACERTO) VL_FINAN  into #T2 
FROM #T1    
GROUP BY CD_CLIENTE  

-- QUERY FINAL   
SELECT   
format(@INICIO,'d','pt-br') [DATA INÍCIO],  
format(@fim,'d','pt-br') [DATA FIM],  
 T3.CD_CLIENTE AS [CÓD. CLIENTE],    
 (SELECT MAX(NM_CLIENTE) FROM V_CLIENTE_TODOS VV   
 WHERE VV.CD_CLIENTE = T2.CD_CLIENTE) [NOME DO CLIENTE],  
 T3.CD_NEGOCIO [ATIVO],  
 FORMAT(T3.VL_FINAN,'f','pt-br') [RESULTADO FINANCEIRO],    
 FORMAT(T2.VL_FINAN,'f','pt-br') [RESULTADO FINANCEIRO TOTAL],  
 T3.VL_ACERTO [ACERTO] ,    
 T3.VL_EMPATE [EMPATE],    
 T3.VL_PERDA  [PERDA],    
FORMAT((CAST(T3.VL_ACERTO AS FLOAT) / (CAST(T3.VL_ACERTO AS FLOAT) + CAST(T3.VL_EMPATE AS FLOAT) + CAST(T3.VL_PERDA AS FLOAT))), 'P2') [PERC. ACERTO] ,    
FORMAT((CAST(T3.VL_PERDA AS FLOAT) / NULLIF((CAST(T3.VL_ACERTO AS FLOAT) + CAST(T3.VL_EMPATE AS FLOAT) + CAST(T3.VL_PERDA AS FLOAT)), 0)), 'P2') [PERC. PERDA]
  
     
FROM #T2 T2, #T3 T3  
    
WHERE     
T2.CD_CLIENTE = T3.CD_CLIENTE   
AND T3.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'')='' THEN T3.CD_CLIENTE ELSE @CD_CLIENTE END    
AND T3.CD_NEGOCIO = CASE WHEN ISNULL(@CD_PAPEL,'')='' THEN T3.CD_NEGOCIO ELSE  @CD_PAPEL END      
--GROUP BY T3.CD_CLIENTE, T3.NM_CLIENTE,T3.CD_NEGOCIO,T2.ACERTO    
  
  
ORDER BY 1    
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS  
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;  
   
    
---------------------------------