CREATE PROCEDURE [dbo].[PR_DIRETAS_BMF] --'2009-01-01','2010-01-12','JOAQUIM CARNEIRO BARBOSA',''		
(		
	@INICIO DATETIME,		
	@FIM DATETIME,		
    @CD_CLIENTE_COMPRA VARCHAR(160),		
    @CD_CLIENTE_VENDA VARCHAR(160)	,
	@QTDPORPAGINA INT,
    @PAGINA INT	
)		
--WITH ENCRYPTION
AS	

--DECLARE @PAGINA        INT = 1;


--DECLARE @QTDPORPAGINA INT = 5
	
--DECLARE @INICIO DATETIME,		
--	@FIM DATETIME,		
--    @CD_CLIENTE_COMPRA VARCHAR(160),		
--    @CD_CLIENTE_VENDA VARCHAR(160)		
		
--SET @INICIO ='20200424'		
--SET	@FIM ='20200424'		
--SET @CD_CLIENTE_COMPRA =''		
--SET @CD_CLIENTE_VENDA=''		
		
		
		
		
SELECT [CD_CLIENTE_COMPRA]		[COD. CLIENTE]
      ,[NM_CLIENTE_COMPRA]		[NOME CLIENTE]	
      ,[VINC_COMPRA]			[VINCULADO COMPRA]	
      ,[CD_CLIENTE_VENDA]		[COD. CLIENTE PONTA]	
      ,[NM_CLIENTE_VENDA]		[NOME CLIENTE PONTA]		
      ,[VINC_VENDA]				[VINCULADO VENDA]	
      ,FORMAT([DT_NEGOCIO],'d','pt-br') [DATA]		
      ,[NR_NEGOCIO]		 [NR NEGOCIO]
      ,FORMAT(QT_NEGOCIO_COMPRA,'#,0','PT-BR')	[QTD. NEGOCIO COMPRA]
      ,FORMAT(QT_NEGOCIO_VENDA,'#,0','PT-BR')	[QTD. NEGOCIO VENDA]	
      ,[CD_COMMOD]	[COMMODITIES]	
      ,[CD_SERIE]		[SÉRIE]
      ,[HH_COMPRA]		 [HH COMPRA]
      ,[HH_VENDA]		 [HH VENDA]
      ,FORMAT(VL_TOTNEG_COMPRA,'f','pt-br') [VOLUME COMPRA]		
      ,FORMAT(VL_TOTNEG_VENDA,'f','pt-br') [VOLUME VENDA]		
      ,FORMAT([VL_NEGOCIO_COMPRA],'f','pt-br')[PREÇO COMPRA]		
      ,FORMAT([VL_NEGOCIO_VENDA],'f','pt-br')[PREÇO VENDA]		
      ,[CD_ASSESSOR_COMPRA]	[COD. ASSESSOR COMPRA]	
      ,[DS_ASSESSOR_COMPRA]	[ASSESSOR COMPRA]	
      ,[CD_ASSESSOR_VENDA]	[COD. ASSESSOR VENDA]	
      ,[DS_ASSESSOR_VENDA]	[ASSESSOR VENDA]
      --,[SISTEMA_COMPRA]	[SISTEMA COMPRA]	
      ,[USUARIO_COMPRA]	[USUARIO COMPRA]
      --,[SISTEMA_VENDA]	[SISTEMA VENDA]	
      ,[USUARIO_VENDA]	[USUARIO VENDA]
		
FROM [ST_DIRETAS_BMF] 		

WHERE		
CD_CLIENTE_COMPRA <> CD_CLIENTE_VENDA AND		
DT_NEGOCIO >= @INICIO AND		
DT_NEGOCIO <= @FIM AND		
CD_CLIENTE_COMPRA = (CASE WHEN ISNULL(@CD_CLIENTE_COMPRA,'') = '' THEN CD_CLIENTE_COMPRA ELSE @CD_CLIENTE_COMPRA END) AND		
CD_CLIENTE_VENDA = (CASE WHEN ISNULL(@CD_CLIENTE_VENDA,'') = '' THEN CD_CLIENTE_VENDA ELSE @CD_CLIENTE_VENDA END) 		
		
--CD_ASSESSOR_COMPRA= (CASE WHEN @CD_ASSESSOR_COMPRA = '' THEN CD_ASSESSOR_COMPRA ELSE CAST(@CD_ASSESSOR_COMPRA AS INT) END) AND		
--CD_ASSESSOR_VENDA = (CASE WHEN @CD_ASSESSOR_VENDA = '' THEN CD_ASSESSOR_VENDA ELSE CAST(@CD_ASSESSOR_VENDA AS INT) END) 		
--AND VINC_VENDA = (CASE WHEN @VINC_VENDA = '' THEN VINC_VENDA ELSE @VINC_VENDA END)		
--AND VINC_COMPRA = (CASE WHEN @VINC_COMPRA = '' THEN VINC_COMPRA ELSE @VINC_COMPRA END)	--0M4	


 
ORDER BY 1		
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;