CREATE PROCEDURE [dbo].[PR_ALERTADETALHADOATIVORESTRITO]
(
   @CD_ANO INT, @DS_MES VARCHAR(50), @CD_CLIENTE INT
)
--WITH ENCRYPTION
AS

--declare @CD_ANO INT, @DS_MES VARCHAR(50), @CD_CLIENTE INT
--SET @CD_ANO = '2024'
--SET @DS_MES = 'OUTUBRO'
--SET @CD_CLIENTE = ''

BEGIN

IF @DS_MES = '01' BEGIN SET @DS_MES = 'JANEIRO' END
ELSE IF @DS_MES = '02' BEGIN SET @DS_MES = 'FEVEREIRO' END
ELSE IF @DS_MES = '03' BEGIN SET @DS_MES = 'MARÇO' END
ELSE IF @DS_MES = '04' BEGIN SET @DS_MES = 'ABRIL' END
ELSE IF @DS_MES = '05' BEGIN SET @DS_MES = 'MAIO' END
ELSE IF @DS_MES = '06' BEGIN SET @DS_MES = 'JUNHO' END
ELSE IF @DS_MES = '07' BEGIN SET @DS_MES = 'JULHO' END
ELSE IF @DS_MES = '08' BEGIN SET @DS_MES = 'AGOSTO' END
ELSE IF @DS_MES = '09' BEGIN SET @DS_MES = 'SETEMBRO' END
ELSE IF @DS_MES = '10' BEGIN SET @DS_MES = 'OUTUBRO' END
ELSE IF @DS_MES = '11' BEGIN SET @DS_MES = 'NOVEMBRO' END
ELSE IF @DS_MES = '12' BEGIN SET @DS_MES = 'DEZEMBRO' END

SET @CD_ANO = CAST(@CD_ANO AS INT)
SET @CD_CLIENTE = CAST(@CD_CLIENTE AS INT)

SELECT DISTINCT
 FORMAT(DATA,'d','pt-br')DATA
,A.CD_CLIENTE							AS [CÓD. CLIENTE]
,IN_QUALIFICADO							AS [INVESTIDOR QUALIFICADO]
,QTDE_NEGOCIOS							AS [QTDE. DE NEGÓCIOS]
,QTDE_ATIVOS							AS [QTDE. DE ATIVOS]
,NEGOCIOS								AS [NEGÓCIOS]

FROM ST_ALERT_ATIVO_RESTRITO A
INNER JOIN ST_PERIODO C  ON DATA = DT_PERIODO 
--LEFT OUTER JOIN V_CLIENTE_TODOS D ON A.CD_CLIENTE = D.CD_CLIENTE  
WHERE CD_ANO = @CD_ANO AND DS_MES = @DS_MES  AND A.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN A.CD_CLIENTE ELSE @CD_CLIENTE END

END