CREATE PROCEDURE [dbo].[FIRA_PR_CARGA_ST_DAYTRADE_DETALHE] @PREGAO DATETIME , @PREGAOFIM DATETIME, @CD_CONTRAPARTE INT
WITH RECOMPILE
AS

 
DROP TABLE IF EXISTS [dbo].[ST_DAYTRADE_DETALHE_PADRAO]
    CREATE TABLE [dbo].[ST_DAYTRADE_DETALHE_PADRAO] (
    [CD_CLIENTE_COMPROU] int NULL,
    [QT_NEGOCIO_COMPROU] float NULL,
    [VL_NEGOCIO_COMPROU] float NULL,
    [CD_NEGOCIO_COMPROU] varchar(12) NULL,
    [DT_PREGAO_COMPROU] datetime NULL,
    [CD_CONTRAPARTE_COMPROU] numeric(8,0) NULL,
    [CD_CONTRAPARTE_COMPROU_DE] numeric(8,0) NULL,
    [CD_CLIENTE_COMPROU_DE] int NULL,
    [QT_NEGOCIO_COMPROU_DE] float NULL,
    [VL_NEGOCIO_COMPROU_DE] float NULL,
    [NR_NEGOCIO_COMPROU] numeric(9,0) NULL,
    [CD_NATOPE] char(1) NULL,
    [QT_DAYTRADE] float NULL,
    [FT_VALORIZACAO] float NULL,
	[DT_FIRA] DATETIME NULL
);

/***************************************************
inicio da comparação entre a tabela
da base padrao fira origem x tabela cliente destino
*****************************************************/
EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo',, @src_table='ST_DAYTRADE_DETALHE_PADRAO',
  @schema_name='dbo', @base_table='ST_DAYTRADE_DETALHE',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1;



--DECLARE  @PREGAO DATETIME,@PREGAOFIM DATETIME,@CD_CONTRAPARTE INT
--SET @PREGAO ='20260201'
--SET @PREGAOFIM ='20260213'
--SET @CD_CONTRAPARTE = (SELECT MAX(CD_PARAMETRO) FROM ST_CLIENTE_PARAMETROS WHERE DS_PARAMETRO = 'CD_CONTRAPARTE')



/****************************	
	CARGA ST_DAYTRADE_DETALHE		
****************************/     

WHILE @PREGAO < @PREGAOFIM 	
BEGIN	
	 


	/*******************************
	  #### PRIMEIRO PROCESSO  ####
	*******************************/ 
 
		
		TRUNCATE TABLE T2#	

		;WITH #DAYTRADE_DETALHE1 AS (
		SELECT DISTINCT 
			X.CD_CLIENTE, X.DT_NEGOCIO , X.CD_PAPEL
		FROM ST_CORRETAGEM_ORDEM X (nolock), 
			 ST_CORRETAGEM_ORDEM Y (nolock)
		WHERE  
			Y.DT_NEGOCIO = X.DT_NEGOCIO 
		AND Y.CD_CLIENTE = X.CD_CLIENTE 
		AND Y.CD_PAPEL = X.CD_PAPEL 
		AND X.CD_NATOPE = 'C' 
		AND Y.CD_NATOPE = 'V' 
		AND X.CD_CONTRAPARTE = @CD_CONTRAPARTE 
		AND X.DT_NEGOCIO = @PREGAO
		)

		INSERT INTO T2#	
		(
		CD_CLIENTE_COMPROU,NM_CLIENTE_COMPROU,QT_NEGOCIO_COMPROU,VL_NEGOCIO_COMPROU
		,CD_NEGOCIO_COMPROU,DT_PREGAO_COMPROU,CD_CONTRAPARTE_COMPROU,CD_CONTRAPARTE_COMPROU_DE
		,CD_CLIENTE_COMPROU_DE,NM_CLIENTE_COMPROU_DE,QT_NEGOCIO_COMPROU_DE,VL_NEGOCIO_COMPROU_DE
		,NR_NEGOCIO_COMPROU,CD_NATOPE,FT_VALORIZACAO
		)
		SELECT DISTINCT 
			A.CD_CLIENTE AS CD_CLIENTE_COMPROU, 	
			NULL AS NM_CLIENTE_COMPROU,
			CASE WHEN A.QT_MULTIPLICADOR < D.QT_MULTIPLICADOR THEN A.QT_MULTIPLICADOR ELSE D.QT_MULTIPLICADOR END AS QT_MULTIPLICADOR_COMPROU, 	
			A.VL_NEGOCIO AS VL_NEGOCIO_COMPROU, 	
			A.CD_PAPEL AS CD_PAPEL_COMPROU, 	
			A.DT_NEGOCIO  AS DT_NEGOCIO_COMPROU, 	
			A.CD_CONTRAPARTE AS CD_CONTRAPARTE_COMPROU,	
			D.CD_CONTRAPARTE AS CD_CONTRAPARTE_COMPROU_DE,	
			D.CD_CLIENTE AS CD_CLIENTE_COMPROU_DE,	
			NULL AS NM_CLIENTE_COMPROU_DE,	
			NULL AS QT_MULTIPLICADOR_COMPROU_DE,	
			D.VL_NEGOCIO AS VL_NEGOCIO_COMPROU_DE,	
			A.NR_NEGOCIO AS NR_NEGOCIO_COMPROU,	
			A.CD_NATOPE  AS CD_NATOPE,
			A.FT_VALORIZACAO	
			
		FROM 	
			ST_CORRETAGEM_ORDEM A (nolock),  	
			ST_CORRETAGEM_ORDEM D (nolock)
		WHERE 
			D.DT_NEGOCIO  = A.DT_NEGOCIO 	
		AND D.CD_PAPEL = A.CD_PAPEL 	
		AND D.NR_NEGOCIO = A.NR_NEGOCIO	
		AND A.CD_NATOPE  = 'C' 
		AND D.CD_NATOPE  = 'V' 	
		AND A.DT_NEGOCIO  = @PREGAO	
		AND EXISTS (SELECT DISTINCT CD_CLIENTE 
					FROM #DAYTRADE_DETALHE1 X
					WHERE  
						X.CD_CLIENTE = A.CD_CLIENTE	
					AND X.DT_NEGOCIO  = A.DT_NEGOCIO
					AND X.CD_PAPEL = A.CD_PAPEL 
					)

 


	
	/*****************************
	  #### SEGUNDO PROCESSO  ####
	*****************************/

	 
		INSERT INTO T2#	
		(
		CD_CLIENTE_COMPROU,NM_CLIENTE_COMPROU,QT_NEGOCIO_COMPROU,VL_NEGOCIO_COMPROU
		,CD_NEGOCIO_COMPROU,DT_PREGAO_COMPROU,CD_CONTRAPARTE_COMPROU,CD_CONTRAPARTE_COMPROU_DE
		,CD_CLIENTE_COMPROU_DE,NM_CLIENTE_COMPROU_DE,QT_NEGOCIO_COMPROU_DE,VL_NEGOCIO_COMPROU_DE
		,NR_NEGOCIO_COMPROU,CD_NATOPE,FT_VALORIZACAO
		)
		SELECT DISTINCT 
			A.CD_CLIENTE AS CD_CLIENTE_COMPROU, 	
			NULL AS NM_CLIENTE_COMPROU, 	
			A.QT_MULTIPLICADOR AS QT_MULTIPLICADOR_COMPROU, 	
			A.VL_NEGOCIO AS VL_NEGOCIO_COMPROU, 	
			A.CD_PAPEL AS CD_PAPEL_COMPROU, 	
			A.DT_NEGOCIO AS DT_NEGOCIO_COMPROU , 	
			A.CD_CONTRAPARTE AS CD_CONTRAPARTE_COMPROU,	
			A.CD_CONTRAPARTE AS CD_CONTRAPARTE_COMPROU_DE,	
			NULL AS CD_CLIENTE_COMPROU_DE,	
			NULL AS NM_CLIENTE_COMPROU_DE,	
			NULL AS QT_MULTIPLICADOR_COMPROU_DE,	
			A.VL_NEGOCIO AS VL_NEGOCIO_COMPROU_DE,	
			A.NR_NEGOCIO AS NR_NEGOCIO_COMPROU,	
			'C' AS CD_NATOPE,	
			A.FT_VALORIZACAO	
			
		FROM 	
			ST_CORRETAGEM_ORDEM A (nolock), 	
			ST_CORRETAGEM_ORDEM D (nolock)	
		WHERE 
			D.DT_NEGOCIO       = A.DT_NEGOCIO 	
		AND D.CD_PAPEL      = A.CD_PAPEL 	
		AND A.CD_CLIENTE      = D.CD_CLIENTE 	
		AND A.CD_NATOPE       = 'C' 
		AND D.CD_NATOPE       = 'V' 	
		AND A.CD_CONTRAPARTE <> @CD_CONTRAPARTE 	
		AND A.DT_NEGOCIO       = @PREGAO	
		
		
 

	
	/******************************
	  #### TERCEIRO PROCESSO  ####
	******************************/ 	

 

		--VENDA
		;WITH #DAYTRADE_DETALHE3 AS (
		SELECT DISTINCT X.CD_CLIENTE, X.DT_NEGOCIO, X.CD_PAPEL 
		FROM ST_CORRETAGEM_ORDEM X (nolock),
			 ST_CORRETAGEM_ORDEM Y (nolock)
		WHERE  
			Y.DT_NEGOCIO  = X.DT_NEGOCIO 
		AND Y.CD_CLIENTE = X.CD_CLIENTE 
		AND Y.CD_PAPEL = X.CD_PAPEL 
		AND X.CD_NATOPE  = 'V' 
		AND Y.CD_NATOPE  = 'C' 
		AND X.CD_CONTRAPARTE = @CD_CONTRAPARTE  
		AND X.DT_NEGOCIO  = @PREGAO
		)


		INSERT INTO T2#
		(
		CD_CLIENTE_COMPROU,NM_CLIENTE_COMPROU,QT_NEGOCIO_COMPROU,VL_NEGOCIO_COMPROU
		,CD_NEGOCIO_COMPROU,DT_PREGAO_COMPROU,CD_CONTRAPARTE_COMPROU,CD_CONTRAPARTE_COMPROU_DE
		,CD_CLIENTE_COMPROU_DE,NM_CLIENTE_COMPROU_DE,QT_NEGOCIO_COMPROU_DE,VL_NEGOCIO_COMPROU_DE
		,NR_NEGOCIO_COMPROU,CD_NATOPE,FT_VALORIZACAO
		)
		SELECT DISTINCT 
			A.CD_CLIENTE AS CD_CLIENTE_VENDEU, 
			NULL AS NM_CLIENTE_VENDEU, 
			CASE WHEN A.QT_MULTIPLICADOR <  D.QT_MULTIPLICADOR THEN A.QT_MULTIPLICADOR ELSE D.QT_MULTIPLICADOR END AS QT_MULTIPLICADOR_VENDEU, 
			A.VL_NEGOCIO AS VL_NEGOCIO_VENDEU, 
			A.CD_PAPEL AS CD_PAPEL_VENDEU, 
			A.DT_NEGOCIO  AS DT_NEGOCIO_VENDEU , 
			A.CD_CONTRAPARTE AS CD_CONTRAPARTE_VENDEU,
			D.CD_CONTRAPARTE AS CD_CONTRAPARTE_VENDEU_PARA,
			D.CD_CLIENTE AS CD_CLIENTE_VENDEU_PARA,
			NULL AS NM_CLIENTE_VENDEU_PARA,
			NULL AS QT_MULTIPLICADOR_VENDEU_PARA,
			D.VL_NEGOCIO AS VL_NEGOCIO_VENDEU_PARA,
			A.NR_NEGOCIO AS NR_NEGOCIO_VENDEU,
			A.CD_NATOPE AS CD_NATOPE,
			A.FT_VALORIZACAO

		FROM ST_CORRETAGEM_ORDEM A (nolock), 
			 ST_CORRETAGEM_ORDEM D (nolock)
		WHERE 
			D.DT_NEGOCIO  = A.DT_NEGOCIO 
		AND D.CD_PAPEL = A.CD_PAPEL 
		AND D.NR_NEGOCIO = A.NR_NEGOCIO 
		AND A.CD_NATOPE  = 'V' 
		AND D.CD_NATOPE  = 'C' 
		AND A.CD_CONTRAPARTE = @CD_CONTRAPARTE 
		AND D.CD_CONTRAPARTE = @CD_CONTRAPARTE  
		AND A.DT_NEGOCIO  = @PREGAO
		AND EXISTS (SELECT DISTINCT CD_CLIENTE 
					FROM #DAYTRADE_DETALHE3 X
					WHERE  
						X.CD_CLIENTE = A.CD_CLIENTE	
					AND X.DT_NEGOCIO  = A.DT_NEGOCIO
					AND X.CD_PAPEL = A.CD_PAPEL
					)
					
 

				
	/*****************************
	  ####  QUARTO PROCESSO   ####
	*****************************/ 	
	 	
		--VENDA OUTROS
		INSERT INTO T2#
		(
		CD_CLIENTE_COMPROU,NM_CLIENTE_COMPROU,QT_NEGOCIO_COMPROU,VL_NEGOCIO_COMPROU
		,CD_NEGOCIO_COMPROU,DT_PREGAO_COMPROU,CD_CONTRAPARTE_COMPROU,CD_CONTRAPARTE_COMPROU_DE
		,CD_CLIENTE_COMPROU_DE,NM_CLIENTE_COMPROU_DE,QT_NEGOCIO_COMPROU_DE,VL_NEGOCIO_COMPROU_DE
		,NR_NEGOCIO_COMPROU,CD_NATOPE,FT_VALORIZACAO
		)
		SELECT DISTINCT 
			A.CD_CLIENTE AS CD_CLIENTE_COMPROU, 
			NULL AS NM_CLIENTE_COMPROU, 
			A.QT_MULTIPLICADOR AS QT_MULTIPLICADOR_COMPROU, 
			A.VL_NEGOCIO AS VL_NEGOCIO_COMPROU, 
			A.CD_PAPEL AS CD_PAPEL_COMPROU, 
			A.DT_NEGOCIO  AS DT_NEGOCIO_COMPROU , 
			A.CD_CONTRAPARTE AS CD_CONTRAPARTE_COMPROU,
			A.CD_CONTRAPARTE AS CD_CONTRAPARTE_COMPROU_DE,
			NULL AS CD_CLIENTE_COMPROU_DE,
			NULL AS NM_CLIENTE_COMPROU_DE,
			NULL AS QT_MULTIPLICADOR_COMPROU_DE,
			A.VL_NEGOCIO AS VL_NEGOCIO_COMPROU_DE,
			A.NR_NEGOCIO AS NR_NEGOCIO_COMPROU,
			A.CD_NATOPE  AS CD_NATOPE,
			A.FT_VALORIZACAO

		FROM ST_CORRETAGEM_ORDEM A (nolock), 
			 ST_CORRETAGEM_ORDEM D (nolock)
		WHERE 
			D.DT_NEGOCIO  = A.DT_NEGOCIO 
		AND D.CD_PAPEL = A.CD_PAPEL 
		AND D.CD_CLIENTE = A.CD_CLIENTE 
		AND A.CD_NATOPE  = 'V' 
		AND D.CD_NATOPE  = 'C' 
		AND	A.CD_CONTRAPARTE <> @CD_CONTRAPARTE
		AND A.DT_NEGOCIO  = @PREGAO

	 
	
	/*****************************
	  ####  PROCESSO FINAL   ####
	*****************************/

	 
		
		DELETE ST_DAYTRADE_DETALHE	WHERE DT_PREGAO_COMPROU = @PREGAO 	
			
		INSERT INTO  ST_DAYTRADE_DETALHE	
		(
		 CD_CLIENTE_COMPROU,QT_NEGOCIO_COMPROU,VL_NEGOCIO_COMPROU,CD_NEGOCIO_COMPROU,DT_PREGAO_COMPROU
		,CD_CONTRAPARTE_COMPROU,CD_CONTRAPARTE_COMPROU_DE,CD_CLIENTE_COMPROU_DE,QT_NEGOCIO_COMPROU_DE,
		VL_NEGOCIO_COMPROU_DE,NR_NEGOCIO_COMPROU,CD_NATOPE,QT_DAYTRADE,FT_VALORIZACAO
		)
		SELECT 
			 [CD_CLIENTE_COMPROU]	
			,[QT_NEGOCIO_COMPROU]	
			,[VL_NEGOCIO_COMPROU]	
			,[CD_NEGOCIO_COMPROU]	
			,[DT_PREGAO_COMPROU]	
			,[CD_CONTRAPARTE_COMPROU]	
			,[CD_CONTRAPARTE_COMPROU_DE]	
			,[CD_CLIENTE_COMPROU_DE]	
			,[QT_NEGOCIO_COMPROU_DE]	
			,[VL_NEGOCIO_COMPROU_DE]	
			,[NR_NEGOCIO_COMPROU]	
			,[CD_NATOPE]
			,NULL
			,FT_VALORIZACAO	
		
		FROM T2#	
		WHERE DT_PREGAO_COMPROU = @PREGAO
	
	
SET @PREGAO = @PREGAO +1

END	


-- ================================================
-- Marca DT_FIRA para registros carregados (fallback)
-- ================================================
DECLARE @__dt_fira_now DATETIME = GETDATE();
IF COL_LENGTH(N'dbo.ST_DAYTRADE_DETALHE', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE [dbo].ST_DAYTRADE_DETALHE
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL;
END 

/******* fim do processo de carga **********/

--passo 3
/***** limpa a tabela do banco para nao ficar sujeira ******/
DROP TABLE IF EXISTS ST_DAYTRADE_DETALHE_PADRAO