CREATE PROCEDURE [dbo].[FIRA_PR_CARGA_ST_MESA_AUX_BVSP]
AS

-- 1) cria tabela PADRAO baseada na estrutura atual da destino
DROP TABLE IF EXISTS [dbo].[ST_MESA_AUX_BVSP_PADRAO]
    CREATE TABLE [dbo].[ST_MESA_AUX_BVSP_PADRAO] (
    [CD_ANOMES] int NOT NULL,
    [CD_CLIENTE] int NOT NULL,
    [QTD_C] bigint NULL,
    [QTD_V] bigint NULL,
    [QTD] bigint NULL,
    [CORRETAGEM] float NULL,
    [VOLUME_COMPRA] float NULL,
	[DT_FIRA] DATETIME NULL
);

-- 2) sincroniza schema (PADRAO -> DESTINO)
EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo',, @src_table='ST_MESA_AUX_BVSP_PADRAO',
  @schema_name='dbo', @base_table='ST_MESA_AUX_BVSP',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1;

-- 3) corpo original


	DECLARE @DT_PREGAO	   SMALLDATETIME 
		  , @DT_PREGAO_FIM SMALLDATETIME
		  , @DIA_UTIL INT	
		  , @AUX INT
		  , @CD_ANOMES INT

	SET @DT_PREGAO		= CAST(DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1) AS DATE); --PRIMEIO DIA DO MES
	SET @DT_PREGAO_FIM	= CAST(GETDATE() AS DATE); --DIA ATUAL

	--VERIFICA QUANTOS DIAS UTEIS JA PASSARAM
	SET @DIA_UTIL		= dbo.dia_util(@DT_PREGAO_FIM)--=(SELECT COUNT(DT_PERIODO) FROM ST_PERIODO WHERE DT_PERIODO >= @DT_PREGAO AND DT_PERIODO <= @DT_PREGAO_FIM AND DT_FERIADO = 'NAO' AND DS_DIASEMANA NOT IN ('SABADO','DOMINGO'));
	
	--VARIAVEL AUXILIAR PARA SETAR AS DATAS DO MES DE CARREGAMENTO, POR EXEMPLO, SE RODAR NO MES DE OUTRUBRO TEM QUE CARREGAR DADOS DE SETEMBRO.
	SET @AUX			= DAY(@DT_PREGAO);
	
	-- PRIMEIRO DIA DO MES E ULTIMO DO MES QUE SERÁ CARREGADO.
	SET @DT_PREGAO_FIM = DATEADD(DAY,- @AUX, @DT_PREGAO);
	SET @DT_PREGAO	   = CAST(DATEFROMPARTS(YEAR(DATEADD(DAY,-@AUX,@DT_PREGAO)), MONTH(DATEADD(DAY,-@AUX,@DT_PREGAO)), 1) AS DATE);
	
	SET @CD_ANOMES = (SELECT MAX(CD_ANOMES) FROM ST_PERIODO WHERE DT_PERIODO = @DT_PREGAO);

	PRINT 'CD_ANOMES:'+CAST(@CD_ANOMES AS VARCHAR)+' DT_PREGAO:'+CONVERT(VARCHAR,@DT_PREGAO,23)+' DT_PREGAO_FIM:'+CONVERT(VARCHAR,@DT_PREGAO_FIM,23)+' DIA UTIL:'+CAST(@DIA_UTIL AS VARCHAR);

	--SE FOR O QUARTO DIA UTIL IRÁ CARREGAR O MES ANTERIOR.
	IF @DIA_UTIL = (SELECT MAX(CD_PARAMETRO) FROM ST_CLIENTE_PARAMETROS WHERE DS_PARAMETRO  = 'DIA_UTIL')
	BEGIN

	PRINT '4'

    DELETE FROM ST_MESA_AUX_BVSP WHERE CD_ANOMES = @CD_ANOMES;

	INSERT INTO ST_MESA_AUX_BVSP 
	(
	CD_ANOMES,CD_CLIENTE,QTD_C,QTD_V,QTD,CORRETAGEM,VOLUME_COMPRA
	)
	SELECT Y.CD_ANOMES
			  , CD_CLIENTE
			  ,	SUM(QTD_C)				AS QTD_C 
			  ,	SUM(QTD_V)				AS QTD_V
			  ,	SUM(QTD_C) + SUM(QTD_V) AS QTD
			  ,	SUM(CORRETAGEM)CORRETAGEM  
			  , SUM(VOLUME_COMPRA) AS VOLUMNE_COMPRA
		  FROM(
				SELECT
					CO.DT_PERIODO DT_NEGOCIO,
					CO.CD_CLIENTE,  
					CASE WHEN CO.CD_NATOPE = 'C' THEN COUNT(DISTINCT CO.NR_SEQORD) ELSE 0 END AS QTD_C,
					CASE WHEN CO.CD_NATOPE = 'V' THEN COUNT(DISTINCT CO.NR_SEQORD) ELSE 0 END AS QTD_V,
					SUM(VL_CORTOT_ORI) AS CORRETAGEM  
				 , CASE WHEN CO.CD_NATOPE = 'C' THEN SUM(VL_TOTNEG) END VOLUME_COMPRA

				FROM ST_MESA_BVSP CO
				WHERE 
					CO.DT_PERIODO >= @DT_PREGAO
				AND CO.DT_PERIODO <= @DT_PREGAO_FIM

				GROUP BY CO.DT_PERIODO, CO.CD_CLIENTE, CO.CD_NATOPE
			 )X
	  LEFT JOIN ST_PERIODO Y 
			ON X.DT_NEGOCIO = Y.DT_PERIODO
	  GROUP BY CD_CLIENTE ,CD_ANOMES

	END

-- ================================================
-- Marca DT_FIRA para registros carregados (fallback)
-- ================================================
	DECLARE @__dt_fira_now DATETIME = GETDATE();
IF COL_LENGTH(N'dbo.ST_MESA_AUX_BVSP', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE [dbo].[ST_MESA_AUX_BVSP]
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL;
END

-- 4) limpa PADRAO
DROP TABLE IF EXISTS [dbo].[ST_MESA_AUX_BVSP_PADRAO];