CREATE   PROCEDURE [dbo].[PR_LISTA_X_CLIENTES] @CLIENTE bigINT ,@QTDPORPAGINA INT, @PAGINA INT
WITH RECOMPILE
--,@LISTA VARCHAR(160)
AS 


--DECLARE @CLIENTE INT , @QTDPORPAGINA INT = 2000 , @PAGINA INT = 1
-------,@LISTA VARCHAR(160)
--SET @CLIENTE = ''

--select * from v_cliente_todos where nm_cliente like '%denis%'

IF COALESCE(@CLIENTE,'') = ''
BEGIN

	;WITH  ALERTA_LISTA as (
		SELECT DISTINCT
			CD_CPFCGC AS CPF_CNPJ,
			CD_CLIENTE,
			NM_CLIENTE AS NOME,
			TP_SITUAC ,
			IN_SITUAC,
			IDSUBLISTA,
			DETALHES,
			ISNULL(CARGOEXERCIDO, '-')CARGOEXERCIDO,
			VERFICACAO

		FROM(

			---VERFICACAO: NOME
			SELECT DISTINCT
				CD.CD_CPFCGC,
				CD.CD_CLIENTE,
				CD.NM_CLIENTE,
				TP_SITUAC,
				CASE WHEN IN_SITUAC = 'A' THEN 'ATIVO' ELSE 'INATIVO' END IN_SITUAC,
				LR.IDSUBLISTA,
				LR.DETALHES,
				LR.CARGOEXERCIDO,
				'NOME' AS VERFICACAO
						
			FROM LISTAATENCAO LR
			INNER JOIN V_CLIENTE_TODOS CD
				ON UPPER(REPLACE(REPLACE(LR.NOME,'.',''),'/','')) = UPPER(REPLACE(REPLACE(CD.NM_CLIENTE,'.',''),'/',''))
			WHERE 
				(LR.CPFCNPJ IS NULL OR LR.CPFCNPJ = '')
			

			UNION ALL


			--VERFICACAO: CPF_PARCIAL
			SELECT DISTINCT
				CD.CD_CPFCGC ,
				CD.CD_CLIENTE,
				CD.NM_CLIENTE ,
				TP_SITUAC,
				CASE WHEN IN_SITUAC = 'A' THEN 'ATIVO' ELSE 'INATIVO' END IN_SITUAC,
				LR.IDSUBLISTA,
				LR.DETALHES,
				LR.CARGOEXERCIDO,
				'CPF_PARCIAL' AS VERFICACAO

			FROM LISTAATENCAO LR
			INNER  JOIN V_CLIENTE_TODOS CD
				ON  SUBSTRING(CAST(REPLACE(REPLACE(REPLACE(UPPER(LR.CPFCNPJ),'.',''),'-',''),'/','') AS VARCHAR(30)),4, 6) = SUBSTRING(CAST(REPLACE(REPLACE(REPLACE(CD.CPFCNPJ,'.',''),'-',''),'/','') AS VARCHAR(30)),4, 6)
				AND UPPER(REPLACE(REPLACE(LR.NOME,'.',''),'/','')) = UPPER(REPLACE(REPLACE(CD.NM_CLIENTE,'.',''),'/',''))
			WHERE  
				(LR.CPFCNPJ IS NOT NULL OR LR.CPFCNPJ <> '')
			AND (SUBSTRING(CAST(LR.CPFCNPJ AS VARCHAR(30)),1, 1) = '*' OR SUBSTRING(CAST(LR.CPFCNPJ AS VARCHAR(30)),1, 1) = 'X')

			UNION ALL

			--VERFICACAO: CPF_COMPLETO
			SELECT DISTINCT 
				CD.CD_CPFCGC,
				CD.CD_CLIENTE,
				CD.NM_CLIENTE ,
				TP_SITUAC,
				CASE WHEN IN_SITUAC = 'A' THEN 'ATIVO' ELSE 'INATIVO' END IN_SITUAC,
				LR.IDSUBLISTA,
				LR.DETALHES,
				LR.CARGOEXERCIDO,
				'CPF_COMPLETO' AS VERFICACAO

			FROM LISTAATENCAO LR
			INNER  JOIN V_CLIENTE_TODOS CD
				ON  REPLACE(REPLACE(LR.CPFCNPJ,'.',''),'-','') = REPLACE(REPLACE(CD.CPFCNPJ,'.',''),'-','')
				AND UPPER(REPLACE(REPLACE(LR.NOME,'.',''),'/','')) = UPPER(REPLACE(REPLACE(CD.NM_CLIENTE,'.',''),'/',''))
			WHERE 
				(LR.CPFCNPJ IS NOT NULL OR LR.CPFCNPJ <> '')
			AND (SUBSTRING(CAST(LR.CPFCNPJ AS VARCHAR(30)),1, 1) <> '*' OR SUBSTRING(CAST(LR.CPFCNPJ AS VARCHAR(30)),1, 1) <> 'X')

		)X

	)


	----------------
	--SELECT FINAL--
	----------------
	SELECT DISTINCT   
		CPF_CNPJ AS "CPF / CNPJ",
		CD_CLIENTE AS "CÓD. CLIENTE",
		I.NOME AS "NOME DO CLIENTE",
		TP_SITUAC AS "SITUAÇÃO CADASTRO GERAL",
		IN_SITUAC AS "CADASTRO BOLSA",
		B.NOME AS LISTA,
		CARGOEXERCIDO AS "CARGO EXERCIDO",
		MAX(DETALHES) AS "OBSERVAÇÃO",		
		VERFICACAO

	FROM ALERTA_LISTA I
	INNER JOIN LISTAATENCAOSUBLISTA B
		ON I.IDSUBLISTA = B.ID
		GROUP BY CPF_CNPJ, CD_CLIENTE, I.NOME, TP_SITUAC, IN_SITUAC, B.Nome, CARGOEXERCIDO, VERFICACAO
	ORDER BY 1		
	OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
	FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;

END
ELSE 
BEGIN

	;WITH  ALERTA_LISTA as (
		SELECT DISTINCT
			CD_CPFCGC AS CPF_CNPJ,
			CD_CLIENTE,
			NM_CLIENTE AS NOME,
			TP_SITUAC ,
			IN_SITUAC,
			IDSUBLISTA,
			DETALHES,
			ISNULL(CARGOEXERCIDO, '-')CARGOEXERCIDO,
			VERFICACAO

		FROM(

			---VERFICACAO: NOME
			SELECT DISTINCT
				CD.CD_CPFCGC,
				CD.CD_CLIENTE,
				CD.NM_CLIENTE,
				TP_SITUAC,
				CASE WHEN IN_SITUAC = 'A' THEN 'ATIVO' ELSE 'INATIVO' END IN_SITUAC,
				LR.IDSUBLISTA,
				LR.DETALHES,
				LR.CARGOEXERCIDO,
				'NOME' AS VERFICACAO
						
			FROM LISTAATENCAO LR
			INNER JOIN V_CLIENTE_TODOS CD
				ON UPPER(REPLACE(REPLACE(LR.NOME,'.',''),'/','')) = UPPER(REPLACE(REPLACE(CD.NM_CLIENTE,'.',''),'/',''))
			WHERE 
				(LR.CPFCNPJ IS NULL OR LR.CPFCNPJ = '')
			AND CD.CD_CLIENTE = @CLIENTE --CASE WHEN ISNULL(@CLIENTE,'') = '' THEN CD_CLIENTE ELSE @CLIENTE END

			UNION ALL


			--VERFICACAO: CPF_PARCIAL
			SELECT DISTINCT
				CD.CD_CPFCGC ,
				CD.CD_CLIENTE,
				CD.NM_CLIENTE ,
				TP_SITUAC,
				CASE WHEN IN_SITUAC = 'A' THEN 'ATIVO' ELSE 'INATIVO' END IN_SITUAC,
				LR.IDSUBLISTA,
				LR.DETALHES,
				LR.CARGOEXERCIDO,
				'CPF_PARCIAL' AS VERFICACAO

			FROM LISTAATENCAO LR
			INNER  JOIN V_CLIENTE_TODOS CD
				ON  SUBSTRING(CAST(REPLACE(REPLACE(REPLACE(UPPER(LR.CPFCNPJ),'.',''),'-',''),'/','') AS VARCHAR(30)),4, 6) = SUBSTRING(CAST(REPLACE(REPLACE(REPLACE(CD.CD_CPFCGC,'.',''),'-',''),'/','') AS VARCHAR(30)),4, 6)
				AND UPPER(REPLACE(REPLACE(LR.NOME,'.',''),'/','')) = UPPER(REPLACE(REPLACE(CD.NM_CLIENTE,'.',''),'/',''))
			WHERE  
				(LR.CPFCNPJ IS NOT NULL OR LR.CPFCNPJ <> '')
			AND (SUBSTRING(CAST(LR.CPFCNPJ AS VARCHAR(30)),1, 1) = '*' OR SUBSTRING(CAST(LR.CPFCNPJ AS VARCHAR(30)),1, 1) = 'X')
			AND CD.CD_CLIENTE = @CLIENTE

			UNION ALL

			--VERFICACAO: CPF_COMPLETO
			SELECT DISTINCT 
				CD.CD_CPFCGC,
				CD.CD_CLIENTE,
				CD.NM_CLIENTE ,
				TP_SITUAC,
				CASE WHEN IN_SITUAC = 'A' THEN 'ATIVO' ELSE 'INATIVO' END IN_SITUAC,
				LR.IDSUBLISTA,
				LR.DETALHES,
				LR.CARGOEXERCIDO,
				'CPF_COMPLETO' AS VERFICACAO

			FROM LISTAATENCAO LR
			INNER  JOIN V_CLIENTE_TODOS CD
				ON  REPLACE(REPLACE(LR.CPFCNPJ,'.',''),'-','') = REPLACE(REPLACE(CD.CD_CPFCGC,'.',''),'-','')
				AND UPPER(REPLACE(REPLACE(LR.NOME,'.',''),'/','')) = UPPER(REPLACE(REPLACE(CD.NM_CLIENTE,'.',''),'/',''))
			WHERE 
				(LR.CPFCNPJ IS NOT NULL OR LR.CPFCNPJ <> '')
			AND (SUBSTRING(CAST(LR.CPFCNPJ AS VARCHAR(30)),1, 1) <> '*' OR SUBSTRING(CAST(LR.CPFCNPJ AS VARCHAR(30)),1, 1) <> 'X')
			AND CD.CD_CLIENTE = @CLIENTE
		)X

	)


	----------------
	--SELECT FINAL--
	----------------
	SELECT DISTINCT   
		CPF_CNPJ AS "CPF / CNPJ",
		CD_CLIENTE AS "CÓD. CLIENTE",
		I.NOME AS "NOME DO CLIENTE",
		TP_SITUAC AS "SITUAÇÃO CADASTRO GERAL",
		IN_SITUAC AS "CADASTRO BOLSA",
		B.NOME AS LISTA,
		CARGOEXERCIDO AS "CARGO EXERCIDO",
		DETALHES AS "OBSERVAÇÃO",		
		VERFICACAO

	FROM ALERTA_LISTA I
	INNER JOIN LISTAATENCAOSUBLISTA B
		ON I.IDSUBLISTA = B.ID


	ORDER BY 1		
	OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
	FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;
END