CREATE PROCEDURE [dbo].[PR_ALERTADETALHADOTRANSFERENCIAFINANCEIRA1]
(
   @CD_ANO INT, @DS_MES VARCHAR(50), @CD_CLIENTE INT
)
--WITH ENCRYPTION

--06/12/2024 A PEDIDO DA LANA (TORO) E COM PERMISSÃO DO GOBBO, add a COLUNA VALOR_DEPOSITO já existente no alerta.
--11/02/2025 - COLUNA PATRIMONIO ADICIONADA - FLÁVIO
AS
BEGIN

IF @DS_MES = '01' BEGIN SET @DS_MES = 'JANEIRO' END
ELSE IF @DS_MES = '02' BEGIN SET @DS_MES = 'FEVEREIRO' END
ELSE IF @DS_MES = '03' BEGIN SET @DS_MES = 'MARÇO' END
ELSE IF @DS_MES = '04' BEGIN SET @DS_MES = 'ABRIL' END
ELSE IF @DS_MES = '05' BEGIN SET @DS_MES = 'MAIO' END
ELSE IF @DS_MES = '06' BEGIN SET @DS_MES = 'JUNHO' END
ELSE IF @DS_MES = '07' BEGIN SET @DS_MES = 'JULHO' END
ELSE IF @DS_MES = '08' BEGIN SET @DS_MES = 'AGOSTO' END
ELSE IF @DS_MES = '09' BEGIN SET @DS_MES = 'SETEMBRO' END
ELSE IF @DS_MES = '10' BEGIN SET @DS_MES = 'OUTUBRO' END
ELSE IF @DS_MES = '11' BEGIN SET @DS_MES = 'NOVEMBRO' END
ELSE IF @DS_MES = '12' BEGIN SET @DS_MES = 'DEZEMBRO' END

SET @CD_ANO = CAST(@CD_ANO AS INT)
SET @CD_CLIENTE = CAST(@CD_CLIENTE AS INT)

drop table if exists #V_CLIENTE_TODOS
select distinct cd_Cliente, tipo into #V_CLIENTE_TODOS from V_CLIENTE_TODOS


SELECT DISTINCT  
FORMAT(DATA,'d','pt-br')DATA
,a.CD_CLIENTE AS [CÓD. CLIENTE]
,a.NM_CLIENTE AS [NOME DO CLIENTE]
,a.CD_CPFCGC AS [CPF/CPNJ]
,TIPO AS [TIPO CLIENTE]
,FORMAT(a.DT_CRIACAO,'d','pt-br') AS [DATA DE CRIAÇÃO]
,FORMAT(DT_DEPOSITO,'d','pt-br') AS [DATA DO DEPÓSITO]
,FORMAT(VALOR_DEPOSITO,'f','pt-br')AS [VALOR DEPÓSITO]
,DIAS AS [QTD DE DIAS]
,FORMAT(a.DT_ULT_OPER,'d','pt-br') AS [DATA ULT. OPER]
,FORMAT(DT_SALDO,'d','pt-br')AS [DATA DO SALDO]
,FORMAT(SALDO_CC,'f','pt-br')AS [SALDO EM CC]
,FORMAT(PATRIMONIO,'f','pt-br')AS [PATRIMONIO]

FROM ST_ALERT_TRANSFERENCIA_FINANCEIRA_01 A
INNER JOIN ST_PERIODO C  ON DATA = DT_PERIODO  
LEFT OUTER JOIN #V_CLIENTE_TODOS D ON A.CD_CLIENTE = D.CD_CLIENTE  
WHERE CD_ANO = @CD_ANO AND DS_MES = @DS_MES  AND A.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN A.CD_CLIENTE ELSE @CD_CLIENTE END

END