CREATE PROCEDURE [dbo].[FIRA_PR_CARGA_ST_DADOS_FINANCEIROS_PJ]
--WITH ENCRYPTION
AS


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ST_DADOS_FINANCEIROS_PJ_PADRAO]') AND type in (N'U'))
CREATE TABLE [dbo].[ST_DADOS_FINANCEIROS_PJ_PADRAO](
	[CPF] [varchar](20) NULL,
	[NM_CLIENTE] [nvarchar](160) NULL,
	[CD_CLIENTE] [int] NULL,
	[NM_ASSESSOR] [varchar](300) NULL,
	[CD_BANCO] [nvarchar](18) NULL,
	[CD_AGENCIA] [nvarchar](15) NULL,
	[CONTA] [nvarchar](26) NOT NULL,
	[PATRIMONIO] [float] NOT NULL,
	[DS_ATIV] [varchar](160) NULL,	 
	[BENS IMÓVEIS] [float] NULL,
	[BENS MÓVEIS] [float] NULL,
	[APLICAÇÕES FINANCEIRAS] [float] NULL,
	[SALÁRIO] [float] NULL,
	[OUTROS RENDIMENTOS] [float] NULL,
	[DESPOSITO_BANCARIO] [float] NULL,
	[RENDA_FIXA] [float] NULL,
	[RENDA_VARIAVEL] [float] NULL,
	[VL_OPERACIONAL1] [float] NULL,
	[IN_CONTR_BOLSA] [nchar](1) NULL,
	[IN_CONTR_BMF] [nchar](1) NULL,
	[IN_CONTR_SOCIAL] [nchar](1) NULL,
	[IN_CONTR_OPC] [nchar](1) NULL,
	[IN_CONTR_TER] [nchar](1) NULL,
	[IN_CONTR_TST] [nchar](1) NULL,
	[IN_CONTR_BTC] [nchar](1) NULL,
	[IN_CONTA_MARGEM] [nchar](1) NULL,
	[TP_SITUAC] [nvarchar](2) NULL,
	[CD_ASSESSOR] [int] NULL,
	[NM_EMPRESA] [nvarchar](160) NULL,
	[DT_FIRA] DATETIME NULL
) ON [PRIMARY]


--/***************************************************
--inicio da comparação entre a tabela
--da base padrao fira origem x tabela cliente destino
--*****************************************************/
 
-- 1) Faz o sync (pode ficar estático)
EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo',, @src_table='ST_DADOS_FINANCEIROS_PJ_PADRAO',
  @schema_name='dbo', @base_table='ST_DADOS_FINANCEIROS_PJ',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1;

-- 2) TRUNCATE pode ficar estático
TRUNCATE TABLE dbo.ST_DADOS_FINANCEIROS_PJ;

/**********************************************************************
-- 3) INSERT em SQL dinâmico (compila após o ALTER) INSERT com lista 
explícita de colunas Isso evita dor de cabeça caso a tabela destino 
tenha colunas a mais, ordem diferente, identity, etc.
**********************************************************************/
DECLARE @sql nvarchar(max) = N'
INSERT INTO dbo.ST_DADOS_FINANCEIROS_PJ
(
    CPF, NM_CLIENTE, CD_CLIENTE, NM_ASSESSOR, CD_BANCO, CD_AGENCIA, CONTA,
    PATRIMONIO, DS_ATIV,
    [BENS IMÓVEIS], [BENS MÓVEIS], [APLICAÇÕES FINANCEIRAS], [SALÁRIO], [OUTROS RENDIMENTOS],
    DESPOSITO_BANCARIO, RENDA_FIXA, RENDA_VARIAVEL, VL_OPERACIONAL1,
    IN_CONTR_BOLSA, IN_CONTR_BMF, IN_CONTR_SOCIAL, IN_CONTR_OPC, IN_CONTR_TER, IN_CONTR_TST,
    IN_CONTR_BTC, IN_CONTA_MARGEM, TP_SITUAC, CD_ASSESSOR, NM_EMPRESA
)
SELECT DISTINCT
    TSCCLIGER.CD_CPFCGC,
    TSCCLIGER.NM_CLIENTE,
    TSCCLICC.CD_CLIENTE,
    TSCASSES.NM_ASSESSOR,
    ISNULL(TSCCLICTA.CD_BANCO,0) AS CD_BANCO,
    ISNULL(TSCCLICTA.CD_AGENCIA,0) AS CD_AGENCIA,
    CONCAT(ISNULL(TSCCLICTA.NR_CONTA,0),''-'',ISNULL(TSCCLICTA.DV_CONTA,0)) AS CONTA,
    ISNULL((SELECT SUM(CAST(TSCSFP.VL_BEN AS FLOAT)) FROM TSCSFP WHERE TSCSFP.CD_CPFCGC = TSCCLIGER.CD_CPFCGC AND CD_SFPGRUPO IN (1) AND CD_SFPSUBGRUPO IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15)),0) +
    ISNULL((SELECT SUM(CAST(TSCSFP.VL_BEN AS FLOAT)) FROM TSCSFP WHERE TSCSFP.CD_CPFCGC = TSCCLIGER.CD_CPFCGC AND CD_SFPGRUPO IN (2) AND CD_SFPSUBGRUPO IN (1,3,4,5,10)),0) +
    ISNULL((SELECT SUM(CAST(TSCSFP.VL_BEN AS FLOAT)) FROM TSCSFP WHERE TSCSFP.CD_CPFCGC = TSCCLIGER.CD_CPFCGC AND CD_SFPGRUPO IN (1,2) AND CD_SFPSUBGRUPO IN (2,6,7,9,12,13)),0) +
    ISNULL((SELECT SUM(CAST(TSCSFP.VL_BEN AS FLOAT)) FROM TSCSFP WHERE TSCSFP.CD_CPFCGC = TSCCLIGER.CD_CPFCGC AND CD_SFPGRUPO IN (2,3) AND CD_SFPSUBGRUPO IN (8,9,11)),0) +
    ISNULL((SELECT SUM(CAST(TSCSFP.VL_BEN AS FLOAT)) FROM TSCSFP WHERE TSCSFP.CD_CPFCGC = TSCCLIGER.CD_CPFCGC AND CD_SFPGRUPO IN (3) AND CD_SFPSUBGRUPO IN (1,2,3,4,5,6,7,10)),0) AS PATRIMONIO,
    ISNULL(TSCATIV.DS_ATIV,''-'') AS DS_ATIV,
    ISNULL((SELECT SUM(CAST(TSCSFP.VL_BEN AS FLOAT)) FROM TSCSFP WHERE TSCSFP.CD_CPFCGC = TSCCLIGER.CD_CPFCGC AND CD_SFPGRUPO IN (1) AND CD_SFPSUBGRUPO IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15)),0) AS [BENS IMÓVEIS],
    ISNULL((SELECT SUM(CAST(TSCSFP.VL_BEN AS FLOAT)) FROM TSCSFP WHERE TSCSFP.CD_CPFCGC = TSCCLIGER.CD_CPFCGC AND CD_SFPGRUPO IN (2) AND CD_SFPSUBGRUPO IN (1,3,4,5,10)),0) AS [BENS MÓVEIS],
    ISNULL((SELECT SUM(CAST(TSCSFP.VL_BEN AS FLOAT)) FROM TSCSFP WHERE TSCSFP.CD_CPFCGC = TSCCLIGER.CD_CPFCGC AND CD_SFPGRUPO IN (1,2) AND CD_SFPSUBGRUPO IN (2,6,7,9,12,13)),0) AS [APLICAÇÕES FINANCEIRAS],
    ISNULL((SELECT SUM(CAST(TSCSFP.VL_BEN AS FLOAT)) FROM TSCSFP WHERE TSCSFP.CD_CPFCGC = TSCCLIGER.CD_CPFCGC AND CD_SFPGRUPO IN (2,3) AND CD_SFPSUBGRUPO IN (8,9,11)),0) AS [SALÁRIO],
    ISNULL((SELECT SUM(CAST(TSCSFP.VL_BEN AS FLOAT)) FROM TSCSFP WHERE TSCSFP.CD_CPFCGC = TSCCLIGER.CD_CPFCGC AND CD_SFPGRUPO IN (3) AND CD_SFPSUBGRUPO IN (1,2,3,4,5,6,7,10)),0) AS [OUTROS RENDIMENTOS],
    CAST(0 AS FLOAT) AS DESPOSITO_BANCARIO,
    CAST(0 AS FLOAT) AS RENDA_FIXA,
    CAST(0 AS FLOAT) AS RENDA_VARIAVEL,
    CAST(0 AS FLOAT) AS VL_OPERACIONAL1,
    ISNULL(TSCDOCS.IN_CONTR_BOLSA,''N'') AS IN_CONTR_BOLSA,
    ISNULL(TSCDOCS.IN_CONTR_BMF,''N'') AS IN_CONTR_BMF,
    ISNULL(TSCDOCS.IN_CONTR_SOCIAL,''N'') AS IN_CONTR_SOCIAL,
    ISNULL(TSCDOCS.IN_CONTR_OPC,''N'') AS IN_CONTR_OPC,
    ISNULL(TSCDOCS.IN_CONTR_TER,''N'') AS IN_CONTR_TER,
    ISNULL(TSCDOCS.IN_CONTR_TST,''N'') AS IN_CONTR_TST,
    ISNULL(TSCDOCS.IN_CONTR_BTC,''N'') AS IN_CONTR_BTC,
    ISNULL(TSCDOCS.IN_CONTA_MARGEM,''N'') AS IN_CONTA_MARGEM,
    TSCCLIGER.TP_SITUAC,
    ISNULL(TSCASSES.CD_ASSESSOR,0) AS CD_ASSESSOR,
    ISNULL(TSCCLICOMP.NM_EMPRESA,''N'') AS NM_EMPRESA
FROM TSCCLIGER
LEFT JOIN TSCCLICC
  ON TSCCLIGER.CD_CPFCGC = TSCCLICC.CD_CPFCGC
 AND TSCCLIGER.DT_NASC_FUND = TSCCLICC.DT_NASC_FUND
 AND TSCCLIGER.CD_CON_DEP = TSCCLICC.CD_CON_DEP
LEFT JOIN TSCCLICTA
  ON TSCCLICTA.CD_CLIENTE = TSCCLICC.CD_CLIENTE
LEFT JOIN TSCCLICOMP
  ON TSCCLICOMP.CD_CPFCGC = TSCCLICC.CD_CPFCGC
 AND TSCCLICOMP.DT_NASC_FUND = TSCCLICC.DT_NASC_FUND
 AND TSCCLICOMP.CD_CON_DEP = TSCCLICC.CD_CON_DEP
LEFT JOIN TSCASSES
  ON TSCASSES.CD_ASSESSOR = TSCCLIGER.CD_ASSESSOR
LEFT JOIN TSCDOCS
  ON TSCCLIGER.CD_CPFCGC = TSCDOCS.CD_CPFCGC
 AND TSCCLIGER.DT_NASC_FUND = TSCDOCS.DT_NASC_FUND
 AND TSCCLIGER.CD_CON_DEP = TSCDOCS.CD_CON_DEP
LEFT JOIN TSCATIV
  ON TSCATIV.CD_ATIV = TSCCLICOMP.CD_ATIV
WHERE TSCCLIGER.TP_PESSOA = ''J''
  AND TSCCLICC.IN_CONTA_INV = ''N'';
';
EXEC sys.sp_executesql @sql;
	
-- ================================================
-- Marca DT_FIRA para registros carregados (fallback)
-- ================================================
DECLARE @__dt_fira_now DATETIME = GETDATE();
IF COL_LENGTH(N'dbo.ST_DADOS_FINANCEIROS_PJ', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE [dbo].[ST_DADOS_FINANCEIROS_PJ]
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL;
END 


 /******* fim do processo de carga **********/

--passo 3
/***** limpa a tabela do banco para nao ficar sujeira ******/
DROP TABLE IF EXISTS ST_DADOS_FINANCEIROS_PJ_PADRAO