CREATE PROCEDURE [dbo].[FIRA_PR_CARGA_ST_DADOS_FINANCEIROS_PF]
--WITH ENCRYPTION
AS

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ST_DADOS_FINANCEIROS_PF_PADRAO]') AND type in (N'U'))
CREATE TABLE [dbo].[ST_DADOS_FINANCEIROS_PF_PADRAO](
	[CPF] [varchar](20) NULL,
	[NM_CLIENTE] [varchar](160) NULL,
	[CD_CLIENTE] [int] NOT NULL,
	[ASSESSOR] [varchar](160) NULL,
	[CD_BANCO] [varchar](3) NULL,
	[AGENCIA] [varchar](5) NULL,
	[CONTA] [varchar](16) NULL,
	[PROF_ATIV] [varchar](60) NULL,
	[PATRIMONIO] [float] NULL,
	[CARGO] [varchar](140) NULL,
	[BENS_IMOV] [float] NULL,
	[BENS_MOV] [float] NULL,
	[APLICACOES_FINAN] [float] NULL,
	[SALARIO] [float] NULL,
	[OUTROS_REND] [float] NULL,
	[DESPOSITO_BANCARIO] [float] NULL,
	[RENDA_FIXA] [float] NULL,
	[RENDA_VARIAVEL] [float] NULL,
	[VL_OPERACIONAL1] [float] NULL,
	[IN_CONTR_BOLSA] [char](1) NULL,
	[IN_CONTR_BMF] [char](1) NULL,
	[IN_CONTR_SOCIAL] [char](1) NULL,
	[IN_CONTR_OPC] [char](1) NULL,
	[IN_CONTR_TER] [char](1) NULL,
	[IN_CONTR_TST] [char](1) NULL,
	[IN_CONTR_BTC] [char](1) NULL,
	[IN_CONTA_MARGEM] [char](1) NULL,
	[tp_situac] [char](2) NULL,
	[CD_ASSESSOR] [int] NULL,
	[NM_EMPRESA] [varchar](100) NULL,
	[DT_FIRA] DATETIME NULL
) ON [PRIMARY]


--/***************************************************
--inicio da comparação entre a tabela
--da base padrao fira origem x tabela cliente destino
--*****************************************************/
---- 1) Faz o sync (pode ficar estático)
EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo',, @src_table='ST_DADOS_FINANCEIROS_PF_PADRAO',
  @schema_name='dbo', @base_table='ST_DADOS_FINANCEIROS_PF',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1;

-- 2) TRUNCATE pode ficar estático
TRUNCATE TABLE ST_DADOS_FINANCEIROS_PF	
	
/**********************************************************************
3) INSERT em SQL dinâmico (compila após o ALTER) INSERT com lista 
explícita de colunas Isso evita dor de cabeça caso a tabela destino 
tenha colunas a mais, ordem diferente, identity, etc.
**********************************************************************/
DECLARE @sql nvarchar(max) = N'
INSERT INTO ST_DADOS_FINANCEIROS_PF	
(
	 [CPF],[NM_CLIENTE],[CD_CLIENTE],[ASSESSOR],[CD_BANCO],[AGENCIA],[CONTA]
	,[PROF_ATIV],[PATRIMONIO],[CARGO],[BENS_IMOV],[BENS_MOV],[APLICACOES_FINAN]
	,[SALARIO],[OUTROS_REND],[DESPOSITO_BANCARIO],[RENDA_FIXA],[RENDA_VARIAVEL]
	,[VL_OPERACIONAL1],[IN_CONTR_BOLSA],[IN_CONTR_BMF],[IN_CONTR_SOCIAL]
	,[IN_CONTR_OPC],[IN_CONTR_TER],[IN_CONTR_TST],[IN_CONTR_BTC],[IN_CONTA_MARGEM]
	,[tp_situac],[CD_ASSESSOR],[NM_EMPRESA]
)

SELECT DISTINCT	
 TSCCLIGER.CD_CPFCGC
,TSCCLIGER.NM_CLIENTE
,TSCCLICC.CD_CLIENTE
,ISNULL(TSCASSES.NM_ASSESSOR,''N'') ASSESSOR
,ISNULL(TSCCLICTA.CD_BANCO,0) AS CD_BANCO
,ISNULL(TSCCLICTA.CD_AGENCIA,0) AS CD_AGENCIA
,CONCAT(ISNULL(TSCCLICTA.NR_CONTA,0),''-'',ISNULL(TSCCLICTA.DV_CONTA,0)) CONTA
,TSCATIV.DS_ATIV
,ISNULL((SELECT SUM(CAST(TSCSFP.VL_BEN AS FLOAT)) FROM TSCSFP WHERE TSCSFP.CD_CPFCGC = TSCCLIGER.CD_CPFCGC AND CD_SFPGRUPO IN (1) AND CD_SFPSUBGRUPO IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15)),0) +
    ISNULL((SELECT SUM(CAST(TSCSFP.VL_BEN AS FLOAT)) FROM TSCSFP WHERE TSCSFP.CD_CPFCGC = TSCCLIGER.CD_CPFCGC AND CD_SFPGRUPO IN (2) AND CD_SFPSUBGRUPO IN (1,3,4,5,10)),0) +
    ISNULL((SELECT SUM(CAST(TSCSFP.VL_BEN AS FLOAT)) FROM TSCSFP WHERE TSCSFP.CD_CPFCGC = TSCCLIGER.CD_CPFCGC AND CD_SFPGRUPO IN (1,2) AND CD_SFPSUBGRUPO IN (2,6,7,9,12,13)),0) +
    ISNULL((SELECT SUM(CAST(TSCSFP.VL_BEN AS FLOAT)) FROM TSCSFP WHERE TSCSFP.CD_CPFCGC = TSCCLIGER.CD_CPFCGC AND CD_SFPGRUPO IN (2,3) AND CD_SFPSUBGRUPO IN (8,9,11)),0) +
    ISNULL((SELECT SUM(CAST(TSCSFP.VL_BEN AS FLOAT)) FROM TSCSFP WHERE TSCSFP.CD_CPFCGC = TSCCLIGER.CD_CPFCGC AND CD_SFPGRUPO IN (3) AND CD_SFPSUBGRUPO IN (1,2,3,4,5,6,7,10)),0) AS PATRIMONIO
,ISNULL(TSCCLICOMP.DS_CARGO,''N'') CARGO
,ISNULL((SELECT SUM(CAST(TSCSFP.VL_BEN AS FLOAT)) FROM TSCSFP WHERE TSCSFP.CD_CPFCGC = TSCCLIGER.CD_CPFCGC AND CD_SFPGRUPO IN (1) AND CD_SFPSUBGRUPO IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15)),0) AS [BENS IMÓVEIS]
,ISNULL((SELECT SUM(CAST(TSCSFP.VL_BEN AS FLOAT)) FROM TSCSFP WHERE TSCSFP.CD_CPFCGC = TSCCLIGER.CD_CPFCGC AND CD_SFPGRUPO IN (2) AND CD_SFPSUBGRUPO IN (1,3,4,5,10)),0) AS [BENS MÓVEIS]
,ISNULL((SELECT SUM(CAST(TSCSFP.VL_BEN AS FLOAT)) FROM TSCSFP WHERE TSCSFP.CD_CPFCGC = TSCCLIGER.CD_CPFCGC AND CD_SFPGRUPO IN (1,2) AND CD_SFPSUBGRUPO IN (2,6,7,9,12,13)),0) AS [APLICAÇÕES FINANCEIRAS]
,ISNULL((SELECT SUM(CAST(TSCSFP.VL_BEN AS FLOAT)) FROM TSCSFP WHERE TSCSFP.CD_CPFCGC = TSCCLIGER.CD_CPFCGC AND CD_SFPGRUPO IN (2,3) AND CD_SFPSUBGRUPO IN (8,9,11)),0) AS [SALÁRIO]
,ISNULL((SELECT SUM(CAST(TSCSFP.VL_BEN AS FLOAT)) FROM TSCSFP WHERE TSCSFP.CD_CPFCGC = TSCCLIGER.CD_CPFCGC AND CD_SFPGRUPO IN (3) AND CD_SFPSUBGRUPO IN (1,2,3,4,5,6,7,10)),0) AS [OUTROS RENDIMENTOS]
,CAST(0 AS FLOAT) AS DESPOSITO_BANCARIO
,CAST(0 AS FLOAT) AS RENDA_FIXA
,CAST(0 AS FLOAT) AS RENDA_VARIAVEL
,CAST(0 AS FLOAT) AS VL_OPERACIONAL1
,ISNULL(TSCDOCS.IN_CONTR_BOLSA,''N'')IN_CONTR_BOLSA
,ISNULL(TSCDOCS.IN_CONTR_BMF,''N'')IN_CONTR_BMF
,ISNULL(TSCDOCS.IN_CONTR_SOCIAL,''N'')IN_CONTR_SOCIAL	
,ISNULL(TSCDOCS.IN_CONTR_OPC,''N'')IN_CONTR_OPC
,ISNULL(TSCDOCS.IN_CONTR_TER,''N'')IN_CONTR_TER
,ISNULL(TSCDOCS.IN_CONTR_TST,''N'')IN_CONTR_TST
,ISNULL(TSCDOCS.IN_CONTR_BTC,''N'')IN_CONTR_BTC
,ISNULL(TSCDOCS.IN_CONTA_MARGEM,''N'')IN_CONTA_MARGEM	
,TSCCLIGER.TP_SITUAC	
,ISNULL(TSCASSES.CD_ASSESSOR,0) CD_ASSESSOR
,ISNULL(TSCCLICOMP.NM_EMPRESA,''N'')NM_EMPRESA	
FROM	
	   TSCCLIGER 	
	   LEFT OUTER JOIN TSCCLICC	
	   ON  TSCCLIGER.CD_CPFCGC = TSCCLICC.CD_CPFCGC	
	   AND TSCCLIGER.DT_NASC_FUND = TSCCLICC.DT_NASC_FUND	
	   AND TSCCLIGER.CD_CON_DEP = TSCCLICC.CD_CON_DEP	
	   LEFT OUTER JOIN TSCCLICTA	
	   ON  TSCCLICC.CD_CLIENTE  = TSCCLICTA.CD_CLIENTE  	
	   LEFT OUTER JOIN TSCCLICOMP	
	   ON  TSCCLICOMP.CD_CPFCGC = TSCCLICC.CD_CPFCGC	
	   AND TSCCLICOMP.DT_NASC_FUND = TSCCLICC.DT_NASC_FUND	
	   AND TSCCLICOMP.CD_CON_DEP = TSCCLICC.CD_CON_DEP	
	   LEFT OUTER JOIN TSCATIV	
	   ON TSCATIV.CD_ATIV = TSCCLICOMP.CD_ATIV 	
	   LEFT OUTER JOIN TSCDOCS	
	   ON  TSCCLIGER.CD_CPFCGC = TSCDOCS.CD_CPFCGC 	
	   AND TSCCLIGER.DT_NASC_FUND = TSCDOCS.DT_NASC_FUND 	
	   AND TSCCLIGER.CD_CON_DEP = TSCDOCS.CD_CON_DEP	
	   LEFT OUTER JOIN TSCASSES 	
	   ON TSCASSES.CD_ASSESSOR  = TSCCLIGER.CD_ASSESSOR 	
	   WHERE	
	   TSCCLIGER.TP_PESSOA = ''F''	
	   AND TSCCLICC.IN_CONTA_INV = ''N'';
';
EXEC sys.sp_executesql @sql;
 /******* fim do processo de carga **********/

-- ================================================
-- Marca DT_FIRA para registros carregados (fallback)
-- ================================================
DECLARE @__dt_fira_now DATETIME = GETDATE();
IF COL_LENGTH(N'dbo.ST_DADOS_FINANCEIROS_PF', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE [dbo].[ST_DADOS_FINANCEIROS_PF]
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL;
END 

--passo 3
--/***** limpa a tabela do banco para nao ficar sujeira ******/
DROP TABLE IF EXISTS ST_DADOS_FINANCEIROS_PF_PADRAO