CREATE PROCEDURE [dbo].[PR_LISTAATENCAOHISTORICO] 
(
	@IDUSUARIO INT,
	@NOME NVARCHAR(500),
	@CPFCNPJ VARCHAR(20),
	@DATAHORACONSULTAINICIO DATE,
	@DATAHORACONSULTAFIM DATE,
	@TIPOCONSULTA VARCHAR(50)
)--WITH ENCRYPTION
AS
BEGIN

	--DECLARE @IDUSUARIO INT, @NOME NVARCHAR(500), @CPFCNPJ VARCHAR(20), @DATAHORACONSULTAINICIO DATETIME, @DATAHORACONSULTAFIM DATETIME
	--SET @IDUSUARIO = 4
	--SET @NOME = NULL
	--SET @CPFCNPJ = NULL
	--SET @DATAHORACONSULTAINICIO = '2020-11-03'
	--SET @DATAHORACONSULTAFIM = '2020-11-03'

	SELECT CPFCNPJ, NOME, DATAHORA AS DATAHORACONSULTA, APONTADO, ID, TIPOCONSULTA FROM HISTORICOCONSULTAKYC
	WHERE IDUSUARIO = @IDUSUARIO
	AND (@TIPOCONSULTA IS NULL OR @TIPOCONSULTA = TIPOCONSULTA)
	AND (
	(@NOME IS NULL OR NOME LIKE '%' + @NOME + '%') 
	AND (@CPFCNPJ IS NULL OR CPFCNPJ = @CPFCNPJ) 
	AND ((@DATAHORACONSULTAINICIO IS NULL OR @DATAHORACONSULTAFIM IS NULL) OR CAST(DATAHORA AS DATE) BETWEEN @DATAHORACONSULTAINICIO AND @DATAHORACONSULTAFIM )
	)
	ORDER BY DATAHORA DESC

END