/****** Object:  StoredProcedure [dbo].[FIRA_PR_CARGA_ALERT_08_INSIDER_TRADING_02]    Script Date: 25/02/2026 15:50:21 ******/

 
CREATE PROCEDURE [dbo].[FIRA_PR_CARGA_ALERT_08_INSIDER_TRADING_02] @PREGAO SMALLDATETIME, @AUX INT
--WITH ENCRYPTION	
AS


/*************************************************************************************************
REGRA DO ALERTA:
Insider Trading consiste no uso indevido de informações privilegiadas, sendo detectado por uma metodologia 
que compara operações de compra e venda em períodos pré e pós- divulgação de informações relevantes,
utilizando a distância euclidiana para medir mudanças no perfil operacional dos investido.
(Distância Euclidiana Compra/Venda > Média da distância Euclidiana Compra/Venda; OU
Resultado Valorizou/
*************************************************************************************************/


 --passo 1
/**********************************
inicio da etapa de verificação
aqui temos o script da base padrao
***********************************/
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ST_ALERT_INSIDER_TRADING_02_PADRAO]') AND type in (N'U'))
CREATE TABLE [dbo].[ST_ALERT_INSIDER_TRADING_02_PADRAO](
	[DATA] [date] NULL,
	[CD_CLIENTE] [int] NOT NULL,
	[CD_PAPEL] [varchar](12) NOT NULL,
	[DT_FATO] [date] NULL,
	[FATO_RELEVANTE] [nvarchar](max) NULL,
	[PRECO_MEDIO_COMPRA_PRE] [numeric](17, 2) NULL,
	[PRECO_MEDIO_VENDA_PRE] [numeric](17, 2) NULL,
	[PRECO_MEDIO_COMPRA_POS] [numeric](17, 2) NULL,
	[PRECO_MEDIO_VENDA_POS] [numeric](17, 2) NULL,
	[QTDE_VALORIZOU] [int] NOT NULL,
	[QTDE_DESVALORIZOU] [int] NOT NULL,
	[RF_VALORIZOU] [numeric](17, 2) NULL,
	[RF_DESVALORIZOU] [numeric](17, 2) NULL,
	[RESULTADO] [numeric](17, 2) NULL,
	[AVG_INTERDAY_POS] [numeric](17, 2) NULL,
	[AVG_INTRADAY_POS] [numeric](17, 2) NULL,
	[DT_FIRA] DATETIME NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ST_INSIDER_TRADING_PADRAO]') AND type in (N'U'))
CREATE TABLE [dbo].[ST_INSIDER_TRADING_PADRAO](
	[DATA] [date] NULL,
	[CD_CLIENTE] [int]  NULL,
	[CD_PAPEL] [varchar](12) NOT NULL,
	[DT_FATO] [date] NULL,
	[FATO_RELEVANTE] [nvarchar](max) NULL,
	[PRECO_MEDIO_COMPRA_PRE] [numeric](17, 2) NULL,
	[PRECO_MEDIO_VENDA_PRE] [numeric](17, 2) NULL,
	[PRECO_MEDIO_COMPRA_POS] [numeric](17, 2) NULL,
	[PRECO_MEDIO_VENDA_POS] [numeric](17, 2) NULL,
	[QTDE_VALORIZOU] [int] NOT NULL,
	[QTDE_DESVALORIZOU] [int] NOT NULL,
	[RF_VALORIZOU] [numeric](17, 2) NULL,
	[RF_DESVALORIZOU] [numeric](17, 2) NULL,
	[RESULTADO] [numeric](17, 2) NULL,
	[AVG_INTERDAY_POS] [numeric](17, 2) NULL,
	[AVG_INTRADAY_POS] [numeric](17, 2) NULL,
	[ALERTA] [char](1) NULL,
	[DT_FIRA] DATETIME NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

 
 
/***************************************************
inicio da comparação entre a tabela
da base padrao fira origem x tabela cliente destino
*****************************************************/
EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo', @src_table='ST_ALERT_INSIDER_TRADING_02_PADRAO',
  @schema_name='dbo', @base_table='ST_ALERT_INSIDER_TRADING_02',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1;


EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo', @src_table='ST_INSIDER_TRADING_PADRAO',
  @schema_name='dbo', @base_table='ST_INSIDER_TRADING',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1; 
/******** fim da etapa de verificação ************/


/*********inicio da carga do alerta*******/
 
--DECLARE @PREGAO SMALLDATETIME, @AUX INT
--SET @PREGAO = '20260205'
--SET @AUX = (SELECT DAY(@PREGAO))

DECLARE @DT_INICIO DATE , @DT_FIM DATE , @CD_ANOMES INT

SET @CD_ANOMES = (SELECT MAX(CD_ANOMES) FROM ST_PERIODO WHERE DT_PERIODO = DATEADD(DAY,-@AUX,@PREGAO))
SET @DT_INICIO = (SELECT MIN(DT_PERIODO) fROM ST_PERIODO WHERE CD_ANOMES = @CD_ANOMES)
SET @DT_FIM	   = (SELECT MAX(DT_PERIODO) fROM ST_PERIODO WHERE CD_ANOMES = @CD_ANOMES)

DROP TABLE IF EXISTS  #FATO;	

	SELECT 
  DISTINCT A.EMPRESA								AS EMPRESA
		 , A.FATORELEVANTE							AS FATO_RELEVANTEATIVO
		 , DATA										AS DT_PERIODO
		 , ATIVO									AS ATIVO
		 , dbo.ObterDataHST(dbo.ObterDataPRE(DATA)) AS DT_COMP
		 , dbo.ObterDataPRE(DATA)					AS DT_PRE
		 , DATA										AS DT_FATO
		 , dbo.ObterDataPOS(DATA)					AS DT_POS
	 INTO #FATO
	 FROM FatosRelevantes  A
	WHERE Data >= @DT_INICIO
	  AND DATA <= @DT_FIM
 ORDER BY DATA ASC;

 -----------------------------------------------------------------------------
 DECLARE @DT_MIN_DAT SMALLDATETIME 
		,@DT_MAX_DAT SMALLDATETIME 
		,@DT_MIN_DAT_AUX SMALLDATETIME 
	    ,@DT_MAX_DAT_AUX SMALLDATETIME 

SET @DT_MIN_DAT     = (SELECT MIN(DT_COMP) FROM #FATO)
SET @DT_MAX_DAT     = (SELECT MAX(DT_POS) FROM #FATO)
SET @DT_MIN_DAT_AUX = (SELECT TOP 1 DT_PERIODO fROM ST_PERIODO WHERE DT_PERIODO < @DT_MIN_DAT ORDER BY ID_PERIODO DESC)

 

DROP TABLE IF EXISTS #BASE_MERCADO;
DROP TABLE IF EXISTS #ST_ATIVO_BOVESPA_AUX;
	 
	 SELECT 
	DISTINCT * 
		   , SUBSTRING(CODNEG,1,4) AS ATIVO 
	    INTO #ST_ATIVO_BOVESPA_AUX 
	    FROM ST_ATIVO_BOVESPA  	
	   WHERE DT_PERIODO >= @DT_MIN_DAT_AUX
	     AND DT_PERIODO <= @DT_MAX_DAT;
	
   WITH ATIVO_BVSP AS(

		   SELECT DT_PERIODO
				, LAG(DT_PERIODO,1) OVER (PARTITION BY CODNEG ORDER BY DT_PERIODO asc) AS  DT_PERIODO_ANT
				, CODNEG
				, ATIVO
				, PREABE
				, PREULT
				, LAG(PREULT,1) OVER (PARTITION BY CODNEG ORDER BY DT_PERIODO asc ) AS  PREULT_ANT
				, VOLTOT
				, TOTNEG 
			 FROM #ST_ATIVO_BOVESPA_AUX A
			WHERE EXISTS (SELECT 1 FROM #FATO B WHERE a.ativo = B.ATIVO) 

				)

		SELECT A.ATIVO
			 , B.CODNEG CD_PAPEL
			 , B.DT_PERIODO DT_PREGAO
			 , A.DT_COMP
			 , A.DT_PRE
			 , A.DT_FATO
			 , A.DT_POS
			 , DT_PERIODO_ANT DT_ANT
			 , B.PREABE
			 , B.PREULT
			 , isnull(PREULT_ANT,0) AS REULT_ANT
			 , B.VOLTOT
			 , B.TOTNEG		 
			 , ISNULL(CAST((B.PREULT / NULLIF(B.PREABE,0)) -1 AS NUMERIC(17,2)),0)  AS INTRADAY		
			 , ISNULL(CAST((B.PREABE / NULLIF(B.PREULT_ANT,0))-1 AS NUMERIC(17,2)),0)	AS INTERDAY
	      INTO #BASE_MERCADO
		  FROM #FATO A 
	INNER JOIN ATIVO_BVSP B
			ON A.ATIVO = B.ATIVO
		 WHERE a.DT_PERIODO >= @DT_MIN_DAT
	       AND a.DT_PERIODO <= @DT_MAX_DAT;

---- ativo comp
 DROP TABLE IF EXISTS #COMP;
		SELECT ATIVO
			 , CD_PAPEL
			 , DT_COMP
			 , DT_PRE
			 , DT_FATO
			 , CAST(AVG(PREABE	) AS NUMERIC(17,2))AVG_PREABE_COMP
			 , CAST(AVG(PREULT	) AS NUMERIC(17,2))AVG_PREULT_COMP
			 , CAST(AVG(VOLTOT	) AS NUMERIC(17,2))AVG_VOLTOT_COMP
			 , CAST(AVG(TOTNEG	) AS NUMERIC(17,2))AVG_TOTNEG_COMP
			 , CAST(AVG(INTRADAY) AS NUMERIC(17,2))AVG_INTRADAY_COMP		
			 , CAST(AVG(INTERDAY) AS NUMERIC(17,2))AVG_INTERDAY_COMP
		  
		  INTO #COMP
		  FROM #BASE_MERCADO
		 WHERE DT_PREGAO >= DT_COMP
		   AND DT_PREGAO <= DT_PRE
	  GROUP BY ATIVO
			 , CD_PAPEL
			 , DT_COMP
			 , DT_PRE
			 , DT_FATO

CREATE NONCLUSTERED INDEX IDX01_COMP
ON [dbo].[#COMP] ([ATIVO],[DT_FATO])
INCLUDE ([CD_PAPEL],[DT_COMP])

DROP TABLE IF EXISTS #PRE;
		SELECT ATIVO
			 , CD_PAPEL
			 , DT_PRE
			 , DT_FATO
			 , CAST(AVG(PREABE	) AS NUMERIC(17,2))AVG_PREABE_PRE
			 , CAST(AVG(PREULT	) AS NUMERIC(17,2))AVG_PREULT_PRE
			 , CAST(AVG(VOLTOT	) AS NUMERIC(17,2))AVG_VOLTOT_PRE
			 , CAST(AVG(TOTNEG	) AS NUMERIC(17,2))AVG_TOTNEG_PRE
			 , CAST(AVG(INTRADAY) AS NUMERIC(17,2))AVG_INTRADAY_PRE		
			 , CAST(AVG(INTERDAY) AS NUMERIC(17,2))AVG_INTERDAY_PRE
		  
		  INTO #PRE
		  FROM #BASE_MERCADO
		 WHERE DT_PREGAO >= DT_PRE 
		   AND DT_PREGAO < DT_FATO
	  GROUP BY ATIVO
			 , CD_PAPEL
			 , DT_PRE
			 , DT_FATO
			
DROP TABLE IF EXISTS #POS;
		SELECT ATIVO
			 , CD_PAPEL			 
			 , DT_FATO
			 , DT_POS
			 , CAST(AVG(PREABE	) AS NUMERIC(17,2))AVG_PREABE_POS
			 , CAST(AVG(PREULT	) AS NUMERIC(17,2))AVG_PREULT_POS
			 , CAST(AVG(VOLTOT	) AS NUMERIC(17,2))AVG_VOLTOT_POS
			 , CAST(AVG(TOTNEG	) AS NUMERIC(17,2))AVG_TOTNEG_POS
			 , CAST(AVG(INTRADAY) AS NUMERIC(17,2))AVG_INTRADAY_POS		
			 , CAST(AVG(INTERDAY) AS NUMERIC(17,2))AVG_INTERDAY_POS
		  
		  INTO #POS
		  FROM #BASE_MERCADO
		 WHERE DT_PREGAO >= DT_FATO
		   AND DT_PREGAO <= DT_POS
	  GROUP BY ATIVO
			 , CD_PAPEL
			 , DT_POS
			 , DT_FATO

			CREATE INDEX IDX_COMP ON #COMP (ATIVO,DT_FATO,CD_PAPEL)
			CREATE INDEX IDX_PRE  ON #PRE (ATIVO,DT_FATO,CD_PAPEL)
			CREATE INDEX IDX_POS  ON #POS (ATIVO,DT_FATO,CD_PAPEL)
			CREATE INDEX IDX_FATO ON #FATO (ATIVO,DT_FATO)
------------------------------------------------------------------
---cliente
DROP TABLE IF EXISTS #FATO_CLI;


	  SELECT A.ATIVO 
		   , A.CD_PAPEL 
		   , A.DT_COMP
		   , B.DT_PRE
		   , A.DT_FATO 
		   , C.DT_POS
		   , D.EMPRESA 
		  , D.FATO_RELEVANTEATIVO
		  , A.AVG_INTERDAY_COMP
		  , A.AVG_INTRADAY_COMP
		  , B.AVG_INTERDAY_PRE
		  , B.AVG_INTRADAY_PRE
		  , C.AVG_INTERDAY_POS
		  , C.AVG_INTRADAY_POS
		INTO #FATO_CLI
		FROM #COMP A
		JOIN #PRE B 
		  ON B.ATIVO = A.ATIVO 
		 AND B.DT_FATO = A.DT_FATO
		 AND B.CD_PAPEL = A.CD_PAPEL
		JOIN #POS C 
		  ON C.ATIVO = A.ATIVO 
		 AND C.DT_FATO = A.DT_FATO
		 AND C.CD_PAPEL = A.CD_PAPEL
		JOIN #FATO D 
		  ON A.ATIVO = D.ATIVO 
		 AND A.DT_FATO = D.DT_FATO;

CREATE NONCLUSTERED INDEX IDX01_FATO_CLI
ON [dbo].[#FATO_CLI] ([CD_PAPEL],[DT_COMP],[DT_PRE],[DT_FATO],[DT_POS])
INCLUDE ([AVG_INTERDAY_COMP],[AVG_INTRADAY_COMP],[AVG_INTERDAY_PRE],[AVG_INTRADAY_PRE],[AVG_INTERDAY_POS],[AVG_INTRADAY_POS])

	-----------------------------------------------------
	--- PRE - INICIO ------------------------------------

	DROP TABLE IF EXISTS #PRE_CLI;
WITH PRE_C AS (		
	   SELECT CD_CLIENTE
		    , A.CD_PAPEL
		    , COUNT(NR_NEGOCIO) QT_NEGOCIO_COMPRA_PRE
			, SUM(QT_NEGOCIO) QT_NEGOCIADA_COMPRA_PRE
			, SUM(VL_TOTNEG) VOLUME_COMPRA_PRE
			, AVG(QT_NEGOCIO) AVG_QT_NEGOCIADA_COMPRA_PRE
			, AVG(VL_NEGOCIO) AVG_VL_NEGOCIO_COMPRA_PRE
			, SUM(VL_NEGOCIO * QT_NEGOCIO) / SUM(QT_NEGOCIO) AVGP_VL_NEGOCIO_COMPRA_PRE
		    , B.DT_FATO
			, B.DT_COMP
			, B.DT_PRE
			, B.DT_POS
		 FROM ST_MESA_BVSP A 
   INNER JOIN #FATO_CLI B
		   ON A.CD_PAPEL = B.CD_PAPEL
		WHERE A.DT_PERIODO >= B.DT_PRE AND A.DT_PERIODO < B.DT_FATO  --periodo comparativo
		AND CD_NATOPE = 'C'
		
	 GROUP BY CD_CLIENTE
			, A.CD_PAPEL
			, B.DT_POS
			, B.DT_FATO
			, B.DT_COMP
			, B.DT_PRE
			)
			,PRE_V AS (
	
	   SELECT CD_CLIENTE
		    , A.CD_PAPEL
		    , COUNT(NR_NEGOCIO) QT_NEGOCIO_VENDA_PRE
			, SUM(QT_NEGOCIO)   QT_NEGOCIADA_VENDA_PRE
			, SUM(VL_TOTNEG)    VOLUME_VENDA_PRE
			, AVG(QT_NEGOCIO)   AVG_QT_NEGOCIADA_VENDA_PRE
			, AVG(VL_NEGOCIO) AVG_VL_NEGOCIO_VENDA_PRE
			, SUM(VL_NEGOCIO * QT_NEGOCIO) / SUM(QT_NEGOCIO) AVGP_VL_NEGOCIO_VENDA_PRE
		    , B.DT_FATO		    
			, B.DT_COMP
			, B.DT_PRE
			, B.DT_POS
			
		 FROM ST_MESA_BVSP A 
   INNER JOIN #FATO_CLI B
		   ON A.CD_PAPEL = B.CD_PAPEL
		WHERE A.DT_PERIODO >= B.DT_PRE AND A.DT_PERIODO < B.DT_FATO ---periodo comparativo
		AND CD_NATOPE = 'V'
		
	 GROUP BY CD_CLIENTE
			, A.CD_PAPEL 
			, B.DT_POS
			, B.DT_FATO
			, B.DT_COMP
			, B.DT_PRE
		
	),PRE AS (
	
	SELECT CD_CLIENTE,CD_PAPEL,DT_COMP,DT_PRE,DT_FATO,DT_POS FROM PRE_C

	UNION
	SELECT CD_CLIENTE,CD_PAPEL,DT_COMP,DT_PRE,DT_FATO,DT_POS FROM PRE_V

	)	
	
		SELECT A.CD_CLIENTE
			 , A.CD_PAPEL
			 , A.DT_COMP
			 , A.DT_PRE
			 , A.DT_FATO
			 , A.DT_POS
			 , ISNULL(C.QT_NEGOCIADA_COMPRA_PRE,0)	   AS QT_NEGOCIADA_COMPRA_PRE
			 , ISNULL(C.QT_NEGOCIO_COMPRA_PRE,0)	   AS QT_NEGOCIO_COMPRA_PRE
			 , ISNULL(C.VOLUME_COMPRA_PRE,0)		   AS VOLUME_COMPRA_PRE
			 , ISNULL(C.AVG_QT_NEGOCIADA_COMPRA_PRE,0) AS AVG_QT_NEGOCIADA_COMPRA_PRE
			 , ISNULL(C.AVG_VL_NEGOCIO_COMPRA_PRE,0)   AS AVG_VL_NEGOCIO_COMPRA_PRE
			 , ISNULL(V.QT_NEGOCIADA_VENDA_PRE,0)	   AS QT_NEGOCIADA_VENDA_PRE
			 , ISNULL(V.QT_NEGOCIO_VENDA_PRE,0)		   AS QT_NEGOCIO_VENDA_PRE
			 , ISNULL(V.VOLUME_VENDA_PRE,0)			   AS VOLUME_VENDA_PRE
			 , ISNULL(V.AVG_QT_NEGOCIADA_VENDA_PRE,0)  AS AVG_QT_NEGOCIADA_VENDA_PRE
			 , ISNULL(V.AVG_VL_NEGOCIO_VENDA_PRE,0)    AS AVG_VL_NEGOCIO_VENDA_PRE
			 , ISNULL(C.AVGP_VL_NEGOCIO_COMPRA_PRE,0)  AS AVGP_VL_NEGOCIO_COMPRA_PRE
			 , ISNULL(V.AVGP_VL_NEGOCIO_VENDA_PRE,0)   AS AVGP_VL_NEGOCIO_VENDA_PRE
		 INTO #PRE_CLI
		 FROM PRE A
	LEFT JOIN PRE_C C
		   ON A.CD_CLIENTE = C.CD_CLIENTE
		  AND A.CD_PAPEL = C.CD_PAPEL
		  AND A.DT_FATO = C.DT_FATO
		  AND A.DT_PRE  = C.DT_PRE
	LEFT JOIN PRE_V V 
		   ON  A.CD_CLIENTE = V.CD_CLIENTE
		  AND A.CD_PAPEL = V.CD_PAPEL
		  AND A.DT_FATO = V.DT_FATO	
		  AND A.DT_PRE = V.DT_PRE

	CREATE NONCLUSTERED INDEX IDX01_PRE_CLI
	ON [dbo].[#PRE_CLI] ([CD_CLIENTE],[CD_PAPEL],[DT_FATO])
	INCLUDE ([DT_COMP],[DT_PRE],[DT_POS],[QT_NEGOCIADA_COMPRA_PRE],[QT_NEGOCIO_COMPRA_PRE],[VOLUME_COMPRA_PRE],[AVG_QT_NEGOCIADA_COMPRA_PRE],[AVG_VL_NEGOCIO_COMPRA_PRE],[QT_NEGOCIADA_VENDA_PRE],[QT_NEGOCIO_VENDA_PRE],[VOLUME_VENDA_PRE],[AVG_QT_NEGOCIADA_VENDA_PRE],[AVG_VL_NEGOCIO_VENDA_PRE],[AVGP_VL_NEGOCIO_COMPRA_PRE],[AVGP_VL_NEGOCIO_VENDA_PRE])


	-----------------------------------------------------
	--- PRE - FIM ---------------------------------------

	-----------------------------------------------------
	--- COMPARATIVO - INICIO ----------------------------
DROP TABLE IF EXISTS #COMP_CLI;
WITH COMP_C AS (		
	   SELECT CD_CLIENTE
		    , A.CD_PAPEL
		    , COUNT(NR_NEGOCIO) QT_NEGOCIO_COMPRA_COMP
			, SUM(QT_NEGOCIO) QT_NEGOCIADA_COMPRA_COMP
			, SUM(VL_TOTNEG) VOLUME_COMPRA_COMP
			, AVG(QT_NEGOCIO) AVG_QT_NEGOCIADA_COMPRA_COMP
			, AVG(VL_NEGOCIO) AVG_VL_NEGOCIO_COMPRA_COMP
			, SUM(VL_NEGOCIO * QT_NEGOCIO) / SUM(QT_NEGOCIO) AVGP_VL_NEGOCIO_COMPRA_COMP
		    , B.DT_FATO
			, B.DT_COMP
			, B.DT_PRE
			, B.DT_POS
		 FROM ST_MESA_BVSP A 
   INNER JOIN #FATO_CLI B
		   ON A.CD_PAPEL = B.CD_PAPEL
		WHERE A.DT_PERIODO >= B.DT_COMP AND A.DT_PERIODO < B.DT_PRE  --periodo comparativo
		AND CD_NATOPE = 'C'
		  AND EXISTS (SELECT 1 
						FROM #PRE_CLI C 
					   WHERE A.CD_CLIENTE = C.CD_CLIENTE 
					     AND A.CD_PAPEL   = C.CD_PAPEL )	
	 GROUP BY CD_CLIENTE
			, A.CD_PAPEL
			, B.DT_POS
			, B.DT_FATO
			, B.DT_COMP
			, B.DT_PRE
			) 
			,COMP_V AS (
	
	   SELECT CD_CLIENTE
		    , A.CD_PAPEL
		    , COUNT(NR_NEGOCIO) QT_NEGOCIO_VENDA_COMP
			, SUM(QT_NEGOCIO)   QT_NEGOCIADA_VENDA_COMP
			, SUM(VL_TOTNEG)    VOLUME_VENDA_COMP
			, AVG(QT_NEGOCIO)   AVG_QT_NEGOCIADA_VENDA_COMP
			, AVG(VL_NEGOCIO) AVG_VL_NEGOCIO_VENDA_COMP
			, SUM(VL_NEGOCIO * QT_NEGOCIO) / SUM(QT_NEGOCIO) AVGP_VL_NEGOCIO_VENDA_COMP
		    , B.DT_FATO		    
			, B.DT_COMP
			, B.DT_PRE
			, B.DT_POS
		 FROM ST_MESA_BVSP A 
   INNER JOIN #FATO_CLI B
		   ON A.CD_PAPEL = B.CD_PAPEL
		WHERE A.DT_PERIODO >= B.DT_COMP AND A.DT_PERIODO < B.DT_PRE ---periodo comparativo
		AND CD_NATOPE = 'V'
		  AND EXISTS (SELECT 1 
						FROM #PRE_CLI C 
					   WHERE A.CD_CLIENTE = C.CD_CLIENTE 
					     AND A.CD_PAPEL   = C.CD_PAPEL)		 
	 GROUP BY CD_CLIENTE
			, A.CD_PAPEL 
			, B.DT_POS
			, B.DT_FATO
			, B.DT_COMP
			, B.DT_PRE
		
	), COMP AS (
	
	SELECT CD_CLIENTE,CD_PAPEL,DT_COMP,DT_PRE,DT_FATO,DT_POS FROM COMP_C
	UNION
	SELECT CD_CLIENTE,CD_PAPEL,DT_COMP,DT_PRE,DT_FATO,DT_POS FROM COMP_V
	)	
	
		SELECT A.CD_CLIENTE
			 , A.CD_PAPEL
			 , A.DT_COMP
			 , A.DT_PRE
			 , A.DT_FATO
			 , A.DT_POS
			 , ISNULL(C.QT_NEGOCIADA_COMPRA_COMP,0)		AS QT_NEGOCIADA_COMPRA_COMP
			 , ISNULL(C.QT_NEGOCIO_COMPRA_COMP,0)		AS QT_NEGOCIO_COMPRA_COMP
			 , ISNULL(C.VOLUME_COMPRA_COMP,0)			AS VOLUME_COMPRA_COMP
			 , ISNULL(C.AVG_QT_NEGOCIADA_COMPRA_COMP,0) AS AVG_QT_NEGOCIADA_COMPRA_COMP
			 , ISNULL(C.AVG_VL_NEGOCIO_COMPRA_COMP,0)	AS AVG_VL_NEGOCIO_COMPRA_COMP
			 , ISNULL(V.QT_NEGOCIADA_VENDA_COMP,0)		AS QT_NEGOCIADA_VENDA_COMP
			 , ISNULL(V.QT_NEGOCIO_VENDA_COMP,0)		AS QT_NEGOCIO_VENDA_COMP
			 , ISNULL(V.VOLUME_VENDA_COMP,0)			AS VOLUME_VENDA_COMP
			 , ISNULL(V.AVG_QT_NEGOCIADA_VENDA_COMP,0)  AS AVG_QT_NEGOCIADA_VENDA_COMP
			 , ISNULL(V.AVG_VL_NEGOCIO_VENDA_COMP,0)    AS AVG_VL_NEGOCIO_VENDA_COMP
			 , ISNULL(C.AVGP_VL_NEGOCIO_COMPRA_COMP,0)  AS AVGP_VL_NEGOCIO_COMPRA_COMP
			 , ISNULL(V.AVGP_VL_NEGOCIO_VENDA_COMP,0)   AS AVGP_VL_NEGOCIO_VENDA_COMP
		 INTO #COMP_CLI
		 FROM COMP   A
	LEFT JOIN COMP_C C
		   ON A.CD_CLIENTE = C.CD_CLIENTE
		  AND A.CD_PAPEL   = C.CD_PAPEL
		  AND A.DT_FATO    = C.DT_FATO
		  AND A.DT_COMP	   = C.DT_COMP
	LEFT JOIN COMP_V V 
		   ON  A.CD_CLIENTE = V.CD_CLIENTE
		  AND A.CD_PAPEL    = V.CD_PAPEL
		  AND A.DT_FATO     = V.DT_FATO
		  AND A.DT_COMP	    = V.DT_COMP

	-----------------------------------------------------
	--- COMPARATIVO - FIM -------------------------------

	-----------------------------------------------------
	--- POS - INICIO ------------------------------------
DROP TABLE IF EXISTS #POS_CLI;
WITH POS_C AS (		
	   SELECT CD_CLIENTE
		    , A.CD_PAPEL
		    , COUNT(NR_NEGOCIO) QT_NEGOCIO_COMPRA_POS
			, SUM(QT_NEGOCIO) QT_NEGOCIADA_COMPRA_POS
			, SUM(VL_TOTNEG) VOLUME_COMPRA_POS
			, AVG(QT_NEGOCIO) AVG_QT_NEGOCIADA_COMPRA_POS
			, AVG(VL_NEGOCIO) AVG_VL_NEGOCIO_COMPRA_POS
			, SUM(VL_NEGOCIO * QT_NEGOCIO) / SUM(QT_NEGOCIO) AVGP_VL_NEGOCIO_COMPRA_POS
		    , B.DT_FATO
			, B.DT_COMP
			, B.DT_PRE
			, B.DT_POS
		 FROM ST_MESA_BVSP A 
   INNER JOIN #FATO_CLI B
		   ON A.CD_PAPEL = B.CD_PAPEL
		WHERE A.DT_PERIODO >= B.DT_FATO AND A.DT_PERIODO < B.DT_POS  --periodo comparativo
		AND CD_NATOPE = 'C'
		
		
	 GROUP BY CD_CLIENTE
			, A.CD_PAPEL
			, B.DT_POS
			, B.DT_FATO
			, B.DT_COMP
			, B.DT_PRE
			)
			,POS_V AS (
	
	   SELECT CD_CLIENTE
		    , A.CD_PAPEL
		    , COUNT(NR_NEGOCIO) QT_NEGOCIO_VENDA_POS
			, SUM(QT_NEGOCIO)   QT_NEGOCIADA_VENDA_POS
			, SUM(VL_TOTNEG)    VOLUME_VENDA_POS
			, AVG(QT_NEGOCIO)   AVG_QT_NEGOCIADA_VENDA_POS
			, AVG(VL_NEGOCIO)   AVG_VL_NEGOCIO_VENDA_POS
			, SUM(VL_NEGOCIO * QT_NEGOCIO) / SUM(QT_NEGOCIO) AVGP_VL_NEGOCIO_VENDA_POS
		    , B.DT_FATO		    
			, B.DT_COMP
			, B.DT_PRE
			, B.DT_POS
			
		 FROM ST_MESA_BVSP A 
   INNER JOIN #FATO_CLI B
		   ON A.CD_PAPEL = B.CD_PAPEL
		WHERE A.DT_PERIODO >= B.DT_FATO AND A.DT_PERIODO < B.DT_POS ---periodo comparativo
		AND CD_NATOPE = 'V'
		
	 GROUP BY CD_CLIENTE
			, A.CD_PAPEL 
			, B.DT_POS
			, B.DT_FATO
			, B.DT_COMP
			, B.DT_PRE
		
	),POS AS (
	
	SELECT CD_CLIENTE,CD_PAPEL,DT_COMP,DT_PRE,DT_FATO,DT_POS FROM POS_C

	UNION
	SELECT CD_CLIENTE,CD_PAPEL,DT_COMP,DT_PRE,DT_FATO,DT_POS FROM POS_V

	)	
	
		SELECT A.CD_CLIENTE
			 , A.CD_PAPEL
			 , A.DT_COMP
			 , A.DT_PRE
			 , A.DT_FATO
			 , A.DT_POS
			 , ISNULL(C.QT_NEGOCIADA_COMPRA_POS,0)	   AS QT_NEGOCIADA_COMPRA_POS
			 , ISNULL(C.QT_NEGOCIO_COMPRA_POS,0)	   AS QT_NEGOCIO_COMPRA_POS
			 , ISNULL(C.VOLUME_COMPRA_POS,0)		   AS VOLUME_COMPRA_POS
			 , ISNULL(C.AVG_QT_NEGOCIADA_COMPRA_POS,0) AS AVG_QT_NEGOCIADA_COMPRA_POS
			 , ISNULL(C.AVG_VL_NEGOCIO_COMPRA_POS,0)   AS AVG_VL_NEGOCIO_COMPRA_POS
			 , ISNULL(V.QT_NEGOCIADA_VENDA_POS,0)	   AS QT_NEGOCIADA_VENDA_POS
			 , ISNULL(V.QT_NEGOCIO_VENDA_POS,0)		   AS QT_NEGOCIO_VENDA_POS
			 , ISNULL(V.VOLUME_VENDA_POS,0)			   AS VOLUME_VENDA_POS
			 , ISNULL(V.AVG_QT_NEGOCIADA_VENDA_POS,0)  AS AVG_QT_NEGOCIADA_VENDA_POS
			 , ISNULL(V.AVG_VL_NEGOCIO_VENDA_POS,0)	   AS AVG_VL_NEGOCIO_VENDA_POS
			 , ISNULL(C.AVGP_VL_NEGOCIO_COMPRA_POS,0)  AS AVGP_VL_NEGOCIO_COMPRA_POS
			 , ISNULL(V.AVGP_VL_NEGOCIO_VENDA_POS,0)   AS AVGP_VL_NEGOCIO_VENDA_POS

		 INTO #POS_CLI
		 FROM POS A
	LEFT JOIN POS_C C
		   ON A.CD_CLIENTE = C.CD_CLIENTE
		  AND A.CD_PAPEL = C.CD_PAPEL
		  AND A.DT_FATO = C.DT_FATO
		  AND A.DT_POS = C.DT_POS
	LEFT JOIN POS_V V 
		   ON  A.CD_CLIENTE = V.CD_CLIENTE
		  AND A.CD_PAPEL = V.CD_PAPEL
		  AND A.DT_FATO = V.DT_FATO	
		  AND A.DT_POS = C.DT_POS

	-----------------------------------------------------
	--- POS - FIM ---------------------------------------

	DROP TABLE IF EXISTS #ANALISE;
	   SELECT A.* 
			, isnull(B.QT_NEGOCIADA_COMPRA_COMP,0)	    AS QT_NEGOCIADA_COMPRA_COMP
			, isnull(B.QT_NEGOCIO_COMPRA_COMP,0)	    AS QT_NEGOCIO_COMPRA_COMP
			, isnull(B.VOLUME_COMPRA_COMP,0)			AS VOLUME_COMPRA_COMP
			, isnull(B.AVG_QT_NEGOCIADA_COMPRA_COMP,0)  AS AVG_QT_NEGOCIADA_COMPRA_COMP
			, isnull(B.AVG_VL_NEGOCIO_COMPRA_COMP,0)	AS AVG_VL_NEGOCIO_COMPRA_COMP
			, isnull(B.QT_NEGOCIADA_VENDA_COMP,0)		AS QT_NEGOCIADA_VENDA_COMP			
			, isnull(B.QT_NEGOCIO_VENDA_COMP,0)			AS QT_NEGOCIO_VENDA_COMP		
			, isnull(B.VOLUME_VENDA_COMP,0)				AS VOLUME_VENDA_COMP
			, isnull(B.AVG_QT_NEGOCIADA_VENDA_COMP,0)	AS AVG_QT_NEGOCIADA_VENDA_COMP
			, isnull(B.AVG_VL_NEGOCIO_VENDA_COMP,0)		AS AVG_VL_NEGOCIO_VENDA_COMP
			, isnull(b.AVGP_VL_NEGOCIO_COMPRA_COMP,0)   AS  AVGP_VL_NEGOCIO_COMPRA_COMP 
			, isnull(b.AVGP_VL_NEGOCIO_VENDA_COMP,0)    AS  AVGP_VL_NEGOCIO_VENDA_COMP
			, C.QT_NEGOCIADA_COMPRA_POS
			, C.QT_NEGOCIO_COMPRA_POS
			, C.VOLUME_COMPRA_POS
			, C.AVG_QT_NEGOCIADA_COMPRA_POS
			, C.AVG_VL_NEGOCIO_COMPRA_POS
			, C.QT_NEGOCIADA_VENDA_POS		
			, C.QT_NEGOCIO_VENDA_POS			
			, C.VOLUME_VENDA_POS
			, C.AVG_QT_NEGOCIADA_VENDA_POS
			, C.AVG_VL_NEGOCIO_VENDA_POS
			, C.AVGP_VL_NEGOCIO_COMPRA_POS
			, C.AVGP_VL_NEGOCIO_VENDA_POS
			,CAST(a.DT_COMP AS DATETIME)DT_COMP_2
			,CAST(a.DT_PRE AS DATETIME) DT_PRE_2
			,CAST(a.DT_POS AS DATETIME) DT_POS_2
			,CAST(A.CD_CLIENTE AS NUMERIC(7,0)) CD_CLIENTE_2
			,CAST(A.CD_PAPEL AS VARCHAR(12)) COD_NEG_2
		 INTO #ANALISE
		 FROM #PRE_CLI A 
	left JOIN #COMP_CLI B 
		   ON A.CD_CLIENTE = B.CD_CLIENTE
		   AND A.CD_PAPEL = B.CD_PAPEL
		   and a.DT_FATO = b.DT_FATO
	inner JOIN #POS_CLI C 
		   ON A.CD_CLIENTE = C.CD_CLIENTE
		   AND A.CD_PAPEL = C.CD_PAPEL
		   and a.DT_FATO = c.DT_FATO	

		   CREATE INDEX IDX1 ON  #ANALISE (CD_CLIENTE_2 , COD_NEG_2 ,DT_COMP_2,DT_PRE_2,DT_POS_2 )
	---POSIÇÃO COMPARATIVO
	
	DECLARE @DT_POSICAO_MIN DATETIME, @DT_POSICAO_MAX DATETIME
	SET @DT_POSICAO_MIN = (SELECT MIN(DT_COMP) FROM #ANALISE)
	SET @DT_POSICAO_MAX = (SELECT MAX(DT_POS) FROM #ANALISE)


				 DROP TABLE IF EXISTS #CUSTODIA;
				 SELECT A.CD_CLIENTE,DT_CUSTODIA
			 , A.COD_NEG 
			 , SUM(A.QTDE_DISP) QTDE_DISP
			 into #custodia
			   FROM ST_CUSTODIA A
				WHERE DT_CUSTODIA >= @DT_POSICAO_MIN
				AND DT_CUSTODIA <= @DT_POSICAO_MAX
				--AND DESC_CARTEIRA IN( 'CARTEIRA GERAL','CARTEIRA DE GARANTIA')
				AND DESC_CARTEIRA LIKE '%CARTEIRA%'
				AND EXISTS (SELECT 1 FROM #ANALISE B WHERE A.CD_CLIENTE = B.CD_CLIENTE_2 and a.cod_neg = b.cod_neg_2) 
				GROUP BY A.CD_CLIENTE
				,DT_CUSTODIA
				, A.COD_NEG 

			DROP TABLE IF EXISTS #CUSTODIA_MAX;
				SELECT A.CD_CLIENTE
							  , A.COD_NEG
							  , MAX(A.DT_CUSTODIA) AS DT_CUSTODIA 
							  INTO #CUSTODIA_MAX
						   FROM #CUSTODIA A
					 INNER JOIN #ANALISE B 
							 ON A.CD_CLIENTE = B.CD_CLIENTE 
							AND A.COD_NEG = B.CD_PAPEL  
							AND A.DT_CUSTODIA >= B.DT_COMP 
							AND A.DT_CUSTODIA < DT_PRE
					   GROUP BY A.CD_CLIENTE
							  , A.COD_NEG
			
	DROP TABLE IF EXISTS #CUSTODIA_COMP;
	    SELECT A.CD_CLIENTE
			 , A.COD_NEG 
			 , A.QTDE_DISP QTDE_COMP
		  INTO #CUSTODIA_COMP
		  FROM #CUSTODIA A 
	INNER JOIN #custodia_max X 
		ON A.CD_CLIENTE  = X.CD_CLIENTE
	   AND A.COD_NEG     = X.COD_NEG 
	   AND A.DT_CUSTODIA = X.DT_CUSTODIA

---posição pré
	DROP TABLE IF EXISTS #CUSTODIA_MAX_PRE;
			 SELECT A.CD_CLIENTE
				  , A.COD_NEG
				  , MAX(A.DT_CUSTODIA) AS DT_CUSTODIA 
				  into #custodia_max_pre
			   FROM #CUSTODIA A
		 INNER JOIN #ANALISE B 
				 ON A.CD_CLIENTE = B.CD_CLIENTE 
				AND A.COD_NEG = B.CD_PAPEL  
				AND A.DT_CUSTODIA >= B.DT_PRE 
				AND A.DT_CUSTODIA < B.DT_FATO
		   GROUP BY A.CD_CLIENTE
				  , A.COD_NEG

	DROP TABLE IF EXISTS #CUSTODIA_PRE;
	    SELECT A.CD_CLIENTE
			 , A.COD_NEG 
			 , A.QTDE_DISP QTDE_PRE
		  INTO #CUSTODIA_PRE
		  FROM #CUSTODIA A 
	INNER JOIN #custodia_max_pre X 
		ON A.CD_CLIENTE  = X.CD_CLIENTE
	   AND A.COD_NEG     = X.COD_NEG 
	   AND A.DT_CUSTODIA = X.DT_CUSTODIA

	DROP TABLE IF EXISTS #DIST_EUCLI;
		SELECT  A.CD_CLIENTE 
			  , CD_PAPEL     
			  , DT_COMP    
			  , DT_PRE     
			  , DT_FATO    
			  , DT_POS     
			  , QT_NEGOCIADA_COMPRA_PRE 
			  , QT_NEGOCIO_COMPRA_PRE 
			  , VOLUME_COMPRA_PRE     
			  , AVG_QT_NEGOCIADA_COMPRA_PRE P_C_PRE--- MEDIA QTDE POSICIONADA COMPRA PRE
			  , AVG_VL_NEGOCIO_COMPRA_PRE
			  , QT_NEGOCIADA_VENDA_PRE 
			  , QT_NEGOCIO_VENDA_PRE 
			  , VOLUME_VENDA_PRE
			  , AVG_QT_NEGOCIADA_VENDA_PRE  P_V_PRE--- MEDIA QTDE POSICIONADA VENDA PRE
			  , AVG_VL_NEGOCIO_VENDA_PRE
			 , QT_NEGOCIADA_COMPRA_COMP 
			  , QT_NEGOCIO_COMPRA_COMP 
			  , VOLUME_COMPRA_COMP     
			  , AVG_QT_NEGOCIADA_COMPRA_COMP AS P_C_COMP--- MEDIA QTDE POSICIONADA COMPRA COMPARATIVO
			  , AVG_VL_NEGOCIO_COMPRA_COMP
			  , QT_NEGOCIADA_VENDA_COMP 
			  , QT_NEGOCIO_VENDA_COMP 
			  , VOLUME_VENDA_COMP      
			  , AVG_QT_NEGOCIADA_VENDA_COMP  AS P_V_COMP--- MEDIA QTDE POSICIONADA VENDA COMPARATIVO
			  , AVG_VL_NEGOCIO_VENDA_COMP
			  , QTDE_COMP AS C_COMP --CUSTODIA FINAL COMPARATIVO            
			  , QTDE_PRE AS C_PRE--CUSTODIA FINAL PRE
			  , A.QT_NEGOCIADA_COMPRA_POS
			  , A.QT_NEGOCIO_COMPRA_POS
			  , A.VOLUME_COMPRA_POS
			  , A.AVG_QT_NEGOCIADA_COMPRA_POS
			  , A.AVG_VL_NEGOCIO_COMPRA_POS
			  , A.QT_NEGOCIADA_VENDA_POS		
			  , A.QT_NEGOCIO_VENDA_POS			
			  , A.VOLUME_VENDA_POS
			  , A.AVG_QT_NEGOCIADA_VENDA_POS
			  , A.AVG_VL_NEGOCIO_VENDA_POS
			  , AVGP_VL_NEGOCIO_COMPRA_COMP
			  , AVGP_VL_NEGOCIO_COMPRA_POS
			  , AVGP_VL_NEGOCIO_COMPRA_PRE
			  , AVGP_VL_NEGOCIO_VENDA_COMP
			  , AVGP_VL_NEGOCIO_VENDA_POS
			  , AVGP_VL_NEGOCIO_VENDA_PRE		  
		 INTO #DIST_EUCLI
		 FROM #ANALISE A
	INNER JOIN #CUSTODIA_PRE B 
		   ON A.CD_CLIENTE = B.CD_CLIENTE 
		  AND A.CD_PAPEL = B.COD_NEG
	INNER JOIN #CUSTODIA_COMP C 
		   ON A.CD_CLIENTE = C.CD_CLIENTE 
		  AND A.CD_PAPEL = C.COD_NEG

DROP TABLE IF EXISTS #DIST_EUCLI_AUX;
	   SELECT a.CD_CLIENTE
			, a.CD_PAPEL
			, a.DT_FATO
			, SQRT(POWER(CAST(C_COMP AS FLOAT) - CAST(C_PRE AS FLOAT), 2) + POWER(CAST(P_C_COMP AS FLOAT) - CAST(P_C_PRE AS FLOAT), 2)) AS DIST_EUCLI_COMPRA
            , SQRT(POWER(CAST(C_COMP AS FLOAT) - CAST(C_PRE AS FLOAT), 2) + POWER(CAST(P_V_COMP AS FLOAT) - CAST(P_V_PRE AS FLOAT), 2)) AS DIST_EUCLI_VENDA
			, AVGP_VL_NEGOCIO_COMPRA_COMP
			, AVGP_VL_NEGOCIO_VENDA_COMP
			, AVGP_VL_NEGOCIO_COMPRA_PRE
			, AVGP_VL_NEGOCIO_VENDA_PRE
			, AVGP_VL_NEGOCIO_COMPRA_POS
			, AVGP_VL_NEGOCIO_VENDA_POS
			,(CASE WHEN QT_NEGOCIADA_COMPRA_PRE > QT_NEGOCIADA_VENDA_POS THEN  QT_NEGOCIADA_VENDA_POS ELSE  QT_NEGOCIADA_COMPRA_PRE END) * (AVGP_VL_NEGOCIO_VENDA_POS - AVGP_VL_NEGOCIO_COMPRA_PRE) RF_VALORIZOU
			,(CASE WHEN QT_NEGOCIADA_COMPRA_POS > QT_NEGOCIADA_VENDA_PRE THEN  QT_NEGOCIADA_VENDA_PRE ELSE  QT_NEGOCIADA_COMPRA_POS END) * (AVGP_VL_NEGOCIO_VENDA_PRE - AVGP_VL_NEGOCIO_COMPRA_POS) RF_DESVALORIZOU
			, b.AVG_INTERDAY_COMP
			, b.AVG_INTERDAY_POS
			, b.AVG_INTERDAY_PRE
			, b.AVG_INTRADAY_COMP
			, b.AVG_INTRADAY_POS
			, b.AVG_INTRADAY_PRE
		   ,(CASE WHEN QT_NEGOCIADA_COMPRA_PRE > QT_NEGOCIADA_VENDA_POS THEN  QT_NEGOCIADA_VENDA_POS ELSE  QT_NEGOCIADA_COMPRA_PRE END) QTDE_VALORIZOU
		   ,(CASE WHEN QT_NEGOCIADA_COMPRA_POS > QT_NEGOCIADA_VENDA_PRE THEN  QT_NEGOCIADA_VENDA_PRE ELSE  QT_NEGOCIADA_COMPRA_POS END) QTDE_DESVALORIZOU

		 INTO #DIST_EUCLI_AUX
		 FROM #DIST_EUCLI a
	LEFT  JOIN #FATO_CLI B 
		   ON A.CD_PAPEL = B.CD_PAPEL
		  AND A.DT_FATO  = B.DT_FATO
		  AND A.DT_COMP  = B.DT_COMP
		  AND A.DT_POS   = B.DT_POS
		  AND A.DT_PRE   = B.DT_PRE

 DROP TABLE IF EXISTS #AVG_DIST_EUCLI;

	   SELECT CD_PAPEL        
			, AVG(DIST_EUCLI_COMPRA)  AS AVG_DIST_EUCLI_COMPRA
			, AVG(DIST_EUCLI_VENDA)   AS AVG_DIST_EUCLI_VENDA
			, AVG(RF_VALORIZOU)		  AS AVG_RF_VALORIZOU          
			, AVG(RF_DESVALORIZOU)    AS AVG_RF_DESVALORIZOU 
		 INTO #AVG_DIST_EUCLI
		 FROM #DIST_EUCLI_AUX 
	 GROUP BY CD_PAPEL;

	DROP TABLE IF EXISTS #INSIDER_TRADING_RESULTADO;

	 WITH INSIDER_TRADING AS (
	
	SELECT DISTINCT   DATEADD(DAY,-@AUX, @PREGAO) DATA
		 , A.CD_CLIENTE
		 , A.CD_PAPEL
		 , A.DT_FATO
		 , C.EMPRESA
		 , C.FATO_RELEVANTEATIVO
		 , RF_VALORIZOU 
		 , RF_DESVALORIZOU
		 , cast( RF_VALORIZOU + RF_DESVALORIZOU as numeric(17,2)) RESULTADO
		 , QTDE_VALORIZOU 
		 , QTDE_DESVALORIZOU 
		 , A.AVG_INTERDAY_POS
		 , A.AVG_INTRADAY_POS	
		 , AVGP_VL_NEGOCIO_COMPRA_PRE
		 , AVGP_VL_NEGOCIO_VENDA_PRE
		 , AVGP_VL_NEGOCIO_COMPRA_POS
		 , AVGP_VL_NEGOCIO_VENDA_POS		 
		 , CASE WHEN ((DIST_EUCLI_COMPRA > AVG_DIST_EUCLI_COMPRA) 
			 OR (DIST_EUCLI_VENDA  > AVG_DIST_EUCLI_VENDA)
			 OR (RF_VALORIZOU      > AVG_RF_VALORIZOU) 
			 OR (RF_DESVALORIZOU   > AVG_RF_DESVALORIZOU))
			AND (RF_VALORIZOU + RF_DESVALORIZOU > 0 ) THEN 1 ELSE 0 END  FLAG_ALRT
	  
	  FROM #DIST_EUCLI_AUX A
 LEFT JOIN #AVG_DIST_EUCLI B 
		ON A.CD_PAPEL = B.CD_PAPEL
 LEFT JOIN #FATO_CLI C 
		ON A.CD_PAPEL = C.CD_PAPEL 
	   AND A.DT_FATO = C.DT_FATO

	   )


 SELECT   DATA
			, CD_CLIENTE
			, CD_PAPEL
			, DT_FATO
			, STUFF((SELECT ' | ' + X.EMPRESA + ': ' + X.FATO_RELEVANTEATIVO
					 FROM INSIDER_TRADING X
					 WHERE X.DATA = A.DATA
					   AND X.CD_CLIENTE = A.CD_CLIENTE
					   AND X.CD_PAPEL = A.CD_PAPEL
					   AND X.DT_FATO = A.DT_FATO
					 FOR XML PATH(''), TYPE
					 ).value('.', 'NVARCHAR(MAX)'), 1, 2, '')  AS FATO_RELEVANTE
			, CAST(AVGP_VL_NEGOCIO_COMPRA_PRE AS NUMERIC(17,2)) AS PRECO_MEDIO_COMPRA_PRE
			, CAST(AVGP_VL_NEGOCIO_VENDA_PRE AS NUMERIC(17,2))  AS PRECO_MEDIO_VENDA_PRE
			, CAST(AVGP_VL_NEGOCIO_COMPRA_POS AS NUMERIC(17,2)) AS PRECO_MEDIO_COMPRA_POS 
			, CAST(AVGP_VL_NEGOCIO_VENDA_POS AS NUMERIC(17,2))  AS PRECO_MEDIO_VENDA_POS
			, QTDE_VALORIZOU 
			, QTDE_DESVALORIZOU
			, RF_VALORIZOU 
			, RF_DESVALORIZOU
			, RESULTADO
			, AVG_INTERDAY_POS
			, AVG_INTRADAY_POS 
			, MAX(FLAG_ALRT)	AS FLAG_ALRT
		INTO #INSIDER_TRADING_RESULTADO
		FROM INSIDER_TRADING A
	   --WHERE FLAG_ALRT = 1
	GROUP BY DATA
			 , CD_CLIENTE
			 , CD_PAPEL
			 , DT_FATO
			 , QTDE_VALORIZOU 
			 , QTDE_DESVALORIZOU 
			 , RF_VALORIZOU 
			 , RF_DESVALORIZOU
			 , RESULTADO
			 , AVG_INTERDAY_POS
			 , AVG_INTRADAY_POS
			 , AVGP_VL_NEGOCIO_COMPRA_PRE
			 , AVGP_VL_NEGOCIO_COMPRA_POS
			 , AVGP_VL_NEGOCIO_VENDA_PRE
			 , AVGP_VL_NEGOCIO_VENDA_POS ;
			 --, FLAG_ALRT


			---INSERT TABELA DE RELATÓRIO
			DELETE FROM ST_INSIDER_TRADING WHERE DATA = DATEADD(DAY,-@AUX, @PREGAO);

			INSERT INTO ST_INSIDER_TRADING (DATA,CD_CLIENTE,CD_PAPEL,DT_FATO,FATO_RELEVANTE,PRECO_MEDIO_COMPRA_PRE,PRECO_MEDIO_VENDA_PRE,PRECO_MEDIO_COMPRA_POS,PRECO_MEDIO_VENDA_POS,QTDE_VALORIZOU,QTDE_DESVALORIZOU
			,RF_VALORIZOU,RF_DESVALORIZOU,RESULTADO,AVG_INTERDAY_POS,AVG_INTRADAY_POS,ALERTA)
			SELECT DATA
					,CD_CLIENTE
					,CD_PAPEL
					,DT_FATO
					,FATO_RELEVANTE
					,PRECO_MEDIO_COMPRA_PRE
					,PRECO_MEDIO_VENDA_PRE
					,PRECO_MEDIO_COMPRA_POS
					,PRECO_MEDIO_VENDA_POS
					,QTDE_VALORIZOU
					,QTDE_DESVALORIZOU
					,RF_VALORIZOU 
					,RF_DESVALORIZOU
					,RESULTADO
					,AVG_INTERDAY_POS
					,AVG_INTRADAY_POS
					, CASE WHEN FLAG_ALRT = 1 THEN 'S' ELSE 'N' END ALERTA					
				FROM #INSIDER_TRADING_RESULTADO

		  ---INSERT TABELA DE ALERTA
		  DELETE FROM ST_ALERT_INSIDER_TRADING_02 WHERE DATA = DATEADD(DAY,-@AUX, @PREGAO);

	      INSERT INTO ST_ALERT_INSIDER_TRADING_02 
		  (DATA,CD_CLIENTE,CD_PAPEL,DT_FATO,FATO_RELEVANTE,PRECO_MEDIO_COMPRA_PRE,PRECO_MEDIO_VENDA_PRE,PRECO_MEDIO_COMPRA_POS,PRECO_MEDIO_VENDA_POS,QTDE_VALORIZOU,QTDE_DESVALORIZOU,
		   RF_VALORIZOU,RF_DESVALORIZOU,RESULTADO,AVG_INTERDAY_POS,AVG_INTRADAY_POS)
			SELECT DATA
					,CD_CLIENTE
					,CD_PAPEL
					,DT_FATO
					,FATO_RELEVANTE
					,PRECO_MEDIO_COMPRA_PRE
					,PRECO_MEDIO_VENDA_PRE
					,PRECO_MEDIO_COMPRA_POS
					,PRECO_MEDIO_VENDA_POS
					,QTDE_VALORIZOU
					,QTDE_DESVALORIZOU
					,RF_VALORIZOU 
					,RF_DESVALORIZOU
					,RESULTADO
					,AVG_INTERDAY_POS
					,AVG_INTRADAY_POS 
				FROM #INSIDER_TRADING_RESULTADO
				WHERE FLAG_ALRT = 1
 
   

/******* fim do processo de carga do alerta **********/
-- ================================================
-- Marca DT_FIRA para registros carregados (fallback)
-- ================================================
DECLARE @__dt_fira_now DATETIME = GETDATE();
DECLARE @__data_ref DATE = CONVERT(date, DATEADD(DAY, -@AUX, @PREGAO));

IF COL_LENGTH(N'dbo.ST_ALERT_INSIDER_TRADING_02', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE dbo.ST_ALERT_INSIDER_TRADING_02
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL
      AND [DATA] = @__data_ref;

    UPDATE dbo.ST_INSIDER_TRADING
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL
      AND [DATA] = @__data_ref;
END

--passo 3
/***** limpa a tabela do banco para nao ficar sujeira ******/
DROP TABLE IF EXISTS ST_ALERT_INSIDER_TRADING_02_PADRAO 	
DROP TABLE IF EXISTS ST_INSIDER_TRADING_PADRAO