CREATE PROCEDURE [dbo].[ATUALIZARSCORELISTAATENCAO]
(
	@USUARIO INT, @ANM1 INT, @B31 INT, @BCB1 INT, @BCB2 INT, @BIS1 INT, @CGU1 INT, @CGU2 INT, @CGU3 INT, @CGU4 INT, @CGU5 INT, @CGU6 INT, @CGU7 INT, @CGU8 INT,
							@CGU9 INT, @DFAT1 INT, @DFIFSA1 INT, @EBC1 INT, @EBC2 INT, @EEAS1 INT, @FINCEN1 INT, @GAFI1 INT, @IBAMA1 INT, @ICIJ1 INT, @INTERPOL1 INT,
							@IPEA1 INT, @ITA1 INT, @MYSOCIETY1 INT, @OFAC1 INT, @OFSIHMT1 INT, @OSFI1 INT, @OSFI2 INT, @PACE1 INT, @PGFN1 INT,
							@RF1 INT, @SECO1 INT, @SISCOAF1 INT, @TCU1 INT, @TCU2 INT, @TCU3 INT, @TI1 INT, @TSE1 INT, @TSE2 INT, @TSE3 INT, @UNSC1 INT
)
--WITH ENCRYPTION
AS
BEGIN
	
	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'ANM1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('ANM1', 'LISTAATENCAO', @ANM1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @ANM1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'ANM1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'B31')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('B31', 'LISTAATENCAO', @B31, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @B31 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'B31'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'BCB1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('BCB1', 'LISTAATENCAO', @BCB1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @BCB1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'BCB1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'BCB2')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('BCB2', 'LISTAATENCAO', @BCB2, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @BCB2 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'BCB2'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'BIS1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('BIS1', 'LISTAATENCAO', @BIS1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @BIS1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'BIS1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'CGU1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('CGU1', 'LISTAATENCAO', @CGU1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @CGU1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'CGU1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'CGU2')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('CGU2', 'LISTAATENCAO', @CGU2, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @CGU2 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'CGU2'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'CGU3')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('CGU3', 'LISTAATENCAO', @CGU3, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @CGU3 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'CGU3'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'CGU4')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('CGU4', 'LISTAATENCAO', @CGU4, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @CGU4 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'CGU4'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'CGU5')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('CGU5', 'LISTAATENCAO', @CGU5, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @CGU5 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'CGU5'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'CGU6')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('CGU6', 'LISTAATENCAO', @CGU6, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @CGU6 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'CGU6'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'CGU7')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('CGU7', 'LISTAATENCAO', @CGU7, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @CGU7 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'CGU7'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'CGU8')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('CGU8', 'LISTAATENCAO', @CGU8, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @CGU8 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'CGU8'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'CGU9')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('CGU9', 'LISTAATENCAO', @CGU9, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @CGU9 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'CGU9'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'DFAT1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('DFAT1', 'LISTAATENCAO', @DFAT1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @DFAT1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'DFAT1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'DFIFSA1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('DFIFSA1', 'LISTAATENCAO', @DFIFSA1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @DFIFSA1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'DFIFSA1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'EBC1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('EBC1', 'LISTAATENCAO', @EBC1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @EBC1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'EBC1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'EBC2')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('EBC2', 'LISTAATENCAO', @EBC2, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @EBC2 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'EBC2'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'EEAS1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('EEAS1', 'LISTAATENCAO', @EEAS1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @EEAS1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'EEAS1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'FINCEN1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('FINCEN1', 'LISTAATENCAO', @FINCEN1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @FINCEN1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'FINCEN1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'GAFI1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('GAFI1', 'LISTAATENCAO', @GAFI1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @GAFI1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'GAFI1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'IBAMA1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('IBAMA1', 'LISTAATENCAO', @IBAMA1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @IBAMA1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'IBAMA1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'ICIJ1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('ICIJ1', 'LISTAATENCAO', @ICIJ1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @ICIJ1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'ICIJ1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'INTERPOL1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('INTERPOL1', 'LISTAATENCAO', @INTERPOL1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @INTERPOL1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'INTERPOL1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'IPEA1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('IPEA1', 'LISTAATENCAO', @IPEA1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @IPEA1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'IPEA1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'ITA1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('ITA1', 'LISTAATENCAO', @ITA1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @ITA1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'ITA1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'MYSOCIETY1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('MYSOCIETY1', 'LISTAATENCAO', @MYSOCIETY1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @MYSOCIETY1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'MYSOCIETY1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'OFAC1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('OFAC1', 'LISTAATENCAO', @OFAC1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @OFAC1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'OFAC1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'OFSIHMT1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('OFSIHMT1', 'LISTAATENCAO', @OFSIHMT1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @OFSIHMT1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'OFSIHMT1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'OSFI1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('OSFI1', 'LISTAATENCAO', @OSFI1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @OSFI1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'OSFI1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'OSFI2')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('OSFI2', 'LISTAATENCAO', @OSFI2, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @OSFI2 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'OSFI2'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'PACE1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('PACE1', 'LISTAATENCAO', @PACE1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @PACE1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'PACE1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'PGFN1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('PGFN1', 'LISTAATENCAO', @PGFN1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @PGFN1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'PGFN1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'RF1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('RF1', 'LISTAATENCAO', @RF1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @RF1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'RF1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'SECO1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('SECO1', 'LISTAATENCAO', @SECO1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @SECO1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'SECO1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'SISCOAF1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('SISCOAF1', 'LISTAATENCAO', @SISCOAF1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @SISCOAF1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'SISCOAF1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'TCU1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('TCU1', 'LISTAATENCAO', @TCU1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @TCU1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'TCU1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'TCU2')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('TCU2', 'LISTAATENCAO', @TCU2, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @TCU2 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'TCU2'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'TCU3')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('TCU3', 'LISTAATENCAO', @TCU3, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @TCU3 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'TCU3'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'TI1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('TI1', 'LISTAATENCAO', @TI1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @TI1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'TI1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'TSE1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('TSE1', 'LISTAATENCAO', @TSE1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @TSE1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'TSE1'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'TSE2')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('TSE2', 'LISTAATENCAO', @TSE2, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @TSE2 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'TSE2'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'TSE3')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('TSE3', 'LISTAATENCAO', @TSE3, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @TSE3 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'TSE3'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'UNSC1')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('UNSC1', 'LISTAATENCAO', @UNSC1, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @UNSC1 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'UNSC1'
	END

	
END