CREATE PROCEDURE [dbo].[FIRA_PR_CARGA_ST_PATRIMONIO_CUSTODIA] @PREGAO DATETIME, @PREGAOFIM DATETIME
WITH RECOMPILE
AS

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ST_PATRIMONIO_CUSTODIA_PADRAO]') AND type in (N'U'))
CREATE TABLE [dbo].[ST_PATRIMONIO_CUSTODIA_PADRAO](
	[DT_CUSTODIA] [datetime] NULL,
	[CD_CLIENTE] [int] NOT NULL,
	[NM_CLIENTE] [nvarchar](160) NULL,
	[CD_CPFCGC] [varchar](20) NULL,
	[DS_ATIV] [varchar](160) NOT NULL,
	[DT_ATUALIZ] [varchar](30) NULL,
	[PATRIMONIO] [float] NULL,
	[POSICAO_CC] [float] NULL,
	[POSICAO_BOVESPA] [float] NULL,
	[POSICAO_BMF] [float] NULL,
	[TESOURO] [float] NULL,
	[RENDA_FIXA] [float] NULL,
	[FUNDOS] [float] NULL,
	[CARTEIRA] [float] NULL,
	[INCOMPATIVEL] [varchar](3) NOT NULL,
	[DT_FIRA] DATETIME NULL
) ON [PRIMARY]


/***************************************************
inicio da comparação entre a tabela
da base padrao fira origem x tabela cliente destino
*****************************************************/
EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo',, @src_table='ST_PATRIMONIO_CUSTODIA_PADRAO',
  @schema_name='dbo', @base_table='ST_PATRIMONIO_CUSTODIA',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1;


/*******************************	
  CARGA ST_PATRIMONIO_CUSTODIA
  reprocessamento.
********************************/  
--DECLARE @PREGAO DATETIME, @PREGAOFIM DATETIME
--SET @PREGAO ='20250601'
--SET @PREGAOFIM ='20260101'

   
WHILE @PREGAO < @PREGAOFIM
BEGIN
 
	----DELETA
	DELETE FROM ST_PATRIMONIO_CUSTODIA	WHERE DT_CUSTODIA = @PREGAO	
	
		drop table if exists #PAT 
		SELECT DATA,XX.CD_CLIENTE,xx.CD_CPFCGC, isnull(CAST(SUM(VAL_BENS) AS NUMERIC(38,2)),0) VAL_BENS
		into  #PAT 
		FROM ST_PATRIMONIO_LIQ  XX (nolock)
		WHERE DATA = @PREGAO					
		GROUP BY DATA,xx.CD_CPFCGC,XX.CD_CLIENTE
	 

		---- 
		--TEMP #CUSTR
	    -------------------------------------------------------------------------
    -- BASE CONSOLIDADA DE POSIÇÕES (sem quebrar quando ST_RENDA_FIXA / ST_FUNDOS não existirem)
    -------------------------------------------------------------------------

    IF OBJECT_ID('tempdb..#CUSTR_RAW') IS NOT NULL DROP TABLE #CUSTR_RAW;
    CREATE TABLE #CUSTR_RAW (
        DT_CUSTODIA  DATETIME,
        CD_CLIENTE   INT,
        POSICAO      FLOAT,
        POSICAO_BMF  FLOAT,
        POSICAO_CC   FLOAT,
        TESOURO      FLOAT,
        RENDA_FIXA   FLOAT,
        FUNDOS       FLOAT
    );

    -- 1) ST_CUSTODIA (sempre)
    INSERT INTO #CUSTR_RAW (DT_CUSTODIA, CD_CLIENTE, POSICAO, POSICAO_BMF, POSICAO_CC, TESOURO, RENDA_FIXA, FUNDOS)
    SELECT
        DT_CUSTODIA,
        CD_CLIENTE,
        SUM(isnull(VL_POSI,0)) AS POSICAO,
        0, 0, 0, 0, 0
    FROM ST_CUSTODIA WITH (NOLOCK)
    --WHERE DT_CUSTODIA = @PREGAO
    GROUP BY DT_CUSTODIA, CD_CLIENTE;
 
    -- 2) ST_CUSTODIA_BMF (sempre)
    INSERT INTO #CUSTR_RAW (DT_CUSTODIA, CD_CLIENTE, POSICAO, POSICAO_BMF, POSICAO_CC, TESOURO, RENDA_FIXA, FUNDOS)
    SELECT
        DT_DATMOV,
        CD_CLIENTE,
        0,
        SUM(TRY_CONVERT(DECIMAL(18,6), REPLACE(VL_DIA_ATU, ',', '.'))) AS POSICAO_BMF,
        0, 0, 0, 0
    FROM ST_CUSTODIA_BMF WITH (NOLOCK)
    WHERE DT_DATMOV = @PREGAO
    GROUP BY DT_DATMOV, CD_CLIENTE;

    -- 3) ST_SALDO (sempre)
    INSERT INTO #CUSTR_RAW (DT_CUSTODIA, CD_CLIENTE, POSICAO, POSICAO_BMF, POSICAO_CC, TESOURO, RENDA_FIXA, FUNDOS)
    SELECT
        DATA,
        CD_CLIENTE,
        0, 0,
        SUM(TRY_CONVERT(DECIMAL(18,6), REPLACE(VL_DISPONIVEL, ',', '.'))) AS POSICAO_CC,
        0, 0, 0
    FROM ST_SALDO WITH (NOLOCK)
    WHERE DATA = @PREGAO
    GROUP BY DATA, CD_CLIENTE;

    -- 4) ST_TESOURO (sempre)
    INSERT INTO #CUSTR_RAW (DT_CUSTODIA, CD_CLIENTE, POSICAO, POSICAO_BMF, POSICAO_CC, TESOURO, RENDA_FIXA, FUNDOS)
    SELECT
        DATA_MVTO,
        COD_CLI,
        0, 0, 0,
        SUM(TRY_CONVERT(DECIMAL(18,6), REPLACE(VAL_TOT, ',', '.'))) AS TESOURO,
        0, 0
    FROM ST_TESOURO WITH (NOLOCK)
    WHERE DATA_MVTO = @PREGAO
    GROUP BY DATA_MVTO, COD_CLI;

    -- 5) ST_RENDA_FIXA (opcional)
    IF OBJECT_ID('dbo.ST_RENDA_FIXA','U') IS NOT NULL
    BEGIN
        INSERT INTO #CUSTR_RAW (DT_CUSTODIA, CD_CLIENTE, POSICAO, POSICAO_BMF, POSICAO_CC, TESOURO, RENDA_FIXA, FUNDOS)
        SELECT
            DATA_MVTO,
            COD_CLI,
            0, 0, 0,
            0,
            SUM(TRY_CONVERT(DECIMAL(18,6), REPLACE(VAL_TOT, ',', '.'))) AS RENDA_FIXA,
            0
        FROM ST_RENDA_FIXA WITH (NOLOCK)
        WHERE DATA_MVTO = @PREGAO
        GROUP BY DATA_MVTO, COD_CLI;
    END;

    -- 6) ST_FUNDOS (opcional)
    IF OBJECT_ID('dbo.ST_FUNDOS','U') IS NOT NULL
    BEGIN
        INSERT INTO #CUSTR_RAW (DT_CUSTODIA, CD_CLIENTE, POSICAO, POSICAO_BMF, POSICAO_CC, TESOURO, RENDA_FIXA, FUNDOS)
        SELECT
            DATA_MVTO,
            COD_CLI,
            0, 0, 0,
            0, 0,
            SUM(TRY_CONVERT(DECIMAL(18,6), REPLACE(VAL_TOT, ',', '.'))) AS FUNDOS
        FROM ST_FUNDOS WITH (NOLOCK)
        WHERE DATA_MVTO = @PREGAO
        GROUP BY DATA_MVTO, COD_CLI;
    END;
 


    -- Agregação final (substitui o seu CTE #CUSTR)
    IF OBJECT_ID('tempdb..#CUSTR') IS NOT NULL DROP TABLE #CUSTR;
    SELECT
        DT_CUSTODIA,
        CD_CLIENTE,
        CAST(SUM(POSICAO)     AS FLOAT) AS POSICAO_BOVESPA,
        CAST(SUM(POSICAO_BMF) AS FLOAT) AS POSICAO_BMF,
        CAST(SUM(POSICAO_CC)  AS FLOAT) AS POSICAO_CC,
        CAST(SUM(TESOURO)     AS FLOAT) AS TESOURO,
        CAST(SUM(RENDA_FIXA)  AS FLOAT) AS RENDA_FIXA,
        CAST(SUM(FUNDOS)      AS FLOAT) AS FUNDOS,
        CAST(
            SUM(POSICAO)
          + SUM(POSICAO_BMF)
          + SUM(POSICAO_CC)
          + SUM(TESOURO)
          + SUM(RENDA_FIXA)
          + SUM(FUNDOS)
          AS FLOAT
        ) AS POSICAO_CONSOLIDADA
    INTO #CUSTR
    FROM #CUSTR_RAW
    GROUP BY DT_CUSTODIA, CD_CLIENTE;

		 

	----
	--INSERT FINAL
 
	INSERT INTO ST_PATRIMONIO_CUSTODIA 
	(
	DT_CUSTODIA,CD_CLIENTE,NM_CLIENTE,CD_CPFCGC,DS_ATIV,DT_ATUALIZ,PATRIMONIO,
	POSICAO_CC,POSICAO_BOVESPA,POSICAO_BMF,TESOURO,RENDA_FIXA,FUNDOS,CARTEIRA,INCOMPATIVEL
	)
	SELECT DISTINCT	
		C.DT_CUSTODIA,	
		Y.CD_CLIENTE, 	
		Y.NM_CLIENTE,	
		Y.CD_CPFCGC,
		isnull(Y.DS_ATIV,'n/a') DS_ATIV,
		DT_ATUALIZ,
		CAST(ISNULL(SUM(VAL_BENS),0) AS FLOAT) as PATRIMONIO,
		CAST(POSICAO_CC AS FLOAT) POSICAO_CC,
		CAST(POSICAO_BOVESPA AS FLOAT) POSICAO_BOVESPA,	
		CAST(POSICAO_BMF AS FLOAT) POSICAO_BMF,	
		CAST(TESOURO AS FLOAT) AS TESOURO,
		CAST(RENDA_FIXA AS FLOAT) RENDA_FIXA,
		CAST(FUNDOS AS FLOAT) FUNDOS,
		CAST(FUNDOS AS FLOAT) + CAST(TESOURO AS FLOAT) + CAST(POSICAO_BOVESPA AS FLOAT) + CAST(POSICAO_BMF AS FLOAT) + CAST(POSICAO_CC AS FLOAT) CARTEIRA,	
		CASE WHEN CAST(FUNDOS AS FLOAT) + CAST(TESOURO AS FLOAT) + CAST(POSICAO_BOVESPA AS FLOAT) + CAST(POSICAO_BMF AS FLOAT) + CAST(POSICAO_CC AS FLOAT) > ISNULL(SUM(VAL_BENS),0) THEN 'SIM' ELSE 'NÃO' END INCOMPATIVEL		
		--INTO ST_PATRIMONIO_CUSTODIA
	FROM V_CLIENTE_TODOS Y	(nolock)
	LEFT OUTER JOIN #CUSTR C ON Y.CD_CLIENTE = C.CD_CLIENTE	
	LEFT OUTER JOIN #PAT D ON Y.CD_CPFCGC = D.CD_CPFCGC AND C.DT_CUSTODIA = D.DATA AND Y.CD_CLIENTE = D.CD_CLIENTE

	WHERE C.DT_CUSTODIA is not null
	and DT_CUSTODIA = @PREGAO

	GROUP BY  	
		C.DT_CUSTODIA,	
		Y.CD_CLIENTE, 	
		Y.CD_CPFCGC,	
		Y.NM_CLIENTE,	
		Y.DS_ATIV,	
		Y.DT_CRIACAO,Y.DT_ATUALIZ,
		CAST((POSICAO_BOVESPA)AS FLOAT),	
		CAST((POSICAO_BMF)AS FLOAT),	
		CAST((POSICAO_CC)AS FLOAT), 	
		CAST(TESOURO AS FLOAT),
		CAST(RENDA_FIXA AS FLOAT),
		CAST(FUNDOS AS FLOAT)
 

SET @PREGAO = DATEADD(DAY, 1, @PREGAO)

END

-- ================================================
-- Marca DT_FIRA para registros carregados (fallback)
-- ================================================
	DECLARE @__dt_fira_now DATETIME = GETDATE();
IF COL_LENGTH(N'dbo.ST_PATRIMONIO_CUSTODIA', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE [dbo].[ST_PATRIMONIO_CUSTODIA]
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL;
END
/******* fim do processo de carga **********/

--passo 3
/***** limpa a tabela do banco para nao ficar sujeira ******/
DROP TABLE IF EXISTS ST_PATRIMONIO_CUSTODIA_PADRAO