CREATE PROCEDURE [dbo].[PR_SWINGTRADE]  @INICIO SMALLDATETIME,@FIM SMALLDATETIME, @CD_CLIENTE VARCHAR(160),@QTDPORPAGINA INT,@PAGINA INT 
--WITH ENCRYPTION
AS

--DECLARE @PAGINA        INT = 1;
--DECLARE @QTDPORPAGINA INT = 5
--DECLARE @INICIO SMALLDATETIME,@FIM SMALLDATETIME, @CD_CLIENTE VARCHAR(160)
--SET @INICIO ='20230101'
--SET @FIM ='20230331'
--SET @CD_CLIENTE =''

--SELECT V.CD_CLIENTE,
SELECT  format(@INICIO,'d','pt-br') [DATA INÍCIO],
format(@fim,'d','pt-br') [DATA FIM],
STB.CD_CLIENTE [CÓD. CLIENTE],
V.NM_CLIENTE [NOME DO CLIENTE],
SUM(QTD_SWINGTRADE) [QTD. SWINGTRADE],
SUM(CASE WHEN RESULTADO >0 THEN 1 ELSE 0 END ) ACERTO,
SUM(CASE WHEN RESULTADO <0 THEN 1 ELSE 0 END ) PERDA,
SUM(CASE WHEN RESULTADO = 0 THEN 1 ELSE 0 END ) EMPATE,
FORMAT(SUM(RESULTADO),'f','pt-br') [RESULTADO FINANCEIRO]
--,FORMAT(SUM(FINANCEIRO),'f','pt-br') FINANCEIRO
FROM ST_SWINGTRADE_BOVESPA STB 
left JOIN V_CLIENTE_TODOS V
ON STB.CD_CLIENTE = V.CD_CLIENTE

WHERE V.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN V.CD_CLIENTE ELSE @CD_CLIENTE END
AND PREGAO >= @INICIO AND PREGAO <= @FIM

GROUP BY stb.CD_CLIENTE,  V.NM_CLIENTE

ORDER BY 1
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;