CREATE PROCEDURE [dbo].[PR_RESUMO_DIRETAS_BVSP] @INICIO SMALLDATETIME, @FIM SMALLDATETIME, @CLIENTE INT,    
@INICIO2 SMALLDATETIME, @FIM2 SMALLDATETIME,@QTDPORPAGINA INT, @PAGINA INT  
WITH RECOMPILE  
AS    
    
  
--DECLARE @PAGINA        INT = 1  
--DECLARE @QTDPORPAGINA INT = 100  
--DECLARE @INICIO SMALLDATETIME, @FIM SMALLDATETIME, @CLIENTE INT,@INICIO2 SMALLDATETIME, @FIM2 SMALLDATETIME    
--SET @INICIO = '20230801'    
--SET @FIM = '20230815'    
--SET @INICIO2 = '20230101'    
--SET @FIM2 = '20230131'    
--SET @CLIENTE = ''    
    
    
DECLARE @CORRET FLOAT    
  
SET @CORRET = (SELECT SUM(QTD_DIRETAS_PONTA) QTD_DIRETAS     
    FROM ST_RESUMO_DIRETAS_BVSP ST    
    WHERE DT_PERIODO>=@INICIO AND DT_PERIODO<=@FIM)    
    
    
    
;WITH #T1 AS (    
SELECT ST.CD_CLIENTE, SUM(QTD_DIRETAS_PONTA) QTD_DIRETAS    
FROM ST_RESUMO_DIRETAS_BVSP ST    
WHERE DT_PERIODO>=@INICIO AND DT_PERIODO<=@FIM    
AND ST.CD_CLIENTE = CASE WHEN ISNULL(@CLIENTE,'') ='' THEN ST.CD_CLIENTE ELSE CAST(@CLIENTE AS INT) END    
GROUP BY CD_CLIENTE    
),    
    
    
#TNEG AS (   
SELECT a.CD_CLIENTE,COUNT(DISTINCT NR_NEGOCIO) QTD_NEGOCIOS     
FROM ST_CORRETAGEM_ORDEM A, V_CLIENTE_TODOS B, ST_PERIODO C    
WHERE A.CD_CLIENTE =B.CD_CLIENTE    
AND A.DT_NEGOCIO = C.DT_PERIODO    
AND DT_PERIODO>=@INICIO AND DT_PERIODO <=@FIM    
AND B.CD_CLIENTE = CASE WHEN ISNULL(@CLIENTE,'') ='' THEN B.CD_CLIENTE ELSE CAST(@CLIENTE AS INT) END    
GROUP BY a.CD_CLIENTE    
),  
    
    
#TNEGANT AS (  
SELECT CD_CLIENTE,SUM(QT_MULTIPLICADOR) QTD_NEGOCIOS     
FROM ST_CORRETAGEM_ORDEM    
WHERE DT_NEGOCIO>=@INICIO2    
AND DT_NEGOCIO <=@FIM2    
AND CD_CLIENTE = CASE WHEN ISNULL(@CLIENTE,'') ='' THEN CD_CLIENTE ELSE CAST(@CLIENTE AS INT) END    
GROUP BY CD_CLIENTE    
),    
    
#TDIRANT AS (  
SELECT ST.CD_CLIENTE, SUM(QTD_DIRETAS_PONTA) QTD_DIRETAS    
 FROM ST_RESUMO_DIRETAS_BVSP ST    
 WHERE DT_PERIODO>=@INICIO2 AND DT_PERIODO<=@FIM2    
 AND ST.CD_CLIENTE = CASE WHEN ISNULL(@CLIENTE,'') ='' THEN ST.CD_CLIENTE ELSE CAST(@CLIENTE AS INT) END    
GROUP BY ST.CD_CLIENTE    
),  
    
  
#TPONTA AS (  
SELECT CD_CLIENTE, SUM(QTD_DIRETAS_PONTA) QTD, CD_CLIENTE_PONTA     
FROM ST_RESUMO_DIRETAS_BVSP     
WHERE DT_PERIODO>=@INICIO    
AND DT_PERIODO<=@FIM    
 AND CD_CLIENTE = CASE WHEN ISNULL(@CLIENTE,'') ='' THEN CD_CLIENTE ELSE CAST(@CLIENTE AS INT) END    
GROUP BY CD_CLIENTE, CD_CLIENTE_PONTA    
),    
   
  
CTE AS   
(    
   SELECT *,    
         ROW_NUMBER() OVER (PARTITION BY CD_CLIENTE ORDER BY QTD DESC) AS RN    
   FROM #TPONTA    
),  
  
  
#T4 AS (  
SELECT CD_CLIENTE,    
QTD, CD_CLIENTE_PONTA    
FROM CTE     
WHERE RN = 1    
)  
  
    
--QUERY FINAL    
 SELECT  format(@INICIO,'d','pt-br') [DATA INÍCIO],  
format(@fim,'d','pt-br') [DATA FIM],  
#T1.CD_CLIENTE AS "CÓD. CLIENTE",  
SA.NM_CLIENTE AS "NOME DO CLIENTE",  
#T4.CD_CLIENTE_PONTA AS "CÓD. CLIENTE PONTA",     
SA2.NM_CLIENTE AS "NOME DO CLIENTE PONTA",  
  
FORMAT(SUM(ISNULL(#TNEG.QTD_NEGOCIOS,0)),'#,0','PT-BR') AS "QTD. NEGOCIOS",   
FORMAT(SUM(ISNULL(#T1.QTD_DIRETAS,0)),'#,0','PT-BR') AS "QTD. DIRETAS ",    
FORMAT(CAST(SUM(#T1.QTD_DIRETAS)AS FLOAT)/CAST(SUM(#TNEG.QTD_NEGOCIOS) AS FLOAT),'P2') AS "PROPORÇÃO QTD. NÉGOCIOS",   
     
  
ISNULL(FORMAT(CAST(SUM(#T1.QTD_DIRETAS)AS FLOAT)/CAST(SUM(#TDIRANT.QTD_DIRETAS) AS FLOAT)-1,'P2'),0) AS "QTD DIRETAS / ANTERIOR",    
FORMAT(CAST(SUM(ISNULL(#T4.QTD,0)) AS FLOAT)/CAST(SUM(#T1.QTD_DIRETAS) AS FLOAT),'P2') "QTD. PONTA / QTD. DIRETAS",    
FORMAT(CAST(SUM(ISNULL(#T1.QTD_DIRETAS,0)) AS FLOAT) / @CORRET,'P2') AS "QTD. DIRETAS / CORRETORA",    
CASE WHEN SA.CD_CPFCGC = SA2.CD_CPFCGC THEN 'SIM' ELSE 'NÃO' END AS "MESMO CPF/CNPJ",    
'NÃO' AS "BROKER"  
  
FROM #T1   
INNER JOIN #TNEG    
ON #T1.CD_CLIENTE = #TNEG.CD_CLIENTE    
INNER JOIN #T4    
ON #T1.CD_CLIENTE = #T4.CD_CLIENTE    
LEFT OUTER JOIN V_CLIENTE_TODOS SA    
ON #T1.CD_CLIENTE = SA.CD_CLIENTE    
LEFT OUTER JOIN V_CLIENTE_TODOS SA2    
ON #T4.CD_CLIENTE_PONTA = SA2.CD_CLIENTE    
LEFT OUTER JOIN #TNEGANT    
ON #T1.CD_CLIENTE = #TNEGANT.CD_CLIENTE    
LEFT OUTER JOIN #TDIRANT    
ON #T1.CD_CLIENTE = #TDIRANT.CD_CLIENTE    
    
GROUP BY #T1.CD_CLIENTE, SA.NM_CLIENTE, SA2.NM_CLIENTE,    
#T4.CD_CLIENTE_PONTA, SA.CD_CPFCGC, SA2.CD_CPFCGC   
    
  
ORDER BY 1  
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS  
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;