CREATE PROCEDURE [dbo].[PR_CONTROLE_MANIPULACAO_BMF] @INICIO SMALLDATETIME , @FIM SMALLDATETIME ,  
@CLIENTE INT , @CD_COMMOD VARCHAR(10),@CD_SERIE VARCHAR(15),@QTDPORPAGINA INT,@PAGINA INT
WITH RECOMPILE 
AS 



-- Parâmetros (no proc, deixe defaults coerentes)
-- IMPORTANTE: @CLIENTE é INT -> não use '' (string). Use NULL.
--DECLARE
--    @INICIO        smalldatetime = '20251201',
--    @FIM           smalldatetime = '20251231',
--    @CLIENTE       int           = NULL,
--    @CD_COMMOD     varchar(10)   = NULL,
--    @CD_SERIE      varchar(15)   = NULL,
--    @PAGINA        int           = 1,
--    @QTDPORPAGINA  int           = 50;

-- =========================
-- T1 (CLIENTE) materializada
-- =========================
DROP TABLE IF EXISTS #T1;
SELECT
    A.DT_NEGOCIO,
    A.CD_CLIENTE,
    A.CD_COMMOD,
    A.CD_SERIE,
    SUM(A.PR_NEGOCIO) * SUM(A.QT_QTDDET) AS VOLUME_CLIENTE,        -- mantida sua lógica
    AVG(A.PR_NEGOCIO) AS PRECO_MED_CLIENTE
INTO #T1
FROM ST_BMF_NEGOCIOS_NC A WITH (NOLOCK)
WHERE
    A.DT_NEGOCIO >= @INICIO
    AND A.DT_NEGOCIO <= @FIM
    AND A.TP_NEGOCIO IN ('NORMAL','DAY TRADE','DAYTRADE')
    AND CD_CLIENTE = CASE WHEN ISNULL(@CLIENTE,'') ='' THEN CD_CLIENTE ELSE @CLIENTE END
    AND CD_COMMOD = CASE WHEN ISNULL(@CD_COMMOD,'') ='' THEN CD_COMMOD ELSE @CD_COMMOD END
	AND CD_SERIE = CASE WHEN ISNULL(@CD_SERIE,'') ='' THEN CD_SERIE ELSE @CD_SERIE END
GROUP BY
    A.DT_NEGOCIO, A.CD_CLIENTE, A.CD_COMMOD, A.CD_SERIE;

-- Índice pra joins
CREATE CLUSTERED INDEX CX_T1 ON #T1 (CD_CLIENTE, CD_COMMOD, CD_SERIE, DT_NEGOCIO);

-- =========================
-- T2 (MERCADO) materializada
-- =========================
DROP TABLE IF EXISTS #T2;

CREATE TABLE #T2
(
    DT_NEGOCIO     smalldatetime NOT NULL,
    CD_COMMOD      varchar(10)   NOT NULL,   -- ajuste pro tamanho real
    CD_SERIE       varchar(15)   NOT NULL,   -- ajuste pro tamanho real
    VOLUME_MERCADO decimal(19,4) NULL,       -- ou o tipo real
    PR_MEDIO       decimal(19,8) NULL,
    PR_ABERTURA    decimal(19,8) NULL,
    PR_FECHAMENTO  decimal(19,8) NULL
);

INSERT INTO #T2 (DT_NEGOCIO, CD_COMMOD, CD_SERIE, VOLUME_MERCADO, PR_MEDIO, PR_ABERTURA, PR_FECHAMENTO)
SELECT
    X.DATA,
    CAST(X.CD_COMMOD AS varchar(10)) ,
    CAST(X.CD_SERIE  AS varchar(15)) ,
    X.VOLUME,
    X.PR_MEDIO,
    X.PR_ABERTURA,
    X.PR_FECHAMENTO
FROM ST_ATIVO_BMF X WITH (NOLOCK)
WHERE
    X.DATA >= @INICIO
    AND X.DATA <= @FIM
    AND CD_COMMOD = CASE WHEN ISNULL(@CD_COMMOD,'') ='' THEN CD_COMMOD ELSE @CD_COMMOD END
	AND CD_SERIE = CASE WHEN ISNULL(@CD_SERIE,'') ='' THEN CD_SERIE ELSE @CD_SERIE END;

CREATE CLUSTERED INDEX CX_T2 ON #T2 (CD_COMMOD, CD_SERIE, DT_NEGOCIO);
-- (ordem pode ser DT_NEGOCIO, CD_COMMOD, CD_SERIE também; depende do seu join mais frequente)

-- =========================
-- T3 (anteriores) sem recalcular T1/T2
-- =========================
DROP TABLE IF EXISTS #T3;
SELECT
    A.DT_NEGOCIO,
    A.CD_CLIENTE,
    A.CD_COMMOD,
    A.CD_SERIE,
    ISNULL(T1ANT.VOLUME_CLIENTE, 0)      AS VOLUME_CLIENTE_ANT,
    ISNULL(T1ANT.PRECO_MED_CLIENTE, 0)   AS PRECO_MED_CLIENTE_ANT,
    ISNULL(T2ANT.VOLUME_MERCADO, 0)      AS VOL_MERC_ANT
INTO #T3
FROM #T1 A
JOIN ST_PERIODO P WITH (NOLOCK)
    ON P.DT_PERIODO = A.DT_NEGOCIO
LEFT JOIN #T1 T1ANT
    ON T1ANT.DT_NEGOCIO = P.DT_PERIODO_ANT
   AND T1ANT.CD_CLIENTE = A.CD_CLIENTE
   AND T1ANT.CD_COMMOD  = A.CD_COMMOD
   AND T1ANT.CD_SERIE   = A.CD_SERIE
LEFT JOIN #T2 T2CUR
    ON T2CUR.DT_NEGOCIO = A.DT_NEGOCIO
   AND T2CUR.CD_COMMOD  = A.CD_COMMOD
   AND T2CUR.CD_SERIE   = A.CD_SERIE
LEFT JOIN #T2 T2ANT
    ON T2ANT.DT_NEGOCIO = P.DT_PERIODO_ANT
   AND T2ANT.CD_COMMOD  = T2CUR.CD_COMMOD
   AND T2ANT.CD_SERIE   = T2CUR.CD_SERIE;

CREATE INDEX IX_T3 ON #T3 (CD_CLIENTE, CD_COMMOD, CD_SERIE, DT_NEGOCIO);

-- =========================
-- Resultado final
-- =========================
;WITH CLI AS (
    SELECT CD_CLIENTE, MAX(NM_CLIENTE) AS NM_CLIENTE
    FROM V_CLIENTE_TODOS WITH (NOLOCK)
    GROUP BY CD_CLIENTE
)
SELECT
    -- se precisar MUITO do texto pt-br, faça só aqui (não no GROUP BY)
    CONVERT(date, T1.DT_NEGOCIO) AS [Data],

    T1.CD_CLIENTE AS [Cód. do Cliente],
    C.NM_CLIENTE  AS [Nome do Cliente],
    T1.CD_COMMOD  AS [Commodities],
    T1.CD_SERIE   AS [Série],

    MAX(T2.PR_MEDIO)      AS [PRECO MED. MERC],
    MAX(T2.PR_ABERTURA)   AS [PRECO ABERTURA],
    MAX(T2.PR_FECHAMENTO) AS [PRECO FECHAMENTO],

    SUM(T1.VOLUME_CLIENTE) AS [VOLUME CLIENTE],
    AVG(T1.PRECO_MED_CLIENTE) AS [PRECO MED. CLIENTE],

    SUM(T3.VOLUME_CLIENTE_ANT) AS [VOLUME CLIENTE ANT],
    ISNULL(SUM(T1.VOLUME_CLIENTE) / NULLIF(SUM(T3.VOLUME_CLIENTE_ANT), 0), 0) AS [VARIACAO CLIENTE],

    SUM(T2.VOLUME_MERCADO) AS [VOLUME MERCADO],
    SUM(T3.VOL_MERC_ANT)   AS [VOLUME MERCADO ANT],
    ISNULL(SUM(T2.VOLUME_MERCADO) / NULLIF(SUM(T3.VOL_MERC_ANT), 0), 0) AS [VARIACAO MERCADO],

    ISNULL(SUM(T1.VOLUME_CLIENTE) / NULLIF(SUM(T2.VOLUME_MERCADO), 0), 0) AS [VARIACAO CLIENTE X MERC]
FROM #T1 T1
LEFT JOIN #T3 T3
    ON T3.DT_NEGOCIO = T1.DT_NEGOCIO
   AND T3.CD_CLIENTE = T1.CD_CLIENTE
   AND T3.CD_COMMOD  = T1.CD_COMMOD
   AND T3.CD_SERIE   = T1.CD_SERIE
LEFT JOIN #T2 T2
    ON T2.DT_NEGOCIO = T1.DT_NEGOCIO
   AND T2.CD_COMMOD  = T1.CD_COMMOD
   AND T2.CD_SERIE   = T1.CD_SERIE
LEFT JOIN CLI C
    ON C.CD_CLIENTE = T1.CD_CLIENTE
GROUP BY
    CONVERT(date, T1.DT_NEGOCIO),
    T1.CD_CLIENTE,
    C.NM_CLIENTE,
    T1.CD_COMMOD,
    T1.CD_SERIE
ORDER BY
    T1.CD_CLIENTE, T1.CD_COMMOD, T1.CD_SERIE, CONVERT(date, T1.DT_NEGOCIO)
OFFSET (ISNULL(@PAGINA, 1) - 1) * ISNULL(NULLIF(@QTDPORPAGINA, 0), 100000000) ROWS
FETCH NEXT ISNULL(NULLIF(@QTDPORPAGINA, 0), 100000000) ROWS ONLY;