CREATE PROCEDURE [dbo].[PR_ZE_COM_ZE_BVSP] 
(		
	@INICIO DATETIME,		
	@FIM DATETIME,		
    @CD_CLIENTE_COMPRA VARCHAR(10),		
    @CD_PAPEL VARCHAR(10),
	@QTDPORPAGINA INT, @PAGINA INT
)		
--WITH ENCRYPTION
AS		
--DECLARE @PAGINA        INT = 1;
--DECLARE @QTDPORPAGINA INT = 5, 
--@INICIO DATETIME ='20230101',		
--	@FIM DATETIME ='20231231',		
--    @CD_CLIENTE_COMPRA VARCHAR(10) ='',		
--    @CD_PAPEL VARCHAR(10) ='' 


SELECT CONVERT(VARCHAR(20),[DT_PERIODO],103) [PERÍODO]	
	  ,[CD_CLIENTE_COMPRA]	as [CÓD. CLIENTE COMPRA]	
       ,[NM_CLIENTE_COMPRA] [NOME DO CLIENTE COMPRA]		
      ,CASE WHEN [VINC_COMPRA] = 'S' THEN 'SIM'
	  WHEN [VINC_COMPRA] ='N' THEN 'NÃO' END AS [VINC. COMPRA]
      ,[CD_CLIENTE_VENDA] [CÓD. CLIENTE VENDA]		
      ,[NM_CLIENTE_VENDA] [NOME DO CLIENTE]		
      , CASE WHEN [VINC_VENDA] = 'S' THEN 'SIM'
	  WHEN [VINC_VENDA] = 'N' THEN 'NÃO' END AS [ VINC. VENDA]
      --,[SISTEMA_COMPRA] [SISTEMA COMPRA]
      --,[SISTEMA_VENDA]	[SISTEMA VENDA]	
      ,[NR_NEGOCIO]	 [NR. NEGÓCIO]	
      ,SUM([QT_NEGOCIO_COMPRA])[QTD. NEGÓCIO COMPRA]		
      ,SUM([QT_NEGOCIO_VENDA]) [QTD. NEGÓCIO VENDA]		
      ,[CD_PAPEL] ATIVO		
      ,[HH_COMPRA]	[HORA COMPRA]	
      ,[HH_VENDA]	[HORA VENDA]	
      ,SUM([VL_TOTNEG_COMPRA])AS [VL. TOTNEG. COMPRA]		
      ,SUM([VL_TOTNEG_VENDA]) AS[VL. TOTNEG. VENDA]		
      ,SUM([VL_NEGOCIO_COMPRA]) AS[VL. NEGÓCIO COMPRA]		
      ,SUM([VL_NEGOCIO_VENDA])AS [VL. NEGÓCIO VENDA]		
      ,[CD_ASSESSOR_COMPRA]	 AS [CÓD. ASSESSOR COMPRA]	
      ,[DS_ASSESSOR_COMPRA]	AS [DS. ASSESSOR COMPRA]	
      ,[CD_ASSESSOR_VENDA]	AS [CÓD. ASSESSOR VENDA]	
      ,[DS_ASSESSOR_VENDA] AS [DS. ASSESSOR VENDA]	
       ,CD_OPERADOR_COMPRA AS [CÓD. OPERADOR COMPRA]		
       ,DS_OPERADOR_COMPRA AS [DS. OPERADOR COMPRA]		
       ,CD_OPERADOR_VENDA AS [CÓD. OPERADOR VENDA]		
       ,DS_OPERADOR_VENDA AS  [DS. OPERADOR VENDA]
	   ,CD_CLIENTE_BRO_VENDA [CÓD. CLIENTE BRO. VENDA] 
	   , CD_CLIENTE_BRO_COMPRA [CÓD. CLIENTE BRO. COMPRA]		
        ,IN_AFTERM as [IN. AFTERM]
		 		
 FROM  ST_DIRETAS_BVSP
 
  WHERE 		
   CD_CLIENTE_COMPRA = CD_CLIENTE_VENDA  
  AND DT_PERIODO >=@INICIO AND DT_PERIODO<=@FIM 		
  AND CD_CLIENTE_COMPRA = (CASE WHEN ISNULL(@CD_CLIENTE_COMPRA,'') = '' THEN CD_CLIENTE_COMPRA ELSE CONVERT(INT,@CD_CLIENTE_COMPRA) END)		
  AND CD_PAPEL = (CASE WHEN ISNULL(@CD_PAPEL,'')='' THEN CD_PAPEL ELSE @CD_PAPEL END)		
GROUP BY 		
 [CD_CLIENTE_COMPRA]		
      ,[NM_CLIENTE_COMPRA]		
      ,[VINC_COMPRA]		
      ,[CD_CLIENTE_VENDA]		
      ,[NM_CLIENTE_VENDA]		
      ,[VINC_VENDA]		
      ,CONVERT(VARCHAR(20),[DT_PERIODO],103) 		
      ,[SISTEMA_COMPRA]		
      ,[SISTEMA_VENDA]		
      ,[NR_NEGOCIO]		
      ,[CD_PAPEL]		
      ,[HH_COMPRA]		
      ,[HH_VENDA]		
      ,[CD_ASSESSOR_COMPRA]		
      ,[DS_ASSESSOR_COMPRA]		
      ,[CD_ASSESSOR_VENDA]		
      ,[DS_ASSESSOR_VENDA],		
         CD_OPERADOR_COMPRA,		
         DS_OPERADOR_COMPRA,		
         CD_OPERADOR_VENDA,		
         DS_OPERADOR_VENDA,		
CD_CLIENTE_BRO_VENDA, CD_CLIENTE_BRO_COMPRA, IN_AFTERM	

ORDER BY 1
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY