CREATE PROCEDURE [dbo].[FIRA_PR_CARGA_ST_SWINGTRADE_BOVESPA] @PREGAO DATETIME , @PREGAOFIM DATETIME
--WITH ENCRYPTION
AS

DROP TABLE IF EXISTS [dbo].[ST_SWINGTRADE_BOVESPA_PADRAO]
    CREATE TABLE [dbo].[ST_SWINGTRADE_BOVESPA_PADRAO] (
    [PREGAO] datetime NULL,
    [PREGAO_ANT] datetime NULL,
    [CD_CLIENTE] int NOT NULL,
    [PAPEL] nvarchar(20) NULL,
    [QUANTIDADE] float NULL,
    [PRECO_COMPRA] float NULL,
    [PRECO_VENDA] float NULL,
    [RESULTADO] float NULL,
    [QTD_SWINGTRADE] int NULL,
	[DT_FIRA] DATETIME NULL
);

/***************************************************
inicio da comparação entre a tabela
da base padrao fira origem x tabela cliente destino
*****************************************************/
EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo',, @src_table='ST_SWINGTRADE_BOVESPA_PADRAO',
  @schema_name='dbo', @base_table='ST_SWINGTRADE_BOVESPA',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1;

--DECLARE @PREGAO DATETIME , @PREGAOFIM DATETIME   
--SET @PREGAO ='20260201'
--SET @PREGAOFIM ='20260213'

/********************************	
	CARGA ST_SWINGTRADE_BOVESPA		
*********************************/     

---DELETE TABLE     		    		
DELETE ST_SWINGTRADE_BOVESPA WHERE PREGAO >= @PREGAO  and PREGAO <= @PREGAOFIM		


/********************************
#### VARIAVEIS PARA O CURSOR ####
*********************************/        		
DECLARE @PREGAO2 SMALLDATETIME, @PREGAO_ANT2 SMALLDATETIME        		
        			
DECLARE CONTAGEM CURSOR FOR    		
    SELECT DT_PERIODO_ANT, DT_PERIODO  		
    FROM ST_PERIODO 		
    WHERE 
		DT_PERIODO >= @PREGAO		
    AND DT_PERIODO <= @PREGAOFIM        		
        		
OPEN CONTAGEM        		
FETCH NEXT FROM CONTAGEM INTO @PREGAO_ANT2,@PREGAO2        		 		
WHILE @@FETCH_STATUS = 0        		    		
BEGIN        		
        		
	/************************
	#### PREGAO ANTERIOR ####
	*************************/
	SELECT 
		DT_PERIODO, 
		CD_PAPEL,
		CD_CLIENTE, 		
		ISNULL(SUM(CASE WHEN CD_TIPO_OFERTA = 'C' THEN QT_MULTIPLICADOR ELSE 0 END),0) QUANTIDADE_COMPRA,		
		ISNULL(SUM(CASE WHEN CD_TIPO_OFERTA = 'V' THEN QT_MULTIPLICADOR ELSE 0 END),0) QUANTIDADE_VENDA, 		
		ISNULL(SUM(CASE WHEN CD_TIPO_OFERTA = 'C' THEN QT_MULTIPLICADOR ELSE 0 END),0) - ISNULL(SUM(CASE WHEN CD_TIPO_OFERTA = 'V' THEN QT_MULTIPLICADOR ELSE 0 END),0) QUANTIDADE,		
		AVG(CASE WHEN CD_TIPO_OFERTA = 'C' THEN VL_NEGOCIO ELSE NULL END) PRECO_MEDIO_COMPRA,		
		AVG(CASE WHEN CD_TIPO_OFERTA = 'V' THEN VL_NEGOCIO ELSE NULL END) PRECO_MEDIO_VENDA 
	
	INTO #PREGAO_ANT		
	FROM(			
		SELECT 
			DT_NEGOCIO AS DT_PERIODO, 
			CD_CLIENTE, 
			CD_PAPEL, 
			CD_NATOPE AS CD_TIPO_OFERTA,
			SUM(cast(VL_NEGOCIO as decimal(20,2))) AS VL_NEGOCIO,
			SUM(QT_MULTIPLICADOR / FT_VALORIZACAO) AS QT_MULTIPLICADOR,
			NR_NEGOCIO		
			
		FROM ST_CORRETAGEM_ORDEM
		WHERE DT_NEGOCIO = @PREGAO_ANT2
		GROUP BY  CD_CLIENTE, DT_NEGOCIO,CD_PAPEL , CD_NATOPE, NR_NEGOCIO
	)X		
	GROUP BY DT_PERIODO, CD_PAPEL, CD_CLIENTE		
			
			
	DELETE #PREGAO_ANT WHERE ISNULL(QUANTIDADE_VENDA,0) >= ISNULL(QUANTIDADE_COMPRA,0)		
			
			
	/**********************
	#### PREGAO ATUAL ####
	**********************/
	SELECT 
		DT_PERIODO, 
		CD_PAPEL,
		CD_CLIENTE,  		
		ISNULL(SUM(CASE WHEN CD_TIPO_OFERTA = 'C' THEN QT_MULTIPLICADOR ELSE 0 END),0) QUANTIDADE_COMPRA,		
		ISNULL(SUM(CASE WHEN CD_TIPO_OFERTA = 'V' THEN QT_MULTIPLICADOR ELSE 0 END),0) QUANTIDADE_VENDA, 		
		ISNULL(SUM(CASE WHEN CD_TIPO_OFERTA = 'V' THEN QT_MULTIPLICADOR ELSE 0 END),0) - ISNULL(SUM(CASE WHEN CD_TIPO_OFERTA = 'C' THEN QT_MULTIPLICADOR ELSE 0 END),0) QUANTIDADE,		
		AVG(CASE WHEN CD_TIPO_OFERTA = 'C' THEN VL_NEGOCIO ELSE NULL END) PRECO_MEDIO_COMPRA,		
		AVG(CASE WHEN CD_TIPO_OFERTA = 'V' THEN VL_NEGOCIO ELSE NULL END) PRECO_MEDIO_VENDA
	
	INTO #PREGAO		
	FROM(		
		SELECT 
			DT_NEGOCIO AS DT_PERIODO, 
			CD_CLIENTE, 
			CD_PAPEL, 
			CD_NATOPE AS CD_TIPO_OFERTA,
			SUM(cast(VL_NEGOCIO as decimal(20,2))) AS VL_NEGOCIO,
			SUM(QT_MULTIPLICADOR / FT_VALORIZACAO) AS QT_MULTIPLICADOR,
			NR_NEGOCIO		
			
		FROM ST_CORRETAGEM_ORDEM
		WHERE DT_NEGOCIO = @PREGAO2
		GROUP BY  CD_CLIENTE, DT_NEGOCIO, CD_PAPEL, CD_NATOPE, NR_NEGOCIO	
	)X		
			
	GROUP BY DT_PERIODO, CD_PAPEL, CD_CLIENTE		
			
			
	DELETE #PREGAO	WHERE ISNULL(QUANTIDADE_COMPRA,0) >= ISNULL(QUANTIDADE_VENDA,0)		
		

	/**************************
	#### INSERT NA TABELA ####
	**************************/
	INSERT INTO ST_SWINGTRADE_BOVESPA		
	(
	 PREGAO,PREGAO_ANT,CD_CLIENTE,PAPEL,QUANTIDADE,PRECO_COMPRA
	,PRECO_VENDA,RESULTADO,QTD_SWINGTRADE
	)
	SELECT 
		@PREGAO2, 
		@PREGAO_ANT2,
		P.CD_CLIENTE, 
		P.CD_PAPEL, 
		CASE WHEN P.QUANTIDADE > PA.QUANTIDADE THEN PA.QUANTIDADE ELSE P.QUANTIDADE END QUANTIDADE,		
		PA.PRECO_MEDIO_COMPRA,		
		P.PRECO_MEDIO_VENDA, 
		CASE WHEN P.QUANTIDADE > PA.QUANTIDADE THEN PA.QUANTIDADE ELSE P.QUANTIDADE END * (P.PRECO_MEDIO_VENDA - PA.PRECO_MEDIO_COMPRA) RESULTADO, 
		1 AS QTD_SWINGTRADE		
		
	FROM #PREGAO P 
	INNER JOIN #PREGAO_ANT PA		
		ON P.CD_PAPEL = PA.CD_PAPEL		
		AND P.CD_CLIENTE = PA.CD_CLIENTE		
			
		
	/*******************
	#### DROP TEMP ####
	*******************/		
    DROP TABLE #PREGAO      		
    DROP TABLE #PREGAO_ANT   	
	
		
FETCH NEXT FROM CONTAGEM INTO @PREGAO_ANT2, @PREGAO2        		     		
END        		
     		
CLOSE CONTAGEM        		  		
DEALLOCATE CONTAGEM

-- ================================================
-- Marca DT_FIRA para registros carregados (fallback)
-- ================================================
	DECLARE @__dt_fira_now DATETIME = GETDATE();
IF COL_LENGTH(N'dbo.ST_SWINGTRADE_BOVESPA', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE [dbo].[ST_SWINGTRADE_BOVESPA]
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL;
END

/******* fim do processo de carga **********/

--passo 3
/***** limpa a tabela do banco para nao ficar sujeira ******/
DROP TABLE IF EXISTS ST_SWINGTRADE_BOVESPA_PADRAO