CREATE PROCEDURE [dbo].[PR_DAY_TRADE_RESUMO_BMF] @INICIO SMALLDATETIME
	,@FIM SMALLDATETIME
	,@INICIO2 SMALLDATETIME
	,@FIM2 SMALLDATETIME
	,@CD_CLIENTE VARCHAR(50)
	,@QTDPORPAGINA INT
	,@PAGINA INT
	WITH RECOMPILE
AS

--DECLARE @QTDPORPAGINA INT = 1000,        @PAGINA       INT = 1;
--DECLARE @INICIO SMALLDATETIME, @FIM SMALLDATETIME,@INICIO2 SMALLDATETIME,   @FIM2 SMALLDATETIME, @CD_CLIENTE VARCHAR(50)		
--SET @INICIO ='20250101'		
--SET @FIM = '20250131'		
--SET @INICIO2 = '20250101'		
--SET @FIM2 = '20250131'		
--SET @CD_CLIENTE ='17797'		
SET ARITHABORT OFF 		
SET ANSI_WARNINGS OFF		
	;

WITH #T1
AS (
	SELECT CD_CLIENTE_COMPROU
		,@INICIO INICIO
		,@FIM FIM
		,SUM(VL_FINANC) FINAN
		,(
			SELECT CAST(SUM(X.QTD_DIAS_DAYTRADE) AS FLOAT)
			FROM (
				SELECT A.CD_CLIENTE
					,A.DT_DATMOV
					,COUNT(DISTINCT A.DT_DATMOV) AS QTD_DIAS_DAYTRADE
				FROM ST_DAYTRADE_DETALHE_BMF A
				WHERE A.CD_CLIENTE = A2.CD_CLIENTE_COMPROU AND A.DT_DATMOV >= @INICIO AND A.DT_DATMOV <= @FIM AND QT_QTDDET > 0
				AND CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'')='' THEN CD_CLIENTE ELSE ISNULL(@CD_CLIENTE,'') END
				GROUP BY A.CD_CLIENTE
					,A.DT_DATMOV
				) X
			) QTD_DIAS_DAYTRADE
	FROM ST_DAYTRADE_RESUMO_BMF A2
	WHERE DT_PREGAO_COMPROU >= @INICIO AND DT_PREGAO_COMPROU <= @FIM
	GROUP BY CD_CLIENTE_COMPROU
	)
	
	,#T2
	AS (
	SELECT CD_CLIENTE
		,CAST(SUM(ACERTO) AS FLOAT) ACERTO
		,CAST(SUM(PERDA) AS FLOAT) PERDA
		,CAST(SUM(EMPATE) AS FLOAT) EMPATE
	FROM (
		SELECT CD_CLIENTE, CD_COMMOD,CD_SERIE, 
		SUM(CASE WHEN VL_FINAN >0 THEN 1 ELSE 0 END) ACERTO,    
		SUM(CASE WHEN VL_FINAN =0 THEN 1 ELSE 0 END) EMPATE,    
		SUM(CASE WHEN VL_FINAN <0 THEN 1 ELSE 0 END) PERDA,    
		SUM(VL_FINAN) VL_FINAN  
		FROM (
			SELECT DT_PREGAO_COMPROU DT_PREGAO,     
			CD_CLIENTE,CD_COMMOD, CD_SERIE,   
			SUM(CAST(VL_FINANC AS FLOAT)) VL_FINAN     
			FROM ST_DAYTRADE_RESUMO_ATIVO_BMF    
			WHERE DT_PREGAO_COMPROU >= @INICIO AND DT_PREGAO_COMPROU <= @FIM    
			AND CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'')='' THEN CD_CLIENTE ELSE ISNULL(@CD_CLIENTE,'') END    
			GROUP BY DT_PREGAO_COMPROU, CD_CLIENTE, CD_COMMOD,CD_SERIE 	
			) X
		group by  CD_CLIENTE, CD_COMMOD,CD_SERIE
		) X2
	GROUP BY CD_CLIENTE
	)
	
	,#T3
AS (
	SELECT CD_CLIENTE_COMPROU
		,@INICIO INICIO
		,@FIM FIM
		,(CASE WHEN SUM(VL_FINANC) = 0 THEN 0 ELSE SUM(VL_FINANC) END) FINAN
		,(
			SELECT CAST(SUM(X.QTD_DIAS_DAYTRADE) AS FLOAT)
			FROM (
				SELECT A.CD_CLIENTE
					,A.DT_DATMOV,a.cd_commod,a.cd_serie
					,COUNT(DISTINCT A.DT_DATMOV) AS QTD_DIAS_DAYTRADE
				FROM ST_DAYTRADE_DETALHE_BMF A
				WHERE A.CD_CLIENTE = A2.CD_CLIENTE_COMPROU AND A.DT_DATMOV >= @INICIO2 AND A.DT_DATMOV <= @FIM2 AND QT_QTDDET > 0
				AND CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'')='' THEN CD_CLIENTE ELSE ISNULL(@CD_CLIENTE,'') END
				GROUP BY A.CD_CLIENTE,a.cd_commod,a.cd_serie
					,A.DT_DATMOV
				) X
			) QTD_DIAS_DAYTRADE
	FROM ST_DAYTRADE_RESUMO_BMF A2
	WHERE DT_PREGAO_COMPROU >= @INICIO2 AND DT_PREGAO_COMPROU <= @FIM2
	GROUP BY CD_CLIENTE_COMPROU
	)

	,#T4
AS (
	SELECT CD_CLIENTE
		,CAST(SUM(ACERTO) AS FLOAT) ACERTO
		,CAST(SUM(PERDA) AS FLOAT) PERDA
		,CAST(SUM(EMPATE) AS FLOAT) EMPATE
	FROM (
		SELECT CD_CLIENTE
			,CASE WHEN VL_ACERTO > 0 THEN 1 ELSE 0 END ACERTO
			,CASE WHEN VL_ACERTO < 0 THEN 1 ELSE 0 END PERDA
			,CASE WHEN VL_ACERTO = 0 THEN 1 ELSE 0 END EMPATE
		FROM (
			SELECT DT_DATMOV DT_PREGAO
				,A.CD_CLIENTE
				,CD_COMMOD ,CD_SERIE,		
				CAST(SUM(CAST(VL_VALOPE AS NUMERIC(15, 2))) AS FLOAT) VL_ACERTO
			FROM ST_DAYTRADE_DETALHE_BMF A
			WHERE DT_DATMOV >= @INICIO2 AND DT_DATMOV <= @FIM2
			AND CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'')='' THEN CD_CLIENTE ELSE ISNULL(@CD_CLIENTE,'') END
			GROUP BY DT_DATMOV
				,CD_CLIENTE , CD_COMMOD, CD_SERIE		
			) X
		) X2
	GROUP BY CD_CLIENTE
	)


SELECT DISTINCT FORMAT(T1.INICIO, 'd', 'pt-br') [DATA INÍCIO]
	,FORMAT(T1.FIM, 'd', 'pt-br') [DATA FIM]
	,T1.CD_CLIENTE_COMPROU [CÓD. CLIENTE]
	,XX.NM_CLIENTE AS [NOME DO CLIENTE]
	,FORMAT(T1.QTD_DIAS_DAYTRADE, '#,0', 'PT-BR') [QTD. DIAS DAYTRADES]
	,FORMAT(T1.FINAN, 'F', 'PT-BR') [RESULTADO FINANCEIRO]
	,FORMAT(T2.ACERTO, '#,0', 'PT-BR') ACERTO
	,FORMAT(T2.PERDA, '#,0', 'PT-BR') PERDA
	,FORMAT(T2.EMPATE, '#,0', 'PT-BR') EMPATE
	,FORMAT(T2.ACERTO / (T2.ACERTO + T2.PERDA + T2.EMPATE), 'P2') [PERC. ACERTO]
	,FORMAT(ISNULL(CAST(#T4.ACERTO AS FLOAT) / NULLIF(CAST(T3.QTD_DIAS_DAYTRADE AS FLOAT), 0), 0), 'P2') [PERC. ACERTO ANTERIOR]
FROM #T1 T1
LEFT OUTER JOIN #T2 T2 ON T1.CD_CLIENTE_COMPROU = T2.CD_CLIENTE
LEFT OUTER JOIN #T3 T3 ON T1.CD_CLIENTE_COMPROU = T3.CD_CLIENTE_COMPROU
LEFT OUTER JOIN #T4 ON T1.CD_CLIENTE_COMPROU = #T4.CD_CLIENTE
LEFT OUTER JOIN V_CLIENTE_TODOS XX ON T1.CD_CLIENTE_COMPROU = XX.CD_CLIENTE
WHERE T1.CD_CLIENTE_COMPROU = CASE WHEN ISNULL(@CD_CLIENTE, '') = '' THEN T1.CD_CLIENTE_COMPROU ELSE ISNULL(@CD_CLIENTE, '') END

ORDER BY 1 OFFSET(ISNULL(@PAGINA, 1) - 1) * CASE WHEN ISNULL(@QTDPORPAGINA, '') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN ISNULL(@QTDPORPAGINA, '') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;