CREATE   PROCEDURE [dbo].[FIRA_PR_CARGA_ST_DADOS_BASICOS_PF]  
--WITH ENCRYPTION
AS 

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ST_DADOS_BASICOS_PF_PADRAO]') AND type in (N'U'))
CREATE TABLE [dbo].[ST_DADOS_BASICOS_PF_PADRAO](
	[NM_CLIENTE] [nvarchar](160) NULL,
	[CD_CLIENTE] [int] NOT NULL,
	[CD_CPFCGC] [varchar](20) NULL,
	[DT_CRIACAO] [datetime] NULL,
	[DT_ATUALIZ] [datetime] NULL,
	[NM_LOGRADOURO] [nvarchar](160) NULL,
	[NR_PREDIO] [nvarchar](160) NULL,
	[NM_COMP_ENDE] [nvarchar](160) NULL,
	[NM_BAIRRO] [nvarchar](160) NULL,
	[NM_CIDADE] [nvarchar](160) NULL,
	[SG_ESTADO] [nvarchar](160) NULL,
	[SG_PAIS] [nvarchar](160) NULL,
	[NM_E_MAIL] [nvarchar](160) NULL,
	[IN_PESS_VINC] [nvarchar](160) NULL,
	[DT_NASC_FUND] [datetime2](7) NULL,
	[DS_TIPO_CLIENTE] [nvarchar](160) NULL,
	[NM_PAI] [nvarchar](160) NULL,
	[NM_MAE] [nvarchar](160) NULL,
	[NM_CONJUGE] [nvarchar](160) NULL,
	[NR_TELEFONE] [numeric](18, 0) NULL,
	[DS_NACION] [varchar](160) NULL,
	[IN_POLITICO_EXP] [nvarchar](160) NULL,
	[NM_EMIT_ORDEM] [nvarchar](160) NULL,
	[CD_CPFCGC_EMIT] [varchar](20) NULL,
	[CD_DOC_IDENT_EMIT] [nvarchar](50) NULL,
	[EMISSOR_PRINCIPAL] [nvarchar](160) NULL,
	[CD_SISTEMA] [nvarchar](50) NULL,
	[ENDE_SEQ] [int] NULL,
	[MAIL_SEQ] [int] NULL,
	[CD_ASSESSOR] [numeric](18, 0) NULL,
	[CD_CON_DEP] [varchar](10) NULL,
	[DS_CON_DEP] [varchar](10) NULL,
	[IN_CONTA_INV] [nvarchar](160) NULL,
	[IN_SITUAC] [nvarchar](160) NULL,
	[cd_Cep] [varchar](9) NULL,
	[CD_DDD_TEL] [int] NULL,
	[TP_SITUAC] [varchar](160) NULL,
	[nm_grupo] [varchar](160) NULL,
	[NM_ASSESSOR] [varchar](160) NULL,
	[VL_OPERACIONAL1] [float] NULL,
	[VL_OPERACIONAL2] [float] NULL,
	[VL_OPERACIONAL3] [float] NULL,
	[VL_CAPACIDADE_FIN] [float] NULL,
	[DS_ATIV] [varchar](160) NULL,
	[DS_CARGO] [nvarchar](160) NULL,
	[DT_ATUALIZ_SALARIO] [datetime] NULL,
	[TP_CLIENTE] [varchar](100) NULL,
	[NM_RESU_ASSES] [varchar](160) NULL,
	[IND_CAD_SIMP] [nvarchar](160) NULL,
	[IN_PRINCIPAL] [nvarchar](160) NULL,
	[IN_PROCUR] [nvarchar](160) NULL,
	[DT_ULT_OPER] [datetime] NULL,
	[DT_VALIDADE] [datetime] NULL,
	[NM_COMPL_NOME] [varchar](150) NULL,
	[CPFCNPJ] [varchar](20) NULL,
	[IN_QUALIFICADO] [char](1) NULL,
	[CD_CNPJ_EMPRESA] [varchar](20) NULL,
	[DT_FIRA] DATETIME NULL
) ON [PRIMARY]


/***************************************************
inicio da comparação entre a tabela
da base padrao fira origem x tabela cliente destino
*****************************************************/
EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo',, @src_table='ST_DADOS_BASICOS_PF_PADRAO',
  @schema_name='dbo', @base_table='ST_DADOS_BASICOS_PF',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1;

 
-- 2) TRUNCATE pode ficar estático
TRUNCATE TABLE ST_DADOS_BASICOS_PF	
	
/**********************************************************************
3) INSERT em SQL dinâmico (compila após o ALTER) INSERT com lista 
explícita de colunas Isso evita dor de cabeça caso a tabela destino 
tenha colunas a mais, ordem diferente, identity, etc.
**********************************************************************/
DECLARE @sql nvarchar(max) = N'
INSERT INTO ST_DADOS_BASICOS_PF	
(
	 NM_CLIENTE,CD_CLIENTE,CD_CPFCGC,DT_CRIACAO,DT_ATUALIZ,NM_LOGRADOURO
	,NR_PREDIO,NM_COMP_ENDE,NM_BAIRRO,NM_CIDADE,SG_ESTADO,SG_PAIS,NM_E_MAIL
	,IN_PESS_VINC,DT_NASC_FUND,DS_TIPO_CLIENTE,NM_PAI,NM_MAE,NM_CONJUGE
	,NR_TELEFONE,DS_NACION,IN_POLITICO_EXP,NM_EMIT_ORDEM,CD_CPFCGC_EMIT
	,CD_DOC_IDENT_EMIT,EMISSOR_PRINCIPAL,CD_SISTEMA,ENDE_SEQ,MAIL_SEQ
	,CD_ASSESSOR,CD_CON_DEP,DS_CON_DEP,IN_CONTA_INV,IN_SITUAC,cd_Cep
	,CD_DDD_TEL,TP_SITUAC,nm_grupo,NM_ASSESSOR,VL_OPERACIONAL1,VL_OPERACIONAL2
	,VL_OPERACIONAL3,VL_CAPACIDADE_FIN,DS_ATIV,DS_CARGO,DT_ATUALIZ_SALARIO
	,TP_CLIENTE,NM_RESU_ASSES,IND_CAD_SIMP,IN_PRINCIPAL,IN_PROCUR,DT_ULT_OPER
	,DT_VALIDADE,NM_COMPL_NOME,CPFCNPJ,IN_QUALIFICADO,CD_CNPJ_EMPRESA
)
	
SELECT  
	B.NM_CLIENTE,
	A.CD_CLIENTE,
	A.CD_CPFCGC,
	B.DT_CRIACAO,
	B.DT_ATUALIZ,
	C.NM_LOGRADOURO,
	C.NR_PREDIO,
	C.NM_COMP_ENDE,
	C.NM_BAIRRO,
	C.NM_CIDADE,
	C.SG_ESTADO, 
	C.SG_PAIS, 
	ISNULL(M.NM_E_MAIL, C.NM_E_MAIL) NM_E_MAIL,
	B.IN_PESS_VINC,
	B.DT_NASC_FUND,
	E.DS_TIPO_CLIENTE,
	F.NM_PAI,
	F.NM_MAE,
	F.NM_CONJUGE,
	C.NR_TELEFONE,
	G.DS_NACION,
	B.IN_POLITICO_EXP,
	H.NM_EMIT_ORDEM,
	H.CD_CPFCGC_EMIT,
	H.CD_DOC_IDENT_EMIT,
	H.IN_PRINCIPAL AS EMISSOR_PRINCIPAL,
	H.CD_SISTEMA,
	NULL AS ENDE_SEQ,
	NULL AS MAIL_SEQ,
	A.CD_ASSESSOR,
	A.CD_CON_DEP,
	I.DS_CON_DEP,
	A.IN_CONTA_INV,
	A.IN_SITUAC,
	CAST(C.CD_CEP AS VARCHAR) +''-''+CAST(C.CD_CEP_EXT AS VARCHAR) AS CD_CEP,
	C.CD_DDD_TEL,
	CASE 
		WHEN B.TP_SITUAC = ''AT'' THEN ''ATIVO''
		WHEN B.TP_SITUAC = ''IN'' THEN ''INATIVO''
		WHEN B.TP_SITUAC = ''BL'' THEN ''BLOQUEADO''
		WHEN B.TP_SITUAC = ''EN'' THEN ''ENCERRADO''
	ELSE ''OUTROS'' END TP_SITUAC,
	J.NM_GRUPO, 
	K.NM_ASSESSOR,
	B.VL_OPERACIONAL1, 
	B.VL_OPERACIONAL2, 
	B.VL_OPERACIONAL3, 
	B.VL_CAPACIDADE_FIN , 
	L.DS_ATIV, 
	F.DS_CARGO,
	DT_VL_OPERACIONAL,
	E.TP_CLIENTE,
	K.NM_RESU_ASSES,
	A.IND_CAD_SIMP,
	h.IN_PRINCIPAL,
	D.IN_PROCUR,
	A.DT_ULT_OPER,
	CASE 
		WHEN D.DT_VALIDADE < CONVERT(VARCHAR,''17530101'',103) THEN CONVERT(VARCHAR,''99991231'',103)
		ELSE D.DT_VALIDADE 
	END AS DT_VALIDADE,
	NM_COMPL_NOME,---inserido 17.11.2023 devido suitability
	NULL AS CPFCNPJ,
	null AS IN_QUALIFICADO,
	CD_CNPJ_EMPRESA

FROM TSCCLIBOL A (NOLOCK)
LEFT OUTER  JOIN TSCCLIGER B (NOLOCK)
	ON  A.CD_CPFCGC = B.CD_CPFCGC
	AND A.DT_NASC_FUND = B.DT_NASC_FUND
	AND A.CD_CON_DEP = B.CD_CON_DEP

LEFT OUTER JOIN TSCENDE C  (NOLOCK)
	ON A.CD_CPFCGC =  C.CD_CPFCGC 
	AND A.DT_NASC_FUND = C.DT_NASC_FUND 
	AND A.CD_CON_DEP = C.CD_CON_DEP 

LEFT OUTER JOIN TSCDOCS D  	 (NOLOCK)
	ON A.CD_CPFCGC = D.CD_CPFCGC  	
    AND A.DT_NASC_FUND = D.DT_NASC_FUND  	
    AND A.CD_CON_DEP = D.CD_CON_DEP 

LEFT OUTER JOIN TSCTIPCLI E (NOLOCK)
	ON  B.TP_CLIENTE = E.TP_CLIENTE

LEFT OUTER JOIN TSCCLICOMP F (NOLOCK)
	ON A.CD_CPFCGC = F.CD_CPFCGC
	AND A.DT_NASC_FUND = F.DT_NASC_FUND
	AND A.CD_CON_DEP = F.CD_CON_DEP

LEFT OUTER JOIN TSCNACION G (NOLOCK)
	ON F.CD_NACION = G.CD_NACION

LEFT OUTER JOIN TSCEMITORDEM H  (NOLOCK)
	ON A.CD_CPFCGC = H.CD_CPFCGC
	AND A.DT_NASC_FUND = H.DT_NASC_FUND
	AND A.CD_CON_DEP = H.CD_CON_DEP

LEFT OUTER JOIN TSCCONDEP I (NOLOCK)
	ON A.CD_CON_DEP = I.CD_CON_DEP

LEFT OUTER JOIN TSCCLIGRUPO J (NOLOCK)
	ON B.CD_GRUPO = J.CD_GRUPO

LEFT OUTER JOIN TSCASSES K  (NOLOCK)
	ON A.CD_ASSESSOR = K.CD_ASSESSOR

LEFT OUTER JOIN TSCATIV L   (NOLOCK)
	ON F.CD_ATIV = L.CD_ATIV 

LEFT OUTER JOIN TSCEMAIL M (NOLOCK)
	ON A.CD_CPFCGC = M.CD_CPFCGC
	AND A.DT_NASC_FUND = M.DT_NASC_FUND

				
WHERE B.TP_PESSOA = ''F''

 
INSERT INTO ST_DADOS_BASICOS_PF	
(
	 NM_CLIENTE,CD_CLIENTE,CD_CPFCGC,DT_CRIACAO,DT_ATUALIZ,NM_LOGRADOURO
	,NR_PREDIO,NM_COMP_ENDE,NM_BAIRRO,NM_CIDADE,SG_ESTADO,SG_PAIS,NM_E_MAIL
	,IN_PESS_VINC,DT_NASC_FUND,DS_TIPO_CLIENTE,NM_PAI,NM_MAE,NM_CONJUGE
	,NR_TELEFONE,DS_NACION,IN_POLITICO_EXP,NM_EMIT_ORDEM,CD_CPFCGC_EMIT
	,CD_DOC_IDENT_EMIT,EMISSOR_PRINCIPAL,CD_SISTEMA,ENDE_SEQ,MAIL_SEQ
	,CD_ASSESSOR,CD_CON_DEP,DS_CON_DEP,IN_CONTA_INV,IN_SITUAC,cd_Cep
	,CD_DDD_TEL,TP_SITUAC,nm_grupo,NM_ASSESSOR,VL_OPERACIONAL1,VL_OPERACIONAL2
	,VL_OPERACIONAL3,VL_CAPACIDADE_FIN,DS_ATIV,DS_CARGO,DT_ATUALIZ_SALARIO
	,TP_CLIENTE,NM_RESU_ASSES,IND_CAD_SIMP,IN_PRINCIPAL,IN_PROCUR,DT_ULT_OPER
	,DT_VALIDADE,NM_COMPL_NOME,CPFCNPJ,IN_QUALIFICADO,CD_CNPJ_EMPRESA
)
SELECT  
	B.NM_CLIENTE,
	A.CD_CLIENTE,
	A.CD_CPFCGC,
	B.DT_CRIACAO,
	B.DT_ATUALIZ,
	C.NM_LOGRADOURO,
	C.NR_PREDIO,
	C.NM_COMP_ENDE,
	C.NM_BAIRRO,
	C.NM_CIDADE,
	C.SG_ESTADO, 
	C.SG_PAIS, 
	ISNULL(M.NM_E_MAIL, C.NM_E_MAIL) NM_E_MAIL,
	B.IN_PESS_VINC,
	B.DT_NASC_FUND,
	E.DS_TIPO_CLIENTE,
	F.NM_PAI,
	F.NM_MAE,
	F.NM_CONJUGE,
	C.NR_TELEFONE,
	G.DS_NACION,
	B.IN_POLITICO_EXP,
	H.NM_EMIT_ORDEM,
	H.CD_CPFCGC_EMIT,
	H.CD_DOC_IDENT_EMIT,
	H.IN_PRINCIPAL AS EMISSOR_PRINCIPAL,
	H.CD_SISTEMA,
	NULL AS ENDE_SEQ,
	NULL AS MAIL_SEQ,
	NULL AS CD_ASSESSOR,
	A.CD_CON_DEP,
	I.DS_CON_DEP,
	NULL AS IN_CONTA_INV,
	NULL AS IN_SITUAC,
	CAST(C.CD_CEP AS VARCHAR) +''-''+CAST(C.CD_CEP_EXT AS VARCHAR) AS CD_CEP,
	C.CD_DDD_TEL,
	CASE 
		WHEN B.TP_SITUAC = ''AT'' THEN ''ATIVO''
		WHEN B.TP_SITUAC = ''IN'' THEN ''INATIVO''
		WHEN B.TP_SITUAC = ''BL'' THEN ''BLOQUEADO''
		WHEN B.TP_SITUAC = ''EN'' THEN ''ENCERRADO''
	ELSE ''OUTROS'' END TP_SITUAC,
	J.NM_GRUPO, 
	K.NM_ASSESSOR,
	B.VL_OPERACIONAL1, 
	B.VL_OPERACIONAL2, 
	B.VL_OPERACIONAL3, 
	B.VL_CAPACIDADE_FIN , 
	L.DS_ATIV, 
	F.DS_CARGO,
	DT_VL_OPERACIONAL,
	E.TP_CLIENTE,
	K.NM_RESU_ASSES,
	NULL AS IND_CAD_SIMP,
	h.IN_PRINCIPAL,
	D.IN_PROCUR,
	NULL AS DT_ULT_OPER,
	CASE 
		WHEN D.DT_VALIDADE < CONVERT(VARCHAR,''17530101'',103) THEN CONVERT(VARCHAR,''99991231'',103)
		ELSE D.DT_VALIDADE 
	END AS DT_VALIDADE,
    null as NM_COMPL_NOME,
	NULL AS CPFCNPJ,
	null AS IN_QUALIFICADO,
	CD_CNPJ_EMPRESA

FROM TSCCLICC A (NOLOCK)
LEFT OUTER  JOIN TSCCLIGER B (NOLOCK)
	ON  A.CD_CPFCGC = B.CD_CPFCGC
	AND A.DT_NASC_FUND = B.DT_NASC_FUND
	AND A.CD_CON_DEP = B.CD_CON_DEP

LEFT OUTER JOIN TSCENDE C  (NOLOCK)
	ON A.CD_CPFCGC =  C.CD_CPFCGC 
	AND A.DT_NASC_FUND = C.DT_NASC_FUND 
	AND A.CD_CON_DEP = C.CD_CON_DEP 

LEFT OUTER JOIN TSCDOCS D  	 (NOLOCK)
	ON A.CD_CPFCGC = D.CD_CPFCGC  	
    AND A.DT_NASC_FUND = D.DT_NASC_FUND  	
    AND A.CD_CON_DEP = D.CD_CON_DEP 

LEFT OUTER JOIN TSCTIPCLI E (NOLOCK)
	ON  B.TP_CLIENTE = E.TP_CLIENTE

LEFT OUTER JOIN TSCCLICOMP F (NOLOCK)
	ON A.CD_CPFCGC = F.CD_CPFCGC
	AND A.DT_NASC_FUND = F.DT_NASC_FUND
	AND A.CD_CON_DEP = F.CD_CON_DEP

LEFT OUTER JOIN TSCNACION G (NOLOCK)
	ON F.CD_NACION = G.CD_NACION

LEFT OUTER JOIN TSCEMITORDEM H (NOLOCK)
	ON A.CD_CPFCGC = H.CD_CPFCGC
	AND A.DT_NASC_FUND = H.DT_NASC_FUND
	AND A.CD_CON_DEP = H.CD_CON_DEP

LEFT OUTER JOIN TSCCONDEP I (NOLOCK)
	ON A.CD_CON_DEP = I.CD_CON_DEP

LEFT OUTER JOIN TSCCLIGRUPO J (NOLOCK)
	ON B.CD_GRUPO = J.CD_GRUPO

LEFT OUTER JOIN TSCASSES K  (NOLOCK)
	ON B.CD_ASSESSOR = K.CD_ASSESSOR

LEFT OUTER JOIN TSCATIV L   (NOLOCK)
	ON F.CD_ATIV = L.CD_ATIV 

LEFT OUTER JOIN TSCEMAIL M (NOLOCK)
	ON A.CD_CPFCGC = M.CD_CPFCGC
	AND A.DT_NASC_FUND = M.DT_NASC_FUND
	
 
				
WHERE B.TP_PESSOA = ''F''
AND A.CD_CLIENTE NOT IN (SELECT DISTINCT CD_CLIENTE FROM ST_DADOS_BASICOS_PF (NOLOCK))
 
 update ST_DADOS_BASICOS_PF
 set cpfcnpj = dbo.FORMATAR_CPF(CD_CPFCGC)

 	 DROP TABLE IF EXISTS #Q
	 SELECT CD_CLIENTE INTO #Q  FROM ST_DADOS_BASICOS_PF
	 WHERE IN_QUALIFICADO IS NULL

	 DROP TABLE IF EXISTS #V
	 SELECT A.CD_CLIENTE,IN_QUALIFICADO INTO #V FROM ST_V_TBOMOVCL A
	 JOIN #Q B ON A.CD_CLIENTE=B.CD_CLIENTE
	 
	 UPDATE A
	 SET A.IN_QUALIFICADO = B.IN_QUALIFICADO
	 FROM ST_DADOS_BASICOS_PF A JOIN #V B ON A.CD_CLIENTE=B.CD_CLIENTE
';
EXEC sys.sp_executesql @sql;
/******* fim do processo de carga **********/

-- ================================================
-- Marca DT_FIRA para registros carregados (fallback)
-- ================================================
DECLARE @__dt_fira_now DATETIME = GETDATE();
IF COL_LENGTH(N'dbo.ST_DADOS_BASICOS_PF', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE [dbo].[ST_DADOS_BASICOS_PF]
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL;
END


--passo 3
/***** limpa a tabela do banco para nao ficar sujeira ******/
DROP TABLE IF EXISTS ST_DADOS_BASICOS_PF_PADRAO