/****** Object:  StoredProcedure [dbo].[FIRA_PR_CARGA_ALERT_301_MEDIA_BOVESPA_01]    Script Date: 25/02/2026 15:50:21 ******/

CREATE PROCEDURE [dbo].[FIRA_PR_CARGA_ALERT_301_MEDIA_BOVESPA_01] @PREGAO SMALLDATETIME, @AUX INT
WITH RECOMPILE	
AS

--"AND NOT (DATEDIFF(MONTH, C.DT_CRIACAO, @DT_REF) IN (0, 1, 2))" comentado por Heitor e Saulo e AND B.MEDIA >= 1 adicionado em 25/05/26
/*************************************************************************************************
REGRA DO ALERTA:
Volume mês > média 6 meses + 3 desvios padrão
Volume mês (pf/pj) > Q3 + (1.5 * IQR)
Onde: IQR (intervalo Interquartil) e Q3 (terceiro quartil)
*************************************************************************************************/

 --passo 1
/**********************************
inicio da etapa de verificação
aqui temos o script da base padrao
***********************************/
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ST_ALERT_MEDIA_BOVESPA_01_PADRAO]') AND type in (N'U'))
CREATE TABLE [dbo].[ST_ALERT_MEDIA_BOVESPA_01_PADRAO](
	[DATA] [date] NULL,
	[CD_CLIENTE] [int] NOT NULL,
	[VOLUME] [float] NULL,
	[MEDIA] [float] NULL,
	[DESVIO] [float] NULL,
	[ATV_TOT] [varchar](MAX) NULL,
	[QTD_MES] [float] NULL,
	[DT_FIRA] DATETIME NULL
) ON [PRIMARY]
 

/***************************************************
inicio da comparação entre a tabela
da base padrao fira origem x tabela cliente destino
*****************************************************/
EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo', @src_table='ST_ALERT_MEDIA_BOVESPA_01_PADRAO',
  @schema_name='dbo', @base_table='ST_ALERT_MEDIA_BOVESPA_01',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1;
/******** fim da etapa de verificação ************/


/*********inicio da carga do alerta*******/
--DECLARE @PREGAO SMALLDATETIME, @AUX INT
--SET @PREGAO = '20260105'
--SET @AUX = (SELECT DAY(@PREGAO))
 
declare @dt_ini date = dateadd(month, datediff(month,0, dateadd(month,-1,@pregao)),0) -- 1 dia do mes atual
declare @dt_fim date = dateadd(month,1,@dt_ini) -- ultimo dia do mes atual
declare @dt_ini_6m date = dateadd(month, datediff(month,0, dateadd(month,-7,@pregao)),0) -- primeiro dia do 6 mes anterior ao mes atual
declare @dt_fim_6m date = @dt_ini -- 1 dia do mes atual
DECLARE @DT_REF DATE = DATEADD(DAY, - @AUX, @PREGAO);



--VOLUME MENSAL POR CLIENTE
DROP TABLE IF EXISTS #MBOV;
	SELECT CD_CLIENTE
		,CAST(SUM(ISNULL(VL_TOTNEG, 0)) AS NUMERIC(18, 2)) AS VOLUME
		,SUM(ISNULL(QT_MULTIPLICADOR, 0)) AS QTD_MES
	INTO #MBOV
	FROM ST_CORRETAGEM_ORDEM
	WHERE DT_NEGOCIO >= @dt_ini
		AND DT_NEGOCIO < @dt_fim
	GROUP BY CD_CLIENTE;

CREATE CLUSTERED INDEX IX_MBOV ON #MBOV (CD_CLIENTE);

---CLIENTES (JOIN AO INVÉS DE EXISTS)
DROP TABLE IF EXISTS #CLIENTE;
	SELECT DISTINCT a.CD_CLIENTE,a.DT_CRIACAO
	INTO #CLIENTE
	FROM ST_DADOS_BASICOS_PF a
	JOIN #MBOV b ON a.CD_CLIENTE = b.CD_CLIENTE
	UNION ALL
	SELECT DISTINCT a.CD_CLIENTE,a.DT_CRIACAO
	FROM ST_DADOS_BASICOS_PJ a
	JOIN #MBOV b ON a.CD_CLIENTE = b.CD_CLIENTE


DROP TABLE IF EXISTS #CLIENTEPF
SELECT DISTINCT a.CD_CLIENTE
	,a.DT_CRIACAO
INTO #CLIENTEPF
FROM ST_DADOS_BASICOS_PF a
JOIN #MBOV b ON a.CD_CLIENTE = b.CD_CLIENTE;


DROP TABLE IF EXISTS #CLIENTEPJ
SELECT DISTINCT a.CD_CLIENTE
	,a.DT_CRIACAO
INTO #CLIENTEPJ
FROM ST_DADOS_BASICOS_PJ a
JOIN #MBOV b ON a.CD_CLIENTE = b.CD_CLIENTE;

CREATE NONCLUSTERED INDEX IX_PF ON #CLIENTEPF (CD_CLIENTE);

CREATE NONCLUSTERED INDEX IX_PJ ON #CLIENTEPJ (CD_CLIENTE);

CREATE NONCLUSTERED INDEX IX_CLIENTE ON #CLIENTE (CD_CLIENTE) INCLUDE (DT_CRIACAO);

----VOLUME PF / PJ
DROP TABLE IF EXISTS #MBOV_PF
	,#MBOV_PJ;
	SELECT M.CD_CLIENTE
		,M.VOLUME
	INTO #MBOV_PF
	FROM #MBOV M
	JOIN #CLIENTEPF PF ON PF.CD_CLIENTE = M.CD_CLIENTE;

SELECT M.CD_CLIENTE
	,M.VOLUME
INTO #MBOV_PJ
FROM #MBOV M
JOIN #CLIENTEPJ PJ ON PJ.CD_CLIENTE = M.CD_CLIENTE;

----QUARTIS (SEM OVER())
DROP TABLE IF EXISTS #QUARTIL_PF;
	SELECT DISTINCT Q1
		,Q3
		,(Q3 - Q1) AS IQR
		,(Q3 + 1.5 * (Q3 - Q1)) AS LIMITE_SUPERIOR_PF
	INTO #QUARTIL_PF
	FROM (
		SELECT PERCENTILE_CONT(0.25) WITHIN
		GROUP (
				ORDER BY VOLUME
				) OVER () AS Q1
			,PERCENTILE_CONT(0.75) WITHIN
		GROUP (
				ORDER BY VOLUME
				) OVER () AS Q3
		FROM #MBOV_PF
		) X;

DROP TABLE IF EXISTS #QUARTIL_PJ;
	SELECT DISTINCT Q1
		,Q3
		,(Q3 - Q1) AS IQR
		,(Q3 + 1.5 * (Q3 - Q1)) AS LIMITE_SUPERIOR_PJ
	INTO #QUARTIL_PJ
	FROM (
		SELECT PERCENTILE_CONT(0.25) WITHIN
		GROUP (
				ORDER BY VOLUME
				) OVER () AS Q1
			,PERCENTILE_CONT(0.75) WITHIN
		GROUP (
				ORDER BY VOLUME
				) OVER () AS Q3
		FROM #MBOV_PJ
		) X;

---MÉDIA E DESVIO – 6 MESES
DROP TABLE IF EXISTS #MBOV_MEDIA;
	SELECT CD_CLIENTE
		,CAST(AVG(VOLUME) AS NUMERIC(18, 2)) AS MEDIA
		,CAST(STDEV(VOLUME) AS NUMERIC(18, 2)) AS DESVIO
	INTO #MBOV_MEDIA
	FROM (
		SELECT X.CD_ANOMES
			,F.CD_CLIENTE
			,SUM(ISNULL(F.VL_TOTNEG, 0)) AS VOLUME
		FROM ST_CORRETAGEM_ORDEM F
		JOIN ST_PERIODO X ON X.DT_PERIODO = F.DT_NEGOCIO
		WHERE X.DT_PERIODO >= @DT_INI_6M
			AND X.DT_PERIODO < @DT_FIM_6M
		GROUP BY X.CD_ANOMES
			,F.CD_CLIENTE
		) Z
	GROUP BY CD_CLIENTE;

CREATE CLUSTERED INDEX IX_MBOV_MEDIA ON #MBOV_MEDIA (CD_CLIENTE);

----ATIVOS POR CLIENTE
DROP TABLE IF EXISTS #ATIVOS_VOLUME;
	SELECT CD_CLIENTE
		,CD_PAPEL
		,SUM(ISNULL(VL_TOTNEG, 0)) AS VOLUME
	INTO #ATIVOS_VOLUME
	FROM ST_CORRETAGEM_ORDEM
	WHERE DT_NEGOCIO >= @dt_ini
		AND DT_NEGOCIO < @dt_fim
	GROUP BY CD_CLIENTE
		,CD_PAPEL;

CREATE NONCLUSTERED INDEX IX_ATIVOS ON #ATIVOS_VOLUME (CD_CLIENTE) INCLUDE (
	CD_PAPEL
	,VOLUME
	);

----CONCATENAÇÃO DE ATIVOS (SQL 2016 SAFE)
DROP TABLE IF EXISTS #TOTAL_ATIVOS2;
	SELECT A.CD_CLIENTE
		,STUFF((
				SELECT ', ' + V.CD_PAPEL
				FROM #ATIVOS_VOLUME V
				WHERE V.CD_CLIENTE = A.CD_CLIENTE
				ORDER BY V.VOLUME DESC
				FOR XML PATH('')
					,TYPE
				).value('.', 'VARCHAR(MAX)'), 1, 2, '') AS ATIVOS_TOTAL
	INTO #TOTAL_ATIVOS2
	FROM #ATIVOS_VOLUME A
	GROUP BY A.CD_CLIENTE;

CREATE CLUSTERED INDEX IX_TOTAL_ATIVOS ON #TOTAL_ATIVOS2 (CD_CLIENTE);

----RESULTADO FINAL + FILTROS
DROP TABLE IF EXISTS #CLI;
	SELECT @DT_REF AS DATA
		,A.CD_CLIENTE
		,C.DT_CRIACAO AS DT_CRIACAO_GERAL
		,PJ.DT_CRIACAO AS DT_CRIACAO_PJ
		,PF.DT_CRIACAO AS DT_CRIACAO_PF
		,CASE 
			WHEN YEAR(@DT_REF) * 100 + MONTH(@DT_REF) = YEAR(C.DT_CRIACAO) * 100 + MONTH(C.DT_CRIACAO)
				THEN 'SIM'
			ELSE 'NAO'
			END AS MESMO_MES
		,DATEDIFF(MONTH, C.DT_CRIACAO, @DT_REF) AS MESES
		,A.VOLUME
		,B.MEDIA
		,ISNULL(B.DESVIO, 0) AS DESVIO
		,T.ATIVOS_TOTAL AS ATV_TOT
		,A.QTD_MES
		,QPF.LIMITE_SUPERIOR_PF
		,QPJ.LIMITE_SUPERIOR_PJ
	INTO #CLI
	FROM #MBOV A
	JOIN #MBOV_MEDIA B  WITH (INDEX(IX_MBOV_MEDIA)) ON B.CD_CLIENTE = A.CD_CLIENTE
	LEFT JOIN #CLIENTE C  WITH (INDEX(IX_CLIENTE)) ON C.CD_CLIENTE = A.CD_CLIENTE
	LEFT JOIN #CLIENTEPF PF WITH (INDEX(IX_PF)) ON PF.CD_CLIENTE = A.CD_CLIENTE
	LEFT JOIN #CLIENTEPJ PJ WITH (INDEX(IX_Pj)) ON PJ.CD_CLIENTE = A.CD_CLIENTE
	LEFT JOIN #TOTAL_ATIVOS2 T WITH (INDEX(IX_TOTAL_ATIVOS)) ON T.CD_CLIENTE = A.CD_CLIENTE
	LEFT JOIN #QUARTIL_PF QPF ON PF.CD_CLIENTE IS NOT NULL
	LEFT JOIN #QUARTIL_PJ QPJ ON PJ.CD_CLIENTE IS NOT NULL
	WHERE A.VOLUME > ISNULL(B.MEDIA, 0) + ISNULL(B.DESVIO, 0) * 3
		AND ((PF.CD_CLIENTE IS NOT NULL AND A.VOLUME > QPF.LIMITE_SUPERIOR_PF)
			OR (PJ.CD_CLIENTE IS NOT NULL AND A.VOLUME > QPJ.LIMITE_SUPERIOR_PJ))
		--AND NOT (DATEDIFF(MONTH, C.DT_CRIACAO, @DT_REF) IN (0, 1, 2))
		AND B.MEDIA >= 1




--delete em caso de reprocessamento.  
DELETE FROM ST_ALERT_MEDIA_BOVESPA_01 WHERE DATA = @DT_REF        

----insert do alerta final              
INSERT INTO ST_ALERT_MEDIA_BOVESPA_01 (DATA,CD_CLIENTE,VOLUME,MEDIA,DESVIO,ATV_TOT,QTD_MES)
---SELECT FINAL
SELECT 
     DATA
	,CD_CLIENTE
	,CAST(VOLUME AS FLOAT) VOLUME
	,CAST(MEDIA AS FLOAT) MEDIA
	,CAST(DESVIO AS FLOAT) DESVIO
	,ATV_TOT
	,QTD_MES 
FROM #CLI
ORDER BY CD_CLIENTE;
/******* fim do processo de carga do alerta **********/
-- ================================================
-- Marca DT_FIRA para registros carregados (fallback)
-- ================================================
DECLARE @__dt_fira_now DATETIME = GETDATE();
IF COL_LENGTH(N'dbo.ST_ALERT_MEDIA_BOVESPA', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE [dbo].ST_ALERT_MEDIA_BOVESPA
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL;
END

--passo 3
/***** limpa a tabela do banco para nao ficar sujeira ******/
DROP TABLE IF EXISTS ST_ALERT_MEDIA_BOVESPA_01_PADRAO