CREATE PROCEDURE [dbo].[PR_ALERTADETALHADOMUDANCAREPENTINA]
(
   @CD_ANO INT, @DS_MES VARCHAR(50), @CD_CLIENTE INT
)
--WITH ENCRYPTION
AS

----COALESCE COMENTADO, POIS JÁ É FEITO NA CARGA DO ALERTA
--declare @CD_ANO INT, @DS_MES VARCHAR(50), @CD_CLIENTE INT

--SET @CD_ANO = '2024'
--SET @DS_MES = 'MARÇO'
--SET @CD_CLIENTE = ''

BEGIN

IF @DS_MES = '01' BEGIN SET @DS_MES = 'JANEIRO' END
ELSE IF @DS_MES = '02' BEGIN SET @DS_MES = 'FEVEREIRO' END
ELSE IF @DS_MES = '03' BEGIN SET @DS_MES = 'MARÇO' END
ELSE IF @DS_MES = '04' BEGIN SET @DS_MES = 'ABRIL' END
ELSE IF @DS_MES = '05' BEGIN SET @DS_MES = 'MAIO' END
ELSE IF @DS_MES = '06' BEGIN SET @DS_MES = 'JUNHO' END
ELSE IF @DS_MES = '07' BEGIN SET @DS_MES = 'JULHO' END
ELSE IF @DS_MES = '08' BEGIN SET @DS_MES = 'AGOSTO' END
ELSE IF @DS_MES = '09' BEGIN SET @DS_MES = 'SETEMBRO' END
ELSE IF @DS_MES = '10' BEGIN SET @DS_MES = 'OUTUBRO' END
ELSE IF @DS_MES = '11' BEGIN SET @DS_MES = 'NOVEMBRO' END
ELSE IF @DS_MES = '12' BEGIN SET @DS_MES = 'DEZEMBRO' END

SET @CD_ANO = CAST(@CD_ANO AS INT)
SET @CD_CLIENTE = CAST(@CD_CLIENTE AS INT)

SELECT DISTINCT 
FORMAT(DATA,'d','pt-br')DATA
,CD_CLIENTE AS [CÓD. CLIENTE]
--,COALESCE( (SELECT DISTINCT CAST(o.CD_TP_MERCADO AS VARCHAR(MAX)) + ' | ' [text()] 
--			FROM ST_ALERT_MUDANCA_REPENTINA_01 AS O 
--			WHERE O.CD_CLIENTE = A.CD_CLIENTE AND 
--			O.data = A.data 
--			ORDER BY 1 
--			FOR XML PATH(''), TYPE).value('.[1]', 'VARCHAR(MAX)'), '') AS  MERCADO
,CD_TP_MERCADO AS  MERCADO
,COALESCE( (SELECT DISTINCT CAST(o.MERCADO_HIST_6M AS VARCHAR(MAX)) + ' | ' [text()] 
			FROM ST_ALERT_MUDANCA_REPENTINA_01 AS O 
			WHERE O.CD_CLIENTE = A.CD_CLIENTE AND 
			O.data = A.data 
			ORDER BY 1
			FOR XML PATH(''), TYPE).value('.[1]', 'VARCHAR(MAX)'), '') as [MERCADO HISTÓRICO 6 MESES]
 
FROM ST_ALERT_MUDANCA_REPENTINA_01 A
INNER JOIN ST_PERIODO C  ON DATA = DT_PERIODO  
--LEFT OUTER JOIN V_CLIENTE_TODOS D ON A.CD_CLIENTE = D.CD_CLIENTE  
WHERE CD_ANO = @CD_ANO AND DS_MES = @DS_MES  AND A.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN A.CD_CLIENTE ELSE @CD_CLIENTE END

END