CREATE PROCEDURE [dbo].[PR_SALDO_RELATORIO] @INICIO SMALLDATETIME, @FIM SMALLDATETIME, @CD_CLIENTE VARCHAR(160),@QTDPORPAGINA INT , @PAGINA INT
--WITH ENCRYPTION
AS
 
 --DECLARE  @PAGINA       INT = 1;

 --DECLARE @INICIO SMALLDATETIME, @FIM SMALLDATETIME, @CD_CLIENTE VARCHAR(160)
 --DECLARE @QTDPORPAGINA INT = 80000
 --SET @INICIO ='20251201'
 --SET @FIM ='20251231'
 --SET @CD_CLIENTE = ''--'312664'

 
 SELECT DISTINCT 
		FORMAT(DATA,'d','pt-br') "PERIODO",
		A.CD_CLIENTE [CÓD. CLIENTE],
		A.NM_CLIENTE "NOME DO CLIENTE",
		FORMAT(SUM(VL_DISPONIVEL),'f','pt-br')"SALDO EM CC"
		
FROM ST_SALDO A
LEFT OUTER JOIN V_CLIENTE_TODOS B
ON A.CD_CLIENTE = B.CD_CLIENTE
WHERE
		DATA >=@INICIO AND DATA <=@FIM
		AND A.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN A.CD_CLIENTE ELSE @CD_CLIENTE END
GROUP BY DATA ,A.CD_CLIENTE,A.NM_CLIENTE,B.IN_PESS_VINC

ORDER BY 1
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;