CREATE PROCEDURE [dbo].[PR_PATRIMONIO_HIST] @INICIO SMALLDATETIME, @CD_CLIENTE VARCHAR(160),@QTDPORPAGINA INT, @PAGINA INT
--WITH ENCRYPTION
AS
 
--DECLARE @PAGINA INT = 1;
--DECLARE @QTDPORPAGINA INT = 100000
--DECLARE  @INICIO SMALLDATETIME,@FIM SMALLDATETIME, @CD_CLIENTE VARCHAR(160)
--SET @INICIO ='20251231' 
--SET @CD_CLIENTE = '847'

--;WITH #V_CLIENTE_TODOS AS (
drop table if exists #V_CLIENTE_TODOS
SELECT DISTINCT CD_CLIENTE,NM_CLIENTE 
INTO #V_CLIENTE_TODOS
FROM V_CLIENTE_TODOS (NOLOCK)
--)

--, #PATCUST AS  (
drop table if exists #patcust
SELECT XX.CD_CLIENTE, isnull(CAST(SUM(VAL_BENS) AS NUMERIC(38,2)),0) PATRIMONIO
INTO #PATCUST
FROM ST_PATRIMONIO_LIQ  XX
WHERE DATA = @INICIO
 GROUP BY  XX.CD_CLIENTE
--)
  
CREATE NONCLUSTERED INDEX T1         
ON [DBO].[#PATCUST] ([CD_CLIENTE]) 
INCLUDE ([PATRIMONIO]) 
     
	
SELECT
 CONVERT(vARCHAR,DATA,103) AS DATA
,A.CD_CPFCGC AS [CPF/CNPJ]
,A.CD_CLIENTE AS [CÓD. DO CLIENTE]
,T.NM_CLIENTE AS [NOME DO CLIENTE]
,TIPO [PF/PJ]
,CD_GRUPO AS [GRUPO]
,CD_SFPSUBGRUPO AS [SUBGRUPO]
,DS_GRUPO AS [DESCRICAO GRUPO]
,DS_BEN AS [DESCRICAO BEM]
,FORMAT(isnull(CAST(VAL_BENS AS NUMERIC(38,2)),0),'f','pt-br') [BENS DECLARADO]
,FORMAT(isnull(CAST(VAL_RENDA_MENSAL AS NUMERIC(38,2)),0),'f','pt-br') AS [RENDA MENSAL]
,FORMAT(isnull(CAST(VAL_RENDA_ANUAL AS NUMERIC(38,2)),0),'f','pt-br') AS [RENDA ANUAL]
,FORMAT(isnull(CAST(VAL_SITU_PATRM AS NUMERIC(38,2)),0),'f','pt-br') AS [SITUCAO PATRIMONIAL]
,FORMAT(isnull(CAST(VAL_CAPTL_SCIAL AS NUMERIC(38,2)),0),'f','pt-br') AS [CAPITAL SOCIAL]
,FORMAT(isnull(CAST(VAL_CAPTL_GIRO  AS NUMERIC(38,2)),0),'f','pt-br') AS [CAPITAL DE GIRO]
,FORMAT(isnull(CAST(VAL_PATRM_LIQ AS NUMERIC(38,2)),0),'f','pt-br') AS [PATRIMONIO LIQUIDO]

,format(isnull(CAST(PATRIMONIO AS NUMERIC(38,2)),0),'f','pt-br') AS [SFP TOTAL ALERTA]


FROM ST_PATRIMONIO_LIQ A (NOLOCK)
INNER JOIN #V_CLIENTE_TODOS T ON A.CD_CLIENTE = T.CD_CLIENTE
LEFT JOIN #patcust C ON A.CD_CLIENTE = C.CD_CLIENTE
WHERE A.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'')='' THEN A.CD_CLIENTE ELSE @CD_CLIENTE END
AND A.DATA = @INICIO 
 
 
ORDER BY 2,1
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;