CREATE PROCEDURE [dbo].[FIRA_PR_CARGA_ALERT_301_TRANSFERENCIA_FINANCEIRA_01] @PREGAO SMALLDATETIME, @AUX INT
AS

 


/*************************************************************************************************
REGRA DO ALERTA:
Cliente que depositou a 90 dias e não fez nenhuma negociação e
nem qualquer movimentação em conta corrente.
*************************************************************************************************/


 --passo 1
/**********************************
inicio da etapa de verificação
aqui temos o script da base padrao
***********************************/
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ST_ALERT_TRANSFERENCIA_FINANCEIRA_01_PADRAO]') AND type in (N'U'))
CREATE TABLE [dbo].[ST_ALERT_TRANSFERENCIA_FINANCEIRA_01_PADRAO](
	[DATA] [date] NULL,
	[CD_CLIENTE] [int] NOT NULL,
	[TP_CLIENTE] [numeric](2, 0) NULL,
	[NM_CLIENTE] [varchar](400) NULL,
	[CD_CPFCGC] [varchar](20) NULL,
	[DT_CRIACAO] [datetime2](7) NULL,
	[DT_DEPOSITO] [date] NULL,
	[DIAS] [int] NULL,
	[DT_ULT_OPER] [datetime2](7) NULL,
	[DT_SALDO] [date] NULL,
	[SALDO_CC] [numeric](15, 2) NULL,
	[VALOR_DEPOSITO] [decimal](17, 2) NULL,
	[DT_ULT_MOVIMENTACAO] [date] NULL,
	[PATRIMONIO] [float] NULL,
	[DT_FIRA] DATETIME NULL
) ON [PRIMARY]
 

/***************************************************
inicio da comparação entre a tabela
da base padrao fira origem x tabela cliente destino
*****************************************************/
EXEC dbo.usp_sync_table_schema_add_alter_2012
  --@src_schema='dbo', @src_table='ST_ALERT_TRANSFERENCIA_FINANCEIRA_01_PADRAO',
  @schema_name='dbo', @base_table='ST_ALERT_TRANSFERENCIA_FINANCEIRA_01',
  @execute=1,
  @allow_drop=1, @apply_rename_map=1;

/******** fim da etapa de verificação ************/


/*********inicio da carga do alerta*******/
--DECLARE @PREGAO SMALLDATETIME, @AUX INT
--SET @PREGAO = '20260105'
--SET @AUX = (SELECT DAY(@PREGAO))
 
declare @dt_ini date = dateadd(month, datediff(month,0, dateadd(month,-1,@pregao)),0) -- 1 dia do mes atual
declare @dt_fim date = dateadd(month,1,@dt_ini) -- ultimo dia do mes atual
declare @dt_ini_6m date = dateadd(month, datediff(month,0, dateadd(month,-7,@pregao)),0) -- primeiro dia do 6 mes anterior ao mes atual
declare @dt_fim_6m date = @dt_ini -- 1 dia do mes atual
DECLARE @DT_REF DATE = DATEADD(DAY, - @AUX, @PREGAO);

--DEFINIÇÃO DOS VALORES ATRIBUIDO AS VARIAVEIS DE DATA

DECLARE @CD_ANOMES     INT
	  , @CD_ANOMES_INI INT
	  , @CD_ANOMES_FIM INT
	  , @DATA_MIN	   SMALLDATETIME
	  , @DATA_MAX	   SMALLDATETIME

SET @CD_ANOMES = (
			     SELECT MAX(CD_ANOMES) 
				   FROM ST_PERIODO 
				  WHERE DT_PERIODO =  DATEADD(DAY,-@AUX,@PREGAO)
				  )

DROP TABLE IF EXISTS #3MESES;

	   SELECT 
	 DISTINCT TOP 3 CD_ANOMES  
	     INTO #3MESES 
		 FROM ST_PERIODO 
		WHERE CD_ANOMES <= @CD_ANOMES 
	 ORDER BY CD_ANOMES DESC

SET @CD_ANOMES_INI = (
					 SELECT MIN(CD_ANOMES)
					   FROM #3MESES
					  )

SET @CD_ANOMES_FIM = (
					 SELECT MAX(CD_ANOMES)
					   FROM #3MESES
					  )

SET @DATA_MIN = (
				SELECT MIN(DT_PERIODO) 
				  FROM ST_PERIODO 
				 WHERE CD_ANOMES = @CD_ANOMES_INI
				  )

SET @DATA_MAX = (
				 SELECT MAX(DT_PERIODO) 
				   FROM ST_PERIODO 
				  WHERE CD_ANOMES = @CD_ANOMES_FIM
				  )

--------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------


--patrimonio
DROP TABLE IF EXISTS #PATCUST
SELECT XX.CD_CLIENTE, isnull(CAST(SUM(VAL_BENS) AS NUMERIC(38,2)),0) PATRIMONIO
INTO #PATCUST
FROM ST_PATRIMONIO_LIQ  XX
WHERE DATA = (SELECT MAX(DATA) FROM ST_PATRIMONIO_LIQ YY 
				WHERE DATA >= @dt_ini
				AND DATA < @dt_fim
				and DATEPART(WEEKDAY, DATA) NOT IN (7,1)
			  )
 GROUP BY  XX.CD_CLIENTE
 
CREATE NONCLUSTERED INDEX T1         
ON [DBO].[#PATCUST] ([CD_CLIENTE]) 
INCLUDE ([PATRIMONIO])    


/*ULTIMO DEPOSITO ANTES DA DATA MINIMA DOS 90 DIAS*/	
DROP TABLE IF EXISTS #ULT_DEPOSITO;
	   SELECT CD_CLIENTE 
			, MAX(DT_REFERENCIA) DT_REFERENCIA
			, SUM(VL_LANCAMENTO) SUM_VL_LANCAMENTO
			, 'SIM' DEPOSITO 
		 INTO #ULT_DEPOSITO
	     FROM ST_EXTRATO_CC 
	    WHERE DT_REFERENCIA < @DATA_MIN 
		  AND CD_HISTORICO IN (SELECT CD_PARAMETRO 
								 FROM ST_CLIENTE_PARAMETROS 
								WHERE DS_PARAMETRO = 'DEPOSITO')
	 GROUP BY  CD_CLIENTE
	
/*VERIFICA SE O CLIENTE MOVIMENTOU DEPOIS DO ULTIMO DEPOSITO ATÉ O ULTIMO DIA DO MES DE ALERTA

VERIFICAMOS SE HÁ MOVIMENTAÇÃO DENTRO DOS NOVENTA DIAS, DEPÓSITO, REMUNERAÇÃO (EMPRÉSTIMO) ,DIVIDENDO E RENDIMENTO NÃO SÃO CONSIDERADOS MOVIMENTAÇÕES.
ALÉM DE INCLUIR DEPOSITO E RETIRADA NA ST_CLIENTE_PARAMETROS É PRECISO INCLUIR OS CÓDIGOS REFERENTES A REMUNERAÇÃO, DIVIDENDO E RENDIMENTO.

DS_PARAMETRO
------------
DEPOSITO
RETIRADA
DEPOSITO
REMUNERACAO
RENDIMENTO
DIVIDENDO
*/
 DROP TABLE IF EXISTS #ULT_RETIRADA;		
		SELECT A.CD_CLIENTE 
			 , 'SIM' MOVIMENTACAO
		  INTO #ULT_RETIRADA
		  FROM ST_EXTRATO_CC A 
	INNER JOIN #ULT_DEPOSITO B 
			ON A.CD_CLIENTE = B.CD_CLIENTE 
		   
		 WHERE CD_HISTORICO NOT IN (SELECT CD_PARAMETRO 
									  FROM ST_CLIENTE_PARAMETROS 
									 WHERE DS_PARAMETRO IN ('DEPOSITO','DIVIDENDO','RENDIMENTO','REMUNERACAO'))	
		   AND A.DT_REFERENCIA >= B.DT_REFERENCIA
		   AND A.DT_REFERENCIA <= @DATA_MAX
		
		
/*CLIENTES CUJO O ULTIMO DEPOSITO NÃO HOUVE UMA MOVIMENTAÇÃO*/	

 DROP TABLE IF EXISTS #ULT_DEPOSITO_SEM_MOVIMENTACAO;

		SELECT A.CD_CLIENTE
			 , A.DEPOSITO 
			 , B.MOVIMENTACAO
			 , A.SUM_VL_LANCAMENTO
		  INTO #ULT_DEPOSITO_SEM_MOVIMENTACAO
		  FROM #ULT_DEPOSITO A 
	 LEFT JOIN #ULT_RETIRADA B 
		    ON A.CD_CLIENTE = B.CD_CLIENTE
		 WHERE B.MOVIMENTACAO IS NULL 

	
/*PEGA A ULTIMA OPERAÇÃO EM BOVESPA E BMF*/

 DROP TABLE IF EXISTS #ULTOPER;

		SELECT CD_CLIENTE
			 , MAX(ULT_BVSP) AS ULT_BVSP
			 , MAX(ULT_BMF)  AS ULT_BMF
		INTO #ULTOPER
		FROM (
					SELECT A.CD_CLIENTE
						 , MAX(DT_NEGOCIO) AS ULT_BVSP
						 , NULL ULT_BMF 
					FROM ST_CORRETAGEM_ORDEM  A
			  INNER JOIN #ULT_DEPOSITO_SEM_MOVIMENTACAO B 
					  ON A.CD_CLIENTE = B.CD_CLIENTE
				   WHERE DT_NEGOCIO <= @DATA_MAX
				GROUP BY A.CD_CLIENTE
		
				   UNION ALL
		
				  SELECT A.CD_CLIENTE
					   , NULL ULT_BVSP
					   , MAX(DT_NEGOCIO) AS ULT_BMF 
					FROM ST_BMF_NEGOCIOS_NC A
			  INNER JOIN #ULT_DEPOSITO_SEM_MOVIMENTACAO B 
					  ON A.CD_CLIENTE = B.CD_CLIENTE
				   WHERE DT_NEGOCIO <= @DATA_MAX
					 AND TP_NEGOCIO IN ('NORMAL','DAY TRADE','DAYTRADE')
				GROUP BY A.CD_CLIENTE
			)X
	 GROUP BY CD_CLIENTE 


/*CALCULA A QTD DE DIAS DO DEPOSITO ATÉ O ULTIMO DIA DOS 90 DIAS*/

 DROP TABLE IF EXISTS #QTD_DIAS;

		SELECT A.CD_CLIENTE,A.DEPOSITO,A.MOVIMENTACAO
			 , B.DT_REFERENCIA AS DT_ULT_DEPOSITO
			 , CASE WHEN C.ULT_BVSP > C.ULT_BMF THEN C.ULT_BVSP ELSE C.ULT_BMF END DT_ULT_OPER
			 , DATEDIFF(D,B.DT_REFERENCIA,@DATA_MAX) QTD_DIAS_DEPOSITO
			 , DATEDIFF(D,CASE WHEN C.ULT_BVSP > C.ULT_BMF THEN C.ULT_BVSP ELSE C.ULT_BMF END, @DATA_MAX ) QTD_DIAS_OPE
			 , A.SUM_VL_LANCAMENTO
		  INTO #QTD_DIAS
		  FROM #ULT_DEPOSITO_SEM_MOVIMENTACAO A
	 LEFT JOIN #ULT_DEPOSITO B 
			ON A.CD_CLIENTE = B.CD_CLIENTE
	 LEFT JOIN #ULTOPER C 
			ON A.CD_CLIENTE = C.CD_CLIENTE	


/*QUANDO QTD DE DIAS DE DEPOSITO FOR MAIOR QUE 90 E QTD DE DIAS OPERADOS  MAIOR OU IGUAL AO QTD DE DIAS DE DEPOSITO É ALERTADO*/

 DROP TABLE IF EXISTS #TRANSFERENCIA_01;

 		SELECT CD_CLIENTE
 			 , DEPOSITO
 			 , MOVIMENTACAO
 			 , DT_ULT_DEPOSITO
 			 , DT_ULT_OPER
 			 , QTD_DIAS_DEPOSITO
 			 , QTD_DIAS_OPE
 			 , SUM_VL_LANCAMENTO AS VALOR_DEPOSITO
 		  INTO #TRANSFERENCIA_01
 		  FROM #QTD_DIAS
 		 WHERE QTD_DIAS_DEPOSITO >= 90 
 		   AND QTD_DIAS_OPE >= QTD_DIAS_DEPOSITO




/*VERIFICA SE O SALDO FICOU NEGATIVO*/
DROP TABLE IF EXISTS #SALDO_NEGATIVO_AUX;
    SELECT A.CD_CLIENTE,
           A.VL_DISPONIVEL,
           DATA,
           ROW_NUMBER() OVER (PARTITION BY A.CD_CLIENTE ORDER BY DATA DESC) AS RN, -- Identifica o saldo mais recente
           MAX(CASE 
                   WHEN VL_DISPONIVEL < 0 THEN 1 
                   ELSE 0 
               END) OVER (PARTITION BY A.CD_CLIENTE) AS FLAG_NEGATIVO -- Verifica se houve saldo negativo
		  INTO #SALDO_NEGATIVO_AUX
		  FROM ST_SALDO A 
	INNER JOIN  #TRANSFERENCIA_01 B 
			ON A.CD_CLIENTE = B.CD_CLIENTE
		 WHERE DATA BETWEEN @DATA_MIN AND @DATA_MAX --and A.CD_CLIENTE = 956472

DROP TABLE IF EXISTS #SALDO_NEGATIVO;
   SELECT CD_CLIENTE,
      MAX(CASE 
               WHEN RN = 1 THEN VL_DISPONIVEL 
               ELSE NULL 
           END) AS SALDO_ULTIMO_DIA, -- Retorna o saldo do último dia
       MAX(FLAG_NEGATIVO) AS FLAG_NEGATIVO, -- Retorna a flag de saldo negativo
	   MAX(DATA)DATA
    INTO #SALDO_NEGATIVO
    FROM #SALDO_NEGATIVO_AUX
GROUP BY CD_CLIENTE;



		
/*NESSA QUERIE PEGAMOS A ULTIMA MOVIMENTAÇÃO DO CLIENTE ANTES DO DEPOSITO PARA AGREGAR INFORMAÇÃO AO ALERTA*/

 DROP TABLE IF EXISTS #ULT_MOVIMENTACAO ;

		SELECT A.CD_CLIENTE
			 , MAX(DT_REFERENCIA) DT_ULT_MOVIMENTACAO 
		INTO #ULT_MOVIMENTACAO
		FROM ST_EXTRATO_CC A
  INNER JOIN #TRANSFERENCIA_01 B 
		  ON A.CD_CLIENTE = B.CD_CLIENTE
		 AND A.DT_REFERENCIA < B.DT_ULT_DEPOSITO
	   WHERE CD_HISTORICO NOT IN (SELECT CD_PARAMETRO 
									FROM ST_CLIENTE_PARAMETROS 
								   WHERE DS_PARAMETRO IN ('DEPOSITO','DIVIDENDO','RENDIMENTO','REMUNERACAO'))
	GROUP BY A.CD_CLIENTE

/*RESULTADO ALERTA */

	DELETE FROM ST_ALERT_TRANSFERENCIA_FINANCEIRA_01 WHERE DATA = (@PREGAO - @AUX)
	
	INSERT INTO ST_ALERT_TRANSFERENCIA_FINANCEIRA_01 (DATA,CD_CLIENTE,TP_CLIENTE,NM_CLIENTE,CD_CPFCGC,DT_CRIACAO,DT_DEPOSITO,DIAS,DT_ULT_OPER,DT_SALDO,SALDO_CC,VALOR_DEPOSITO,DT_ULT_MOVIMENTACAO,PATRIMONIO)
	  	 SELECT CAST(@PREGAO - @AUX AS DATE) AS DATA
	  		  , A.CD_CLIENTE
	  		  , B.TP_CLIENTE
	  		  , B.NM_CLIENTE
	  		  , B.CD_CPFCGC
	  		  , B.DT_CRIACAO 
	 		  , A.DT_ULT_DEPOSITO   AS DT_DEPOSITO
	  		  , A.QTD_DIAS_DEPOSITO AS DIAS 
	 		  , A.DT_ULT_OPER
	  		  , D.DATA DT_SALDO 
	  		  , D.SALDO_ULTIMO_DIA SALDO_CC
	  		  , CAST(A.VALOR_DEPOSITO AS DECIMAL(17,2)) AS VALOR_DEPOSITO
	  		  , C.DT_ULT_MOVIMENTACAO
			  , ISNULL(PAT.PATRIMONIO,0) AS PATRIMONIO
	  	   FROM #TRANSFERENCIA_01 A 
	  LEFT JOIN V_CLIENTE_TODOS B 
	  	     ON A.CD_CLIENTE = B.CD_CLIENTE
	  LEFT JOIN #ULT_MOVIMENTACAO C 
	  	     ON A.CD_CLIENTE = C.CD_CLIENTE
	  LEFT JOIN #SALDO_NEGATIVO D
			 ON A.CD_CLIENTE = D.CD_CLIENTE
	  LEFT JOIN #PATCUST PAT ON A.CD_CLIENTE = PAT.CD_CLIENTE
/******* fim do processo de carga do alerta **********/
-- ================================================
-- Marca DT_FIRA para registros carregados (fallback)
-- ================================================
DECLARE @__dt_fira_now DATETIME = GETDATE();
IF COL_LENGTH(N'dbo.ST_ALERT_TRANSFERENCIA_FINANCEIRA_01', 'DT_FIRA') IS NOT NULL
BEGIN
    UPDATE [dbo].ST_ALERT_TRANSFERENCIA_FINANCEIRA_01
    SET DT_FIRA = @__dt_fira_now
    WHERE DT_FIRA IS NULL;
END

--passo 3
/***** limpa a tabela do banco para nao ficar sujeira ******/
DROP TABLE IF EXISTS ST_ALERT_TRANSFERENCIA_FINANCEIRA_01_PADRAO