CREATE PROCEDURE [dbo].[PR_ALERTADETALHADOINSIDERTRADINGBVSP02]
(
   @CD_ANO INT, @DS_MES VARCHAR(50), @CD_CLIENTE INT
)
--WITH ENCRYPTION
AS

--declare @CD_ANO INT, @DS_MES VARCHAR(50), @CD_CLIENTE INT
--set @cd_ano = '2023'
--set @DS_MES ='AGOSTO'
BEGIN

IF @DS_MES = '01' BEGIN SET @DS_MES = 'JANEIRO' END
ELSE IF @DS_MES = '02' BEGIN SET @DS_MES = 'FEVEREIRO' END
ELSE IF @DS_MES = '03' BEGIN SET @DS_MES = 'MARÇO' END
ELSE IF @DS_MES = '04' BEGIN SET @DS_MES = 'ABRIL' END
ELSE IF @DS_MES = '05' BEGIN SET @DS_MES = 'MAIO' END
ELSE IF @DS_MES = '06' BEGIN SET @DS_MES = 'JUNHO' END
ELSE IF @DS_MES = '07' BEGIN SET @DS_MES = 'JULHO' END
ELSE IF @DS_MES = '08' BEGIN SET @DS_MES = 'AGOSTO' END
ELSE IF @DS_MES = '09' BEGIN SET @DS_MES = 'SETEMBRO' END
ELSE IF @DS_MES = '10' BEGIN SET @DS_MES = 'OUTUBRO' END
ELSE IF @DS_MES = '11' BEGIN SET @DS_MES = 'NOVEMBRO' END
ELSE IF @DS_MES = '12' BEGIN SET @DS_MES = 'DEZEMBRO' END

SET @CD_ANO = CAST(@CD_ANO AS INT)
SET @CD_CLIENTE = CAST(@CD_CLIENTE AS INT)

  SELECT 
DISTINCT 
FORMAT(DATA,'d','pt-br') [DATA]
,CD_CLIENTE AS [CÓD. CLIENTE]
,CD_PAPEL AS ATIVO
,convert(varchar,DT_FATO,103) AS [DATA FATO RELEVANTE]
,FATO_RELEVANTE AS [FATO RELEVANTE]
,FORMAT(ISNULL(PRECO_MEDIO_COMPRA_PRE,0),'f','pt-br') AS [PRECO MÉD COMPRA PRÉ]
,FORMAT(ISNULL(PRECO_MEDIO_VENDA_PRE,0),'f','pt-br')  AS [PRECO MÉD VENDA PRÉ]
,FORMAT(ISNULL(PRECO_MEDIO_COMPRA_POS,0),'f','pt-br') AS [PRECO MÉD COMPRA POS]
,FORMAT(ISNULL(PRECO_MEDIO_VENDA_POS,0),'f','pt-br')  AS [PRECO MÉD VENDA POS]
,FORMAT(ISNULL(QTDE_VALORIZOU,0),'f','pt-br')		  AS [QTDE. VALORIZOU]
,FORMAT(ISNULL(QTDE_DESVALORIZOU,0),'f','pt-br')	  AS [QTDE. DESVALORIZOU]
,FORMAT(ISNULL(RF_VALORIZOU,0),'f','pt-br')			  AS [RF VALORIZOU]
,FORMAT(ISNULL(RF_DESVALORIZOU,0),'f','pt-br')		  AS [RF DESVALORIZOU]
,FORMAT(ISNULL(RESULTADO,0),'f','pt-br')			  AS [RESULTADO]
,FORMAT(ISNULL(AVG_INTERDAY_POS,0),'f','pt-br')		  AS [MÉD INTERDAY POS]
,FORMAT(ISNULL(AVG_INTRADAY_POS,0),'f','pt-br')		  AS [MÉD INTRADAY POS]
FROM ST_ALERT_INSIDER_TRADING_02 A
INNER JOIN ST_PERIODO C  ON DATA = DT_PERIODO  
--LEFT OUTER JOIN V_CLIENTE_TODOS D ON A.CD_CLIENTE = D.CD_CLIENTE  
WHERE CD_ANO = @CD_ANO AND DS_MES = @DS_MES  AND A.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN A.CD_CLIENTE ELSE @CD_CLIENTE END

END