CREATE PROCEDURE [dbo].[ATUALIZARSCORECADASTRO]
(
	@USUARIO INT, @MENORIDADE INT, @SEPTUAGENARIO INT, @PROFISSAORISCO INT, @VINCULADO INT
)
--WITH ENCRYPTION
AS

--DECLARE
--@USUARIO INT = 1, 
--@MENORIDADE INT = 5, 
--@SEPTUAGENARIO INT= 5, 
--@PROFISSAORISCO INT= 5, 
--@VINCULADO INT = 5


BEGIN
	
	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'Menores de 18 anos')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('Menores de 18 anos', 'CADASTRO', @MENORIDADE, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @MENORIDADE 
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'Menores de 18 anos'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'Maiores de 70 anos')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('Maiores de 70 anos', 'CADASTRO', @SEPTUAGENARIO, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @SEPTUAGENARIO
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'Maiores de 70 anos'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'Profissão de risco')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('Profissão de risco', 'CADASTRO', @PROFISSAORISCO, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @PROFISSAORISCO
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'Profissão de risco'
	END


	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'Vinculado')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('Vinculado', 'CADASTRO', @VINCULADO, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @VINCULADO
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'Vinculado'
	END
	

	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'Tempo de relacionamento')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('Tempo de relacionamento', 'CADASTRO', @VINCULADO, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @VINCULADO
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'Tempo de relacionamento'
	END
	

	IF NOT EXISTS (SELECT * FROM PORTALCONFIGSCORE WHERE IDUSUARIO = @USUARIO AND ITEM = 'Canal de distribuição')
	BEGIN
    INSERT INTO PORTALCONFIGSCORE (Item,Tipo,Peso,IdUsuario)
    VALUES('Canal de distribuição', 'CADASTRO', @VINCULADO, @USUARIO)
	END
	ELSE
	BEGIN
    UPDATE PORTALCONFIGSCORE 
	SET PESO = @VINCULADO
	WHERE 
	IDUSUARIO = @USUARIO AND
	ITEM = 'Canal de distribuição'
	END
	
END