CREATE PROCEDURE [dbo].[PR_ALERTADETALHADOPATRIMONIOCUSTODIA]
(
   @CD_ANO INT, @DS_MES VARCHAR(50), @CD_CLIENTE INT
)
--WITH ENCRYPTION
AS

--declare @CD_ANO INT, @DS_MES VARCHAR(50), @CD_CLIENTE INT
--set @CD_ANO = '2023'
--set @DS_MES ='DEZEMBRO'
--SET @CD_CLIENTE = '752238'

BEGIN

IF @DS_MES = '01' BEGIN SET @DS_MES = 'JANEIRO' END
ELSE IF @DS_MES = '02' BEGIN SET @DS_MES = 'FEVEREIRO' END
ELSE IF @DS_MES = '03' BEGIN SET @DS_MES = 'MARÇO' END
ELSE IF @DS_MES = '04' BEGIN SET @DS_MES = 'ABRIL' END
ELSE IF @DS_MES = '05' BEGIN SET @DS_MES = 'MAIO' END
ELSE IF @DS_MES = '06' BEGIN SET @DS_MES = 'JUNHO' END
ELSE IF @DS_MES = '07' BEGIN SET @DS_MES = 'JULHO' END
ELSE IF @DS_MES = '08' BEGIN SET @DS_MES = 'AGOSTO' END
ELSE IF @DS_MES = '09' BEGIN SET @DS_MES = 'SETEMBRO' END
ELSE IF @DS_MES = '10' BEGIN SET @DS_MES = 'OUTUBRO' END
ELSE IF @DS_MES = '11' BEGIN SET @DS_MES = 'NOVEMBRO' END
ELSE IF @DS_MES = '12' BEGIN SET @DS_MES = 'DEZEMBRO' END

SET @CD_ANO = CAST(@CD_ANO AS INT)
SET @CD_CLIENTE = CAST(@CD_CLIENTE AS INT)

;with #V_CLIENTE_TODOS as  (
select distinct cd_cliente,nm_Cliente,cd_cpfcgc, tipo from v_cliente_todos
)

SELECT DISTINCT
 CONVERT(VARCHAR,DATA,103) AS [DATA]
,CONVERT(VARCHAR,DT_CUSTODIA,103) AS [DATA CUSTÓDIA]
,a.CD_CLIENTE AS [CÓD. CLIENTE]
,D.NM_CLIENTE as [NOME DO CLIENTE]
,D.CD_CPFCGC AS [CPF_CNPJ]
,D.TIPO AS [PF_PJ]
,FORMAT(POSICAO_CC,'f','pt-br') AS [SALDO CC]
,FORMAT(POSICAO_BOVESPA,'f','pt-br') AS [ACOES BVSP]
,FORMAT(POSICAO_BMF,'f','pt-br') AS [ACOES BMF]
,FORMAT(TESOURO,'f','pt-br') AS TESOURO
,FORMAT(RENDA_FIXA,'f','pt-br') AS RENDA_FIXA
,FORMAT(FUNDOS,'f','pt-br') AS FUNDOS
,FORMAT(CARTEIRA,'f','pt-br') AS [CARTEIRA TOTAL] 
,FORMAT(PATRIMONIO,'f','pt-br') PATRIMONIO
,DS_NATUREZA_BVSP AS [OPEROU BVSP]
,DS_NATUREZA_BMF AS [OPEROU BMF]

FROM ST_ALERT_PATRIMONIO_CUSTODIA A
INNER JOIN ST_PERIODO C  ON DATA = DT_PERIODO  
LEFT OUTER JOIN #V_CLIENTE_TODOS D ON A.CD_CLIENTE = D.CD_CLIENTE  
WHERE CD_ANO = @CD_ANO AND DS_MES = @DS_MES  AND A.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN A.CD_CLIENTE ELSE @CD_CLIENTE END

END