CREATE PROCEDURE [dbo].[PR_MEDIA_OPERACOES_ATIVO_BMF] @ANOMES INT, @CD_CLIENTE INT , @QTDPORPAGINA INT, @PAGINA INT	,@ATIVO VARCHAR(60)
WITH RECOMPILE
AS 	

--DECLARE @PAGINA  INT 
--DECLARE @QTDPORPAGINA INT 	
--DECLARE @ANOMES INT
--DECLARE @CD_CLIENTE INT	
--DECLARE @ATIVO VARCHAR(60)


--SET @ANOMES =202512	
--SET @CD_CLIENTE='10'	
--SET @ATIVO = ''

DECLARE @ANOMES_INI SMALLDATETIME
DECLARE @ANOMES_FIM SMALLDATETIME

SET @ANOMES_INI = (SELECT TOP 1 EOMONTH(DT_PERIODO,-7) FROM ST_PERIODO WHERE CD_ANOMES = @ANOMES)
SET @ANOMES_FIM = (SELECT TOP 1 EOMONTH(DT_PERIODO,-1) FROM ST_PERIODO WHERE CD_ANOMES = @ANOMES)

		

		
--------VOL MES ATUAL------------
;WITH  #T1  AS (
SELECT 		
X.CD_ANOMES,		
F.CD_CLIENTE,		
CONCAT(F.CD_COMMOD,ISNULL(F.CD_SERIE,'')) ATIVO,
SUM(ISNULL((VL_VALOPE),0)) VOL_MES_ATUAL,
SUM(QT_QTDDET) QTD_MES		
FROM 		
ST_BMF_NEGOCIOS_NC F,		
st_periodo X		
WHERE 		
F.DT_NEGOCIO = X.DT_PERIODO AND		
X.CD_ANOMES = @ANOMES AND		
TP_NEGOCIO IN ('NORMAL','DAY TRADE','DAYTRADE')		
GROUP BY X.CD_ANOMES,F.CD_CLIENTE,CONCAT(F.CD_COMMOD,ISNULL(F.CD_SERIE,''))	),	
		
			
	
--------------MEDIA E DESVIO 6 MESES-----------------	
 #T4 AS(
SELECT 
CD_CLIENTE,	 ATIVO,
AVG(VOL_MES_ATUAL)VOL_MED_6_MESES,
STDEV(VOL_MES_ATUAL)VOL_DESV_6_MESES,
AVG(TOTAL) QTD_MED_6MESES,
STDEV(TOTAL)QTD_DESV_6MESES
FROM (
	SELECT 		
	F.CD_CLIENTE, 		
	CONCAT(F.CD_COMMOD,ISNULL(F.CD_SERIE,''))ATIVO,
	SUM(ISNULL(VL_VALOPE,0)) VOL_MES_ATUAL,
	sum(QT_QTDDET) TOTAL	
	FROM 		
	ST_BMF_NEGOCIOS_NC F		
	WHERE 		
	DT_NEGOCIO > @ANOMES_INI AND
	DT_NEGOCIO <= @ANOMES_FIM AND
	F.TP_NEGOCIO IN ('NORMAL', 'DAY TRADE','DAYTRADE') AND
	F.CD_CLIENTE= CASE WHEN ISNULL(@CD_CLIENTE,'') = '' THEN F.CD_CLIENTE ELSE CAST(@CD_CLIENTE AS INT) END		
	GROUP BY F.CD_CLIENTE,CONCAT(F.CD_COMMOD,ISNULL(F.CD_SERIE,'')) 
	)X	
GROUP BY CD_CLIENTE,ATIVO)
		  
				
		
		
--------------SOMA TUDO--------------		
SELECT DISTINCT		
A.CD_ANOMES [ANO MÊS],		
A.CD_CLIENTE [CÓD. CLIENTE],		
V.NM_CLIENTE [NOME DO CLIENTE],		
A.ATIVO AS [COMMOD],
FORMAT(ISNULL(SUM(A.QTD_MES),0),'#.#','PT-BR') [QTD. CONTRATO MÊS],
FORMAT(ISNULL(SUM(A.VOL_MES_ATUAL),0),'f','pt-br') [VALOR AJUSTE MÊS],	
FORMAT(ISNULL(SUM(D.VOL_MED_6_MESES),0),'f','pt-br') [MÉDIA AJUSTE 6M],
FORMAT(ISNULL(SUM(D.VOL_DESV_6_MESES),0),'f','pt-br')[DESVIO AJUSTE 6M],
FORMAT(ISNULL(ISNULL(SUM(A.VOL_MES_ATUAL),0) / NULLIF(SUM(D.VOL_MED_6_MESES),0),0),'P','PT-BR') [PERC. AJUSTE MÊS],
FORMAT(ISNULL(NULLIF(SUM(D.QTD_MED_6MESES), ''), 0), '#.#', 'PT-BR') AS [MÉDIA QTD. CONTRATO 6M],
FORMAT(ISNULL(NULLIF(SUM(D.QTD_DESV_6MESES), ''), 0), 'f', 'PT-BR') AS [DESVIO QTD. CONTRATO 6M],		
FORMAT(ISNULL(ISNULL(CAST(SUM(A.QTD_MES) AS FLOAT),0) / NULLIF(CAST(SUM(D.QTD_MED_6MESES) AS FLOAT),0),0),'P','PT-BR') [PERC. QTD. CONTRATO MÊS],
		
CASE WHEN 	ISNULL(SUM(A.VOL_MES_ATUAL),0) > SUM(D.VOL_MED_6_MESES) + (ISNULL(SUM(D.VOL_DESV_6_MESES),0)*3) THEN 'SIM' ELSE 'NÃO' END [CAI ALERTA]
		
FROM #T1 A 		
LEFT OUTER JOIN #T4 D ON A.CD_CLIENTE = D.CD_CLIENTE AND A.ATIVO = D.ATIVO
LEFT OUTER JOIN (SELECT DISTINCT CD_CLIENTE,NM_CLIENTE FROM V_CLIENTE_TODOS) V ON A.CD_CLIENTE = V.CD_CLIENTE		
		
WHERE 		
    A.CD_ANOMES =  (CASE WHEN ISNULL(@ANOMES,'') = '' THEN A.CD_ANOMES ELSE CONVERT(INT,@ANOMES) END)		
AND A.CD_CLIENTE = (CASE WHEN ISNULL(@CD_CLIENTE,'')='' THEN A.CD_CLIENTE ELSE CONVERT(INT,@CD_CLIENTE) END)	
AND A.ATIVO = (CASE WHEN ISNULL(@ATIVO,'')='' THEN A.ATIVO ELSE CONVERT(VARCHAR,@ATIVO) END)	

GROUP BY 
A.CD_ANOMES,A.CD_CLIENTE,V.NM_CLIENTE,A.ATIVO

ORDER BY 1
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;