CREATE PROCEDURE [dbo].[PR_OBTERCOLUNAS]
(
	@PROCEDURE NVARCHAR(MAX)
)
--WITH ENCRYPTION
AS
BEGIN
    SET FMTONLY OFF;
    SET NOCOUNT ON;
    EXEC SP_DESCRIBE_FIRST_RESULT_SET @PROCEDURE
END