CREATE PROCEDURE [dbo].[PR_EXTRATO_CC]		
(		
		
	@INICIO SMALLDATETIME,		
	@FIM SMALLDATETIME	,
	@CD_CLIENTE VARCHAR(160) ,
	@QTDPORPAGINA INT, @PAGINA INT
)		
--WITH ENCRYPTION
AS		

--DECLARE @PAGINA        INT = 1;
--	DECLARE @QTDPORPAGINA INT = 5
--	DECLARE @CD_CLIENTE VARCHAR(160)  
--	DECLARE @INICIO SMALLDATETIME 
--	DECLARE @FIM SMALLDATETIME 

--    SET @CD_CLIENTE  = '74'
--	SET @INICIO ='20210901'	
--	SET @FIM = '20210910'
	

	SELECT  
	   [DT_REFERENCIA] AS [REFERÊNCIA]
      ,[DT_LIQUIDACAO] AS [DATA DE LIQUIDAÇÃO]
      ,[NM_CLIENTE] AS [NOME DO CLIENTE] 
      ,[CD_CLIENTE]
      ,[DS_LANCAMENTO] AS [DESCRIÇÃO]
      ,[TOTAL]
      ,[SALDO_CC]
      ,[SALDO_ANT]
      ,[SALDO_CC_FINAL]
      ,[CD_HISTORICO]
      ,[DEBCRED]
	FROM		
	(		
 		SELECT 		
			'' DT_REFERENCIA,		
			'' DT_LIQUIDACAO,		
			'' NM_CLIENTE,		
			NULL CD_CLIENTE,		
			CASE WHEN SUM(CAST(VL_LANCAMENTO AS FLOAT)) > 0 THEN 'A CRÉDITO' ELSE 'A DÉBITO' END DS_LANCAMENTO,		
			FORMAT(SUM(CAST(VL_LANCAMENTO AS FLOAT)),'f','pt-br') TOTAL,		
			NULL SALDO_CC,		
			NULL SALDO_ANT,		
			NULL SALDO_CC_FINAL,		
			NULL CD_HISTORICO,
			CASE WHEN SUM(CAST(VL_LANCAMENTO AS FLOAT)) < 0 THEN 'D' ELSE 'C' END DEBCRED
			
		FROM		
			ST_EXTRATO_CC B 		
		WHERE		
			B.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'')='' THEN B.CD_CLIENTE ELSE @CD_CLIENTE END
  			AND B.DT_REFERENCIA >= @INICIO		
			AND B.DT_REFERENCIA <= @FIM		
 		
		UNION 		ALL
		
		SELECT 		
			FORMAT(DT_REFERENCIA,'d','pt-br')DT_REFERENCIA,		
			FORMAT(DT_LIQUIDACAO,'d','pt-br')DT_LIQUIDACAO,		
			B.NM_CLIENTE NM_CLIENTE,		
			B.CD_CLIENTE CD_CLIENTE,		
			B.DS_LANCAMENTO DS_LANCAMENTO,		
			FORMAT(CAST(VL_LANCAMENTO AS FLOAT),'f','pt-br') VL_LANCAMENTO_TOTAL_DIA,		
			FORMAT(ISNULL((SELECT SUM(CAST(X.VL_DISPONIVEL AS FLOAT)) FROM ST_SALDO X		
			WHERE X.CD_CLIENTE = B.CD_CLIENTE		
			AND X.DATA = B.DT_REFERENCIA),0),'f','pt-br') SALDO_CC,		
			
			FORMAT(ISNULL((SELECT SUM(CAST(X.VL_DISPONIVEL AS FLOAT)) FROM ST_SALDO X		
			WHERE X.CD_CLIENTE = B.CD_CLIENTE		
			AND X.DATA = @INICIO-1),0),'f','pt-br') SALDO_ANT,		
			
			FORMAT(ISNULL((SELECT MAX(CAST(X.VL_DISPONIVEL AS FLOAT)) FROM ST_SALDO X		
			WHERE X.CD_CLIENTE = B.CD_CLIENTE		
			AND X.DATA = @FIM),0),'f','pt-br') SALDO_CC_FINAL,		
			CD_HISTORICO,
			CASE WHEN (CAST(VL_LANCAMENTO AS FLOAT)) < 0 THEN 'D' ELSE 'C' END DEBCRED
		FROM		
			ST_EXTRATO_CC B 		
		WHERE		
			B.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'')='' THEN B.CD_CLIENTE ELSE @CD_CLIENTE END
  			AND B.DT_REFERENCIA >= @INICIO		
			AND B.DT_REFERENCIA <= @FIM		
		
	 )X		
		
  		
		
ORDER BY ROW_NUMBER() OVER (ORDER BY DT_REFERENCIA DESC)		
		
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;

		
 /*		
SELECT 		
	CONVERT(VARCHAR,DT_LIQUIDACAO,103)DT_LIQUIDACAO,		
	CONVERT(VARCHAR,DT_REFERENCIA,103)DT_REFERENCIA,		
	B.NM_CLIENTE NM_CLIENTE,		
	B.CD_CLIENTE CD_CLIENTE,		
		
	B.DS_LANCAMENTO DS_LANCAMENTO,		
	CAST(VL_LANCAMENTO AS FLOAT) VL_LANCAMENTO_TOTAL_DIA,		
	--D.SALDO_CC SALDO_CC,		
	ISNULL((SELECT SUM(CAST(X.VL_DISPONIVEL AS FLOAT)) FROM ST_SALDO X		
	WHERE X.CD_CLIENTE = B.CD_CLIENTE		
	AND X.DATA = B.DT_REFERENCIA),0)SALDO_CC,		
			
	ISNULL((SELECT SUM(CAST(X.VL_DISPONIVEL AS FLOAT)) FROM ST_SALDO X		
	WHERE X.CD_CLIENTE = B.CD_CLIENTE		
	AND X.DATA = @INICIO-1),0)SALDO_ANT,		
			
	ISNULL((SELECT MAX(CAST(X.VL_DISPONIVEL AS FLOAT)) FROM ST_SALDO X		
	WHERE X.CD_CLIENTE = B.CD_CLIENTE		
	AND X.DATA = @FIM),0)SALDO_CC_FINAL,		
			
	CD_HISTORICO		
FROM		
	ST_EXTRATO_CC B 		
WHERE		
	B.CD_CLIENTE = CASE WHEN ISNULL(@CD_CLIENTE,'')='' THEN B.CD_CLIENTE ELSE @CD_CLIENTE END AND		
  	B.DT_REFERENCIA >= @INICIO		
	AND B.DT_REFERENCIA <= @FIM		
		
ORDER BY DT_REFERENCIA--, NR_LANCAMENTO		
		
*/		
---------------------------------	0JP