CREATE TABLE [dbo].[TESTE] (
    [ANALISE] varchar(8) NOT NULL,
    [Referencia] varchar(42) NULL,
    [Cód. Cliente] int NULL,
    [NOME DO CLIENTE] nvarchar(160) NULL,
    [NACIONALIDADE] varchar(160) NULL,
    [CPF/CNPJ] varchar(20) NULL,
    [PF / PJ] varchar(2) NULL,
    [IDADE] int NULL,
    [INVESTIDOR] int NULL,
    [DATA DE CRIAÇÃO] datetime2(7) NULL,
    [FRONTEIRA] varchar(3) NOT NULL,
    [PEP SINACOR] nvarchar(160) NULL,
    [PESSOA VINCULADA] nvarchar(160) NULL,
    [INR] varchar(13) NULL,
    [ASSESSOR] varchar(160) NULL,
    [PROFISSÃO / SEGMENTO DE ATUAÇÃO] varchar(160) NULL,
    [PROFISSÃO DE RISCO] varchar(160) NULL,
    [SCORE RISCO] varchar(5) NOT NULL,
    [RISCO ABR] varchar(5) NULL,
    [Ativo Restrito] nvarchar(4000) NULL,
    [Atualização Cadastral] nvarchar(4000) NULL,
    [Churning] nvarchar(4000) NULL,
    [Insider Trading] nvarchar(4000) NULL,
    [Lista Atenção] nvarchar(4000) NULL,
    [Média Oper. Bmf] nvarchar(4000) NULL,
    [Média Oper. Bvsp] nvarchar(4000) NULL,
    [Money Pass Corretora Bmf] nvarchar(4000) NULL,
    [Money Pass Corretora Bvsp] nvarchar(4000) NULL,
    [Mudança Repentina] nvarchar(4000) NULL,
    [OMC Bmf] nvarchar(4000) NULL,
    [Omc Bvsp] nvarchar(4000) NULL,
    [Omg Bvsp] nvarchar(4000) NULL,
    [Patrimônio x Custódia] nvarchar(4000) NULL,
    [Patrimônio x Mov Cc] nvarchar(4000) NULL,
    [Patrimônio x Netting] nvarchar(4000) NULL,
    [Patrimônio x Transf. Custodia] nvarchar(4000) NULL,
    [Procurador] nvarchar(4000) NULL,
    [Transf. Financeira 01] nvarchar(4000) NULL,
    [Transf. Financeira 02] nvarchar(4000) NULL,
    [Vinculado ao Emissor] nvarchar(4000) NULL,
    [TOTAL] int NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);