CREATE TABLE [dbo].[ST_ALERT_PATRIMONIO_MOVIMENTO] (
    [DATA] date NULL,
    [CD_CLIENTE] int NOT NULL,
    [VOLUME_CC] numeric(38,2) NULL,
    [PATRIMONIO] float NOT NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_ALERT_PATRIMONIO_MOVIMENTO] ON [dbo].[ST_ALERT_PATRIMONIO_MOVIMENTO] ([CD_CLIENTE], [DATA]);

CREATE INDEX [ID002_ST_ALERT_PATRIMONIO_MOVIMENTO] ON [dbo].[ST_ALERT_PATRIMONIO_MOVIMENTO] ([DATA]);