CREATE TABLE [dbo].[ST_ALERT_TRANSFERENCIA_FINANCEIRA_01] (
    [DATA] date NULL,
    [CD_CLIENTE] int NOT NULL,
    [TP_CLIENTE] numeric(2,0) NULL,
    [NM_CLIENTE] varchar(400) NULL,
    [CD_CPFCGC] varchar(20) NULL,
    [DT_CRIACAO] datetime2(7) NULL,
    [DT_DEPOSITO] date NULL,
    [DIAS] int NULL,
    [DT_ULT_OPER] datetime2(7) NULL,
    [DT_SALDO] date NULL,
    [SALDO_CC] numeric(15,2) NULL,
    [VALOR_DEPOSITO] decimal(17,2) NULL,
    [DT_ULT_MOVIMENTACAO] date NULL,
    [PATRIMONIO] float NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_ALERT_TRANSFERENCIA_FINANCEIRA_01] ON [dbo].[ST_ALERT_TRANSFERENCIA_FINANCEIRA_01] ([CD_CLIENTE], [DATA]);

CREATE INDEX [ID002_ST_ALERT_TRANSFERENCIA_FINANCEIRA_01] ON [dbo].[ST_ALERT_TRANSFERENCIA_FINANCEIRA_01] ([DATA]);