CREATE TABLE [dbo].[ST_ALERT_MEDIA_BOVESPA_01] (
    [DATA] date NULL,
    [CD_CLIENTE] int NOT NULL,
    [VOLUME] float NULL,
    [MEDIA] float NULL,
    [DESVIO] float NULL,
    [ATV_TOT] varchar(MAX) NULL,
    [QTD_MES] float NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_ALERT_MEDIA_BOVESPA_01] ON [dbo].[ST_ALERT_MEDIA_BOVESPA_01] ([CD_CLIENTE], [DATA]);

CREATE INDEX [ID002_ST_ALERT_MEDIA_BOVESPA_01] ON [dbo].[ST_ALERT_MEDIA_BOVESPA_01] ([DATA]);