CREATE TABLE [dbo].[ST_ALERT_AML_CORRETORA] (
    [DATA] date NULL,
    [CD_CLIENTE] int NOT NULL,
    [CD_CORRET_COMPRA] int NOT NULL,
    [NM_CORRET_COMPRA] varchar(100) NULL,
    [RESULTADO] float NULL,
    [MEDIA] float NOT NULL,
    [DESVIO] float NOT NULL,
    [CD_PAPEL] nvarchar(MAX) NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_ALERT_AML_CORRETORA] ON [dbo].[ST_ALERT_AML_CORRETORA] ([CD_CLIENTE], [DATA]);

CREATE INDEX [ID002_ST_ALERT_AML_CORRETORA] ON [dbo].[ST_ALERT_AML_CORRETORA] ([DATA]);