CREATE TABLE [dbo].[ST_ALERT_AML_CORRETORA_BMF] (
    [DATA] date NULL,
    [CD_CLIENTE] int NOT NULL,
    [CD_CORRET] int NULL,
    [NM_CORRET] varchar(400) NULL,
    [RESULTADO] float NULL,
    [MEDIA] float NOT NULL,
    [DESVIO] float NOT NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_ALERT_AML_CORRETORA_BMF] ON [dbo].[ST_ALERT_AML_CORRETORA_BMF] ([CD_CLIENTE], [DATA]);

CREATE INDEX [ID002_ST_ALERT_AML_CORRETORA_BMF] ON [dbo].[ST_ALERT_AML_CORRETORA_BMF] ([DATA]);