CREATE TABLE [dbo].[ST_ALERT_TRANSFERENCIA_FINANCEIRA_02] (
    [DATA] date NULL,
    [CD_CLIENTE] int NOT NULL,
    [TP_CLIENTE] varchar(2) NULL,
    [NM_CLIENTE] varchar(400) NULL,
    [CD_CPFCGC] varchar(20) NULL,
    [DT_CRIACAO] datetime2(7) NULL,
    [DT_DEPOSITO] smalldatetime NULL,
    [DT_RETIRADA] smalldatetime NULL,
    [TOTAL] float NULL,
    [PATRIMONIO] float NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_ALERT_TRANSFERENCIA_FINANCEIRA_02] ON [dbo].[ST_ALERT_TRANSFERENCIA_FINANCEIRA_02] ([CD_CLIENTE], [DATA]);

CREATE INDEX [ID002_ST_ALERT_TRANSFERENCIA_FINANCEIRA_02] ON [dbo].[ST_ALERT_TRANSFERENCIA_FINANCEIRA_02] ([DATA]);