CREATE TABLE [dbo].[ST_DAYTRADE_DETALHE_BMF] (
    [CD_CLIENTE] int NOT NULL,
    [QT_QTDDET] float NULL,
    [PR_NEGOCIO] float NULL,
    [VL_VALOPE] float NULL,
    [DT_DATMOV] datetime NULL,
    [CD_COMMOD] char(3) NULL,
    [CD_SERIE] char(4) NULL,
    [NR_NEGOCIO] numeric(12,0) NULL,
    [CD_NATOPE] varchar(1) NULL,
    [CD_CLIENTE_COMPROU_DE] int NULL,
    [CD_CONTRAPARTE_COMPROU] int NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_DAYTRADE_DETALHE_BMF] ON [dbo].[ST_DAYTRADE_DETALHE_BMF] ([DT_DATMOV]);

CREATE INDEX [ID002_ST_DAYTRADE_DETALHE_BMF] ON [dbo].[ST_DAYTRADE_DETALHE_BMF] ([DT_DATMOV]);