CREATE TABLE [dbo].[PosTrade_Equities_IB_PF] (
    [Trade_Date] date NULL,
    [Trade_ID] int NULL,
    [Client_Account_Code] nvarchar(50) NULL,
    [Executing_Broker_Code] nvarchar(50) NULL,
    [Buy_Sell] nvarchar(10) NULL,
    [Market_Type] nvarchar(10) NULL,
    [Trade_Type] nvarchar(10) NULL,
    [Exercise_Type] nvarchar(50) NULL,
    [Ticker] nvarchar(50) NULL,
    [Qtd] int NULL,
    [ISIN] nvarchar(30) NULL,
    [Settlement_Date] date NULL,
    [Price] decimal(19,6) NULL,
    [Trade_Amount] decimal(19,6) NULL,
    [Broker_Fee] decimal(19,6) NULL,
    [Taxa_de_Liquidacao] decimal(19,6) NULL,
    [Taxa_de_Registro_Clearing] decimal(19,6) NULL,
    [Exchange_Fee] decimal(19,6) NULL,
    [Net_Settlement_Amount] decimal(19,6) NULL,
    [Horario_Trade] time(7) NULL,
    [Numero_do_negocio] int NULL,
    [Codigo_do_Operador] nvarchar(50) NULL,
    [Nome_do_Operador] nvarchar(200) NULL,
    [Tamanho_do_lote_do_ativo] int NULL,
    [After_market] nvarchar(10) NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);