CREATE TABLE [dbo].[ST_ALERT_PATRIMONIO_CUSTODIA] (
    [DATA] date NULL,
    [DT_CUSTODIA] datetime NULL,
    [CD_CLIENTE] int NOT NULL,
    [POSICAO_BOVESPA] float NULL,
    [POSICAO_BMF] float NULL,
    [POSICAO_CC] float NULL,
    [PATRIMONIO] float NULL,
    [DS_NATUREZA_BVSP] varchar(12) NOT NULL,
    [DS_NATUREZA_BMF] varchar(12) NOT NULL,
    [TESOURO] float NULL,
    [RENDA_FIXA] float NULL,
    [FUNDOS] float NULL,
    [CARTEIRA] float NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_ALERT_PATRIMONIO_CUSTODIA] ON [dbo].[ST_ALERT_PATRIMONIO_CUSTODIA] ([CD_CLIENTE], [DATA]);

CREATE INDEX [ID002_ST_ALERT_PATRIMONIO_CUSTODIA] ON [dbo].[ST_ALERT_PATRIMONIO_CUSTODIA] ([DATA]);