CREATE TABLE [dbo].[RelatorioGeralKYCRFBPJ] (
    [id] int IDENTITY(1,1) NOT NULL,
    [abertura] nvarchar(MAX) NULL,
    [atividade_principal] nvarchar(MAX) NULL,
    [atividades_secundarias] nvarchar(MAX) NULL,
    [bairro] nvarchar(MAX) NULL,
    [capital_social] nvarchar(MAX) NULL,
    [cep] nvarchar(MAX) NULL,
    [cnpj] nvarchar(MAX) NULL,
    [cnpjs_do_grupo] nvarchar(MAX) NULL,
    [code] nvarchar(MAX) NULL,
    [complemento] nvarchar(MAX) NULL,
    [data_situacao] nvarchar(MAX) NULL,
    [data_situacao_especial] nvarchar(MAX) NULL,
    [efr] nvarchar(MAX) NULL,
    [email] nvarchar(MAX) NULL,
    [extra] nvarchar(MAX) NULL,
    [fantasia] nvarchar(MAX) NULL,
    [ibge] nvarchar(MAX) NULL,
    [inscricao_municipal] nvarchar(MAX) NULL,
    [logradouro] nvarchar(MAX) NULL,
    [message] nvarchar(MAX) NULL,
    [motivo_situacao] nvarchar(MAX) NULL,
    [municipio] nvarchar(MAX) NULL,
    [natureza_juridica] nvarchar(MAX) NULL,
    [nome] nvarchar(MAX) NULL,
    [numero] nvarchar(MAX) NULL,
    [porte] nvarchar(MAX) NULL,
    [qsa] nvarchar(MAX) NULL,
    [sigla_natureza_juridica] nvarchar(MAX) NULL,
    [situacao] nvarchar(MAX) NULL,
    [situacao_especial] nvarchar(MAX) NULL,
    [status] nvarchar(MAX) NULL,
    [telefone] nvarchar(MAX) NULL,
    [tipo] nvarchar(MAX) NULL,
    [tipo_logradouro] nvarchar(MAX) NULL,
    [uf] nvarchar(MAX) NULL,
    [ultima_atualizacao] nvarchar(MAX) NULL,
    [version] nvarchar(MAX) NULL,
    [id_requisicao] int NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate()),
    CONSTRAINT [PK_RelatorioGeralKYCRFBPJ] PRIMARY KEY ([id])
);