CREATE TABLE [dbo].[ST_CARTEIRA_MEDIA_MENSAL] (
    [CD_ANOMES] int NOT NULL,
    [CD_CLIENTE] int NOT NULL,
    [MED_CARTEIRA] float NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate()),
    CONSTRAINT [PK_ST_CARTEIRA_MEDIA_MENSAL] PRIMARY KEY ([CD_ANOMES], [CD_CLIENTE])
);