CREATE TABLE [dbo].[ST_RELATORIO_MONEYPASS_BMF_DIARIO] (
    [DT_PERIODO] date NULL,
    [DT_PERIODO_2] date NULL,
    [CD_CLIENTE_1] int NULL,
    [CD_CLIENTE_2] int NULL,
    [CD_PAPEL] varchar(510) NULL,
    [QUANTIDADE] int NULL,
    [RESULTADO] numeric(38,2) NULL,
    [ASSERTIVIDADE] numeric(19,7) NULL,
    [CONCENTRACAO] numeric(30,13) NULL,
    [INTENCIONALIDADE] numeric(19,7) NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_RELATORIO_MONEYPASS_BMF_DIARIO] ON [dbo].[ST_RELATORIO_MONEYPASS_BMF_DIARIO] ([DT_PERIODO], [DT_PERIODO_2]);