CREATE TABLE [dbo].[ST_ALERT_ATIVO_RESTRITO] (
    [DATA] date NULL,
    [CD_CLIENTE] int NOT NULL,
    [IN_QUALIFICADO] char(1) NULL,
    [QTDE_NEGOCIOS] int NULL,
    [QTDE_ATIVOS] int NULL,
    [NEGOCIOS] varchar(MAX) NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_ALERT_ATIVO_RESTRITO] ON [dbo].[ST_ALERT_ATIVO_RESTRITO] ([CD_CLIENTE], [DATA]);

CREATE INDEX [ID002_ST_ALERT_ATIVO_RESTRITO] ON [dbo].[ST_ALERT_ATIVO_RESTRITO] ([DATA]);