CREATE TABLE [dbo].[ST_ALERT_MEDIA_BMF_01] (
    [DATA] date NULL,
    [CD_CLIENTE] int NOT NULL,
    [VOLUME] float NULL,
    [MEDIA] float NULL,
    [DESVIO] float NULL,
    [COMMOD_TOTAL] varchar(1000) NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_ALERT_MEDIA_BMF_01] ON [dbo].[ST_ALERT_MEDIA_BMF_01] ([CD_CLIENTE], [DATA]);

CREATE INDEX [ID002_ST_ALERT_MEDIA_BMF_01] ON [dbo].[ST_ALERT_MEDIA_BMF_01] ([DATA]);