CREATE TABLE [dbo].[ST_DAYTRADE_DETALHE] (
    [CD_CLIENTE_COMPROU] int NULL,
    [QT_NEGOCIO_COMPROU] float NULL,
    [VL_NEGOCIO_COMPROU] float NULL,
    [CD_NEGOCIO_COMPROU] varchar(12) NULL,
    [DT_PREGAO_COMPROU] datetime NULL,
    [CD_CONTRAPARTE_COMPROU] numeric(8,0) NULL,
    [CD_CONTRAPARTE_COMPROU_DE] numeric(8,0) NULL,
    [CD_CLIENTE_COMPROU_DE] int NULL,
    [QT_NEGOCIO_COMPROU_DE] float NULL,
    [VL_NEGOCIO_COMPROU_DE] float NULL,
    [NR_NEGOCIO_COMPROU] numeric(9,0) NULL,
    [CD_NATOPE] char(1) NULL,
    [QT_DAYTRADE] float NULL,
    [FT_VALORIZACAO] float NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_DAYTRADE_DETALHE] ON [dbo].[ST_DAYTRADE_DETALHE] ([CD_CLIENTE_COMPROU], [CD_NEGOCIO_COMPROU], [DT_PREGAO_COMPROU], [NR_NEGOCIO_COMPROU], [CD_NATOPE]);

CREATE INDEX [ID002_ST_DAYTRADE_DETALHE] ON [dbo].[ST_DAYTRADE_DETALHE] ([DT_PREGAO_COMPROU]);