CREATE TABLE [dbo].[ST_CONTROLE_VINCULADOS_BMF] (
    [DT_NEGOCIO] datetime NOT NULL,
    [CD_CLIENTE_COMPRA] int NULL,
    [NM_CLIENTE_COMPRA] varchar(400) NULL,
    [VINC_COMPRA] char(1) NULL,
    [CD_CLIENTE_VENDA] int NULL,
    [NM_CLIENTE_VENDA] varchar(400) NULL,
    [VINC_VENDA] char(1) NULL,
    [NR_NEGOCIO] numeric(12,0) NULL,
    [QT_NEGOCIO_COMPRA] float NOT NULL,
    [CD_COMMOD] varchar(10) NULL,
    [CD_SERIE] varchar(10) NULL,
    [HH_COMPRA] varchar(8) NULL,
    [VL_TOTNEG_COMPRA] float NOT NULL,
    [VL_NEGOCIO_COMPRA] float NOT NULL,
    [CD_ASSESSOR_COMPRA] int NULL,
    [DS_ASSESSOR_COMPRA] varchar(60) NULL,
    [CD_ASSESSOR_VENDA] int NULL,
    [DS_ASSESSOR_VENDA] varchar(60) NULL,
    [SISTEMA_COMPRA] varchar(10) NULL,
    [USUARIO_COMPRA] varchar(100) NULL,
    [SISTEMA_VENDA] varchar(10) NULL,
    [USUARIO_VENDA] varchar(100) NULL,
    [IN_DAYTRADE_COMPRA] char(1) NULL,
    [IN_DAYTRADE_VENDA] char(1) NULL,
    [CD_NATOPE] char(1) NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);