CREATE TABLE [dbo].[ST_MANIPULACAO_BVSP] (
    [DT_PERIODO] smalldatetime NULL,
    [CD_CLIENTE] int NOT NULL,
    [CD_CLIENTE_BRO] int NULL,
    [CD_PAPEL] varchar(12) NULL,
    [INDICE_BVSP] varchar(1) NOT NULL,
    [PREMED] numeric(17,2) NOT NULL,
    [PREABE] numeric(17,2) NOT NULL,
    [PREULT] numeric(17,2) NOT NULL,
    [VOLUME] float NULL,
    [VOLUME_CLIENTE_ANT] float NOT NULL,
    [VOL_MED_ATUAL] float NOT NULL,
    [VARIACAO_CLIENTE] float NOT NULL,
    [VARIACAO_CLIENTE_STRING] varchar(31) NULL,
    [VOLUME_MERCADO] float NULL,
    [VOLUME_MERCADO_ANT] float NOT NULL,
    [VARIACAO_MERCADO] float NOT NULL,
    [VARIACAO_MERCADO_STRING] varchar(31) NULL,
    [PERC_CLIENTE_MERCADO] float NOT NULL,
    [PERC_CLIENTE_MERCADO_STRING] varchar(31) NULL,
    [IND_LEILAO] varchar(1) NOT NULL,
    [VL_NEGOCIO_ABERTURA] float NOT NULL,
    [VL_NEGOCIO_FECHAMENTO] float NOT NULL,
    [VL_NEGOCIO_MIN] float NULL,
    [VL_NEGOCIO_MAX] float NULL,
    [VL_NEGOCIO_AVG] float NULL,
    [QTD_NEGOCIO] int NOT NULL,
    [PRECO_MIN_MERCADO] numeric(17,2) NOT NULL,
    [PRECO_MAX_MERCADO] numeric(17,2) NOT NULL,
    [QTD_NEGOCIOS_MERCADO] numeric(17,0) NOT NULL,
    [INTRADAY_CLIENTE] float NOT NULL,
    [INTRADAY_CLIENTE_STRING] varchar(31) NULL,
    [INTERDAY_CLIENTE] float NOT NULL,
    [INTERDAY_CLIENTE_STRING] varchar(31) NULL,
    [INTRADAY_MERCADO] numeric(38,20) NULL,
    [INTRADAY_MERCADO_STRING] varchar(31) NULL,
    [INTERDAY_MERCADO] numeric(38,20) NULL,
    [INTERDAY_MERCADO_STRING] varchar(31) NULL,
    [PRAZOT] varchar(20) NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [IDX01_ST_MANIPULACAO_BVSP] ON [dbo].[ST_MANIPULACAO_BVSP] ([DT_PERIODO]);

CREATE INDEX [IDX02_ST_MANIPULACAO_BVSP] ON [dbo].[ST_MANIPULACAO_BVSP] ([CD_CLIENTE], [CD_PAPEL]);

CREATE INDEX [IDX03_ST_MANIPULACAO_BVSP] ON [dbo].[ST_MANIPULACAO_BVSP] ([DT_PERIODO]);