CREATE TABLE [dbo].[ST_ALERT_EMISSOR_VINCULADO] (
    [DATA] date NULL,
    [CD_CLIENTE] int NULL,
    [RESULTADO] numeric(17,2) NULL,
    [TICKER] char(4) NULL,
    [CNPJ] varchar(20) NULL,
    [RAZAO_SOCIAL] varchar(800) NULL,
    [QTD_COMPRA] int NULL,
    [QTD_VENDA] int NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_ALERT_EMISSOR_VINCULADO] ON [dbo].[ST_ALERT_EMISSOR_VINCULADO] ([CD_CLIENTE], [DATA]);

CREATE INDEX [ID002_ST_ALERT_EMISSOR_VINCULADO] ON [dbo].[ST_ALERT_EMISSOR_VINCULADO] ([DATA]);