CREATE TABLE [dbo].[ST_ALERT_LISTA_ATENCAO] (
    [DATA] date NULL,
    [CD_CLIENTE] int NOT NULL,
    [CD_CPFCGC] varchar(20) NULL,
    [NM_CLIENTE] varchar(400) NULL,
    [CPF_PARC] varchar(1) NOT NULL,
    [CPF_COMP] varchar(1) NOT NULL,
    [NOME_ENC] varchar(1) NOT NULL,
    [RSLT_CONS] nvarchar(MAX) NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_ALERT_LISTA_ATENCAO] ON [dbo].[ST_ALERT_LISTA_ATENCAO] ([CD_CLIENTE], [DATA]);

CREATE INDEX [ID002_ST_ALERT_LISTA_ATENCAO] ON [dbo].[ST_ALERT_LISTA_ATENCAO] ([DATA]);