CREATE TABLE [dbo].[incident] (
    [id] int IDENTITY(1,1) NOT NULL,
    [summary] nvarchar(400) NULL,
    [area_id] bigint NULL,
    [priority_id] bigint NULL,
    [source_id] bigint NULL,
    [group_id] bigint NULL,
    [reporter_id] bigint NULL,
    [assignee_id] bigint NULL,
    [subgroup_id] bigint NULL,
    [state_id] bigint NULL,
    [reference_id] bigint NULL,
    [client_code] bigint NULL,
    [client_name] nvarchar(1000) NULL,
    [client_document] nvarchar(50) NULL,
    [description] nvarchar(MAX) NULL,
    [date_start] smalldatetime NOT NULL,
    [date_end] smalldatetime NULL,
    [sla_type] varchar(100) NULL,
    [sla_time] varchar(100) NULL,
    [company_id] int NULL,
    [service_group_id] int NULL,
    [client_abbreviation] varchar(100) NULL,
    [distribuicaoPropria] int NULL,
    [sinacor_client] bit NULL,
    [broker_code] int NULL,
    [code_88] int NULL,
    [cvm_code] int NULL,
    [incident_id] bigint NULL,
    [id_processamento] bigint NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate()),
    CONSTRAINT [PK_incident] PRIMARY KEY ([id])
);