CREATE TABLE [dbo].[ST_RELATORIO_PAINEL_ALERTAS_CVM] (
    [ANALISE] varchar(8) NULL,
    [Referencia] varchar(42) NULL,
    [Cód. Cliente] int NULL,
    [NOME DO CLIENTE] nvarchar(160) NULL,
    [NACIONALIDADE] varchar(160) NULL,
    [CPF/CNPJ] varchar(20) NULL,
    [PF / PJ] varchar(3) NULL,
    [IDADE] int NULL,
    [INVESTIDOR] nvarchar(160) NULL,
    [DATA DE CRIAÇÃO] nvarchar(4000) NULL,
    [FRONTEIRA] varchar(3) NULL,
    [PEP SINACOR] varchar(3) NULL,
    [PESSOA VINCULADA] varchar(3) NULL,
    [INR] varchar(13) NULL,
    [ASSESSOR] varchar(160) NULL,
    [PROFISSÃO / SEGMENTO DE ATUAÇÃO] varchar(160) NULL,
    [PROFISSÃO DE RISCO] varchar(160) NULL,
    [SCORE RISCO] varchar(5) NULL,
    [RISCO ABR] varchar(10) NULL,
    [Money Pass Corretora Bvsp] nvarchar(4000) NULL,
    [Money Pass Corretora Bmf] nvarchar(4000) NULL,
    [Money Pass Bvsp] nvarchar(4000) NULL,
    [Money Pass Bmf] nvarchar(4000) NULL,
    [Média Oper. BMF] nvarchar(4000) NULL,
    [Média Oper. Bvsp] nvarchar(4000) NULL,
    [Transf. Financeira 01] nvarchar(4000) NULL,
    [Transf. Financeira 02] nvarchar(4000) NULL,
    [Patrimônio X Custódia] nvarchar(4000) NULL,
    [Patrimônio X Netting] nvarchar(4000) NULL,
    [Patrimônio X Mov Cc] nvarchar(4000) NULL,
    [Patrimônio X Transf. Custodia] nvarchar(4000) NULL,
    [Atualização Cadastral] nvarchar(4000) NULL,
    [Procurador] nvarchar(4000) NULL,
    [Mudança Repentina] nvarchar(4000) NULL,
    [Ranking Daytrade Bvsp] nvarchar(4000) NULL,
    [Ranking Daytrade Bmf] nvarchar(4000) NULL,
    [Lista Atenção] nvarchar(4000) NULL,
    [Ativo Restrito] nvarchar(4000) NULL,
    [Insider Trading] nvarchar(4000) NULL,
    [Churning] nvarchar(4000) NULL,
    [Omc Bvsp] nvarchar(4000) NULL,
    [Omc Bmf] nvarchar(4000) NULL,
    [Oscilação] nvarchar(4000) NULL,
    [Omg Bvsp] nvarchar(4000) NULL,
    [Omg Bmf] nvarchar(4000) NULL,
    [TOTAL] int NULL,
    [Vinculado ao Emissor] nvarchar(4000) NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);