CREATE TABLE [dbo].[ST_DIRETAS_BVSP] (
    [CD_CLIENTE_COMPRA] int NOT NULL,
    [NM_CLIENTE_COMPRA] varchar(400) NULL,
    [VINC_COMPRA] char(1) NULL,
    [CD_CLIENTE_BRO_COMPRA] int NOT NULL,
    [CD_CLIENTE_VENDA] int NOT NULL,
    [NM_CLIENTE_VENDA] varchar(400) NULL,
    [VINC_VENDA] char(1) NULL,
    [CD_CLIENTE_BRO_VENDA] int NOT NULL,
    [DT_PERIODO] smalldatetime NULL,
    [SISTEMA_COMPRA] varchar(40) NULL,
    [SISTEMA_VENDA] varchar(40) NULL,
    [NR_NEGOCIO] int NOT NULL,
    [QT_NEGOCIO_COMPRA] float NOT NULL,
    [QT_NEGOCIO_VENDA] float NOT NULL,
    [CD_PAPEL] varchar(50) NULL,
    [HH_COMPRA] varchar(5) NULL,
    [HH_VENDA] varchar(5) NULL,
    [VL_TOTNEG_COMPRA] float NULL,
    [VL_TOTNEG_VENDA] float NULL,
    [VL_NEGOCIO_COMPRA] float NULL,
    [VL_NEGOCIO_VENDA] float NULL,
    [CD_ASSESSOR_COMPRA] int NULL,
    [DS_ASSESSOR_COMPRA] varchar(60) NULL,
    [CD_ASSESSOR_VENDA] int NULL,
    [DS_ASSESSOR_VENDA] varchar(60) NULL,
    [CD_OPERADOR_COMPRA] int NULL,
    [CD_OPERADOR_VENDA] int NULL,
    [DS_OPERADOR_COMPRA] varchar(40) NULL,
    [DS_OPERADOR_VENDA] varchar(40) NULL,
    [TP_CLIENTE_COMPRA] int NULL,
    [DS_TP_CLIENTE_COMPRA] varchar(40) NULL,
    [TP_CLIENTE_VENDA] int NULL,
    [DS_TP_CLIENTE_VENDA] varchar(40) NULL,
    [ds_tp_mercado_compra] varchar(100) NULL,
    [cd_tp_mercado_compra] varchar(3) NULL,
    [ds_tp_mercado_venda] varchar(100) NULL,
    [cd_tp_mercado_venda] varchar(3) NULL,
    [in_Afterm] varchar(100) NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);