CREATE TABLE [dbo].[ST_TESOURO] (
    [DATA_MVTO] datetime2(7) NULL,
    [DATA_NEGO] datetime2(7) NULL,
    [COD_LOC] numeric(7,0) NOT NULL,
    [COD_CLI] numeric(15,0) NOT NULL,
    [TIPO_TITU] nvarchar(10) NULL,
    [DATA_VENC] datetime2(7) NULL,
    [COD_SELI] numeric(6,0) NULL,
    [COD_ISIN] nvarchar(12) NULL,
    [NAT_OPE] nvarchar(1) NULL,
    [QTDE_TITU] numeric(13,2) NULL,
    [NUM_PROT] numeric(10,0) NULL,
    [COD_USUA] nvarchar(15) NULL,
    [COD_USUA_CONP] numeric(15,0) NULL,
    [PREC_TRNS] numeric(15,2) NULL,
    [VAL_TRNS] numeric(15,2) NULL,
    [VAL_TAXA_AGEN] numeric(15,2) NULL,
    [VAL_TOT] numeric(15,2) NULL,
    [PREC_ORIG] numeric(15,2) NULL,
    [VAL_ORIG] numeric(15,2) NULL,
    [DATA_ORIG] datetime2(7) NULL,
    [IND_ORI] numeric(3,0) NULL,
    [DATA_LIQD] datetime2(7) NULL,
    [VAL_RES] numeric(15,2) NULL,
    [VAL_IR] numeric(15,2) NULL,
    [DESC_HIST_MVTO] nvarchar(80) NULL,
    [NOME_USUA] nvarchar(20) NULL,
    [NOME_TMNL] nvarchar(15) NULL,
    [DATA_SIST] datetime2(7) NULL,
    [NUM_EXTR] numeric(7,0) NULL,
    [IND_INTR_EXEC] nvarchar(1) NULL,
    [NOME_USUA_INTR] nvarchar(20) NULL,
    [NOME_TMNL_INTR] nvarchar(110) NULL,
    [DATA_SIST_INTR] datetime2(7) NULL,
    [VAL_CBLC] numeric(15,2) NULL,
    [NUM_DIAS] numeric(4,0) NULL,
    [VAL_IOF] numeric(15,2) NULL,
    [VAL_TAXA_SEME_BOLS] numeric(13,2) NULL,
    [VAL_TAXA_SEME_AGCT] numeric(13,2) NULL,
    [NUM_PROT_AGENDA] numeric(10,0) NULL,
    [PERC_REINV] numeric(5,2) NULL,
    [VAL_ORIG_REINV] numeric(13,2) NULL,
    [VAL_REINV] numeric(13,2) NULL,
    [NUM_ARQ_CRTD] numeric(9,0) NULL,
    [DATA_EMIS_TIT] datetime2(7) NULL,
    [DATA_PGTO_CUP_ANTE] datetime2(7) NULL,
    [DATA_PGTO_PRIM_CUPOM] datetime2(7) NULL,
    [VAL_PREC_PRIM_CUPOM_JURO] numeric(15,2) NULL,
    [DATA_PGTO_CUPOM_ANTE_COMPRA] datetime2(7) NULL,
    [DATA_LIQD_COMPRA] datetime2(7) NULL,
    [QTDE_TITU_GARANTIA] numeric(13,2) NULL,
    [NUM_SEQ_TCFMOVI_TEDI] int NULL,
    [COD_TIPO_DATA_BASE] char(1) NULL,
    [VAL_RES_TITU_BLOQ] numeric(12,2) NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);