CREATE TABLE [dbo].[ST_PATRIMONIO_LIQ] (
    [CD_CPFCGC] varchar(30) NULL,
    [CD_GRUPO] int NOT NULL,
    [DS_GRUPO] varchar(15) NULL,
    [VAL_BENS] float NULL,
    [DS_BEN] varchar(100) NULL,
    [TIPO] varchar(2) NULL,
    [CD_CLIENTE] int NOT NULL,
    [DATA] smalldatetime NULL,
    [CD_SFPSUBGRUPO] int NULL,
    [VAL_CAPTL_SCIAL] float NULL,
    [VAL_CAPTL_GIRO] float NULL,
    [VAL_RENDA_MENSAL] float NULL,
    [VAL_RENDA_ANUAL] float NULL,
    [VAL_SITU_PATRM] float NULL,
    [VAL_PATRM_LIQ] float NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_PATRIMONIO_LIQ] ON [dbo].[ST_PATRIMONIO_LIQ] ([VAL_BENS], [DATA], [VAL_SITU_PATRM], [VAL_PATRM_LIQ]);

CREATE INDEX [ID002_ST_PATRIMONIO_LIQ] ON [dbo].[ST_PATRIMONIO_LIQ] ([DATA]);

CREATE INDEX [IDX001_DM_PATRIMONIO_LIQ] ON [dbo].[ST_PATRIMONIO_LIQ] ([DATA]);

CREATE INDEX [IDX002_DM_PATRIMONIO_LIQ] ON [dbo].[ST_PATRIMONIO_LIQ] ([DATA]);

CREATE INDEX [IDX003_DM_PATRIMONIO_LIQ] ON [dbo].[ST_PATRIMONIO_LIQ] ([DATA]);