CREATE TABLE [dbo].[ST_ALERT_ATULIZACAO_CADASTRAL_01] (
    [DATA] date NULL,
    [CD_CLIENTE] int NOT NULL,
    [TP_SITUAC] nvarchar(255) NULL,
    [DT_VALIDADE] datetime2(7) NULL,
    [DT_BVSP] smalldatetime NULL,
    [DS_NATUREZA_BVSP] varchar(12) NULL,
    [DT_BMF] datetime NULL,
    [DS_NATUREZA_BMF] varchar(12) NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_ALERT_ATULIZACAO_CADASTRAL_01] ON [dbo].[ST_ALERT_ATULIZACAO_CADASTRAL_01] ([CD_CLIENTE], [DATA]);

CREATE INDEX [ID002_ST_ALERT_ATULIZACAO_CADASTRAL_01] ON [dbo].[ST_ALERT_ATULIZACAO_CADASTRAL_01] ([DATA]);