CREATE TABLE [dbo].[ST_DADOS_FINANCEIROS_PJ] (
    [CPF] varchar(20) NULL,
    [CONTA] nvarchar(26) NULL,
    [PATRIMONIO] float NULL,
    [DS_ATIV] varchar(160) NULL,
    [DESPOSITO_BANCARIO] float NULL,
    [RENDA_FIXA] float NULL,
    [RENDA_VARIAVEL] float NULL,
    [VL_OPERACIONAL1] float NULL,
    [IN_CONTR_BOLSA] nchar(1) NULL,
    [IN_CONTR_BMF] nchar(1) NULL,
    [IN_CONTR_SOCIAL] nchar(1) NULL,
    [IN_CONTR_OPC] nchar(1) NULL,
    [IN_CONTR_TER] nchar(1) NULL,
    [IN_CONTR_TST] nchar(1) NULL,
    [IN_CONTR_BTC] nchar(1) NULL,
    [IN_CONTA_MARGEM] nchar(1) NULL,
    [TP_SITUAC] nvarchar(2) NULL,
    [CD_ASSESSOR] int NULL,
    [NM_EMPRESA] nvarchar(160) NULL,
    [NM_CLIENTE] nvarchar(160) NULL,
    [CD_CLIENTE] int NULL,
    [NM_ASSESSOR] varchar(300) NULL,
    [CD_BANCO] nvarchar(18) NULL,
    [CD_AGENCIA] nvarchar(15) NULL,
    [BENS IMÓVEIS] float NULL,
    [BENS MÓVEIS] float NULL,
    [APLICAÇÕES FINANCEIRAS] float NULL,
    [SALÁRIO] float NULL,
    [OUTROS RENDIMENTOS] float NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);