CREATE TABLE [dbo].[RelatorioAlertas] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [INDICE] int NOT NULL,
    [NOME] nvarchar(1000) NOT NULL,
    [DESCRICAO] nvarchar(2000) NOT NULL,
    [PROCEDURE] nvarchar(4000) NOT NULL,
    [IDCATEGORIA] int NULL,
    [IDSUBCATEGORIA] int NULL,
    [ROTA] varchar(80) NULL,
    [ROTULO] nvarchar(MAX) NULL,
    [CAMINHO] nvarchar(MAX) NULL,
    [MOSTRARALERTA] bit NULL,
    [SQL] nvarchar(MAX) NULL,
    [ID_MENU] int NULL,
    [VISIVEL] bit NULL,
    [IDSCORECATEGORIA] int NULL,
    [INCISO] varchar(20) NULL,
    [TIPO_ALERTA] varchar(50) NULL,
    [SCHEMA_NAME] sysname NULL,
    [COL_DATA] sysname NULL,
    [COL_CLIENTE] sysname NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate()),
    [DETALHE_ALERTA] nvarchar(4000) NULL,
    CONSTRAINT [PK_RelatorioAlertas] PRIMARY KEY ([ID])
);