CREATE TABLE [dbo].[ST_ALERT_OMC_BMF_01] (
    [DATA] date NULL,
    [CD_CLIENTE] int NULL,
    [NR_NEGOCIO] numeric(12,0) NULL,
    [QT_NEGOCIO_COMPRA] float NULL,
    [QT_NEGOCIO_VENDA] float NULL,
    [CD_NEGOCIO] varchar(20) NULL,
    [HH_COMPRA] varchar(5) NULL,
    [HH_VENDA] varchar(5) NULL,
    [VL_TOTNEG_COMPRA] float NULL,
    [VL_TOTNEG_VENDA] float NULL,
    [VL_NEGOCIO_COMPRA] float NULL,
    [VL_NEGOCIO_VENDA] float NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_ALERT_OMC_BMF_01] ON [dbo].[ST_ALERT_OMC_BMF_01] ([CD_CLIENTE], [DATA]);

CREATE INDEX [ID002_ST_ALERT_OMC_BMF_01] ON [dbo].[ST_ALERT_OMC_BMF_01] ([DATA]);