CREATE TABLE [dbo].[ST_ALERT_MONEYPASS_CORRETORA] (
    [DATA] date NULL,
    [CD_CLIENTE] int NULL,
    [CD_CONTRAPARTE] int NULL,
    [NR_NEGOCIOS] varchar(MAX) NULL,
    [PAPEIS] varchar(MAX) NULL,
    [QTD_TOTAL] bigint NULL,
    [RESULTADO] decimal(17,3) NULL,
    [RESULTADO_MEDIA_6M] decimal(17,3) NULL,
    [RESULTADO_DESVIO_6M] decimal(17,3) NULL,
    [CONCENTRACAO] decimal(17,3) NULL,
    [CONCENTRACAO_MEDIA_6M] decimal(17,3) NULL,
    [CONCENTRACAO_DESVIO_6M] decimal(17,3) NULL,
    [IND_ACERTO] decimal(17,3) NULL,
    [IND_ACERTO_MEDIO_6M] decimal(17,3) NULL,
    [IND_ERRO] decimal(17,3) NULL,
    [IND_ERRO_6M] decimal(17,3) NULL,
    [INTENCIONALIDADE] decimal(17,3) NULL,
    [INTENCIONALIDADE_MEDIA_6M] decimal(17,3) NULL,
    [INTENCIONALIDADE_DESVIO_6M] decimal(17,3) NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_ALERT_MONEYPASS_CORRETORA] ON [dbo].[ST_ALERT_MONEYPASS_CORRETORA] ([CD_CLIENTE], [DATA]);

CREATE INDEX [ID002_ST_ALERT_MONEYPASS_CORRETORA] ON [dbo].[ST_ALERT_MONEYPASS_CORRETORA] ([DATA]);