CREATE TABLE [dbo].[ST_ALERT_PATRIMONIO_TRANF_CUST] (
    [DATA] date NULL,
    [CD_CLIENTE] int NOT NULL,
    [TOTAL_MES] numeric(38,2) NULL,
    [PATRIMONIO] numeric(38,2) NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_ALERT_PATRIMONIO_TRANF_CUST] ON [dbo].[ST_ALERT_PATRIMONIO_TRANF_CUST] ([CD_CLIENTE], [DATA]);

CREATE INDEX [ID002_ST_ALERT_PATRIMONIO_TRANF_CUST] ON [dbo].[ST_ALERT_PATRIMONIO_TRANF_CUST] ([DATA]);