CREATE TABLE [dbo].[ST_ALERT_MUDANCA_REPENTINA_01] (
    [DATA] date NULL,
    [CD_CLIENTE] int NOT NULL,
    [CD_TP_MERCADO] nvarchar(255) NULL,
    [MERCADO_HIST_6M] varchar(100) NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_ALERT_MUDANCA_REPENTINA_01] ON [dbo].[ST_ALERT_MUDANCA_REPENTINA_01] ([CD_CLIENTE], [DATA]);

CREATE INDEX [ID002_ST_ALERT_MUDANCA_REPENTINA_01] ON [dbo].[ST_ALERT_MUDANCA_REPENTINA_01] ([DATA]);