CREATE TABLE [dbo].[ST_ALERT_OSCILACAO] (
    [DATA] date NOT NULL,
    [CD_CLIENTE] int NULL,
    [ATIVO] nvarchar(300) NULL,
    [ALERTADO_CVM50] int NOT NULL,
    [ALERTADO_CVM62] int NOT NULL,
    [PROPORCAO] decimal(15,4) NULL,
    [OSCILACAO_MEDIA] decimal(15,4) NULL,
    [OSCILACAO_MAX] decimal(15,4) NULL,
    [DIFERENCA_MEDIA] decimal(15,4) NULL,
    [ALERTADO_OSCILACAO] int NOT NULL,
    [ALERTADO_OSCILACAO_MAX] int NOT NULL,
    [ALERTADO_DIFERENCA] int NOT NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_ALERT_OSCILACAO] ON [dbo].[ST_ALERT_OSCILACAO] ([CD_CLIENTE], [DATA]);

CREATE INDEX [ID002_ST_ALERT_OSCILACAO] ON [dbo].[ST_ALERT_OSCILACAO] ([DATA]);