CREATE TABLE [dbo].[ST_ALERT_CHURNING_BOVESPA_02] (
    [DATA] date NULL,
    [CD_CLIENTE] int NOT NULL,
    [QTD] int NULL,
    [CORRETAGEM] numeric(20,2) NULL,
    [TURNOVER_RATIO] numeric(20,2) NULL,
    [COST_EQUITY_RATIO] numeric(20,2) NULL,
    [ALERTADO_TR] varchar(10) NULL,
    [ALERTADO_CE] varchar(10) NULL,
    [VOLUME_COMPRA] float NULL,
    [QTD_DIA_UTEIS_MES] int NULL,
    [QTD_DIA_UTEIS_SEMESTRE] int NULL,
    [MED_CARTEIRA] numeric(17,2) NULL,
    [ATIVO] nvarchar(MAX) NULL,
    [RESULTADO] float NULL,
    [NM_CLIENTE] varchar(400) NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_ALERT_CHURNING_BOVESPA_02] ON [dbo].[ST_ALERT_CHURNING_BOVESPA_02] ([CD_CLIENTE], [DATA]);

CREATE INDEX [ID002_ST_ALERT_CHURNING_BOVESPA_02] ON [dbo].[ST_ALERT_CHURNING_BOVESPA_02] ([DATA]);