CREATE TABLE [dbo].[ST_DADOS_FINANCEIROS_PF] (
    [CPF] varchar(20) NULL,
    [NM_CLIENTE] varchar(160) NULL,
    [CD_CLIENTE] int NOT NULL,
    [ASSESSOR] varchar(160) NULL,
    [CD_BANCO] varchar(3) NULL,
    [AGENCIA] varchar(5) NULL,
    [CONTA] varchar(16) NULL,
    [PROF_ATIV] varchar(60) NULL,
    [PATRIMONIO] float NULL,
    [CARGO] varchar(140) NULL,
    [BENS_IMOV] float NULL,
    [BENS_MOV] float NULL,
    [APLICACOES_FINAN] float NULL,
    [SALARIO] float NULL,
    [OUTROS_REND] float NULL,
    [DESPOSITO_BANCARIO] float NULL,
    [RENDA_FIXA] float NULL,
    [RENDA_VARIAVEL] float NULL,
    [VL_OPERACIONAL1] float NULL,
    [IN_CONTR_BOLSA] char(1) NULL,
    [IN_CONTR_BMF] char(1) NULL,
    [IN_CONTR_SOCIAL] char(1) NULL,
    [IN_CONTR_OPC] char(1) NULL,
    [IN_CONTR_TER] char(1) NULL,
    [IN_CONTR_TST] char(1) NULL,
    [IN_CONTR_BTC] char(1) NULL,
    [IN_CONTA_MARGEM] char(1) NULL,
    [tp_situac] char(2) NULL,
    [CD_ASSESSOR] int NULL,
    [NM_EMPRESA] varchar(100) NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);