CREATE TABLE [dbo].[ST_CONTROLE_VINCULADOS] (
    [CD_CLIENTE_COMPRA] int NOT NULL,
    [NM_CLIENTE_COMPRA] varchar(400) NULL,
    [VINC_COMPRA] char(1) NULL,
    [CD_CLIENTE_BRO_COMPRA] int NOT NULL,
    [CD_CLIENTE_VENDA] int NULL,
    [NM_CLIENTE_VENDA] varchar(400) NULL,
    [VINC_VENDA] char(1) NULL,
    [CD_CLIENTE_BRO_VENDA] int NULL,
    [DT_PERIODO] smalldatetime NOT NULL,
    [SISTEMA_COMPRA] varchar(40) NULL,
    [SISTEMA_VENDA] varchar(40) NULL,
    [NR_NEGOCIO] int NOT NULL,
    [QT_NEGOCIO_COMPRA] float NOT NULL,
    [QT_NEGOCIO_VENDA] float NULL,
    [CD_PAPEL] varchar(50) NOT NULL,
    [HH_COMPRA] varchar(5) NULL,
    [HH_VENDA] varchar(5) NULL,
    [VL_TOTNEG_COMPRA] float NULL,
    [VL_TOTNEG_VENDA] float NULL,
    [VL_NEGOCIO_COMPRA] float NULL,
    [VL_NEGOCIO_VENDA] float NULL,
    [CD_ASSESSOR_COMPRA] int NULL,
    [DS_ASSESSOR_COMPRA] varchar(60) NULL,
    [CD_ASSESSOR_VENDA] int NULL,
    [DS_ASSESSOR_VENDA] varchar(60) NULL,
    [DS_TIPO_OFERTA] varchar(6) NOT NULL,
    [SALDO_CC] numeric(15,2) NULL,
    [POSI_PAPEL_LIVRE] float NULL,
    [POSI_GARANTIAS] float NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);