CREATE TABLE [dbo].[RelatorioGeralKYCBSMPAD] (
    [numero_pad] varchar(MAX) NULL,
    [acusado] varchar(MAX) NULL,
    [tipo_de_acusado] varchar(MAX) NULL,
    [origem] varchar(MAX) NULL,
    [infracao] varchar(MAX) NULL,
    [data_de_instauração] varchar(MAX) NULL,
    [status] varchar(MAX) NULL,
    [penalidade_aplicada] varchar(MAX) NULL,
    [data_de_encerramento] varchar(MAX) NULL,
    [periodo_de_ocorrencia] varchar(MAX) NULL,
    [artigo_inciso] varchar(MAX) NULL,
    [indice] int NULL,
    [valor] varchar(MAX) NULL,
    [relator_1_instancia] varchar(MAX) NULL,
    [conselheiro_2_1_instancia] varchar(MAX) NULL,
    [conselheiro_3_1_instancia] varchar(MAX) NULL,
    [relator_2_instancia] varchar(MAX) NULL,
    [proposta_tc] varchar(MAX) NULL,
    [valor_tc] varchar(MAX) NULL,
    [decisao_cs] varchar(MAX) NULL,
    [id_requisicao] int NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);