CREATE TABLE [dbo].[ST_DAYTRADE_RESUMO_BMF] (
    [CD_CLIENTE_COMPROU] int NULL,
    [VL_COMPRA] float NULL,
    [VL_VENDA] float NULL,
    [VL_FINANC] float NULL,
    [DT_PREGAO_COMPROU] datetime NOT NULL,
    [QT_CONTRAPARTES] int NULL,
    [DT_PRIMEIRA_OPER] smalldatetime NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_DAYTRADE_RESUMO_BMF] ON [dbo].[ST_DAYTRADE_RESUMO_BMF] ([DT_PREGAO_COMPROU]);