CREATE TABLE [dbo].[ST_CONSULTA_TRIBUNAIS_PROCESSO_V2] (
    [Numero] varchar(MAX) NULL,
    [Nome] varchar(MAX) NULL,
    [TipoParteConsultada] varchar(MAX) NULL,
    [Assuntos] varchar(MAX) NULL,
    [PartesAtivas] varchar(MAX) NULL,
    [PartesPassivas] varchar(MAX) NULL,
    [AdvogadosEnvolvidos] varchar(MAX) NULL,
    [OutrasPartesEnvolvidas] varchar(MAX) NULL,
    [UF] varchar(MAX) NULL,
    [UltimoAndamento] varchar(MAX) NULL,
    [DataUltimoAndamento] varchar(MAX) NULL,
    [Juiz] varchar(MAX) NULL,
    [segredoJustica] bigint NULL,
    [classes] varchar(MAX) NULL,
    [vara] varchar(MAX) NULL,
    [comarca] varchar(MAX) NULL,
    [dataAutuacao] varchar(MAX) NULL,
    [dataDistribuicao] varchar(MAX) NULL,
    [valor] varchar(MAX) NULL,
    [situacao] varchar(MAX) NULL,
    [movimentacoes] varchar(MAX) NULL,
    [tribunal] varchar(MAX) NULL,
    [IdRequisicao] int NULL,
    [StatusConsulta] varchar(500) NULL,
    [urlResultPage] varchar(500) NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);