CREATE TABLE [dbo].[ST_V_TBOMOVCL] (
    [CD_ASSESSOR] numeric(5,0) NULL,
    [CD_BOLSAMOV] varchar(2) NULL,
    [CD_CARLIQ] numeric(3,0) NULL,
    [CD_CLIENTE] int NULL,
    [CD_CLIENTE_BRO] int NULL,
    [CD_CLIENTE_FIN] int NULL,
    [CD_NATOPE] char(1) NULL,
    [CD_NEGOCIO] varchar(12) NULL,
    [DT_NEGOCIO] datetime2(7) NULL,
    [DV_NEGOCIO] numeric(1,0) NULL,
    [IN_BROKER] char(1) NULL,
    [IN_CORRESP] char(1) NULL,
    [IN_LIQUIDA] char(1) NULL,
    [NR_NEGOCIO] numeric(9,0) NULL,
    [QT_QTDESP] numeric(16,4) NULL,
    [TP_NEGOCIO] char(3) NULL,
    [VL_CORTOT] numeric(17,2) NULL,
    [VL_CORTOT_ORI] numeric(17,2) NULL,
    [VL_NEGOCIO] numeric(19,8) NULL,
    [VL_TOTNEG] numeric(17,2) NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate()),
    [IN_QUALIFICADO] char(1) NULL
);