CREATE TABLE [dbo].[ST_ALERT_PATRIMONIO_NETTING] (
    [DATA] date NULL,
    [CD_CLIENTE] int NOT NULL,
    [NETTING_BVSP] float NULL,
    [NETTING_BMF] float NULL,
    [PATRIMONIO] numeric(38,2) NULL,
    [DT_FIRA] datetime NULL DEFAULT (getdate())
);

CREATE INDEX [ID001_ST_ALERT_PATRIMONIO_NETTING] ON [dbo].[ST_ALERT_PATRIMONIO_NETTING] ([CD_CLIENTE], [DATA]);

CREATE INDEX [ID002_ST_ALERT_PATRIMONIO_NETTING] ON [dbo].[ST_ALERT_PATRIMONIO_NETTING] ([DATA]);