CREATE FUNCTION [dbo].[DIA_UTIL] (@DT_PERIODO DATE)
RETURNS INT
AS
BEGIN
	DECLARE @DIA_UTL INT;
	SET @DIA_UTL = (
		
		SELECT DIA_UTIL 
		  FROM (
				SELECT DT_PERIODO
					 , ROW_NUMBER() OVER (ORDER BY DT_PERIODO) DIA_UTIL   
				  FROM  (
						  SELECT DT_PERIODO
		  					  , CD_DIA
		  					  , DS_DIASEMANA_ABREV
		  					  , DT_FERIADO 
		  					  , CASE WHEN DT_FERIADO = 'SIM' THEN 0 WHEN DS_DIASEMANA_ABREV IN ('SABADO','DOMINGO') THEN 0 ELSE 1 END FLAG_DIA_UTIL 
						  FROM ST_PERIODO 
						 WHERE CD_ANO  = YEAR(@DT_PERIODO) 
						   AND CD_MES  = MONTH(@DT_PERIODO) 
						) x
						WHERE FLAG_DIA_UTIL = 1 
				)Y
		  WHERE DT_PERIODO = @DT_PERIODO)

RETURN ISNULL(@DIA_UTL,0)

END