CREATE   VIEW [dbo].[VDASH_ALERTAS_INICIAL]
AS

SELECT TOP 6 
YEAR(DT_PERIODO)CD_ANO,
MONTH(DT_PERIODO)CD_MES,
DT_PERIODO AS [DATA],
COUNT(DISTINCT CD_CLIENTE) AS [QTD_CLIENTES],
COUNT(NM_ALERTA) AS [QTD_ALERTAS]  
FROM VDASH_ALERTAS 
WHERE EOMONTH(DATEFROMPARTS(YEAR(DT_PERIODO), MONTH(DT_PERIODO), 1)) >= (SELECT CAST(GETDATE()-365 AS DATE))
GROUP BY DT_PERIODO
ORDER BY 3 DESC