--alterado em 03/02/2021 por Felipe 
CREATE VIEW [dbo].[VW_EIXO_XY]
--WITH ENCRYPTION
as

-- VIEW EIXO X/Y

select top 10
CONTAGEM, CD_ANOMES , ROW_NUMBER() OVER(ORDER BY CD_ANOMES desc) ORDER_BY from (
SELECT count(distinct CD_CLIENTE) CONTAGEM, CD_ANOMES  
FROM (
SELECT distinct  CD_CLIENTE, B.CD_ANOMES FROM ST_CORRETAGEM_ORDEM A
INNER JOIN ST_PERIODO B ON A.DT_NEGOCIO = B.DT_PERIODO
where a.dt_NEGOCIO >= getdate()-365

UNION ALL

SELECT distinct CD_CLIENTE CONTAGEM, B.CD_ANOMES FROM ST_BMF_NEGOCIOS_NC A
INNER JOIN ST_PERIODO B ON A.DT_NEGOCIO = B.DT_PERIODO
AND TP_NEGOCIO IN ('NORMAL','DAY TRADE','DAYTRADE')
where a.DT_NEGOCIO >= getdate()-365
) X

GROUP BY CD_ANOMES 
) Y
order by 3 desc