CREATE   VIEW dbo.VDASH_ALERTAS
AS
SELECT
    XX.DT_PERIODO,
    XX.CD_CLIENTE,
    B.NM_CLIENTE,
    B.CD_CPFCGC,
    XX.NOME_ALERTA AS NM_ALERTA,
    SUM(XX.QTD_ALERTAS_PERIODO) AS QTD_ALERTAS_PERIODO,
    XX.INCISO,
    ISNULL(MAX(C.[VALUE]),0) AS AJUSTE,
    XX.Tipo_alerta
FROM (
    SELECT
        X.DT_PERIODO,
        X.CD_CLIENTE,
        X.NOME_ALERTA,
        COUNT(X.QTD_MES) AS QTD_ALERTAS_PERIODO,
        X.INCISO,
        X.Tipo_alerta
    FROM (
        SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Money Pass Corretora Bmf' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '301' AS INCISO, 'Transacional' AS Tipo_alerta FROM dbo.[ST_ALERT_MONEYPASS_CORRETORA_BMF] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Money Pass Corretora Bvsp' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '301' AS INCISO, 'Transacional' AS Tipo_alerta FROM dbo.[ST_ALERT_MONEYPASS_CORRETORA] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Atualização Cadastral' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '301' AS INCISO, 'Cadastral' AS Tipo_alerta FROM dbo.[ST_ALERT_ATULIZACAO_CADASTRAL_01] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Churning' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '08' AS INCISO, 'Transacional' AS Tipo_alerta FROM dbo.[ST_ALERT_CHURNING_BOVESPA_02] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Insider Trading' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '08' AS INCISO, 'Transacional' AS Tipo_alerta FROM dbo.[ST_ALERT_INSIDER_TRADING_02] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Média Oper. Bmf' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '301' AS INCISO, 'Transacional' AS Tipo_alerta FROM dbo.[ST_ALERT_MEDIA_BMF_01] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Média Oper. Bvsp' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '301' AS INCISO, 'Transacional' AS Tipo_alerta FROM dbo.[ST_ALERT_MEDIA_BOVESPA_01] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Mudança Repentina' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '301' AS INCISO, 'Transacional' AS Tipo_alerta FROM dbo.[ST_ALERT_MUDANCA_REPENTINA_01] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'OMC Bmf' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '08' AS INCISO, 'Transacional' AS Tipo_alerta FROM dbo.[ST_ALERT_OMC_BMF_01] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Omc Bvsp' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '08' AS INCISO, 'Transacional' AS Tipo_alerta FROM dbo.[ST_ALERT_OMC_01] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Patrimônio x Custódia' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '301' AS INCISO, 'Patrimonial' AS Tipo_alerta FROM dbo.[ST_ALERT_PATRIMONIO_CUSTODIA] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Patrimônio x Mov Cc' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '301' AS INCISO, 'Patrimonial' AS Tipo_alerta FROM dbo.[ST_ALERT_PATRIMONIO_MOVIMENTO] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Patrimônio x Netting' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '301' AS INCISO, 'Patrimonial' AS Tipo_alerta FROM dbo.[ST_ALERT_PATRIMONIO_NETTING] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Patrimônio x Transf. Custodia' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '301' AS INCISO, 'Patrimonial' AS Tipo_alerta FROM dbo.[ST_ALERT_PATRIMONIO_TRANF_CUST] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Procurador' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '301' AS INCISO, 'Cadastral' AS Tipo_alerta FROM dbo.[ST_ALERT_PROCURADOR_02] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Transf. Financeira 01' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '301' AS INCISO, 'Transacional' AS Tipo_alerta FROM dbo.[ST_ALERT_TRANSFERENCIA_FINANCEIRA_01] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Transf. Financeira 02' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '301' AS INCISO, 'Transacional' AS Tipo_alerta FROM dbo.[ST_ALERT_TRANSFERENCIA_FINANCEIRA_02] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Money Pass Bvsp' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '301' AS INCISO, 'Transacional' AS Tipo_alerta FROM dbo.[ST_ALERT_MONEYPASS_02] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Money Pass Bmf' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '08' AS INCISO, 'Transacional' AS Tipo_alerta FROM dbo.[ST_ALERT_MONEYPASS_BMF_02] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Lista Atenção' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '301' AS INCISO, 'Transacional' AS Tipo_alerta FROM dbo.[ST_ALERT_LISTA_ATENCAO] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Ranking daytrade Bvsp' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '301' AS INCISO, 'Transacional' AS Tipo_alerta FROM dbo.[ST_ALERT_RANKING_DAYTRADE_BVSP] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Ranking daytrade Bmf' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '301' AS INCISO, 'Transacional' AS Tipo_alerta FROM dbo.[ST_ALERT_RANKING_DAYTRADE_BMF] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Oscilação' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '08' AS INCISO, 'Transacional' AS Tipo_alerta FROM dbo.[ST_ALERT_OSCILACAO] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Omg Bvsp' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '08' AS INCISO, 'Transacional' AS Tipo_alerta FROM dbo.[ST_ALERT_OMG] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Omg Bmf' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '08' AS INCISO, 'Transacional' AS Tipo_alerta FROM dbo.[ST_ALERT_OMG_BMF] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Ativo Restrito' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '301' AS INCISO, 'Transacional' AS Tipo_alerta FROM dbo.[ST_ALERT_ATIVO_RESTRITO] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
UNION ALL
SELECT CONVERT(date, A.DATA) AS DT_PERIODO, CAST(A.CD_CLIENTE AS int) AS CD_CLIENTE, 'Vinculado ao Emissor' AS NOME_ALERTA, COUNT_BIG(1) AS QTD_MES, '08' AS INCISO, 'Transacional' AS Tipo_alerta FROM dbo.[ST_ALERT_EMISSOR_VINCULADO] A GROUP BY CONVERT(date, A.DATA), CAST(A.CD_CLIENTE AS int)
    ) X
    GROUP BY
        X.DT_PERIODO, X.CD_CLIENTE, X.NOME_ALERTA, X.INCISO, X.Tipo_alerta
) XX
LEFT JOIN (SELECT DISTINCT CD_CLIENTE, NM_CLIENTE, CD_CPFCGC FROM V_CLIENTE_TODOS) B
    ON XX.CD_CLIENTE = B.CD_CLIENTE
LEFT JOIN SCORE C
    ON XX.NOME_ALERTA = C.NAME
GROUP BY
    XX.DT_PERIODO, XX.CD_CLIENTE, XX.NOME_ALERTA, XX.INCISO,
    B.NM_CLIENTE, B.CD_CPFCGC, XX.Tipo_alerta;