CREATE VIEW [dbo].[V_BENEFICIARIOS]
AS

SELECT 
 CASE WHEN CPFCNPJ IS NULL THEN CAST(CPFCNPJ AS NUMERIC(20,0)) ELSE CPFCNPJ END AS CD_CLIENTE
,CASE 
    WHEN LEN(CPFCNPJ) = 11 THEN
        STUFF(STUFF(STUFF(CPFCNPJ, 4, 0, '.'), 8, 0, '.'), 12, 0, '-')
    WHEN LEN(CPFCNPJ) = 14 THEN
        STUFF(STUFF(STUFF(STUFF(CPFCNPJ, 3, 0, '.'), 7, 0, '.'), 11, 0, '/'), 16, 0, '-')
    ELSE CPFCNPJ
END AS CD_CPFCGC
,NOME AS NM_CLIENTE
,CASE WHEN LEN(CPFCNPJ) > 11 THEN 'PJ' ELSE 'PF' END TIPO
,[DATA_CRIACAO] AS DT_CRIACAO
FROM BENEFICIARIOS