CREATE VIEW [dbo].[VW_CPF_POR_ESTADO]
--WITH ENCRYPTION
AS


-- VIEW COM CPF POR ESTADO

SELECT SG_ESTADO, SUM(CD_CPFCGC) AS CD_CPFCGC FROM (
SELECT SG_ESTADO, COUNT(DISTINCT CD_CPFCGC) CD_CPFCGC FROM ST_DADOS_BASICOS_PF
WHERE SG_PAIS = 'BRA'
GROUP BY SG_ESTADO

UNION ALL

SELECT SG_ESTADO, COUNT(DISTINCT CD_CPFCGC) CD_CPFCGC  FROM ST_DADOS_BASICOS_PJ
WHERE SG_PAIS = 'BRA'
GROUP BY SG_ESTADO
) X GROUP BY SG_ESTADO