CREATE VIEW [dbo].[V_CLIENTE_TODOS]
--WITH ENCRYPTION
AS

SELECT DISTINCT 
B.CD_CLIENTE,
B.CD_CPFCGC,
MAX(B.IN_POLITICO_EXP)IN_POLITICO_EXP,
MAX(B.DS_ATIV)DS_ATIV,
MAX(C.RISCO)RISCO,
ISNULL(CASE WHEN MAX(D.CLASS_RISCO) = '1' THEN 'ALTO' 
	 WHEN MAX(D.CLASS_RISCO) = '2' THEN 'MÉDIO' 
	 WHEN MAX(D.CLASS_RISCO) = '3' THEN 'BAIXO' ELSE '' END,'NÃO INFORMADO') AS PERFIL,
(IN_PESS_VINC) IN_PESS_VINC,
B.CD_ASSESSOR,
B.NM_ASSESSOR,
CONVERT(VARCHAR,MAX(B.DT_ATUALIZ),103) DT_ATUALIZ, 
'PF' TIPO,
B.VL_OPERACIONAL1, 
MAX(B.DT_ATUALIZ) DT_ATUALIZ_DATA, 
MAX(b.DT_CRIACAO) DT_CRIACAO,
MAX(B.NM_CLIENTE) NM_CLIENTE, 
MAX(B.TP_SITUAC) TP_SITUAC, 
B.IN_SITUAC,MAX(B.TP_CLIENTE)TP_CLIENTE,
CASE WHEN MAX(IND_CAD_SIMP) ='S' THEN 'SIMPLIFICADO' 
	 WHEN MAX(IND_CAD_SIMP) ='N' THEN 'COMPLETO' ELSE 'NÃO INFORMADO' END INR, 
MAX(B.IN_PROCUR)IN_PROCUR,
max(b.DT_VALIDADE)DT_VALIDADE,
MAX(B.IN_PRINCIPAL) IN_PRINCIPAL,
MAX(B.NM_EMIT_ORDEM) NM_EMIT_ORDEM,
MAX(ISNULL(B.CD_CPFCGC_EMIT,0)) CD_CPFCGC_EMIT,MAX(DS_TIPO_CLIENTE)DS_TIPO_CLIENTE,
MAX(DS_NACION)DS_NACION,MAX(B.DT_ULT_OPER)DT_ULT_OPER,
'SINACOR' FONTE
,CPFCNPJ
,(SELECT MAX(CD_PARAMETRO) FROM ST_CLIENTE_PARAMETROS WHERE DS_PARAMETRO = 'CD_CONTRAPARTE') CD_CONTRAPARTE
,DATEDIFF(YEAR,MAX(DT_NASC_FUND),CAST(GETDATE() AS DATE)) AS IDADE
,NM_CIDADE
,SG_ESTADO

FROM ST_DADOS_BASICOS_PF B
LEFT OUTER JOIN ST_PROFISSAO_RISCO C ON B.DS_ATIV = C.PROFISSAO
LEFT OUTER JOIN ST_PERFIL_CADASTRO D ON B.CD_cPFCGC = D.CD_CPFCGC
 
GROUP BY  B.CD_CLIENTE,B.CD_CPFCGC, B.VL_OPERACIONAL1, B.IN_SITUAC,IN_PESS_VINC,B.CD_ASSESSOR,B.NM_ASSESSOR,CPFCNPJ,NM_CIDADE,SG_ESTADO
 

UNION ALL

SELECT DISTINCT 
B.CD_CLIENTE,
B.CD_CPFCGC,
MAX(B.IN_POLITICO_EXP)IN_POLITICO_EXP,
ISNULL(DS_TIPO_CLIENTE,'OUTROS'),
MAX(RISCO) RISCO,
ISNULL(CASE WHEN MAX(D.CLASS_RISCO) = '1' THEN 'ALTO' 
	 WHEN MAX(D.CLASS_RISCO) = '2' THEN 'MÉDIO' 
	 WHEN MAX(D.CLASS_RISCO) = '3' THEN 'BAIXO' ELSE '' END,'NÃO INFORMADO') AS PERFIL,
IN_PESS_VINC,
B.CD_ASSESSOR,
B.NM_ASSESSOR,
CONVERT(VARCHAR,MAX(B.DT_ATUALIZ),103) DT_ATUALIZ, 
'PJ' TIPO,
B.VL_OPERACIONAL1,
MAX(B.DT_ATUALIZ) DT_ATUALIZ_DATA, 
MAX(b.DT_CRIACAO) DT_CRIACAO,
MAX(B.NM_CLIENTE) NM_CLIENTE,
MAX(B.TP_SITUAC) TP_SITUAC, 
B.IN_SITUAC,MAX(B.TP_CLIENTE)TP_CLIENTE,CASE WHEN MAX(IND_CAD_SIMP) ='S' THEN 'SIMPLIFICADO' 
	 WHEN MAX(IND_CAD_SIMP) ='N' THEN 'COMPLETO' ELSE 'NÃO INFORMADO' END INR, 
MAX(B.IN_PROCUR)IN_PROCUR,
max(b.DT_VALIDADE)DT_VALIDADE,
MAX(B.IN_PRINCIPAL) IN_PRINCIPAL,
MAX(B.NM_EMIT_ORDEM) NM_EMIT_ORDEM,
MAX(ISNULL(B.CD_CPFCGC_EMIT,0)) CD_CPFCGC_EMIT,MAX(DS_TIPO_CLIENTE)DS_TIPO_CLIENTE,
'-' AS DS_NACION,MAX(DT_ULT_OPER)DT_ULT_OPER, 'SINACOR' FONTE,CPFCNPJ
,(SELECT MAX(CD_PARAMETRO) FROM ST_CLIENTE_PARAMETROS WHERE DS_PARAMETRO = 'CD_CONTRAPARTE') CD_CONTRAPARTE
,DATEDIFF(YEAR,MAX(DT_NASC_FUND),CAST(GETDATE() AS DATE)) AS IDADE
,NM_CIDADE
,SG_ESTADO

FROM ST_DADOS_BASICOS_PJ B
LEFT OUTER JOIN ST_PROFISSAO_RISCO C ON B.DS_TIPO_CLIENTE = C.PROFISSAO 
LEFT OUTER JOIN ST_PERFIL_CADASTRO D ON B.CD_cPFCGC = D.CD_CPFCGC

GROUP BY  B.CD_CLIENTE,B.CD_CPFCGC, B.VL_OPERACIONAL1, B.IN_SITUAC,IN_PESS_VINC,B.CD_ASSESSOR,B.NM_ASSESSOR, 
DS_TIPO_CLIENTE,CPFCNPJ,NM_CIDADE,SG_ESTADO